### ISSUE TITLE
ocamlyacc: wrong file and line information for types in %type declarations

### ISSUE THREAD

**Issue by DemiMarie** [ocaml/ocaml#10001]
If a type in a %type declaration causes a compiler error, the error message will point to the generated code, rather than the `.mly` source.  This is because ocamlyacc fails to generate line directives for it.

**Comment by dra27** [comment]
I started a fix - it's bigger than I expected, as it also extends to the generated .mli file, which doesn't have `#` directives currently. I'll push it when done.

**Comment by xavierleroy** [comment]
Please keep in mind that ocamlyacc is not the way forward -- Menhir is.  So, small usability fixes on ocamlyacc are OK, but big changes may be a waste of time, as serious OCaml users should already be using Menhir instead.

**Comment by DemiMarie** [comment]
Should still be reproducible.

**Comment by DemiMarie** [comment]
Still a problem unless something has changed.

**Comment by DemiMarie** [comment]
@dra27 do you have a draft of your fix anywhere?

**Comment by dra27** [comment]
I'm afraid I don't appear to (it looks like the worktree I was using might have got overwritten before committing)

**Comment by DemiMarie** [comment]
Darn!  How long did it take to implement?

**Comment by dra27** [comment]
I don't think I'd spent more than an hour or so on it when I commented above in https://github.com/ocaml/ocaml/issues/10001#issuecomment-720402007 (but I can't remember, I'm afraid!)

**Comment by DemiMarie** [comment]
> I don't think I'd spent more than an hour or so on it when I commented above in [#10001 (comment)](https://github.com/ocaml/ocaml/issues/10001#issuecomment-720402007) (but I can't remember, I'm afraid!)

Would you mind implementing it again?  Feel free to say “no” if you don’t want to.

**Comment by dra27** [comment]
I'm not going to have any time in the foreseeable future to come back to this one, I'm afraid!

**Comment by DemiMarie** [comment]
@dra27 don’t worry, fix turned out to be easy: #11728.
