### ISSUE TITLE
Warn on trailing semicolons

### ISSUE THREAD

**Issue by DemiMarie** [ocaml/ocaml#10003]
They lead to bad error messages in many cases.

**Comment by dra27** [comment]
What examples do you have in mind?

**Comment by DemiMarie** [comment]
None come to mind right away, but I remember that they were a problem when I was trying to remove `;;` from the compiler.

**Comment by hhugo** [comment]
Is this what you are takling about ? where removing `;;` would result in a parse error ?
```ocaml
let _ =
  e1;
  e2;
  e3;
;;

let () = e4
```

**Comment by DemiMarie** [comment]
I believe it was.  The parse error would not show up until after e4.

**Comment by dra27** [comment]
So a warning for _toplevel_ expressions. That could be fine, I was worried you meant things like `(e1; e2; e3;)` which would not be fine to add a warning to!

**Comment by johnwhitington** [comment]
> Is this what you are takling about ? where removing `;;` would result in a parse error ?
> 
> ```ocaml
> let _ =
>   e1;
>   e2;
>   e3;
> ;;
> 
> let () = e4
> ```

This error caught me out frequently when I was learning OCaml. I didn't use the double semicolon except in the top level. So when both of the functions are, say, 20 lines long, this error can be baffling the first time you see it.

Typically, it happens when removing debug printing. For example, imagine if e3 above were `print_endline "finished!"`, so we remove it, and then get an inscrutable error.

**Comment by stedolan** [comment]
This issue is definitely annoying, but maybe what we need is a better syntax error when this occurs, rather than a warning on the non-problematic uses of trailing semicolons?

**Comment by dra27** [comment]
Possibly, although given that these days we advocate `;;` as being unnecessary outside the toplevel, a warning that you're using a `;;` non-redundantly might be more useful if your aim is to remove `;;` from a codebase?

**Comment by DemiMarie** [comment]
Still a problem last I checked.

**Comment by DemiMarie** [comment]
Still an issue.
