### ISSUE TITLE
Warning on non-delimited pattern matches

### ISSUE THREAD

**Issue by DemiMarie** [ocaml/ocaml#10002]
If a pattern match is nested in another pattern match, and is not delimited (either with parenthesis or with `begin ... end`), we should issue a warning.

**Comment by dra27** [comment]
See prior discussions in https://github.com/ocaml/ocaml/pull/716, https://github.com/ocaml/ocaml/pull/722 and https://github.com/ocaml/ocaml/issues/9034. I don't think your suggestion differs from #716, but feel free to re-open if you disagree!
