### ISSUE TITLE
Add a .messages file for Menhir

### ISSUE THREAD

**Issue by DemiMarie** [ocaml/ocaml#10020]
I think we can all agree that better syntax error messages would be nice.

**Comment by let-def** [comment]
I am working on improving error messages. It is a research project, I cannot tell exactly when it will be ready, but the situation should be better in a few months from now.

My solution is not directly based on `.messages` but could be seen as a generalization.

**Comment by DemiMarie** [comment]
Still open unless @let-def has changed something.

**Comment by let-def** [comment]
I confirm that I am still working on that topic (though this is not my main project and needs a lot more work)

**Comment by DemiMarie** [comment]
Still an issue.  @let-def any updates?

**Comment by gasche** [comment]
I can provide an update from my (imperfect) understanding: @let-def has indeed managed to finish a first prototype of an improved approach to error messages (I would hazard the guess that the result is in the [lrgrep](https://github.com/let-def/lrgrep) repository). But currently there is no active work on upstreaming support for OCaml error messages. I hope that @let-def or people using his work will actually try to upstream something, but probably not before a few months.

**Comment by lpw25** [comment]
@let-def has been working on upstreaming lrgrep into merlin first, which is a slightly easier place to experiment with things. We're in the process of getting set up to try this prototype out inside Jane Street.
