### ISSUE TITLE
Mutable record field updates get lost when in partial application

### ISSUE THREAD

**Issue by IagoAbal** [ocaml/ocaml#10032]
I observed a regression when upgrading from OCaml 4.04.2 to a more recent version, after some debugging I came to the conclusion that this is related to mutable record fields and partial application, and the behavior changed from 4.05.0 to 4.06.0. Here you have a minimal example (simply `ocamlopt main.ml && ./main`):

```ocaml
type norm_env =
  { mutable k : int; }

let push_local ({k;} as env) _ =
  env.k <- k + 1;
  Printf.eprintf "push_local %d --> %d\n" k env.k

let pop_local ({k;} as env) _ =
  env.k <- k - 1;
  Printf.eprintf "pop_local %d --> %d\n" k env.k

let bug() =
  let env = { k=0; } in
  Printf.eprintf "BUG?\n";
  List.iter (push_local env) [1; 2];        (* BUG? *)
  List.iter (pop_local env) [1; 2]          (* BUG? *)

let works() =
  let env = { k=0; } in
  Printf.eprintf "WORKS\n";
  List.iter (fun x -> push_local env x) [1; 2];   (* WORKS *)
  List.iter (fun x -> pop_local env x) [1; 2]     (* WORKS *)

let _ =
  bug();
  works()

(* OCaml 4.05.0
BUG?
push_local 0 --> 1
push_local 1 --> 2
pop_local 2 --> 1
pop_local 1 --> 0
WORKS
push_local 0 --> 1
push_local 1 --> 2
pop_local 2 --> 1
pop_local 1 --> 0
 *)

(* OCaml 4.06.0
BUG?
push_local 0 --> 1
push_local 0 --> 1
pop_local 1 --> 0
pop_local 1 --> 0
WORKS
push_local 0 --> 1
push_local 1 --> 2
pop_local 2 --> 1
pop_local 1 --> 0
 *)
```

**Comment by gasche** [comment]
I haven't investigated your example in details yet, but this looks like a consequence of #1308, which changed the way mutable fields and partial-application interact together. This may break code, but the change was necessary because the previous behavior did not correspond to the language specification and program-reasoning expectations.

**Comment by lthls** [comment]
Starting from 4.12.0 you will also be able to use warning 68 to check for these problems (see #9641 and #9751).
It's not active by default though.

**Comment by dra27** [comment]
Out of curiosity, where does interpreting 

```ocaml
let push_local ({k;} as env) _ =
...
```
as
```ocaml
let push_local env _ =
  let {k;} = env in
  ...
```
fall over semantically?

**Comment by xavierleroy** [comment]
Remove the syntactic sugar:
```
let push_local = fun env -> let k = env.k in fun _ -> ...
```
vs
```
let push_local = fun env -> fun _ -> let k = env.k in ...
```
In the former code, the value of `env.k` is read before the passing of the second argument, while in the latter code it is read after.

**Comment by IagoAbal** [comment]
Sorry, I now see that I wasn't the first one to encounter this issue  (#7789). Then I guess I can only fix my code. Thanks a lot for the clarification!
