### ISSUE TITLE
Prompt style options

### ISSUE THREAD

**Issue by OrionRandD** [ocaml/ocaml#10059]
Is it possible to increment a feature in ocaml for having other prompt styles?
The thing is that, this prompt "#"  - hash style - does not goes well with GNU/Linux, when we use the "root user", because the root user prompt is also a hash.
Apart from that, it is not a beautiful prompt at all...
Perhaps:

o->
oc-> 
O-> 
->
>
or other thing 
could be a better option...
thx a lot...

**Comment by nojb** [comment]
You may be interested in [`utop`](https://github.com/ocaml-community/utop) which is more full-featured than the standard `ocaml` toplevel; in particular you can customize its prompt to your heart's content.

**Comment by OrionRandD** [comment]
@nojb thx for pointing me there --> utop

**Comment by OrionRandD** [comment]
their documentation is too vague
You can customize the prompt of utop by setting the reference UTop.prompt
And even in  "man utop"
There is no example about setting it...

**Comment by redianthus** [comment]
Something like:

```
utop # UTop.prompt := "bla";;
Line 1, characters 15-20:
Error: This expression has type string but an expression was expected of type
         LTerm_text.t React.signal
```

But you'll have to figure out what's a ` LTerm_text.t React.signal` yourself as I have no idea. Anyway, I believe you'd better ask on the utop issue tracker.

**Comment by OrionRandD** [comment]
I have asked them...
Waiting...
thx

**Comment by hyphenrf** [comment]
@OrionRandD 
To set a prompt, you need to convert its string to the type utop expects like so:
`UTop.prompt := Lwt_react.S.const (LTerm_text.of_utf8 "> ")`
Plug this in your init file and you should be good to go.
