### ISSUE TITLE
toplevel not recognizing newly created files

### ISSUE THREAD

**Issue by quakerquickoats** [ocaml/ocaml#10087]
Loading toplevel ("ocaml") works great to #mod_use or #load files. However, when creating a new file while session is open, we get "Cannot load 'xyz.ml'" for either command or similar, until restarting the toplevel interpreter. This is entirely reproducable, and we are using 4.11.1 with opam.

**Comment by gasche** [comment]
Indeed. A quick testing indicate that this used to work until 4.07.1, and stopped working in 4.08.0. This sounds worth fixing.

**Comment by nojb** [comment]
This is probably due to the fact that the content of include directories is read once at startup for efficiency (I believe this behaviour was introduced in #2041)

cc @jeremiedimino

**Comment by gasche** [comment]
This also looks like something Merlin people have thought about: cc @trefis @let-def

**Comment by dra27** [comment]
This is indeed a consequence of #2041. Given that it's only an error path, I expect this just requires tweaking `Load_path.find` to fall-back to searching `Load_path.dirs` (and updating the cache if it finds it), but that behaviour needs to be selectable so that only the toplevel does it (an optional parameter should do it).

The dual case is broken as well (or at least the error message is inconsistent):

```
$ echo 'let answer = 42' > t.ml
$ ocaml
        OCaml version 4.11.1

# #use "t.ml";;
val answer : int = 42
# ^Z
[1]+  Stopped                 ocaml
$ rm t.ml ; fg
ocaml
# #use "t.ml";;
Error: I/O error: t.ml: No such file or directory
# #use "u.ml";;
Cannot find file u.ml.
```

**Comment by quakerquickoats** [comment]
so what can we do now? continue to reload utop/toplevel until it is fixed
officially ? it is as proven definitely reproducible but it sounds like it
takes some architecture restructuring which is concerning.

**Comment by dra27** [comment]
The fix shouldn't be too difficult. However, let's not forget in terms of urgency that it's broken for 2½ years! It's not likely to get back-ported (well, certainly not to 4.07) so I expect utop is going to want to work around this for older toplevels. It might be possible for utop to second-guess the toplevel and in this case run `Load_path.(init (get_paths ()))` which I think should cause a full rescan of all the directories.

**Comment by ghost** [comment]
Another idea would be to clear the cache regularly in the toplevel, or even not use a cache at all. BTW, a workaround in the meantime is to do `#use "./t.ml"`. Adding `./` will force the toplevel to do a full search and skip the cache.

**Comment by gasche** [comment]
That's a good suggestion, clearing the cache on all toplevel directives should be enough, simple to implement and not so ugly in the code. (It's also no less efficient than the current behavior for all single-script use-cases, unlike the idea of clearing the cache on each phrase.)

**Comment by dra27** [comment]
I have a feeling that clearing the cache on all directives will be noticeable on your least favourite platform. During some previous (incomplete) work profiling the compiler on Windows, I found that directory rescanning which occurs in `ocamlopt -c foo.ml bar.ml` (i.e. there's some resetting which occurs when you compile multiple files) is significant if you have a large number of code files, and the Win32 API/CRT functions showed up in traces (not dominating, but wasting significant ms of the execution time).

It wouldn't surprise with with a perfectly reasonable load path you'd notice the delay returning to the prompt after a toplevel directive.

**Comment by xavierleroy** [comment]
See #10138 for a two-line fix.
