### ISSUE TITLE
Syntax for simple variable definition not covered in Grammar?

### ISSUE THREAD

**Issue by ananthp** [ocaml/ocaml#10088]
The [language reference](https://ocaml.org/releases/4.11/htmlman/language.html) doesn't seem to have any construct equivalent to the simple let binding to create a variable
```
let x = 10
```

[Expressions](https://ocaml.org/releases/4.11/htmlman/expr.html) has this:

```
let [rec] let-binding  { and let-binding } in  expr  
```

Here, `in expr` is not optional, so doesn't match the variable binding above. This is understandable `let x=10` isn't an expression while `let ... in expr` is one.

[let-binding](https://ocaml.org/releases/4.11/htmlman/expr.html#let-binding) doesn't fully describe it either, as it doesn't include the keyword `let`.

**Comment by yallop** [comment]
It's in [7.11](https://ocaml.org/releases/4.11/htmlman/modules.html#ss%3Amexpr-structures), e.g.:

> **Value definitions**
> 
> A value definition `let [rec] let-binding  { and let-binding }` bind value names in the same way as a `let … in …` expression

**Comment by ananthp** [comment]
> Module expressions are the module-level equivalent of value expressions

Is it appropriate that it's listed only under modules? Why not in [7.2 Values](https://ocaml.org/releases/4.11/htmlman/values.html)

**Comment by yallop** [comment]
It's listed under modules because value definitions are components of modules: every value definition `let x = e` is part of a module expression.

_7.2 Values_ is about the objects that are manipulated by programs at runtime, not about the definitions that make up programs.

**Comment by gasche** [comment]
My understanding is that there is no bug (or clear documentation issue) discussed here, but more of a discussion about the ordering of concepts in the manual. It is completely fine to ask for clarifications here, and we could possibly think of whether clarifications should go to the main documentation; but I am "closing" this to not keep it marked as an issue in the tracker.
