### ISSUE TITLE
Allocate afl_area_initial dynamically

### ISSUE THREAD

**Issue by dra27** [ocaml/ocaml#10117]
As noted in https://github.com/ocaml/ocaml/pull/10107#discussion_r550780219, the runtime reserves 64KB for AFL, regardless of whether it's used or even supported.

Assuming it doesn't affect the operation of AFL, `caml_setup_afl` should allocate the buffer dynamically on first call.

**Comment by xavierleroy** [comment]
I have a fix in some branch somewhere.  Will come back to it after the Multicore merge.

**Comment by dra27** [comment]
It's in your afl-dynamic-allocation branch, apparently 🙂
