### ISSUE TITLE
ocamldebug's next_1 command not works properly on tailcall-opt case

### ISSUE THREAD

**Issue by hackwaly** [ocaml/ocaml#10110]
I'm the author of ocamlearlybird - an ocaml debug adapter for vscode. I found that ocamldebug's next_1 implemention has bug. It doesn't work properly on tailcall-opt case.

https://github.com/ocaml/ocaml/blob/trunk/debugger/time_travel.ml#L586
https://github.com/ocaml/ocaml/blob/49aa87c316c441aa47974e8e9191a5a7e6d03d9a/debugger/time_travel.ml#L586-L604

Here's relevant code in ocamlearlybird

```OCaml
    let internal_step_over () =
      let%lwt stack_pos1, pc1 = Debugcom.get_frame conn in
      let%lwt step_in_status = internal_step_in () in
      let%lwt stack_pos2, pc2 = Debugcom.get_frame conn in
      let ev1 = find_event agent pc1 in
      let ev2 = find_event agent pc2 in
      (* tailcallopt case *)
      let is_tco () =
        if stack_pos2 - ev2.ev.ev_stacksize = stack_pos1 - ev1.ev.ev_stacksize
        then ev2.ev.ev_info = Event_function
        else false
      in
      let is_entered () =
        stack_pos2 - ev2.ev.ev_stacksize > stack_pos1 - ev1.ev.ev_stacksize
      in
      if is_entered () || is_tco () then internal_step_out ()
      else Lwt.return step_in_status
    in
```

Without consider of tailcall-opt case. It's buggy:

https://user-images.githubusercontent.com/540298/103441664-6f36eb00-4c8a-11eb-96e6-43b759c4917a.mov

You can see next command behaves as step_in at tailcall point.
 
## Expected behavior

Next command should step over, not step in at tailcall point.

## Propose to change the implementation of `next_1`

Add tailcall-opt check, if it is at tailcall point and tailcall-opt happens, call `finish` to exit current frame as it's reused by tailcall-opt

**Comment by hackwaly** [comment]
Code fix should be simple. Should I make a pull request? I'm not familar with contributing to ocaml codebase.

**Comment by xavierleroy** [comment]
Why don't you write down
- which behavior you expect
- how you propose to change the implementation of "next" to implement it.
 
Then we'll happily guide you through a pull request.

**Comment by hackwaly** [comment]
> Why don't you write down
> 
> * which behavior you expect
> * how you propose to change the implementation of "next" to implement it.
> 
> Then we'll happily guide you through a pull request.

Thank you! I'll edit the description of issue soon.

**Comment by hackwaly** [comment]
> > Why don't you write down
> > 
> > * which behavior you expect
> > * how you propose to change the implementation of "next" to implement it.
> > 
> > Then we'll happily guide you through a pull request.
> 
> Thank you! I'll edit the description of issue soon.

@xavierleroy Done.

**Comment by xavierleroy** [comment]
OK, I see better now, thanks a lot.

I agree that `next` should act like `finish` if we are at a tail call.

As to contributing a pull request: there is an extensive guide here: https://github.com/ocaml/ocaml/blob/trunk/CONTRIBUTING.md

It's a lot to read, but to get you started:
- You need to make a pull request in this ocaml/ocaml repository against the default branch ("trunk").
- Try to keep the change small.  Small changes get reviewed much more quickly and don't need a CLA to be signed.
- If you can, try to add a test in `testsuite/tests/tool-debugger`.  You can take inspiration from the existing tests.

**Comment by gasche** [comment]
@hackwaly let me know that he will not have more time to spend on ocamldebug-related topics. Anyone should feel encouraged to fix this issue; I'm tentatively assigning myself, but please feel free to offer a PR anyway.
