### ISSUE TITLE
[RFC] Improve Contributions Guidelines for the Stdlib

### ISSUE THREAD

**Issue by bschommer** [ocaml/ocaml#10128]
My experience when adding functions to the standard library are that a lot of the discussions are also around names and parameter ordering. In order to simplify the process here I would suggest adding a few lines to the Contributions document mentioning for example that for names and API one should take a look at some other popular standard libraries in OCaml, such as for example Base, Batteries, etc. ideally with a link to their repositories or other popular programming languages.

**Comment by gasche** [comment]
Yes, why not? Would you like to propose a Pull Request for this change?

`CONTRIBUTING.md` is already a bit large. Adding to it is okay, but we could also have a file `stdlib/CONTRIBUTING.md` for contribution advice specific to the stdlib (just like we have HACKING.adoc files for some subdirectories), with a link from the main CONTRIBUTING.md file.

**Comment by bschommer** [comment]
I'm give it a try, however I'm not the best at writing documentation.

**Comment by bschommer** [comment]
PR is merged, I think this is already some improvement.
