### ISSUE TITLE
C error building eventlog.c

### ISSUE THREAD

**Issue by skaller** [ocaml/ocaml#10147]
MacOS, BugSur:
```
~/ocaml>gcc --version
gcc (Homebrew GCC 9.1.0) 9.1.0
```
Note, ./configure guessed the wrong compiler. On a Mac, clang should always be chosen, full stop.
I will rebuild with clang. But for now:
```
gcc -c -O2 -fno-strict-aliasing -fwrapv -Wall -Wdeclaration-after-statement -Werror -fno-common -fexcess-precision=standard -fno-tree-vrp -g  -D_FILE_OFFSET_BITS=64 -D_REENTRANT -DCAML_NAME_SPACE   -DCAMLDLLIMPORT= -DCAML_INSTR  -o eventlog.bi.o eventlog.c
eventlog.c: In function 'time_counter':
eventlog.c:108:3: error: ISO C90 forbids mixed declarations and code [-Werror=declaration-after-statement]
  108 |   uint64_t now = mach_absolute_time ();
      |   ^~~~~~~~
cc1: all warnings being treated as errors
make[2]: *** [eventlog.bi.o] Error 1
make[1]: *** [coldstart] Error 2
make: *** [world.opt] Error 2
```
If C99 is required, the configure script should have bugged out I think.

**Comment by skaller** [comment]
FYI with CC=clang, the error above does not occur.

**Comment by dra27** [comment]
Just confirming that you were building a Git clone, not a release tarball?

> Note, ./configure guessed the wrong compiler. On a Mac, clang should always be chosen, full stop.

Why?

> If C99 is required, the configure script should have bugged out I think.

The issue appears to be a bug in clang.

**Comment by skaller** [comment]
Confirmed, building from the Git repo. I've had trouble in the past with brew, opam, etc etc but the raw Ocaml build script is excellent and has worked for me for many years. Congrats.

In a standard Mac, gcc is linked to clang anyhow. On my system I have a real gcc installed by brew. However the system compiler is not a stock clang, but one Apple has messed with:
```
~/felix>clang --version
Apple clang version 12.0.0 (clang-1200.0.32.21)
Target: x86_64-apple-darwin20.2.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
~/felix>ls -lasp `which clang`
24 -rwxr-xr-x  1 root  wheel  137536  1 Jan  2020 /usr/bin/clang
```
Some Apple stuff won't work with the stock clang, so basically a developer on Apple doing anything Apple related has to use the Xcode supplied clang. So this should be the default. IMHO.

Since the Ocaml build uses the "error if you declare a variable after an executable statement" switch you're probably right, its a bug in Apple clang that it doesn't respect the switch.
