### ISSUE TITLE
Multiline OCaml code samples in manual all slightly malformed

### ISSUE THREAD

**Issue by johnwhitington** [ocaml/ocaml#10142]
(This is a bug report rather than a PR because I've spent too long trying to fix it, and failed. It's probably easy for someone who knows the code). The correct formatting should be, to pick the first multiline code from the first chapter of the tutorial:

```
# let rec fib n =
    if n < 2 then n else fib (n-1) + fib (n-2);;
```
(Hash on first line, space after hash, indenting otherwise correct)

But currently we see:

TEXT manual
```
#let rec fib n =
#  if n < 2 then n else fib (n-1) + fib (n-2);;
```
(Hash on every line, no space after hash on first line)

HTML manual
```
# let rec fib n =
   if n < 2 then n else fib (n-1) + fib (n-2);;
val fib : int -> int = <fun>
```
(Adds the hash with css `::before` mechanism, so indenting now wrong)

PDF manual
```
# let rec fib n =
#   if n < 2 then n else fib (n-1) + fib (n-2);;
```
(Correct indenting, but hash on every line, which top level doesn't do)

**Comment by Octachron** [comment]
If there is an agreement in principle that we want to switch to an unified rendering between all outputs, I can implement the changes. The best way is probably to directly emit the right output from `caml_tex` and remove one layer of macros from the manual.

**Comment by gasche** [comment]
I don't understand what you have in mind with "unified rendering", but the "correct formatting" proposed by @johnwhitington looks nicer to me that the three existing renderings. I don't know how non-toplevel code blocks are rendered; are the current toplevel-rendering choices are related to those?

**Comment by Octachron** [comment]
Currently each line of example is prefixed with a `\?` macro:
```latex
\begin{camlinput}
$\?$let rec fib n =
$\?$  if n < 2 then n else fib (n-1) + fib (n-2);;
\end{camlinput}
```
Then the latex and text backends redefine `\?` to `# ` in the toplevel examples. 
The current html defines this macro away, and adds `#` with a css trick to the toplevel examples.
Previously, the html backend was redefining `\?` on the fly to make it first expand to `# ` and then to `  `.

If we want to remove all the customization above, we could simply emit the desired output:
```latex
\begin{camlinput}
# let rec fib n =
    if n < 2 then n else fib (n-1) + fib (n-2);;
\end{camlinput}
```
for toplevel examples and
```latex
\begin{camlinput}
let rec fib n =
  if n < 2 then n else fib (n-1) + fib (n-2);;
\end{camlinput}
```
in verbatim mode.

**Comment by gasche** [comment]
Yes, that sounds good to me.
