### ISSUE TITLE
boot/ocamlrun - unterminated quoted string

### ISSUE THREAD

**Issue by nickbetteridge** [ocaml/ocaml#10160]
I'm trying to build a 4.12 arm runtime on intel so that I can use the ocaml libs on a baremetal arm kernel

```./configure --prefix /tmp/install --build i386-linux --host aarch64-unknown-linux-gnu CC='aarch64-linux-gnu-gcc' AS='aarch64-linux-gnu-as' ASPP='aarch64-linux-gnu-gcc -c'```

which gives an output of 

<snip>

```
aarch64-linux-gnu-gcc -c -O2 -fno-strict-aliasing -fwrapv -Wall -Wdeclaration-after-statement -Werror -fno-common -fexcess-precision=standard -ffunction-sections -g  -D_FILE_OFFSET_BITS=64 -D_REENTRANT -DCAML_NAME_SPACE   -DCAMLDLLIMPORT=  -o prims.o prims.c
aarch64-linux-gnu-gcc -O2 -fno-strict-aliasing -fwrapv -Wall -Wdeclaration-after-statement -Werror -fno-common -fexcess-precision=standard -ffunction-sections -g  -Wl,-E -o ocamlrun prims.o libcamlrun.a -lm -ldl  -lpthread 
aarch64-linux-gnu-gcc -O2 -fno-strict-aliasing -fwrapv -Wall -Wdeclaration-after-statement -Werror -fno-common -fexcess-precision=standard -ffunction-sections -g  -Wl,-E -g -o ocamlrund prims.o libcamlrund.a -lm -ldl  -lpthread 
aarch64-linux-gnu-gcc -O2 -fno-strict-aliasing -fwrapv -Wall -Wdeclaration-after-statement -Werror -fno-common -fexcess-precision=standard -ffunction-sections -g  -Wl,-E -o ocamlruni prims.o libcamlruni.a -lm -ldl  -lpthread 
make[2]: Leaving directory '/home/nick/tmp/ocaml/runtime'
cp runtime/ocamlrun boot/ocamlrun
make -C stdlib  \
  CAMLC='$(BOOT_OCAMLC) -use-prims ../runtime/primitives' all
make[2]: Entering directory '/home/nick/tmp/ocaml/stdlib'
../boot/ocamlrun ../boot/ocamlc -use-prims ../runtime/primitives -strict-sequence -absname -w +a-4-9-41-42-44-45-48 -g -warn-error A -bin-annot -nostdlib -principal -safe-string -strict-formats  -nopervasives -c camlinternalFormatBasics.mli
../boot/ocamlrun: 1: Syntax error: Unterminated quoted string
make[2]: *** [Makefile:201: camlinternalFormatBasics.cmi] Error 2
make[2]: Leaving directory '/home/nick/tmp/ocaml/stdlib'
make[1]: *** [Makefile:143: coldstart] Error 2
make[1]: Leaving directory '/home/nick/tmp/ocaml'
make: *** [Makefile:274: world.opt] Error 2
```

Very much out of my comfort zone here :) - suspect this is an error on my part - please ask for any other info - thanks, Nick

**Comment by nickbetteridge** [comment]
ah, configure, of course, followed by a ```make world.opt```

**Comment by nickbetteridge** [comment]
in addition, the tree was cloned from https://github.com/ocaml/ocaml and 4.12 checked out

**Comment by xavierleroy** [comment]
OCaml doesn't support cross-compilation currently, even though this is being worked on.

In your run, `boot/ocamlrun` was built as an AArch64 ELF executable, because that's what you requested, but it needs to be run on the host machine during compilation of the OCaml system, as in the line `../boot/ocamlrun ../boot/ocamlc -use-prims`.  The x86 kernel doesn't recognize `boot/ocamlrun` as a machine executable, so it calls `/bin/sh` to run it as a shell script, and nothing good comes out of this.

Your best bet is to build on an AArch64 machine.  A Raspberry Pi 4 with a 64-bit distro (e.g. Ubuntu 20.04) works nicely.

You can also try to set up an AArch64 virtual machine on your x86 host, but it will be slow.

**Comment by nickbetteridge** [comment]
Thanks for the very helpful insight, and, luckily, I have a rpi4 to hand! Thanks again

**Comment by xavierleroy** [comment]
Another option (but I never tried it, so I cannot swear it will work): register QEMU as the "executor" for AArch64 ELF executables on your x86 Linux host.  More details here: https://wiki.debian.org/QemuUserEmulation .  This way, calls to `boot/ocamlrun` during the build will work, albeit a bit slowly.
