### ISSUE TITLE
Manual built with trunk lacks syntax colouring on examples

### ISSUE THREAD

**Issue by johnwhitington** [ocaml/ocaml#10163]
See, for example, this image: https://coherentpdf.com/tmp/colours.png

On the left, manual built with trunk. On the right, the 4.11 manual as uploaded to caml.inria.fr.

Was this intentional? It looks like a downgrade to me....

**Comment by Octachron** [comment]
This is an accident: when merging the api and manual side of the documentation generation, I forgot to pick the `-colorize-code` option. I would propose to fix that in #9997 to avoid overriding the fix here.

**Comment by johnwhitington** [comment]
Ok, so does that mean it will be colorized correctly for the 4.12 release?

**Comment by Octachron** [comment]
Yes, the change in the documentation generation that introduced the bug is only present in trunk.
