### ISSUE TITLE
New HeVeA fixes bug in UTF8 plain text manual

### ISSUE THREAD

**Issue by johnwhitington** [ocaml/ocaml#10162]
I have been looking at why the file manual.txt, the plain text form of the reference manual, is not rendering some characters correctly.

The root cause was a bug in HeVeA -- some spurious characters were being ouput, leading to text editors failing to recognise the file as UTF8. They were, therefore, trying to render it as ASCII, with predictable results.

Luc Maranget has kindly helped to diagnose the problem, and has produced a new release, v2.3.5, which can be obtained at https://github.com/maranget/hevea , and soon in OPAM. This should be installed on the machine which generates manual.txt for OCaml releases.

Using this new version of HeVeA, the manual.txt file now loads correctly in Windows  Notepad, OS X TextEdit, vim etc, showing all accents and special characters correctly.

**Comment by Octachron** [comment]
Yes, the issue was on Hevea side. It is good to know that fixing it will no longer require to use the development version of Hevea. Thanks.
