### ISSUE TITLE
Backtrace says Hashtbl.find throwing hd

### ISSUE THREAD

**Issue by skaller** [ocaml/ocaml#10172]
I have a weird bug where I get this output:
```
~/felix>OCAMLRUNPARAM=b flx src/test/regress/rt/recog-04.fdoc
....
SPawn Fthread svc call '_svc_fthread' is _svc_fthread<9890>closure
Raised at Stdlib__hashtbl.find in file "hashtbl.ml", line 539, characters 13-28
Called from Flx_profile.call.fend in file "src/compiler/flx_misc/flx_profile.ml", line 20, characters 10-38

SYSTEM FAILURE
hd
```
This occurs in Ocaml 4.06 and also the repo head. It only happens when I modify a particular file that does certain processing.  The line after the dots is my diagnostic. The SYSTEM FAILURE is my routine reporting it has caught a `hd` exception. The execution trace indicates the fault is in Hashtbl.find. This routine cannot throw `hd`, only `Not_found`. The profiling function is this:
```
(** A wrapper function to profile a function call. *)
let call name f arg =
  let start_time = Unix.gettimeofday () in
  let fend () =
    let end_time = Unix.gettimeofday () in
    let old_times =
      try Hashtbl.find statistics name
      with Not_found -> []
    in
    Hashtbl.replace statistics name ((end_time -. start_time) :: old_times)
  in
  Flx_util.finally fend f arg
```
and
```
let finally fend f x =
  let r =
    try
      f x
    with e ->
      fend ();
      raise e
  in
  fend ();
  r
```
This looks like a bug in Hashtbl.find although it probably isn't. However none of my code is calling `hd` here or in any of the code being profiled AFAIK. There is no doubt my code is causing a problem although exactly how I cannot figure out. However the execution trace is clearly wrong.

**Comment by gasche** [comment]
In the current OCaml runtime the "last exception backtrace" is a global mutable constant, set when an exception is raised (unless `%raise_notrace` is used). A recurring source of confusion, which may be the problem here, is when a first exception backtrace is "trashed" by another exception-raising computation that happened during the first exception handling.

So a scenario could be:
- `f arg` fails with an exception `e` whose diagnostic is `hd`
- but `Hashtbl.find` raises and thus overwrites the previous backtrace
- then `e` is reraised, and you diagnostic catches it (with the `Hashtbl.find` backtrace)

(I'm skeptical about this, because the second `raise e` should show up in the backtrace.)

Note that OCaml since 4.08 provides a function `Fun.protect : ~finally:(unit -> unit) -> (unit -> 'a) -> 'a` that acts as your `try_with`, yet is careful to avoid any backtrace trashing in the `finally` function (by calling backtrace-careful lower primitives, in particular `Printexc.raise_with_backtrace`).

**Comment by skaller** [comment]
Thanks for the hints. I will switch to Fun.protect, couldn't do this before since Ocaml 4.06 was required due to safe string issue. I have just found the code wasn't built with the -g option as it should have been, i'm rebuilding it now.  

Ah it's my mistake I'm sorry. I will close the issue. The backtrace was wrong because -g wasn't specified. With that switch on, I now get a sane backtrace:
```
Raised at Flx_util.finally in file "src/compiler/flx_misc/flx_util.ml", line 14, characters 6-13
Called from Flxg.handle_optimize in file "src/compiler/flxg/flxg.ml", line 206, characters 19-114
Called from Flxg.handle_lower in file "src/compiler/flxg/flxg.ml", line 223, characters 30-73
Called from Flxg.handle_codegen in file "src/compiler/flxg/flxg.ml", line 241, characters 30-70
Called from Flxg.main in file "src/compiler/flxg/flxg.ml", line 302, characters 10-75
```
This doesn't pinpoint the error due to my `finally` stuff but already I know where to look, I have broken an invariant which the lowering code (which replaces abstract types with their representations) expects.

**Comment by skaller** [comment]
BTW, with Fun.protect here is the very much better backtrace, thanks for hint:
```
Raised at Stdlib.failwith in file "stdlib.ml", line 29, characters 17-33
Called from Stdlib__list.hd in file "list.ml" (inlined), line 30, characters 10-23
Called from Flx_list.list_prefix.aux in file "src/compiler/flx_misc/flx_list.ml", line 74, characters 29-34
Called from Flx_numono.mono_element in file "src/compiler/flx_frontend/flx_numono.ml", line 116, characters 20-45
Called from Flx_numono.monomorphise2 in file "src/compiler/flx_frontend/flx_numono.ml", line 230, characters 4-79
Called from Flx_opt.print_time in file "src/compiler/flx_opt/flx_opt.ml", line 8, characters 15-19
Called from Flx_opt.optimize_bsym_table' in file "src/compiler/flx_opt/flx_opt.ml", line 82, characters 3-135
Called from Flx_opt.print_time in file "src/compiler/flx_opt/flx_opt.ml", line 8, characters 15-19
Called from Flxg_opt.optimize in file "src/compiler/flxg/flxg_opt.ml", line 12, characters 19-90
Called from Stdlib__fun.protect in file "fun.ml", line 33, characters 8-15
Re-raised at Stdlib__fun.protect in file "fun.ml", line 38, characters 6-52
Called from Flxg.handle_optimize in file "src/compiler/flxg/flxg.ml", line 206, characters 19-114
Called from Flxg.handle_lower in file "src/compiler/flxg/flxg.ml", line 223, characters 30-73
Called from Flxg.handle_codegen in file "src/compiler/flxg/flxg.ml", line 241, characters 30-70
Called from Flxg.main in file "src/compiler/flxg/flxg.ml", line 302, characters 10-75
```
So actually I broken an invariant required by the monomorphisation code exactly here:
```
        | BBDCL_fun (_,vs,_,_,_,_) ->
          let n = List.length vs in
          let pts = Flx_list.list_prefix ts n in 
```
The vs are type variables and the ts are their replacements.  There are not enough types to monomorphise the specified list of type variables.
