### ISSUE TITLE
Code and documentation are inconsistent for `caml_shutdown`

### ISSUE THREAD

**Issue by gadmm** [ocaml/ocaml#10179]
Leaving this observation here for the record (following the maxim “when the code does not do what the documentation says then both are probably wrong”):

At https://caml.inria.fr/pub/docs/manual-ocaml/intfc.html#ss:c-embedded-code it is explained that `caml_shutdown` shuts down the runtime "gracefully" because among others it closes the file descriptors owned by values of type `in_channel` and `out_channels` by running their finalisers. This is incorrect: the finaliser does not release the file descriptor. In order to do like the comment says, one could traverse the global list of channels and close the descriptors by hand. But this is a bad idea, since we do not know whether the descriptor is really owned by the channel. (Some descriptors are owned by several channels at once, and you probably do not want in general to close descriptors such as stdin, stderr and stdout.)

I suspect that the current behaviour is desirable under the assumption that it is done in cooperation with the OCaml program, which must have done its own cleanup beforehand and reached a proper exit, and that it would be too difficult to improve the behaviour into the finalisation of all heap values rather than just custom blocks (as documented erroneously for `caml_finalise_heap` in `major_gc.h`).

**Comment by gadmm** [comment]
#10304 addresses this issue (among other things)

**Comment by nojb** [comment]
Related to #10865

**Comment by gadmm** [comment]
@nojb I do not see what this has to do with #10865. This predates multicore. However, since the "cleanup at exit" mode is not usable as it is anyway, and nobody is willing or able to work on it (#10304), it makes sense to close this issue.

**Comment by nojb** [comment]
> @nojb I do not see what this has to do with #10865. This predates multicore. However, since the "cleanup at exit" mode is not usable as it is anyway, and nobody is willing or able to work on it (#10304), it makes sense to close this issue.

Indeed, it is not a duplicate, just related (I amended the note).
