### ISSUE TITLE
Could the error message when passing an empty char be better?

### ISSUE THREAD

**Issue by rbjorklin** [ocaml/ocaml#10196]
I tripped myself with this and my eyes didn't spot the missing space between the the single quotes. Unfortunately the compiler was only moderately helpful too. Could this error message be clarified?
![empty-char](https://user-images.githubusercontent.com/1704798/106834503-73b84000-664a-11eb-8cbe-25ae4283b108.png)

**Comment by gasche** [comment]
Thanks for the report. I propose a fix in #10197.

**Comment by gasche** [comment]
The fix was merged, with the following error message:

```
Error: Illegal empty character literal ''
  Hint: Did you mean ' ' or a type variable 'a ?
```

**Comment by rbjorklin** [comment]
Thank you!
