### ISSUE TITLE
ocaml-base-compiler fails build on step 7/12, 4.11.1

### ISSUE THREAD

**Issue by gtdlk20** [ocaml/ocaml#10216]
Ive installed opam on mac catalina, initialized opam, and tried to create switch 4.11.1. It fails on step 7/12, and this is the error screen afterwards:
```
<><> Gathering sources ><><><><><><><><><><><><><><><><><><><><><><><><><><>  🐫 
[ocaml-base-compiler.4.11.1] found in cache

<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><>  🐫 
∗ installed base-bigarray.base
∗ installed base-threads.base
∗ installed base-unix.base
[ERROR] The compilation of ocaml-base-compiler failed at "/Users/gkaufmann/.opam/opam-init/hooks/sandbox.sh build make -j3 world".

#=== ERROR while compiling ocaml-base-compiler.4.11.1 =========================#
# context     2.0.8 | macos/x86_64 |  | https://opam.ocaml.org#600f8620
# path        ~/.opam/4.11.1/.opam-switch/build/ocaml-base-compiler.4.11.1
# command     ~/.opam/opam-init/hooks/sandbox.sh build make -j3 world
# exit-code   2
# env-file    ~/.opam/log/ocaml-base-compiler-76744-e7966f.env
# output-file ~/.opam/log/ocaml-base-compiler-76744-e7966f.out
### output ###
# [...]
# cc -c -O2 -fno-strict-aliasing -fwrapv -Wall -Wdeclaration-after-statement -fno-common -g -D_FILE_OFFSET_BITS=64 -D_REENTRANT -DCAML_NAME_SPACE   -o startup_byt_b.o startup_byt.c
# cc -c -O2 -fno-strict-aliasing -fwrapv -Wall -Wdeclaration-after-statement -fno-common -g -D_FILE_OFFSET_BITS=64 -D_REENTRANT -DCAML_NAME_SPACE   -DDEBUG -o instrtrace_bd.o instrtrace.c
# rm -f libcamlruni.a && ar rc libcamlruni.a  interp_bi.o misc_bi.o stacks_bi.o fix_code_bi.o startup_aux_bi.o startup_byt_bi.o freelist_bi.o major_gc_bi.o minor_gc_bi.o memory_bi.o alloc_bi.o roots_byt_bi.o globroots_bi.o fail_byt_bi.o signals_bi.o signals_byt_bi.o printexc_bi.o backtrace_byt_bi.o backtrace_bi.o compare_bi.o ints_bi.o eventlog_bi.o floats_bi.o str_bi.o array_bi.o io_bi.o exter[...]
# rm -f libcamlrun_pic.a && ar rc libcamlrun_pic.a  interp_bpic.o misc_bpic.o stacks_bpic.o fix_code_bpic.o startup_aux_bpic.o startup_byt_bpic.o freelist_bpic.o major_gc_bpic.o minor_gc_bpic.o memory_bpic.o alloc_bpic.o roots_byt_bpic.o globroots_bpic.o fail_byt_bpic.o signals_bpic.o signals_byt_bpic.o printexc_bpic.o backtrace_byt_bpic.o backtrace_bpic.o compare_bpic.o ints_bpic.o eventlog_bp[...]
# /opt/local/bin/ranlib: object: libcamlrun_pic.a(interp_bpic.o) malformed object (unknown load command 1)
# /opt/local/bin/ranlib: object: libcamlruni.a(interp_bi.o) malformed object (unknown load command 1)
# ar: internal ranlib command failed
# ar: internal ranlib command failed
# make[1]: *** [libcamlrun_pic.a] Error 1
# make[1]: *** Waiting for unfinished jobs....
# make[1]: *** [libcamlruni.a] Error 1
# make: *** [coldstart] Error 2



<><> Error report <><><><><><><><><><><><><><><><><><><><><><><><><><><><><>  🐫 
┌─ The following actions failed
│ λ build ocaml-base-compiler 4.11.1
└─ 
┌─ The following changes have been performed (the rest was aborted)
│ ∗ install base-bigarray base
│ ∗ install base-threads  base
│ ∗ install base-unix     base
└─ 

<><> ocaml-base-compiler.4.11.1 troubleshooting <><><><><><><><><><><><><><>  🐫 
=> A failure in the middle of the build may be caused by build parallelism
      (enabled by default).
      Please file a bug report at https://github.com/ocaml/ocaml/issues
=> You can try installing again including --jobs=1
      to force a sequential build instead.
```
I can't make heads or tails of this. Any advice or help?

**Comment by dbuenzli** [comment]
> /opt/local/bin/ranlib

You seem to have `binutils` installed via an alternate package manager that are taking over and interacting with the MacOS devtools in a bad way. 

You should likely alter your `PATH` to make sure that: 

```
> type ranlib
ranlib is /usr/bin/ranlib
```

**Comment by gtdlk20** [comment]
I'm not sure exactly how to accomish that. Can you please elaborate?

**Comment by dbuenzli** [comment]
> I'm not sure exactly how to accomish that. Can you please elaborate?

You can tweak the [`PATH`](https://en.wikipedia.org/wiki/PATH_(variable)) order by editing `/etc/paths`, see for example [this random blog post](https://www.architectryan.com/2012/10/02/add-to-the-path-on-mac-os-x-mountain-lion). 

But unless you need it the easiest is likely to get rid of that `binutils` install.

**Comment by gtdlk20** [comment]
I’ve edited the paths according to the blog post, and when I run echo $PATH this is my output, which differs from what is in the etc/paths file:

echo $PATH
/Users/gkaufmann/.opam/4.11.1/bin:/Library/Frameworks/Python.framework/Versions/2.7/bin:/Library/Frameworks/Python.framework/Versions/3.8/bin:/Users/gkaufmann/.cargo/bin:/Library/Frameworks/Python.framework/Versions/3.7/bin:/Library/Frameworks/Python.framework/Versions/2.7/bin:/Library/Frameworks/Python.framework/Versions/3.7/bin:/opt/anaconda3/bin:/Users/gkaufmann/anaconda3/condabin:/opt/local/bin:/opt/local/sbin:/anaconda3/bin:/Library/Frameworks/Python.framework/Versions/3.6/bin:/Library/Frameworks/Python.framework/Versions/3.6/bin:/Library/Frameworks/Python.framework/Versions/2.7/bin:/Library/Frameworks/Python.framework/Versions/3.6/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/opt/X11/bin:/Library/Apple/usr/bin

**Comment by dbuenzli** [comment]
There are quite [a few other places](https://stackoverflow.com/questions/603785/environment-variables-in-mac-os-x/4567308#4567308) where the PATH can be setup. It may also depend on your shell. 

In any case if you are using a package manager there may be a way to remove these `binutils` executables from the `PATH`. E.g. in `brew` you would do `brew unlink binutils` but I doesn't seem you are using brew.
