### ISSUE TITLE
Use different warning 32 message wording for values not used by anything and values shadowed within the module

### ISSUE THREAD

**Issue by dmbaturin** [ocaml/ocaml#10223]
I fear the issue title may be confusing, but I couldn't come up with a better wording.

Intuitively, the "unused value" warning means "a value that is not used by anything else in the module and not made public in its interface". That's also the most common way to get that warning.

However, shadowing a value can produce exactly the same warning. While technically correct, it may make the user start looking in a wrong direction, when the real problem is much simpler.

Consider a trivial example:

```ocaml
let hello () = print_endline "hi world"

let hello () = print_endline "hello world"

let () = hello ()
```
The best thing to say about it would be like "useless value `hello` on line 1 (shadowed on line 3)".
However, in practice we get the usual warning 32 wording:

```
$ ocamlopt -o hello -w @32 ./test.ml 
File "./test.ml", line 1, characters 4-9:
1 | let hello () = print_endline "hi world"
        ^^^^^
Error (warning 32): unused value hello.
```

**Comment by dra27** [comment]
I think the original wording could be unaltered, but simply add the note about shadowing? `Error (warning 32): unused value hello (shadowed at line 3, characters 4-9)`.

**Comment by dmbaturin** [comment]
@dra27 Indeed. My point is just that additional clarification could be helpful.

**Comment by dmbaturin** [comment]
Now that I think of it, there may be a valid reason to make it a different warning entirely. 

* A value that is shadowed within the same module is almost certainly a programming mistake.
* A value that is shadowed in a different module may be a mishap, or it may be a necessary hack, but it's definitely not a good sign.
* A value that exists in a module but isn't used by anything else in a codebase is almost certainly harmless dead code, or maybe even a not _yet_ used piece of code that the user wants to check.

I believe with `-Werror`, shadowing a value within a module should always fail the build, but having unused functions in an internal module is something one may want to allow.

**Comment by stedolan** [comment]
> A value that is shadowed within the same module is almost certainly a programming mistake.

An _unused_ value shadowed in the same module does sound like a mistake, but merely shadowing is often done on purpose.

A not-unheard-of programming style is to first define a (often recursive) function using an internal interface, and then immediately shadow it with a wrapper that has a more explicit interface / better error handling / etc. See [Env.normalize_module_path in the compiler](https://github.com/ocaml/ocaml/blob/trunk/typing/env.ml#L1099-L1134) for an example.

**Comment by xavierleroy** [comment]
> An unused value shadowed in the same module does sound like a mistake, but merely shadowing is often done on purpose.

Agreed.  Another example of "good" shadowing is to temporarily add tracing code  or assertion checking code to help with debugging:
```
let rec f x = ...

let f x = printf "f is called with %d\n" x; let res = f x in printf "f returns %d\n" res; res
```

An unused, shadowed value is probably a mistake, I agree.  Whether it deserves a specific warning is up for discussion.

**Comment by dmbaturin** [comment]
@stedolan Well, good shadowing (when the body of the "shadower" refers to the shadowed value) doesn't cause that warning, so it's alright.

My main point is that a message that says "unused value" can send a developer down a wrong debugging path, while a clarification about shadowing can prevent that false lead.

**Comment by dmbaturin** [comment]
I still think it would be a UX improvement, so I don't think this issue should be closed.
