### ISSUE TITLE
4.11.2: test suite is failing

### ISSUE THREAD

**Issue by kloczek** [ocaml/ocaml#10249]
Looks like something is missing in dist source tree and/or test suite is trying to lookup outside of the build tree.
```
+ cd ocaml-4.11.2
+ /usr/bin/make -O -j48 V=1 VERBOSE=1 -C testsuite all
cannot find file '../../ocamlopt'
make[2]: *** [Makefile:48: testing.cmx] Error 127
make[1]: *** [Makefile:270: lib] Error 2
make: *** [Makefile:113: all] Error 2
```

**Comment by Octachron** [comment]
Could you clarify where you got the source and your build process?

**Comment by kloczek** [comment]
I'm using autogenerated by github frontend tar ball from git tag.
https://github.com/ocaml/ocaml/archive/4.11.2/ocaml-4.11.2.tar.gz

**Comment by Octachron** [comment]
Did you build the rest of the compiler suite (with ocamltest enabled) before trying to run the test suite?

**Comment by Octachron** [comment]
I am closing this issue in the absence of feedback (or was #10250 the root issue?).

**Comment by kloczek** [comment]
Maybe .. for now I agree that that issu may be somehow connected ant to minimise noise this ticket can be closed :)
