### ISSUE TITLE
hash function in modules Bool/Int/Char/String

### ISSUE THREAD

**Issue by backtracking** [ocaml/ocaml#10259]
It would be convenient if modules `Bool`/`Int`/`Char`/`String` would provide a `hash` function, so that we can pass them to functors such as `Hashtbl.Make`.

Of course, we can use the polymorphic hash function `Hashtbl.hash` for this purpose, or define custom hash function (e.g. the identity for type `int`), but that's less convenient from a user's perspective.

Note: module `Float` already provides a `hash` function.

**Comment by dra27** [comment]
Cross-referencing at least https://github.com/ocaml/ocaml/pull/8878/files (`String.hash`)

**Comment by xavierleroy** [comment]
See my comment here: https://github.com/ocaml/ocaml/pull/10262#issuecomment-789063292 . There's a tension between seeded and unseeded hash functions, and bad name choices in the past prevent us from implementing both in the same module.
