### ISSUE TITLE
Chapter labels in new html manual

### ISSUE THREAD

**Issue by sanette** [ocaml/ocaml#10254]
I have not followed the integration of the new manual into the ocaml web site, but I noticed something weird concerning chapter and part labels. See the pictures below. I can work on this but before I start I'd like to know if reintroducing the "Part" and "Chapter" labels was done on purpose or not.

The current version:
![Screenshot_20210226_091748](https://user-images.githubusercontent.com/7536536/109275259-ca153a80-7814-11eb-8df6-cbee404c61bf.png)

What I assume to be the correct rendering:
![Screenshot_20210226_091805](https://user-images.githubusercontent.com/7536536/109275265-cc779480-7814-11eb-96ee-a19ba5a4d41a.png)

**Comment by Octachron** [comment]
This looks like the recent use of unicode spaces in hevea broke the rewriting rules for chapters and parts.

**Comment by Drup** [comment]
There are other weirdnesses, for instance:

![image](https://user-images.githubusercontent.com/801124/109282302-a4406380-781d-11eb-9e97-880b394d164f.png)

**Comment by sanette** [comment]
yes I saw that, it's clearly the same problem

**Comment by sanette** [comment]
> This looks like the recent use of unicode spaces in hevea broke the rewriting rules for chapters and parts.

I see, that makes sense. 

EDIT: the hevea version is not specified in the makefile, so we could either check the version when building the manual, or modify the rewriting rule to make it work for all versions

**Comment by sanette** [comment]
could you post the file `index.html` of the manual generated by the latest hevea?
EDIT: so apparently hevea writes:
```
'Chapter\u2004\u200d2\u2003The module system'
```
So it's actually using **three** different "space" chars, wow!
\u2004 = Three-Per-Em Space
\u200d = Zero Width Joiner (ZWJ)  
\u2003 = Em Space

In previous hevea versions, the three of them were all "\xa02", ie isolatin no-break space.

**Comment by sanette** [comment]
looking up the wikipedia page on "Zero Width Joiner", I wonder whether hevea uses it in a correct fashion. Apparently its primary use is to indicate that two characters should be connected (either superposed, or with a ligature). Maybe that's the reason why Firefox changes the font of the figure following it. Hence I tend to think it should be reported as a bug to hevea.

**Comment by Michelletaylor7123** [comment]
Hello, I am not a computer science student but I want to learn programming and designing, can you guys please tell me what laptop and computer accessories will be the best buy from [Coupon Codest](https://www.couponcodest.com/) to learn programming languages and website designing? Thanks in advance!

**Comment by maranget** [comment]
See [hevea PR 61](https://github.com/maranget/hevea/pull/61) for a tentative solution.

**Comment by Octachron** [comment]
This was fixed by #10282 (which makes the manual post-processing phase recognizes all sensible unicode space characters) and pushed online at https://ocaml.org/manual .
