### ISSUE TITLE
[trunk] Bound types via GADT are not resolved when referred via a module

### ISSUE THREAD

**Issue by kit-ty-kate** [ocaml/ocaml#10271]
The following test-case succeeds with OCaml 4.12 but fails with trunk (https://github.com/ocaml/ocaml/commit/8b8168ee097aa15e0148816984279220526f970f)
```
$ cat test.ml
module M = struct
  type _ rr = Soa : int rr
  type b = B : 'a rr * 'a -> b
end

let test =
  let M.(B (k, v)) = M.(B (Soa, 0)) in
  match k, v with
  | M.Soa, soa -> (soa : int)
$ ocamlc test.ml
File "test.ml", line 9, characters 19-22:
9 |   | M.Soa, soa -> (soa : int)
                       ^^^
Error: This expression has type $B_'a but an expression was expected of type
         int
       $B_'a is abstract because no corresponding cmi file was found in path.
```
However when we remove the module `M` and move the types at toplevel or only remove the references to `M` in `test` and add an `open M` above, it works.
```
$ cat test.ml
module M = struct
  type _ rr = Soa : int rr
  type b = B : 'a rr * 'a -> b
end

open M

let test =
  let B (k, v) = B (Soa, 0) in
  match k, v with
  | Soa, soa -> (soa : int)
$ ocamlc test.ml
```

**Comment by lpw25** [comment]
This looks to me like an interaction between the call to `Env.copy_local` in the `Ppat_open` case of `type_pat_aux` and the change in #9584 from using `Env.add_local_type` to using `Env.enter_type` for existential types.

**Comment by garrigue** [comment]
Thank you for the report, and thanks to @lpw25 for the correct analysis. I completely missed this side use of the local type map.
