### ISSUE TITLE
OCaml manual for 4.12 online

### ISSUE THREAD

**Issue by clarus** [ocaml/ocaml#10278]
Hello,

For me the manual on https://caml.inria.fr/pub/docs/manual-ocaml/index.html shows:

![image](https://user-images.githubusercontent.com/316665/110296525-b88d1900-7ff2-11eb-9954-f6c3089f44fe.png)

with "The OCaml system release 4.11" while the 4.12.0 version of OCaml has been released for 12 days. I wonder if this is a standard delay or if the manual version should be updated.

**Comment by Octachron** [comment]
The manual has moved to `ocaml.org`: https://ocaml.org/manual . I am not sure if we should still upload the manual to `caml.inria.fr` or if we should add a redirection to `ocaml.org`.

**Comment by gasche** [comment]
(Going in the direction of @Octachron) in any case the current state is not ideal, as the present issue shows.

@Octachron, in practice you are the person doing the work of publishing the manual, so please feel free to do as you think is best. Both options seem fine to me. I must say that my muscle memory leads me to caml.inria.fr whenever I'm reaching for the manual, but actually maybe a redirection would be nice to emphasize the new location and improve its discoverability for long-term users.

**Comment by Naereen** [comment]
Hi,
The new manual seems very great! Congrats :clap:! 

I saw an error on https://ocaml.org/releases/4.12/api/index.html the OCaml logo redirects to https://ocaml.org/releases/4.12/manual/index.html which is empty. ~~I can open a specific issue if needed, let me know.~~ see #10279

**Comment by xavierleroy** [comment]
I'm in favor of redirecting https://caml.inria.fr/pub/docs/manual-ocaml/ to https://ocaml.org/manual/ .  Notwithstanding the habits of old persons, ocaml.org is now the primary source of OCaml information.

**Comment by avsm** [comment]
@Naereen a bug report on PR on https://github.com/ocaml/ocaml.org/issues is appreciated for anything related to that site.

**Comment by Naereen** [comment]
> @Naereen a bug report on PR on https://github.com/ocaml/ocaml.org/issues is appreciated for anything related to that site.

Done in #10279, sorry @avsm of course I should have opened a new issue directly, sorry for the noise!

And well done everybody for the newest manual at <https://ocaml.org/manual/>, especially the API search which works very very well :clap:! I've been using [Zeal](https://zealdocs.org/) for years, mainly because it has this magic search power, which is now available to everybody on the official manual!!!

**Comment by pmetzger** [comment]
Who controls https://caml.inria.fr/pub/docs/manual-ocaml/ and could redirect it?

**Comment by Octachron** [comment]
It is hosted by the Cambium team (at Inria Paris). In other words, I need to find the time to fiddle with the configuration.

**Comment by Octachron** [comment]
The redirection should be online: https://caml.inria.fr/pub/docs/manual-ocaml is now redirected to ocaml.org/manual (with a specialized redirection for the standard library https://caml.inria.fr/pub/docs/manual-ocaml to ocaml.org/api and compiler library). The redirection is not yet permanent to give us some time to test the change.

**Comment by Naereen** [comment]
Great! It's a very nice URL, <https://ocaml.org/api/> and <https://ocaml.org/manual/>

Where should I open an issue regarding the API documentation? Thanks!
It's not optimal that every value has a `#VAL..` anchor but cannot be directly clicked or accessed from each API page, Sphinx for Python does a better job for this.

**Comment by Octachron** [comment]
The API documentation is currently generated by ocamldoc (which is distributed with ocaml). However, ocamldoc is currently in maintenance mode and we are planning to switch to odoc (a newer document generator which understands better OCaml module system).

And odoc already adds a visible anchor to each item.

In other words, your issue should be solved by the offsprings of #9997 .

**Comment by Naereen** [comment]
Okay thanks for the details, it's what I thought.

**Comment by clarus** [comment]
Thanks!
