### ISSUE TITLE
Strange 'ǧ' characters in the manual

### ISSUE THREAD

**Issue by ghost** [ocaml/ocaml#10287]
When the Ocaml documentation [talks](http://caml.inria.fr/pub/docs/manual-ocaml/debugger.html#s%3Adebugger-execution) about `ocamldebug` and "events", it includes strange `ǧ` characters.

I believe that it stands for a place in a program that represent one particular "event" (where we can set a breakpoint and where a program can stop).

I am wondering whether this is the only way how to denote the concept of "events" or what would be a clearer way to do so.

**Comment by Octachron** [comment]
Closed by #10288 .
Note that there is few other pending issues in the manual, I will regenerate the manual once there are all solved.
