### ISSUE TITLE
Could Unix.map_file support specifying the MAP_ANONYMOUS flag?

### ISSUE THREAD

**Issue by UnixJunkie** [ocaml/ocaml#10280]
Hello,

```ocaml
val Unix.map_file file_descr -> ?pos:int64 -> ('a, 'b) Bigarray.kind -> 'c Bigarray.layout -> bool -> int array -> ('a, 'b, 'c) Bigarray.Genarray.t
```

Currently, the bool only controls MAP_SHARED or MAP_PRIVATE (I see in otherlibs/unix/mmap.c), and there
is no way to specify MAP_ANONYMOUS.

Regards,
Francois.

**Comment by dra27** [comment]
`Unix.map_file` clearly can't support this: the signature would change and for `MAP_ANONYMOUS` the `file_descr` and `~pos` arguments are ignored, which is "fine" in C, but an API smell in OCaml.

I have no opinion on the merits of having `val Unix.map_anonymous : ('a, 'b) Bigarray.kind -> 'c Bigarray.layout -> bool -> int array -> ('a, 'b, 'c) Bigarray.Genarray.t` (or some such).

**Comment by UnixJunkie** [comment]
Maybe it should accept a list of flags, to be future proof / complete.

**Comment by xavierleroy** [comment]
`MAP_ANONYMOUS` is Linux-specific and not standard: https://pubs.opengroup.org/onlinepubs/009695399/functions/mmap.html .  The common idiom is to open /dev/null and map it privately.

**Comment by dra27** [comment]
> Maybe it should accept a list of flags, to be future proof / complete.

That still doesn't solve the fact that `MAP_ANONYMOUS` is a _different_ function!

**Comment by stedolan** [comment]
What do you want this for? `MAP_ANONYMOUS` is mainly used for allocating memory, for which there's the `Bigarray.ArrayN.create` functions.

**Comment by UnixJunkie** [comment]
In Linux, you can combine MAP_ANONYMOUS with MAP_SHARED.
MAP_ANONYMOUS allows to not have the shm area synchronized to a file.

If there is a workaround like opening /dev/null (or /dev/zero) to achieve the effect of MAP_ANONYMOUS, then my feature request can be closed.

**Comment by UnixJunkie** [comment]
Maybe, if we manage to pass a -1 file_descr to the current Unix.map_file and the offset is 0 (pos), it should turn on the MAP_ANONYMOUS flag on Linux.

**Comment by UnixJunkie** [comment]
I currently don't know how to create a Unix.file_descr from -1 or any user-provided int though.

PS: Maybe this way: let fd: Unix.file_descr = Obj.magic (-1);;

**Comment by UnixJunkie** [comment]
I checked on a recent Mac: they also have the MAP_ANONYMOUS flag.

**Comment by UnixJunkie** [comment]
this could be assigned to me, I'll try to send a patch

**Comment by pmetzger** [comment]
Just an FYI, it seems most modern Unixish platforms support MAP_ANON / MAP_ANONYMOUS. The BSDs do, Mac does, Linux does, Solaris and Illumos support it. (Indeed, I can't find a platform that has mmap and doesn't support MAP_ANONYMOUS but I may have forgotten to check a few.)

**Comment by UnixJunkie** [comment]
Yes, only old kernels don't have it, and probably old unices.

**Comment by pmetzger** [comment]
So far as I can tell, MAP_ANON is part of the original specification of the mmap system call as described in the BSD 4.3 and BSD 4.4 architecture manuals, so anyone who implemented a compatible version of mmap implemented that. Very old kernels don't have mmap at all of course.

**Comment by pmetzger** [comment]
@UnixJunkie I suspect if you want this to happen you may have to implement it.

**Comment by UnixJunkie** [comment]
@pmetzger I have sent a patch, but IIRC it was not working correcty in my tests.
If you want to have a look at it and make it work, you are very welcome.
https://github.com/ocaml/ocaml/pull/10316/files
I don't have time for this these days.
