### ISSUE TITLE
Present-but-wrong backtraces in programs partially compiled without `-g`

### ISSUE THREAD

**Issue by stedolan** [ocaml/ocaml#10290]
If some files in a project are compiled without `-g`, then exceptions raised from this file will report as their backtrace whatever happened to be lying around in the backtrace buffer, from some exception previously raise by code compiled with `-g`. This is extremely confusing (I spend half an hour this morning trying to work out what was going on!)

There are three kinds of `raise`, according to `Lambda.raise_kind`:
  - `Raise_regular` - normal `raise`, collects a backtrace if enabled
  - `Raise_reraise` - reraise (raise inside handler), appends to existing backtrace if enabled
  - `Raise_notrace` - raise without collecting a backtrace (e.g. `Stdlib.raise_notrace`)

Cmm_helpers translates `raise` into `Raise_notrace` when compiling without debug info, which seems reasonable. But the implementation of `Raise_notrace` appears to preserve the existing backtrace. I think it should instead unconditionally clear the backtrace.

**Comment by gasche** [comment]
I have vague remembrances of having already discussed a similar change with you, due to the fact that some Jane Street library (Core or Base, I guess) would use internal runtime functions specifically to implement this variant -- or maybe something close. Does that ring a bell?

**Comment by jberdine** [comment]
This one: https://github.com/janestreet/base/blob/9ef390d678d4573ff54b7d94c2cb5ccdf92dc0ad/src/exn.ml#L144 ?

FWIW I have also been bitten by confusing backtraces from code only partially compiled with `-g`.

**Comment by gasche** [comment]
Yes! I guess we should consider making this change, and maybe ask the community about it. (It's a kind of change we cannot evaluate by just building opam and running unit tests.)

**Comment by gasche** [comment]
Ah: one reason to appreciate the current behavior is when you want to use local exceptions for control flow. Then you know that if you mark them `notrace`, they do not interact with the backtrace. This is important and useful in code that runs some cleanup handlers or prints some stuff, and then reraises the exception. Nowadays we have the `raise_with_backtrace` primitive that lets us do this more cleanly, but it has a higher performance cost (than doing nothing at all) and code may have been written using `notrace` with this property in mind before _with_backtrace was available.

**Comment by nojb** [comment]
> Ah: one reason to appreciate the current behavior is when you want to use local exceptions for control flow.

I confirm this is an actual use-case, which is why I think the proposed change could be problematic. See https://github.com/ocaml/ocaml/pull/1731 for an example in the compiler itself.

**Comment by stedolan** [comment]
Perhaps there should be both `Raise_notrace` and `Raise_cleartrace`? Preserving the existing backtrace seems reasonable for explicit uses of `raise_notrace`, but not for uses of `raise` that were silently changed to `raise_notrace` by Cmm.

Also, since we already detect raises that are statically inside a handler (to make them into reraises), maybe we should ensure that those always preserve the backtrace, by saving/restoring it if necessary? I think that would make the Format change unnecessary.

**Comment by jberdine** [comment]
I don't want to make a big deal out of it, but I have also encountered issues with how the backtrace is cleared by `Base.Exn.raise_without_backtrace`. There is code where we avoid using any function that might end up calling `Base.Exn.raise_without_backtrace`, which quickly leads to just not using `Base`, and is unfortunate.

I have only thought about it a bit, but I think that @stedolan's proposal (for explicit uses of `raise_notrace` to leave the backtrace untouched while the uses introduced by optimization clear the backtrace) would provide a good trade-off in both cases.

I also find the idea of automatically preserving backtraces in handlers to be very appealing. Currently this needs to be done manually (perhaps with a wrapper `protect` function) and is easy to overlook, with no help from the type system. I wonder if the potential performance impact of automatically saving and restoring the backtraces means that there ought to be some escape to disable this in some handlers in case it becomes necessary. Perhaps an attribute attached to the `try..with` expression would suffice.
