### ISSUE TITLE
"double-double" floating point algorithm tricked by pernickety hardware

### ISSUE THREAD

**Issue by let-def** [ocaml/ocaml#10323]
*Note: This is a post-mortem of a bug due to a combination of compiler and hardware optimisations rather than a bug in OCaml per se. Still, I found the case interesting enough to share and document it for posterity.*

Double-double and Quad-double arithmetic are algorithms that implement species of floating point numbers with augmented precision. A good reference is [Library for Double-Double and Quad-Double Arithmetic, by Yozo Hida, Xiaoye S. Li, and David H. Bailey](http://web.mit.edu/tabbott/Public/quaddouble-debian/qd-2.3.4-old/docs/qd.pdf).

## Quick Introduction to Double-double

Intuitively the idea is to manipulate tuples of floats. The first float is interpreted like a normal float, but the latter ones provide additional precision to it. For instance, here is a representation of pi (printed as decimal) as a double-double:

```ocaml
let pi = {
  hi = 3.1415926535_8979311599_7963468544;
  lo = 0.0000000000_0000012246_4679914735;
}
```

The `hi` value is the same as the built-in`Float.pi`. However the `lo` value increases the precision:

```
3.1415926535 8979311599 7963468544 (hi)
0.0000000000 0000012246 4679914735 (lo)
----------------------------------
3.1415926535 8979323846 2643383279 (proper pi approximation)
```

If you were to add the `hi` and `lo` digits, you could see that they coincide with the correct approximation of pi to this precision.

In practice the floating point values are constructed such that the exponents are redundant (the exponent of `lo` is equal to the exponent of `hi` shifted by the number of bits of the mantissa) and the mantissa complement.

The paper describes how common operations can be implemented on this representation while benefitting of the extra precision. I implemented such a library in OCaml, [Doubledouble](https://github.com/let-def/grenier/tree/master/doubledouble), basing my code on the [DD](http://www.tsusiatsoftware.net/dd/main.html) implementation for Java.

## Failures on Some Architectures

For a few years, it went without problems (and without much use as far as I can tell :-)). However, improvements to Opam CI revealed a few errors earlier this year: tests that had been working for years on AMD64 where failing on X86-32 and ARM64. Only in native code, the byte code backend worked reliably on all architectures.

With the help of @kit-ty-kate, we tracked down the issue to two places:

- optimisations of store and load on x86-32
- use of fused multiply add and subs on arm64

In both cases, it is a problem of increased precision. On x86-32, the FPU has an internal precision of 80 bits: if a store-load sequence is optimised, the precision increases by 16 bits. And the use of fused operations also provides an increased precision: computing (a * b + c) in two operations results in rounding twice, while FMA instruction computes the same value with one rounding.

Double-double algorithms being very sensitive to floating point precision (and rounding mode), having more than 64 bits precision can thus be a problem in practice.

Here is a small code that reproduces the problem, extracted from the computation of inverse:

```ocaml
let k_split = 134217729.0

type t = {hi: float; lo: float}

let inv {hi; lo} =
  (*C = 1.0/hi; *)
  let c' = 1. /. hi in
  (*c = SPLIT*C; *)
  let c  = k_split *. c' in
  (*hc =c-C;  *)
  let hc = c -. c' in
  (*u = SPLIT*hi;*)
  let u  = k_split *. hi in
  (*hc = c-hc; tc = C-hc; hy = u-hi; U = C*hi; hy = u-hy; ty = hi-hy;*)
  let hc = c  -. hc in
  let tc = c' -. hc in
  let hy = u  -. hi in
  let u' = c' *. hi in
  let hy = u  -. hy in
  let ty = hi -. hy in
  (*u = (((hc*hy-U)+hc*ty)+tc*hy)+tc*ty;*)
  let u  = (((hc *. hy -. u') +. hc *. ty) +. tc *. hy) +. tc *. ty in
  (*c = ((((1.0-U)-u))-C*lo)/hi;*)
  let c  = (((1.0 -. u') -. u) -. c' *. lo) /. hi in
  let hi = c' +. c in
  let lo = (c' -. hi) +. c in
  {hi; lo}

let () =
  (*let a = {hi = 0.34; lo = 0.0} in
  let a' = inv a in*)
  let a' = {
    hi = 2.9411764705882350590115947852609679102898;
    lo = 0.0000000000000000238179334002628905858757;
  } in
  let a'' = inv a' in
  (*Printf.printf "%.40f\n" (a'.hi);
    Printf.printf "%.40f\n" (a'.lo);*)
  Printf.printf "should be zero: %Ld\n" (Int64.bits_of_float a''.lo)
```

And here is the output:

```shell
$ ocamlc case.ml -o bc; ./bc
should be zero: 0
$ (x86-32) ocamlopt case.ml -o nat; ./nat
should be zero: -5121333759196444753
$ (arm64) ocamlopt case.ml -o nat; ./nat
should be zero: -5121329459252241702
```

This case is easy to fix, one just needs to change the second `c` to:

```ocaml
  let c'' = c' *. lo in
  let c = (((1.0 -. u') -. u) -. c'') /. hi in
```

We just extracted the `c' *. lo` computation, which disabled the problematic optimisation on both platforms.

I didn’t go through the whole library to find other unfortunate optimisations. And I am not sure whether it is worth it (and the fix is, afaik, not very reliable as the compiler is free to optimise these cases more aggressively).

**Comment by Gbury** [comment]
Did you try and compile the fixed version with flambda to see if your fix/change survives across the optimisations that flambda performs ?

**Comment by let-def** [comment]
@gbury A bit harder to test with flambda, but the results are not good.
The testcase I shared works with flambda x86-32, even without the fix. However more failures occur in the rest of the library.

**Comment by dra27** [comment]
Similar issues for x86 in https://github.com/ocaml/ocaml/issues/8629.

**Comment by let-def** [comment]
flambda fails similarly on arm64.
The test succeeds by default on flambda, but adding `-Oclassic` behaves as expected: it fails just like with the classic backend ;).

**Comment by gasche** [comment]
I am not sure that this is not an OCaml bug. I would naively expect floating-point operations to have a well-defined semantics, making it *possible* to write precise floating-point computations in the language. My understanding is that the (informal) specification of OCaml says that floating-points are exactly IEEE-blabla doubles, so the observed failures here could be considered implementation bugs.

Whether this is a bug or not, I would expect the existence of a *reliable* way to get the desired behavior. (For example, using attributes/annotations.) The comments here do not seem to suggest that a reliable approach exists.

How do other languages, for example C, deal with this problem?

(cc @xavierleroy, @silene and @jhjourdan, which I would expect to be very knowledgeable on this topic.)

**Comment by silene** [comment]
> How do other languages, for example C, deal with this problem?

The rules for C (floating-point computations might be performed with a higher precision and range than mandated by the static type) are such that the described behaviors are allowed: 80-bit precision and multiplication-addition fusion. This is a bit painful in practice (fusions can be avoided by doing explicit stores between operations).

For Java, they added a keyword `strictfp` that enforces strict IEEE-754 semantics at some performance cost on older architectures.

The issue with 80-bit precision is bound to disappear in the future and can be ignored. The use of FMAs (and new operations to come), however, is a real design decision for OCaml: Can floating-point operations be fused automatically or should the user explicitly call a (builtin) function?

**Comment by xavierleroy** [comment]
> How do other languages, for example C, deal with this problem?

I can recommend [a fine paper on this topic](https://xavierleroy.org/bibrefs/Boldo-Jourdan-Leroy-Melquiond-JAR.html).

As discussed earlier with @let-def, there are two problems here:
- x86-32 with x87 extended-precision FP arithmetic: this one is a mess, but it's an obsolete architecture that will be un-supported soon, so the problem will solve itself.
- Fused Multiply-Add: I think it's good (for performance and for precision of most numerical algorithms) that `a *. b +. c` is automatically compiled as a FMA on platforms where FMA is always available (ARM, PowerPC).  I agree that we could provide a way to turn FMA recognition off for the few cases where it causes problems, like this "double double" library.  A command-line flag would be trivial to implement.  An attribute would have to be propagated quite far "down" the compilation chain.

**Comment by silene** [comment]
> An attribute would have to be propagated quite far "down" the compilation chain.

I suppose you could just annotate (or duplicate) `Pmulfloat` and `Cmulf` with a no-fusion boolean.

That said, the issue with FMA works both way. The `inv` function from the original post becomes irrelevant if you have an FMA at hand. So, you also want to give the user a way to mandate the use of an FMA, irrespective of any optimization from the compiler. For example, in a double-double library, you would usually have two versions of each function, one that uses FMA and one that uses simple additions and multiplications, and then the correct one would be chosen either at compilation or execution time, depending on the target architecture. (This is kind of an argument in favor of having a command-line flag.)

**Comment by gasche** [comment]
Last week an [RFC was sent to LLVM](https://reviews.llvm.org/D100118) to introduce a builtin `__arithmetic_fence(...)` intrisic that would disable fusion of the operations inside with the operations outside: `__arithmetic_fence(a * b) + c` cannot turn into a fused-multiply-add. This corresponds to our `Sys.opaque_identity : 'a -> 'a`, tuned for floating-point computations.

**Comment by silene** [comment]
> `__arithmetic_fence(a * b) + c` cannot turn into a fused-multiply-add

Are you sure about that? Because reading the pull request for the underlying builtin (i.e., `llvm.arith.fence`), I see that the following transformation is allowed:

>     llvm.arith.fence(a * b) + c  →  llvm.arith.fence(FMA(a, b, c))

As a consequence, I fail to see the point of such a builtin.

**Comment by silene** [comment]
For the record, the aforementioned pull request was merged into LLVM. It has been deeply rewritten since the original submission. In particular, the optimizer is no longer allowed to merge `fence(a * b) + c` into an FMA. As far as I understand, only the x86 backend respects this fence; other backends have yet to be ported.

**Comment by bschommer** [comment]
I think a flag to disable generation of fused-multiple arithmetic would be more helpful for the given case. As far as I understand the `__arithmetic_fence` is only used to prevent fusion if `-ffast-math` is specified, which explicitly tells clang to perform non-IEEE optimizations.

**Comment by xavierleroy** [comment]
FYI: since OCaml 4.11.0, `Sys.opaque_identity` is honored in the ocamlopt back-end.  So,
```
let f x y z = Sys.opaque_identity (x *. y) +. z
```
will be compiled without an FMA even on platforms that support it.

There are additional costs to using `Sys.opaque_identity` here, in particular `Sys.opaque_identity` also prevents FP unboxing, so the intermediate product is heap-allocated.  But you asked for no optimizations whatsoever, right? :-)

That's a lot of comments for a closed issue...  Can we please agree that `Sys.opaque_identity` is a reasonable answer to the rather uncommon need expressed here?

**Comment by gasche** [comment]
If we agree that it should be possible for users to control this, and we decide that `opaque_identity` is our control mechanism, it would be nice to add a test in the testsuite checking that we get the expected double rounding. @let-def, would you maybe like to submit such a test?
