### ISSUE TITLE
opam switch create 4.12.0+trunk on macos arm fails with native opam

### ISSUE THREAD

**Issue by RBornat** [ocaml/ocaml#10330]
richard@Richard-Bornats-Mac-Mini ~ % opam switch install 4.12.0+trunk
[ERROR] Could not resolve set of base packages:
        The following dependencies couldn't be met:
          - ocaml-variants → ocaml-beta
              unmet availability conditions: enable-ocaml-beta-repository

Switch initialisation failed: clean up? ('n' will leave the switch partially installed) [Y/n] Y
richard@Richard-Bornats-Mac-Mini ~ % file `which opam`
/opt/homebrew/bin/opam: Mach-O 64-bit executable arm64

**Comment by gasche** [comment]
This looks like an opam-repository policy rather than an issue with the OCaml compiler. My understanding is that the message says that to use the development version (+trunk here means "in-development 4.12 branch"), you need to have enabled the [opam ocaml-beta repository](https://github.com/ocaml/ocaml-beta-repository) (see there for explanation on what that is). I suppose that either enabling this repository, or trying to use 4.12.0 rather than 4.12.0+trunk would fix the issue.

**Comment by jberdine** [comment]
Hi Richard, IIUC using the standard (non-trunk) versions 4.10.2 or 4.12 should work on mac arm64.

**Comment by RBornat** [comment]
Thanks both of you. I enabled beta (both set default and all switches, belt and braces). I can't create switch 4.12.0 -- it's not in list-available; if I try 4.12.0+trunk (which is available) I get 

richard@Richard-Bornats-Mac-Mini ~ % opam switch install 4.12.0+trunk                                                          

<><> Gathering sources ><><><><><><><><><><><><><><><><><><><><><><><><><><>  🐫 
[ERROR] The sources of the following couldn't be obtained, aborting:
          - ocaml-variants.4.12.0+trunk: Download command failed

Switch initialisation failed: clean up? ('n' will leave the switch partially installed) [Y/n] Y
richard@Richard-Bornats-Mac-Mini ~ % opam switch create !$
opam switch create 4.12.0+trunk

<><> Gathering sources ><><><><><><><><><><><><><><><><><><><><><><><><><><>  🐫 
[ERROR] The sources of the following couldn't be obtained, aborting:
          - ocaml-variants.4.12.0+trunk: Download command failed

Switch initialisation failed: clean up? ('n' will leave the switch partially installed) [Y/n] Y
richard@Richard-Bornats-Mac-Mini ~ % opam switch create 4.12.0
[ERROR] No compiler matching '4.12.0' found, use 'opam switch list-available' to see what is available, or use '--packages' to select packages
        explicitly.

**Comment by RBornat** [comment]
Whoops sorry. Egg on face. opam update did the trick (ouch!)
