### ISSUE TITLE
ocamlc.opt -config-var does not print newline, as sugested in -help output

### ISSUE THREAD

**Issue by olafhering** [ocaml/ocaml#10342]
````
ocamlc.opt -help
....
  -config-var  Print the value of a configuration variable, a newline, and exit
    (print nothing and exit with error value if the variable does not exist)
....
````
But no newline is appended:
````
ocamlc.opt -config-var  native_c_compiler | xxd -a
....
000000b0: 5345 545f 4249 5453 3d36 3420 2d44 5f52  SET_BITS=64 -D_R
000000c0: 4545 4e54 5241 4e54 20                   EENTRANT 
````
I have not checked if this is a regression.
````
ocamlc.opt --version
4.12.0
````

**Comment by dra27** [comment]
The documentation ended up out-of-sync with the code (https://github.com/ocaml/ocaml/pull/1430#issuecomment-338910725):

https://github.com/ocaml/ocaml/blob/359e1c49294a2633ebca982d06ce098217a61095/utils/misc.ml#L809-L815

The documentation should therefore be corrected, thanks!
