### ISSUE TITLE
Diverging behavior of ocamlc during typechecking

### ISSUE THREAD

**Issue by lthms** [ocaml/ocaml#10359]
Dear OCaml developers,

I wasn’t sure whether or not it was worth reporting, so feel free to close this issue. That being said, I ran into a diverging behavior while refactoring an API, that was quite annoying because Emacs just hanged (nothing `C-g` couldn’t fix, but still).

I have isolated the file responsible for my bad adventure in [a dedicated repository](https://labs.soap.coffee/bug-reports/ocamlc-diverges.git/about/).

[The file itself](https://labs.soap.coffee/bug-reports/ocamlc-diverges.git/tree/test.ml) is an OCaml module which builds an API on top of the `Map` functor.

The refactor is as follows:

1. Turn `type table = t Table.t` into `type table = (kind * t) list Table.t`
2. Update all but one `add`-like functions

When I fix the last `add`-like function, everything works fine (as mentioned in the README, which contains the required patch).

I haven’t tried to reproduce with another version than `4.12.0`, but could if you’d like.

And if you need more precisions, feel free to ask any questions you want!

**Comment by gasche** [comment]
Could you upload the faulty version (one of them) on which the type-checker appears to diverge?

**Comment by lthms** [comment]
It’s in the repository I linked in my message, [here](https://labs.soap.coffee/bug-reports/ocamlc-diverges.git/tree/test.ml) more precisely. The two links were maybe too closed to distinguished there were two.

**Comment by Octachron** [comment]
It doesn't look like `ocamlc` is diverging here: removing few of the `add_operator` and `add_keyword` , the code compiles but the type of `default` grows exponentially (or worse?).

**Comment by Octachron** [comment]
A back-of-the-enveloppe computation gives me a 12 days compilation time for the linked example. Did you really run this example that long?

**Comment by lthms** [comment]
I am not sure to understand your comment. I was able to compile the linked example by fixing the error in it, but I never waited more than dozens of seconds before assuming `ocamlc` was diverging.

**Comment by Octachron** [comment]
This is understandable. This is not  `ocamlc` diverging.

It is a known theoretical limitation: the size of types can increase exponentially (or worse) with the size of the program. This is generally not an issue for human-written code.
However in your case, the conjunction of the very long chain of applications, the use of `kind` as a fully polymorphic argument in `add_alias` and the refactoring error triggered this issue.

Typically, restraining the code to 20 `add_keyword`, the type checking already takes 20 seconds and the inferred mli file is around 170MB.

The problem itself cannot be solved without restricting the use of functions, I am thus closing the issue. Note that there are few possible ways to refactor the code to avoid future instance of this problem:
* an `add_keywords` function that adds a list of keywords
* using a label `~kind` in `add_alias`
* precising the type of `kind` in `add_alias`

**Comment by lthms** [comment]
Thanks for taking the time to explain exactly what was going on :).
