### ISSUE TITLE
cclib should properly parse the arguments

### ISSUE THREAD

**Issue by EduardoRFS** [ocaml/ocaml#10369]
When using `-cclib` with files with spaces, like on Windows `Program Files` folder, cclib will split the file in two and quote them, treating each part as a different side, even if quotes or `\` is used.

## Reproduction

```shell
touch a.ml b.ml
ocamlopt -a -cclib "\"/some file\"" a.ml -o a.cmxa
ocamlopt -linkall a.cmxa b.ml -o b.exe -verbose
```

## Suggestion

Ignore it and treat as a piece of string like what it happens with `-ccopt`, if no one is against I can open a PR for it.

## Related code

Seems also to be the case for `-dllib`

https://github.com/ocaml/ocaml/blob/cce52acc7c7903e92078e9fe40745e11a1b944f0/driver/compenv.ml#L410
https://github.com/ocaml/ocaml/blob/4f4e46af447364ed633dd6baf5f8a2ad79c5d081/driver/main_args.ml#L1827
https://github.com/ocaml/ocaml/blob/4f4e46af447364ed633dd6baf5f8a2ad79c5d081/driver/main_args.ml#L1974

**Comment by nojb** [comment]
This looks reasonable to me, but am not sure if there is some use-case for the current behaviour... cc @dra27 @gasche 
By the way one can work around the current behaviour when needed by using `-args` and `-args0`.

**Comment by xavierleroy** [comment]
The current behavior of `-cclib` is designed so that one can take the output of `pkg-config --libs`, e.g.
```
-lpangocairo-1.0 -lpango-1.0 -lgobject-2.0 -lglib-2.0 -lharfbuzz -lcairo
```
and slap a single `-cclib` option around it
```
-cclib '-lpangocairo-1.0 -lpango-1.0 -lgobject-2.0 -lglib-2.0 -lharfbuzz -lcairo'
```
and in the end it works.  

It looks like your suggestion breaks this behavior and could break a number of OPAM packages.

**Comment by EduardoRFS** [comment]
@xavierleroy that would still work, on `-ccopt` there is no quotes added, so if you do `-ccopt '-lpangocairo-1.0 -lpango-1.0'` it is passed to the compiler and linker as `gcc -lpangocairo-1.0 -lpango-1.0`.

**Comment by xavierleroy** [comment]
I'm afraid not because we also need to quote...  If you pass
```
-cclib 'C:\Program Files\foo\bar.lib'
```
you want the C compiler to receive `C:\Program Files\foo\bar.lib` as one argument, not as `C:\Program` then `Files\foo\bar.lib`.  No?

**Comment by EduardoRFS** [comment]
That is invalid today and will still be invalid with this suggestion, you would need to explicitly quote it. Having this as a requirement makes total sense, and is how `-ccopt` behaves. I didn't tried pkg-config on windows tho.

```shell
-cclib '"C:\Program Files\foo\bar.lib"'
```

**Comment by dra27** [comment]
> @xavierleroy that would still work, on `-ccopt` there is no quotes added

Is that a typo switching from `cclib` to `-ccopt`?

**Comment by dra27** [comment]
I'm not entirely convinced by a solution for Windows which is incredibly hard to encode... to send a quotes in an argument to an executable, cmd requires `-cclib """"C:\Program Files\foo\bar.lib""""`.

I'd more readily go for leaving `-cclib` as is and potentially having another a different parameter which is intended to pass a single library.

**Comment by EduardoRFS** [comment]
It's not a typo, `-ccopt` doesn't add quotes already, `-cclib` adds quotes and splits.

> cmd requires -cclib """"C:\Program Files\foo\bar.lib"""".

That's already the case for `-ccopt` and it just works, also tools like dune already behaves exactly as you would expect.

>  I'd more readily go for leaving -cclib as is and potentially having another a different parameter which is intended to pass a single library.

`-cclib` is about linker flags, like `-L`, `-l`, `-Wl,rpath` a flag intended to pass a single library would not solve it.

I would argue that on the current setup `-cclib` should never used, as the user cannot have spaces in any of his folders with code inside. Of course that's a bigger issue on Windows.

**Comment by dra27** [comment]
> It's not a typo, `-ccopt` doesn't add quotes already, `-cclib` adds quotes and splits.

Indeed, but something which was passed before to `-cclib` can't be arbitrarily changed to use `-ccopt`. `-ccopt` and `-cclib` do not simply differ by how they process their argument.

> > cmd requires -cclib """"C:\Program Files\foo\bar.lib"""".
> 
> That's already the case for `-ccopt` and it just works, also tools like dune already behaves exactly as you would expect.

I'm not sure I've expressed what I meant properly - your suggestion (if I understand correctly) is that you would like _literal quotes_ in the `-cclib` argument to be interpreted by the driver as "one argument". My point is that _passing_ literal quotes in the command line argument to ocamlopt involves quadruple quotes in the Windows shell. It may be old-fashioned, but I care how the compiler driver is invoked!

> > I'd more readily go for leaving -cclib as is and potentially having another a different parameter which is intended to pass a single library.
> 
> `-cclib` is about linker flags, like `-L`, `-l`, `-Wl,rpath` a flag intended to pass a single library would not solve it.

Not it's not - the manual states that `-cclib` is about `-l` flags. `-ccopt` is for `-L`, etc. Anyway, my point was to add an alternative `-cclib` which still behaves like `-cclib` (arguments at the end of the command) but parses like `-ccopt`, thus allowing the existing uses without introducing millions of double-quotes into manual uses of the driver.

> I would argue that on the current setup `-cclib` should never used, as the user cannot have spaces in any of his folders with code inside. Of course that's a bigger issue on Windows.

I agree that it might be useful to have a way of doing `-cclib` which doesn't split its argument (were OCaml not nearly 25 but in fact the same age as Dune it might be done differently), but the use of the current version is already stated in https://github.com/ocaml/ocaml/issues/10369#issuecomment-826119284.

**Comment by EduardoRFS** [comment]
> Indeed, but something which was passed before to -cclib can't be arbitrarily changed to use -ccopt. -ccopt and -cclib do not simply differ by how they process their argument.

Hmm I'm pretty sure if you ignore files containing quotes, that's actually true, because all the current examples cannot contain spaces anyway, so instead of adding it as `"x" "y"`, it would be added as `x y` which is almost always the same. Sure it's not always, but we can run it against opam to ensure of course.

> Not it's not - the manual states that -cclib is about -l flags. 

I didn't knew about it, BUT, the CLI says any `<opt>` which means one of them could change, but again, my proposal still accepts the current semantics enforced by the manual, always. As if the only valid use case of `-cclib` is `-lxyz`, this will still work without any quotes as it already does.

Line of the CLI message https://github.com/ocaml/ocaml/blob/trunk/driver/main_args.ml#L52

> thus allowing the existing uses without introducing millions of double-quotes into manual uses of the driver

That's a problem because then new tools will fail to target old versions of OCaml as the new flag is only supported by OCaml 4.13+.

> but the use of the current version is already stated in

Yes and this use still works. As I pointed out at https://github.com/ocaml/ocaml/issues/10369#issuecomment-826121417, I'm not proposing breaking it, it's an extension.

**Comment by EduardoRFS** [comment]
The good thing about just making it behave as `ccopt` is that old scripts which don't work on Windows when the user has spaces on the username will start to work magically when we release the new version with it.

And my hypothesis is that there is no valid use case of `-cclib` which will not be covered. Will try this against opam in the next days to gather data

**Comment by dra27** [comment]
> Hmm I'm pretty sure if you ignore files containing quotes, that's actually true, because all the current examples cannot contain spaces anyway, so instead of adding it as `"x" "y"`, it would be added as `x y` which is almost always the same. Sure it's not always, but we can run it against opam to ensure of course.

Yes, but all of that doesn't change the fact ccopt arguments appear _before_ modules and cclib arguments appear _after_ modules in the link order, which matters!

Running against opam repository is a (very useful) tool, but it's not a silver bullet. In particular, we're talking about linking here, and opam is overwhelmingly libraries, not programs and the Windows coverage still isn't yet there. Other code also exists!

> That's a problem because then new tools will fail to target old versions of OCaml as the new flag is only supported by OCaml 4.13+.

That's always going to be the case - supporting old compilers to do new things can be dealt with via back-porting if wanted in opam, but it's not a consideration on the change (that said, please don't get the impression I don't care at all [about our old compilers](https://github.com/metastack/ocaml-legacy) 😉)

> Yes and this use still works.

Right - my comment was with reference to "I would argue that on the current setup `-cclib` should never used"! I'm for solving this problem, but to have to write `ocamlopt -a -o foo.cmxa bar.cmx -cclib """"C:\Program Files\Strangely installed library\baz.lib""""` isn't the solution I want to get behind 🙂

**Comment by xavierleroy** [comment]
Are you aware that a command-line argument ending in `.a` or `.lib` (depending on platform) is treated as a C library and stored in .cma/.cmxa archive files for later linking?  So,
```
ocamlopt -a -o foo.cmxa bar.cmx "C:\Program Files\Strangely installed library\baz.lib"
```
should do the job nicely, no need for a new option or deep quoting.

**Comment by dra27** [comment]
@xavierleroy - no, I'd forgotten that, in amongst all this!

It requires extra processing (but what on Windows doesn't?!), but unless we start having to support `"-llibrary with spaces"` to get "liblibrary with spaces.lib" (I haven no idea why anyone would do that to themselves...!), I agree that the motivation for this evaporates (in fact, directly specifying the `.lib` file is probably why I don't recall ever having hit this...)

**Comment by EduardoRFS** [comment]
@dra27 

> cclib arguments appear after modules in the link order

That's still going to be the case, the order will not be changed at all. The only thing is how it will be stored in the `.cmxa` as a single string per `-cclib` and the quotes removed. It's not an alias to `-ccopt` they're still different references and will still be on the same place.

If you want to support Windows I doubt that you will be making batch scripts, you will probably be using a Makefile / dune / ocamlbuild and others. Where the problem of `"""` doesn't exists.

That's already the case for `ccopt` if you want to do a `-I` on Windows you need to do `ocamlopt -a -o foo.cmxa -ccopt "-I"""C:\Program Files\x""""` this is how it works today.

@xavierleroy no I didn't knew, that will be definitely useful, but I still need to keep an additional conditional, as on Unix-like I can just do `-cclib "-L/folders -llib"`. With this change it would also works for Windows. Also the `-rpath` thing

Again this actually works on Linux even if it's not on the manual, but the CLI suggests it.

**Comment by EduardoRFS** [comment]
Sub comment on this, the argument of -cclib is only for `-l` is really weird, especially because even the tools that the compiler uses it in the more general way.

As it can be seen on flexdll
https://github.com/alainfrisch/flexdll/blob/7aacd75e33bd34d27109bc765f40f46932716560/Makefile#L122
