### ISSUE TITLE
FFI: forced to discard "const" qualifier

### ISSUE THREAD

**Issue by gerdstolpmann** [ocaml/ocaml#10367]
This code results in a warning from clang "passing 'const char *' to parameter of type 'void *' discards qualifiers":
```
value v_request = caml_alloc_string(request_len);
memcpy(String_val(v_request), request, request_len);
```
The string may contain zeros, so using `caml_copy_string` is not possible.

I understand the intent of the `const` qualifier introduced by `String_val`, but the FFI is missing a function to create strings from arbitrary memory regions (e.g. `caml_copy_string_from_mem`), so you have to use a typecast so far, which is undesirable.

**Comment by kit-ty-kate** [comment]
>  but the FFI is missing a function to create strings from arbitrary memory regions

Have you tried `Bytes_val(v_request)` instead of `String_val(v_request)` ? I believe this should be what you are looking for.

**Comment by yallop** [comment]
I think you want [`caml_alloc_initialized_string`](https://github.com/ocaml/ocaml/blob/b9acbd671163c7e614a9e86875e3ba4c69619533/runtime/caml/alloc.h#L38).

**Comment by gerdstolpmann** [comment]
thanks, @yallop I was overlooking this
