### ISSUE TITLE
Print inferred variance

### ISSUE THREAD

**Issue by lavib** [ocaml/ocaml#10375]
Current situation for variance inference is not linear and can lead to errors even to the seasoned developer: in a type declaration, declared variance is checked (but not constrained) except if there are constraint on the type declared, in this case they are mandatory. This is event worse in a class declaration, where the constraint may appear from the code, without writing it directly.

If changing this is probably difficult, printing the inferred variance (covariant, contravariant or bivariant) in the toplevel and with option -i may help the developer.

I see several benefits:
- In some cases, when the inferred variance is not the expected one, it may reveal a bug
- it would more make more visible that declared variance is just checked
- it remins the developer to write it for the abstract type in the mli
- it sometimes it also helps to understand quicker the type

I see however two drawbacks
- for beginner, this reveal too early an advanced feature. I don't see this as a real issue, but maybe some do.
- more importantly, this means finding a good way to print bi-variant variables, with a consensus in it... right now I see 4 options
  1. `#` a new symbol, neither `+` or `-`
  2. `_` with the meaning unused variable
  3. both `+-` and `-+` well two chars, but bi-variant variables are not so common, and at least meaning is explicit
  4. `?` cause it is opposite to `!`

**Comment by garrigue** [comment]
I do see some value in printing this information for type-debugging purposes, but as you wrote yourself printing it always would be noisy and particularly confusing for beginners.
Which means that we would probably need a new flag, such as `-print-variance`.
This is not the only case  where a flag could change the printing of types: we already have `-short-paths`.
However, this raises the question of providing a more regular structure for this kind of flags.

The printing of bi-variant variables raises another question: independently of the symbol chosen, if we can print it, then we should probably accept it as input, and properly handle it. This should not be too difficult, maybe more a problem of doing enough testing to be sure that the current machinery already handles it properly.

For the notation, `?` looks nice, but bi-variance is not the opposite of `!`, which denotes injectivity. In particular, a parameter can be both bi-variant and injective:
```
type ?!'a t = A
```
Currently, invariance is denoted by the absence of annotation for abstract and private row types, and there is no notation to print invariance when it is inferred. I suppose this means that with `-print-variance` we would print all type definitions as though they were abstract, but the change of meaning for the absence of annotation might be confusing if one does not check the flag.
