### ISSUE TITLE
.cds file generation 4.11/4.12

### ISSUE THREAD

**Issue by progman1** [ocaml/ocaml#10370]
In using -output-complete-exe I see that the generation of the .cds file goes to /tmp (randomly named but not cleaned up) and the way to have it retained is by giving the output file a .c extension. Why generate a .cds at all unless it is to be used?
However, since the obj_file name is derived from the c_file this results in a C compiler  command that specifies an input of the same name as the output, which then fails.

for the first issue perhaps an extra argument to link_bytecode_as_c of basename for
the exclusive use of the .cds maker.
for the second issue, it doesn't make much sense for a .c output on an executable anyway.

**Comment by nojb** [comment]
Thanks for the report! Indeed this is a bug, since `.cds` files are useless with `-output-complete-exe`. Fix in #10371.
