### ISSUE TITLE
ocamldebug doesn't work on Cygwin64

### ISSUE THREAD

**Issue by kcrary** [ocaml/ocaml#10378]
On Cygwin64 the debugger fails to fork threads:

$ cat foo.ml

let () = ()

$ ocamlc -g foo.ml

$ ocamldebug camlprog
        OCaml Debugger version 4.10.0

(ocd) step
Loading program...       0 [main] ocamlrun 2275 child_info_fork::abort: address space needed by 'dllunix.so' (0x400000) is already occupied
Unix error: 'fork' failed: Resource temporarily unavailable

It looks like this might be the same problem as: https://github.com/ocaml/opam/issues/3785

**Comment by xavierleroy** [comment]
OCaml version < 4.12 under Cygwin64 is seriously crippled  by DLL loading issues.  #9927 fixed these issues but is available only in OCaml 4.12.0 and up.  If you installed `opam` as I suggested earlier, just do `opam switch create 4.12.0` and everything will work better.
