### ISSUE TITLE
Documentation of Unix.kill: Sys.sigint works on Windows

### ISSUE THREAD

**Issue by jfehrle** [ocaml/ocaml#10415]
The doc says "On Windows: only the Sys.sigkill signal is emulated.", but I just tried this on Windows with Sys.sigint in CoqIDE.  It works, so it appears this statement is inaccurate.  Also "supported" seems like better wording than "emulated"; the latter raises questions of how emulation is different from Linux behavior.

As seen [here](https://ocaml.org/api/Unix.html#1_Basicfileinputoutput) in the description of "kill".

**Comment by dra27** [comment]
Were using Cygwin?
https://github.com/ocaml/ocaml/blob/5fbd6e15c8ccffeb533389e4695223fbc9370b4b/otherlibs/win32unix/unix.ml#L555-L557

**Comment by dra27** [comment]
"Emulation" is appropriate - there are no signals on Windows, so it is not sending the kill signal (i.e. it is not in fact calling [`kill(2)`](https://linux.die.net/man/2/kill)) but rather using a different Windows mechanism to emulate the behaviour of `kill(pid, SIGKILL)`

**Comment by jfehrle** [comment]
> Were using Cygwin?

I ran the Coq 8.12 release on Windows.  That used to be cygwin on Windows AFAIK, perhaps @zimmi48 or @msoegtropIMC recalls the details.  (I've been developing on WSL2 for over a year, so I don't do Windows builds on my system any more.)

The call with `sigint` is in `coq.ml`, and it was last changed in 2012.

`let interrupter = ref (fun pid -> Unix.kill pid Sys.sigint)`

**Comment by dra27** [comment]
Right, and on Windows that ref gets overwritten in OS-specific start-up to call the `win32_interrupt` stub, which correctly sends CTRL+C to the coqtop console, not calling `Unix.kill`

**Comment by jfehrle** [comment]
OK.  Do you know if this works for all the defined signals?

**Comment by dra27** [comment]
No - what Coq is doing doesn't even generalise to all applications.
