### ISSUE TITLE
"is not a compiled interface for this version of OCaml" error should report actual versions

### ISSUE THREAD

**Issue by JasonGross** [ocaml/ocaml#10425]
When I see the error message
```
File "/tmp/.coq-native/Ntmpychg3keq.native", line 1:
Error: /github/workspace/builds/coq/coq-failing/_install_ci/lib/coq/../coq-core/kernel/nativevalues.cmi
       is not a compiled interface for this version of OCaml.
It seems to be for an older version of OCaml.
Error: Native compiler exited with status 2
```
(full log [here](https://github.com/coq-community/run-coq-bug-minimizer/runs/2649891303?check_suite_focus=true#step:5:41763)) this is not that useful if I believe I have only one version of OCaml installed, and I am not the one who invoked OCaml (e.g., it was invoked indirectly via Coq).  It would be much more useful if OCaml would report the current version of OCaml and made a best effort guess at reporting the version of OCaml that the interface was compiled for, and I got a message like "is not a compiled interface for this version of OCaml (4.XX.YY).  It seems to be for an older version of OCaml (likely 4.ZZ.WW)."

**Comment by xavierleroy** [comment]
I remember @gasche looking at this issue a long time ago, but I may be wrong.  It would be much easier to report version numbers if magic numbers were based on version numbers, as investigated in #9645.  

Generally speaking, this is one of those features that require a lot of code yet are rarely useful (it's exceedingly rare to run into this issue if you're doing `make clean` or  `git clean -f -x` religiously), so don't hold your breath.

**Comment by JasonGross** [comment]
Even if you just reported both magic numbers and I had to go digging though git history to discover the versions, that would (have) be(en) enormously helpful.

I am quite confused about this error message, because I'm running on a CI in a docker image where there's only a single version of OCaml being used globally, AFAIK.  I am downloading artifacts generated by two other CI jobs, but AFAICT they both use the same docker image and same opam switch as I'm using, so the generated OCaml files should all be compatible.

**Comment by gasche** [comment]
> I remember @gasche looking at this issue a long time ago, but I may be wrong.

I did, and the report above is a result of the work at that time. Otherwise it would just have said "... is not a compiled interface".

We could store a mapping in the code from old magic numbers to the corresponding OCaml versions (I think it would not be a lot of work to add; @JasonGross, is this something that you may be interested in contributing?), but of course that would only work in the case where the wrong header is from an older version, not from a more recent version.

(Indeed #9645 is a simpler approach, but it died from a thousand cuts; getting this right is *hard*.)

**Comment by JasonGross** [comment]
> We could store a mapping in the code from old magic numbers to the corresponding OCaml versions (I think it would not be a lot of work to add; @JasonGross, is this something that you may be interested in contributing?)

Sure, though it may be faster for someone else to contribute this, since I don't know the codebase at all.  I've constructed such a table here, though:
```
$ cat ./find-magic.sh
```
```bash
#!/usr/bin/env bash

set -e -o pipefail

commit=trunk
files=("runtime/caml/exec.h" "byterun/caml/exec.h" "byterun/exec.h")
echo "Magic Number | First Commit | First Tag Containing Commit | File Name Containing Definition"
echo "-------------|--------------|-----------------------------|--------------------------------"
while true; do
    blame_text="$(git blame $commit^ "${files[0]}" | grep '#define EXEC_MAGIC ' | sed s'/^\([^ ]*\).*#define EXEC_MAGIC "\([^"]*\)".*/\2 | \1/g')"
    commit="$(echo "${blame_text}" | sed 's/ //g' | cut -d"|" -f2)"
    while ! git cat-file -e "$commit:${files[0]}" 2>/dev/null; do
        files=("${files[@]:1}") # https://unix.stackexchange.com/a/68323/45323
    done
    echo "${blame_text} | "'`'"$(git name-rev --tags --name-only $commit)"'`'" | ${files[0]}"
done
```
```
$ ./find-magic.sh
```

Magic Number | First Commit | First Tag Containing Commit | File Name Containing Definition
-------------|--------------|-----------------------------|--------------------------------
Caml1999X029 | 55973d1203 | `4.12.0-alpha1~8` | runtime/caml/exec.h
Caml1999X027 | e9bb827ff7 | `4.11.0+alpha1~263` | runtime/caml/exec.h
Caml1999X025 | 6da5262dd1 | `4.09.0+beta1~214` | runtime/caml/exec.h
Caml1999X024 | 58f9eff953 | `4.09.0+beta1~217` | runtime/caml/exec.h
Caml1999X023 | c10b2edccc | `4.08.0+beta1~719` | byterun/caml/exec.h
Caml1999X011 | 2b9f94b69b | `4.02.0+beta1~260` | byterun/exec.h
Caml1999X010 | 57fe3746f6 | `4.02.0+beta1~271` | byterun/exec.h
Caml1999X011 | dd7bd5b339 | `4.02.0+beta1~272` | byterun/exec.h
Caml1999X010 | d802a51be6 | `4.02.0+beta1~404^2~13` | byterun/exec.h
Caml1999X009 | f31325cbaf | `4.02.0+beta1~404^2~25` | byterun/exec.h
Caml1999X008 | 9d19bcf441 | `3.08.0~160` | byterun/exec.h
Caml1999X007 | 320487c59f | `3.04~98` | byterun/exec.h
Caml1999X006 | ee2c3d5bc6 | `3.00~226` | byterun/exec.h
Caml1999X005 | 45a18236df | `2.99~34` | byterun/exec.h
Caml1999X004 | fd8ea59807 | `2.00~159` | byterun/exec.h
Caml1999X003 | ea8fe59ea0 | `2.00~184` | byterun/exec.h
Caml1999X002 | c99916fdb9 | `1.06~187` | byterun/exec.h
Caml1999X001 | 61bd8ace6b | `csl-1.06~261` | byterun/exec.h

**Comment by JasonGross** [comment]
Ah, but it seems that maybe I'm looking in the wrong file?  Should I be looking in utils/config.mlp instead?

**Comment by JasonGross** [comment]
If I use `files=("utils/config.mlp")` and `blame_text="$(git blame $commit^ "${files[0]}" | grep 'cmxs_magic_number = ' | sed s'/^\([^ ]*\).*cmxs_magic_number = "\([^"]*\)".*/\2 | \1/g')"`, then I get

Magic Number | First Commit | First Tag Containing Commit | File Name Containing Definition
-------------|--------------|-----------------------------|--------------------------------
Caml1999D029 | 55973d1203 | `4.12.0-alpha1~8` | utils/config.mlp
Caml1999D027 | e9bb827ff7 | `4.11.0+alpha1~263` | utils/config.mlp
Caml1999D025 | 6da5262dd1 | `4.09.0+beta1~214` | utils/config.mlp
Caml1999D024 | 58f9eff953 | `4.09.0+beta1~217` | utils/config.mlp
Caml1999D023 | 7c416d1c01 | `4.08.0+beta1~722` | utils/config.mlp
Caml1999D022 | 8ba70ff194 | `4.07.0+beta1~599` | utils/config.mlp
Caml2007D002 | 1ce29d9bfc | `4.02.0+beta1~125` | utils/config.mlp
Caml2007D001 | 95104b3924 | `4.02.0+beta1~154` | utils/config.mlp
Caml2007D002 | 521ac0213a | `4.02.0+beta1~157` | utils/config.mlp
Caml2007D001 | 2adec7d747 | `3.12.0+beta1~105` | utils/config.mlp

Using instead `blame_text="$(git blame $commit^ "${files[0]}" | grep 'cmi_magic_number = ' | sed s'/^\([^ ]*\).*cmi_magic_number = "\([^"]*\)".*/\2 | \1/g')"` gives

Magic Number | First Commit | First Tag Containing Commit | File Name Containing Definition
-------------|--------------|-----------------------------|--------------------------------
Caml1999I029 | 55973d1203 | `4.12.0-alpha1~8` | utils/config.mlp
Caml1999I027 | e9bb827ff7 | `4.11.0+alpha1~263` | utils/config.mlp
Caml1999I025 | 6da5262dd1 | `4.09.0+beta1~214` | utils/config.mlp
Caml1999I024 | 58f9eff953 | `4.09.0+beta1~217` | utils/config.mlp
Caml1999I023 | 7c416d1c01 | `4.08.0+beta1~722` | utils/config.mlp
Caml1999I022 | 8ba70ff194 | `4.07.0+beta1~599` | utils/config.mlp
Caml1999I021 | d5a6e50ebe | `4.04.0+beta1~54^2` | utils/config.mlp
Caml1999I020 | 1d196f4ddd | `4.03.0+beta1~564` | utils/config.mlp
Caml1999I019 | 7fa3f30114 | `flambda_fork_point~201` | utils/config.mlp
Caml1999I018 | e3ad818fb5 | `flambda_fork_point~221` | utils/config.mlp
Caml1999I017 | 1ce29d9bfc | `4.02.0+beta1~125` | utils/config.mlp
Caml1999I016 | 95104b3924 | `4.02.0+beta1~154` | utils/config.mlp
Caml1999I017 | 521ac0213a | `4.02.0+beta1~157` | utils/config.mlp
Caml1999I016 | d802a51be6 | `4.02.0+beta1~404^2~13` | utils/config.mlp
Caml1999I015 | f59df29db4 | `4.02.0+beta1~662` | utils/config.mlp
Caml1999I014 | d39d43e55f | `4.01.0+beta1~768` | utils/config.mlp
Caml1999I013 | 304dba8a0f | `4.00.0+beta1~422^2~104` | utils/config.mlp
Caml1999I012 | 1e5b4a4857 | `3.12.0+beta1~382` | utils/config.mlp
Caml1999I011 | b2157a6afb | `3.11.0-beta1~439` | utils/config.mlp
Caml1999I010 | 762a006652 | `3.08.0~142` | utils/config.mlp
Caml1999I009 | a1bcfad7c5 | `3.06~31` | utils/config.mlp
Caml1999I008 | 02ca0f87f8 | `3.02~95` | utils/config.mlp
Caml1999I007 | 83ca813e4b | `3.01~160` | utils/config.mlp
Caml1999I006 | 7dfe9784b7 | `3.00~151` | utils/config.mlp
Caml1999I005 | 296fc05470 | `2.99~51` | utils/config.mlp
Caml1999I004 | d1561bbfe8 | `2.00~69` | utils/config.mlp
Caml1999I003 | 9f30d68f00 | `1.06~219` | utils/config.mlp
Caml1999I002 | 6eb8978908 | `csl-1.10~97` | utils/config.mlp
Caml1999I001 | 61bd8ace6b | `csl-1.06~261` | utils/config.mlp
