### ISSUE TITLE
OCaml 32-bit executable can't display Unicode characters in Windows 10 console, the same exe as 64-bit has no problems

### ISSUE THREAD

**Issue by ALIENQuake** [ocaml/ocaml#10436]
Hi,

The [WeiDU](https://github.com/WeiDUorg/weidu/) is OCaml executable, it's compiled as 32-bit and 64-bit

- this program displays strings at the Windows 10 20H1 console
- strings are loaded from UTF8 files
- 64-bit has no problems to display proper characters
- 32-bit executable display garbage

What might be the reason? Source code? Lack of specific compiler flags for 32-bit?

Links:

https://github.com/WeiDUorg/weidu/blob/master/Makefile
https://github.com/WeiDUorg/weidu/blob/master/sample.Configuration
https://github.com/WeiDUorg/weidu/blob/master/Makefile.ocaml

**Comment by gasche** [comment]
Thanks for the report! This sounds like a question for @nojb or @dra27 (the latter being in holidays right now). Could you let us know about which OCaml version you are using, how you installed it, and which of the various Windows ports are being used? (Currently: MSVC, Mingw-64, or Cygwin; see [README.win32.adoc](https://github.com/ocaml/ocaml/blob/trunk/README.win32.adoc) ).

P.S.: I never knew about weidu, sounds like a fun program with an active community. I would encourage you to post a message describing the project to the [OCaml Discourse forum](https://discuss.ocaml.org/), to make members of the OCaml community aware that it exists -- who knows, you may attract contributors. In particular, this is an old project with an old Makefile build system; if you ever want help in trying to use more standard tooling, Discourse would be the right place to ask.

**Comment by xavierleroy** [comment]
Unicode and the Windows console is a long story, see #1408 and #1444.  @dra27 is the expert here.

**Comment by ALIENQuake** [comment]
@xavierleroy But why 32-bit doesn't work when 64-bit works correctly? @dra27 Can you please provide feedback? Is there any kind of workaround?

**Comment by ALIENQuake** [comment]
@nojb Since dra27 is on vacation, I'm tagging you also.

**Comment by nojb** [comment]
> @nojb Since dra27 is on vacation, I'm tagging you also.

Nothing comes to mind right now. But as @gasche said it would be useful to know how is OCaml configured and what version of OCaml is used (`mingw`, `msvc` or `Cygwin`).

**Comment by ALIENQuake** [comment]
@nojb Sorry, the Windows compilation is made via Cygwin. As for OCaml configuration, I can 'extract' those from the Makefile, Configuration and Makefile.ocaml files that I've linked but I need to know what you are looking for.

**Comment by nojb** [comment]
Do you have a reproduction case? Or at least a screenshot?

**Comment by ALIENQuake** [comment]
@nojb Sure:
![image](https://user-images.githubusercontent.com/365255/120115451-fd54c600-c183-11eb-8300-c749cee98ade.png)

[WeiDU-UTF8-Example.zip](https://github.com/ocaml/ocaml/files/6566703/WeiDU-UTF8-Example.zip)

**Comment by nojb** [comment]
> @nojb Sure:

Thanks. Which version of OCaml was used to compile the executable? And what is the compilation command? I tried running `make` from the root of the repository with the OCaml binaries in the `PATH` but it does not seem to work.

**Comment by ALIENQuake** [comment]
@nojb 
I'm afraid that creating the correct build environment for this project will not be a simple task. The [instructions](https://weidu.org/~thebigg/new_compile.html) require few manual steps and could be confusing. In order to avoid frustration, I can provide a 2GB archive with a pre-configured Cygwin. Let me know if you want to receive full package.

opam list output:

```
$ opam list
# Packages matching: installed
# Name         # Installed     # Synopsis
base-bigarray  base
base-threads   base
base-unix      base
ocaml          4.09.0          The OCaml compiler (virtual package)
ocaml-config   1               OCaml Switch Configuration
ocaml-variants 4.09.0+mingw64c pre-compiled 4.09.0 release (mingw64)
```
I don't know male/OCaml build chain, attempt to provide compilation flags:
`ocamlopt -unsafe-string -w y -ccopt -w ...`
````
.opam\\4.09.0+mingw64c\\bin/ocamlopt.opt -unsafe-string -o obj/x86_WIN32/weidu.asm.exe unix.cmxa str.cmxa -cclib -lunix -cclib -lcamlstr obj/x86_WIN32/weidu_resources.o ...
````

**Comment by nojb** [comment]
I investigated a bit. If you do `chcp 65001` (setting code page to UTF-8) in your `cmd.exe` before running the program it seems to work OK. Maybe there is a difference how the code page is set by default between 32-bit and 64-bit? I don't have time to dig deeper at the moment, unfortunately. But it doesn't seem to be a bug in OCaml at first sight (but perhaps there is something to improve on our side -- we will have to wait for @dra27's return from holiday for more on this).

It would be great if you could confirm if this workaround fixes the immediate issue, in any case.

**Comment by ALIENQuake** [comment]
@nojb Yep, adding `chcp 65001` before launching weidu32 is a known workaround. This however has unpredicted consequences, especially on older Windows versions so it can't be used. FWIW, the initial codepage for both 32-bit and 64-bit executable is 852. Let me know if you want more information.

**Comment by dra27** [comment]
The 32-bit executable you link has been compiled with OCaml 4.05.0 and the 64-bit executable with 4.07.1; the Unicode support was added in 4.06, hence the observed difference in behaviour.

**Comment by ALIENQuake** [comment]
@dra27 Big thanks for investigation. Success!
![image](https://user-images.githubusercontent.com/365255/121081536-23f6aa80-c7dd-11eb-8c68-21bd2b76ca32.png)
