### ISSUE TITLE
4.12.0 regression for #cd and #use 

### ISSUE THREAD

**Issue by vrotaru** [ocaml/ocaml#10442]
I found a regression in 4.12.0 when OCaml in "scripting" mode, so to speak. Example below.

First the "project"
```Con
> tree
└── test
    ├── test.ml
    └── version.ml

> cat test/test.ml 
#cd "test"
#directory "."
#use "version.ml"

> cat test/version.ml 
let _ = print_endline Sys.ocaml_version
```
And now to the actual bug.
```Con
> opam switch 4.11.2
> ocaml test/test.ml
4.11.2
> opam switch 4.12.0
> ocaml test/test.ml
File "./test/test.ml", ine 1:
Error: I/O error: test/version.ml: No such file or directory
[2]> 
```

In case it helps, if I move the `test.ml` to parent folder and run `ocaml test.ml` everything runs fine

Attaching the relevant parts of `strace` output 

[strace-4.11.txt](https://github.com/ocaml/ocaml/files/6600678/strace-4.11.txt)
[strace-4.12.txt](https://github.com/ocaml/ocaml/files/6600679/strace-4.12.txt)

**Comment by dra27** [comment]
This has been caused by https://github.com/ocaml/ocaml/pull/9611 - this example should definitely go in the testsuite, thanks!
