### ISSUE TITLE
Type of caml_send in Cmm

### ISSUE THREAD

**Issue by nandor** [ocaml/ocaml#10460]
The type of the cache argument seems to be fixed to `Val` in https://github.com/ocaml/ocaml/blob/trunk/asmcomp/cmm_helpers.ml#L1868, however the argument is computed as an address in the helper function generating calls to it at https://github.com/ocaml/ocaml/blob/trunk/asmcomp/cmm_helpers.ml#L787 . Shouldn't the type of the cache then be `type_addr` instead of `type_val`?

**Comment by lthls** [comment]
Thank you for the report. I think passing `Addr` arguments to a function is very dangerous, so I proposed a different fix in #10461.

**Comment by nandor** [comment]
Thank you, this solution fixes my issue as well.
