### ISSUE TITLE
Minor improvement in module Switch

### ISSUE THREAD

**Issue by mhrde** [ocaml/ocaml#10465]
Hello OCAML team,

on inspection of the code in **lambda/switch.ml** I found a slight unsymmetry in the function **case_append**.
The low and high boundaries are changed to close gaps, if neighbouring cases have the same action.
This is done, if the first case list has more then one case or if the second case list has more then **two** cases.
In order to also optimize the latter for exactly two cases, one comparison must be changed as done in the
[lambda-switch.patch.gz](https://github.com/ocaml/ocaml/files/6677664/lambda-switch.patch.gz).

This might slightly produce better code.

Kind regards,

Michael Rose

**Comment by gasche** [comment]
The proposed patch is as follows:

```diff
diff -Naur ocaml/lambda/switch.ml ocaml-patched/lambda/switch.ml
--- ocaml/lambda/switch.ml      2021-06-18 16:19:45.050255694 +0200
+++ ocaml-patched/lambda/switch.ml      2021-06-18 16:25:05.844442177 +0200
@@ -269,7 +269,7 @@
             end else
               l1
           and h =
-            if 1 < len2-1 then begin
+            if 1 <= len2-1 then begin
               let l,_,_ = c2.(1) in
               if h2+1 < l then
                 l-1
```

(Note: I would recommend using git, making commits, and then using `git format-patch` if you want a patch file.)

**Comment by gasche** [comment]
The proposed patch looks correct to me. There are two symmetric tests

```ocaml
let len1 = Array.length c1
and len2 = Array.length c2 in
let l1,h1,act1 = c1.(Array.length c1-1)
and l2,h2,act2 = c2.(0) in
if act1 = act2 then
  let r = Array.make (len1+len2-1) c1.(0) in
  for i = 0 to len1-2 do
    r.(i) <- c1.(i)
  done ;

  let l =
    if len1-2 >= 0 then begin
      let _,h,_ = r.(len1-2) in
      if h+1 < l1 then
        h+1
      else
        l1
    end else
      l1
  and h =
    if 1 < len2-1 then begin
      let l,_,_ = c2.(1) in
      if h2+1 < l then
        l-1
      else
        h2
    end else
      h2
   in
  (* ... *)
end else (* .... *)
```

The first test `len1-2 >= 0` checks that the following array access `r.(len1-2)` is valid. The second test `1 < len2-1` checks that the following array access c2.(1) is valid, but it is too conservative, `1 < len2` (or `1 <= len2-1` as suggested, which I find less clear) would be correct and indeed produce slightly better code in case `c2` has two elements.
