### ISSUE TITLE
Missing "destructive substitution of types in module signature" in language specification

### ISSUE THREAD

**Issue by raphael-proust** [ocaml/ocaml#10483]
The OCaml manual defines module signatures as

```
module-type:
          modtype-path
        | 'sig' { specification [';;'] } 'end'
        | 'functor' '(' module-name ':' module-type ')' '->' module-type
        | module-type '->' module-type
        | module-type 'with' mod-constraint { 'and' mod-constraint }
        | '(' module-type ')'
```
and module constraints as 

```
mod-constraint:
          'type' [type-params] typeconstr type-equation { type-constraint }
        | 'module' module-path '=' extended-module-path
```

And the type equation as

```
type-equation:
          '=' typexpr
```

It seems like this spec does not allow the form `'with' 'type' [type-params] typeconstr ':=' typexpr`.

**Comment by Octachron** [comment]
Note that I tried to mention this in the text just below the specification:

> See also the following language extensions: recovering the type of a module, substitution inside a signature, type-level module aliases, attributes, extension nodes and generative functors.

Did you miss this paragraph or is it not clear that `substitution inside a signature` cover this point?

**Comment by raphael-proust** [comment]
I missed that text because I was probably focusing too much on the formal grammar rather than the accompanying text. IIRC (sorry it's taken me some time to respond) I was CTRL+F on the string ":=" because in this specific instance of checking out the documentation I already knew what I was looking for.
