### ISSUE TITLE
Bug (?) in Simplif.simplify_exits

### ISSUE THREAD

**Issue by stedolan** [ocaml/ocaml#10495]
@lpw25 and I noticed that Simplif.simplify_exits does not preserve semantics when `Lstaticraise` is used in non-tail position, transforming this:
```
(catch (seq (exit 0) (raise exn/4)) with (0) 42)
```
which evaluates to 42, into this:
```
(seq 42 (raise exn/4))
```
which raises an exception.

This doesn't seem to cause an actual miscompilation, since as far as we can tell the compiler never produces an `Lstaticraise` except in tail position of the corresponding `Lstaticcatch`.

Still, this seems dubious, so I think we should do one of two things:

  - if `Lstaticraise` can only be used in tail position, then this invariant should be noted and enforced by some check.
  - if `Lstaticraise` can be used outside tail position, then the optimisation in Simplif is broken and should be fixed.

(Either seems fine to me, but at the moment I don't actually know whether this invariant is intended)

**Comment by xavierleroy** [comment]
Unless I'm mistaken, a `staticexit` in non-tail-position implies that the code "after" the `staticexit` is dead code.  (Remember: `staticexit` is essentially a block-scoped `goto`.)

Since `staticexit` and `staticcatch` are introduced by the compiler (as opposed to being written out explicitly by the programmers), I very much hope that the compiler never introduces dead code via a non-tail `staticexit` !  

If it is cheap to check this in an assertion, I'm OK with it.  But there's no reason to add a bunch of code to check an invariant "`staticexit` is always in tail position" that must be true by construction.

**Comment by gasche** [comment]
If I remember correctly, it is possible to use `staticraise` across a `try .. with` handler (`staticraise` compilation keeps track of their nesting and pops the correct number of exception handlers before jumping), so technically not in tail position.

(@alainfrisch also played with an optimization, https://github.com/ocaml/ocaml/pull/260, that would turn some locally-resolvable `raise` into `staticraise`; the `raise` may be in non-tail position, although I guess this optimization could also take care of cleaning up the dead code after it in this case.)

**Comment by stedolan** [comment]
> Unless I'm mistaken, a staticexit in non-tail-position implies that the code "after" the staticexit is dead code. (Remember: staticexit is essentially a block-scoped goto.)

My example is a bit silly, but it's not true in all cases that a staticexit in non-tail-position is useless, because the staticexit might be on one side of a conditional. Consider:
```
(catch
  (seq
    (if x (exit 0) 1)
    (raise exn))
  with (0) 42)
```
No part of this is dead, but it is not equivalent to:
```
(seq
  (if x 42 1)
  (raise exn))
```

**Comment by stedolan** [comment]
> (@alainfrisch also played with an optimization, #260, that would turn some locally-resolvable raise into staticraise; the raise may be in non-tail position, although I guess this optimization could also take care of cleaning up the dead code after it in this case.)

It depends on the exact order that Simplif optimisations are run in, but I think some code using this locally-resolvable-exception feature would be miscompiled by this optimisation, turning:
```ocaml
let f x = 
  let exception Negative in
  try
    if x < 0 then raise Negative;
    x + 1
  with
    Negative -> 0
```
into:
```ocaml
let f x =
  if x < 0 then 0;
  x + 1
```
giving a different answer for `f (-3)`.

**Comment by stedolan** [comment]
Closing this because the issue can't come up in the Lambda patterns that ocaml actually generates.
