### ISSUE TITLE
Fatal error: exception Unix.Unix_error(Unix.EINVAL, "out_channel_of_descr", "")

### ISSUE THREAD

**Issue by SuperLeilia** [ocaml/ocaml#10509]
I'm running a project using Ocaml. But it returned 
**Fatal error: exception Unix.Unix_error(Unix.EINVAL, "out_channel_of_descr", "")** 
,which I didn't figure out the reason.

# Packages under opam FYI:
Packages matching: installed
Name Installed Synopsis
base-bigarray base
base-threads base
base-unix base
batteries 3.3.0 A community-maintained standard library extension
conf-findutils 1 Virtual package relying on findutils
conf-gmp 3 Virtual package relying on a GMP lib system installation
coq 8.13.2 Formal proof management system
num 1.4 The legacy Num library for arbitrary-precision integer and rational arithmetic
ocaml 4.12.0 The OCaml compiler (virtual package)
ocaml-base-compiler 4.12.0 Official release 4.12.0
ocaml-config 2 OCaml Switch Configuration
ocaml-options-vanilla 1 Ensure that OCaml is compiled with no special options enabled
ocamlbuild 0.14.0 OCamlbuild is a build system with builtin rules to easily build most OCaml projects.
ocamlfind 1.9.1 A library manager for OCaml
zarith 1.12 Implements arithmetic and logical operations over arbitrary-precision integers

Could anyone give any solutions on this error?

**Comment by nojb** [comment]
This site is reserved for issues related to the development of the OCaml **compiler**. For general questions about OCaml usage, I suggest you post to https://discuss.ocaml.org/ where you should be able to get help. Thanks!
