### ISSUE TITLE
manual: LaTeX collapses double dashes in command-line options since 4.08

### ISSUE THREAD

**Issue by wikku** [ocaml/ocaml#10513]
![image](https://user-images.githubusercontent.com/35867657/125794828-d6c81d31-b0cc-403d-b2de-2c2f4c56afae.png)
`--help` is rendered `-help`  
 
This [could have been introduced](https://tex.stackexchange.com/questions/9813/how-can-i-stop-latex-from-converting-two-hyphens-to-a-single-hyphen-when-loading) by loading `fontenc` in #1789.

In tex source code it's `\machine{--help}`. `\machine` is `\tt` with adjusted spacing (?). Probably it should be `\verb` instead, but I don't understand these 25 year old macros well.

**Comment by xavierleroy** [comment]
I agree `\verb` should be used instead of `\machine` in the hand-written LaTeX sources (.etex files).

`\machine` is also generated by the texquote2 preprocessor, and there might be reasons for not using `\verb` there (such as robustness in all contexts).

**Comment by xavierleroy** [comment]
This said, I see no point for ligatures in a typewriter font. (Yes, `--` for en-dash is part of TeX's ligature machinery.)  So, turning ligatures off for `\tt` would be a good fix.
