### ISSUE TITLE
Naming scheme for debug-related options?

### ISSUE THREAD

**Issue by gasche** [ocaml/ocaml#10533]
Currently the only debug-related command-line option for OCaml is `-g`, which does many different things, including:
- inserting debug events in the source / including debug information in binary
- enabling the collection of backtrace information on `raise`
- inhibiting certain optimizations that reduce the accuracy of debug information
  (some are explicitly disabled, some are implicity disabled by the presence of debug events)

#6238 requests having an option to have debug information, but no backtraces on raise and no/minimal code transformations.

Currently we don't even have an option to *disable* `-g` when it is enabled by default (in the toplevel). (#9290 offers a toplevel directive to disable debug, but not command-line flag).

**Comment by gasche** [comment]
## Proposal

Have several options prefixed by `-debug-`:
- `-debug-info`
- `-debug-backtraces`
- `-debug-codegen` (or some better suggestion) for code-generation improvement
- `-debug` means the conjunction of all `-debug-*` options, and is synonymous with `-g`
- `-no-debug` and `-no-debug-*` options can disable each part selectively.

Note: `-debug-backtraces` requires `-debug-info`; it is invalid to enable `-backtraces` without also enabling `-info`.

**Comment by pmetzger** [comment]
No opinion if it's better or worse since the options here are quite limited, but another sort of pattern I've seen in some programs is

```
--debug=info,backtraces,codegen
```

Again, this probably is not a real issue here, but this pattern can reduce command line bloat when there are lots of possible options to set.

(The general form is `--option=alpha,nobeta,nogamma,delta`)
