### ISSUE TITLE
Feature Request: Coq-style function parameter type-annotations.

### ISSUE THREAD

**Issue by rudynicolop** [ocaml/ocaml#10532]
I was wondering if it would be possible for the OCaml syntax to support more compact type-annotations for function parameters.

I often find myself writing code such as:
```ocaml
let f (n1 : int) (n2 : int) : int = ...
```
But I would like to condense it to:
```ocaml
let f (n1 n2 : int) : int = ...
```
Sometimes there are several parameters of the same type...
```ocaml
let rec shift (ct : int) (it : int) (ce : int) (ie : int) (es: expr)  :  expr -> expr = function
...
```
where I really want to write:
```ocaml
let rec shift (ct it ce ie : int) (es : expr) : expr -> expr = function
...
```

Thank you!

**Comment by nojb** [comment]
Personally I find the proposal interesting, but one point that lessens its interest is that type annotations are much less common in OCaml than in Coq.

**Comment by pmetzger** [comment]
> one point that lessens its interest is that type annotations are much less common in OCaml than in Coq

It depends on circumstances. When I'm debugging a weird type error, my first impulse is to annotate a lot of the involved functions, after which the error usually becomes comprehensible. I rarely remove the annotations afterwards. I'd have enjoyed having coq-like syntax in some such cases.

**Comment by stp59** [comment]
It is also possible that this inconsistency in supported syntax is a contributing factor to the fact cited above, that OCaml type annotations are less common than those in Coq. Perhaps making type annotations in OCaml less cumbersome would encourage OCaml hackers to adopt the same type annotation style used in Coq, leading to an increase in easier-to-read, self-documenting code?

**Comment by pmetzger** [comment]
I think there's generally a feeling among OCaml programmers that type annotations aren't really necessary. I tend to disagree with this; I also like them a lot as documentation. When I plunge into a new piece of code, knowing the types immediately provides a lot of clues to what I'm looking at, and in my own code, I often defensively annotate both for documentation purposes and to improve error reporting. However, it should be noted that this appears to be a minority opinion, and that many very good OCaml programmers don't like annotations. I also agree that the type annotation syntax in OCaml is a bit cumbersome, and that this may discourage annotation.

**Comment by Octachron** [comment]
A point to keep in mind is that labelled arguments tend to decrease the number of argument with the same type. Typically, I tend to add labels as soon as arguments share the same type and are not symmetric.

**Comment by hyphenrf** [comment]
> When I plunge into a new piece of code, knowing the types immediately provides a lot of clues to what I'm looking at

I agree, it's why I often have the `mli` open next to the corresponding `ml` in my editor though as it offers both sigs and docs. A counter-argument to annotating everything is extra unnecessary rigidity that may hinder future refactorings.

I'm personally excited about this simall quality of life upgrade. It also feels consistent with things like locally abstract `(type a b)` being short for `(type a) (type b)`, just the other way around.

**Comment by pmetzger** [comment]
Still seems relevant.
