### ISSUE TITLE
4.14.0+trunk what happened to `Toploop.use_file` ? 

### ISSUE THREAD

**Issue by dbuenzli** [ocaml/ocaml#10556]
Hello, 

I'm getting a flurry of reports (some, but not all, of which are listed [here](https://github.com/ocaml-bench/sandmark/issues/250))  and PRs on my packages because it seems `Toploop.use_file` disappeared in trunk. I'm [offered](https://github.com/dbuenzli/fmt/pull/50) with replacing these calls with `Toploop.load_file` which I suspect is wrong (there is a difference betwen `#use`ing and loading a file in the toplevel, but then it's not as if the current API is properly documented, so I don't know). This raises a few questions: 

1. Was there no way to keep `Toploop.use_file` or at least deprecate it in the API ? 
2. What is the supposed replacement for the functionality ? 
3. Is the replacement functionality applicable pre 4.14 ?

In case you wonder about the usage that's mainly for my `$PKG.top` packages which when loaded provide toplevel functionality for `$PKG`. I guess most (but not all) of these packages could go if #7770 were to be solved. 

Thanks.

**Comment by nojb** [comment]
I think the responsible PR is #10438. The function `use_file` was renamed `use_input` and made more general (it can now take as input a file, a string or `stdin`). I think the obvious solution is to reintroduce `use_file` as a wrapper around the more general `use_input`.
