### ISSUE TITLE
Pexp_constraint expression locations are ghost

### ISSUE THREAD

**Issue by aantron** [ocaml/ocaml#10554]
Essentially, why are they ghost? Is this a bug?

This appears to be affecting Bisect_ppx (the coverage tool) in https://github.com/aantron/bisect_ppx/issues/377#issuecomment-879855965. Here is a smaller example than in the issue:

```ocaml
let () =
  if true then
    (() : unit)
  else
    ()
```

with OCaml 4.12.0 and Bisect_ppx `master` (or any recent version), this gets instrumented as

![Снимок](https://user-images.githubusercontent.com/12073668/128297900-51817d44-4500-4794-a058-a0e6165f3132.PNG)

Note the lack of point on the expression in the `then` branch, which is suppressed by having `()` wrapped in a constraint expression. This is because Bisect currently deliberately avoids instrumenting expressions with ghost locations. If the contraint expression is removed, the remaining `()` will be instrumented, as expected by users, and as shown by the `else` branch.

The uninstrumented AST for this program:

```
[
  structure_item (foo.ml[1,0+0]..[5,47+6])
    Pstr_value Nonrec
    [
      <def>
        pattern (foo.ml[1,0+4]..[1,0+6])
          Ppat_construct "()" (foo.ml[1,0+4]..[1,0+6])
          None
        expression (foo.ml[2,9+2]..[5,47+6])
          Pexp_ifthenelse
          expression (foo.ml[2,9+5]..[2,9+9])
            Pexp_construct "true" (foo.ml[2,9+5]..[2,9+9])
            None
          expression (foo.ml[3,24+4]..[3,24+15]) ghost
            Pexp_constraint
            expression (foo.ml[3,24+5]..[3,24+7])
              Pexp_construct "()" (foo.ml[3,24+5]..[3,24+7])
              None
            core_type (foo.ml[3,24+10]..[3,24+14])
              Ptyp_constr "unit" (foo.ml[3,24+10]..[3,24+14])
              []
          Some
            expression (foo.ml[5,47+4]..[5,47+6])
              Pexp_construct "()" (foo.ml[5,47+4]..[5,47+6])
              None
    ]
]
```

The `ghost` on the location of the `Pexp_constraint` is in question in this issue.

I see a potentially related discussion in https://github.com/ocaml/ocaml/pull/1850.

cc @gkaracha @dorranh

**Comment by nojb** [comment]
Thanks for the report, this looks like a bug at first sight.
