### ISSUE TITLE
Feature request: further relax the value restriction and/or add a bottom type

### ISSUE THREAD

**Issue by stedolan** [ocaml/ocaml#10552]
In the presence of a type with covariant parameters:
```ocaml
type (+'a, +'b) t
val diag : unit -> ('a, 'a) t
```
the relaxed value restriction ([@garrigue, 2004](https://caml.inria.fr/pub/papers/garrigue-value_restriction-fiwflp04.pdf)) means that we can generalise the type of expressions that would not pass the normal value restriction test:
```ocaml
let gen = diag ()
```
Despite containing an application, `gen` is given the generalised type `val gen : ('a, 'a) t`. The argument justifying this is based on subtyping: assuming a least type ⊥, we could initially give `gen` the monomorphic type `(⊥,⊥) t`, and then note that by subtyping and covariance of `t` we also have `gen : ('a, 'a) t`.

However, this is not the most general type we could give: the same argument justifies `val gen : ('a, 'b) t`, with no sharing between the variables.

When `('a, 'b) t` is a concrete type, say `'a * 'b`, we can get the more general type by eta-expanding:
```ocaml
let gen' = let (a,b) = gen in (a,b)
```
giving `val gen' : ('a, 'b) t`. But this doesn't help when the type `t` is abstract.

So, my feature request is some means to write `val gen : ('a, 'b) t`, even when `t` is abstract, either by:

  - **Further relaxing the value restriction**, so that sharing is removed when variables are generalised by the relaxed value restriction.

    (This is neat in theory, but I suspect in practice would be awkward to implement, as it goes against the grain of the typechecker which tries hard to preserve sharing)

  - **Providing an explicit bottom type** (see #9459), to allow explicit use of the relaxed value restriction argument as e.g.:
    ```ocaml
    let gen = (diag () : (bottom, bottom) t :> ('a, 'b) t)
    ```

**Comment by Octachron** [comment]
Currently, that would break libraries that use both equality between phantom types and the relaxed value restriction. For instance, with type-level addition implemented with
```ocaml
type (+'a,+'b) nat
val zero: ('a,'a) nat
val (+): ('low,'mid) nat -> ('mid,'sup) nat -> ('low,'sup) nat
```
unsharing the two type variables of `zero` would break the link between the phantom types and the underlying values.
At the same time, in this case, the covariance annotations are only used as a proxy for the relaxed value restriction.
