### ISSUE TITLE
Break dependency of Obj on Marshal

### ISSUE THREAD

**Issue by fpottier** [ocaml/ocaml#10566]
@c-cube and I are currently working on a series of additions to the standard library module `Seq`. One of these additions is the function `Seq.memoize`, whose definition creates a dependency of `Seq` on `Lazy`. Unfortunately, this dependency creates a cycle, because `Lazy` depends on `Obj` which depends on `Marshal` which depends on `Bytes` which depends on `Seq`.

Arguably the dependency of `Obj` on `Marshal` is somewhat surprising. This dependency is created by the functions `Obj.marshal` and `Obj.unmarshal`, which are deprecated and (according to @xavierleroy) have been deprecated for 7 years.

Could the dependency of `Obj` on `Marshal` be removed?

One option would be to remove the functions `Obj.marshal` and `Obj.unmarshal` entirely. Another option would be to keep them, but rewrite them without referring to `Marshal` or `Bytes` (which seems feasible, at the cost of duplicating a certain amount of code).

**Comment by gasche** [comment]
Sure: send a PR to remove these two functions, we will gently ask @Octachron or @kit-ty-kate to test it against opam, and assuming they are indeed unused we could go ahead.

This being said: is it wise to have `Seq`, which is a moderately simple data-structure, depend on `Lazy`, which is arguably a more complex data structure? (Would it make sense to consider adding a dependency from Lazy to Seq instead?)

**Comment by fpottier** [comment]
Thanks for your reply! I have created a PR (#10568).

We could indeed rename `Seq.memoize` to `Lazy.memoize_seq` or just `Lazy.seq` and introduce a dependency of `Lazy` on `Seq`.

**Comment by c-cube** [comment]
> Thanks for your reply! I have created a PR (#10568).
> 
> We could indeed rename `Seq.memoize` to `Lazy.memoize_seq` or just `Lazy.seq` and introduce a dependency of `Lazy` on `Seq`.

I don't like that idea, it's not intuitive to use. If I want to memoize a `Seq.t` I'll look in `Seq`, not in an unrelated module (`Lazy`) in which it is only because of an entirely avoidable implementation detail.

**Comment by fpottier** [comment]
I tend to agree with Simon.

**Comment by lthls** [comment]
My own impression is that we're having a design issue. We're expecting to have one module for each base type, and that each function manipulating data should be in the module where it seems most natural.
But we have a hard constraint that modules need to be totally ordered for linking, so we can't create dependency loops. In particular it may be nice to have both `Bytes.of_seq` and `Seq.to_bytes`, but it's not possible if the implementation needs to rely on functions from both `Seq` and `Bytes`.

In the past we had avoided this problem by making many of the common types (lists, arrays, strings, ...) builtin, so the types can be used everywhere (and the base functions for these types were all exposed in `Pervasives`). Now that we're actually adding new modules to the Stdlib that do not have builtin types, we get hit by the dependency issues.

I would suggest two possible solutions:
- Separate the modules defining the types (and some raw functionality) from the modules exposing the features. In practice, for `Seq` we could have a module `Seq_types`, with no dependencies, that all the other modules could depend on, and a `Seq` module that would re-export the functionality from `Seq_types` plus all kinds of other features that may require extra dependencies. The same approach could be generalized to a lot of other modules actually, if we wanted to.
- Make the `Seq.t` type either builtin or part of `Pervasives`. This means that `Bytes`, for instance, would not need to depend on `Seq` anymore. We clearly shouldn't be doing that for all the types exposed in the standard library, but the fact that `Seq.t` is used everywhere would justify it.

I have other less realistic possibilities in mind too, but I'll spare you the details (stdlib as a single recursive pack!).
What I'd like to avoid is to have to make arbitrary decisions on which module depends on which one. In particular, the modules of the standard library are only linked in an executable if a program transitively depends on them, so each extra dependency between modules of the stdlib can increase the size of the generated programs, which I think is a shame.

Going back to the original problem: I don't think you need to introduce a dependency on `Lazy` to implement `Seq.memoize`. The `Lazy.t` type is builtin, as `lazy_t`. It can be constructed and deconstructed using the `lazy` keyword. If you really want to use `Lazy.from_fun`, my suggestion would be to move the function to `CamlinternalLazy` (but that's not a very appealing solution).

**Comment by fpottier** [comment]
Hi @lthls!

Regarding your general analysis, and your suggestion to separate `Seq_types` and `Seq`, I tend to agree with you. In fact, I discussed this option privately with @xavierleroy, but he seemed to dislike it.

> Going back to the original problem: I don't think you need to introduce a dependency on `Lazy` to implement `Seq.memoize`. The `Lazy.t` type is builtin, as `lazy_t`. It can be constructed and deconstructed using the `lazy` keyword.

@c-cube already formulated this remark, and I have tried it. As far as I can tell, it doesn't work: using the `lazy` keyword (for construction and deconstruction) produces references to `CamlinternalLazy` in the generated code, and `CamlinternalLazy` depends on `Obj`, so the original problem remains.

**Comment by gasche** [comment]
In general one design for avoiding cyclic dependencies is to build the system in "layers": for each concept of the stdlib have first core module with only the absolutely necessary dependencies (no convience stuff), and then an "extended module" that depends on (its own core module and) other concepts *core modules* (of course in general there can be more than two layers, you see the point of using an order to enforce acyclicity). This has been done in some parts already with "camlInternalFoo" as the "core module" and "Foo" as the "extended module". I'm not sure it's worth moving to such a setup there, but it's an option if it can be relatively incrementally. In particular, we can remove Obj->Marshal and then go through CamlInternalLazy only, that would be nice indeed.

**Comment by Octachron** [comment]
The core issue has been solved by #10568 which removes the `Obj`⇒`Marshal` dependency.
