### ISSUE TITLE
ocamltest should not depend on GNU diff

### ISSUE THREAD

**Issue by dra27** [ocaml/ocaml#10562]
ocamltest's `Filecompare.diff` assumes GNU diff: https://github.com/ocaml/ocaml/blob/cce52acc7c7903e92078e9fe40745e11a1b944f0/ocamltest/filecompare.ml#L233-L236

It's only called when a test fails, so mostly this doesn't cause issues but it does mean that Alpine workers in Jenkins (and other systems where `diff` is not GNU diff) fail to display errors correctly if a test breaks.

We should fix it by probing for the diff command properly in `configure`. While doing that, we should prefer `patdiff` if it's available.

**Comment by shindere** [comment]
I believe this has been fixed by #10143, thus closing.
