### ISSUE TITLE
Error: co-processor offset out of range (arm32)

### ISSUE THREAD

**Issue by talex5** [ocaml/ocaml#10571]
The capnp package's tests don't compile on arm32 (OCaml 4.12). The error is:
```
(cd _build/default && /home/opam/.opam/4.12/bin/ocamlopt.opt -w @1..3@5..28@30..39@43@46..47@49..57@61..62-40 -strict-sequence -strict-formats -short-paths -keep-locs -w -53-55 -g -I src/tests/.run_tests.eobjs/byte -I src/tests/.run_tests.eobjs/native -I /home/opam/.opam/4.12/lib/base -I /home/opam/.opam/4.12/lib/base/base_internalhash_types -I /home/opam/.opam/4.12/lib/base/caml -I /home/opam/.opam/4.12/lib/base/shadow_stdlib -I /home/opam/.opam/4.12/lib/base_quickcheck -I /home/opam/.opam/4.12/lib/bytes -I /home/opam/.opam/4.12/lib/fieldslib -I /home/opam/.opam/4.12/lib/jane-street-headers -I /home/opam/.opam/4.12/lib/oUnit -I /home/opam/.opam/4.12/lib/ocplib-endian -I /home/opam/.opam/4.12/lib/ounit2 -I /home/opam/.opam/4.12/lib/ounit2/advanced -I /home/opam/.opam/4.12/lib/ppx_assert/runtime-lib -I /home/opam/.opam/4.12/lib/ppx_bench/runtime-lib -I /home/opam/.opam/4.12/lib/ppx_compare/runtime-lib -I /home/opam/.opam/4.12/lib/ppx_enumerate/runtime-lib -I /home/opam/.opam/4.12/lib/ppx_hash/runtime-lib -I /home/opam/.opam/4.12/lib/ppx_here/runtime-lib -I /home/opam/.opam/4.12/lib/ppx_inline_test/config -I /home/opam/.opam/4.12/lib/ppx_inline_test/runtime-lib -I /home/opam/.opam/4.12/lib/ppx_sexp_conv/runtime-lib -I /home/opam/.opam/4.12/lib/res -I /home/opam/.opam/4.12/lib/result -I /home/opam/.opam/4.12/lib/sexplib0 -I /home/opam/.opam/4.12/lib/splittable_random -I /home/opam/.opam/4.12/lib/stdint -I /home/opam/.opam/4.12/lib/stdlib-shims -I /home/opam/.opam/4.12/lib/time_now -I src/runtime/.capnp.objs/byte -I src/runtime/.capnp.objs/native -intf-suffix .ml -no-alias-deps -opaque -open Dune__exe -o src/tests/.run_tests.eobjs/native/dune__exe__Test.cmx -c -impl src/tests/test.ml)
/tmp/build975190.dune/camlasm7c32d8.s: Assembler messages:
/tmp/build975190.dune/camlasm7c32d8.s:15413: Error: co-processor offset out of range
/tmp/build975190.dune/camlasm7c32d8.s:15416: Error: co-processor offset out of range
/tmp/build975190.dune/camlasm7c32d8.s:15634: Error: co-processor offset out of range
/tmp/build975190.dune/camlasm7c32d8.s:15639: Error: co-processor offset out of range
/tmp/build975190.dune/camlasm7c32d8.s:36427: Error: co-processor offset out of range
/tmp/build975190.dune/camlasm7c32d8.s:36430: Error: co-processor offset out of range
/tmp/build975190.dune/camlasm7c32d8.s:36672: Error: co-processor offset out of range
/tmp/build975190.dune/camlasm7c32d8.s:36673: Error: co-processor offset out of range
```

`camlasm7c32d8.s:15413` is `fstd    d0, [sp, #1216]`

This Dockerfile should reproduce the problem:
```Dockerfile
FROM ocaml/opam:debian-10-ocaml-4.12@sha256:06eb040f3ab14e6d3db0e93b3836cd46b93dd8494e87b0c4261da23e29ceb65a
# debian-10-4.12_arm32
USER 1000:1000
SHELL [ "/usr/bin/linux32", "/bin/sh", "-c" ]
WORKDIR /src
RUN sudo chown opam /src
RUN cd ~/opam-repository && (git cat-file -e f774eea442d7f3496d9c90e6e1cb2f0147abc72e || git fetch origin master) && git reset -q --hard f774eea442d7f3496d9c90e6e1cb2f0147abc72e && git log --no-decorate -n1 --oneline && opam update -u
RUN git clone https://github.com/capnproto/capnp-ocaml.git .
RUN opam pin -n capnp.dev .
ENV DEPS base.v0.14.1 base-bigarray.base base-bytes.base base-threads.base base-unix.base base_quickcheck.v0.14.1 conf-capnproto.1 cppo.1.6.7 csexp.1.5.1 dune.2.9.0 dune-configurator.2.9.0 fieldslib.v0.14.0 jane-street-headers.v0.14.0 jst-config.v0.14.0 ocaml.4.12.0 ocaml-base-compiler.4.12.0 ocaml-compiler-libs.v0.12.3 ocaml-config.2 ocaml-migrate-parsetree.2.2.0 ocaml-options-vanilla.1 ocamlfind.1.9.1 ocplib-endian.1.1 octavius.1.2.2 ounit.2.2.4 ounit2.2.2.4 ppx_assert.v0.14.0 ppx_base.v0.14.0 ppx_bench.v0.14.1 ppx_cold.v0.14.0 ppx_compare.v0.14.0 ppx_derivers.1.2.1 ppx_enumerate.v0.14.0 ppx_fields_conv.v0.14.2 ppx_hash.v0.14.0 ppx_here.v0.14.0 ppx_inline_test.v0.14.1 ppx_js_style.v0.14.1 ppx_let.v0.14.0 ppx_optcomp.v0.14.3 ppx_sexp_conv.v0.14.3 ppx_sexp_message.v0.14.1 ppx_sexp_value.v0.14.0 ppxlib.0.22.2 res.5.0.1 result.1.5 sexplib0.v0.14.0 splittable_random.v0.14.0 stdint.0.7.0 stdio.v0.14.0 stdlib-shims.0.3.0 time_now.v0.14.0
RUN opam depext --update -y capnp.dev $DEPS
RUN opam install $DEPS
RUN opam exec -- dune build @install @check @runtest && rm -rf _build
```

**Comment by xavierleroy** [comment]
It looks like a function has a really big stack frame, so big that accessing a FP number stored in the stack frame exceeds the maximal offset supported by FP loads and stores, namely 1020.  The bad news is that there is no obvious change to the ocamlopt ARM code emitter to support such far-away accesses.  However, it would be good to understand why such a big stack frame is generated and whether it could be avoided (e.g. by inlining less).  Is it possible to add the generated .s file to this PR?

**Comment by talex5** [comment]
Here are the .s and .ml files:

[files.zip](https://github.com/ocaml/ocaml/files/7033059/files.zip)

**Comment by xavierleroy** [comment]
Thanks for the files.  Unfortunately, the function with the huge stack frame is an anonymous function, so it's hard to know where it comes from in the source.  

There are several `inline` directives in the source.  What happens if they are removed?

The source is huge and feels auto-generated (?).  It would help to split it in smaller parts.

**Comment by bluddy** [comment]
Since this is something that is bound to happen as we increase inlining, doesn't it make sense to handle it generally and add another register for this purpose when needed (which will of course increase spilling, but still)?

**Comment by xavierleroy** [comment]
> Since this is something that is bound to happen as we increase inlining,

Inlining that produces huge functions is a failure, as the resulting code runs slower than the original code. We want better inlining, not silly inlining.  I suspect that this particular example forces inlining where it doesn't make sense.

>  doesn't it make sense to handle it generally and add another register for this purpose when needed (which will of course increase spilling, but still)?

No.  Registers are a precious resource, esp. on ARM which has only 16 integer registers.  You don't reserve a register for a condition that is observed once in 20 years.  (The ARM back-end for OCaml dates back to the late 1990's.)

This said, it might be possible to use the return address register R14 as temporary in non-leaf functions.  Leaf functions with huge stack frames are even more unlikely than non-leaf functions with huge stack frames.

**Comment by talex5** [comment]
I removed all the inline directives, but it still fails. In fact, the `.s` file got larger!

```
/tmp/camlasm3ef8cc.s: Assembler messages:
/tmp/camlasm3ef8cc.s:19754: Error: co-processor offset out of range
/tmp/camlasm3ef8cc.s:19757: Error: co-processor offset out of range
/tmp/camlasm3ef8cc.s:19975: Error: co-processor offset out of range
/tmp/camlasm3ef8cc.s:19980: Error: co-processor offset out of range
/tmp/camlasm3ef8cc.s:40768: Error: co-processor offset out of range
/tmp/camlasm3ef8cc.s:40771: Error: co-processor offset out of range
/tmp/camlasm3ef8cc.s:41013: Error: co-processor offset out of range
/tmp/camlasm3ef8cc.s:41014: Error: co-processor offset out of range
```
[without-inline.zip](https://github.com/ocaml/ocaml/files/7049659/without-inline.zip)

(note: the inlining directives are really for flambda, but I'm not sure how to indicate that regular compiler versions should ignore them)

It doesn't seem to be any particular function that causes the problem, just the number of them. Deleting things until it stops breaking, the difference is removing this function from the `Builder.TestAllTypes` module:
```ocaml
      let data_list_set x v =
        BA_.set_blob_list x 16 v
```

Removing the last function in this file makes the difference between failing and building successfully:

[shrunk.zip](https://github.com/ocaml/ocaml/files/7049853/shrunk.zip)

The error is just:
```
/tmp/build2cff6f.dune/camlasm601896.s: Assembler messages:
/tmp/build2cff6f.dune/camlasm601896.s:4788: Error: co-processor offset out of range
/tmp/build2cff6f.dune/camlasm601896.s:4994: Error: co-processor offset out of range
```

**Comment by lthls** [comment]
I'm surprised removing the `[@inline]` annotations makes any difference. As far as I can tell, they're only used on functors in this example, and Closure cannot inline most functors.

The main reason why the frame needs to be enormous seems to be the coercion between the inferred type for the `MakeRPC` functor's body and the declared type in `test.mli`: all modules and submodules are coerced at the same point, so every single value defined in any of these modules has to be kept alive until the end. If you have some way to patch your code generator, you might want to add explicit coercions on every submodule you define in the implementation; this should decrease significantly the number of values that need to stay alive until the end.
