### ISSUE TITLE
teyjus project fails to build with ocaml-4.12.0: undefined symbol: caml_local_roots

### ISSUE THREAD

**Issue by yurivict** [ocaml/ocaml#10585]
[teyjus](https://github.com/teyjus/teyjus) project version 2.1-7-ge63f40a fails:
```
+ ocamlopt.opt -w -A -I . -I compiler -I disassembler -I simulator -I loader -o tjlink.opt front/parseargs.cmx front/linkerfront.cmx liblink.a
ld: error: undefined symbol: caml_local_roots
>>> referenced by linker_c.c:30
>>>               linker_c.o:(FRONT_link) in archive liblink.a
>>> referenced by linker_c.c:30
>>>               linker_c.o:(FRONT_link) in archive liblink.a
>>> referenced by linker_c.c:30
>>>               linker_c.o:(FRONT_link) in archive liblink.a
>>> referenced 2 more times
```

Full log: https://people.freebsd.org/~yuri/teyjus-2.1.7.log

**Comment by Octachron** [comment]
This project has vendored all OCaml runtime headers. This breaks any possibility of upward compatibility with OCaml versions. Those headers should either be removed and replaced by the one distributed by the compiler, or at least updated for each version of OCaml.

**Comment by yurivict** [comment]
Thank you, this works.
