### ISSUE TITLE
Format.asprintf sets column limit

### ISSUE THREAD

**Issue by iitalics** [ocaml/ocaml#10592]
`Format.asprintf` gives the intermediate formatter a fairly conservative column-limit of 78. This is really inconvenient for using the Format module to generate string representations of data, since functions like `asprintf` can be expected to be used for all sorts of applications *besides* printing to a TTY (for example, displaying on a GUI, or sending over the net).

`asprintf` is used in popular libraries such as `Fmt` and `ppx_deriving.show` to generate to-string conversion functions. All of these functions secretly have a 78 column limit as a result, and for most users I can assume this would be considered a bug. I don't think this should be the default behavior of a function like `asprintf` which is not connected to a TTY.

**Comment by Octachron** [comment]
This limit can be changed with `Format.pp_set_geometry`. Moreover, this column limit only matters if the user provide break hints (or open boxes) indicating that they want the formater to break lines in function of the column limit. This seems like a sensible default to me.

**Comment by iitalics** [comment]
Break hints are automatically inserted by the libraries mentioned above. And this is fine, since then it will work nicely if the pretty printer happens to be used in a context with a column limit (like `std_formatter`, `err_formatter`, a hovbox, or an otherwise custom configured formatter).

However, the user has no chance to call `pp_set_geometry` if they are using asprintf in a way such as `asprintf "%a" pp_mytype myvalue` (which is exactly what these libraries do to generate to-string functions). Column limit does not make a lot of sense for rendering to string since there is no guaruntee that the consumer of this string has any concept of "columns".

**Comment by Octachron** [comment]
The user can set `pp_set_geometry` with a custom `asprintf`
```ocaml
let asprintf_bis fmt =
  let b = Buffer.create 512 in
  let ppf = Format.formatter_of_buffer b in
  let pp_infinity = 10_000_000_000 in
  Format.pp_set_geometry ppf  ~max_indent:(pred pp_infinity) ~margin:pp_infinity;
  Format.kfprintf (fun ppf -> Format.pp_print_flush ppf (); Buffer.contents b) ppf fmt
 ```
With this function,
```ocaml
let test = asprintf_bis "@[@<1000>%d@,@<1000>%d@]" 1 2
```
prints  "12" compared to `"1\n2"` with the standard `asprintf`.

**Comment by jberdine** [comment]
Another option is something like:
```ocaml
let blast_margin ppf =
  let pp_infinity = 10_000_000_000 in
  Format.pp_set_geometry ppf ~max_indent:(pred pp_infinity)
    ~margin:pp_infinity

let test = Format.asprintf "%t@[@<1000>%d@,@<1000>%d@]" blast_margin 1 2
```
This lets you use the standard `asprintf`, but if the library itself makes an `asprintf "%a"` call that you can't change to `asprintf "%t%a" blast_margin`, then it might not be enough.

**Comment by iitalics** [comment]
Both of these libraries simply use `asprintf "%a"`. I suppose its worth investigating them separately to see if a column limit was intended. But if neither of them intended that behavior then perhaps this default is not correct.
https://github.com/dbuenzli/fmt/blob/master/src/fmt.ml#L762
https://github.com/ocaml-ppx/ppx_deriving/blob/master/src_plugins/show/ppx_deriving_show.cppo.ml#L304

**Comment by Octachron** [comment]
It is up to the library authors to choose their own library string printers. Since an alternative string printer can be defined with 6 line of code, it seems reasonable to assume that 78-wide character formatting is seen as a feature or at least isn't seen as a bug whenever `asprintf` is used. Breaking backward compatibility doesn't seem warranted in this case.

**Comment by Octachron** [comment]
In absence of comments from the concerned library authors, I am closing this issue. Don't hesitate to reopen it if you have more data points.
