### ISSUE TITLE
Values of existential type are printed <poly>

### ISSUE THREAD

**Issue by wikku** [ocaml/ocaml#10607]
The `<poly>` here:

```
type t = E : 'a -> t;;
E ();;
- : t = E <poly>
```

is certainly not a polymorphic value and is a different thing from the `<poly>` here:

```
Obj.magic ();;
- : 'a = <poly>
```

I think it would make more sense if something like `E <existential>` was printed. I don't know if there are substantially different contexts in which we could encounter such things (what should we print when debugging polymorphic functions?). If GADTs are the only place where we can encounter existentials, then a probable fix would be to remember which type variables are existentially quantified when traversing the value we are printing.

**Comment by Octachron** [comment]
Given a value `E x`, the sub-expression `x` is certainly polymorphic, since it could be any type. At the same time, for existentially quantified type, we have a useful naming convention that we are already using for error messages. We could reuse it to print
```ocaml
E <?:$E_'a>
```
rather than just
```ocaml
E <poly>
```

**Comment by gasche** [comment]
I don't find `<?:$E_'a>` very readable.

**Comment by Octachron** [comment]
Under the hypothesis that this happen infrequently, maybe the more explicit `<existential:$E_'a>` ?

**Comment by gasche** [comment]
Yes! (I would add a space after the colon.)

In the example we are discussing, it is not very interesting to give more information than `<poly>` because it looks obvious where the existential comes from. But the `<poly>` marker can in fact come deep within the value, and there it would indeed be interesting to know from which constructor comes the existential type.

```ocaml
# type 'a t = T : 'a * 'b -> 'a t
   and u = U : 'a t -> u;;
# U (T (true, "foo"));;
- : u = U (T (<poly>, <poly>))
```

**Comment by garrigue** [comment]
Actually, shouldn't it be just `<abstract>`.
From a type theoretical point of view, there is not much difference between `<poly>` and `<abstract>`, but in ocaml existential type variables are encoded as abstract types.
If you want to give a name, this should be the case for all abstract types, but I'm not convinced this is useful.
