### ISSUE TITLE
Get the `system` variable to be consistent

### ISSUE THREAD

**Issue by kit-ty-kate** [ocaml/ocaml#10613]
Currently, in OCaml code in the wild, people use the output of `ocamlc -config` to detect the architecture and OS of the system they are on.

However while debugging https://github.com/janestreet/core/issues/145 I discovered that the variable `system`, in particular, is not consistent and does not always return "linux" on linux systems for example.

This pattern of using the `system` variable to detect the OS is especially prevalent in dune where there is no other builtin way to get this information (see https://github.com/ocaml/dune/issues/4895).

In addition of fixing dune and other build systems with similar issues (I believe `oasis`, back in the days, also used the `system` variable: https://github.com/ocaml/oasis/blob/master/setup.ml#L4133), I think it would be nice to make the variable more consistent. e.g.
* regroup all the linux variants as `linux`
* regroup `bsd_elf` and `bsd` as `bsd`
* regroup all the openbsd variants as `openbsd` (currently it's split between `bsd` and `openbsd` depending on the architecture)
* regroup `win32` and `win64` into one (not sure which name it should have, but having the `system` variable carry the same information as the `architecture` variable doesn't seem right to me)
* same for `mingw` and `mingw64` (cc @dra27 who probably has ideas about windows)

See https://github.com/ocaml/ocaml/blob/12523517cf5c6c782563f8b76e661b67748e010b/configure.ac#L1044-L1132 for the list of current possible values of `system`

**Comment by dra27** [comment]
@mshinwell remembers trying to tackle this with one of the debugger PRs. I think it's a good idea, but I expect we'll have to do this as we did with `c_compiler` and `bytecomp_c_compiler`/`native_c_compiler` - introduce a better variable and live with the old one being there too.

For example, while there's no reason not to use ARCH and SYSTEM to determine, say, 32-bit MSVC, there's definitely a lot of obscure (and not necessarily open source...) stuff relying on `SYSTEM=win32` meaning exactly 32-bit MSVC. FWIW, I'd happily have all four native Windows ports have the same "SYSTEM" value and determine the exact one from ARCH, SYSTEM=windows and CCOMP_TYPE.

**Comment by kit-ty-kate** [comment]
Indeed that would be a good backward compatible way of fixing this, although keeping the `system` variable around carries a maintainance burden and we'll have to port each use of it to the new variable.

In the dune issue linked above I proposed to add a new `%{os}` variable. The same thing could be done in the compiler as well.

**Comment by dra27** [comment]
> Indeed that would be a good backward compatible way of fixing this, although keeping the `system` variable around carries a maintainance burden and we'll have to port each use of it to the new variable.

I don't follow the maintenance burden? Dune, for example, has to keep interpreting both variables in order to support older compilers (as it did for the c_compiler variable, cf. src/ocaml-config/ocaml_config.ml) and keeping the variable allows other systems to be gradually switched over to a new variable? The burden in ocaml itself is just that matrix of m4sh referenced above.

**Comment by dra27** [comment]
Kind of a lot's happened in the last year 🙂 I don't think the lack of forward motion on this issue is a sign of a lack of importance, so I'm removing the Stale label and hoping that the Stale bot won't get to nag us next year!

**Comment by shindere** [comment]
Still an issue, definitely.

I am willing to work on it but that's the easy part, I guess. The most
difficult part seems to determine how best to deal with it.

Do we need two instances, one for the host and one for the target, or is
one instance (for the target, I guess) enough?

If two instances would be welcome, then `host_system` and
`target_system` look like natural candidates to me and we can agree on
the common set of values these variables may take.

Thoughts welcome!
