### ISSUE TITLE
Ocaml 4.12 Build Fails on FreeBSD Powerpc64

### ISSUE THREAD

**Issue by lenoil98** [ocaml/ocaml#10614]
Attempting to build Ocaml 4.12 release on FreeBSD 13 on PowerPC64 (Big Endian) and encountered the below error:

`gmake[4]: Entering directory '/usr/ports/tmp/ocaml-4.12/stdlib'`
`../boot/ocamlrun ../ocamlopt -strict-sequence -absname -w +a-4-9-41-42-44-45-48 -g -warn-error A -bin-annot -nostdlib -principal -safe-string -strict-formats   -nopervasives -c camlinternalFormatBasics.ml`
`sh: -o: not found`
`File "/usr/ports/tmp/ocaml-4.12/stdlib/camlinternalFormatBasics.ml", line 1:`
`Error: I/O error:   -o 'camlinternalFormatBasics.o' '/tmp/camlasmd1cb08.s'`
`gmake[4]: *** [Makefile:213: camlinternalFormatBasics.cmx] Error 2`
`gmake[4]: Leaving directory '/usr/ports/tmp/ocaml-4.12/stdlib'`
`gmake[3]: *** [Makefile:785: libraryopt] Error 2`
`gmake[3]: Leaving directory '/usr/ports/tmp/ocaml-4.12'`
`gmake[2]: *** [Makefile:199: opt-core] Error 2`
`gmake[2]: Leaving directory '/usr/ports/tmp/ocaml-4.12'`
`gmake[1]: *** [Makefile:215: opt.opt] Error 2`
`gmake[1]: Leaving directory '/usr/ports/tmp/ocaml-4.12'`
`gmake: *** [Makefile:275: world.opt] Error 2`

**Comment by dra27** [comment]
Running:

```
cd stdlib
../boot/ocamlrun ../ocamlopt -strict-sequence -absname -w +a-4-9-41-42-44-45-48 -g -warn-error A -bin-annot -nostdlib -principal -safe-string -strict-formats -nopervasives -c camlinternalFormatBasics.ml -verbose
```

will show the commands being executed, but it looks like the assembler isn't properly configured. What arguments were passed to `configure`?

**Comment by dra27** [comment]
I'm puzzled it got that far, though - if `AS` and `ASPP` are incorrect, how did it build the native runtime - has `power.S` been compiled in `runtime/`?

**Comment by kit-ty-kate** [comment]
@dra27 The combination ppc64 + freebsd isn't part of the host detection in the configure script:
https://github.com/ocaml/ocaml/blob/12523517cf5c6c782563f8b76e661b67748e010b/configure.ac#L1044-L1132

Wouldn't that maybe why it fails?

**Comment by lenoil98** [comment]
@dra27 

> I'm puzzled it got that far, though - if AS and ASPP are incorrect, how did it build the native runtime - has power.S been compiled in runtime/?

I solved the problem,  I was not setting `AS and ASPP` .   I used the command-line `gmake CC="/usr/local/bin/gcc10" AS="/usr/local/bin/gcc10" ASPP='/usr/local/bin/gcc10 -c" PARTIALLD="/usr/local/bin/ld -r"` to get the build to work.

@dra27 
>The combination ppc64 + freebsd isn't part of the host detection in the configure script:

I patched the configure script with the below patch:

```
--- configure.ac.orig
+++ configure.ac
@@ -891,6 +891,7 @@
     [x86_64-*-darwin*], [natdynlink=true],
     [s390x*-*-linux*], [natdynlink=true],
     [powerpc*-*-linux*], [natdynlink=true],
+    [powerpc*-*-freebsd*], [natdynlink=true],
     [x86_64-*-solaris*], [natdynlink=true],
     [i686-*-kfreebsd*], [natdynlink=true],
     [x86_64-*-kfreebsd*], [natdynlink=true],
@@ -949,6 +950,10 @@
     [arch=power; model=ppc64le; system=elf],
   [[powerpc*-*-linux*]],
     [arch=power; AS_IF([$arch64],[model=ppc64],[model=ppc]); system=elf],
+  [[powerpc64le*-*-freebsd*]],
+    [arch=power; model=ppc64le; system=bsd_elf],
+  [[powerpc*-*-freebsd*]],
+    [arch=power; AS_IF([$arch64],[model=ppc64],[model=ppc]); system=bsd_elf],
   [[s390x*-*-linux*]],
     [arch=s390x; model=z10; system=elf],
   [armv6*-*-linux-gnueabihf],
```

**Comment by dra27** [comment]
Sounds fixed! @lenoil98, if you'd like to open a PR, we can merge the `configure` changes - it looks like you've included Power 32 as well - have you been able to test that? If you do, you could add `FreeBSD` to the entries in `README.adoc` in the Tier 2 column.
