### ISSUE TITLE
Weird behaviour of `-o` when compiling C files

### ISSUE THREAD

**Issue by nojb** [ocaml/ocaml#10625]
(Discussed in #10610)

In the current `trunk`:

- `ocamlc -o foo a.c` ---> `gcc -o a.o -c a.c`
- `ocamlc -o foo -c a.c` ---> `gcc -o a.o -c a.c`

In 4.12 it was not possible to use `-o` and `-c` at the same time with C files, but the first case (without `-c`) gives

- `ocamlc -o foo a.c` ---> `gcc -c a.c`

(essentially equivalent to the behaviour of `trunk`)

It seems to me that `-o` when `-c` is *not* passed should be handled similarly to how it is handled when `-c` *is* passed: it should be passed to the C compiler instead of being ignored.

**Comment by Octachron** [comment]
Current trunk (and 4.13) has exactly the same behavior as 4.12:

* `ocamlc -o foo -c a.c` ⇒ `gcc ... -c a.c`

Similarly, `ocamlc -o foo -c a.c` does send the argument `-o foo` argument to gcc as `gcc ... -o foo a.c`.
Moreover, the current behavior to not pass the `-o` flag to `gcc` in `ocamlc -o foo a.c` is partially here to accommodate
```
ocamlopt -o result a.c b.c main.ml
```
where the `-o` flag provides the name of the executable.
Do we want to adjust this behavior of the `-o ` flag without `-c ` in the case where the input files are exactly one `C` file?

**Comment by nojb** [comment]
> Current trunk (and 4.13) has exactly the same behavior as 4.12:

In 4.12 I get the following:
```
nojebar@PERVERSESHEAF:~$ ocamlc --version
4.12.0
nojebar@PERVERSESHEAF:~$ ocamlc -o foo -c a.c
Options -c and -o are incompatible when compiling C files
```
??

> Do we want to adjust this behavior of the -o flag without -c in the case where the input files are exactly one C file?

Am not sure, but the current behaviour is a bit unexpected. If the `-o` argument is ignored in some cases wouldn't it be better to fail if it is used in those cases?

**Comment by lthls** [comment]
My two cents: `ocamlc -o foo a.c` is not a compilation command, it's a link command that needs to compile some of its inputs first.
It should throw an error (with or without the `-o` flag), as none of the provided inputs will be actually linked (the bytecode compiler ignores C object files unless in `-custom` mode). Currently a link command without OCaml inputs succeeds without doing anything, probably to ensure that non-compilation commands like `-help` or `-config` succeed, but there should probably be a check that C objects are not present too.

If we want to preserve the old behaviour for compatibility reasons, I don't mind, but it should be documented as a hack and not generalised more than strictly necessary.

**Comment by Octachron** [comment]
@nojb : Sorry, I meant the case without the `-c` flag where both 4.12 and trunk ignores the `-o` flag.

**Comment by nojb** [comment]
> @nojb : Sorry, I meant the case without the `-c` flag where both 4.12 and trunk ignores the `-o` flag.

Right, makes sense.
