### ISSUE TITLE
Bigarray kind cast

### ISSUE THREAD

**Issue by crackcomm** [ocaml/ocaml#10631]
Hello, I'm wondering if I'd submit a PR with a bigarray kind cast feature to a standard library, is there a chance it would get merged?

[Here](https://gist.github.com/crackcomm/9d5fbeaa8e038194cdbf0ba990d698e6#gistcomment-3889407) is something I have in mind, just more generic - this applies only conversion into a `Char` kind.

**Comment by xavierleroy** [comment]
> Hello, I'm wondering if I'd submit a PR with a bigarray kind cast feature to a standard library, is there a chance it would get merged?

Possibly,  but you'll have to write a clear description of what your "cast" function does (in the PR and as a doc string in the code), and provide convincing examples of use.  Based on your discuss.ocaml.org post, I'm not sure what you're trying to do, and why it matters.

**Comment by crackcomm** [comment]
The main use of this function is to cast multidimensional array into a bigstring type for hashing and sending it across the network. Hopefully that could be achieved without any C extensions. I think it's pretty common operation.

**Comment by crackcomm** [comment]
Turns out this functionality [exists](https://discuss.ocaml.org/t/cast-bigarray-kind/8469/9) in ctypes already. Unless we can do it better in stdlib I don't think it's necessary and I don't think I can. I'll give you the pleasure of closing this issue if you will, thanks for your support and help in fixing my code =)

**Comment by xavierleroy** [comment]
> Turns out this functionality exists in ctypes already.

Good to know!  

Re: sending bigarrays across the network, watch out for endianness mismatches between the two ends.  OCaml's marshaler (module `Marshal`) supports marshaling of bigarrays, and does take care of endianness conversions.
