### ISSUE TITLE
Rename file `Changes` to `CHANGES`

### ISSUE THREAD

**Issue by sidkshatriya** [ocaml/ocaml#10640]
We have `HACKING.adoc`, `LICENSE`, `INSTALL.adoc`, `BOOTSTRAP.adoc`, `README.adoc` and so on. The capitalization is often necessary for GitHub to recognize the file. However, the capitalization also gives prominence to the file in a long list of other files which may not be so important.

The `Changes` file is quite important. Many projects call it `CHANGELOG.md` or `CHANGELOG`. To adhere to this informal convention and also give prominence to this file when looking at the OCaml repo directory listing we should rename the file to `CHANGES` or `CHANGELOG`!

**Comment by dra27** [comment]
It has been called `Changes` since 1995 (at the same as `INSTALL`, `LICENSE` and `README` - `BOOTSTRAP.adoc` and `HACKING.adoc` are much younger)

**Comment by sidkshatriya** [comment]
Though its been called `Changes` since 1995, the point is that people who come from _outside_ the ocaml community may be able to navigate the git repo and find this file at a quick glance in a long list of files in the root folder. It's actually quite a valuable file and allows you to understand the progress OCaml is making at a quick glance -- having the file name in caps is useful. Many projects do have a file called `CHANGELOG` so it fulfills those expectations.

I'm totally cool if you wish to close this ticket if you think that it should remain `Changes`. Its actually not a big deal either way...

**Comment by dra27** [comment]
For the caps, changing to `CHANGES` or `CHANGELOG` won't change where it appears. FWIW, I find it quite visible being in Title case in the middle of a series of ALL CAPS:

```
BOOTSTRAP.adoc
CONTRIBUTING.md
Changes
HACKING.adoc
INSTALL.adoc
LICENSE
```

We get enough conflicts to deal with in normal operation of the Changes file - I'm concerned as to whether Git's rename mechanism might fall over with both conflicts _and_ renaming (especially across branches). On that basis, if you don't mind, I'm going to close this one.
