### ISSUE TITLE
Ignore `_opam` in git and check-typo

### ISSUE THREAD

**Issue by arbipher** [ocaml/ocaml#10648]
I followed the instructions in [HACKING](https://github.com/ocaml/ocaml/blob/trunk/HACKING.adoc).

Section `Testing with opam` mentions to create a local switch. This will result in a local `_opam` directory. 

Then `tools/check-typo` (mentioned in a later section) will scan the local files including `_opam` which has lots of warnings.

Maybe my first question are these instructions up-to-date? If so, I am thinking it may help to
1. add `/_opam` to `.gitignore`.
2. add `/_opam    typo.prune` to `.gitattributes`.

I can make a PR if appropriate.

**Comment by gasche** [comment]
Yes, I think that would be a good idea. Your PR is welcome.

**Comment by kit-ty-kate** [comment]
> add `/_opam` to `.gitignore`.

I think this is always welcome to have in the `gitignore` file.

> add `/_opam typo.prune` to `.gitattributes`.

Unless I'm mistake this should be unnecessary since the `tools/check-typo` script ignores files that are already listed in the `.gitignore` file.

**Comment by arbipher** [comment]
I just tested it.

If adding both to `.gitgnore` and `.gitattribute`:
```shell
⋊> ~/c/r/ocaml on gitignore-opam ◦ ./tools/check-typo                                                                                      15:40:23
INFO: pruned path ./manual (typo.prune)
INFO: pruned path ./build-aux (typo.prune)
INFO: pruned path ./_opam (typo.prune)
```

If adding just to `.gitgnore`.
```shell
⋊> ~/c/r/ocaml on gitignore-opam ◦ ./tools/check-typo                                                                                      15:42:23
INFO: pruned path ./manual (typo.prune)
INFO: pruned path ./build-aux (typo.prune)
INFO: pruned path ./_opam/.opam-switch/sources/ocaml-variants/manual (typo.prune)
INFO: pruned path ./_opam/.opam-switch/sources/ocaml-variants/build-aux (typo.prune)
INFO: pruned path ./_opam/.opam-switch/build/ocaml-variants.4.14.0+trunk/manual (typo.prune)
INFO: pruned path ./_opam/.opam-switch/build/ocaml-variants.4.14.0+trunk/build-aux (typo.prune)
```

The result is in both cases they are ignored though the rules applied are not the same.
I can modify the commit if you think just adding to `.gitignore` is better.
