### ISSUE TITLE
Handling of Misc.Fatal_error

### ISSUE THREAD

**Issue by zoggy** [ocaml/ocaml#10651]
Hi,

This is not a bug but a suggestion and a question regarding `Misc.Fatal_error`.

By now, `Misc.fatal_errorf` formats and prints the given error message on stderr and raises the exception `Fatal_error message`. This is not very convenient when embedding compiler-libs: you can catch the exception but the output has already been done.

Moreover it is not consistent with the rest of the compiler: Other exceptions are raised without printing any message and are caught in the main module, which prints them and exits.

Would it be possible to change `Misc.fatal_errorf` to just format the message and raise `Fatal_error`, and let main modules of tools catch it, print the message and exit ?

By the way, and just for my information, what is supposed to trigger a `Misc.Fatal_error` exception rather than another, more precise one ? I don't remember seeing a fatal error message on my regular use of the compiler and tools, so I guess this exception has a rather internal use.

**Comment by hhugo** [comment]
I just got the following `Fatal_error`. It is rather unfriendly.
```
$ cat ~/a.ml
let x = 2 + 4
$ BUILD_PATH_PREFIX_MAP=invalid ocamlc -g -c ~/a.ml
>> Fatal error: Invalid value for the environment variable BUILD_PATH_PREFIX_MAP: invalid key/value pair "invalid", no '=' separator
Fatal error: exception Misc.Fatal_error
```
