### ISSUE TITLE
Install the release notes in configure's docdir 

### ISSUE THREAD

**Issue by dbuenzli** [ocaml/ocaml#10668]
Finding the release notes of the compiler you are using in your opam switch is always a very frustrating and time consuming experience.

It could be much easier if `Changes` was installed in the `configure`'s `docdir` directory. It shouldn't then be hard for the `opam` ocaml package to set that directory to its `opam var doc` directory convention (which does not follow the standard configure layout, which has the docdir directory in `share`). 

That way any of these exceedly simple invocations will do the job:

```
less $(opam var doc)/ocaml/Changes
less $(opam var ocaml:doc)/Changes 
odig changes ocaml
```

There's certainly other things that could be installed there like the README, but I care a bit less about this one.

**Comment by nojb** [comment]
This sounds reasonable. Would you like to propose a PR? It should just be a matter of modifying the `install` target in the main `Makefile`.

**Comment by dbuenzli** [comment]
I'm afraid not. The reason why I didn't open a PR is that I think its more complicated than that :-) I'm not longer really familiar with the build system and autoconf machinery.
