### ISSUE TITLE
`Clflags.use_threads` is not set when using `ocamlc -I +threads`

### ISSUE THREAD

**Issue by arbipher** [ocaml/ocaml#10674]
Both `ocamlc -help` and `Changes` mentions:

>  -thread  (deprecated) same as -I +threads

> - #7687, #1653: 
> deprecate -thread option,
  which is equivalent to -I +threads.
  (Nicolás Ojeda Bär, report by Daniel Bünzli)

It doesn't reflect in `Clflags.use_threads` when parsing the command-line arguments given by `-I +threads`.

One related test case is [testsuite/tests/ppx-contexts/test.ml](https://github.com/ocaml/ocaml/blob/3eb0ab091f83b6d769ba6463a718b6935b011bc5/testsuite/tests/ppx-contexts/test.ml#L10).

**Comment by nojb** [comment]
My understanding is that `Clflags.use_threads` is deprecated/unneeded and we only left in there (it is always `false`) in order to avoid breaking existing code. What exactly is the behaviour that you have in mind?

**Comment by arbipher** [comment]
I just happen to realize it's deprecated after checking `ocamlc -help` for other things.
When I searched `-thread` in the code base (for document), I was then unclear whether `Clflags.use_threads` was deprecated together.
I re-check the previous issues and I think I overlook some discussions there.
