### ISSUE TITLE
Extra leading space for the first `item` of the `itemize` block in the manual

### ISSUE THREAD

**Issue by arbipher** [ocaml/ocaml#10671]
It looks like a rendering artifact in several sections e.g. [here](https://ocaml.org/manual/intfc.html#ss:staticlink-c-code) (_the table of the required_) and [here](https://ocaml.org/manual/flambda.html#s:flambda-inlining) (_to reduce the runtime overhead_)

The space is in the html output for the 1st item e.g. `" to reduce the runtime overhead ..."` .

The space is uniform for all the items in the manual source, e.g. see here
https://github.com/ocaml/ocaml/blob/3eb0ab091f83b6d769ba6463a718b6935b011bc5/manual/src/cmds/flambda.etex#L528

**Comment by sanette** [comment]
this is related to this Hevea issue:
https://github.com/maranget/hevea/issues/62
I thought it was fixed. Do you know which version of Hevea was used to generate this version of the manual?

**Comment by arbipher** [comment]
The metadata of the page html shows 2.35 (`<meta name="generator" content="hevea 2.35">`).
Your fix in heave is in dev.
so maybe we can wait for the hevea's next release?
