### ISSUE TITLE
A syntax for the empty polymorphic variant type

### ISSUE THREAD

**Issue by gasche** [ocaml/ocaml#10687]
I currently don't know how to write the empty polymorphic variant type, and I'm not the only one, see [this Discuss topic](https://discuss.ocaml.org/t/empty-polymorphic-variant-type/8467/3).

I propose the following syntax: `[ | ]`. This is rather consistent with the fact that leading bars are allowed in non-empty variants: ``type t = [ | `A | `B ]``.

Remarks:
- `[< ]` does not work as a ground type, as it has an implicit row variable.
- `[| ]` or ``[| `A | `B ]`` are rejected as `[|` is lexed as a different token. We could allow it to avoid user surprises, just like we do for variance declarations (we support `type +!'a` even though `+!` is lexed as a token).

Use case: suppose we want a limited type-level encoding of booleans (say, some absent/present information) where disjunction (but not conjunctino) can be computed implicitly. A natural approach is to take False/Absent to be the empty variant, True/Present to have one constructor, and to ensure that the values we manipulate keep an open variant type:

```ocaml
type absent = [ | ]
type present = [ | `Present ]

type +'a t
val absent : [> absent] t
val present : 'a -> [> 'present ] t
val union : 'p t -> 'p t -> 'p t
```

Currently the lack of syntax (to my knowledge) for empty variants can be worked around by:
1. Adding an arbitrary variant constructor, `` `Foo``, to both `absent` and `present`; rather silly
2. Not giving a name to the absent type, and using `val absent : [> ] t`

**Comment by gasche** [comment]
... of course the "natural" polymorphic variant encoding I proposed above doesn't quite work, because an `absent` value can be implicitly coerced to a `present` value. That's what you get for writing phantom polymorphic-variant signatures without testing them heavily first. The feature proposal still stands.

**Comment by mikeshulman** [comment]
It doesn't work as an encoding of booleans, but there are other situations in which one might want a pair of types in which one *can* be coerced to the other.

FYI, you can include backquotes in inline code by using double backquotes as the delimiter:
```
``[ | `A | `B ]``
```
produces ``[ | `A | `B ]``.

**Comment by garrigue** [comment]
This is not a problem of syntax: currently empty polymorphic variants are not allowed by the type checker.
Most often they denote typos, where one ends up creating a function that accepts no input.
```ocaml
let f = function `Aa -> 1 | `Bb -> 2;;
val f : [< `Aa | `Bb ] -> int = <fun>
let g = function `Aaa -> true | `Cc -> false;;
val g : [< `Aaa | `Cc ] -> bool = <fun>
let h x = (f x, g x);;
Error: This expression has type [< `Aa | `Bb ]
       but an expression was expected of type [< `Aaa | `Cc ]
       These two variant types have no intersection
```

**Comment by Willenbrink** [comment]
I'm interested in working on this issue, primarily as I've not contributed to the compiler yet and this seems to be a relatively simple issue.
@gasche: I assume you have not started work on this?
@garrigue: Is this really a concern? Merlin would tell you about the type. Also, if the function accepts no input it can never be called, therefore resulting in an unused warning. If it is part of the interface it will not typecheck unless you specify its argument as empty. I believe the benefit of having an empty polymorphic type outweighs this disadvantage.

**Comment by garrigue** [comment]
First point, this is a polymorphic variant issue, so unfortunately this is not a simple issue.
I.e., the type checker assumes and ensures that polymorphic variants are not empty in many places, so I'm afraid this requires to change many places.

I remember that I introduced this restriction because of repeated errors due to
typos. Having to do type-debugging to find typos is a non-starter.

Unfortunately, the current approach does not naturally lends itself to warnings.
The definition of `h` above contains no pattern-matching, so it would raise no warning.
Another approach could be to warn on functions whose type contains an empty type
in a negative occurrence. This would require experiments to see how this fares in practice.

**Comment by Willenbrink** [comment]
Okay, thanks for the information that it is neither simple to change nor clear whether this feature is really wanted. In that case I will find another issue to work on.

**Comment by Toxaris** [comment]
> This is not a problem of syntax: currently empty polymorphic variants are not allowed by the type checker.
> Most often they denote typos, where one ends up creating a function that accepts no input.

Just FYI, we have the following use case for an empty polymorphic variant type: we use phantom type variables to track effects, and would like to annotate "no effect" in a way that correctly merges with other effects.

**Comment by yallop** [comment]
Perhaps you can use object types instead, marking the phantom type parameter contravariant, and use `< >` to mean no effects
