### ISSUE TITLE
ocamllex: union of character sets

### ISSUE THREAD

**Issue by mjambon** [ocaml/ocaml#10754]
This is one of a few [features that I put in micmatch](https://mjambon.github.io/mjambon2016/micmatch-howto.html#regexp-basics) back in 2004 and were quite useful. I haven't asked about having these features in ocamllex until now, mostly because I hadn't been using ocamllex much until last year.

This first feature request is about allowing regexp definitions like this:

```ocaml
let lower = ['a'-'z']
let upper = ['A'-'Z']
let letter = lower | upper
let not_letter = _ # letter (* currently fails since 'letter' isn't understood as a character set *)
```
It's especially useful with complex sets like `let punct = [ ';' ':' ... ]` that we don't want to copy-paste.

I'm assuming this wouldn't change the semantic of the `|` operator where it's already permitted but maybe I'm missing something.

It looks like the implementation may be as simple as adding a case to the [`as_cset` function in `parser.mly`](https://github.com/ocaml/ocaml/blob/b6aa64e7eed6f0a9eddc4e5d2e3e1be282f5b729/lex/parser.mly#L44-L46) and tests. I'm happy to give it a shot if there's agreement on supporting the feature.

**Comment by xavierleroy** [comment]
That's a nice idea, thanks for suggesting it.
