### ISSUE TITLE
Bad C object file from ocamlopt -output-obj -o foo.o foo.ml

### ISSUE THREAD

**Issue by pestun** [ocaml/ocaml#10758]
ocamlopt 4.12.1
Linux with GNU cc 9.3.0
GNU ld 2.34

The object file `foo.o` from
```
ocamlopt -output-obj -o foo.o foo.ml
```
has undefined 
```
                 U camlFoo__code_begin
                 U camlFoo__code_end
                 U camlFoo__data_begin
                 U camlFoo__data_end
                 U camlFoo__entry
                 U camlFoo__frametable
                 U camlFoo__gc_roots
```
and does not link correctly with the main program in C.

The bug is observed under the combination of 
- name foo.o matching name foo.ml
- using ocamlopt over the GNU cc / ld 

https://discuss.ocaml.org/t/bad-object-file-from-ocamlopt-output-obj-o-foo-o-foo-ml/8753

**Comment by nojb** [comment]
As mentioned in the Discuss thread, this is bound to cause issues as there are two different files named `foo.o` being generated by this command, the one resulting from the compilation of `foo.ml` and the one coming from `-output-obj`. Whether that ends up working or not for some combination of linkers and systems is purely coincidental and it is bound to cause problems down the line. The easiest solution is to simply use a different filename for the `-output-obj` argument.

I guess this could be better documented on the manual, e.g. explicitly listing the set of files generated as a side effect when compiling a single source file and also adding a note to `-output-obj` regarding this issue.

**Comment by pestun** [comment]
I could think of two solutions:

- Forbid the option `ocamlopt -output-object -o object_name.o` where `object_name` matches to the name of one of intermediately generated files, decline to compile, throw an error and document this constraint on the name of output object file.  Easier to implement but leads to less user-friendly API to the clients of `ocamlopt` and more complex documentation? 

- Fix the linking process. For example, cache the intermediate object files before they become overridden the final `-o` output object. Harder to implement, but makes a cleaner API to the clients of `ocamlopt` in the long run?
