### ISSUE TITLE
Interactive toplevel ignores all input after the first double semicolon

### ISSUE THREAD

**Issue by dmbaturin** [ocaml/ocaml#10759]
There's a behavior in the interactive toplevel that is confusing beginners. If you enter multiple statements separated by double semicolons, only the first one is actually processed.

It would be nice if the top-level could split the input at double semicolons and execute all statements rather than used the first `;;` as an input terminator.

```ocaml
# let x = ref 0 ;;
val x : int ref = {contents = 0}

# print_endline "Updating the ref";; x := 1 ;;
Updating the ref
- : unit = ()
- 
# x ;;
- : int ref = {contents = 0}
```

If this isn't an intentional design choice and I'm not missing any undesirable consequences of allowing multiple statements on a single line, I'm ready to try my hand at fixing this.

**Comment by Armael** [comment]
(See also #8813 .)

**Comment by hhugo** [comment]
And https://github.com/ocaml/ocaml/issues/6472

**Comment by dmbaturin** [comment]
Sorry, my issue search failed to find that it was already reported.
