### ISSUE TITLE
exhaustiveness warning missing on GADTs when some warnings are suppressed

### ISSUE THREAD

**Issue by EduardoRFS** [ocaml/ocaml#10753]
The following module should trigger a `partial-match` warning. But it doesn't, if one of the `ocaml.warnings` on top are removed then the problem goes away but they seems to be completely unrelated to the `partial-match`.

```ocaml
[@@@ocaml.warning "-unused-var-unused-type-declaration"]
type _ nat =
  | O: _ nat
  | S: _ nat

let f: type a. a nat -> int = function | O -> 1
```

**Comment by gasche** [comment]
```
$ ocaml
        OCaml version 4.13.1

# [@@@ocaml.warning "-unused-var-unused-type-declaration"];;
Alert ocaml_deprecated_cli: Setting a warning with a sequence of lowercase or uppercase letters,
like 'eclaration', is deprecated.
Use the equivalent signed form:
-u-n-u-s-e-d-v-a-r-u-n-u-s-e-d-t-y-p-e-d-e-c-l-a-r-a-t-i-o-n.
Hint: Enabling or disabling a warning by its mnemonic name requires a + or - prefix.
Hint: Did you make a spelling mistake when using a mnemonic name?
```

You are hitting an UI issue we discussed at length in https://github.com/ocaml/ocaml/pull/9657#issuecomment-758092075 and should not occur with 4.13.1 anymore: here `-var` includes `-a`, which disables all warnings.

**Comment by EduardoRFS** [comment]
Thank you, yes I'm on 4.12 that's why thought it would still be present.

**Comment by gasche** [comment]
Welcome :-)
Note: I wrote 4.13.1 above, but in fact the warning is already in 4.13.0.

**Comment by gasche** [comment]
Some remarks when re-reading the warning in context:
- `eclaration` is the last group of consecutive non-prefixed letter, maybe we should show the first group or all groups
- I don't remember what is the proper way to pass several warning specifications (space-as-separator does not work, passing several strings is not supported, and using several `@@@warning` in a row is inconvenient), and I suspect the UI could still be improved. (Possibly a hint to say how to do that.)

**Comment by Octachron** [comment]
The multi-warning syntax has not been implemented yet.
