### ISSUE TITLE
OCaml 4.14 infinit loops while building odoc-parser

### ISSUE THREAD

**Issue by kit-ty-kate** [ocaml/ocaml#10762]
Reproductible with a simple `opam install odoc-parser`. e.g. with docker:
```
$ docker run --rm -it ocaml/opam:debian-11-ocaml-4.14
opam@4bca9a9111d3:~$ opam install odoc-parser
The following actions will be performed:
  - install ocamlfind   1.9.1  [required by astring]
  - install dune        2.9.1  [required by odoc-parser]
  - install ocamlbuild  0.14.0 [required by astring]
  - install result      1.5    [required by odoc-parser]
  - install topkg       1.0.4  [required by astring]
  - install astring     0.8.5  [required by odoc-parser]
  - install odoc-parser 0.9.0
[...]
```
<img width="853" alt="Screenshot 2021-11-10 at 11 30 30" src="https://user-images.githubusercontent.com/2611789/141118942-4e4d9e65-1b61-494c-8d8f-9a5a5f5379bd.png">

The file it infinit loops on is `src/token.ml`: https://github.com/ocaml-doc/odoc-parser/blob/626ccc9e319d7d3cc67251425ddbb48e33bc2de8/src/token.ml

**Comment by lthls** [comment]
Minimal repro:
```ocaml
type style = [ `Bold | `Italic ]
type t = [ `Begin_style of style ]
let print : [< t ] -> unit = function
  | `Begin_style `Bold -> ()
  | `Begin_style `Italic -> ()
```

The infinite loop happens somewhere in a call to `Parmatch.check_unused`.
Bisecting the issue points to commit 2250fd8a2218796c07b0a25f184cdc682e4695ba
