### ISSUE TITLE
Preserve original formatting in integer literal type hint

### ISSUE THREAD

**Issue by curiousleo** [ocaml/ocaml#10766]
# Context

There's code in `typecore.ml` to output a helpful hint in case someone forgets to add the appropriate suffix to a number literal. As far as I can tell, this hint always uses decimal notation stripped of any underscores.

That is fine if the original literal was in decimal and without underscores:

```
File "hints.ml", line 1, characters 16-18:                                                                                                                               
1 | let _ : int32 = 11
                    ^^
Error: This expression has type int but an expression was expected of type
         int32
  Hint: Did you mean `11l'?
```

If the original literal is in decimal but with underscores, those are dropped:

```
File "hints.ml", line 1, characters 16-21:
1 | let _ : int32 = 1_000
                    ^^^^^
Error: This expression has type int but an expression was expected of type
         int32
  Hint: Did you mean `1000l'?
```

If the original literal was expressed in another base, the hint gets a bit confusing: especially as the number gets large, it is not immediately obvious how the hint relates to the original literal:

```
File "hints.ml", line 1, characters 16-19:
1 | let _ : int32 = 0xB
                    ^^^
Error: This expression has type int but an expression was expected of type
         int32
  Hint: Did you mean `11l'?
```

Perhaps it is clear that `0xB` and `11` mean the same thing, but how about if the original literal was `0xFFFFFFFF` and the type hint says something about `4294967295L`?

The following simply confirm that octal and binary literals are translated to decimal notation in the hint as well:

```
File "hints.ml", line 1, characters 16-20:
1 | let _ : int32 = 0o13
                    ^^^^
Error: This expression has type int but an expression was expected of type
         int32
  Hint: Did you mean `11l'?
```

```
File "hints.ml", line 1, characters 16-22:
1 | let _ : int32 = 0b1011
                    ^^^^^^
Error: This expression has type int but an expression was expected of type
         int32
  Hint: Did you mean `11l'?
```

# Proposal 1

I think that ideally, the way the literal is rendered in the hint should be the same as in the original literal. I'm using `int32` in these examples, the formatting should be preserved for `in64` and `nativeint` in the same way:

- `let _ : int32 = 11` should hint at `11l` as currently
- `let _ : int32 = 1_000` should hint at `1_000l` (and underscores preserved for hexadecimal, octal and binary notation too)
- `let _ : int32 = 0xB` should hint at `0xBl`
- `let _ : int32 = 0o13` should hint at `0x13l`
- `let _ : int32 = 0b1011` should hint at `0b1011l`

# Proposal 2

As a step towards formatting the hint more closely to how the original literal was formatted, it would help if the base was preserved even if underscores are dropped.

# Proposal 3

As a very first step, if the hint included _all_ notations, that may also be an improvement over the status quo. But it may also be the case that this could confuse people.

Something along the lines of:

```
File "hints.ml", line 1, characters 16-22:
1 | let _ : int32 = 0b1011
                    ^^^^^^
Error: This expression has type int but an expression was expected of type
         int32
  Hint: Did you mean `11l'?
         (Alternative notations: `0xBl', `0o13l', `0b1101l')
```

**Comment by curiousleo** [comment]
I added Proposal 3 after looking at `typecore.ml` and seeing that at least a few steps up the call tree from `report_literal_type_constraint`, which adds the hint, the original formatting of the literal is not known.

**Comment by gasche** [comment]
If I understand correctly (from a distance), you are suggesting to add information to the typedtree that is already present in the parsetree. This is a reasonably easy change (as in: changing the parsetree breaks stuff, but there are not many external consumers of the typedtree so we are more relaxed there), would you like to propose a PR to do this?

Note however that we have entered the [Sequential glaciation](https://discuss.ocaml.org/t/the-road-to-ocaml-5-0/8584#the-sequential-glaciation-3), so work on this topic which is not Multicore-integration-related may have to wait until OCaml 5.0 to be merged upstream.

**Comment by curiousleo** [comment]
> If I understand correctly (from a distance), you are suggesting to add information to the typedtree that is already present in the parsetree.

Disclaimer: I am not familiar with the structure of the OCaml compiler specifically. But yes, that sounds very much like a high-level description of what needs to happen to make Proposal 1 possible. Thanks for adding this context here, it gives me a good starting point.

> This is a reasonably easy change (as in: changing the parsetree breaks stuff, but there are not many external consumers of the typedtree so we are more relaxed there), would you like to propose a PR to do this?

I'm happy to give it a go!

> Note however that we have entered the [Sequential glaciation](https://discuss.ocaml.org/t/the-road-to-ocaml-5-0/8584#the-sequential-glaciation-3), so work on this topic which is not Multicore-integration-related may have to wait until OCaml 5.0 to be merged upstream.

Thanks very much for this advance notice.
