### ISSUE TITLE
Module naming consistency between snake case and camel case in stdlib

### ISSUE THREAD

**Issue by hcarty** [ocaml/ocaml#10778]
We are about to gain very useful new `In_channel` and `Out_channel` modules in the OCaml stdlib. Meanwhile, in the multicore branch, new modules like `EffectHandlers` and `ThreadLocal` are being added. These names for these new modules are split between `Snake_case` and `CamelCase`. I know that the multicore modules have not landed in stdlib yet! This seems worth considering early so, if possible, stdlib module naming can be internally consistent.

I noticed the inconsistency in case while reading through the latest multicore update notes on the discuss forum. After asking some of the developers focused on multicore it was suggested that I raise the question here on the OCaml issue tracker.

**Comment by gasche** [comment]
I agree it's an issue, I personally prefer underscores (so `Snake_case`), but arguably we already have `ListLabels` and `ThreadUnix` in the standard library so the (camel) case could be made that we should stick with `CamelCase`.

**Comment by dbuenzli** [comment]
> stdlib module naming can be internally consistent.

This looks already a bit doomed. Among other things:

* `Std_exit`, `{In,out}_channel`
* `Bigarray`, `Hashtbl`, `Genlex`, `Topdirs`, `Nativeint`,  `Printexc`
* `Hashtbl.MakeSeeded`
* `*Labels`, `Camlinternal*`, `ThreadUnix` 

I note however that compiler-libs seems pretty consistent in ~~using snake case~~ not using `CamlCase`. 

If something needs to be decided for future additions count me in the camp of snake case everywhere. As I once wrote somewhere else:

> Since I don’t want to think too much about these things either while defining or using identifiers I always simply lowercase everything (acronyms included) separate words by underscore and for modules names capitalize the first letter as is mandated by the language.

**Comment by yminsky** [comment]
+1 for Snake_case. Jane Street standardized on that long ago, and we'd be happier if new additions to the compiler followed the same pattern.

**Comment by xavierleroy** [comment]
>     * `Std_exit`, `{In,out}_channel`

`Std_exit` is a linking trick, not visible to the user.  Indeed, it contains no definitions!
> 
>     * `Bigarray`, `Hashtbl`, `Genlex`, `Topdirs`, `Nativeint`,  `Printexc`

These are neither CamelCase nor Snake_case, just run-on words.  `HashTbl` or `Hash_tbl` would be pedantic.
> 
>     * `Hashtbl.MakeSeeded`
> 
>     * `*Labels`, `Camlinternal*`, `ThreadUnix`

`Camlinternal*` are not to be used directly, and `ThreadUnix` is deprecated and will disappear eventually.

So, this leaves `*Labels` vs. `In_channel`/`Out_channel`.

My personal taste is that `CamelCase` works well for capitalized identifiers, but `snake_case` works better for lowercase identifiers.  But I'm not arguing strongly one way or another.

**Comment by mshinwell** [comment]
I would prefer to see `Snake_case` since (at least empirically) this seems to be what the majority of code uses.  It is also what the compiler produces for module names from filenames in lower case, which again empirically seems to be the general convention.

**Comment by Chris00** [comment]
Once a decision is made on this, it would also be good to communicate it to the community.  Such "rules" should at least also be applied to the OCaml platform (cc @avsm).

**Comment by bikallem** [comment]
> Once a decision is made on this, 

How do we reach a decision on this? voting?

**Comment by hcarty** [comment]
Now that the 4.14 alpha is out with the `In_channel` and `Out_channel` names there seems to be limited time to make an explicit decision about stdlib module naming. `EffectHandlers` has been renamed to `Effect` for 5.00 so the initial new module naming inconsistency that sparked this issue has been addressed.

**Comment by gasche** [comment]
Well that's ideal:
- there is no *inconsistency* anymore
- not doing anything means that my favorite choice wins

I'm even tempted to close this issue. Does anyone disagree?

**Comment by nojb** [comment]
No disagreement in sight, let's close.
