### ISSUE TITLE
[4.14] Overridden methods keep their inherited attributes

### ISSUE THREAD

**Issue by kit-ty-kate** [ocaml/ocaml#10781]
Using the `4.14` branch (https://github.com/ocaml/ocaml/commit/3f170f317e8b1da5eb4197268c57deb717e82a95), the following code now fails (compiled fine in 4.13 and older):
```
class virtual virt = object
  method virtual private test : unit
end

let impl = object
  inherit virt
  method test = ()
end

let () = impl#test
```
with the following error message:
```
File "test.ml", line 10, characters 9-13:
10 | let () = impl#test
              ^^^^
Error: This expression has type virt
       It has no method test
```
This issue makes `0install.2.17` fail to build

**Comment by lpw25** [comment]
Fix in #10782
