### ISSUE TITLE
Moving tag numbers?

### ISSUE THREAD

**Issue by gasche** [ocaml/ocaml#10785]
Multicore changes the set of tags used for OCaml value representation and exposed through the `Obj` module.
(See [multicore:obj.ml](https://github.com/ocaml-multicore/ocaml-multicore/blob/4469f89/stdlib/obj.ml#L52-L70).)

As far as I can tell, the only change is the addition of two new tags, `Obj.forcing_tag` (a lazy thunk being forced) and `Obj.cont_tag` (which I assume is used for continuations / captured stack fragments). To make space for these new tags, `Obj.last_non_constant_constructor_tag` (which is also the maximal number of non-constant constructors in a datatype) moves from `245` to `243`.

Question: if we are going to add new tags, could we also consider reordering existing tags?

It would be nice-looking if thunk-related tags (`forcing_tag`, `lazy_tag` and `forward_tag`) were consecutive, and rather useful if closure-related tags (`closure_tag` and `infix_tag`) were consecutive. Indeed, some users (such as Coq's `native_compute`) have a need for quickly testing whether an object is a function, and I believe that it is easier to check if `t` is in `{247, 248}` than whether it is in `{247, 249}`. (For example you can do an unsigned subtraction of `247` and then check `<= 1`, as the pattern-matching compiler does for its `Isin` primitive.)

The downside, of course, is the risk of breaking existing code that would hardcode tag values (in OCaml or in C). However, I have the impression that such code could be rewritten in a compatibility-preserving way by using `Obj.foo` or the appropriate runtime macro.

Said otherwise: if we had the opportunity to redesign tag numbers from scratch, would we use the current mapping or a different one? Should we consider changing for 5.00?

**Comment by nojb** [comment]
> However, I have the impression that such code could be rewritten in a compatibility-preserving way by using `Obj.foo` or the appropriate runtime macro.

Just as a data point the `Obj.with_tag` optimization to avoid a double allocation only works with literal values (see #10051).

**Comment by gasche** [comment]
Note: the Multicore GC implementation currently assumes that `Forward_tag`, `Infix_tag` and `No_scan_tag` are contiguous ( [multicore:runtime/minor_gc.c](https://github.com/ocaml-multicore/ocaml-multicore/blob/4469f89/runtime/minor_gc.c#L248-L249) ). This means that either the lazy-related tags can be contiguous, or the closure-related tags, but not both. The latter would be enough for my interest in unboxed functions.

**Comment by lthls** [comment]
I believe that @mshinwell presented various alternatives for closure compilation in a past developer meeting; and at least one of them did not require an infix tag. That may prove useful for fast unboxed functions, as you only have one tag to check.

**Comment by gasche** [comment]
Note: the Multicore implementation of Lazy.force (the one inlined by the compiler that is located in... matching.ml) generates code that check whether the tag is `forcing_tag` or `lazy_tag`, and would thus benefit from the two tags being consecutive for the same reasons as `infix_tag` and `closure_tag`.

**Comment by gasche** [comment]
It is unclear that this would happen at any point, and that the benefits would be noticeable. Closing.
