### ISSUE TITLE
Make stack non-executable (FreeBSD)

### ISSUE THREAD

**Issue by devosalain** [ocaml/ocaml#10793]
When i put the security feature w^x on the os (freebsd) i.e.
sysctl:
kern.elf64.nxstack=0,
so pages are write-able OR executable but not both, the ocaml compiler spits out errors.
Maybe this is normal & expected behavior, maybe it isn’t ?

https://en.wikipedia.org/wiki/W%5EX

**Comment by xavierleroy** [comment]
OCaml doesn't need the stack to be executable.  However, the GNU linker (and perhaps the LLVM linker too) default to producing binaries with executable stacks.

For Linux, we add the appropriate annotation to assembly files to tell the linker that nonexecutable stacks are OK:
https://github.com/ocaml/ocaml/blob/3fa2cfce074d0a83225d7a21678b971bad959a7f/runtime/amd64.S#L695-L698

Would that work for FreeBSD too?  For any ELF-based platform?

**Comment by silene** [comment]
> Would that work for FreeBSD too?

Given the following commit in the FreeBSD repository, I guess it would. https://reviews.freebsd.org/rS319510

> For any ELF-based platform?

I am pretty sure NetBSD does not support this annotation. But I have no idea if it would just ignore it (the stack is not executable anyway, so it does not matter) or if it would choke on it.

**Comment by xavierleroy** [comment]
I cannot reproduce the problem on FreeBSD 13:
```
$ uname -a
FreeBSD ocaml-freebsd-64 13.0-RELEASE FreeBSD 13.0-RELEASE #0 releng/13.0-n244733-ea31abc261f: Fri Apr  9 04:24:09 UTC 2021     root@releng1.nyi.freebsd.org:/usr/obj/usr/src/amd64.amd64/sys/GENERIC  amd64
$ sysctl kern.elf64.nxstack
kern.elf64.nxstack: 0
$ ocamlopt -o hello.exe hello.ml
$ ./hello.exe
Hello, world!
$ readelf -a ./hello.exe | grep GNU_STACK -A 1
  GNU_STACK      0x0000000000000000 0x0000000000000000 0x0000000000000000
                 0x0000000000000000 0x0000000000000000  RW     0
```
So, no kernel errors (nothing in the logs either) and the stack is `RW`, not `RWE`.

**Comment by kostikbel** [comment]
On FreeBSD stable/13 and ocaml built from the today trunk, I still see
```
   GNU_STACK      0x0000000000000000 0x0000000000000000 0x0000000000000000
                 0x0000000000000000 0x0000000000000000  RWE    0x10
```
FWIW, `kern.elf64.nxstack=0` forces executable stack for native 64bit ELF binaries unconditionally, I do not know why it was cited there.  W^X is controlled by `kern.elf64.allow_wx`. With this knob tweaked, I see
```
$ sudo sysctl kern.elf64.allow_wx=0 
Password:
kern.elf64.allow_wx: 1 -> 0
$ ./hello-ocaml
exec_new_vmspace: mapping stack size 0x20000000 prot 0x7 failed mach error 2 errno 13
[1]    1270 abort      ./hello-ocaml
```
Adding .note.GNU-stack section should be quite safe for systems not supporting it, for them it would result in PT_GNU_STACK segment that is not processed by image activator and dynamic linker.

**Comment by avsm** [comment]
I can't reproduce this either, on either OCaml 4.13.1 or OCaml 5.0+trunk

```
# uname -a
FreeBSD freebsd-dev-1 13.0-RELEASE-p6 FreeBSD 13.0-RELEASE-p6 #0: Mon Jan 10 06:28:50 UTC 2022
# sysctl kern.elf64.allow_wx=0
kern.elf64.allow_wx: 0 -> 0
# ocamlopt.opt hello.ml
# ./a.out
hello world
# ocamlc -version
4.13.1
```

Setting `kern.elf64.nxstack=0` after forcing allow_wx does predictably and dramatically trash the system since nothing can validly execute after that.

**Comment by nojb** [comment]
Closing this as non-reproducible, feel free to open a new issue if needed.
