### ISSUE TITLE
Pretty printer drops variance from LHS of type substitution

### ISSUE THREAD

**Issue by lukemaurer** [ocaml/ocaml#10790]
I was surprised to discover this syntax is valid, but apparently so:

```
module type T1 = sig
  type 'a t
end

module type ListT1 = T1 with type +'a t := 'a list
```

```
$ ocamlc -c a.ml
$
```
It's checked for consistency with the RHS, too (the above does not work with `-'a t`). But it's not printed faithfully by the pretty printer:

```
$ ocamlc -dsource -c a.ml 
module type T1  = sig type 'a t end
module type ListT1  = T1 with type 'a t :=  'a list
```

AFAICT the source printed this way will always compile, but it's a problem for ppxes and `[@@deriving_inline]`, since ppxlib's `mk_named_sig` will sometimes generate this construction. (It doesn't have to, clearly, so this particular problem could be fixed there as well.)

**Comment by nojb** [comment]
Thanks for the report. Fixes for `-dsource` are welcome!

Could you say a few words about your use-case though? My understanding is that `-dsource` is *not* a general-purpose pretty-printer, but a debugging aid. No tooling should depend on its output, as it is known to have edge cases and is not tested consistently, etc.
