### ISSUE TITLE
Change the toplevel prompt character? (because of beginner confusion with directives)

### ISSUE THREAD

**Issue by wikku** [ocaml/ocaml#10805]
Many materials introducing the toplevel* have to warn that the `#` prompt is different from the `#` at the beginning of directives.
If no one is particularly attached to the `#` prompt, we could change it to (for example) `>` to eliminate this confusion. The materials saying that `#` is the prompt would become a bit outdated, but maybe it won't be very surprising if done in the same release as another change in the toplevel looks (#10527).

---

\* including [the OCaml manual](https://ocaml.org/manual/toplevel.html#s%3Atoplevel-directives), the HOL Light tutorial, [CS3110 at Cornell](https://cs3110.github.io/textbook/chapters/basics/toplevel.html)

**Comment by xavierleroy** [comment]
Back in 1978, Milner's original ML implementation already used `#` as its prompt,  according to the "Edinburgh LCF" book.  Perhaps that's the reason why CAML, Caml Light, Caml Special Light, Objective Caml and OCaml all use `#` as prompt.  (SML/NJ and Moscow ML use `-`.)  So, this is not to be changed lightly :-)

**Comment by dra27** [comment]
Given that terminal colour support is fairly pervasive, we could instead consider putting the prompt character in another colour? (I recently started putting shell prompts in dark grey for demonstrations)

**Comment by wikku** [comment]
Colors are already used in error messages, so that should be fine.

Additionally the handler for "Unbound value" could be overridden in the toplevel to hint if the unbound name is a directive.

**Comment by dra27** [comment]
The hint sounds like a great idea! It'd obviously be "glaciated" at the moment, but is this something you'd be able/happy to work on?

**Comment by wikku** [comment]
It would presumably be similar to/expand on #10647, so after that gets approved/merged

**Comment by ferminr** [comment]
Maybe the prompt could be configurable... In GHCI, your prompt can be a lambda: all you need to do is add  :set prompt "λ>" to your .ghci file

**Comment by xavierleroy** [comment]
We could possibly add a directive to change the prompt, which you could invoke from your `.ocamlinit` file, but the directive would start with a `#` :-)

**Comment by dra27** [comment]
Briefly setting aside the ecstasy of being able to have 🐫 as my toplevel prompt character, being able to configure the prompt character wouldn’t help beginners, though, which is the original thread of this issue

**Comment by xavierleroy** [comment]
See also #10059 .
