### ISSUE TITLE
Install META files for compiler libraries

### ISSUE THREAD

**Issue by nojb** [ocaml/ocaml#10810]
(I know non-Multicore devs are frozen at the moment, but just to get the dicussion started...)

The fact that the compiler does not install META files is a source of problems for the two main consumers of this metadata: `ocamlfind` and `dune`. In fact, both tools include their own set of META definitions for these libraries to avoid depending on each other. This leads to tricky bugs from time to time as well as adding friction due to the need to keep them in sync with each other and with the library definitions.

Having the compiler install META files for its own libraries would cleanly solve this issue, and would be a small change at that. I don't see any outright downsides to doing so.

Opinions?

cc @jeremiedimino

**Comment by gasche** [comment]
Sounds like a good idea. Is it clear where they should be installed?

**Comment by nojb** [comment]
I think the most compatible choice would be to install `META.stdlib` in `$(ocamlc -where)` and `META` files for `compiler-libs` in `$(ocamlc -where)/compiler-libs`. This respects the existing conventions so that adding `$(ocamlc -where)` to `OCAMLPATH` would allow `ocamlfind` and `dune` to find these `META` files, without any extra special logic.

**Comment by gasche** [comment]
That sounds good to me. Would you want to submit a PR?

**Comment by nojb** [comment]
> That sounds good to me. Would you want to submit a PR?

Will do. Thanks for the ping!

**Comment by nojb** [comment]
> That sounds good to me. Would you want to submit a PR?

#11007
