### ISSUE TITLE
It is no longer possible to shorten Sys.argv in trunk

### ISSUE THREAD

**Issue by garrigue** [ocaml/ocaml#10819]
In all released versions of OCaml one can modify `Sys.argv` by updating its fields and truncating it.
Lablgtk uses this feature to support the behavior of `gtk_init`, which filters some command line options before the application processes it.
But in trunk `Obj.truncate` has been removed, so that it is no longer possible to adjust the size of `Sys.argv`.

I'm not sure what a solution should be, but this is a concern.

**Comment by nojb** [comment]
Have you tried using the primitive `caml_sys_modify_argv`? https://github.com/ocaml/ocaml/blob/759d667092f684cce696898193044c94387e9df1/toplevel/topcommon.ml#L271-L272

**Comment by garrigue** [comment]
Thanks ! 
Exactly what I need.
Is the change advertised somewhere ?
Clearly this function is not included in `Sys`.

**Comment by nojb** [comment]
No, it is not documented, it was introduced when `Obj.truncate` was deprecated with the toplevel in mind only: https://github.com/ocaml/ocaml/pull/2279

**Comment by Octachron** [comment]
See also  #9251 for a (short lived) discussion about exposing `modify_argv` in the standard library.

**Comment by garrigue** [comment]
While I agree with @gasche 's comment there that providing a function to do this in `Sys` may be overkill, it would be good to document this somewhere, as closed issues are not the best documentation.
Anyway, I close this since this solves my problem.
