### ISSUE TITLE
Synchronization of `refcount` fields in `bigarray.h`/`io.h`

### ISSUE THREAD

**Issue by gadmm** [ocaml/ocaml#10832]
As per https://github.com/ocaml/ocaml/pull/10831, this concerns the multicore PR and is opened as a separate issue from the PR.

The `refcount` fields in `caml/{bigarray,io}.h` perform reference counting for values that may or may not be shared across threads (with or without appropriate synchronisation by the user during their use). The one in `io.h` was made atomic, but the one in `bigarray.h` was not. I think that atomic refcounting is needed both for memory safety (hence MVP) and because programmers would not be able to implement their own synchronisation mechanism since they do not control when finalizers run.

It might be worth it to factorize in a helper header the code needed to implement refcounted finalizers in io.h/bigarray.h. As a post-MVP feature suggestion, I think that refcounted finalizers for similarly-shared resources can be useful to programmers, because atomic refcounting is delicate to implement correctly in an optimized fashion (with a bonus question: does the OCaml memory model change anything to the usual optimized implementation?).

**Comment by xavierleroy** [comment]
You're right, bigarray refcounts should be implemented with atomic updates.

Which "optimized implementation" do you have in mind?  At any rate, refcount manipulations over channels are not performance-critical.  For bigarrays, they occur only when sub-arrays (slices) are taken, which I suspect is rarely performance-critical either.

**Comment by gadmm** [comment]
With the C++11 memory model at least you only need relaxed increment/decrements, which makes a difference on armv8 (and none on x86): [godbolt](https://godbolt.org/#g:!((g:!((g:!((h:codeEditor,i:(fontScale:14,fontUsePx:'0',j:1,lang:___c,selection:(endColumn:1,endLineNumber:2,positionColumn:1,positionLineNumber:2,selectionStartColumn:1,selectionStartLineNumber:2,startColumn:1,startLineNumber:2),source:'%23include+%3Cstdatomic.h%3E%0A%0Avoid+release(void)%3B%0A%0Avoid+drop_seq_cst(atomic_int+*+n)%0A%7B%0A++++if+(1+%3D%3D+atomic_fetch_sub(n,+1))+%7B%0A++++++++release()%3B%0A++++%7D%0A%7D%0A%0Avoid+drop_relaxed(atomic_int+*+n)%0A%7B%0A++++if+(1+%3D%3D+atomic_fetch_sub_explicit(n,+1,+memory_order_release))+%7B%0A++++++++atomic_thread_fence(memory_order_acquire)%3B%0A++++++++release()%3B%0A++++%7D%0A%7D%0A%0Avoid+clone_seq_cst(atomic_int+*+n)%0A%7B%0A++++atomic_fetch_add(n,+1)%3B%0A%7D%0A%0Avoid+clone_relaxed(atomic_int+*+n)%0A%7B%0A++++atomic_fetch_add_explicit(n,+1,+memory_order_relaxed)%3B%0A%7D%0A'),l:'5',n:'0',o:'C+source+%231',t:'0')),k:35.97835888187557,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((g:!((h:compiler,i:(compiler:armv8-cclang-trunk,filters:(b:'0',binary:'1',commentOnly:'0',demangle:'0',directives:'0',execute:'1',intel:'0',libraryCode:'1',trim:'1'),flagsViewOpen:'1',fontScale:14,fontUsePx:'0',j:2,lang:___c,libs:!(),options:'-O2',selection:(endColumn:1,endLineNumber:1,positionColumn:1,positionLineNumber:1,selectionStartColumn:1,selectionStartLineNumber:1,startColumn:1,startLineNumber:1),source:1,tree:'1'),l:'5',n:'0',o:'armv8-a+clang+(trunk)+(C,+Editor+%231,+Compiler+%232)',t:'0')),header:(),k:57.98403193612775,l:'4',m:79.25824175824175,n:'0',o:'',s:0,t:'0'),(g:!((h:output,i:(compiler:2,editor:1,fontScale:14,fontUsePx:'0',tree:'1',wrap:'1'),l:'5',n:'0',o:'Output+of+armv8-a+clang+(trunk)+(Compiler+%232)',t:'0')),header:(),l:'4',m:20.741758241758244,n:'0',o:'',s:0,t:'0')),k:64.02164111812444,l:'3',n:'0',o:'',t:'0')),l:'2',n:'0',o:'',t:'0')),version:4).

I agree that performance is not important for channels; for bigarray slices this is less clear to me. Anyway the point is first that the current code could benefit in clarity from being factored via a notion of refcounted finalized resource; then having the usual implementation simply avoids making assumptions based on particular use-cases.

**Comment by gadmm** [comment]
@kayceesrk Could this get a 5.0 label?

**Comment by kayceesrk** [comment]
Sure. This needs to be done for 5.0. 

I agree that bigarray refcounts are not performance-critical. For 5.0, I would prefer to go with a correct and possibly inefficient implementation. We can go for a more efficient implementation when we have benchmarks that exhibit the need.

**Comment by Octachron** [comment]
Closed by #11177 which implements the naive refcounting functions and use them for bigarrays.
