### ISSUE TITLE
[ocamldoc] html - type escapes its 'type' class

### ISSUE THREAD

**Issue by sanette** [ocaml/ocaml#10842]
Consider the following mli file
```ocaml
type t
```
and produce the doc with `ocamldoc -html`.
The resulting code contains
```html
<pre><span id="TYPEt"><span class="keyword">type</span> <code class="type"></code>t</span> </pre>
```
We can see that the `t` (near the end of that line) is outside of its `<code>` element (and hence doesn't get correctly styled by the CSS).

**Comment by gasche** [comment]
(cc @Octachron)

I'm not sure, but this might in fact be the desired behavior if the idea was to style type names (or add links, etc.) in a way that would not work inside `<code>`.

**Comment by sanette** [comment]
on the other hand the styling of `val f : t -> t` does put the type `t` inside `<code>`:

```html
<pre><span id="VALf"><span class="keyword">val</span> f</span> : <code class="type"><a href="Aaa.html#TYPEt">t</a> -> <a href="Aaa.html#TYPEt">t</a></code></pre>
```

**Comment by Octachron** [comment]
I am marking this is issue as wontfix because this is a potentially breaking change that seems out of scope for ocamldoc maintenance mode.
