### ISSUE TITLE
trunk does not compile if Flambda is enabled

### ISSUE THREAD

**Issue by pi8027** [ocaml/ocaml#10869]
I get the following compilation error:
```
File "/home/i/src/ocaml/otherlibs/dynlink/otherlibs/dynlink/dynlink_common.ml", lines 129-130, characters 10-53:
Error (warning 59 [flambda-assignment-to-non-mutable-value]): A potential assignment to a non-mutable value was detected
in this source file.  Such assignments may generate incorrect code
when using Flambda.
```

**Comment by pi8027** [comment]
I confirm this is not the case in https://github.com/ocaml/ocaml/commit/263a2a429ce3f4a70318f6487e93ae84a86686ae. So I guess Multicore OCaml broke Flambda.

The reason I have to try this is that I wish to use both TRMC and Flambda for benchmarking purposes in my paper. Here is my side question: which commit of OCaml is reasonable to use in my case?

**Comment by Octachron** [comment]
Flambda is indeed not yet supported in OCaml 5.

Rather than using trunk which is not stable in anyway, you should use the 4.14 branch (since multicore is the only difference between 4.14.0 and 5.00) .

There will be a first alpha release of 4.14.0 relatively soon (this week?) which should be more stable for testing purpose.

**Comment by pi8027** [comment]
Thanks for the explanation. I thought TRMC has not been merged in 4.14.0, but apparently, it was incorrect. Let me close the issue.

**Comment by gasche** [comment]
I'm curious to know more about what use TRMC you are interested in :-)

**Comment by pi8027** [comment]
> I'm curious to know more about what use TRMC you are interested in :-)

I have a [Coq library](https://github.com/pi8027/stablesort) to prove the stability of mergesort functions using parametricity. The motivation of this work is as follows: Non-tail-recursive mergesort (e.g., Haskell's `Data.List.sort`) allows us to compute output incrementally in call-by-need evaluation but consumes the call stack linearly in call-by-value evaluation. In contrast, tail-recursive mergesort (e.g., OCaml's `List.stable_sort`) prevents consuming the call stack in call-by-value evaluation but does not allow for incremental computation. Therefore, we argue that the best implementation of mergesort depends on the situation, in particular, the evaluation strategy and whether it should be incremental or not.

However, it seems that non-tail-recursive mergesort is actually tail-recursive modulo cons. So I think I have to check which implementation is the best one in the presence of TRMC.

Note that some of our implementations extracted from Coq achieve comparable performance with OCaml's `List.stable_sort`. Benchmark results are available here: https://github.com/pi8027/stablesort/blob/benchmark-results/output/main.pdf
