### ISSUE TITLE
glibc's handling of signaling NaN

### ISSUE THREAD

**Issue by gretay-js** [ocaml/ocaml#10862]
The value of `Float.nan ** 0.` expression depends on the version of glibc: it's `nan` with glibc 2.25 or later, and `1.` for older versions.

This is caused by changes in the handling of signaling NaN values in glibc to confirm to TS 18661-1. It affects OCaml's Float.nan, which is a signaling NaN.  In this example, the implementation of `pow` in glibc  changed (see [issue 20916](https://sourceware.org/bugzilla/show_bug.cgi?id=20916).), but there may be other functions.  

This changes the behavior of some existing ocaml code in subtle ways. How should it be handled? 

@xavierleroy

**Comment by xavierleroy** [comment]
I forgot that `Float.nan` is a signaling NaN.  I wonder if this was a conscious decision or just bad luck... and if there is consensus that it should better be a quiet NaN, now could be a good time to do the change (in OCaml 5.00).

I also can't help but think that well-written numerical code should not raise numbers to the 0. power.

**Comment by xavierleroy** [comment]
Addressed in #10899.
