### ISSUE TITLE
caml_thread_setname compilation and adjustments

### ISSUE THREAD

**Issue by abbysmal** [ocaml/ocaml#10870]
I am opening this issue to track two things that were brought up during the Multicore PR review. (#10831)

The first item is a comment made by @damiendoligez about `caml_ml_domain_set_name` not taking into account the extra id appended by `caml_thread_setname` when checking for length. (see https://github.com/ocaml/ocaml/pull/10831#discussion_r779668302)

I think `caml_ml_domain_set_name` should actually not append an id to the thread name: this function is the user facing utility to allow user to name the underlying domain's system thread, and as such users should have full control over the name. This also makes the length checking logic simpler.

The second item is an observation made by @avsm on the macro used to check for the existence of `pthread_setname_np` and portability concerns.
I could not track down the exact comment, but I think it is worth discussing this here as well.
It seems like @avsm was unsure about the usage of `_GNU_SOURCE` for the feature check and that we may have to be a bit more specific for it to be not bricky.

**Comment by hannesm** [comment]
For portability, I guess configure should be instructed to test for `pthread_setname_np` (similar to how `HAS_TIMES` works), since e.g. on BSD systems the function is available, but there's no `_GNU_SOURCE`. It seems that the function is of different arity on macOS than BSD & Linux.

**Comment by avsm** [comment]
I'm just testing a fix for this; will open it once the testsuites all churn through on the various BSDs
