### ISSUE TITLE
Move Random to a splitting generator

### ISSUE THREAD

**Issue by gasche** [ocaml/ocaml#10877]
(This is a tracking issue for Random+Multicore, which we could act upon now that Multicore is merged in trunk.)

There is consensus that Random should "split" its global generator state when a new domain is spawned. There are two aspects to this:
- the domain-local-state API needs to support "splitting" functions; this was prototyped in https://github.com/ocaml-multicore/ocaml-multicore/pull/756, submitted upstream as https://github.com/ocaml/ocaml/pull/10887
- the PRNG should change to a new algorithm where a splitting operation has been studied to be statistically robust; see https://github.com/ocaml/RFCs/pull/28 and https://github.com/ocaml/ocaml/pull/10742

**Comment by xavierleroy** [comment]
Sir! Yes, sir!  Right now I'm fixing a 2x slowdown in the bytecode interpreter (#10880) and trying to get the Inria CI working again, but after this I'll devote all my attention to the PRNG, sir!

**Comment by xavierleroy** [comment]
In the meantime, why don't you resurrect https://github.com/ocaml-multicore/ocaml-multicore/pull/756 as a pull request here?  We'll need DLS keys of the "split from parent" kind anyway.

**Comment by gasche** [comment]
Indeed, this is the first item above and I'm planning to do this soon. (Unfortunately I don't have a 2x speedup of my own to report ;-)

**Comment by gasche** [comment]
I have submitted the Domain.DLS change as an upstream PR: #10887.

**Comment by xavierleroy** [comment]
I think we're done with this task.
