### ISSUE TITLE
Make Format buffer more efficient for Multicore

### ISSUE THREAD

**Issue by gasche** [ocaml/ocaml#10876]
(this issue was raised during the "synchronous review" period for Multicore; it's easier to work on it now that Multicore is merged in trunk.)

When a second domain is spawned, Format switches to a buffered implementation for stdout/stdeer, where writes only happen on flushes. This provides best-effort behavior in presence of interleaved writes to those global mutable formatters.

The implementation is currently relatively crude, switching to a `Buffer.t` value that is then flushed explicitly. In a quick&dirty experiment I measured an overhead of about +100% on `ocamlc -dtypedtree` with the buffered implementation. It should be possible to reduce the overhead by pushing the buffering logic inside the Format engine itself, which already decides to delay printing in some situations. (If the overhead becomes small enough, we could even think of simplifying the code by staying buffered all the time.)

**Comment by Octachron** [comment]
Looking at the issue more precisely, I don't think it is really straightforward path to move the buffered implementation inside Format formatting logic itself: the buffering at the formatting engine level is mostly done at the line level, while the formatting engine is waiting for a break hint to resolve into either a space or a line break. This does not really line-up with the use of flushes as synchronization point in the multicore buffered implementation.

Orthogonally, the efficiency of the two implementations does not seem completely comparable. In my tests, there are cases (e.g https://gist.github.com/Octachron/2a72556bba4ca1cdfdd04ea9133ddec3)  where spawning a domain to switch to the multicore buffered implementation results in a speedup by a factor of ×4.

**Comment by gasche** [comment]
Good news! The issue is solved by doing nothing, then. Closing.
