### ISSUE TITLE
Downstream patch changes for deprecated functions from PR#10867

### ISSUE THREAD

**Issue by shakthimaan** [ocaml/ocaml#10917]
As a follow-up to https://github.com/ocaml/ocaml/pull/10867/files, I am trying to build `easy-format-1.3.2` and `cubicle.1.1.2` with the latest trunk. I have replaced most of the `_tag` functions with `_stag` functions. Can you please advise on the correct patch changes for the following two compiler errors?
1. `easy-format-1.3.2`
```
# File "src/easy_format.ml", line 338, characters 23-35:
# 338 |         tag_string fmt p.atom_style s;
#                              ^^^^^^^^^^^^
# Error: This expression has type style_name option
#        but an expression was expected of type Format.stag option
#        Type style_name = string is not compatible with type Format.stag 
```
The context of the code is:
```
  let tag_string fmt o s =
    match o with
        None -> pp_print_string fmt s
      | Some tag ->
          pp_open_stag fmt tag;
          pp_print_string fmt s;
          pp_close_stag fmt ()

  let rec fprint_t fmt = function
      Atom (s, p) ->
       tag_string fmt p.atom_style (Format.String_tag s);
       ...
```
2. `cubicle-1.1.2`
I have replaced `Obj.set_tag` with `Obj.with_tag`, but, I get the following error:
```
# File "enumerative.ml", line 1187, characters 35-47:
# 1187 |   List.iter (fun s -> Obj.with_tag (Obj.repr s) (Obj.no_scan_tag)) env.states
#                                           ^^^^^^^^^^^^
# Error: This expression has type Obj.t but an expression was expected of type
#          int
# make: *** [Makefile:168: enumerative.cmx] Error 2
```
The relevant code in `enumerative.ml` is:
```
let no_scan_states env =
  (* Prevent the GC from scanning the list env.states as it is going to be
     kept in memory all the time. *)
  List.iter (fun s -> Obj.with_tag (Obj.repr s) (Obj.no_scan_tag)) env.states
```
What number should be used after `Obj.with_tag`?

**Comment by nojb** [comment]
> 1. `easy-format-1.3.2`
> 
> The context of the code is:
> 
> ```
>   let tag_string fmt o s =
>     match o with
>         None -> pp_print_string fmt s
>       | Some tag ->
>           pp_open_stag fmt tag;
>           pp_print_string fmt s;
>           pp_close_stag fmt ()
> 
>   let rec fprint_t fmt = function
>       Atom (s, p) ->
>        tag_string fmt p.atom_style (Format.String_tag s);
>        ...
> ```

This seems the wrong fix. The second argument of `tag_string` is a tag name (optionally) and the third argument a `string`. So the right fix is to leave the callsites of `tag_string` as they were (eg `tag_string fmt p.atom_style s`) and change the call of `pp_open_stag` in the definition of `tag_string` to `pp_open_stag fmt (String_tag s)`.

> 2. `cubicle-1.1.2`
>    I have replaced `Obj.set_tag` with `Obj.with_tag`, but, I get the following error:
> 
> ```
> # File "enumerative.ml", line 1187, characters 35-47:
> # 1187 |   List.iter (fun s -> Obj.with_tag (Obj.repr s) (Obj.no_scan_tag)) env.states
> #                                           ^^^^^^^^^^^^
> # Error: This expression has type Obj.t but an expression was expected of type
> #          int
> # make: *** [Makefile:168: enumerative.cmx] Error 2
> ```

The right fix is to replace `Obj.set_tag (Obj.repr s) (Obj.no_scan_tag)` by `Obj.with_tag Obj.no_scan_tag (Obj.repr s)` (note the order of arguments).

Please confirm here if this fixes your build, so that we can close the issue. Thanks!

**Comment by lthls** [comment]
For cubicle, I already wrote a patch to compile it with Flambda 2. You can find my patch [here](https://github.com/ocaml-flambda/flambda2-opam/blob/main/packages/cubicle/cubicle.1.1.2%2Bflambda2/files/0001-Replace-Obj.set_tag-with-Obj.with_tag.patch).
It's more complicated than just a one line change because I wanted to make sure that the allocation patterns were not changed. If you plan to submit the patch upstream, I would suggest to use my patch (or something similar).

**Comment by shakthimaan** [comment]
I have `cubicle.1.1.2` building now with https://github.com/ocaml-bench/sandmark for 5.00.0+trunk. I used Vincent patch, but, I also had to patch `pretty.ml` to use _stag functions instead.
For easy-format-1.3.2, with the following code change:
```
let tag_string fmt o s =
    match o with
        None -> pp_print_string fmt s
      | Some tag ->
          pp_open_stag fmt (String_tag s);
          pp_print_string fmt s;
          pp_close_stag fmt ()

  let rec fprint_t fmt = function
      Atom (s, p) ->
       tag_string fmt p.atom_style s;

    | List ((_, _, _, p) as param, l) ->
        open_tag fmt p.list_style;
        if p.align_closing then
          fprint_list fmt None param l
        else
          fprint_list2 fmt param l;
        close_tag fmt p.list_style

    | Label (label, x) -> fprint_pair fmt label x
    | Custom f -> f fmt
```
I now get this error:
```
# File "src/easy_format.ml", line 341, characters 21-33:
# 341 |         open_tag fmt p.list_style;
#                            ^^^^^^^^^^^^
# Error: This expression has type style_name option
#        but an expression was expected of type Format.stag option
#        Type style_name = string is not compatible with type Format.stag 
```
Thanks for your prompt replies.

**Comment by nojb** [comment]
> I now get this error:

See https://github.com/ocaml-community/easy-format/pull/27 for a patch to make `easy-format` compile.

**Comment by shakthimaan** [comment]
Thanks for the patch to build `easy-format`. It builds fine with trunk! The issue can be closed.
