### ISSUE TITLE
Private values

### ISSUE THREAD

**Issue by hsk** [ocaml/ocaml#10919]
When we try to create private values, we have to write a mli file.
If we write the private keyword before let, we can create private values without using a mli file, which is convenient.

**Comment by Octachron** [comment]
The `open struct ... end` construct can be used to create such private values.

However, writing interface file is the expected good practice: it improves separate compilation, gives a clear contract to library users, and it is also the right place to write the documentation.

Consequently, such `private` keyword seem to me to be mostly an anti-feature.
