### ISSUE TITLE
configure.ac should reject all 32-bit platforms

### ISSUE THREAD

**Issue by dra27** [ocaml/ocaml#10916]
OCaml 5.00 requires a 64-bit platform - although the native compiler will be disabled, the bytecode runtime will still attempt to build on a 32-bit platform.

**Comment by glondu** [comment]
Are you saying that even bytecode will no longer be supported on 32-bit?

**Comment by xavierleroy** [comment]
> Are you saying that even bytecode will no longer be supported on 32-bit?

We don't know yet.  5.00 is a "minimal viable product" meaning that many things will not work like before.  It may very well be x86 64-bit only.  Later releases 5.01 and 5.02 should pick up most of the 4.x features that may not work in 5.00, including support for non-x86 64-bit platforms, in native code and in bytecode.  The fate of 32-bit platforms is kind of open at the moment.

**Comment by dra27** [comment]
On the other hand, we intend to provide "official" support for 4.14 until either the 5.x series has architecture-parity or the missing architectures have been officially abandoned (rather than the present state of "not yet implemented").

**Comment by dra27** [comment]
i.e. if my understanding is correct, we intend to carry on supporting bug-fixes for 4.14 even after 5.01 has been released (which is when we would normally stop applying bug fixes to 4.14)

**Comment by xavierleroy** [comment]
Right now, 32-bit platforms are supported in bytecode-only mode.  So, I'm closing this issue.
