### ISSUE TITLE
Improve warning 14: illegal backslash

### ISSUE THREAD

**Issue by lucas-deangelis** [ocaml/ocaml#10929]
I recently wrote a program that raised warning 14: illegal backslash. While the compiler suggested a fix, it lacked an explanation. Example from an utop session:

```ocaml
utop # let example = "\*";;
Line 1, characters 15-17:
Warning 14 [illegal-backslash]: illegal backslash escape in string.
val example : string = "\\*"
```

There's a [thread on the Discuss forum](https://discuss.ocaml.org/t/quick-question-about-warning-14/4303) asking about this warning, and it's at the end of the [Common Error Messages](https://ocaml.org/learn/tutorials/common_error_messages.html#Warning-Illegal-backslash-escape-in-string) tutorial on the official website.

What I would suggest is adding a small explanation with that warning, for example:

```ocaml
utop # let example = "\*";;
Line 1, characters 15-17:
Warning 14 [illegal-backslash]: illegal backslash escape in string.
You should escape your backslashes by doubling them.
val example : string = "\\*"
```

I'm not sure about the wording. "Protect" is what's used in the "Common Error Messages" page, but "escape" seems to be the correct term to use. I'm also not sure if I should first make an issue, and after a PR or directly a PR.

**Comment by dra27** [comment]
It could be possibly be one step cleverer in the hint, and suggest quoted strings, if appropriate:

```ocaml
# let _ = "\*";;
Warning 14: illegal backslash escape in string.
Quoted strings would avoid this ({|...|})
- : string = "\\*"
# let _ = "\*\n.";;
Warning 14: illegal backslash escape in string.
Literal backslash characters must be escaped ("\\")
- : string = "\\*\n."
```

**Comment by gasche** [comment]
The suggestion makes sense to me, and I would encourage you to go for a PR.

"Escape" is indeed the correct term. It may not be familiar to some users, but I think the best idea is to be more explicit:

```
You should escape your backslashes by doubling them: use \\ instead of \.
```

We could be even more explanatory:

```
Single backslashes \ are reserved for control characters (\n, \0...).
To get a backslash character, escape it with a second backslash: \\.
```

**Comment by lucas-deangelis** [comment]
Thank you. I like the detailed explanation, I think I'll go for this one in the PR, and add a line about quoted strings.

**Comment by Octachron** [comment]
One possible issue is that people might encounter the error message when they are trying to use an escape sequence which is not valid in OCaml (like  `\v`, `\f`, `\e`, `\a`, `\0`, `\XN...`, `\?`, `\uN...`, ...).

I would thus propose to the message about escape sequence as a hint to indicate that the message is only a possible fix.

Similarly, quoted strings might be not a good option if the string if the original string is `"\\\n\\\t\r\\\b\n". Thus it should be also an hint (and a separate one).

By hints, I mean using the structure
```ocaml
Hint: Single backslashes \ are ...
Hint: Quoted strings ...
```

**Comment by lucas-deangelis** [comment]
That's a good idea, thank you. Is there something like a maximum number of hints, or a maximum size of a warning? This one is getting longer than most others. Right now I have:

```ocaml
utop # let example = "\*";;
Line 1, characters 15-17:
Warning 14 [illegal-backslash]: illegal backslash escape in string.
Hint: Single backslashes \ are reserved for escape sequences (\n, \r...).
Did you check the list of OCaml escape sequences?
To get a backslash character, escape it with a second backslash: \\.
Hint: Quoted strings literals may help you avoid this: {|Hel\*o|}.
val example : string = "\\*"
```

I've merged the "escape sequence" parts into one and separated the quoted string part into another hint. The term "escape sequence" can be easily searched with "OCaml" on a search engine, which will lead users to [Lexical conventions](https://ocaml.org/manual/lex.html), where a search for "escape" leads almost directly to the table of escape sequences. I've changed "quoted strings" to "quoted strings literals" to make the search results more relevant. On both Google and DuckDuckGo, the manual is now the first result.

**Comment by Octachron** [comment]
A `limited set` might not convey the right intuition: both `\a` and `\v` are not exactly the most useful escape sequences, `\0` is merely written `\000` and the other escape sequences that I mentioned are not universal. I would propose to either drop this part or use a more direct `Did you check the list of OCaml escape sequence?`

**Comment by lucas-deangelis** [comment]
Good point, I've edited the above example to reflect that.
