### ISSUE TITLE
Approach the AST magic numbers as soon as possible

### ISSUE THREAD

**Issue by pitag-ha** [ocaml/ocaml#10936]
Hi compiler team, thanks for your great compiler work all the time!

I'd like to add `5.00.0+trunk` support to ppxlib as soon as possible and am blocked by not knowing what will happen to the AST magic numbers `ast_<impl, intf>_magic_number`. So to allow folks to try out multicore on projects with ppx rewriters, it would be great to approach that question as soon as possible (as opposed to right before releasing as usual). I see two different approaches:

1. You could decide to simply not bump them this time for 5.0 for the following reason. The AST magic numbers provide a map
     ```
     magic number -> type of AST
     ```
     So far that map is injective which is great for performance (ASTs are only migrated if the migration is not the identity). So keeping it injective seems like a good approach and, given that the AST doesn't change from 4.14 to 5.00, that means not bumping the magic numbers this time. Of course this is just ppxlib's perspective; I can't speak for others.

2. You do bump them. In that case the question is when you do so. Since the AST is not going to change from 4.14 to 5.00, it would be great if you could already bump them now so that I can adapt ppxlib to the new magic numbers.

**Comment by pitag-ha** [comment]
As a side-note: for opening the issue I had to choose between "feature-wish" and "bug" and since this isn't a bug report, I chose "feature-wish", but feel free to remove that label I've accidentally added by doing so.

**Comment by nojb** [comment]
Our current policy re magic numbers is described in https://github.com/ocaml/ocaml/blob/trunk/utils/HACKING.adoc. According to what it says, I think it should be fine to do 2. right now or soon-ish since no chages are expected in the AST.

@xavierleroy (or @damiendoligez, I don't remember) once suggested to derive the magic numbers from the version number, which means that the magic numbers would be automatically bumped as soon as the version number is changed. I don't know if there were any problems with this idea, or if it is just a case of no-one actually working on this.

cc @Octachron

**Comment by pitag-ha** [comment]
Thanks @nojb for your quick answer and for the link to the magic numbers policy (hadn't seen that yet)!

> which means that the magic numbers would be automatically bumped as soon as the version number is changed. I don't know if there were any problems with this idea

I guess it's a payoff. If you decide to bump the magic number early (e.g. when the version number is changed), the file format _can_ be detected on `trunk` at any time, but it only _is_ detected if the detection logic is kept up-to-date, including the new magic number. So some tools will always be file-format-compatible with `trunk` and others never.

If you bump the magic number late (right before the beta or rc release), then at certain moments the file format can't be detected by anyone; concretely, it can't be detected if it has changed since the last release. Still, as @Octachron has pointed out in another conversation, the upside of that option is that there's a time window during which the file format can be detected for sure and by any tool: from the last release until the moment at which the file format changes or the magic number is bumped (late).

Since for 5.0 we know that the file formats won't change, the time window during which the file formats can be detected for sure lasts until the magic numbers are bumped. Hence my one option of simply not bumpimg them this time. But also, I've noticed that this issue isn't actually necessary for ppxlib (it's more a question of convenience than necessity). So if you prefer to bump the magic numbers late as always, that's also absolutely ok for me. In any case, this has been interesting for me. So thanks already for the discussion and the link!

P.D.: I'll need to come back to this discussion when I upstream `Astlib` to the compiler: the idea of `Astlib` is to have ppxlib compatible with `trunk` _at any time_. And as pointed out above, that's only possible if the AST magic numbers are bumped early.

**Comment by pitag-ha** [comment]
I'm closing this now since the magic numbers have been bumped
