### ISSUE TITLE
Downstream patch changes for removed `Stream` and `Pervasives` library PR#10896

### ISSUE THREAD

**Issue by shakthimaan** [ocaml/ocaml#10930]
The following packages are failing to build after the "Remove Stream, Genlex, Pervasives & the legacy bigarray library" PR https://github.com/ocaml/ocaml/pull/10896.

1. `sexplib0`
```
# File "src/sexp_conv.ml", line 447, characters 32-46:
# 447 |     ; ( [%extension_constructor Stream.Failure]
#                                       ^^^^^^^^^^^^^^
# Error: Unbound module Stream
```
2. `ocamlfind.1.9.2`
```
# File "fl_metascanner.ml", line 41, characters 13-25:
# 41 |           in Stream.lsing (fun _ -> (line, pos, Eof))
#                   ^^^^^^^^^^^^
# Error: Unbound module Stream
```
3. `ocamlbuild.0.14.0`
```
# 127 |       let compare = Pervasives.compare
#                           ^^^^^^^^^^^^^^^^^^
# Error: Unbound module Pervasives
```
4. `integers.0.5.1`
```
# File "src/unsigned.ml", line 104, characters 32-50:
# 104 |   let compare (x : t) (y : t) = Pervasives.compare x y
#                                       ^^^^^^^^^^^^^^^^^^
# Error: The module Pervasives is an alias for module Pervasives, which is missing
```
5. `biniou.1.2.1`
```
# File "src/bi_stream.mli", line 20, characters 59-67:
# 20 | val read_stream : (string -> 'a array) -> in_channel -> 'a Stream.t
#                                                                 ^^^^^^^^
# Error: Unbound module Stream
```

Please advise on the recommended fixes for the same. Thank you.

Reference:
* PR#271. Parameterize ocaml-variants information in on Docker environment variables. https://github.com/ocaml-bench/sandmark/pull/271

**Comment by kit-ty-kate** [comment]
There is already a PR opened for ocamlfind: https://github.com/ocaml/ocamlfind/pull/31

**Comment by nojb** [comment]
The general fixes are to replace `Pervasives` by `Stdlib` and to remove mentions of `Stream`, but all this is better handled by the maintainers of each project so I encourage you to get in touch with them. In any case, see below:

> The following packages are failing to build after the "Remove Stream, Genlex, Pervasives & the legacy bigarray library" PR #10896.
> 
> 1. `sexplib0`
> 
> ```
> # File "src/sexp_conv.ml", line 447, characters 32-46:
> # 447 |     ; ( [%extension_constructor Stream.Failure]
> #                                       ^^^^^^^^^^^^^^
> # Error: Unbound module Stream
> ```

The mentions of `Stream` can be removed. Upstream: https://github.com/janestreet/sexplib0.

> 2. `ocamlfind.1.9.2`
> 
> ```
> # File "fl_metascanner.ml", line 41, characters 13-25:
> # 41 |           in Stream.lsing (fun _ -> (line, pos, Eof))
> #                   ^^^^^^^^^^^^
> # Error: Unbound module Stream
> ```

PR already available ocaml/ocamlfind#31

> 3. `ocamlbuild.0.14.0`
> 
> ```
> # 127 |       let compare = Pervasives.compare
> #                           ^^^^^^^^^^^^^^^^^^
> # Error: Unbound module Pervasives
> ```

You can replace `Pervasives` by `Stdlib` everywhere, but a good idea to consult upstream https://github.com/ocaml/ocamlbuild (cc @gasche are you the "maintainer" of `ocamlbuild`?)

> 4. `integers.0.5.1`
> 
> ```
> # File "src/unsigned.ml", line 104, characters 32-50:
> # 104 |   let compare (x : t) (y : t) = Pervasives.compare x y
> #                                       ^^^^^^^^^^^^^^^^^^
> # Error: The module Pervasives is an alias for module Pervasives, which is missing
> ```

You can replace `Pervasives` by `Stdlib` everywhere, but a good idea to consult upstream https://github.com/ocamllabs/ocaml-integers cc @yallop 

> 5. `biniou.1.2.1`
> 
> ```
> # File "src/bi_stream.mli", line 20, characters 59-67:
> # 20 | val read_stream : (string -> 'a array) -> in_channel -> 'a Stream.t
> #                                                                 ^^^^^^^^
> # Error: Unbound module Stream
> ```

`Stream` has been moved out of the standard library so I guess this package now requires https://github.com/ocaml/camlp-streams. The upstream is https://github.com/ocaml-community/biniou but this package seems unmaintained.

> Please advise on the recommended fixes for the same. Thank you.
> 
> Reference:
> 
> * PR#271. Parameterize ocaml-variants information in on Docker environment variables. [Parameterize ocaml-variants information as Docker environment variables ocaml-bench/sandmark#271](https://github.com/ocaml-bench/sandmark/pull/271)

**Comment by shakthimaan** [comment]
We have [Sandmark](https://github.com/ocaml-bench/sandmark) benchmarking building for 5.00.0+trunk with the required patches. I will follow-up with the respective package maintainers with the necessary changes.

The issue can be closed. Thanks!

**Comment by nojb** [comment]
Thanks!
