### ISSUE TITLE
configure: C11 atomic support required for 5.00.0

### ISSUE THREAD

**Issue by dra27** [ocaml/ocaml#10940]
The `_Atomic` keyword was added in [GCC 4.9](https://gcc.gnu.org/gcc-4.9/changes.html#c-family) which means that RHEL 7 and derivatives (CentOS, Oracle Linux, etc.) cannot build OCaml 5.00.0. RHEL 7 doesn't reach EOL until middle of 2024.

- [x] Remove cruft for pre-4.9 GCC from `configure.ac` (there's quite a lot of it)
- [x] Display a better error message for pre-4.9 GCC (CentOS 7 fails with a flood of errors at present!)
- [x] In addition to the GCC version probe, add a test for the `_Atomic` keyword (i.e. C11 atomics - there's almost certainly an off-the-shelf one)

**Comment by dra27** [comment]
A minor update, RHEL 7 cannot build 5.00.0+ _by default_. It can if one follows the instructions to install the [RedHat Software Collections](https://www.softwarecollections.org/en/scls/rhscl/devtoolset-7/) to get GCC 7.

**Comment by xavierleroy** [comment]
Grepping through the sources, most uses of `_Atomic` are hidden behind the `atomic_intnat` and `atomic_uintnat` types (sometimes at the cost of extra casts over pointer types) but there are `_Atomic` pointer types in `runtime/lf_skiplist.c` and the corresponding header, and using `atomic_uintnat` instead would significantly obscure the code.

I'm in favor of using proper C11 for the runtime system.  However, the configure test should test this, not specific GCC version numbers.  I changed the title of the issue accordingly.

**Comment by xavierleroy** [comment]
The first two items were done as part of #11037 .

**Comment by lpw25** [comment]
Probably worth pointing out that Jane Street is on such a system, so we can no longer build trunk.

**Comment by lpw25** [comment]
(More accurately, we can no longer build trunk with the gcc we use by default. We do have ways of using more modern gccs.)

**Comment by xavierleroy** [comment]
> We do have ways of using more modern gccs

Then please do.  GCC 4.9 was released in 2014, and this version or any later version should work fine.
