### ISSUE TITLE
Safety of non-atomic header loads

### ISSUE THREAD

**Issue by OlivierNicole** [ocaml/ocaml#10942]
Reading a block header is done by a non-atomic load, except for Lazy values for which the tag is loaded using `caml_obj_tag` which reads the tag using acquired loads. Tags other than `Lazy_tag` never change [<https://github.com/ocaml/ocaml/pull/1725#issuecomment-462721024>].

Is it safe to load headers non-atomically (as long as the tag is not `Lazy_tag`, or is not used) in multicore?

Live discussion with @maranget and @lthls suggests that it is probably safe, but this issue is to keep track of the debate and reach a consensus.

**Comment by gasche** [comment]
Blocks tagged `Lazy_tag` and `Forcing_tag` have mutable tags, and the GC can move around a value with tag `Forward_tag` into a value with a different tag. (If your intermediate representation sits at an abstraction level where GC-moves-around is considered as the identity, then from that perspective `Forward_tag` blocks are mutable, as @lthls explained for Flambda.)

Reading a tag non-atomically is always "safe", but the question is whether assumptions made on the *rest* of the block are correct in presence of concurrent updates. So I think what should be carefully specified is: in what state is the rest of the block after we read the tag? In other words: what are you allowed to do with the block after reading the tag? In particular, in the case of `Forward_tag` or `Lazy_tag`, you should have a barrier / perform an atomic read if you need to assume that the block argument is up-to-date.

> Live discussion with @maranget and @lthls suggests that it is probably safe, but this issue is to keep track of the debate and reach a consensus.

If you are talking of the memory model WG discussions, then my understanding was that a consensus was reached there. I'm inclined to close this issue: it may be useful to have an issue number specifically for this question, but it's not clear that it should remain *open* -- it doesn't refer to work we should do in the future and not lose track of.

**Comment by OlivierNicole** [comment]
> Reading a tag non-atomically is always "safe", but the question is whether assumptions made on the rest of the block are correct in presence of concurrent updates.

Sorry, to be more precise, the question was: is it correct to assume that the length and the tag parts of the header are immutable when the tag is not `Lazy_tag` or `Forcing_tag`, and that they can be read non-atomically with always the same result?

> If you are talking of the memory model WG discussions, then my understanding was that a consensus was reached there. I'm inclined to close this issue: it may be useful to have an issue number specifically for this question, but it's not clear that it should remain open -- it doesn't refer to work we should do in the future and not lose track of.

In that case I'm fine with closing.
