### ISSUE TITLE
[Ast_mapper]: Suggest error message improvement

### ISSUE THREAD

**Issue by shayne-fletcher** [ocaml/ocaml#10963]
It would be tremendously helpful for debugging if the error message [`Ast_mapper: OCaml version mismatch or malformed input`](https://github.com/ocaml/ocaml/blob/f22a84b4fdaafa92ed2a6a783ec8f8d249baf780/parsing/ast_mapper.ml#L1018) were improved such that it were able to report exactly which of these two reasons is the cause of an error and in the case of the former, detailed the version numbers involved.

**Comment by nojb** [comment]
xref #10938 (which is one easy way of mapping magic numbers to version numbers).
