### ISSUE TITLE
Handle orphaning of GC statistics

### ISSUE THREAD

**Issue by abbysmal** [ocaml/ocaml#10961]
I open this issue to keep track of a slight issue with the current design of GC stats in Multicore.

## Description of the issue

When attempting to move the allocation of `domain_state` from `mmap` to `malloc` (see https://github.com/ocaml/ocaml/pull/10950), I found that the way we handle the GC stats on a per domain basis, that would prevent us from freeing properly `Caml_state` at domain termination.

This is caused by the fact that, currently, `Caml_state` is only really allocated once (currently through mmap) per domain, and if the domain shuts down, it will reuse the same domain slot, and thus we can skip further allocations and setup work.

See how `create_domain` secures a slot for the first time:

```
   if (!s->interrupt_word) {
      caml_domain_state* domain_state;
      atomic_uintnat* young_limit;
      /* never been started before, so set up minor heap */
      if (!caml_mem_commit(
              (void*)d->tls_area, (d->tls_area_end - d->tls_area))) {
        /* give up now */
        d = 0;
        goto domain_init_complete;
      }
      domain_state = (caml_domain_state*)(d->tls_area);
      young_limit = &domain_state->young_limit;
      s->interrupt_word = young_limit;
      atomic_store_rel(young_limit, (uintnat)domain_state->young_start);
    }
```

Reusing a domain slot has also nice properties when it comes to GC stats: a newly spawned domain will carry over the stats from a terminated domain that ran on this slot, because those are not reset. Which means that we do get statistics that reflects the entirety of the run of the program.

There is a bit more to this, because the stats, as retrieved by the user, are gathered through an aggregate stored in [sampled_gc_stats](https://github.com/ocaml/ocaml/blob/trunk/runtime/major_gc.c#L910), which is a buffer that domains refresh to their current stats values at the end of every minor cycles and on domain termination.

[caml_sample_gc_collect]( https://github.com/ocaml/ocaml/blob/trunk/runtime/major_gc.c#L977) will set the statistics in the `sampled_gc_stats` buffer to the current value of the calling domain. (rather than adding to it.)

This means that freeing `domain_state` would result in the loss of statistics over the program's lifetime if a domain happened to be started on a previously used domain slot.

## Suggested implementation
@kayceesrk suggested we should add a global structure or buffer in which we could orphan stats at domain termination. (which sounds reasonable  since `domain_terminate` also happens to own `all_domain_lock`, so writing to this structure could be protected there.).

As a side note (and potentially something to take into account when implementing this), `caml_gc_quick_stat` does not pull the current major collection count from the aforementioned buffer, but rather, from `Caml_state` itself. (see https://github.com/ocaml/ocaml/blob/trunk/runtime/gc_ctrl.c#L61)

This is also an issue if we were to attempt to free `domain_state`, as it would reset the major_collection count on a specific domain.

Maybe `stat_major_collection` and `stat_minor_collection` could be moved elsewhere than in individual domain state fields. (as both a full major and a full minor cycle involve a stop the world sequence, meaning the numbers should arguably be the same across domains.)

**Comment by gasche** [comment]
I believe that this issue was in fact solved by #11047. We still have issues with the gc-statistics code (we're not sure what should be global and what should be per-domain, etc.), but orphaning should be handled properly.
