### ISSUE TITLE
In_channel.input_all limited to small inputs

### ISSUE THREAD

**Issue by mllken** [ocaml/ocaml#10976]
It seems In_channel.input_all cannot read more than 65536 bytes, but I would have expected to be able to read much higher amounts:

$ ocamlopt --version
4.14.0+dev4-2022-01-20
$ cat h.ml
let () =
  ignore @@ In_channel.input_all stdin
$ ocamlopt -o h h.ml
$ head -c 65537 /dev/urandom | ./h
Fatal error: exception Invalid_argument("index out of bounds")

**Comment by nojb** [comment]
Thanks for the report! There is an embarrasing bug in the implementation of `input_all`, will be fixed in #10978.
