### ISSUE TITLE
Confusing error message when using the wrong constructor argument syntax

### ISSUE THREAD

**Issue by rlepigre** [ocaml/ocaml#10990]
Consider the following scenario: a Coq user discovers a Coq bug and tries to go and fix it in the Coq source code. However, they are confused with the subtle differences in syntax between the two languages, and end up writing the following program.
```ocaml
type t =  C of int * int

let f : t option -> bool = fun t ->
  match t with
  | Some(C _ _) -> true  (* pattern should be [Some(C(_,_))] *)
  | None        -> false
```
Now, this seems like a simple syntax error. However, the compiler (or interpreter) produces the following message, which is quite confusing.
```bash
$ ocaml test.ml
File "./test.ml", line 5, characters 13-14:
Error: Syntax error: ')' expected
File "./test.ml", line 5, characters 8-9:
Error: This '(' might be unmatched
```
Clearly, parentheses are matched, so the message is confusing (and even more so with a bigger, non-minimised example).

I think in that case, it would be much clearer if the compiler gave the following message:
```
File "./test.ml", line 5, characters 14-15:
Error: Syntax error: unexpected '_'
```

**Comment by gasche** [comment]
`C _` is a valid pattern, but `C _ _` is not. (Note: `C C _` is also a valid pattern as it implicitly means `C (C _)`, which I find a bit unfortunate.)

The reason for the current error message, I believe, is the following rule in the parser:

```
  | LPAREN pattern error
      { unclosed "(" $loc($1) ")" $loc($3) }
```

This rule *is* useful in other cases where the user actually forgot a closing parenthesis, for example:

```
# match (1,(2, 3)) with (x, (y, z) -> ();;
                        ^          ^^
Error: Syntax error: ')' expected
Line 1, characters 22-23:   This '(' might be unmatched
```

Sometimes it is not so useful:

```
# match (1,(2, 3)) with (x, random!garbage -> ();;
                        ^         ^
Error: Syntax error: ')' expected
Line 1, characters 22-23:   This '(' might be unmatched
```

I don't know of a simple fix for this issue, that does not risk degrading error messages in other cases. (I think in general the paren-matching errors are rather more useful than hurtful?). In addition, this error-handling style is on the way out; we have plans -- we have had plans for a few years now -- to revamp the syntax-error handling completely.

Given the difficulties and the uncertain longevity of a fix, I'm personally tempted to do nothing for now.

**Comment by gasche** [comment]
My assessment of the issue still stands: this is a real issue but there is no easy fix, and the best course of action is probably to wait for a reimplementation of our syntax-error-message strategy. Given that there has not been other feedback for a year, I move to close the issue as "won't fix for now".

**Comment by rlepigre** [comment]
Yeah, I agree fixing this would require quite a bit of work.

It is indeed a bit unfortunate that things like `C C _` is valid syntax. I mean, it's cute when you implement Peano natural numbers, but otherwise it quickly messes up code clarity (at least from my point of view). And that's definitely not the only such example in OCaml. To solve that kind of issue without hurting backward-compatibility, I would personally advocate for a command-line option to enable a stricter syntax that would, among other things, enforce parentheses around variant arguments (and yes, I would even enforce writing `Some(x)` when `x` is an atom). That might be a good way to softly and gradually improve on the quirks of OCaml's syntax. Or in other words, we could think of versioning the syntax. Has this been considered before?

**Comment by nojb** [comment]
> Has this been considered before?

This was discussed in the context of simplifying the maintenance of the PPX ecosystem. Indeed the `ppxlib` project and, before it, `ocaml-migrate-parsetree`, implement syntax versioning for OCaml, and it was discussed whether this should be done inside the compiler. However, nothing much came of that discussion, and my recollection is that there were some arguments against (but I don't remember what they were).

**Comment by let-def** [comment]
I played a bit with the error to understand it better, here are some variations:

It is not just about `_`, variables (or any construction that could start a pattern) can trigger it:
```ocaml
| C a a
| C _ a
| C (foo) (foo)
```
For all these errors, the message should suggest `C (_, _)`.

It can be nested:
```ocaml
| Foo Bar Baz _ _ -> (*error on second _*)
| Foo Bar Baz (_, _) -> (* parse as Foo (Bar (Baz (_, _))) *)`
```
Here I would suggest `(Baz (_, _))` as the solution, even though the outermost parentheses are not necessary.

**Comment by let-def** [comment]
And here is an update of lrgrep with a tentative* rule to handle this case:

```
1 | function C a a -> ()
                 ^
Error: Issue #10990: arguments of n-ary constructors should be put between parentheses, e.g. C (..., a)
```

```
1 | function C _ a -> ()
                 ^
Error: Issue #10990: arguments of n-ary constructors should be put between parentheses, e.g. C (..., a)
```

```
1 | function C (foo) (foo) -> ()
                     ^
Error: Issue #10990: arguments of n-ary constructors should be put between parentheses, e.g. C (..., ...)
```

```
1 | function Foo Bar Baz _ _ -> ()
                           ^
Error: Issue #10990: arguments of n-ary constructors should be put between parentheses, e.g. Foo (Bar (..., _))
```
Note: for this last rule, it chose to parse it as `Foo (Bar (Baz _, _))`, `Foo (Bar (Baz (_, _)))` was another possible solution. The default matcher is too greedy and this is not customizable yet.

*: It revealed a few bugs and limitations of the current engine, easy to workaround, but a reminder there is still a lot of work :P
