### ISSUE TITLE
Documentation: Unix.create_process description should avoid the word "fork"

### ISSUE THREAD

**Issue by jfehrle** [ocaml/ocaml#11009]
The description says "`create_process prog args stdin stdout stderr` forks a new process that executes the program in file `prog`, with arguments `args`."  I suggest using "creates" instead of "forks": "fork" is a specific Linux system call with rather different semantics.  Easy to misread.  Also, AFAIK there is no fork call on Windows.

**Comment by nojb** [comment]
Sounds reasonable.

**Comment by nangahamandine** [comment]
Hello, I am Amandine, an Outreachy applicant and I am interested in contributing to Ocaml. 
Please I will like to work on this. Can you assign to me?

**Comment by nojb** [comment]
> Hello, I am Amandine, an Outreachy applicant and I am interested in contributing to Ocaml. Please I will like to work on this. Can you assign to me?

No need to be assigned. Feel free to make the fix and open a PR with it. You can find general information about contributing in https://github.com/ocaml/ocaml/blob/trunk/CONTRIBUTING.md (NB: most of it is not relevant for a small documentation fix). Thanks!

**Comment by shindere** [comment]
Welcome on board, @amaluxx!

I did assign you, many thanks to @nojb for having given the relevant
details!
