### ISSUE TITLE
Stdlib interface files improvement proposal: the type of an accumulator should always be 'acc

### ISSUE THREAD

**Issue by UnixJunkie** [ocaml/ocaml#11026]
Hello,

I think this would make type signatures in the stdlib way more readable.
Especially since some people have fun at making the accumulator sometimes
as the first parameter, sometimes as the second one, for dubious reasons
(being consistent would be a way better reason for choosing the position of the accumulator
in the parameters list).

Lowering the cognitive burden for users is a laudable thing.

Regards,
F.

**Comment by Octachron** [comment]
I tend to agree that using meaningful type variable names in interfaces improve the documentation.

**Comment by mimi-tech** [comment]
Hi, @Octachron  I am an outreachy applicant. Please can I work on this issue? I have Ocaml running successfully on my local machine. Please also direct me more on which file(s) I am to work on. Thank you.

**Comment by Octachron** [comment]
As a first good step, you can try to rename the accumulator type for the `fold` functions in the `Seq` module to `'acc`.

**Comment by mimi-tech** [comment]
@Octachron Thanks for replying  I found the change to be here 
```javascript
let rec fold_left f acc seq =
  match seq () with
    | Nil -> acc
    | Cons (x, next) ->
        let acc = f acc x in
        fold_left f acc next
```
This is what I did to fix the issue
```javascript
let rec fold_left f 'acc seq =
  match seq () with
    | Nil -> 'acc
    | Cons (x, next) ->
        let acc = f 'acc x in
        fold_left f 'acc next
```
Does it look good? Thank you.

**Comment by Octachron** [comment]
You need to update the documentation (in the mli file) and not the code. An issue ticket is also not an ideal communication medium. If you have further questions, may I suggest that you ask them on either discord, irc, or discuss.ocaml.org ?

**Comment by mimi-tech** [comment]
@Octachron Alright, thanks.

**Comment by UnixJunkie** [comment]
I'll send an exemple PR for the List module interface file.

**Comment by Octachron** [comment]
@UnixJunkie Thank you very much for taking the time to mentor students.

However, the `ocaml/ocaml` repository is not a good teaching platform. In particular, this decreases the signal/noise ratio for all contributors, and there are already many people which finds the repository too noisy to follow.
 
May I suggest that you either move the discussion to `discuss.ocaml.org` or use your own ocaml fork next time?

**Comment by UnixJunkie** [comment]
I have not written that I am accepting to mentor any student (if outside of the lab where I work).
I am not affiliated with the outreachy program.

**Comment by Octachron** [comment]
Yes, I know I meant that in an informal way. Sorry for the confusion.
