### ISSUE TITLE
Why is it `'a Effect.eff` and not `'a Effect.t` ?

### ISSUE THREAD

**Issue by dbuenzli** [ocaml/ocaml#11030]
I notice the `Effect` module seems to diverge from the usual Stdlib convention  for types, is there any reason ?

**Comment by avsm** [comment]
Mostly because a number of the examples `open Effect / open Effect.Deep` at the top, and then it's clearer to have `type 'a eff += ...` for the effect definition.

**Comment by nojb** [comment]
> Mostly because a number of the examples `open Effect / open Effect.Deep` at the top, and then it's clearer to have `type 'a eff += ...` for the effect definition.

An alternative is to define a built-in type `'a eff = ..` and a re-export `type 'a t = 'a eff = ..` inside `Effect` (like we do with other built-in types). That way examples can continue to use `type 'a eff += ...` but the "t" convention is upheld.

**Comment by dbuenzli** [comment]
But why open `Effect` or `Effect.Deep` at all ? They don't seem to define DSLs to make them worth opening.

**Comment by kayceesrk** [comment]
The reason for eff instead of t is historical. Effect handler primitives were declared in the pervasives module originally in Multicore OCaml. Having eff as the type made sense then. Now they reside in their own module. And I don't see a strong reason why the type shouldn't be named t.

**Comment by dbuenzli** [comment]
I bet another reason might be that the module used to be called `EffectHandlers` :–)

Also in passing since I just managed to  `odig` a 5.00 switch thanks to @kit-ty-kate's `odoc`'s patches, there's no module synopsis for the `Effect` module (and on the `Domain` one).

**Comment by gasche** [comment]
So do we want to switch to `t` now?

(There is a tension between staying compatible with experimental 4.12+multicore+effects, and cleaning up before these notions get much wider use. I would be in favor of cleaning up.)

@dbuenzli PRs to carve a synopsis for these modules would be warmly welcome.

**Comment by nojb** [comment]
> So do we want to switch to `t` now?

I'm in favor.

**Comment by dbuenzli** [comment]
> So do we want to switch to `t` now?

If you want to do so I suggest also looking at `Domain.DLS` which also follows quite non-standard conventions as far as the `Stdlib` is concerned (no `M.t` and `new_key` instead of `make`).

I also find `Domain.DLS` to be quite jargonic and cryptic. What about `Domain.Local_storage` or `Domain.Key` if you want to retain the pthread terminology.

**Comment by kit-ty-kate** [comment]
> (There is a tension between staying compatible with experimental 4.12+multicore+effects, and cleaning up before these notions get much wider use. I would be in favor of cleaning up.)

trunk has already drifted away from `4.12+domains` quite significantly with #10879 so one more change wouldn’t be too bad.

I’m also in favour of changing to `Effect.t` for what it’s worth, to me encouraging uses of `open` is a dangerous design choice.
