### ISSUE TITLE
Segfault from multiply-registered roots

### ISSUE THREAD

**Issue by stedolan** [ocaml/ocaml#11045]
The following innocuous-enough code segfaults in no-naked-pointers mode in (I think) every version of OCaml 4:

`bad.ml`:
```ocaml
external double_register : (string -> string -> 'r) -> 'r =
  "double_register"

let f () =
  print_endline (double_register (fun _ _ ->
    Gc.compact ();
    "hello"))

let () = f ()
```
`bad_stubs.c`:
```c
#include <caml/memory.h>
#include <caml/alloc.h>
#include <caml/callback.h>

value double_register(value closure)
{
  CAMLparam1(closure);
  CAMLlocal3(arg0, arg1, ret);
  CAMLlocalN(args, 2);

  arg0 = caml_copy_string("hello");
  arg1 = caml_copy_string("world");

  args[0] = arg0;
  args[1] = arg1;
  ret = caml_callbackN(closure, 2, args);

  CAMLreturn(ret);
}
```
```
$ ocamlopt bad_stubs.c bad.ml -o bad && ./bad
Segmentation fault
```

When the page table is enabled (i.e. not in no-naked-pointers mode), the segfault becomes nondeterministic and much harder to trigger, but does not entirely go away.

## Explanation

The issue is that `caml_callbackN` registers its `args` array as a root, even though it is already registered in the example above. Most of the time, doubly-registered roots cause no problems, as most root-scanning operations are idempotent.

However, the pointer-reversal done by compaction is not idempotent. After the root is visited the first time (traversing `caml_callbackN`), the pointer is replaced with its header. The second visit to the same root (traversing `double_register`) sees a header instead of a pointer. If the page table is absent, it tries to dereference the header and crashes.

If the page table is present, then it is often harmless, as the header does not point to a heap word and is skipped. However, this is not reliable: the bit patterns used by headers are not disjoint from those used by pointers (depending on the length of the value and which addresses the OS hands out), so with the page table check it is still possible to corrupt memory and/or crash.

## Fix

I'm not sure what the right fix is, because I can't tell whether the above code is expected to work or considered a user error.

  - If roots may be registered twice, we should ensure this doesn't break compaction (easily done in OCaml 5, which currently lacks compaction), and add some tests that register roots twice to ensure we don't break it again in future.

  - If roots may not be registered twice, we should document this in the manual (especially around `caml_callbackN`), and make some changes to turn the sporadic random segfaults that you currently get into more reliable or at least more frequent failures.

**Comment by gasche** [comment]
I always assumed that it's fine to chain two functions that registers their `value` argument as roots -- a function can re-register arguments that were already registered by its callers. Are you saying that this assumption is wrong, or is there something specific about the behavior of `caml_callback*` that I'm missing?

**Comment by jhjourdan** [comment]
@gasche , the situation you are referring to is when you register two different local variables containing the same value.

Here, args is the same array, shared by `caml_callbackN` and the calling function, and registered by these two functions. So, in fact, we are registering twice the same local variable.

**Comment by jhjourdan** [comment]
The simplest solution that I can see is to copy the args array in `caml_callbackN`. That should not be very costly: we are passing these arguments one by one, after all...

**Comment by gasche** [comment]
Ah, this is a sort of by-value / by-reference different I was missing. Thanks!

**Comment by xavierleroy** [comment]
Well spotted !  It's important that the same value can be registered multiple times, but sharing the same array of values between two registrations is at odds with the compactor, indeed.

Note that there is no need to declare `CAMLlocalN(args, 2);` in the example, everything would work (and avoid the problem!) if `args` was not declared as an array of roots...

**Comment by xavierleroy** [comment]
> That should not be very costly: we are passing these arguments one by one, after all...

Not true!  In bytecode we pass them all at once, and in native-code we pass them by groups of up to 3 arguments.

**Comment by stedolan** [comment]
> Note that there is no need to declare `CAMLlocalN(args, 2);` in the example, everything would work (and avoid the problem!) if `args` was not declared as an array of roots...

Indeed! When this came up in practice, the fix we went with is to replace `CAMLlocalN(args, 2)` with `value args[2]`.

What I'm still unsure about is whether this fix was:

  - _the correct fix for broken code_: roots may not be registered twice, and since `caml_callbackN` registers its roots it must be passed an array that is not otherwise registered. (In which case, we should document this invariant, as well as perhaps changing `caml_callbackN` as @jhjourdan suggests)
  - _a workaround for a runtime bug_: at present, the runtime does not correctly handle multiply-registered roots which were created by this perfectly-legitimate code. (In which case, we should fix the runtime / ensure it doesn't break again)

Opinions on which of these is the case?

**Comment by xavierleroy** [comment]
Since this problem is not present in OCaml 5, and is quite uncommon to begin with, I suggest to document it in the OCaml 4 reference manual (#11409) and not change the OCaml 4 code base.

**Comment by xavierleroy** [comment]
For reference, an old joke:

How many programmers does it take to change a lightbulb?

None, we'll just document the issue.

**Comment by xavierleroy** [comment]
"Fixed" (for some meaning of "fixed") in https://github.com/ocaml/ocaml/commit/9acf32acf8843db4083c92a0200309fa51d0e4d1
