### ISSUE TITLE
Confusing error: 'eprecated', is deprecated

### ISSUE THREAD

**Issue by talex5** [ocaml/ocaml#11069]
After updating to the latest 5.0 trunk, this code:
```ocaml
[@@@warning "-deprecated"]
```
now gives the alert:
```
1 | [@@@warning "-deprecated"]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
Alert ocaml_deprecated_cli: Setting a warning with a sequence of lowercase or uppercase letters,
like 'eprecated', is deprecated.
Use the equivalent signed form: -d-e-p-r-e-c-a-t-e-d.
Hint: Enabling or disabling a warning by its mnemonic name requires a + or - prefix.
Hint: Did you make a spelling mistake when using a mnemonic name?
```

What does "Enabling or disabling a warning by its mnemonic name requires a + or - prefix." mean? I already have a `-`.

**Comment by Octachron** [comment]
The issue is that `deprecated` is not a mnemonic name for any warnings. The alert is rightly explaining that
```ocaml
[@@@warning "-deprecated"]
```
is equivalent to
```ocaml
[@@@warning "-d-e-p-r-e-c-a-t-e-d"]
```
(and that has always been the case).
It might be time to de-emphasis the deprecated syntax for warning specifications and spend more time in the alert enumerating known mnemonic names.

**Comment by talex5** [comment]
Ah, I see: earlier versions of OCaml interpret the initial `-d` as turning off deprecation warnings, and the other letters are just turning off other warnings at random.

Yes, perhaps it should warn that `-d` itself is deprecated. Though it's funny to issue a warning about the deprecation of the system for ignoring warnings about deprecation...

**Comment by Octachron** [comment]
My current plan is that one-letter warning, and variant of the form `A+...` or `d+...`, will stay for the sake of backward compatibility, but we will slowly remove support for multi-letter specification (e.g. `Ae`) while we  improve the support for mnemonics.
