### ISSUE TITLE
The file `parsetree.mli` is mostly documented in regular comments (instead of doc-comments)

### ISSUE THREAD

**Issue by panglesd** [ocaml/ocaml#11071]
(I was not sure if this Issue should be classified as "Bug report" or "Feature request", feel free to change the tag to something more appropriate) 

In the file [parsetree.mli](https://github.com/ocaml/ocaml/blob/trunk/parsing/parsetree.mli), there are many [useful comments](https://github.com/ocaml/ocaml/blob/trunk/parsing/parsetree.mli#L122..L126) for ppx rewriter authors.
However, the comments are regular comments, so they are not rendered by any document generator. 
In the `ppxlib` docs, we currently encourage people to open the file to read the comments, which is not very user-friendly. In an effort to improve the ppxlib doc (ocaml-ppx/ppxlib#324), we would prefer to be able to link directly to a generated documentation (cc @pitag-ha).

Now that ocaml/odoc#830 has been merged, doc-comments attached to big records and variant types would render much better than what they used to, in odoc.

Is there a reason to keep the comments in `parsetree.mli` as regular comments, or would a PR updating these to doc-comments be welcomed?

**Comment by Octachron** [comment]
I would welcome (and review) an update that lifts comments into documentation comments for any of the compiler-libs module. Beware however, that most of those comments are not syntactically valid as documentation comments.

**Comment by panglesd** [comment]
Thanks @Octachron!

I opened the PR with the lifted comments : #11107.

**Comment by Octachron** [comment]
Fixed by the merge of #11107 and deployed at https://ocaml.org/api/compilerlibref/Parsetree.html .
