### ISSUE TITLE
Missed removal opportunities in the Thread module ? 

### ISSUE THREAD

**Issue by dbuenzli** [ocaml/ocaml#11075]
I don't know if that was maybe discussed elsewhere but since OCaml 5.0 took the step to remove some functionality I was wondering whether [these functions](https://github.com/ocaml/ocaml/blob/67e6406511e6895fca71041b938ade60c8c14f03/otherlibs/systhreads/thread.mli#L90-L124) in the `Thread` module which basically say to use their `Unix` counterpart could also have been part of the function removed by https://github.com/ocaml/ocaml/pull/10867

**Comment by kit-ty-kate** [comment]
Since they haven’t truely been marked for deprecation, they might apply for the same treatment as done in https://github.com/ocaml/ocaml/pull/10924 instead. Removing them right away wouldn’t feel right imo.

**Comment by nojb** [comment]
Yes, they should be marked as deprecated and removed in a future version.

**Comment by rbjorklin** [comment]
Just throwing it out there, could the `deprecated` attribute be added to the functions in question before 4.14 sees a final release?

**Comment by nojb** [comment]
> Just throwing it out there, could the `deprecated` attribute be added to the functions in question before 4.14 sees a final release?

@Octachron is the final arbiter, but my understanding is that it is too late to do so.

**Comment by Octachron** [comment]
Indeed, adding deprecated tag does create a substantial amount of friction in the opam ecosystem. I would rather not add them that late in the release cycle. Moreover, it seems to me that it is fine to add the deprecation alerts only in 5.0, and potentially remove the function once the OCaml 5 branch is stabilized.

**Comment by nojb** [comment]
See #11087
