### ISSUE TITLE
Code comprehension: why don't STW sections keep `all_domains_lock` the whole time?

### ISSUE THREAD

**Issue by gasche** [ocaml/ocaml#11073]
STW sections provide a mutual-exclusion mechanism, but the way they prevent races with new domains being created is subtle: they use a condition variable `all_domains_cond` to signal the end of their section, paired with an atomic variable `stw_leader` to test whether a STW section is currently running.

https://github.com/ocaml/ocaml/blob/be2db8e1362dfdd930544f10698859b1ad322237/runtime/domain.c#L455-L468

I tried to document (my understanding of) the current synchronization mechanism for STW sections in #11072.

**Question**: why don't STW sections keep `all_domains_lock` the whole time? (Instead of taking it once at setup, and once at the end to signal that condition variable.) Then `create_domain` could just take `all_domains_lock`, and that would guarantee that all STW sections are done running. It looks like the behavior would be the same (no less parallelism), and the code would be simpler.

cc @ctk21 @kayceesrk 

(Note: this question arose from a code-reading party I had today with @Engil, @Armael and @jhjourdan)

**Comment by xavierleroy** [comment]
One possible reason is that the last domain to exit the STW is not necessarily the first domain to enter it.  A POSIX mutex must be unlocked by the thread that locked it.

More generally, the mutex + shared state + condition variable dance can express many more protocols than just mutexes or just semaphores or just Win32 events.

**Comment by xavierleroy** [comment]
On a related note: variables protected by mutexes need not be atomic.   So I believe `stw_leader` doesn't need to be declared atomic, and could have its true pointer type instead of "atomic_uintnat".

**Comment by gasche** [comment]
There are unprotected accesses to `stw_leader`, see the "check for a leader or try to take the lock" dance at:

https://github.com/ocaml/ocaml/blob/be2db8e1362dfdd930544f10698859b1ad322237/runtime/domain.c#L1109-L1137

Maybe this could be done with just a `try_lock`? If it fails, we give up, if it succeeds we know that we must be the leader.

**Comment by gasche** [comment]
> One possible reason is that the last domain to exit the STW is not necessarily the first domain to enter it.

Right, so the leader would have to wait for all other domains to exit the STW sections before releasing the lock, which adds more latency to the leader. (We could do useful "spin callback" work at this point, but most STW sections don't provide a spin callback.)

I'll wait a bit more in case other people would be able to comment, and then propose the best explanation as a documentation PR.

**Comment by ctk21** [comment]
I believe the optimization at the top of `caml_try_run_on_all_domains_with_spin_work` in which we poll `stw_leader` was an optimization born from benchmarking parallel applications with very large numbers of cores. The benchmarks used are [here](https://github.com/ocaml-bench/sandmark/tree/main/benchmarks/multicore-numerical).

It is also possible that the benefit outweighs the complexity; sadly I don't think I can resuscitate the numbers easily.

**Comment by gasche** [comment]
I wrote out of curiosity a patch to make `stw_leader` non-atomic at
  https://github.com/gasche/ocaml/compare/non-atomic-stw-leader-base..non-atomic-stw-leader

Indeed the main change is that the current code does an atomic load before `trylock`, while the patch must use `trylock` directly. I suppose that `trylock` is a bit more expensive that a load-acquire (if only because glibc must test the mutex kind, etc.), so doing an atomic load first is an optimization in the case where many domains try to run a STW concurrently.

For now my plan is to change nothing (not submit my change as a PR), but document this suggested reason for the current code.

**Comment by ctk21** [comment]
> Question: why don't STW sections keep all_domains_lock the whole time? (Instead of taking it once at setup, and once at the end to signal that condition variable.) Then create_domain could just take all_domains_lock, and that would guarantee that all STW sections are done running. It looks like the behavior would be the same (no less parallelism), and the code would be simpler.

Flexibility of the lock/cond pair with state idiom. In particular the pthread leaving the STW section is very likely not to be the one that triggered it. 

Also, while your suggestion might simplify `create_domain`, I'm not (immediately) sure it will simplify `terminate_domain` as that thread needs to know it can get into the STW section if needed:
https://github.com/ocaml/ocaml/blob/04ddddd0e1d2bf2acb5091f434b93387243d4624/runtime/domain.c#L1404-L1439
Dropping the `all_domain_lock` in the STW initiation (`caml_try_run_on_all_domains_with_spin_work `) is making sure that the terminating domains can join that STW section.

**Comment by gasche** [comment]
Thanks! I believe that my questions have been adequately answered. I would like to close this issue, but rather to "fix" it by documenting these discussions in the code itself, possibly in #11072.

@ctk21 ah right, I missed this interaction with `domain_terminate`. I guess we could `try_lock` instead of locking there, and handle interrupts as long as we cannot get the lock, just like the STW startup code does? (`caml_try_...` does not try_lock in a loop, but its callers call it in a loop.)

Note: I'm happy to see that I'm not the only one having trouble remembering the inconsistent function names `create_domain` and `domain_terminate`. I felt a little too proud to send a PR just for that, but maybe I should.

**Comment by ctk21** [comment]
> @ctk21 ah right, I missed this interaction with domain_terminate. I guess we could try_lock instead of locking there, and handle interrupts as long as we cannot get the lock, just like the STW startup code does? (caml_try_... does not try_lock in a loop, but its callers call it in a loop.)

Possibly, I'd have to see the proposed code. The mutex/condition pair with state is an idiomatic and flexible way to do things.

**Comment by gasche** [comment]
I have documented the answer to this question in the now-merged #11072: https://github.com/ocaml/ocaml/pull/11072/files#diff-67115925103982a8ebeb085cfab5ef31a182c9a442bc51e053934364d3750dafR1258-R1270 . This can now be closed. Thanks!
