### ISSUE TITLE
program name usability issue

### ISSUE THREAD

**Issue by gasche** [ocaml/ocaml#11090]
### Issue

When working on the Multicore runtime, I observe that `top` reports OCaml programs as `Domain0`.

Repro case from a built compiler repository:

```
$ cat test.ml
let () = for i = 1 to 1 lsl 32 do () done

$ ./ocamlopt.opt -nostdlib -I stdlib test.ml -o test

# 'top' shows Domain0
$ ./test & (PID=$!; top -n 1 | grep $PID) 
1010782 gasche    20   0 1144948   2608   2196 S 100.0   0.0   0:00.17 Domain0

# 'ps' shows Domain0
$ ./test & (PID=$!; ps | grep $PID) 
1010801 pts/87   00:00:00 Domain0

# 'ps aux' shows the real thing
$ ./test & (PID=$!; ps aux | grep $PID) 
gasche   1010817  0.0  0.0 1144948 2464 pts/87   Sl   18:05   0:00 ./test
gasche   1010820  0.0  0.0 221528   788 pts/87   S+   18:05   0:00 grep --color=auto 1010817
```

I think this is due to 

https://github.com/ocaml/ocaml/blob/cfb362b844b1309be4cfe7b7b048e989b9ec2684/runtime/domain.c#L688

which calls `caml_thread_setname` which in turn is define as `pthread_set_name_np` or `pthread_setname_np`.

This seems to be a usability regression to me. For example, running `make -j` in the compiler directory followed by `top` will give something that looks like this:

```
 909770 gasche    20   0 9068392   2.0g 858984 S  18.9   5.1 361:26.59 GeckoMain                                                                                                                                                              
   2707 gasche    20   0 8528072   1.2g 705344 R  14.6   3.0   1461:30 gnome-shell                                                                                                                                                            
   5738 gasche    20   0 1437712 560016 392976 S  13.0   1.4  50:56.79 gnome-terminal-                                                                                                                                                        
1011715 gasche    20   0 1063488  13180   2124 R   8.6   0.0   0:00.26 Domain0                                                                                                                                                                
1011718 gasche    20   0 1062524  12136   2012 R   8.3   0.0   0:00.25 Domain0                                                                                                                                                                
1011717 gasche    20   0 1061512  11384   2096 R   6.3   0.0   0:00.19 Domain0                                                                                                                                                                
1011730 gasche    20   0 1060860  10856   2080 R   5.0   0.0   0:00.15 Domain0                                                                                                                                                                
1011732 gasche    20   0 1062160  11868   2096 R   4.0   0.0   0:00.12 Domain0                                                                                                                                                                
1011733 gasche    20   0 1061500  11520   2012 R   3.7   0.0   0:00.11 Domain0                                                                                                                                                                
1011734 gasche    20   0 1061500  11648   2140 R   3.3   0.0   0:00.10 Domain0                                                                                                                                                                
1011735 gasche    20   0 1060988  11004   2096 R   3.0   0.0   0:00.09 Domain0                                                                                                                                                                
1011740 gasche    20   0 1060184  10336   2128 R   2.7   0.0   0:00.08 Domain0                                                                                                                                                                
   2842 gasche     9 -11  357020 107628   4960 S   2.3   0.3 101:26.70 pipewire-pulse                                                                                                                                                         
1011736 gasche    20   0 1060988  10860   1960 R   2.3   0.0   0:00.07 Domain0                                                                                                                                                                
 918368 gasche    20   0 9829.8m   2.9g 729692 S   2.0   7.4 270:55.65 thunderbird                                                                                                                                                            
1011741 gasche    20   0 1060328  10420   2128 R   2.0   0.0   0:00.06 Domain0                                                                                                                                                                
1011742 gasche    20   0 1059672   9700   2056 R   2.0   0.0   0:00.06 Domain0   
```

### Situation

If I understand correctly:
- The reason to call pthread_set_name_np on each domain is to make it easier to debug a single instance of a multicore OCaml program, by making it easy to distinguish threads from one another in instrumentation output / logs.
- But currently this comes at the expense of distinguishing separate OCaml processes, which get shown in the same way by standard Unix tools.
- `pthread_set_name_np` expects a name of length at most 10. There is not a lot of room to use a name that is good for both purposes!

### Proposal

I propose to *not* call `pthread_set_name_np` on the main thread of Domain 0. In my testing, this restores the "command name" printing to its previous behavior for `top` and `ps` on my machine.

**Comment by xavierleroy** [comment]
`Domain0` but also `Domain1`, `Domain2`, etc, show up in the output of `perf` as well, but maybe this is tolerable.

> I propose to not call pthread_set_name_np on the main thread of Domain 0. In my testing, this restores the "command name" printing to its previous behavior for top and ps on my machine.

Sound reasonable.  If it's still not enough, we could use pthread_set_name_np only in the debug runtime system.

One last suggestion: `OCamlNNN` might be easier to understand than `DomainNNN` for non OCaml experts who debug mixed OCaml/C applications, for example.

**Comment by gasche** [comment]
The runtime uses the `Domain` prefix for the thread corresponding to the domain, and `Backup` for the backup thread. (But the backup thread is not expected to show up in profiles much.) I agree to change to `OCaml` and `Backup`. I'll send a PR later in the week.

**Comment by gasche** [comment]
> Sound reasonable. If it's still not enough, we could use pthread_set_name_np only in the debug runtime system.

When I said "debug" above, that includes performance monitoring/understanding, so things done using the instrumented runtime as well. The Eventring PR is now suggesting to emit most monitoring events from the non-instrumented runtime (because their cost is low enough), so I think a runtime-specific strategy would not work well.

**Comment by xavierleroy** [comment]
> The runtime uses the Domain prefix for the thread corresponding to the domain, and Backup for the backup thread. (But the backup thread is not expected to show up in profiles much.) I agree to change to OCaml and Backup

Or `OCamlDomNNN` and `OCamlBackup` (fits in 10 characters...).

> When I said "debug" above, that includes performance monitoring/understanding, so things done using the instrumented runtime as well. 

I don't know about the Eventring stuff.  But currently Domain0, Domain1, etc, show up in the output of `perf`, and I don't know if it's useful (maybe if there's a single OCaml program running) or confusing (if there are several OCaml programs being reported on).

**Comment by kayceesrk** [comment]
Agree that this is a regression and the main thread should not use `pthread_set_name_np`. 

It is useful to have the names in the default runtime. Sometimes non-determinism bugs don't show up under debug runtime. I use `gdb` on parallel programs running under the default runtime, and here telling the threads apart is handy (but not a blocker if the names were not there). 

While this may not be to everyone's liking, one possibility is to optionally enable thread names with an OCAMLRUNPARAM option. I'm assuming that those who want this feature are experts, and they can find this option if needed. If eventring requires thread names, it can turn this feature on. 

@sadiqj does eventring use the thread names?

**Comment by sadiqj** [comment]
> does eventring use the thread names?

No. It uses the domain id (and gives you the pid when it first starts).

**Comment by EduardoRFS** [comment]
There is any decided solution? Opt-in by using OCAMLRUNPARAM seems reasonable.

**Comment by gasche** [comment]
@EduardoRFS are you proposing to implement a fix for this issue? Then please pick anything you think is good, for example "only set thread names with a new OCAMLRUNPARAM setting" indeed, or the smaller change "set thread name for non-0 domains".

**Comment by sabine** [comment]
Here's a proposal: What if we change the code to look up the existing name via `pthread_get_name_np` and then truncate+append the domain id, for domain id > 0, then set that as the pthread name?

So, `hello-world` becomes `hello-world`, `hello-world-1`, `hello-world-2`, `hello-world-3`. Backup thread name becomes `hello-world-BK`, etc., same for the tick thread.

A program with just a single domain would still behave as it did before multicore, and as soon as we add more domains, their pthreads are still easily identified by the human observer and in process monitoring tools.

IMO, this would be more useful in development / debugging of applications than changing the pthread name to `OCaml` and variations thereof.

Edit: turns out we have 15 characters to use: "The thread name is a meaningful C language string, whose length is restricted to 16 characters, including the terminating null byte ('\0')." (https://man7.org/linux/man-pages/man3/pthread_setname_np.3.html) and the existing code in domain.c uses `#define MAX_DOMAIN_NAME_LENGTH 16` to restrict the length of the thread name.

**Comment by gasche** [comment]
I don't know what the "thread name" is for a program that never sets a thread name (as most sequential OCaml programs today). Is there a thread name equal to `argv[0]` (clipped to size 16?), or is there "no thread name" and a special behavior? 

Your plan sounds generally fine, but I would find it safer/easier to not set the thread name at all for the main thread of Domain 0.
(For backup/tick threads, there are one per domain, so the suffix should probably contain the domain id as well.)

Note: by "domain id" we probably mean the "unique id" here (not the "reused id"), as it is the only one accessible from OCaml, so the one users may print in their debug logs etc.

**Comment by sabine** [comment]
> Is there a thread name equal to argv[0] (clipped to size 16?), or is there "no thread name" and a special behavior?

Kind of like that, yes, but it's also possible to set a process thread name explicitly when executing a command. So, we must assume that the user may have set a name in their deployment setup that they may be relying on.

> I would find it safer/easier to not set the thread name at all for the main thread of Domain 0

Yes, the first domain must only read the existing pthread name, so we can use that name for setting other pthreads' names.

For the domain id, I was going to stick to what is currently being used in the code. That's `Caml_state->id`

**Comment by favonia** [comment]
I want to express my support of the opt-in via OCAMLRUNPARAM, including the backup threads. That is, the runtime should not set _any_ name unless explicitly told to do so. As for `top`, though, one could use the tree view to see which thread belongs to which process, in case we decide to keep the current behavior.

**Comment by sabine** [comment]
I've looked into how Go and Haskell do it:

- Go does not set any name for its process threads which is easily checked by searching the repository at https://github.com/golang/go
- GHC used to name its worker thread `"ghc_worker"`, they renamed it to `"[original_process_name]:w"` (Sep 2017, https://gitlab.haskell.org/ghc/ghc/-/commit/d07b8c7ae8bc22a7c36c96cb3fd800aecdde6eac)

**Comment by gasche** [comment]
Thanks, this is very useful. GHC made this change to help debugging (same as here I guess?), but the commit you point to appears to only set the name to `[original_name]:w` on Linux, and keep `ghc_worker` on other OSes. Do you have any guess as to why other systems would not use the suffixed-original-name approach? (Maybe it's harder to know about the size limit?)

**Comment by sabine** [comment]
http://www.open-std.org/jtc1/sc22/wg14/www/docs/n2419.htm says
> "[For Windows] The thread name is restricted to the typical unicode string as stored in the kernel (32767 characters)."

In the official Microsoft documentation I couldn't find any statement about max length of the thread name.

--

Apple seems to set a higher thread name max length than Linux- and Unix-based systems:
```
#define MAXTHREADNAMESIZE 64
```
https://opensource.apple.com/source/xnu/xnu-2050.7.9/bsd/sys/bsdtask_info.h.auto.html

--

I don't see a technical reason for GHC not implementing the suffixed-original-name approach for the other OSes. On a cursory glance, it seems like 16 (i.e. 15 actual characters) is the minimum of the maximum thread name length across different OSes.

It guess that having a worker thread named `ghc_worker` on non-Linux OSes has not been a pressing problem that the community would champion to have changed. ETA: However, on Linux, people were bothered enough by this to patch the compiler.

**Comment by sabine** [comment]
There's two different PRs I can submit here on short notice:
1. put the runtime-driven renaming behind an OCAMLRUNPARAM flag and assign names based on the original pthread name decorated with suffixes (for domain id and whether it's a special kind of thread associated with the domain), (see https://github.com/ocaml/ocaml/compare/5c269836bdd1c415fcf06d23ce704012bc50eec4...sabine:multicore_process_names?expand=1) or
2. remove runtime-driven pthread renaming altogether, as this is the minimal thing we need to do for the 5.00 release (see https://github.com/ocaml/ocaml/compare/5c269836bdd1c415fcf06d23ce704012bc50eec4...sabine:remove_pthread_renaming?expand=1)

I think, for now, 2) makes more sense.

If, in the future, the community requests a switch to have the runtime assign more descriptive pthread names for domain, backup, and tick threads, we can add 1) when the need arises.

Opinions? @xavierleroy @gasche

**Comment by gasche** [comment]
Personally I'm rather in favor of (1), because if we find out at once 5.0 is released that it's painful in practice to debug multicore programs and have to ask users at this point to (a) wait for a couple weeks and then (b) work from trunk instead, this is going to be more pain for everyone.

**Comment by kayceesrk** [comment]
I'm also in favour of (1).

**Comment by favonia** [comment]
Wow this is great. Personally I like (1), especially if it's presented as an opt-in for experimental features. This is the only way to collect feedback (and remove it if people hate it). I have two further ideas that might be useful:
1. Call `caml_thread_getname` for every new thread because, at least on Linux, one can change the process name via `prctl`; this also avoids the global array.
2. Use something like base64 encoding (`:a` instead of `:10` after `:9`) to save even more space. The downsides are (1) potentially confusing names and (2) the need of another scheme to name backup/ticking threads.

**Comment by sabine** [comment]
Good feedback!

> Call caml_thread_getname for every new thread because, at least on Linux, one can change the process name via prctl

Even using only OCaml, the program can use `Domain.set_name` can modify the process name at runtime. :thinking: (And, indeed, a program could also be calling `prctl` or even `pthread_setname_np` inside C code to change the process name of a particular domain, or the user could be using command line tools to change the process name).

There will be one quirk around nested domain-spawning when we always look up the process name when assigning the id-suffix:

Let's say the initial process name is `a`.

Situation A): The initial domain spawns another domain `a:1`. When domain `1` spawns another domain, we end up with `a:1:2` because the process name we read was `a:1`, and there was enough space to append the suffix for domain `2` without truncating. This continues with `a:1:2:3`, `a:1:2:3:4`, when the newest domain spawns another domain. If we keep creating domains which create domains, we get names like `a:1:2:3:4:5::10`. :thinking: Probably a non-issue because the majority of programs will not have a deeply nested tree of domains that spawn other domains, and this is even more information visible at a glance.

Situation B): The initial domain spawns another domain `a:1`. Domain `1` uses `Domain.set_name "b"`, and then spawns another domain `b:2`. Resulting process names: `a, b, b:2`. Seems nice, because in the global-variable-based implementation, we would see `a, b, a:2`, where it is less obvious where `a:2` was spawned.

> Use something like base64 encoding

I have doubts that the savings in characters would make up the complexity in translating between numbers and their encodings for base64.

However, one low-complexity way to compress the ids a bit, is to use hexadecimal encoding, since that is supported by `printf` and also still reasonably human-readable, so I'm adding that.

Very good point about advertising this as an experimental feature behind OCAMLRUNPARAM that could disappear or change.

**Comment by favonia** [comment]
> There will be one quirk around nested domain-spawning when we always look up the process name when assigning the id-suffix:

Ah! I was misled by the Linux documentation, which says the default pthread name is the program name. :sweat_smile: Just played with the Linux API a bit and I don't feel there's a reliable way to avoid the quirk, then. Please disregard my first idea.

**Comment by gasche** [comment]
> There's two different PRs I can submit here on short notice:
> 
>  1. put the runtime-driven renaming behind an OCAMLRUNPARAM flag and assign names based on the original pthread name decorated with suffixes (for domain id and whether it's a special kind of thread associated with the domain), (see https://github.com/ocaml/ocaml/compare/5c269836bdd1c415fcf06d23ce704012bc50eec4...sabine:multicore_process_names?expand=1) or
> 
>  2. remove runtime-driven pthread renaming altogether, as this is the minimal thing we need to do for the 5.00 release (see https://github.com/ocaml/ocaml/compare/5c269836bdd1c415fcf06d23ce704012bc50eec4...sabine:remove_pthread_renaming?expand=1)

In practice we have gone for (2) (1ce84536093a68f88a76073fd0cf3b18a86cdbf7), and the issue I originally reported is fixed. Thanks @sabine! Closing.
