### ISSUE TITLE
A recursive type constraint fails on 4.14

### ISSUE THREAD

**Issue by Octachron** [ocaml/ocaml#11101]
The following definition  fails with  OCaml > `4.14.0~` 
```ocaml
type ('node,'self) extension = < node: 'node; self: 'self > as 'self
type 'ext node = < > constraint 'ext = ('ext node, 'self) extension
```

```
1 |   type 'ext node = < > constraint 'ext = ('ext node, 'self) extension
           ^^^^
Error: Constraints are not satisfied in this type.
       Type ('a node, < node : 'a node; self : 'b > as 'b) extension as 'a
       should be an instance of
         ('c, < node : 'c; self : 'd > as 'd) extension
```
Similarly, using classes it is possible to trigger an internal compiler error with 4.14:

```ocaml
class type ['node] extension =
  object ('self)
    method clone : 'self
    method node : 'node
  end

type 'ext node = < >
  constraint 'ext = 'ext node #extension

module Raise: sig val default_extension: 'a node extension as 'a end = struct
  let default_extension = assert false
end
```
> Fatal error: exception Ctype.Escape(_)

Both examples works with previous versions (from OCaml 4.02.3 to OCaml 4.13.1).

As far as I can see, the regression appeared with #10337, and I am still investigating the root issue.

The issue was discovered by @kit-ty-kate in the [wild](http://check.ocamllabs.io/log/1646478756-0320214bdd317139efb4cd36210bf08e3ae551dd/4.14/bad/pxp.1.2.9).
I am thus hoping to fix the issue before the release of 4.14.0.

**Comment by garrigue** [comment]
I will also try to look into this ASAP.

**Comment by garrigue** [comment]
Not yet found the source of the problem, but at least I found what happens:
`Typedecl.check_constraints_rec` calls `Ctype.matches`, which in turn calls unification.
During unification, `Ctype.occur_rec` is called before unifying a variable (`{id=1640}` for me on db17a8e) with
`('a, < node : 'a; self : 'b > as 'b) extension node as 'a` (`{id=1507}` for me).
However, during this check some expansion occurs, and as a result this variable gets unified to `'a`. The change triggers a second occur check (of `'a` in `'a`), which of course fails.
What seems basically wrong here is that the constraints on the variable should have been enforced earlier, eliminating the need for unification in the first place.

**Comment by garrigue** [comment]
I found a fix, but it requires changing the semantics of `occur`, which is a bit strange for a regression.
Also, it is not clear how robust it is in general, as it only checks for physical equality.
