### ISSUE TITLE
LTO: Ocaml 4.13.1 fails to compile Findlib (ocamlfind) if compiled with `-flto`

### ISSUE THREAD

**Issue by saloniamatteo** [ocaml/ocaml#11119]
(Continued from [Gentoo bug #835157](https://bugs.gentoo.org/835157))

Hello everyone,
I just discovered a bug. If `ocaml` is compiled with the flag `-flto`, it will compile most programs just fine,
but it will error out when compiling `dev-ml/findlib` (`ocamlfind`).

When compiling `findlib`, after a certain point `ld` will start spitting out errors saying
`undefined reference to xxxxx.o`, and will fail to compile `findlib`.

I was told to report this bug upstream (here);
on Gentoo the current solution (as of 16 March 2022) is to filter out the `-flto` flag when compiling Ocaml.
It seems like issue #9825 is not sufficient to fix this problem.

Greetings,
Matteo

**Comment by saloniamatteo** [comment]
More details:

when Ocaml is compiled with CFLAGS `-O2 -flto=4` (or any lto level), as I said, it will have no problems in compiling most Ocaml packages, yet it will error out when compiling findlib. Removing `-flto` fixes this problem, for now.

Complete build log: https://835157.bugs.gentoo.org/attachment.cgi?id=767073

What's interesting is, when I removed the `ocamlopt` USE flag before compiling `findlib`, it built without any problems, even with `-flto`. What I figure is the `ocamlopt` decides whether to run `ocamlopt` when building `findlib` (and other Ocaml programs), so perhaps the issue lies within `ocamlopt`. (I'm not sure though, I'm not an Ocaml dev)

Edit:
https://gitweb.gentoo.org/repo/gentoo.git/tree/dev-ml/findlib/findlib-1.9.3.ebuild
Function `src_compile`, ebuild checks if `ocamlopt` USE flag is enabled, thus compiles with `ocamlopt` (`emake -j1 opt`, which is a function contained in EAPI 7; https://devmanual.gentoo.org/ebuild-writing/functions/src_compile/building/index.html)

**Comment by Octachron** [comment]
> it will have no problems in compiling most Ocaml packages

Which packages compile fine? It is seem suspicious that only `findlib` is affected by what looks like linker errors
```
/usr/lib/gcc/x86_64-pc-linux-gnu/11.2.1/../../../../x86_64-pc-linux-gnu/bin/ld: /var/tmp/portage/dev-ml/findlib-1.9.3/temp/cc9eyOkJ.ltrans0.ltrans.o:(.debug_info+0x37): undefined reference to `signals.c.97586eba'
```

Another data point is that  `Fedora` compiles the findlib library with LTO optimisation enabled on 4.13.1 without troubles.
That might point towards a configuration issue or some missing compilation artifacts?

**Comment by xavierleroy** [comment]
It may be that Findlib is the first OCaml package that uses the Unix library (first in compilation order)...

Did you run the test suite that is part of the source tarball for the core OCaml system?

**Comment by saloniamatteo** [comment]
@xavierleroy,
> Did you run the test suite that is part of the source tarball for the core OCaml system?

Yes, when compiling Ocaml with Gentoo the tests are run automatically:

```bash
src_test() {
	emake -j

	# OCaml tests only work when run sequentially
	if use ocamlopt ; then
		emake -j1 ocamltest.opt
	else
		emake -j1 ocamltest
		#ewarn "${PN} was built without 'ocamlopt' USE flag; skipping tests."
	fi

	emake -j1 tests
}
```

**Comment by saloniamatteo** [comment]
@Octachron,
> Which packages compile fine? It is seem suspicious that only `findlib` is affected by what looks like linker errors

For example, `dune` compiles without any problems. Another package I tried (which uses `ocamlopt`) is `ocaml-hashcons`.

> Another data point is that `Fedora` compiles the findlib library with LTO optimisation enabled on 4.13.1 without troubles. That might point towards a configuration issue or some missing compilation artifacts?

🤷🏻‍♂️ I tried compiling with both `-fuse-ld=ld.bfd` and `-fuse-ld=ld.gold` but the problem persists.
As I said, removing the `-flto` flag is the only solution available at the moment.

Also, I tried to compile with and without `ccache` to see if that would've been an issue, but that turned out to be innocent.

I don't know why only `findlib` has this problem with LTO.

**Comment by thesamesam** [comment]
For the ebuild to run tests, you have to do FEATURES=test emerge ..., FWIW.

**Comment by saloniamatteo** [comment]
@thesamesam you're right -- here's the [**build log**](https://github.com/ocaml/ocaml/files/8273928/ocaml.gz) of `ocaml` with FEATURES=test enabled. Obviously, this was built with `-flto`. Without `-flto` all tests are successful.

What is interesting can be seen at the end of the file: 

```
[...]

List of failed tests:
    tests/lib-fun/'test.ml' with 2 (bytecode) 
    tests/lib-scanf/'tscanf.ml' with 1 (native) 
    tests/basic/'equality.ml' with 1 (native) 
    tests/fma/'fma.ml' with 2 (bytecode) 
    tests/fma/'fma.ml' with 1 (native) 
    tests/lib-float/'test.ml' with 2 (bytecode) 
    tests/lib-floatarray/'floatarray.ml' with 2 (bytecode) 
    tests/output-complete-obj/'test.ml' with 2.1.1 (script) 
    tests/lib-floatarray/'floatarray.ml' with 1 (native) 
    tests/output-complete-obj/'test.ml' with 1.1.1 (script) 
    tests/basic/'equality.ml' with 2 (bytecode) 
    tests/lib-float/'test.ml' with 1 (native) 
    tests/lib-scanf/'tscanf.ml' with 2 (bytecode) 

Summary:
  2881 tests passed
   32 tests skipped
   13 tests failed
  109 tests not started (parent test skipped or failed)
    0 unexpected errors
  3035 tests considered
#### Something failed. Exiting with error status.
```

For example, if we take `fma.ml`:

```
 ... testing 'fma.ml' with 1 (native) => failed (program output /var/tmp/portage/dev-lang/ocaml-4.13.1/work/ocaml-4.13.1/testsuite/_ocamltest/tests/fma/fma/ocamlopt.byte/fma.opt.output differs from reference /var/tmp/portage/dev-lang/ocaml-4.13.1/work/ocaml-4.13.1/testsuite/tests/fma/fma.reference: 

--- /var/tmp/portage/dev-lang/ocaml-4.13.1/work/ocaml-4.13.1/testsuite/tests/fma/fma.reference	2021-09-30 15:51:42.000000000 +0200
+++ /var/tmp/portage/dev-lang/ocaml-4.13.1/work/ocaml-4.13.1/testsuite/_ocamltest/tests/fma/fma/ocamlopt.byte/fma.opt.output	2022-03-16 21:21:00.219992112 +0100
@@ -255,8 +255,8 @@
 255 OK!
 256 OK!
 257 OK!
-258 OK!
-259 OK!
+258 FAIL!	fma (0x1.deadbeef2feedp+1023, 0x0p+0, -0x1.a05f8c01a4bfbp+1) returned -0x1.a05f8c01a4bfbp+1 (normal) instead of 0x1.0989687bc9da4p-53.
+259 FAIL!	fma (0x1.deadbeef2feedp+900, 0x0p+0, -0x1.a05f8c01a4bfbp-122) returned -0x1.a05f8c01a4bfbp-122 (normal) instead of 0x1.0989687bc9da4p-176.
 260 OK!
 261 OK!
 262 OK!
@@ -273,12 +273,12 @@
 273 OK!
 274 OK!
 275 OK!
-276 OK!
-277 OK!
-278 OK!
-279 OK!
-280 OK!
-281 OK!
+276 FAIL!	fma (0x1.ffffffffffffcp-1022, 0x1.0000000000001p-1, 0x0p+0) returned 0x0p+0 (zero) instead of 0x1p-1022.
+277 FAIL!	fma (-0x1.ffffffffffffcp-1022, 0x1.0000000000001p-1, -0x0p+0) returned -0x0p+0 (zero) instead of -0x1p-1022.
+278 FAIL!	fma (0x0p+0, 0x1p-1, 0x0p+0) returned 0x0p+0 (zero) instead of 0x1p-1022.
+279 FAIL!	fma (-0x0p+0, 0x1p-1, -0x0p+0) returned -0x0p+0 (zero) instead of -0x1p-1022.
+280 FAIL!	fma (0x0p+0, 0x1.1p-1, 0x0p+0) returned 0x0p+0 (zero) instead of 0x1p-1022.
+281 FAIL!	fma (-0x0p+0, 0x1.1p-1, -0x0p+0) returned -0x0p+0 (zero) instead of -0x1p-1022.
 282 OK!
 283 OK!
 284 OK!

)
 ... testing 'fma.ml' with 2 (bytecode) => failed (program output /var/tmp/portage/dev-lang/ocaml-4.13.1/work/ocaml-4.13.1/testsuite/_ocamltest/tests/fma/fma/ocamlc.byte/fma.byte.output differs from reference /var/tmp/portage/dev-lang/ocaml-4.13.1/work/ocaml-4.13.1/testsuite/tests/fma/fma.reference: 
--- /var/tmp/portage/dev-lang/ocaml-4.13.1/work/ocaml-4.13.1/testsuite/tests/fma/fma.reference	2021-09-30 15:51:42.000000000 +0200
+++ /var/tmp/portage/dev-lang/ocaml-4.13.1/work/ocaml-4.13.1/testsuite/_ocamltest/tests/fma/fma/ocamlc.byte/fma.byte.output	2022-03-16 21:21:00.419992110 +0100
@@ -255,8 +255,8 @@
 255 OK!
 256 OK!
 257 OK!
-258 OK!
-259 OK!
+258 FAIL!	fma (0x1.deadbeef2feedp+1023, 0x0p+0, -0x1.a05f8c01a4bfbp+1) returned -0x1.a05f8c01a4bfbp+1 (normal) instead of 0x1.0989687bc9da4p-53.
+259 FAIL!	fma (0x1.deadbeef2feedp+900, 0x0p+0, -0x1.a05f8c01a4bfbp-122) returned -0x1.a05f8c01a4bfbp-122 (normal) instead of 0x1.0989687bc9da4p-176.
 260 OK!
 261 OK!
 262 OK!
@@ -273,12 +273,12 @@
 273 OK!
 274 OK!
 275 OK!
-276 OK!
-277 OK!
-278 OK!
-279 OK!
-280 OK!
-281 OK!
+276 FAIL!	fma (0x1.ffffffffffffcp-1022, 0x1.0000000000001p-1, 0x0p+0) returned 0x0p+0 (zero) instead of 0x1p-1022.
+277 FAIL!	fma (-0x1.ffffffffffffcp-1022, 0x1.0000000000001p-1, -0x0p+0) returned -0x0p+0 (zero) instead of -0x1p-1022.
+278 FAIL!	fma (0x0p+0, 0x1p-1, 0x0p+0) returned 0x0p+0 (zero) instead of 0x1p-1022.
+279 FAIL!	fma (-0x0p+0, 0x1p-1, -0x0p+0) returned -0x0p+0 (zero) instead of -0x1p-1022.
+280 FAIL!	fma (0x0p+0, 0x1.1p-1, 0x0p+0) returned 0x0p+0 (zero) instead of 0x1p-1022.
+281 FAIL!	fma (-0x0p+0, 0x1.1p-1, -0x0p+0) returned -0x0p+0 (zero) instead of -0x1p-1022.
 282 OK!
 283 OK!
 284 OK!

[...]
```

**Comment by lthls** [comment]
From the build log:
```
CFLAGS='-Ofast -pipe -march=haswell -mtune=haswell -fno-plt -falign-functions=32 -flto=4 -fgraphite-identity -floop-nest-optimize -fno-semantic-interposition -fno-common -fno-signed-zeros -fno-trapping-math -fassociative-math -freciprocal-math -fno-math-errno -ffinite-math-only -fno-rounding-math -fno-signaling-nans -fcx-limited-range -fexcess-precision=fast -
fdevirtualize-at-ltrans -fno-plt -Wl,-O1 -Wl,--as-needed -Wl,--fuse-ld=ld.gold'
```
I'm not a C specialist, but some of these flags look likely to mess with the semantics of floating point computations. That would explain the float-related errors in the testsuite.

The errors on the `output-complete-obj` test look more related to the LTO flags. I think that when in `output-obj` mode to produce a `.o` file, the OCaml compilers issue a call to the linker directly and produce an object file that is not LTO-enabled. Then the final linking phase tries to link this object with LTO-enabled objects, and this fails.

If Fedora compiles OCaml with LTO enabled, it could be useful to check how they configure the compiler; they probably have a few tweaks to pass the correct flags to the linker calls or use a specific linker.

**Comment by saloniamatteo** [comment]
Perhaps `-fno-semantic-interposition -fno-common -fno-signed-zeros -fno-trapping-math -fassociative-math -freciprocal-math -fno-math-errno -ffinite-math-only -fno-rounding-math -fno-signaling-nans -fcx-limited-range -fexcess-precision=fast -
fdevirtualize-at-ltrans -fno-plt` are flags that could cause issues. Today when I have the time I'll run an Ocaml test build again and test each flag to see which one(s) are problematic.

**Comment by saloniamatteo** [comment]
Hello again,
I ran some tests. [In this archive](https://github.com/ocaml/ocaml/files/8309550/ocaml.tar.gz) you can find 3 log files, containing three different compilations, all with tests.

In short:
- Test 1:
    - CFLAGS: `-O3 -pipe -march=haswell -mtune=haswell -fno-plt -falign-functions=32 -flto=4 -fgraphite-identity -floop-nest-optimize -fexcess-precision=fast -fdevirtualize-at-ltrans -fno-plt`
    - Test results:
    ```
    List of skipped tests:
    tests/lib-unix/isatty/'isatty_tty.ml' with 1 (libwin32unix) 
    tests/warnings/'w59.ml' with 2 (no-flambda) 
    tests/manual-intf-c
    tests/lib-unix/win-symlink
    tests/lib-bigarray-2/'bigarrfml.ml' with 1 (script) 
    tests/generalized-open/'clambda_optim.ml' with 1 (no-flambda) 
    tests/lib-unix/win-stat
    tests/unwind
    tests/asmcomp/'func_sections.ml' with 1.1 (arch_arm) 
    tests/runtime-errors/'syserror.ml' with 2.1.1.2 (libwin32unix) 
    tests/arch-power
    tests/lib-unix/unix-execvpe/'exec.ml' with 1.1 (script) 
    tests/lib-dynlink-csharp
    tests/lib-dynlink-initializers/'test10_main.ml' with 1 (no-flambda) 
    tests/afl-instrumentation/'afltest.ml' with 1.1 (script) 
    tests/asmcomp/'func_sections.ml' with 1.2 (arch_arm64) 
    tests/translprim/'module_coercion.ml' with 1.1.2 (no-flat-float-array) 
    tests/runtime-errors/'syserror.ml' with 1.1.1.2 (libwin32unix) 
    tests/basic-modules/'anonymous.ml' with 2.1.1 (no-flambda) 
    tests/letrec-check/'no_flat_float_array.ml' with 1 (no-flat-float-array) 
    tests/backtrace/'callstack.ml' with 1.1 (no-flambda) 
    tests/typing-unboxed-types/'test_no_flat.ml' with 1 (no-flat-float-array) 
    tests/translprim/'array_spec.ml' with 1.1.2 (no-flat-float-array) 
    tests/lib-unix/win-env
    tests/statmemprof/'callstacks.ml' with 2 (no-flat-float-array) 
    tests/runtime-errors/'stackoverflow.ml' with 2 (libwin32unix) 
    tests/warnings/'w55.ml' with 2 (no-flambda) 
    tests/tool-caml-tex/'redirections.ml' with 1.1.2 (no-shared-libraries) 
    tests/asmcomp/'func_sections.ml' with 1.4 (arch_i386) 
    tests/win-unicode
    tests/typing-misc/'pr6939-no-flat-float-array.ml' with 1 (no-flat-float-array) 
    tests/asmgen/'integr.cmm' with 1 (skip) 

    List of failed tests:
    tests/output-complete-obj/'test.ml' with 2.1.1 (script) 
    tests/output-complete-obj/'test.ml' with 1.1.1 (script) 

    Summary:
    2892 tests passed
    32 tests skipped
    2 tests failed
    109 tests not started (parent test skipped or failed)
    0 unexpected errors
    3035 tests considered
    ```

- Test 2:
    - CFLAGS: `-O3 -pipe -march=haswell -mtune=haswell -falign-functions=32 -flto=4 -floop-nest-optimize`
    - Test results:
    ```
    List of skipped tests:
    tests/lib-unix/isatty/'isatty_tty.ml' with 1 (libwin32unix) 
    tests/warnings/'w59.ml' with 2 (no-flambda) 
    tests/manual-intf-c
    tests/lib-unix/win-symlink
    tests/lib-bigarray-2/'bigarrfml.ml' with 1 (script) 
    tests/generalized-open/'clambda_optim.ml' with 1 (no-flambda) 
    tests/lib-unix/win-stat
    tests/unwind
    tests/asmcomp/'func_sections.ml' with 1.1 (arch_arm) 
    tests/runtime-errors/'syserror.ml' with 2.1.1.2 (libwin32unix) 
    tests/arch-power
    tests/lib-unix/unix-execvpe/'exec.ml' with 1.1 (script) 
    tests/lib-dynlink-csharp
    tests/lib-dynlink-initializers/'test10_main.ml' with 1 (no-flambda) 
    tests/afl-instrumentation/'afltest.ml' with 1.1 (script) 
    tests/asmcomp/'func_sections.ml' with 1.2 (arch_arm64) 
    tests/translprim/'module_coercion.ml' with 1.1.2 (no-flat-float-array) 
    tests/runtime-errors/'syserror.ml' with 1.1.1.2 (libwin32unix) 
    tests/basic-modules/'anonymous.ml' with 2.1.1 (no-flambda) 
    tests/letrec-check/'no_flat_float_array.ml' with 1 (no-flat-float-array) 
    tests/backtrace/'callstack.ml' with 1.1 (no-flambda) 
    tests/typing-unboxed-types/'test_no_flat.ml' with 1 (no-flat-float-array) 
    tests/translprim/'array_spec.ml' with 1.1.2 (no-flat-float-array) 
    tests/lib-unix/win-env
    tests/statmemprof/'callstacks.ml' with 2 (no-flat-float-array) 
    tests/runtime-errors/'stackoverflow.ml' with 2 (libwin32unix) 
    tests/warnings/'w55.ml' with 2 (no-flambda) 
    tests/tool-caml-tex/'redirections.ml' with 1.1.2 (no-shared-libraries) 
    tests/asmcomp/'func_sections.ml' with 1.4 (arch_i386) 
    tests/win-unicode
    tests/typing-misc/'pr6939-no-flat-float-array.ml' with 1 (no-flat-float-array) 
    tests/asmgen/'integr.cmm' with 1 (skip) 

    List of failed tests:
    tests/output-complete-obj/'test.ml' with 2.1.1 (script) 
    tests/output-complete-obj/'test.ml' with 1.1.1 (script) 

    Summary:
    2892 tests passed
    32 tests skipped
    2 tests failed
    109 tests not started (parent test skipped or failed)
    0 unexpected errors
    3035 tests considered
    ```

- Test 3:
    - CFLAGS: `-O3 -pipe -march=haswell -mtune=haswell -flto=4`
    - Test results:
    ```
    List of skipped tests:
    tests/lib-unix/isatty/'isatty_tty.ml' with 1 (libwin32unix) 
    tests/warnings/'w59.ml' with 2 (no-flambda) 
    tests/manual-intf-c
    tests/lib-unix/win-symlink
    tests/lib-bigarray-2/'bigarrfml.ml' with 1 (script) 
    tests/generalized-open/'clambda_optim.ml' with 1 (no-flambda) 
    tests/lib-unix/win-stat
    tests/unwind
    tests/asmcomp/'func_sections.ml' with 1.1 (arch_arm) 
    tests/runtime-errors/'syserror.ml' with 2.1.1.2 (libwin32unix) 
    tests/arch-power
    tests/lib-unix/unix-execvpe/'exec.ml' with 1.1 (script) 
    tests/lib-dynlink-csharp
    tests/lib-dynlink-initializers/'test10_main.ml' with 1 (no-flambda) 
    tests/afl-instrumentation/'afltest.ml' with 1.1 (script) 
    tests/asmcomp/'func_sections.ml' with 1.2 (arch_arm64) 
    tests/translprim/'module_coercion.ml' with 1.1.2 (no-flat-float-array) 
    tests/runtime-errors/'syserror.ml' with 1.1.1.2 (libwin32unix) 
    tests/basic-modules/'anonymous.ml' with 2.1.1 (no-flambda) 
    tests/letrec-check/'no_flat_float_array.ml' with 1 (no-flat-float-array) 
    tests/backtrace/'callstack.ml' with 1.1 (no-flambda) 
    tests/typing-unboxed-types/'test_no_flat.ml' with 1 (no-flat-float-array) 
    tests/translprim/'array_spec.ml' with 1.1.2 (no-flat-float-array) 
    tests/lib-unix/win-env
    tests/statmemprof/'callstacks.ml' with 2 (no-flat-float-array) 
    tests/runtime-errors/'stackoverflow.ml' with 2 (libwin32unix) 
    tests/warnings/'w55.ml' with 2 (no-flambda) 
    tests/tool-caml-tex/'redirections.ml' with 1.1.2 (no-shared-libraries) 
    tests/asmcomp/'func_sections.ml' with 1.4 (arch_i386) 
    tests/win-unicode
    tests/typing-misc/'pr6939-no-flat-float-array.ml' with 1 (no-flat-float-array) 
    tests/asmgen/'integr.cmm' with 1 (skip) 

    List of failed tests:
    tests/output-complete-obj/'test.ml' with 2.1.1 (script) 
    tests/output-complete-obj/'test.ml' with 1.1.1 (script) 

    Summary:
    2892 tests passed
    32 tests skipped
    2 tests failed
    109 tests not started (parent test skipped or failed)
    0 unexpected errors
    3035 tests considered
    ```

So, something is definitely wrong with either `-flto`, or some optimisations enabled by `-O3`, as the test results are always the same for the 3 tests. I will try to run one final test with CFLAGS: `-O2 -pipe -march=haswell -mtune=haswell -flto=4` and see if there are any issues.

**Comment by saloniamatteo** [comment]
Looks like the tests still fail with the CFLAGS mentioned above, with the exact same results as above.

**Comment by xavierleroy** [comment]
Thanks for all the testing!  My interpretation of the results:
- OCaml really wants floating-point arithmetic to be implemented exactly as in the IEEE 754 standard.  For this reason, C compiler options such as -fassociative-math -freciprocal-math  -ffinite-math-only -fno-rounding-math should not be used to compile the OCaml run-time system.  For me, these options are just a way to get wrong results faster.  Maybe that's good enough for machine learning code.  But OCaml is used for verification tools and static analysis tools that demand IEEE 754-exact FP arithmetic.
- The failure on `output-complete-obj` is probably unrelated to the failure on Findlib.  The "output complete obj" mode  is a recent addition to OCaml, and I suspect Findlib is not using it.

So, at this point, we need to go back to Findlib itself to understand the failure in conjunction with LTO on Gentoo, while it seems to be working on Fedora...

**Comment by xavierleroy** [comment]
(Updated comment to remove irrelevant reference to incbin.h.)

**Comment by saloniamatteo** [comment]
Hello,
I just visited Fedora's packages website and learned that they use the following CFLAGS: `-O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64 -march=x86-64-v2 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection`.

I reckon that the tests could be run with just the following CFLAGS: `-O2 -pipe -march=haswell -mtune=haswell -flto=4 -ffat-lto-objects`, as other CFLAGS are used for debugging and/or hardening.

I will try to do more tests, and will report back my results.

**Comment by saloniamatteo** [comment]
Seems like `-ffat-lto-objects` fixed something -- now only 1 test fails (and its child tests are skipped)

With CFLAGS `-O3 -pipe -march=haswell -mtune=haswell -flto=4 -ffat-lto-objects`, Ocaml during the test phase now only prints this:

```
List of skipped tests:
    tests/lib-unix/isatty/'isatty_tty.ml' with 1 (libwin32unix) 
    tests/warnings/'w59.ml' with 2 (no-flambda) 
    tests/manual-intf-c
    tests/lib-unix/win-symlink
    tests/lib-bigarray-2/'bigarrfml.ml' with 1 (script) 
    tests/generalized-open/'clambda_optim.ml' with 1 (no-flambda) 
    tests/lib-unix/win-stat
    tests/unwind
    tests/asmcomp/'func_sections.ml' with 1.1 (arch_arm) 
    tests/runtime-errors/'syserror.ml' with 2.1.1.2 (libwin32unix) 
    tests/arch-power
    tests/lib-unix/unix-execvpe/'exec.ml' with 1.1 (script) 
    tests/lib-dynlink-csharp
    tests/lib-dynlink-initializers/'test10_main.ml' with 1 (no-flambda) 
    tests/afl-instrumentation/'afltest.ml' with 1.1 (script) 
    tests/asmcomp/'func_sections.ml' with 1.2 (arch_arm64) 
    tests/translprim/'module_coercion.ml' with 1.1.2 (no-flat-float-array) 
    tests/runtime-errors/'syserror.ml' with 1.1.1.2 (libwin32unix) 
    tests/basic-modules/'anonymous.ml' with 2.1.1 (no-flambda) 
    tests/letrec-check/'no_flat_float_array.ml' with 1 (no-flat-float-array) 
    tests/backtrace/'callstack.ml' with 1.1 (no-flambda) 
    tests/typing-unboxed-types/'test_no_flat.ml' with 1 (no-flat-float-array) 
    tests/translprim/'array_spec.ml' with 1.1.2 (no-flat-float-array) 
    tests/lib-unix/win-env
    tests/statmemprof/'callstacks.ml' with 2 (no-flat-float-array) 
    tests/runtime-errors/'stackoverflow.ml' with 2 (libwin32unix) 
    tests/warnings/'w55.ml' with 2 (no-flambda) 
    tests/tool-caml-tex/'redirections.ml' with 1.1.2 (no-shared-libraries) 
    tests/asmcomp/'func_sections.ml' with 1.4 (arch_i386) 
    tests/win-unicode
    tests/typing-misc/'pr6939-no-flat-float-array.ml' with 1 (no-flat-float-array) 
    tests/asmgen/'integr.cmm' with 1 (skip) 

List of failed tests:
    tests/output-complete-obj/'test.ml' with 2.1.1 (script) 

Summary:
  2894 tests passed
   32 tests skipped
    1 tests failed
  108 tests not started (parent test skipped or failed)
    0 unexpected errors
  3035 tests considered
#### Something failed. Exiting with error status.
```

The same output is produced with `-O2` instead of `-O3`. I also tried CFLAGS `-O2 -pipe -march=haswell -mtune=haswell -flto=4 -ffat-lto-objects -fstack-protector-strong -fstack-clash-protection -fcf-protection -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -m64 -fasynchronous-unwind-tables` to imitate Fedora's build process, yet the output is still the same as above.

One thing to note, if you try to use CFLAGS `-O2 -pipe -march=haswell -mtune=haswell -flto=4 -ffat-lto-objects -fasynchronous-unwind-tables`, you cannot even compile Ocaml, because it fails at the configure phase, saying that the C compiler cannot compile -- perhaps it requires `-fexceptions` or those hardening options.

[Archive containing build logs](https://github.com/ocaml/ocaml/files/8334266/ocaml.tar.gz)

**Comment by saloniamatteo** [comment]
@xavierleroy any updates on this issue?

**Comment by xavierleroy** [comment]
Sorry, I don't have much time for OCaml development these days.

As I mentioned previously, the failure on `tests/output-complete-obj/test.ml` is probably unrelated and could be ignored for the moment.

So, your next step could be to try to compile findlib and other OCaml packages with your new OCaml core package (the one that uses the Fedora-inspired, reasonable CFLAGS settings).
