### ISSUE TITLE
Conflicting error message whether to be or not to be a function

### ISSUE THREAD

**Issue by sim642** [ocaml/ocaml#11129]
## Problem
While working on a ppx deriver and trying to figure out where I need to insert `Ptyp_poly`s to make the generated code typecheck, I happened on this conflicting error message:
```
Error: This expression should not be a function, the expected type is
       Ppx_deriving_ord_helper.t -> Ppx_deriving_runtime.int
```
It's saying that the (`function ...`) expression should be a function (i.e. of a function type), but at the same time not be a function!

When I printed out the generated code and tried compiling that directly, the error suddenly disappeared, confusing things even further, so I cannot even provide simple reproducible example code for it.

## Hypothesis
Since I was messing around with `Ptyp_poly`, I realized I'm inserting some with empty lists for type parameters. Avoiding those made the confusing error disappear.
I'm not familiar with the compiler code, but I have a hypothesis how this happened.

Here `Tpoly` is completely unhandled, so the `Not_a_function` error is raised:
https://github.com/ocaml/ocaml/blob/d0eba6b39a7f1b49172aa88b69c0440b99bbe6a4/typing/ctype.ml#L3225-L3237
And when printing the expected type for the error message, the `Tpoly` with empty type parameter list is quietly thrown away:
https://github.com/ocaml/ocaml/blob/d0eba6b39a7f1b49172aa88b69c0440b99bbe6a4/typing/printtyp.ml#L1153-L1154

Similarly, `Pprintast` ignores them, which is why manually compiling the generated and printed code suddenly worked:
https://github.com/ocaml/ocaml/blob/d0eba6b39a7f1b49172aa88b69c0440b99bbe6a4/parsing/pprintast.ml#L306-L307

## Solutions
I can think of the following things that could be changed:
1. Also handle `Tpoly (_, [])` in `Ctype.filter_arrow`.
2. Somehow distinguish `Tpoly (ty, [])` in error message types.

**Comment by Octachron** [comment]
Producing an invalid AST is a programming mistake on the ppx extension side.
The typechecker is already complex enough without handling such broken ASTs.

The right fix might be to make the `ast_invariant` check rejects `parsetree`s with invalid `Tpoly` nodes.

**Comment by sim642** [comment]
Are such ASTs supposed to be invalid though? Because when looking around, there's lots of other places where `Tpoly (_, [])` is being handled. And there's at least one place in the parser where `Ptyp_poly ([], _)` is introduced. So it isn't entirely apparent that these are invalid, but it's also unclear what these are supposed to mean.

**Comment by Octachron** [comment]
Yes, those parsetree ASTs are invalid.

The single use of `Ptyp_poly([], ...)`  in the parser is simulating a location stack when duplicating a type constraint. Nowadays, it should be replaced by a call to `reloc_typ`.

The typechecker introduces internally such nodes, but that is even more reason to not let ppxs introduce those nodes erroneously.

**Comment by Octachron** [comment]
See #12119 and #11148 that will raise a better error message on invalid `Ptyp_poly` nodes.
