### ISSUE TITLE
Refutation patterns do not work properly

### ISSUE THREAD

**Issue by favonia** [ocaml/ocaml#11139]
This is the minimum (counter)example I could find:
```ocaml
module X (P : sig type t end) = P
module Y = X (struct type t = | end) (* t is the empty variant type *)

let f (x : Y.t) =
  match x with _ -> . (* I thought this would work, but it doesn't. *)
```
Any small variation of the above code seems to compile. For example, if I bind `A` to the argument module, then OCaml knows that the type `Y.t` is empty, as expected.
```ocaml
module X (P : sig type t end) = P
module A = struct type t = | end
module Y = X (A)

let f (x : Y.t) =
  match x with _ -> . (* Now it works! *)
```
If this is indeed a bug, the bug is present in 4.13.1 and the current trunk.

**Comment by Octachron** [comment]
The type of `Y` in:
```ocaml
module Y = X(struct type t = | end)
```
is `sig type t end` because there is no path to the definition of type `t` from the anonymous argument.
Thus, the compiler is right to not presume that `Y.t` is empty.
Contrarily, with
```ocaml
module A = struct type t = | end
module Z = X (A)
```
the type of `Z` is `sig type t = A.t end`. It is thus correct to conclude that `Z.t` is empty.

**Comment by gasche** [comment]
Indeed, as @Octachron explained, this is not a bug. (Functors can behave in surprising ways, especially when passed arguments that are not paths/values. This is independent from refutation patterns.)

**Comment by favonia** [comment]
Thanks for the quick and detailed response!
