### ISSUE TITLE
GADTs with inline records?

### ISSUE THREAD

**Issue by hyphenrf** [ocaml/ocaml#11155]
Or more generally, alternative way to write GADTs like functions. Right now, we're able to express records in GADTs like so:
```ocaml
type show = Show : 'a t -> show
 and 'a t = { show : 'a -> string; value : 'a }
```
This is simple enough for smaller number of existentials, and although it can allow people to construct `'a t` separately, there are easy ways at both type level and module level that'd restrict it.

What I'd like to have is a way to write GADTs just like normal constructors, but with an extra type at the end:
```ocaml
type show = Show of { show : 'a -> string; value : 'a } : show
```
and I wonder if such feature was considered when inline records were introduced but there was any syntax or typing limitation that blocked it. More generally, it'd be an alternative way to write GADT types like we do with functions. i.e. this is similar to the ability to write a function like this:
`let f : 'a -> 'b -> 'b = fun _ b -> b`
and like this:
`let f (_ : 'a) (b : 'b): 'b = b`

**Comment by nojb** [comment]
> What I'd like to have is a way to write GADTs just like normal constructors, but with an extra type at the end:

You are in luck! your wish is already supported:
```ocaml
type show = Show : { show : 'a -> string; value : 'a } -> show
```

**Comment by hyphenrf** [comment]
oh huh.. that's good to know haha
somehow I expected records to not work on the right hand side of `:`, like they don't with function types. But I suppose I should've tried anyway because there are other differences in constructor and function types.
