### ISSUE TITLE
Add Domain.get_name or remove Domain.set_name altogether

### ISSUE THREAD

**Issue by favonia** [ocaml/ocaml#11154]
I wonder if we can include `get_name` in the new `Domain` module, given that `set_name` is there. The API seems to be available on all operating systems we wish to support:

* Linux: [pthread_getname_np](https://man7.org/linux/man-pages/man3/pthread_getname_np.3.html)
* macOS: [pthread_getname_np](https://opensource.apple.com/source/libpthread/libpthread-301.30.1/pthread/pthread.h.auto.html)
* Windows: [GetThreadDescription](https://docs.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-getthreaddescription)
* FreeBSD: [pthread_get_name_np](https://www.freebsd.org/cgi/man.cgi?query=pthread_get_name_np)
* OpenBSD: [pthread_get_name_np](https://man.openbsd.org/pthread_get_name_np)
* NetBSD: [pthread_getname_np](https://man.netbsd.org/pthread_getname_np.3)

EDIT: Otherwise, I think we should remove Domain.set_name after improving the runtime's default naming scheme.

**Comment by sabine** [comment]
If we do change renaming of the pthread names to be based on the original pthread name, adding this feature would be a very simple addition on top of that.

Can you elaborate on the use case?

**Comment by favonia** [comment]
> Can you elaborate on the use case?

I might plan to append strings to existing pthread names for debugging purposes (especially if/when #11090 is resolved in favor of keeping original names). There's currently no easy way for an OCaml program to obtain the names.

**Comment by favonia** [comment]
PS: this will be resolved by #11174 (if merged).

**Comment by favonia** [comment]
Closed by https://github.com/ocaml/ocaml/pull/11264.
