### ISSUE TITLE
Possible misunderstanding in docs on "Modules and separate compilation"

### ISSUE THREAD

**Issue by mobileink** [ocaml/ocaml#11152]
https://github.com/ocaml/ocaml/blob/0a9b6b885903e2dec1f248067c9ea7bddffe1c8e/manual/src/tutorials/moduleexamples.etex#L381-L385

This seems to be both incorrect and very unclear (what does "mapped to separately compiled files" mean?). Module type decls can occur at top level inside a .mli file, and .mli files can be compiled separately. Other .mli files can use such a file by passing `-open` on the cmd line or embedding `open` or `!open`.  I'm not quite decided on how best to revise the docs, but to see that it's wrong, take the sample code from [Destructive substitutions](https://ocaml.org/manual/signaturesubstitution.html#ss%3Adestructive-substitution)

```
module type Printable = sig
  type t
  val print : Format.formatter -> t -> unit
end
module type Comparable = sig
  type t
  val compare : t -> t -> int
end
module type PrintableComparable = sig
  include Printable
  include Comparable with type t := t
end
```

and break it into three `.mli` files:

.printable.mli
```
module type Printable = sig
  type t
  val print : Format.formatter -> t -> unit
end
```

.comparable.mli
```
module type Comparable = sig
  type t
  val compare : t -> t -> int
end
```

.printablecomparable.mli
```
include Printable
include Comparable with type t := t
```
Then a Makefile:

```
COMPILER=ocamlc
pco: p c
	${COMPILER} printablecomparable.mli -open Comparable -open Printable
p:
	${COMPILER} printable.mli
c:
	${COMPILER} comparable.mli
```

**Comment by dra27** [comment]
It’s certainly not incorrect. `printable.mli` describes the module `Printable` - using `-open` is just a convenience to avoid adding `open Printable` in the source files using it - the module type’s path is _still_ `Printable.Printable`. There might be mileage in cross-referencing `-open`, etc.

**Comment by dra27** [comment]
https://github.com/ocaml/RFCs/pull/11 is relevant, too

**Comment by xavierleroy** [comment]
Right, the wording in the manual may be too terse and not clear enough, and suggestions for improvement are welcome, but it is certainly not incorrect.

**Comment by mobileink** [comment]
Thank you for looking at this.  Here is the problem:  "only top-level **structures** can be mapped to 
 separately-compiled files" [emphasis added].  Since "structure" is a technical term in OCaml, that claim is demonstrably false, as the example I gave show.  Unless you give "mapped" an unusual reading.

**Comment by xavierleroy** [comment]
I can assure you that if you have a file `foo.ml`, its contents are interpreted as a **structure** whose members are the various items in the file (values, types, modules, module types, etc).  E.g. if foo.ml contains
```
 module type Printable = sig
  type t
  val print : Format.formatter -> t -> unit
end
```
you get a `Foo` structure with a member `Foo.Printable` that is a module type.

**Comment by mobileink** [comment]
On Fri, Apr 1, 2022 at 1:18 PM Xavier Leroy ***@***.***>
wrote:

> I can assure you that if you have a file foo.ml, its contents are
> interpreted as a *structure* whose members are the various items in the
> file (values, types, modules, module types, etc). E.g. if foo.ml contains
>
>  module type Printable = sig
>   type t
>   val print : Format.formatter -> t -> unit
> end
>
> you get a Foo structure with a member Foo.Printable that is a module type.
>

That's correct, but that's not the issue.  The issue is whether *only*
structures can be mapped to files.

**Comment by mobileink** [comment]
On Fri, Apr 1, 2022 at 2:56 AM David Allsopp ***@***.***>
wrote:

> It’s certainly not incorrect. printable.mli describes the module Printable
> - using -open is just a convenience to avoid adding open Printable in the
> source files using it - the module type’s path is *still*
> Printable.Printable. There might be mileage in cross-referencing -open,
> etc.
>
Thanks for taking a look.  I respectfully disagree with your
reading, though.  A signature does not describe a module, it determines a
class of modules. That's the point of splitting sigs from structs, and it's
why signatures can be compiled without structs.  A module by definition is
a pairing  of a sig and a struct - no struct, no module.  So in my view the
documentation is just wrong insofar as it conflates signatures and modules.
That's a category error, IMO.

thanks,

Gregg

**Comment by Octachron** [comment]
Only structures (and signature) can be mapped to files. Consider for instance, the following mli file:
```ocaml
(* a.mli *)
type t
module type t
module M: sig end
```
it is a signature that contains three signature items: a type, a module type and a module.
It is equivalent to your `printable.mli` example
```ocaml
module type Printable = sig
  type t
  val print : Format.formatter -> t -> unit
end
```
which is a signature that contains one item, the module type `Printable`.

The sentence in the manual that you are misreading means that it is not possible to write directly a module type or a functor directly in a file: it must be an item of a structure.

**Comment by gasche** [comment]
Generally I'm of the opinion that most remarks about such confusions hide genuine feedback, even if they hide it well by being obscured by some layer of misunderstanding or poor form. We can work it out and improve the documentation. But, as a first step, @mobileink, could you stop being arrogant about this? You are telling three maintainers of the language, including the one who basically wrote both the compiler and its documentation, that the documentation is "incorrect", "just wrong", "a category error" and "demonstrably false". It's actually possible that there is a problem with the documentation and likely that the wording can be improved, but it will be much easier to discuss if you tone it down a bit.

**Comment by gasche** [comment]
Here is my understanding of the documentation:

- "File" here dos not mean ".ml file" or ".mli file", but actually "compilation unit". Calling a compilation unit a "file" is a bit of a simplification because it corresponds to a bunch of files (a pair of a .ml and a .mli, both of them optional in some situations, in source form; a pair of a .cmo and a .cmi, in compiled bytecode form; more stuff in native-compiled form).

- The point is that a compilation unit named `Foo` passed to the compiler is always mapped, inside the language, into a *module* (a structure) named `Foo` in the typing environment. In particular, there is no way to write a compilation unit that represents a module signature rather than a module. If you want to define a module signature in its own file, it needs to be an item of a module representing the file. 

I believe that what I described above (1) is correct and (2) corresponds to what the documentation tries to say.

**Comment by Octachron** [comment]
A possible source of the confusion is that compilation units consisting of only one `.mli` file without matching `.ml` file are an implementation detail of the compiler. Even if in some circumstance it is possible to elide the `ml` file from the compilation unit, the `mli` file is still morally part of a compilation unit mapped to a structure.

**Comment by gasche** [comment]
Here would be a proposed rephrasing:

> Note that compilation units are visible inside the languages as modules, not module types or functors. If you want to define a module `struct let x = 1 end`, you can put its content, without `struct..end` directly at the top-level of a `foo.ml` file, and refer to the corresponding module as `Foo` in the rest of the program.
>
> ```ocaml
> (* content of foo.ml *)
> let x = 1
> ```
> On the other hand, if you want to define a module type `sig val x : int end` or a functor `module Make (...) = ...` in separate files `foo.{ml,mli}`, you need to declare them as items inside `foo.ml`, and the rest of the program  will then refer to them as `Foo.S` or `Foo.Make`.
>
> ```ocaml
> (* content of foo.ml *)
> module type S = sig
>   val x : int
> end
> ```

(At the end we could add a mention of `-open Foo` if we wanted to. I'll leave this to @Octachron the King of Manual References.)
