### ISSUE TITLE
Embed the unhandled effect in the exception Unhandled

### ISSUE THREAD

**Issue by favonia** [ocaml/ocaml#11185]
I wonder if it is possible to embed the unhandled effect in the exception `Unhandled`. In terms of the OCaml syntax, it's like this:
```ocaml
type exn += Unhandled : 'a Effect.t -> exn
```
This would enable a library to register a printer via `Printexc` for its effects, which seems to be useful for debugging (e.g., reminding the user to call some `run` to handle effects).

**Comment by favonia** [comment]
PS: I tried to make a PR but was not sure where to put the `Effect.t` in the initial environment. That is, `Effect.t` might have to be in the initial environment like the `exn` type, but I don't know what its name should be.

**Comment by favonia** [comment]
@kayceesrk It seems that you like this proposal---I wonder how you feel about it? I am asking now because this cannot be easily changed once OCaml 5.0 is released. I intended to make a PR but was then felt uncomfortable hacking the assembly code across all platforms (specifically, the `caml_perform` in the runtime system). Ideally, I wish this could be implemented along with #11262. One implied change is that `Effect.t` needs to be predefined, perhaps as `eff`.

**Comment by xavierleroy** [comment]
> embed the unhandled effect in the exception Unhandled. 

@ocaml/caml-devel this must be decided before 5.0 is released, it will be too late afterwards.  Please discuss ASAP.

**Comment by fpottier** [comment]
I don't know what the deep implications of this design decision might be, but from the end user's point of view, it seems desirable to let the exception `Unhandled` carry the effect that could not be handled.

An alternative might be to *not* wrap the unhandled effect in an exception at all: just treat unhandled effects in a primitive way, in the same way unhandled exceptions are treated. But that doesn't seem very appealing: it creates a new kind of unexpected situation and (I imagine?) may lead to code duplication in the runtime system and/or in user code.

**Comment by kayceesrk** [comment]
I have made a PR for this: https://github.com/ocaml/ocaml/pull/11419.
