### ISSUE TITLE
Warnings with `-output-complete-obj` + `unix.cmxa` + MSVC

### ISSUE THREAD

**Issue by nojb** [ocaml/ocaml#11205]
Using MSVC:
```
$ touch main.ml
$ ocamlopt -o main.exe.obj -output-complete-obj unix.cmxa main.ml
advapi32.lib(ADVAPI32.dll) : warning LNK4006: __NULL_IMPORT_DESCRIPTOR already defined in ws2_32.lib(WS2_32.dll); second definition ignored
advapi32.lib(ADVAPI32.dll) : warning LNK4221: This object file does not define any previously undefined public symbols, so it will not be used by any link operation that consumes this library
```
I am guessing that some library is being linked twice, but have not been able to pinpoint the exact cause. cc @dra27

**Comment by nojb** [comment]
Adding `-verbose` to the command line shows:
```
+ link -lib -nologo -machine:AMD64  -out:"main.exe.obj" "/libpath:C:\cygwin64\home\nojebar\mlfi\mlfi-ins\lib\flexdll" "/libpath:C:\cygwin64\home\nojebar\mlfi\mlfi-ins\lib" "C:\cygwin64\tmp\camlstartup25a3eb.obj" "main.obj" "C:\cygwin64\home\nojebar\mlfi\mlfi-ins\lib\unix.lib" "C:\cygwin64\home\nojebar\mlfi\mlfi-ins\lib\stdlib.lib" "C:\cygwin64\home\nojebar\mlfi\mlfi-ins\lib\libunix.lib" "ws2_32.lib" "advapi32.lib" "C:\cygwin64\home\nojebar\mlfi\mlfi-ins\lib\libasmrun.lib"
```

**Comment by shindere** [comment]
Nicolás Ojeda Bär (2022/04/17 14:42 -0700):
> Adding `-verbose` to the command line shows:
> ```
> + link -lib -nologo -machine:AMD64  -out:"main.exe.obj" "/libpath:C:\cygwin64\home\nojebar\mlfi\mlfi-ins\lib\flexdll" "/libpath:C:\cygwin64\home\nojebar\mlfi\mlfi-ins\lib" "C:\cygwin64\tmp\camlstartup25a3eb.obj" "main.obj" "C:\cygwin64\home\nojebar\mlfi\mlfi-ins\lib\unix.lib" "C:\cygwin64\home\nojebar\mlfi\mlfi-ins\lib\stdlib.lib" "C:\cygwin64\home\nojebar\mlfi\mlfi-ins\lib\libunix.lib" "ws2_32.lib" "advapi32.lib" "C:\cygwin64\home\nojebar\mlfi\mlfi-ins\lib\libasmrun.lib"
> ```

Would it help to bisect?

For instance, was the problem laready there before the merge of
win32unix into unix?
