### ISSUE TITLE
ARM64 assembler error on ocaml-variants.5.0.0+trunk

### ISSUE THREAD

**Issue by icristescu** [ocaml/ocaml#11229]
On a `ocaml-variants.5.0.0+trunk` switch on macos, when I build the tests from the [Repr library](https://github.com/mirage/repr)  I get the following error:

```
✦ ❯ dune build ./test/repr/main.exe
File "test/repr/.main.eobjs/native/_unknown_", line 1, characters 0-0:
/var/folders/mj/sbh5f0s1783ch5vgxqp4j87h0000gn/T/build_762d24_dune/camlasm5ee54b.s:34489:17: error: expected compatible register, symbol or integer in range [0, 4095]
  add x16, x16, #4480
                ^
File "test/repr/main.ml", line 1:
Error: Assembler error, input left in file /var/folders/mj/sbh5f0s1783ch5vgxqp4j87h0000gn/T/build_762d24_dune/camlasm5ee54b.s
```
The culprit is the test `test_variants`,  [commenting it out](https://github.com/icristescu/repr/commit/8017e670593035680a96f24617a1bfa62fad8d0c) makes the error disappears. The code runs without issues on my ocaml.4.13.1 switch.

**Comment by nojb** [comment]
- Which architecture?
- Does it work with 4.14?

**Comment by xavierleroy** [comment]
Looks like ARM 64 bits.

**Comment by icristescu** [comment]
The tests run without any errors on a `4.14` switch.
I'm on a macOS arm64 machine.

**Comment by nojb** [comment]
At first sight there are some logical shifts missing in line 295:

https://github.com/ocaml/ocaml/blob/219604e4c8cef984be70099d3262683cef29e24f/asmcomp/arm64/emit.mlp#L288-L298

**Comment by xavierleroy** [comment]
Nope, there's no need to shift anything here.  The assembler understands immediates of the form 000XXX000.

The problem is probably an addition that does NOT go through `emit_addimm`.

**Comment by nojb** [comment]
> Nope, there's no need to shift anything here. The assembler understands immediates of the form 000XXX000.
> 
> The problem is probably an addition that does NOT go through `emit_addimm`.

Right! What about 1088:

https://github.com/ocaml/ocaml/blob/219604e4c8cef984be70099d3262683cef29e24f/asmcomp/arm64/emit.mlp#L1085-L1091

**Comment by xavierleroy** [comment]
Looks plausible!  An `emit_addimm` would be preferable.
