### ISSUE TITLE
unused-field (69) and unused-constructor (37) can't be applied to individual fields/constructors

### ISSUE THREAD

**Issue by Khady** [ocaml/ocaml#11235]
Warnings 69 (introduced in #10232) and 37 have to be applied to whole types, they do not work on individual fields or constructors, which could sometimes be useful.

```ocaml
(* this one works as expected *)
type a = { foo: int; bar: int } [@@warning "-69"]

(* this one does nothing *)
type a' = { foo: int [@warning "-69"]; bar: int }

(* this one works as expected *)
type b =
  | A of string
  | B of int
[@@warning "-unused-constructor"]

(* this one does nothing *)
type b' = 
  | A of string [@warning "-unused-constructor"]
  | B of int
```

**Comment by Octachron** [comment]
This sounds like sensible feature with straightforward implementation.
For interested outreachy students, the warnings are matched to the constructor `Unused_constructor _` and `Unused_field _` inside the compiler. The change requires to find the location where each warning is used and ensure that attributes on the constructor or labels are taken in account in the current warning scope.

**Comment by Oluwabukolab** [comment]
I'd like to work on this issue.

**Comment by Octachron** [comment]
Don't hesitate to go ahead then.
