### ISSUE TITLE
Define an empty variant type in the standard library (e.g., empty, void, or Void.t)

### ISSUE THREAD

**Issue by favonia** [ocaml/ocaml#11265]
There have been lots of discussions about empty types. (See https://github.com/ocaml/ocaml/issues/9459, https://github.com/ocaml/ocaml/issues/9975, https://github.com/ocaml/ocaml/issues/10687 on polymorphic ones, ....) I'd like to throw in yet another proposal that seems to provide some immediate benefits without a need to hack the type-checking algorithm. That is, to define an empty variant type directly in the standard library.

## Pros

* No changes to the type system!
* The undesirable generativity can be solved in practice by using literally the same empty type.

## Cons

* Yet another name would be taken. I personally prefer `void` or `Void.t` because `empty` and `Empty` seem to be popular.
* This does not implement any advanced feature (subtyping, etc.) requested in other GitHub issues.

**Comment by gasche** [comment]
Yes, having a module `Empty` or `Void` in the standard library would be fine. (Now we use a namespacing mechanism to avoid module-name clashes with user programs.)

But: what are the generativity-related problems that we want to solve here? There were a few questions about empty polymorphic variants (which are fairly different); for empty types, are there practical use-cases for a shared definition?

Regarding the naming, personally I prefer `Empty.t` to `Void.t` -- `void` means `unit` in C-family languages, so it can be fairly confusing. Surely many people already use `empty` as an identifier or as a type, but having `Empty.t` or `Stdlib.Empty.t` available in addition should not be an issue, am I missing something?

**Comment by favonia** [comment]
> But: what are the generativity-related problems that we want to solve here? There were a few questions about empty polymorphic variants (which are fairly different); for empty types, are there practical use-cases for a shared definition?

1. I am developing OCaml libraries which could potentially provide specialized interfaces for empty types (something like `empty ast` but a bit different). However, these libraries have to stick to the same empty type defined in some common library, for otherwise the specialized interface in one library cannot work with that in another library. It is also strange to create an OCaml library just to define a common empty type that can be shared across libraries. If we have to do it, the standard library seems to be the right place to define such a type.
2. Within an anonymous module, using a predefined empty type (that is, writing `type t = Stdlib.empty` instead of `type t = |`) makes it easy to retain full information because `Stdlib.empty` is named and the emptiness can be described using simple type equations. (This is only loosely related to the generativity issue but I still want to mention it.)

> Regarding the naming, personally I prefer `Empty.t` to `Void.t` -- `void` means `unit` in C-family languages, so it can be fairly confusing. Surely many people already use `empty` as an identifier or as a type, but having `Empty.t` or `Stdlib.Empty.t` available in addition should not be an issue, am I missing something?

Fair enough. I don't have a strong opinion in either direction.

**Comment by gasche** [comment]
> I am developing OCaml libraries which could potentially provide specialized interfaces for empty types (something like empty ast but a bit different). However, these libraries have to stick to the same empty type defined in some common library, for otherwise the specialized interface in one library cannot work with that in another library.

Do you have a real-world example where this is happening? Is it the case in code that you are writing right now, for example? With the "typical" examples that I can construct in my head, I consume instances of the form `empty t` by pattern-matching, and the positions where `empty` occur become unreachable clauses `| Foo _ -> .`. This works no matter how `empty` is defined, and it does not require the empty types of several libraries to unify together.

In theory I agree that there could be an issue, but I can't tell how practical this is. Before we encounter a real-world example it is a bit harder to motivate ourselves to pour work into it. (But: in this case the work to do is rather clear, has no clear downside, etc., so maybe we could do it anyway. The main unpleasant work we would be saving by suspending this issue is a bike-shedding on the naming of the module.)

**Comment by favonia** [comment]
> Is it the case in code that you are writing right now, for example? With the "typical" examples that I can construct in my head, I consume instances of the form `empty t` by pattern-matching, and the positions where `empty` occur become unreachable clauses `| Foo _ -> .`.

Yes it came from the libraries I am working on.

One example starts with ['hook Yuujinchou.Language.t](https://redprl.org/yuujinchou/yuujinchou/Yuujinchou/Language/index.html#type-t), which is an abstract type that defies pattern matching. It is important to leave `'hook` polymorphic, but it also makes sense to provide a simplified version with `'hook = empty`. Next, the module [Yuujinchou.Modifier](https://redprl.org/yuujinchou/yuujinchou/Yuujinchou/Modifier/index.html) provides a polymorphic interface to apply these modifier of types Yuujinchou.Language.t, and it also makes sense there to offer simplified interfaces with `context = empty` and/or `hook = empty` (all combinations might make sense). Moving on, the module [Yuujinchou.Scope](https://redprl.org/yuujinchou/yuujinchou/Yuujinchou/Scope/index.html) is built upon Yuujinchou.Modifier and it can then again be simplified in various ways with or without `hook = empty`. A typical client (e.g., algaett, and perhaps stagedtt, and maybe others in the future) would use all the modules simultaneously, and it is important that all modifiers have the same type [hook Yuujinchou.Language.t](https://redprl.org/yuujinchou/yuujinchou/Yuujinchou/Language/index.html#type-t) for some `hook`, which means the type parameter `'hook` must be instantiated with the same (empty) type. However, there does not seem to be a good place to define the empty type.

PS: all of these are happening in the same OCaml package now, but we are constantly refactoring code across different packages. Maybe Yuujinchou.Scope should become a standalone package, for example.

Currently, I define the empty type in the final application, giving up the possibility of providing simplified interfaces in the libraries because I don't feel there's a good place to put the common empty type. Using the full interfaces is not a problem for me because I am the author, but a quick glance of [Yuujinchou.Modifier.Make](https://redprl.org/yuujinchou/yuujinchou/Yuujinchou/Modifier/Make/index.html) should make you wonder why there are four independent type parameters. The practical impact is that no ones except us can use these (in my opinion very powerful) libraries. (FYI: I tried to make up simplified interfaces with the unit type, but empty types make more sense in many cases.)

**Comment by gasche** [comment]
Thanks to my enemy the stale bot I was reminded of @stedolan's point in https://github.com/ocaml/ocaml/issues/10552#issue-958838670 in favor of having an explicit bottom type. I think that's a good argument (in Stephen's case it makes OCaml strictly more expressive), and I would support having a builtin `empty` type, re-exported as `Empty.t` in the stdlib, that is a bottom for the subtyping lattice.

**Comment by favonia** [comment]
~~I will try to make a PR.~~ I made a PR.
