### ISSUE TITLE
Rename the exception `Unhandled` to `Unhandled_effect`

### ISSUE THREAD

**Issue by favonia** [ocaml/ocaml#11262]
I believe the name `Unhandled` is too generic in OCaml---I would have thought it's for both exceptions and effects (and maybe other things). `Unhandled_effect` seems to be specific enough. The renaming should be done especially if we are in favor of implementing #11185.

**Comment by xavierleroy** [comment]
>  the name Unhandled is too generic in OCaml---I would have thought it's for both exceptions and effects (and maybe other things). Unhandled_effect seems to be specific enough

@ocaml/caml-devel this possible renaming must be decided before 5.0 is released, it will be too late afterwards.  Please discuss ASAP.

**Comment by fpottier** [comment]
Renaming to `Unhandled_effect` sounds good to me.

**Comment by kayceesrk** [comment]
Renaming to `Unhandled_effect` is a good idea.

**Comment by favonia** [comment]
This issue will also be closed by https://github.com/ocaml/ocaml/pull/11419.

**Comment by favonia** [comment]
Closing this issue as it has been addressed by renaming `Unhandled` to `Effect.Unhandled` in the PR ocaml/ocaml#11423.
