### ISSUE TITLE
Missing documentation: meaning of warning letters

### ISSUE THREAD

**Issue by shindere** [ocaml/ocaml#11285]
I believe that the meaning of the letters that can be used in warnings (see
function `letter` in `utils/warnings.ml`) is not documented in the reference
manual. Just nothing is said about which letters are accepted.

I'd be happy to submit a PR to improve this, but I am not sure
about the message we want to convey about using letters.

Independently of the message, I do think we should add something
about letters to the manual, even to say that using them is deprecated.

**Comment by Octachron** [comment]
The warning letters are explained in the manual in a not-so-obvious location:  https://v2.ocaml.org/manual/comp.html#s:comp-options .

**Comment by shindere** [comment]
After discussion with @Octachron, I confirm that the meaning of letters
is documented (in the list of warnings itself).

It may be good to split this list in two (the numeric warnings on
one side and the letters on the other side) so that a reference to the
secodn list can be added explicitly.

**Comment by gasche** [comment]
Where else would one expect to find them? (We could add a cross-reference.)

**Comment by shindere** [comment]
Gabriel Scherer (2022/10/11 01:20 -0700):
> Where else would one expect to find them? (We could add a
> cross-reference.)

I was expecting to find them just after the list of numeric warnings.

**Comment by Octachron** [comment]
Since the documentation exists, I propose to close the issue for now.
