### ISSUE TITLE
Options in compilerlib.Toploop to disable autoload alerts

### ISSUE THREAD

**Issue by favonia** [ocaml/ocaml#11283]
When updating [utop](https://github.com/ocaml-community/utop) for the new changes introduced in #11198 by @dra27, I found it non-trivial to disable the new alerts from the current compiler-lib API. I wonder if it makes sense to for example introduce some optional flag to `Toploop.set_paths` to disable the warnings. The practical issue is that utop's auto-completion will try to load Unix/Str/Dynlink when the user is still editing the line, and the alert would mess up the output. I suppose the philosophy of utop is to make things as easy as possible so I'm looking for ways to disable the alert.

**Comment by nojb** [comment]
> The practical issue is that utop's auto-completion will try to load Unix/Str/Dynlink when the user is still editing the line, and the alert would mess up the output.

Shouldn't `utop` be updated to set up the load path correctly to avoid triggering the alerts?

**Comment by dra27** [comment]
Unless there’s something else going in utop I hadn’t noticed, it should be silently fine once https://github.com/ocaml/ocamlfind/pull/41 is merged and release as `#require "unix"` will add the required directory anyway?
