### ISSUE TITLE
Warning 9 message contains ocaml specific syntax suggestion

### ISSUE THREAD

**Issue by Khady** [ocaml/ocaml#11313]
```
Either bind these labels explicitly or add '; _' to the pattern.
```

The `; _` part of this message is specific to the ocaml syntax. The compiler allows to use a different frontend such as reason for which the suggested fix is not valid. The reason syntax getting slowly extinct so I don't think that this is a critical problem. But it might happen with other frontend that I don't know about.

Same critic could be applied to warnings 23, 26, 27, 65.

**Comment by Octachron** [comment]
Neither the `ocamlc` nor the `ocamlopt` compiler allow to use different frontends (a preprocessor is not a frontend). It is hardly an issue that OCaml warning messages use OCaml syntax as a common language between the OCaml compiler(s) and OCaml users.

It is the compiler library that gives expert users the possibility to use alternative frontend. And it is the responsibility of such clients to adapt the compiler error messages to suit their needs. It might make sense to ensure that there is a reliable path to do so and I will gladly review such PR, but decreasing the readability of OCaml warning message is not an option.

**Comment by xavierleroy** [comment]
Like @Octachron I think the hints in these warnings are useful even though they don't apply to users of alternative syntaxes.  For this reason I'm closing this issue.
