### ISSUE TITLE
"make opt" fails on vanilla hardware

### ISSUE THREAD

**Issue by bcrowell** [ocaml/ocaml#11316]
This problem is occurring with today's source from github, on totally vanilla hardware. Here is the output of lscpu:

```
Architecture:        i686
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
Address sizes:       36 bits physical, 48 bits virtual
CPU(s):              2
On-line CPU(s) list: 0,1
Thread(s) per core:  1
Core(s) per socket:  2
Socket(s):           1
Vendor ID:           GenuineIntel
CPU family:          6
Model:               15
Model name:          Intel(R) Core(TM)2 Duo CPU     E4600  @ 2.40GHz
Stepping:            13
CPU MHz:             1838.221
CPU max MHz:         2400.0000
CPU min MHz:         1200.0000
BogoMIPS:            4800.21
L1d cache:           32K
L1i cache:           32K
L2 cache:            2048K
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe nx lm constant_tsc arch_perfmon pebs bts cpuid aperfmperf pni dtes64 monitor ds_cpl est tm2 ssse3 cx16 xtpr pdcm lahf_lm pti dtherm

```
I do ./configure && make world, and everything works, but then:

```
$ make opt
Makefile:1223: *** The source tree was configured with --disable-native-compiler!.  Stop.
```
Sorry if this is slim information to go on, but I don't know anything about the build system, so I don't know what other information would be of use to you. I'm guessing that the configure script thinks it's detecting something unusual about the hardware and sets a flag saying that the native compiler won't work. Since this is a very normal CPU, I'm thinking that this is a bug in the configure script.

The whole process works fine on the other machine I tried it on.

**Comment by dra27** [comment]
When you say “today’s” source code, has it previously worked on this machine?

It looks like you’re running either on a 32 bit OS or at least in 32 bit mode? What’s the output of `uname -a`? What are the host and target lines reported early in `configure`’s output?

**Comment by bcrowell** [comment]
Thanks for your reply.

'When you say “today’s” source code, has it previously worked on this machine?'

No.

'It looks like you’re running either on a 32 bit OS or at least in 32 bit mode?'

Uname -i gives 'unknown.' Getconf LONG_BIT outputs 32.

'What’s the output of uname -a?'

Linux cl-t091-011cl 4.19.0-10-686-pae #1 SMP Debian 4.19.132-1 (2020-07-24) i686 GNU/Linux

'What are the host and target lines reported early in configure’s output?'

```
checking host system type... i686-pc-linux-gnu
checking target system type... i686-pc-linux-gnu
```

**Comment by dra27** [comment]
Yup - OCaml 5.x doesn't at present support 32-bit native compilation. Where did you get the instructions for running `make opt` from (have we got some out-of-date instructions floating around in our INSTALL instructions?). For the last few releases, it's sufficient to do `./configure` followed by just `make`, which would do the `make world` for you.

If you need native compilation, then you either need an arm64 or x86_64 system or to use OCaml 4.14

**Comment by bcrowell** [comment]
I see. Thanks for taking the time to walk me through it and figure it out. The build instructions were just from notes I had sitting around from a long time ago.
As a feature suggestion, you might want to change the code to give some clearer / more informative output in this situation. Something like "ocamlopt will not be built, only 64-bit architectures are supported."
