### ISSUE TITLE
tests/typing-sigsubst/sigsubst.ml gives varying output

### ISSUE THREAD

**Issue by garrigue** [ocaml/ocaml#11317]
For some reason, the test at `testsuite/tests/typing-sigsubst/sigsubst.ml` gives unstable output, apparently depending on the machine it runs on.
One reason seems to be that it reveals internal `Ident.t` numbers, but it is not the only such test, so this is only a partial explanation.

**Comment by gasche** [comment]
Can you show an example of output difference from the reference file? (For example the diff between observed output and reference output)

**Comment by Octachron** [comment]
It sounds like it might be #11318 : there was a cmi file that was only read if the compiler was installed which made the tests that relied on `Ident.t` fail after a `make install`.

**Comment by garrigue** [comment]
```
> Action 3/3 (check-program-output) => failed (program output sigsubst.ml.corrected.corrected differs from reference sigsubst.ml: 
> --- sigsubst.ml	2022-06-15 11:16:11.000000000 +0900
> +++ sigsubst.ml.corrected.corrected	2022-06-15 11:23:23.000000000 +0900
> @@ -24,11 +24,11 @@
>  Line 3, characters 2-36:
>  3 |   include Comparable with type t = t
>        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> -Error: Illegal shadowing of included type t/285 by t/290
> +Error: Illegal shadowing of included type t/304 by t/309
>         Line 2, characters 2-19:
> -         Type t/285 came from this include
> +         Type t/304 came from this include
>         Line 3, characters 2-23:
> -         The value print has no valid type if t/285 is shadowed
> +         The value print has no valid type if t/304 is shadowed
>  |}]
>  
>  module type Sunderscore = sig
> 
> )
```

Even if I fix it, I get errors in the CI.

**Comment by garrigue** [comment]
Indeed, I cherry-picked #11318 into #10834, and that solved the problem (the CI is now happy).
Please merge.
I hope this also solves another problem, whereas `make install` was necessary after `make bootstrap` to run the testsuite.

**Comment by garrigue** [comment]
I rebased #11207 over #11318, and this does not fix the bootstrap problem. I.e., if ocaml was installed before, after a bootstrap it is necessary to `make install` before running the testsuite.
