### ISSUE TITLE
Reflect "explicit binders for type variables" feature in `Types`?

### ISSUE THREAD

**Issue by pitag-ha** [ocaml/ocaml#11319]
Has there been a follow-up somewhere on [@gasche's question](https://github.com/ocaml/ocaml/pull/10437#issuecomment-1080826660) whether a `cd_vars` field should be added to `Types.constructor_declaration`?

The reason for that question is the following: when [explicit binders for type variables](https://github.com/ocaml/ocaml/pull/10437) were introduced for 4.14, the `cd_vars` field was added both to [`Typedtree.constructor_declaration`](https://github.com/ocaml/ocaml/blob/trunk/typing/typedtree.mli#L664) and to [`Parsetree.constructor_declaration`](https://github.com/ocaml/ocaml/blob/trunk/parsing/parsetree.mli#L529). It wasn't added to [`Types.constructor_declaration`](https://github.com/ocaml/ocaml/blob/trunk/typing/types.mli#L512-L520) though. From a theoretical point of view, doing so might be good for coherency. And from a practical point of view, doing so would have the advantage that PPXs that rely on the `Types` module, could treat the new feature (see for example`ppx_import` and the conversation about that [here](https://github.com/ocaml-ppx/ppx_import/pull/69#discussion_r836334404)).

Of course, this question isn't the most urgent thing right now, so feel free to answer once the 5.0 alpha release work has calmed down.

**Comment by lpw25** [comment]
I would generally say that `cd_vars` should not appear in `Types.constructor_declaration`. The stuff in `Types` is supposed to represent that semantic type, and doesn't generally contain additional data about the exact syntax that was used. Obviously we remember some syntactic information to improve error messages, but mostly we throw that stuff away.

I think that ppx_import shouldn't really need `cd_vars` to produce valid syntax. It should be possible both to add explicit binders for all bound type variables or to produce no explicit binders, and either would seem to be fine for its use case.

**Comment by pitag-ha** [comment]
Thanks a lot for the nice and quick answer @lpw25! I'm convinced now that the explicit binders shouldn't be reflected in `Types` (I wasn't aware they don't have any impact on the semantics at all, and not even on the error messages).
