### ISSUE TITLE
Add functionality for serialization and deserialization of Random.State

### ISSUE THREAD

**Issue by bluddy** [ocaml/ocaml#11322]
Certain applications (simulations, games, etc) could benefit from the ability to save the current state of the RNG and reload and continue from where they were. It's not enough to have the same seed, because that would require keeping track of how many random numbers have been generated so far, and then looping over the RNG and generating that same number of random numbers, which is inefficient and inelegant. We have functions to load and save the Random.State, but the actual state is opaque, making it impossible to serialize or deserialize unless we use Marshal.

**Comment by dra27** [comment]
Perhaps I just woke up, but "making it impossible to serialize or deserialize unless we use _the Standard Library's serialisation and deserialisation module_?" 🤔

Given that the representation just changed in 5.0, that seems to be a compelling reason not to provide a less opaque mechanism?

**Comment by bluddy** [comment]
Marshal doesn't guarantee any more compatibility than any other method. The only thing the current situation does is prevent any other methods from being used.

**Comment by dra27** [comment]
I'm still puzzled how that's true and what you'd then do with it - given that `Random.State.t` is tied to a given version of the compiler (even if you can get away with loading it across 3.x and 4.x versions, I think, but here be dragons), what's needed beyond `Marshal.to_string` to support any other mechanism?

**Comment by bluddy** [comment]
OK, that's a good point. That'll work. I'm not crazy about the polymorphic nature of Marshal, but it does work.

**Comment by dbuenzli** [comment]
Note if you are doing generative art/sim/whatever needs an algorithm that will regenerate your sequences forever in the future I'd advise against using the stdlib PRNG. With 5.0 it's the second time it's getting changed, I don't think it's safe to assume it's not going to be changed again.

It's actually a bit sad. Since it's neither crypto quality (AFAIR) nor guaranteed to be stable in the future, it  significantly limits its uses.

**Comment by Octachron** [comment]
Concerning stability of the Random module,  I am planning to publish a versioned library for the Random PRNG sometimes before the release.

Concerning state serialization, one advantage that I see of having a simple string serializer is security: the Marshall module can only be used on files that have the same security level than the executable. Serializing the state to a string would not have this issue.

**Comment by gasche** [comment]
> It's not enough to have the same seed, because that would require keeping track of how many random numbers have been generated so far, and then looping over the RNG and generating that same number of random numbers, which is inefficient and inelegant. 

In fact LXM, the generator for OCaml 5, has efficient "jump" functions that can jump ahead 2^k steps in O(1). So in fact, if we kept track of the number of "next" calls to the generator, we could rebuild the same state in logarithmic time (over the number of draws), which would be fine in practice.

This sounds overkill / a theoretical idea. In practice serialization could indeed be fine. It would not be too hard to implement `to_string` and `of_string` methods for random state.

**Comment by xavierleroy** [comment]
> Note if you are doing generative art/sim/whatever needs an algorithm that will regenerate your sequences forever in the future I'd advise against using the stdlib PRNG. With 5.0 it's the second time it's getting changed, I don't think it's safe to assume it's not going to be changed again.

Agreed.  If you're into the very small group that needs PRNG reproducibility, the PRNG should be part of your application.

> It's actually a bit sad. Since it's neither crypto quality (AFAIR) nor guaranteed to be stable in the future, it significantly limits its uses.

This is unnecessarily harsh.  We're trying to keep up with recent progress in random number generation and provide you with what's arguably the best PRNG known today, and you just turn up your nose.  Many applications of PRNGs require neither cryptographic strength nor long-term reproducibility, but benefit from a statistically-perfect, fast, and splittable PRNG.

**Comment by dbuenzli** [comment]
> This is unnecessarily harsh. We're trying to keep up with recent progress in random number generation and provide you with what's arguably the best PRNG known today, and you just turn up your nose.

Right, I should have said *my* uses. I certainly do appreciate the hard work that went into the new PRNG. 

That being said @Octachron I don't know how you see the planned library but if we can have a library in which we put all the PRNGs that the stdlib ever exposes via `Random`, that does actually significantly increases *my* uses since it becomes stable APIs for those application in which PRNGs should be part of the application. If you have a clear idea of what you want and think you can delegate part of the work, I'll glady give a hand, just get in touch.

**Comment by gasche** [comment]
In #11329 I propose to add serialization functions fbetwen `Random.State.t` and `Bytes.t`.
