### ISSUE TITLE
Symbol name collision on ARM64 causing link errors

### ISSUE THREAD

**Issue by mbacarella** [ocaml/ocaml#11321]
I have a very large file called `values.ml`. To speed up compilation, I split it up into files named `values__0.ml` ... `values__7.ml`, then I changed my `values.ml` file to:

```ocaml
include Values__0
include Values__1
include Values__2
include Values__3
include Values__4
include Values__5
include Values__6
include Values__7
```

This works great. Compiles much faster with much less memory usage. On x86-64.

On ARM64 (both on an Apple M1 and Ubuntu on AWS Graviton2) it causes a link error like so:
```
duplicate symbol '_camlFoo_bar__Values__4' in:
    foo/bar/foo_bar.a(foo_bar__Values__4.o)
    foo/bar/foo_bar.a(foo_bar__Values.o)
duplicate symbol '_camlFoo_bar__Values__3' in:
    foo/bar/foo_bar.a(foo_bar__Values__3.o)
    foo/bar/foo_bar.a(foo_bar__Values.o)
duplicate symbol '_camlFoo_bar__Values__2' in:
    foo/bar/foo_bar.a(foo_bar__Values__2.o)
    foo/bar/foo_bar.a(foo_bar__Values.o)
duplicate symbol '_camlFoo_bar__Values__1' in:
    foo/bar/foo_bar.a(foo_bar__Values__1.o)
    foo/bar/foo_bar.a(foo_bar__Values.o)
ld: 4 duplicate symbols for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I noticed however that the symbols in the `objdump -D foo__bar.a` appear to be random blobs of code.

```
000000000000a8e8 <_camlFoo_bar__Values__4>:
    a8e8: 00 00 00 00   udf     #0
    a8ec: 00 00 00 07   <unknown>
    a8f0: fc 17 00 00   udf     #6140
    a8f4: 00 00 00 00   udf     #0

000000000000a8f8 <_camlFoo_bar__Values__3>:
    a8f8: 2e 2f 5f 62   <unknown>
    a8fc: 75 69 6c 64   <unknown>
    a900: 2f 64 65 66   <unknown>
    a904: 61 75 6c 74   <unknown>
    a908: 2f 61 77 73   <unknown>
    a90c: 2f 65 63 32   <unknown>
    a910: 2f 76 61 6c   ldnp    d15, d29, [x17, #-496]
    a914: 75 65 73 2e   umax.4h v21, v11, v19
    a918: 6d 6c 00 00   udf     #27757
    a91c: 00 00 00 05   <unknown>
    a920: fc 0b 00 00   udf     #3068
    a924: 00 00 00 00   udf     #0

000000000000a928 <_camlFoo_bar__Values__2>:
    a928: 61 77 73 6d   ldp     d1, d29, [x27, #-208]
    a92c: 5f 65 63 32   <unknown>
    a930: 00 00 00 00   udf     #0
    a934: 00 00 00 07   <unknown>
    a938: fc 0f 00 00   udf     #4092
    a93c: 00 00 00 00   udf     #0

000000000000a940 <_camlFoo_bar__Values__1>:
    a940: 41 77 73 6d   ldp     d1, d29, [x26, #-208]
    a944: 5f 65 63 32   <unknown>
    a948: 5f 5f 56 61   <unknown>
    a94c: 6c 75 65 73   <unknown>
    a950: 00 00 00 00   udf     #0
    a954: 00 00 00 07   <unknown>
```

Also there's only 4 of those even thought there are eight submodules.

That made me wonder if naming my modules `Values__0` ... `Values__7`  when I also have a `Values` begged for some kind of generated symbol name collision. Sure enough, changing them to `values_sub0.ml` ... `values_sub7.ml` fixed the issue.

So, a workaround is possible though I'm sorry to say I don't know what exactly is causing this collision.

Every minimal test case I've tried to construct does not exhibit this bug. Hopefully the cause of the bug is more apparent to in-the-know people. Thanks very much.

**Comment by shindere** [comment]
Many thanks for the report!

Does it change something if you change thenumber of _ characters (using
1, 3...)?

Out of curiosity, is your values.ml handwritten?

I'd be curious about your use-case.

**Comment by mbacarella** [comment]
> Many thanks for the report! Does it change something if you change the number of _ characters (using 1, 3...)?

1 _ works
3 ___ works

> Out of curiosity, is your values.ml handwritten? I'd be curious about your use-case.

No, it's program generated.

**Comment by lthls** [comment]
Don't use double underscores in your program, it's used internally by the compiler as a separator. In this case, the symbol for the module `Values__4` (`camlFoo_bar__Values__4`) clashes with a static constant numbered 4 from `Values`, which also gets the symbol `camlFoo_bar__Values__4`.
(Following this same argument, `dune` shouldn't use double underscores it its generated module names either)

**Comment by mbacarella** [comment]
I believe you, but why is the x86-64 backend able to build this, out of curiosity?

**Comment by lthls** [comment]
On my laptop, I do get linking errors with a small repro case similar to yours.
One possibility is that you're using flambda on your x86_64 setup, and not on the ARM64 ones (Flambda generates slightly different symbol names).

**Comment by gasche** [comment]
> Don't use double underscores in your program, it's used internally by the compiler as a separator.

I would argue that this is a bug in the compiler: if we mangle names, we should do it correctly.

This is related to #9108 and #8998 where @sliquister tried to fix this issue, but unfortunately we couldn't come to an agreement on the design and there was no pressing need, so we did not do anything. Would the implementation in #9108 fix the present bug?

**Comment by lthls** [comment]
> Would the implementation in #9108 fix the present bug?

No, none of the symbols in this case would be considered "problematic". The proposals to change the module separator would work though.

**Comment by mbacarella** [comment]
> One possibility is that you're using flambda on your x86_64 setup, and not on the ARM64 ones (Flambda generates slightly different symbol names).

Weirdly, no. I can't get it to happen on either regular or flambda x86-64 switches.

How are you able to repro this? This collision seems like it would require being able to create values *named* `1`, `2` `3` and `4`?

**Comment by Octachron** [comment]
Using a double underscore `__` in type paths has been the recommended way to hide non-canonical type paths since at least OCaml 4.03 : https://ocaml.org/manual/comp.html (see the `-short-path` description). There is a conflict between the typechecker and the backends if some backends cannot handle such names.

**Comment by lthls** [comment]
The double underscores can be handled in types just fine. It's only when you use them for values that you get a problem, and we never recommended to use double underscores for values. You can also find a discussion of the same issue in #7086, by the way, with the obvious solution (change the module separator) proposed but not implemented.

**Comment by shindere** [comment]
Vincent Laviron (2022/06/16 02:00 -0700):
> > Would the implementation in #9108 fix the present bug?
>
> No, none of the symbols in this case would be considered
> "problematic". The proposals to change the module separator would work
> though.

Am I correct that, to be robust, the mangling would have to be dynamic?

It is my guess that if a mangling is odne in a static way, then it is
always possible to write a program that will defeat that mangling. Is
that correct?

**Comment by lthls** [comment]
> Am I correct that, to be robust, the mangling would have to be dynamic? It is my guess that if a mangling is odne in a static way, then it is always possible to write a program that will defeat that mangling. Is that correct?

If you only consider compilation from sources, then by choosing as a delimiter a character that is forbidden in module names and identifiers we don't need dynamic mangling (that's what Xavier did in #11430).
If someone uses compiler-libs directly, then it's possible to create identifiers with any character, but I don't think we need to be robust against that.

**Comment by shindere** [comment]
Quite likely this comment that just landed on GitHub had been sent eons
ago.

It seems many of my e-mails were held somewhere (I don't know where).

Sorry for the noise!

**Comment by lthls** [comment]
Ah, I wondered why we saw so many comments from you at the same time. I hope it means someone fixed a bug, and you won't have to worry about your comments being lost again.

**Comment by shindere** [comment]
Vincent Laviron (2022/10/11 03:54 -0700):
> Ah, I wondered why we saw so many comments from you at the same time.
> I hope it means someone fixed a bug, and you won't have to worry about
> your comments being lost again.

Thanks! Let's hope so!!
