### ISSUE TITLE
Support for `@perform` tag in ocamldoc

### ISSUE THREAD

**Issue by raphael-proust** [ocaml/ocaml#11327]
The `ocamldoc` command supports multiple tags for docstrings. It supports `@raise` which is useful to document the exception raising behaviour of functions. It would be useful to have a similar `@perform` tag for effects.

Documenting which effects are performed by which function seems important for an API to be usable. It helps determine what handler is needed. Having an `@perform` tag would make such documentation more normalised, more greppable.

The format of the suggested tag can be similar to that of the exception raising one (`@perform Effect text`) and the rendering too.

-----------------

It could also be useful to have a `@handle Effect` tag to indicate that a higher order function handles `Effect` when calling one of its argument. E.g.,

```
(** @handle Yield *)
val run : ('a -> 'b promise) -> 'a -> 'b
```

This tag would indicate that a given effect is always handled and never escapes from evaluation.

**Comment by shindere** [comment]
Thanks!

The idea looks meaningful to me but I don't expect it to be implemented
in ocamldoc so I'd suggest to rather open an issue against odoc.

**Comment by Octachron** [comment]
I am not sure that having a documentation tag for an experimental feature is a good idea.

Moreover, we plan to have a typed effect system by the time effect handlers are no longer experimental. This means that the tag would be only useful during the experimental phase of effects which seems not ideal.

**Comment by raphael-proust** [comment]
> Moreover, we plan to have a typed effect system by the time effect handlers are no longer experimental. This means that the tag would be only useful during the experimental phase of effects which seems not ideal.

I'm not sure that's true. Even if we had exception-tracking in the type system, it'd be useful to have the `@raise` tag. Specifically, it'd be useful so that you could indicate the conditions under which an exception is raised:

```
val make : int -> t with raise Invalid_argument
```

is less informative than

```
(** [make v] creates a new [t] blah blah balh

    @raise Invalid_argument if a prior call to [make u] was made where [u >= v]. *)
val make : int -> t with raise Invalid_argument
```

For the same reason the `@perform` tag could still be useful. (It's similar to how we have the `@param` and `@return` tags even though those already appear in the type of the function.)

**Comment by raphael-proust** [comment]
Moved to https://github.com/ocaml/odoc/issues/880, including ongoing thread of conversation.

**Comment by shindere** [comment]
Raphaël Proust (2022/06/21 00:15 -0700):
> Moved to https://github.com/ocaml/odoc/issues/880, including ongoing
> thread of conversation.

Well done! Thanks! Your proposal makes perfectly sense to me, although I
am way less informed than @Octachron about real OCaml programming.
