### ISSUE TITLE
Add Map.add_to_{list,set}

### ISSUE THREAD

**Issue by dbuenzli** [ocaml/ocaml#11334]
Here are two functions I keep on defining after a `Map.Make`: 

```ocaml 
val Map.add_to_list : Map.key -> 'a -> 'a list Map.t -> 'a list Map.t
(** [Map.add_to_list k v m] is [m] with [k] mapping to [l] such that [l] is
    [v :: Map.find k m] if [k] was bound in [m] and [[v]] otherwise. *)

val Map.add_to_set :
      (module Set.S with type elt = 'a and type t = 'set) ->
      Map.key -> 'a -> 'set Map.t -> 'set Map.t
(** [Map.add_to_set (module S) k v m] is [m] with [k] mapping to [s] such that [s] is
    [S.add v (Map.find k m)] if [k] was bound in [m] and [S.singleton v] otherwise. *)
```

I'd like to add them to `Map` but I prefer to test the waters and bikeshed before trying to PR. Here is a [typical implementation](https://github.com/b0-system/b0/blob/914aeaae0861b185377267ccf1366d030453ae8f/src/b00/std/b00_std.ml#L1222-L1231) of these functions. 

The second function would make `Map` depend on `Set`'s interface which people may understandably object.

**Comment by jberdine** [comment]
FWIW the Stdlib extension I use has a function analogous to `add_to_list`, though implemented using `update` to search the underlying tree structure only once.

**Comment by dbuenzli** [comment]
I'd like to prepare a PR for this. 

Regarding the second function Any upstream opinion on introducing a dependency on `Set` in `Map` ? If there's a strong opposition I'll simply add the first function.

**Comment by dbuenzli** [comment]
Qui ne dit mot consent. I have opened https://github.com/ocaml/ocaml/pull/11410 (with slightly more along the way).

**Comment by dbuenzli** [comment]
> ```ocaml
> val Map.add_to_set :
>       (module Set.S with type elt = 'a and type t = 'set) ->
>       Map.key -> 'a -> 'set Map.t -> 'set Map.t
> (** [Map.add_to_set (module S) k v m] is [m] with [k] mapping to [s] such that [s] is
>     [S.add v (Map.find k m)] if [k] was bound in [m] and [S.singleton v] otherwise. *)
> ```

So, since nobody wants to make the critique of this, I'll do it myself :-) 

I use this pattern in my code bases, but it's a limited pattern since you cannot use it on higher-kinded types. Given that I find it questionable to introduce it in the `Stdlib`.

Besides this totally steps on modular implicits territory and I don't want to suppress a good example researchers could use in their papers. 

Thus, as far as I'm concerned, once https://github.com/ocaml/ocaml/pull/11410 is merged, which has `Map.add_to_list`, this can be closed.
