### ISSUE TITLE
assigning result of Bool_val to bool generates error (when used in C++ context)

### ISSUE THREAD

**Issue by ygrek** [ocaml/ocaml#11332]
```
stubs.c:561:54: fatal error: non-constant-expression cannot be narrowed from type 'int' to 'bool' in initializer list [-Wc++11-narrowing]
  struct bpf_filter f { bytes_of_value(Field(v, 0)), Bool_val(Field(v, 1)), t };
                                                     ^~~~~~~~~~~~~~~~~~~~~
/home/user/code/monorepo/_opam/lib/ocaml/caml/mlvalues.h:388:21: note: expanded from macro 'Bool_val'
#define Bool_val(x) Int_val(x)
                    ^~~~~~~~~~
/home/user/code/monorepo/_opam/lib/ocaml/caml/mlvalues.h:80:20: note: expanded from macro 'Int_val'
#define Int_val(x) ((int) Long_val(x))
```

~it was a warning with gcc, but new-ish~ clang makes it an error. It is fixable on the "user" side with an explicit cast but it looks ugly (`(bool)Bool_val`). Does it make sense to have this cast in mlvalues.h guarded with `#ifdef __cplusplus`?

**Comment by xavierleroy** [comment]
Does C++ support `_Bool` from C99 ?  Now that OCaml requires a C11-compliant C compiler, it would make sense to add a cast to `_Bool` in `Bool_val`.

**Comment by ygrek** [comment]
including `<stdbool.h>` and casting `Bool_val` result to `_Bool` makes the compiler happy. Afaiu theoretically there is no guarantee that it will always work (C++ `bool` is not guaranteed to be compatible with C `_Bool`), but I understand for all practical purposes this is ok especially if C and C++ compilers are from the same vendor. In particular I am fine with this solution :)

**Comment by nojb** [comment]
> including `<stdbool.h>` and casting `Bool_val` result to `_Bool` makes the compiler happy. Afaiu theoretically there is no guarantee that it will always work (C++ `bool` is not guaranteed to be compatible with C `_Bool`), but I understand for all practical purposes this is ok especially if C and C++ compilers are from the same vendor. In particular I am fine with this solution :)

For those trying to follow the discussion: `stdbool.h` defines, in C mode, a macro called `bool` as a synonym of `_Bool` (which is a built-in type for C). In C++ mode (in which case `_Bool` is not defined), this header defines `_Bool` as a synonym of `bool` (which is a built-in type for C++). The C++ behaviour is not standard. See eg https://github.com/gcc-mirror/gcc/blob/master/gcc/ginclude/stdbool.h

Given this, if we add a `(_Bool)` cast in `Bool_val`, then `Bool_val` will no longer compile in C++ without including as well `stdbool.h` in the file where it is being used, or am I missing something?

**Comment by ygrek** [comment]
mlvalues.h will include stdbool.h

**Comment by xavierleroy** [comment]
> mlvalues.h will include stdbool.h

That's problematic, because it can break third-party C code that does `typedef int bool;`.

We probably need to have two different definitions of `Bool_val`, one for C++ and one for C.

**Comment by xavierleroy** [comment]
The friendly stale bot helpfully reminds me of this issue.  Thank you friendly bot.

Thinking about it, I believe the best solution is to define `Bool_val` as
```
#define Bool_val(v) ((v) != Val_false)
```
This has type `bool` in C++.  It produces the same results as the current `Bool_val` macro when `v` is `Val_false` or `Val_true`.  Both macros seem to compile down to the same number of machine instructions, as shown by a quick Godbolt check.  Did I miss a downside?

**Comment by gasche** [comment]
For context, the current definitions are

```
#define Long_val(x)     ((x) >> 1)
#define Int_val(x) ((int) Long_val(x))
#define Bool_val(x) Int_val(x)

#define Val_false Val_int(0)
#define Val_true Val_int(1)
```

Here is a goldbolt link comparing the result: https://godbolt.org/z/xeETxbv1h. I observe that the current and new definitions both generate different code when producing an `int` or a `_Bool`. The existing definition gives a 2-instruction sequence to `int` but a 3-instruction sequence to `_Bool`, and conversely the proposal gives a 2-instruction sequence to `_Bool` but a 3-instruction sequence to `int`. (On arm64+gcc, the current definition has a one-instruction expression to `int`, and the new definition for both types is a two-instruction sequence.)

**Comment by MisterDA** [comment]
As of 5.2+trunk today…

> That's problematic, because it can break third-party C code that does `typedef int bool;`

There's one use of `stdbool.h` in `caml/frame_descriptors.h`. EDIT: oops, this one is actually a fix you committed, so it should be correct.
 
> In C++ mode (in which case `_Bool` is not defined), this header (`cstdbool`) defines `_Bool` as a synonym of `bool` (which is a built-in type for C++). The C++ behaviour is not standard. See eg <https://github.com/gcc-mirror/gcc/blob/master/gcc/ginclude/stdbool.h>.

Thus LLVM doesn't define `_Bool` in C++. <https://github.com/llvm/llvm-project/blob/main/libcxx/include/cstdbool>. There's one use of `_Bool` in `runtime/caml/domain_state.tbl`, that gets included in `caml/mlvalues.h`, so the C++ build using LLVM is currently broken.

**Comment by smuenzel** [comment]
> 2-instruction sequence to `_Bool` but a 3-instruction sequence to `int`

For context: the reason for this is that `sizeof(_Bool) == 1`. This means that only the LSByte of the return value will be used -- so on x86, we can use `setXX` only (which only sets a single-byte register), but when we return an int, we need to zero the register first. In terms of performance, the extra `xor eax,eax` only consumes space, but no execution resources. The performance of the 3-instruction version may actually be faster, since it will not cause a stall (a stall can happen because we need to merge the result of `setXX` with the high bytes of whatever was in eax previously).

So I think this means both instruction sequences are okay.

**Comment by xavierleroy** [comment]
Enough clever C/C++ - compatible solutions, let's go for an `#ifdef`: #12702
