### ISSUE TITLE
The missing part of OCaml, is the core library

### ISSUE THREAD

**Issue by ghost** [ocaml/ocaml#11341]
What missing part of OCaml? i guess not the language itself.
But the core library.

## Network

https://github.com/golang/net
https://github.com/netty/netty

##  Database
https://github.com/mybatis/mybatis-3

https://github.com/dotnet/docs/blob/main/docs/csharp/linq/index.md

https://github.com/dotnet/efcore

## Graphic 
https://github.com/ImageMagick/ImageMagick

## Charts
https://github.com/plotly/plotly.py 

## Http 
https://github.com/square/okhttp

## Html parser
https://github.com/jhy/jsoup

## Distribute and cluster 

https://github.com/akka/akka
https://github.com/LMAX-Exchange/disruptor

## Message queue
[mostly library to working with Message queue]
 https://github.com/apache/kafka
https://github.com/apache/rocketmq
https://github.com/apache/activemq

## Utils and library

https://github.com/google/guava
https://github.com/eclipse/eclipse-collections

## RPC

https://github.com/apache/dubbo
https://github.com/apple/servicetalk
https://github.com/grpc/grpc

**Comment by Octachron** [comment]
A random collection of links to libraries (that are not part of any language standard libraries) is not really an actionable feature wish.

You are welcome to open a discussion at https://discuss.ocaml.org, but I am closing this issue.
