### ISSUE TITLE
API to know which platform my app running.

### ISSUE THREAD

**Issue by ghost** [ocaml/ocaml#11351]
## Purpose 
Expose api , let code can detect current running Operating system os.

## Design
expose is[Android]    API,  and runtime.GETOS api 
1. check if it is [Android] or other OS
2. get current OS name

```bash
const GOOS = `aix`

const IsAix = 1
const IsAndroid = 0
const IsDarwin = 0
const IsDragonfly = 0
const IsFreebsd = 0
const IsHurd = 0
const IsIllumos = 0
const IsIos = 0
const IsJs = 0
const IsLinux = 0
const IsNacl = 0
const IsNetbsd = 0
const IsOpenbsd = 0
const IsPlan9 = 0
const IsSolaris = 0
const IsWindows = 0
const IsZos = 0
```

golang provided good api to detect OS

https://cs.opensource.google/go/go/+/refs/tags/go1.18.3:src/internal/goos/gengoos.go

**Comment by ghost** [comment]
Rust lang also have a way to know it .
https://doc.rust-lang.org/std/env/consts/constant.OS.html#

**Comment by dra27** [comment]
See https://github.com/ocaml/ocaml/issues/10613 for discussion related to this already.

There are functions in opam’s core library for doing this already, though - see [`OpamStd.Sys.os`](https://ocaml.org/p/opam-core/2.1.2/doc/OpamStd/Sys/index.html#val-os)

**Comment by ghost** [comment]
Oh, i am looking for it in OCaml std library . 

I am not looking for OPam Std library..

Did they the same level?


I think  ocaml std library is language level ,  The Opam is the third party level?

**Comment by dra27** [comment]
As per [stdlib/CONTRIBUTING.md](https://github.com/ocaml/ocaml/blob/trunk/stdlib/CONTRIBUTING.md), we may need a better case for this kind of addition. This might be a useful addition to, say, the Unix library, but for me this is better covered by external libraries, especially here as that means that fixes/changes can be used by any release of OCaml, not just the latest release. There are already function in the `Sys` module for determining the platform a program is running (`Sys.win32`, `Sys.unix`, `Sys.backend_type`, etc.).

**Comment by xavierleroy** [comment]
`Sys.os_type` in OCaml does the same thing as `std::env::consts::OS` in Rust, which was given as an example in this feature request.  So the feature is already there.  Closing.
