### ISSUE TITLE
Cygwin support in OCaml 5.0 ?

### ISSUE THREAD

**Issue by purplearmadillo77** [ocaml/ocaml#11350]
Recently I was trying to build Ocaml from this repository using Cygwin. I was able to successfully build Ocaml (and use it since) on Cygwin a couple months ago, but now when I run ./configure I get

```
$ ./configure
configure: Configuring OCaml version 5.1.0+dev1-2022-06-09
checking build system type... x86_64-pc-cygwin
checking host system type... x86_64-pc-cygwin
checking target system type... x86_64-pc-cygwin
configure: error: Cygwin is not supported currently
```

Digging through the history, I noticed that in April some lines were added to configure.ac with the note "The MSVC and Cygwin ports are not supported currently". However, documentation such as README.adoc and README.win32.adoc still heavily imply that Cygwin is a viable option. I looked for (but could not find, unless I missed something) an issue discussing this change, so I was just curious what the reasoning behind it was. I was also wondering whether this is a temporary or permanent change, and if there is an alternative solution for running Ocaml on Windows (in some flavor, Cygwin or not) for the time being. Finally, could the documentation be updated to reflect the change? I’m willing to help with this step once I know more. Thank you!

Thank you.

**Comment by nojb** [comment]
Please use the `4.14` branch, which should work without any problem. The current `trunk` and the `5.0` branches include the freshly added Multicore support and as you discovered some architectures are not yet supported (the plan is to bring back support for them eventually). See https://discuss.ocaml.org/t/ocaml-5-0-zeroth-alpha-release/10026 for information about the 5.0 plan.

**Comment by dra27** [comment]
[I have a cunning plan](https://en.m.wikipedia.org/wiki/Baldrick) for Cygwin64 (and [a somewhat evil plan](https://en.m.wikipedia.org/wiki/Bleak_Expectations) for MSVC64), but neither is likely for 5.0 - mingw-w64 is the only supported host on Windows for this release (with bytecode-only in 32bit mode, as for other platforms)

**Comment by gasche** [comment]
> Please use the 4.14 branch, which should work without any problem. 

We have been saying this a lot recently. Could someone add a big warning to the README to make this information more readily available to users? (Does @nojb volunteer to send a PR to this effect?)

**Comment by nojb** [comment]
> Does @nojb volunteer to send a PR to this effect?

Sure, I'll open a PR later today :)

**Comment by xavierleroy** [comment]
`README.win32.adoc` needs updating even more...

**Comment by nojb** [comment]
See #11355
