### ISSUE TITLE
Warning for used variable starting with underscore

### ISSUE THREAD

**Issue by SkySkimmer** [ocaml/ocaml#11366]
Prefixing a variable name with `_` (eg `_foo`) disables the unused variable warning for it. Therefore it is common to use `_foo` to mean "this variable is unused" while still implying something about its meaning through the name (eg `fun (bla, _other_data)`).

However there is currently nothing (AFAIK) to prevent such variables from being used (which will surprise the code reader).

Therefore I propose we have some warning to enforce this pattern of not using `_` variables.

**Comment by nojb** [comment]
One case where this would be inconvenient is when adding an underscore to an identifier bound to a recursive function, where the identifier is necessarily used in the body of the function.

**Comment by alainfrisch** [comment]
Another case I've seen recently is the use of some `_foo` identifier for a function argument which can be used or not, depending on whether some code instrumentation (through ppx) is applied.  Of course, we could always disable the new warning, but I'm tempted to say that people using `_foo` do it deliberately and "know what they do" (and usually, they do it for a good reason, not specifically to confuse the reader).

**Comment by dbuenzli** [comment]
I would also often use `_f` for a C binding or auxiliary function used by a function exposed as `f`. I'm not necessarily attached to that practice though.

**Comment by xavierleroy** [comment]
This feature wish is getting rather negative opinions.  Anyone would like to champion it?  Otherwise we'll close it.

**Comment by SkySkimmer** [comment]
I still hate the bot

**Comment by Octachron** [comment]
There seems to be few supporting voices for this feature request after one year. I am thus closing it.
