### ISSUE TITLE
Document update using dune as primary build system?

### ISSUE THREAD

**Issue by ghost** [ocaml/ocaml#11363]
https://ocaml.org/docs/modules
The document is still base on ocamlopt , I guess it a bit out of sync modern OCaml world.
Now we using dune for every single , small or large project of OCaml.
So the question is , why not just teach user using dune as primary build system for learning OCaml.

I tried to learn OCaml to build with ocamlopt, but it hard to manage a real size OCaml project.
Dune looks a real good tools , just like maven to java, cmake to cpp/c,  cargo to rust.
So please rewrite document, base on dune build tools.

**Comment by Khady** [comment]
this is not the right repo for this issue. The ocaml.org website source code is in https://github.com/ocaml/ocaml.org. You can open your issue there.

**Comment by ghost** [comment]
ok, let's move forward
