### ISSUE TITLE
4.14.0/4.14.1 - Long compiler options in CFLAGS breaks configure’s flexlink test

### ISSUE THREAD

**Issue by purplearmadillo77** [ocaml/ocaml#11370]
Recently I was (again) trying to build Ocaml from this repository using Cygwin. I’ve downloaded release 4.14.0 from https://github.com/ocaml/ocaml/archive/refs/tags/4.14.0.tar.gz and if I run ./configure with no options, it will run smoothly and allow me to build properly. 

However, running something like `./configure CFLAGS="--param=ssp-buffer-size=4"` (or, I believe, due to some scant testing, anything with a double hyphen) results in the following error. This error also persists when building from the 4.14 development branch. 
```
checking for flexdll sources... no
checking for flexlink... flexlink
checking whether flexlink works... no
configure: error: flexlink does not work
```

config.log reveals the error is because of the option:
```
configure:13065: checking whether flexlink works
configure:13072: gcc -c --param=ssp-buffer-size=4  conftest.c >&5
configure:13072: $? = 0
configure:13091: flexlink -chain cygwin64 -exe -o conftest.exe --param=ssp-buffer-size=4 -DCAML_NAME_SPACE    conftest.c conftest2.o >&5
/usr/lib/flexdll/flexlink: unknown option '--param=ssp-buffer-size=4'.
```

It seems like the C compiler options shouldn’t be passed to flexlink—there’s a comment in configure that sort of describes this.
```
# Command to build executalbes
# In general this command is supposed to use the CFLAGs- and LDFLAGS-
# related variables (OC_CFLAGS and OC_LDFLAGS for ocaml-specific
# flags, CFLAGS and LDFLAGS for generic flags chosen by the user), but
# at the moment they are not taken into account on Windows, because
# flexlink, which is used to build executables on this platform, can
# not handle them.
```

I’ve discovered a temporary workaround but I’m not sure if it’s the "proper" one, so to speak. Some other environment variables are changed specifically for the flexlink test so they are saved before the test and reset to their saved values once the test is over. However, CFLAGS remains unchanged throughout this. 
```
  saved_CC="$CC"
  saved_CFLAGS="$CFLAGS"
  saved_CPPFLAGS="$CPPFLAGS"
  saved_LIBS="$LIBS"
  saved_ac_ext="$ac_ext"
  saved_ac_compile="$ac_compile"
  # Move the content of confdefs.h to another file so it does not
  # get included
  mv confdefs.h confdefs.h.bak
  touch confdefs.h
----------(the test)----------
  # Restore the content of confdefs.h
  mv confdefs.h.bak confdefs.h
  ac_compile="$saved_ac_compile"
  ac_ext="$saved_ac_ext"
  CPPFLAGS="$saved_CPPFLAGS"
  CFLAGS="$saved_CFLAGS"
  CC="$saved_CC"
  LIBS="$saved_LIBS"
```
so I’ve currently worked around this by clearing the CFLAGS variable between the save and the test, which shouldn’t be harmful since it gets restored in a couple lines or so, and after this change everything builds smoothly.
```
     CC="$flexlink -chain $flexdll_chain -exe"
     LIBS="conftest2.$ac_objext"
     CPPFLAGS="$internal_cppflags $CPPFLAGS"
+    CFLAGS=""
     cat confdefs.h - <<_ACEOF >conftest.$ac_ext
 /* end confdefs.h.  */
 int main() { return 0; }
```

**Comment by nojb** [comment]
Thanks for the report. I noticed this as well and was meaning to make an issue about it. It can also be reproduced by using the `-ccopt` flag in `ocamlopt`: the arguments are passed on to `flexlink` which doesn't seem right.

cc @dra27 @shindere

**Comment by dra27** [comment]
`CFLAGS` is only passed to flexlink there by mistake. I have a medium-term plan to stop using the "flexlink as a linker" approach (cf. the horrors in #10413), but in the immediate-term, your fix is the one to do, and I've opened a PR with it, thanks!

**Comment by purplearmadillo77** [comment]
Great, thanks for the quick work and the update!

**Comment by shindere** [comment]
David Allsopp (2022/06/29 06:59 -0700):
> `CFLAGS` is only passed to flexlink there by mistake. I have a
> medium-term plan to stop using the "flexlink as a linker" approach
> (cf. the horrors in #10413),

This will be a more than significant simplification, as far as our build
system is concerned, so I am looking towards this with delight!

> but in the immediate-term, your fix is
> the one to do, and I've opened a PR with it, thanks!

Am I correct that it's #11373 you are referring to?

Just to make sure the PR and the issue are properly linked, so that the
merge of the PR will remind us to also close this issue, which could
perhaps be mentionned in the PR's Changes entry, actually.
