### ISSUE TITLE
master (5.00) fail to build with clang 14/13/9

### ISSUE THREAD

**Issue by Et7f3** [ocaml/ocaml#11376]
```shell
$ make
clang -c -O2 -fno-strict-aliasing -fwrapv -pthread -g -Wall -Werror -fno-common -ffunction-sections  -I./runtime  -D_FILE_OFFSET_BITS=64  -DCAMLDLLIMPORT= -DNATIVE_CODE -DTARGET_amd64 -DMODEL_default -DSYS_linux -fPIC -DCAMLDLLIMPORT=  -o runtime/sak.o runtime/sak.c
clang-14: error: argument unused during compilation: '-fno-strict-overflow' [-Werror,-Wunused-command-line-argument]
Makefile:1003: .dep/runtime/signals_nat.npic.d: No such file or directory
make: *** [Makefile:807 : runtime/sak.o] Erreur 1
```

It seem than in clang 14/13/9 `-fwrapv` is only a link flag. because the same command without `-c` work fine.

I just tested random version of clang to test if it is a change in clang behavior.

Tested version:
clang 14.0.1 (latest is 14.0.6 but didn't see commit in changeling about this issue)
clang 13.0.1
clang 9.0.1

I built with nix but the failure should be more general.

As convenience (you can still get another clang14 from your distro) shell.nix to drop inside src:
```nix
let
  pkgs = import <nixpkgs> {};
  mkShell = pkgs.mkShell.override { stdenv = pkgs.llvmPackages_14.stdenv; };
in mkShell {
  name = "ocaml";
}
```

On MacOs clang is not upstream clang but a apple fork so this might explain it was unreported and not catched by CI.

I removed the flag `-fwrapv` and it compile fine but some tests failed.

```
 ... testing 'forbidden.ml' with 1 (native) Timeout expired, killing all child processes
Process 382032 got signal 9(Killed), no core dumped
=> failed (Running program /home/Et7f3/rush1/ocaml/testsuite/_ocamltest/tests/memory-model/forbidden/ocamlopt.byte/forbidden.opt without any argument: command
/home/Et7f3/rush1/ocaml/testsuite/_ocamltest/tests/memory-model/forbidden/ocamlopt.byte/forbidden.opt
failed with exit code -9)
 ... testing 'forbidden.ml' with 2 (bytecode) Timeout expired, killing all child processes
Process 383544 got signal 9(Killed), no core dumped
=> failed (Running program /home/Et7f3/rush1/ocaml/testsuite/_ocamltest/tests/memory-model/forbidden/ocamlc.byte/forbidden.byte without any argument: command
/home/Et7f3/rush1/ocaml/testsuite/_ocamltest/tests/memory-model/forbidden/ocamlc.byte/forbidden.byte
failed with exit code -9)
```

I hit ctrl+C.

**Comment by xavierleroy** [comment]
> I just tested random version of clang to test if it is a change in clang behavior.
> Tested version:
> clang 14.0.1 (latest is 14.0.6 but didn't see commit in changeling about this issue)
> clang 13.0.1
> clang 9.0.1

What was the result of these tests?

https://clang.llvm.org/docs/ClangCommandLineReference.html lists `-fwrapv` as supported.

Could this be a recently-introduced bug in clang?  It doesn't agree with its documentation.

**Comment by Et7f3** [comment]
It doesn't compile. I tested without the option only with clang14

**Comment by dra27** [comment]
I'm sorry if I'm missing something obvious, but why is the conversation about `-fwrapv` when the error message from clang is about `-fno-strict-overflow`? If I configure with `CC="clang -fno-strict-overflow"` then I can get this build failure too.

I don't know enough about nix, but this seems to be something that gets added - cf. https://github.com/NixOS/nixpkgs/search?q=strictoverflow

**Comment by xavierleroy** [comment]
Indeed, as far as we know, `-fwrapv` is both necessary and sufficient to avoid over-optimizations in GCC and Clang.  But from the report it looks like `clang -fwrapv` (without `-fno-strict-overflow`) causes an error about `-fno-strict-overflow`, which would be a Clang problem for sure.

**Comment by xavierleroy** [comment]
I confirm that the Git sources (trunk) compile and test fine with clang-13 on Ubuntu (CC="clang-13") but fail with the reported error if configured with CC="clang-13 -fno-strict-overflow".  

I'm closing this report, as it doesn't appear to be an issue with OCaml.
