### ISSUE TITLE
opam switch create 4.11.1 failed

### ISSUE THREAD

**Issue by jeremydaw** [ocaml/ocaml#11371]
trying command opam switch create jun22 4.11.1
as per coq documentation at https://coq.inria.fr/opam-using.html
I got the following error which asks me to submit a bug report

<><> Error report <><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
+- The following actions failed
| - build ocaml-base-compiler 4.11.1
+- 
+- The following changes have been performed (the rest was aborted)
| - install base-bigarray base
| - install base-threads  base
| - install base-unix     base
+- 

<><> ocaml-base-compiler.4.11.1 troubleshooting <><><><><><><><><><><><><><><><>
=> A failure in the middle of the build may be caused by build parallelism
      (enabled by default).
      Please file a bug report at https://github.com/ocaml/ocaml/issues
=> You can try installing again including --jobs=1
      to force a sequential build instead.

**Comment by shindere** [comment]
Did you try the `--jobs=1` recommended by opam?

Did that solve your problem?

**Comment by Octachron** [comment]
It is in fact rather unlikely that this an issue with parallelism (the warning is over-cautious).

@jeremydaw do you have a full log of the build?
