### ISSUE TITLE
Add a ocamlthanks ?

### ISSUE THREAD

**Issue by Et7f3** [ocaml/ocaml#11375]
Perl has perlthanks that send mail to thanks maintainer and gather some Information on the platform. Do you want that or find it mostly useless ?

**Comment by Octachron** [comment]
I am not sure I follow what would be the  benefits of an ocamlthanks program compared to the current bugtracker. Since no one reacted, I am closing the issue. Don't hesitate to relaunch the discussion on discuss.ocaml.org if you are still interested by the idea.
