### ISSUE TITLE
type of expression in signature definition ?

### ISSUE THREAD

**Issue by craff** [ocaml/ocaml#11428]
Hello,

In a code using a lot first class modules, I am in need for a feature that would be similar to "module type of", but for values. 
I only need the following:

module type A = sig
  val x : type of B.y
  val y : type of C.y list
end

- type of is only followed by an access to a struct field
- it if only usex in the type of a value inside a signature (I would prefer if it was possible to use it inside a type expression,
  but would be ok if it is only at root position, the definition of y above being then forbidden)

Cheers,
Christophe

**Comment by Octachron** [comment]
If the issue is that you have a complex inferred type that you want to lift to the module level, first-class modules are enough:
```ocaml
module type T = sig type t end
type 'a ty = (module T with type t = 'a)
let type_of (type a) (x:a): a ty = (module struct type t = a end)
module Type_of_b = (val type_of B.y)
```

**Comment by craff** [comment]
Thanks! I was already aware of the very nice

`type` 'a ty = (module T with type t = 'a)`

But I dit not think that it would give the definition of type_of you propose! 

It allows me to write
```
module type T = sig type t end
type 'a ty = (module T with type t = 'a)
let type_of (type a) (x:a): a ty = (module struct type t = a end)

let x = 3

module Tx = (val type_of x)

module type A = sig
  val x : Tx.t
end
```

But I would prefer not to have do define the module Tx at toplevel and write
```
module type A = sig
  val x : (val type_of x).t
end
```

So may be my feature wish should be rewritten as "allow (val ...) in module path instead of module expression ?
But this looks rather problematic, as it would bring evaluation in Longident.t in particular and in type 
in general which is not possible.

May be the definition of type_of somewhere in the stdlib ?

**Comment by craff** [comment]
And by the way, I need that to write a ppx and at this level, I can not write the type of the value.
