### ISSUE TITLE
ppx with type

### ISSUE THREAD

**Issue by craff** [ocaml/ocaml#11447]
I propose a new kind of ppx extension where the type would be known. The idea is as follows:

- ppx extensions that need type information require two AST tranformations to be declared per extention.
- we add new nodes Pexp_request_type Pmod_request_type, similar to coerce node, but with a pointer that can store the infered type
  of the expression/module at type-checking
- allow two stages for ppx interpretation as follows:
  - 1st stage produces an AST with the above node that is used in type-checking to store the inferred type. 
     This typed AST is thrown away. This first stage is run only if ppx extension that needs type information are registered.
  - 2nd stage produce another AST, using the type information registered at first stage. The type information should allow
    access to type, module type and class type definitions that appear in the infered type for the node.

This seems 
- not too complicated to implement (compared to a ppx evaluation during type checking), 
- it ensures that all possible type information is available when running the second stage.
- it allow to produce simple AST at first stage that gather only the needed type information.

**Comment by nojb** [comment]
Hello, this sounds interesting, but I don't see the full picture. Could you give some sort of specification of the feature (independent of the implementation)? A minimal example would be great as well.

**Comment by craff** [comment]
The application I have in mind would be to infer the sql type from ocaml type in some data base interface I am currently writing. It would be a bit long to describe.

 More generally, when writing a ppx I am always thinking "how is would be nice if I would knew the type of x" or more often "I need to know the signature of this module". This proposal would allow to do that. 

I have another nice minimal example. Consider an extension   f[%poly Default] always applied to an identifier.

- first stage  it is replaced a function of type `type a.a -> a -> a with a node to remember the type `a`.
  typycally `f = (fun x y -> let _ = [%e Pexp_memo_type (x, ty_ptr)] in let _ = x = y in x)`
  We could imagine definitions in ast_helper to ease the writing of such fake function.
  Here `ty_ptr` would hold the inferred type for `a` after stage 1

- second, if the type of `a` is `M.t` for some module `M` which have a `M.f` function, then we replace the node by `M.f`.
  otherwise we use `Default.f`. This requires a search function to find all possible `M` from the inferred type for `a`.

I think we could change the interpretation of `+` in OCaml to be `(+)[%poly Stdlib]` and it probably would no break existing code
and allow to use `+` polymorphically. This is not my first intended use case, but it show that my proposal has some nice 
applications.

Remark: the above example could probably be used to add lists or arrays if modules like `Array(Float)` or `List(Float)` are available in the environment, to provide the module M with M.t = float array and M.add. 

I think this is quite controlable (nothing happens as long as the needed module are not in the environment). So your + symbol
in a file is interpreted only if something allows for it in your file.

**Comment by johnyob** [comment]
It might be worth checking out @EduardoRFS's typed-ppxlib: https://github.com/EduardoRFS/typedppxlib for something like this. It exposes type checker internals, but would definitely get the job done for your application.
