### ISSUE TITLE
Rename registered named values `Pervasives.*` to `Stdlib.*`

### ISSUE THREAD

**Issue by favonia** [ocaml/ocaml#11453]
When checking `register_named_value`, I realized `Pervasives.array_bound_error` and `Pervasives.do_at_exit` are still registered with the `Pervasives` prefix. I wonder if OCaml 5.0 provides a good opportunity to rename them to `Stdlib.array_bound_error` and `Stdlib.do_at_exit`. A standard library replacement that strives to work with OCaml 4 and 5 can register the values under both names.

PS: I tried to find user C code on GitHub that retrieves these values but to no avail; it seems many code snippets I found are for testing the OCaml compiler itself, which would have to be changed to use "Stdlib". However, personally I think it is expected to update the testcases for a compiler after a major release.

**Comment by dra27** [comment]
(as a largely irrelevant aside, I'm not sure why you changed the title from the _correct_ `Pervasives.*` to the incorrect `Pervasive.*`?)

I'm in two minds - on the one hand, it's inconsistent; on the other it's just a quirky little inconsistency in (as far as I know) a much less crowded namespace than the toplevel module namespace. I'm leaning towards suggesting we leave it as it is on the basis that the deprecation of the `Pervasives` module had the full power of the type checker behind it, but this is just a string. If there's any code out there (including non-public code) which actually uses either of those from C (especially, I guess `Pervasives.do_at_exit`) it could be really subtle to identify the problem?

**Comment by favonia** [comment]
As a "workaround", the values can be registered under both names for compatibility. Personally I can't form any strong opinion because it doesn't affect any of my code. Was bringing it up only because OCaml 5.0.0 seems to be the best timing.

> (as a largely irrelevant aside, I'm not sure why you changed the title from the _correct_ `Pervasives.*` to the incorrect `Pervasive.*`?)

Thanks. Was confused by #11454. :sweat_smile:

**Comment by dra27** [comment]
> As a "workaround", the values can be registered under both names for compatibility.

If there’s one thing we should learn from the various deprecations which we have already “completed” for 5.0, it’s that we need better (more detailed) stories than this 🙂 The problem here is what defines the point where we can get rid of the old name (i.e. remove the compatibility), because otherwise we end up with two names and a fear that we can never get rid of the old one!
