### ISSUE TITLE
Confusing error message when applying a functor to an empty structure

### ISSUE THREAD

**Issue by let-def** [ocaml/ocaml#11450]
This simple toplevel session results in an error message that is not very helpful:
```
# module X (P : sig type t end) = struct end;;
# module Y = X(struct end);;
Error: The functor was expected to be applicative at this position
```

Passing anything else than an empty structure lead to a better message. For instance a useless attribute:
```
# module Y = X(struct [@@@foo] end);;
Error: Modules do not match: sig end is not included in sig type t end
     The type `t' is required but not provided
```

This happens because `X()`, the syntax for applying generative functors, translates to `X(struct end)`:
- in the parser: [parser.mly#L1329](https://github.com/ocaml/ocaml/blob/38a9884/parsing/parser.mly#L1329)
- in the typechecker, by directly checking syntactic equality: [typing/typemod.ml#L2271](https://github.com/ocaml/ocaml/blob/38a9884/typing/typemod.ml#L2271)

This makes the implementation simpler at the cost of this slightly worse error message.
Should we try to address this?

**Comment by gasche** [comment]
Why not? We could use a dedicated parsetree node for `()`.

**Comment by Octachron** [comment]
Another option would be to have a node for the generative application `F()` itself.

**Comment by gasche** [comment]
Why not, but in either case we may need a symmetric construct for generative abstraction.

Having `()` as an module argument makes it slightly more convenient to gather all arguments in a mixed-mode n-ary application `F(A)(B)()(C)`.

**Comment by Octachron** [comment]
The symmetric construct already exists in fact: https://github.com/ocaml/ocaml/blob/trunk/parsing/parsetree.mli#L819 .

**Comment by xavierleroy** [comment]
> The symmetric construct already exists in fact

What's the problem, then?  The Parsetree construct is not generated by the parser?  The elaborator mishandles the Parsetree construct?

**Comment by gasche** [comment]
There is a `Unit` construct in the AST in the syntactic category of formal parameters (for abstractions `module F () = ...`), but not in the category of module expressions (for applications `F ()`).

**Comment by let-def** [comment]
I went this way in this branch: https://github.com/let-def/ocaml/tree/explicit-generative-application

I chose to just use an option, I can make a more specific type if people prefers:
```ocaml
(* Parsetree *)
  | Pmod_apply of module_expr * module_expr option
...
(* Typedtree *)
  | Tmod_apply of module_expr * (module_expr * module_coercion) option
```

Right now we silently accept an empty module argument where unit is expected:
```
module F() = ...
module X = F(struct end)
```
We can keep doing that, or warn that a `()` would be more appropriate.

**Comment by gasche** [comment]
I'm worried that the approach of changing the type of `Pmod_apply` may be sensibly more invasive in parsetree-consuming codebases than the approach of adding a new `Pmod_unit` constructor. Unless there is a strong design argument to prefer one approach over the other, then going for the less-code-to-fix-in-the-ecosystem route sounds better. Would you actually have the time of trying that other one and comparing the diff on ocamldoc for example?)

**Comment by gasche** [comment]
Otherwise:
- Great, thanks for doing the work!
- Please send a PR ?
- No strong opinion on your question of how to handle `(functor () -> ...) (struct end)`, but I think indeed that a warning would make sense.

**Comment by let-def** [comment]
Ok, I will do that on Tuesday.
