### ISSUE TITLE
online OCaml manual: there should be an easy way to get a fixed-version URL

### ISSUE THREAD

**Issue by gasche** [ocaml/ocaml#11458]
Suppose I'm browsing a random page of the OCaml manual

  <https://v2.ocaml.org/manual/types.html#sss:typexpr-sharp-types>

and I want to refer other people to it. The URL above I found through my search engine does not mention a specific OCaml version, so it is not stable, it may be dead or contain different content next time we look at it.

Feature wish: it should be easy to get a fixed-version equivalent of the same URL, just like github offers an interface to get a "permalink" from the source view of a versioned file.

There is a version name in the top-left corner of the page that says "Version 4.14". I would expect that clicking on it brings me exactly to such a fixed-version version of the page, but in fact it brings to <https://ocaml.org/releases/> which is certainly not what I'm looking for.

Note: this would be easier if the URL scheme was regular among "current versions" and "fixed version" manual pages. Currently we have:

- <https://v2.ocaml.org/manual/attributes.html>
- <https://v2.ocaml.org/releases/4.12/manual/attributes.html>

so there is no way to guess the fixed-version URL from the current-version URL. Instead we could have

- <https://v2.ocaml.org/releases/latest/manual/attributes.html>
- <https://v2.ocaml.org/releases/4.12/manual/attributes.html>

where I could easily guess that replacing "latest" by a version number will give me what I want.

Edit: I cross-referenced this issue on the ocaml.org bugtracker: https://github.com/ocaml/ocaml.org/issues/534

**Comment by xavierleroy** [comment]
I was about to redirect this PR to ocaml/ocaml.org.  I support the request, but there's nothing ocaml/ocaml can do about it.  Please continue the discussion at https://github.com/ocaml/ocaml.org/issues/534 .
