### ISSUE TITLE
Temporary asm file not deleted

### ISSUE THREAD

**Issue by xavierleroy** [ocaml/ocaml#11471]
When running the test https://github.com/ocaml/ocaml/blob/trunk/testsuite/tests/tool-ocamlopt-save-ir/start_from_emit.ml , a temporary asm file /tmp/camlasmXXXX.s is not removed.  

This is a mild problem for CI machines (where /tmp gets cluttered by temp files eventually), and may indicate an oversight in the implementation of the `-save-ir-after` and `-stop-after` options.

Cc: @gretay-js

**Comment by xavierleroy** [comment]
Ping @gretay-js

**Comment by nojb** [comment]
Fix in #11850
