### ISSUE TITLE
Auto format OCaml codes of stdlib and etc

### ISSUE THREAD

**Issue by sina-devel** [ocaml/ocaml#11477]
We can use `ocamlformat` to automatically format OCaml codes in a consistent style.

**Comment by dra27** [comment]
Quoting [CONTRIBUTING.md](https://github.com/ocaml/ocaml/blob/trunk/CONTRIBUTING.md#coding-guidelines), "there are no strongly enforced guidelines specific to the compiler" - this would be a huge change, even if it were only applied to the Standard Library to begin with.

Even with an agreement from all core developers to do this, it could create a rebasing disaster for long-lived forks (at the very least, it becomes quite hard, especially if trying to maintain commit history while rebasing) and it would basically close all old PRs[^1]. We're also not in the greatest place to have working on the compiler _require_ a tool written in OCaml, though that's a much a smaller issue.

Overall, I think the cost of doing this far outweighs the benefit - I'd move to close this, I'm afraid.

[^1]: granted, that's not necessarily a bad thing!

**Comment by hhugo** [comment]
Note that there exists tooling to rebase commits across formatting changes. In particular, see https://github.com/hhugo/merge-fmt

**Comment by xavierleroy** [comment]
I agree that the cost outweighs the benefit.  Closing.
