### ISSUE TITLE
random order of modules in stdlib index [documentation]

### ISSUE THREAD

**Issue by sanette** [ocaml/ocaml#11478]
The landing page for OCaml API documentation presents a list of modules in a (seemingly?) random order,
see https://v2.ocaml.org/api/index.html

This has been reported several times in the forum as a weakness of the documentation, and I can understand this. I guess it should not be too difficult to solve.
By the way, others have reported that the "Camlinternal" modules could be hidden from that list.

The page is built from the file `manual/src/htmlman/libref/index.html`, which is generated, IIUC, by this Makefile
https://github.com/ocaml/ocaml/blob/f40bc2697234e075eb69294e2e2e19a790de8aba/api_docgen/odoc/Makefile#L139-L144

Restoring an alphabetical order (and hiding the "Camlinternal" modules) can certainly be done at the level of the `webman` (html post-processing) but maybe it would make more sense to modify the `htmlman/libref` index file via the Makefile.

**Comment by shindere** [comment]
I think @Octachron may be the person who can best deal with the
situation.

**Comment by xavierleroy** [comment]
Ping @Octachron .

**Comment by sanette** [comment]
fixed by https://github.com/ocaml/v2.ocaml.org/pull/1631

**Comment by Octachron** [comment]
Thanks for triaging the issue!
