### ISSUE TITLE
The option `-output-complete-obj` fails to create a shared library on `amd64` architecture

### ISSUE THREAD

**Issue by tournev** [ocaml/ocaml#11480]
When using `-output-complete-obj` to create a shared library on `amd64` architecture, `ocamlopt` seems to include code from `$(ocamlopt -where)/libasmrun.a` in the generated object file. This file is non-PIC, so the linker fails to create the shared library.

Example:
```
$ ocamlopt -output-complete-obj -o test.so test.ml
/usr/bin/ld: /home/vincent/.opam/default/lib/ocaml/libasmrun.a(startup_nat.n.o): warning: relocation against `caml_system__code_end' in read-only section `.text.caml_startup_common'
/usr/bin/ld: /home/vincent/.opam/default/lib/ocaml/libasmrun.a(roots_nat.n.o): relocation R_X86_64_PC32 against symbol `caml_frame_descriptors_mask' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
File "caml_startup", line 1:
Error: Error during linking (exit code 1)
```
The content of `test.ml` is not important, it can even be empty.

We get the same error when asking `ocamlopt` to create an object file, and then including this file in a shared library:
```
$ ocamlopt -output-complete-obj -o test-runtime.o test.ml
$ clang -shared -o libtest.so test-runtime.o 
/usr/bin/ld: test-runtime.o: warning: relocation against `caml_system__code_end' in read-only section `.text.caml_startup_common'
/usr/bin/ld: test-runtime.o: relocation R_X86_64_PC32 against symbol `caml_cleanup_on_exit' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: bad value
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

A solution is to use `-output-obj` and then manually include the needed OCaml runtime functions in the dynamic library, from the file `$(ocamlopt -where)/libasmrun_pic.a`, which is PIC. I didn't find a way to make `ocamlopt -output-complete-obj` use the OCaml runtime code from `libasmrun_pic.a`, but maybe there is something that I don't understand about it.

An other solution is to replace the content of the file `libasmrun.a` with `libasmrun_pic.a`:
```
$ cd $(ocamlopt -where)
$ cp libasmrun_pic.a libasmrun.a
```
Then both above examples work fine.

I had this issue when trying to create a shared library from OCaml code, to then be able to call this OCaml code with an other language, by loading this shared library at runtime.  I use intermediate C code to create functions which call the OCaml code, with `caml_callback`. This is why I need the runtime functions, such as `caml_startup`.

OCaml version:
```
$ ocamlopt --version
4.14.0
```

**Comment by nojb** [comment]
You should use the `-runtime-variant _pic` flag to make the compiler use the right runtime for a shared library.

**Comment by tournev** [comment]
Thank you for your answer. It doesn't fail to create the shared library with `-runtime-variant _pic`.

But is the error above, when using `-output-complete-obj something.so` without `-runtime-variant _pic`, the intended behavior ?

Maybe it would be better to fail with a cleaner error message, such as `The runtime variant _pic is needed to create a shared library (try -runtime-variant _pic).` ? Or maybe this option should be automatically used in this case ?
