### ISSUE TITLE
In OCaml 5.0.0 alpha 1, ocamlmktop generates an extra directory by default

### ISSUE THREAD

**Issue by johnwhitington** [ocaml/ocaml#11495]
MacOS 12.5, OCaml version 5.0.0~alpha1.

After using `ocamlmktop`, in addition to, say, `camlpdf.top`, I get a new directory `camlpdf.top.dSYM` which has an `Contents/Info.plist` and, another file `Contents/Resources/DWARF/camlpdf.top` of this type:

```
$ file camlpdf.top
camlpdf.top: Mach-O 64-bit dSYM companion file arm64
```

This does not happen in 4.14.0. Is this debug output intentionally the default in 5.0? If so, it's just something for me to add to `make clean` and something for other build systems to be aware of. If it's not intentionally the default it may need fixing. Of course, the actual files produced will be different on each OS.

**Comment by xavierleroy** [comment]
I tried to reproduce on my Mac but could not.  @damiendoligez @garrigue other-mac-users: can you reproduce?

I suspect this could be caused by an environment variable that happens to be set in your environment.  Could you run "printenv" and eyeball the output?

**Comment by johnwhitington** [comment]
Here are steps to reproduce:

```
opam switch create 5.0.0~alpha1
eval $(opam env)
opam install ocamlfind
git clone https://github.com/johnwhitington/camlpdf.git
cd camlpdf
make
make clean
git status
```

This gives:

```
On branch master
Your branch is up to date with 'origin/master'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	camlpdf.top.dSYM/

nothing added to commit but untracked files present (use "git add" to track)
```

Here is the output of printenv:

```
$ printenv
CAML_LD_LIBRARY_PATH=/Users/john/.opam/5.0.0~alpha1/lib/stublibs:/Users/john/.opam/5.0.0~alpha1/lib/ocaml/stublibs:/Users/john/.opam/5.0.0~alpha1/lib/ocaml
TERM_PROGRAM=Apple_Terminal
SHELL=/bin/bash
TERM=xterm-256color
TMPDIR=/var/folders/n5/fqmw3hhj3159kjvdwfq6kq0r0000gn/T/
TERM_PROGRAM_VERSION=445
OLDPWD=/Users/john/repos/temp
OPAM_SWITCH_PREFIX=/Users/john/.opam/5.0.0~alpha1
TERM_SESSION_ID=39965191-E03D-4483-87C7-A148EE7C9236
OCAML_TOPLEVEL_PATH=/Users/john/.opam/5.0.0~alpha1/lib/toplevel
USER=john
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.3iT50WRgaF/Listeners
BASH_SILENCE_DEPRECATION_WARNING=1
PATH=/Users/john/.opam/5.0.0~alpha1/bin:/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/usr/local/share/dotnet:/opt/X11/bin:~/.dotnet/tools:/Library/Apple/usr/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands
LaunchInstanceID=73EB235E-EBA9-4EFA-83A5-870510894799
__CFBundleIdentifier=com.apple.Terminal
PWD=/Users/john/repos/temp/camlpdf
JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk-17.0.2.jdk/Contents/Home
LANG=en_GB.UTF-8
XPC_FLAGS=0x0
XPC_SERVICE_NAME=0
SHLVL=1
HOME=/Users/john
LOGNAME=john
DISPLAY=/private/tmp/com.apple.launchd.8zT8eUpliB/org.xquartz:0
SECURITYSESSIONID=186b1
_=/usr/bin/printenv
```

I am using up-to-date MacOS Monterey on ARM and up-to-date XCode.

**Comment by xavierleroy** [comment]
Thanks for the repro.  @damiendoligez could you possibly look into this?

**Comment by dbuenzli** [comment]
FWIW I'm getting a spurious untracked `ocamltest/ocamltest.dSYM/` when I build the compiler.

macOS 12.6, x86_64, xcode 14.0

**Comment by johnwhitington** [comment]
Still present in 5.0.0~beta1.

**Comment by shindere** [comment]
My understanding of
`https://stackoverflow.com/questions/17743993/dsym-files-generated-from-comm3/dsym-files-generated-from-command-line-mac`
is that these files and directories are produced as soon as one compiles
C files with `-g` and contain debugging symboles. If that's the case
perhaps the best thing we can do is to add appropriate patters to
`.gitignore` and modify `make clean` to make sure the files and
directories in question do get removed?

**Comment by johnwhitington** [comment]
@shindere But this doesn't explain why this is new behaviour in OCaml 5.

**Comment by dra27** [comment]
This looks like a bug in https://github.com/ocaml/ocaml/pull/11240/commits/6a2724edc180673f629e2a380c80fef8450bb663 is to blame here. The intent of that commit is to ensure that all the C files in the system are compiled with `-g`, but the `-g` flag "leaks" into `Config.mkexe`. One can see that on branch 4.14, `./configure && make -j utils/config.ml` that `Config.mkexe` does _not_ include `-g` but on 5.0 it does.

That affects bytecode builds using `-custom` - `ocamltest` is compiled with `-custom` (which confirms @dbuenzli's observation) and as far as I can see from from camlpdf's sources, since `NO_CUSTOM` is _not_ defined, `OCamlMakefile` also builds with `-custom` which I think includes `camlpdf.top`.

**Comment by shindere** [comment]
I believe that https://github.com/ocaml/ocaml/pull/11701 should fix this ussue. Coudl someone with access to MacOS double-check, please?

**Comment by johnwhitington** [comment]
Happy to test this, but what is the modern way to check out an opam switch with a PR? The instructions here seem out of date:

https://github.com/ocaml/ocaml-pr-repository

**Comment by nojb** [comment]
> Happy to test this, but what is the modern way to check out an opam switch with a PR? The instructions here seem out of date:
> 
> https://github.com/ocaml/ocaml-pr-repository

See https://github.com/ocaml/ocaml/blob/trunk/HACKING.adoc#testing-with-opam

**Comment by johnwhitington** [comment]
Thanks. I have tried:

```
opam switch create dsym --empty
opam pin add ocaml-variants.5.1.0+trunk git+https://github.com/shindere/ocaml/tree/fix-mkexe-exp
```

But no luck. Google does not reveal how to get a better URL for the `fix-mkexe-exp` branch, and clicking on the "Code" button does not include it in the URL either.

**Comment by shindere** [comment]
Perhaps try

git+https://github.com/shindere/ocaml#fix-mkexe-exp

(found on the man page for opam pin)

**Comment by johnwhitington** [comment]
Thanks. For reference, the right commands were:

```
opam switch create dsym --empty
opam pin add ocaml-variants.5.1.0+trunk git+https://github.com/shindere/ocaml.git#fix-mkexe-exp
```

However, due to poor hotel Wifi, I suspect, it failed every time after a few minutes with:

```
"/usr/bin/git fetch -q" exited with code 128 "error: 3264 bytes of body are still expected"
```

So I'm afraid someone else will have to verify this patch works.

**Comment by shindere** [comment]
Well the patch is small so you could as well download it and create a
local branch with it, on top of the 5.0 branch for instance, and then
you could pin to that.

**Comment by johnwhitington** [comment]
The patch works. The dsym directory is no longer created.

**Comment by shindere** [comment]
John Whitington (2022/11/05 06:23 -0700):
> The patch works.

Ah cool! Thanks!

And congrats to @dra27 who understood where the problem was coming from.
