### ISSUE TITLE
Bytes.escaped unsafe under concurrent modification

### ISSUE THREAD

**Issue by jmid** [ocaml/ocaml#11508]
There's a safety issue with the current definition of `Bytes.escaped`:
https://github.com/ocaml/ocaml/blob/7412593a42f0e6a8c274c0cb7bf22a4c3646abd0/stdlib/bytes.ml#L170-L208

`Bytes` operations should not crash under concurrent usage as documented in https://github.com/ocaml/ocaml/pull/11237.
However under concurrent modification of the underlying data structure, the above may result in out-of-bounds `unsafe_set` if more escapable `char`s are present since the target length `n` was calculated.

Here's a test case to trigger it:
```ocaml
(*TEST*)

let buf = Bytes.make 128 '0'

let fn_mutate s =
  let c = if Random.bool () then '0' else '\n' in
  Bytes.fill s 0 127 c

let fn_escape s =
  let s' = Bytes.escaped s in
  assert ((Bytes.length s') <= 4*(Bytes.length s))

let _ =
  let iter = Atomic.make 0 in
  let d_mutate = Domain.spawn (fun () ->
        while Atomic.get iter < 100_000; do fn_mutate buf done; ) in
  let d_escape = Domain.spawn (fun () ->
        while Atomic.get iter < 100_000; do
          fn_escape buf; ignore (Atomic.fetch_and_add iter 1) done; ) in

  ignore (Domain.join d_mutate);
  ignore (Domain.join d_escape)
```

```
$ ocamlopt -o /tmp/bytescrash.exe /tmp/bytescrash.ml 
$ /tmp/bytescrash.exe 
Fatal error: allocation failure during minor GC
Aborted (core dumped)
```

I'm creating a issue rather than a PR, to discuss the preferred fix.
- one option is to make an early  `copy` of `s` which will prevent concurrent changes to the copy
- another option is to switch from `unsafe_set` to safe `set`
- a third option is to bound writing to be within the bounds of the output buffer
- ...

This was a team effort: @ctk21 identified the cause and wrote the independent test case illustrating it. @haesbaert suggested an elegant fix. I just made it crash with a random test... :sweat_smile:

**Comment by gasche** [comment]
Two remarks on potential solutions:

1. There isn't a way to atomically copy a string, so even the "do a copy first and work from that" approach has an unclear specification in presence of concurrent updates to the string.

2. If we try to do without a copy, with our own bound checking instead of using `String.set`, we still need a check in the common case of character written directly; we can only avoid extra bound checks in the case where the characters are escaped. I think this means in practice that, unless we copy, just switching to String.set is reasonable.

Despite (1), I still think that the best fix for now is to do a copy. It's likely to be the fastest option (but only detailed benchmarking would tell) and it is simple.

**Comment by haesbaert** [comment]
I'd point out that 1.

> Two remarks on potential solutions:
> 
> 1. There isn't a way to atomically copy a string, so even the "do a copy first and work from that" approach has an unclear specification in presence of concurrent updates to the string.
> 2. If we try to do without a copy, with our own bound checking instead of using `String.set`, we still need a check in the common case of character written directly; we can only avoid extra bound checks in the case where the characters are escaped. I think this means in practice that, unless we copy, just switching to String.set is reasonable.
> 
> Despite (1), I still think that the best fix for now is to do a copy. It's likely to be the fastest option (but only detailed benchmarking would tell) and it is simple.

At worst what can happen is that architectures with weakly ordered stores could see a "future character" be updated before, at least amd64 is guaranteed to see "one truthful representation of the string at some point in time".
I don't think we should attempt to guarantee anything more.

**Comment by haesbaert** [comment]
Just a small note, one can argue that using the "safe_set" and raising an exception is better behavior since it forces the user to address the issue instead of him trying to figure how his escaped string got funky.

**Comment by gasche** [comment]
Yes, but with the current implementation the exception would only be called in certain scenarios of concurrent updates, far from all of them. (We only record the total size, so many changes would pass under the radar.) I don't think *unreliable* exceptions are a clear improvement, especially when they come with a noticeable performance cost.

**Comment by gasche** [comment]
I posted a PR with the `copy` approach as #11509.
