### ISSUE TITLE
Thread-unsafety in `caml_make_float_vect`

### ISSUE THREAD

**Issue by gadmm** [ocaml/ocaml#11504]
The static initialization code below appears to be thread-unsafe in the presence of multiple domains:

https://github.com/ocaml/ocaml/blob/712ee62e5abde7d7871f6345c1d2b917c6380596/runtime/array.c#L255-L259

**Comment by xavierleroy** [comment]
Well spotted.  Even without domains, this code is pretty bad.  (The initializing float can be allocated statically.)
