### ISSUE TITLE
`[@deprecated_mutable]` is broken

### ISSUE THREAD

**Issue by ccasin** [ocaml/ocaml#11516]
The `deprecated_mutable` attribute is currently broken.  For example, the following program does not result in a warning, but did in OCaml 4.09.1:

```ocaml
module M = struct
  type t = { mutable x : int [@deprecated_mutable] }
end

let foo : M.t = {M.x = 5}

let () = foo.M.x <- 42
```

It looks like the check for the warning was accidentally removed in #2127.

I considered making a new PR to fix the warning, which is simple.  But another option is to just remove the attribute - it's been broken since 2019 and nobody seems to have noticed.

**Comment by nojb** [comment]
> I considered making a new PR to fix the warning, which is simple. But another option is to just remove the attribute - it's been broken since 2019 and nobody seems to have noticed.

I think this should be fixed, not removed. PR welcome!
