### ISSUE TITLE
`-strict-formats` by default

### ISSUE THREAD

**Issue by sim642** [ocaml/ocaml#11538]
[As it came up on discuss](https://discuss.ocaml.org/t/format-conversion-doesnt-support-padding/10437/3?u=sim642), both the documentation and implementation of `-strict-formats` claim that the strict behavior is to become the default:
https://github.com/ocaml/ocaml/blob/949e2626c22b5fe8159cb29d47207d5621eabf90/manual/src/cmds/unified-options.etex#L691-L694
https://github.com/ocaml/ocaml/blob/cce52acc7c7903e92078e9fe40745e11a1b944f0/stdlib/camlinternalFormat.mli#L75-L80

The latter comment is 8 years old, so that "next version" being 5.0 would be the perfect opportunity, if still possible.

**EDIT:** Apparently this was supposed to happen in 4.04 but was just forgotten: https://github.com/ocaml/ocaml/pull/514#issuecomment-211414397.

**Comment by nojb** [comment]
Sounds like a good idea to me. @Octachron: if we wanted to do this, would it be possible to get this into 5.0, or should we be thinking of 5.1 instead?

**Comment by Octachron** [comment]
My opinion is that it is too late in the 5.0 cycle to introduce such breaking change, even if they are minor.

Moreover, `dune` uses `-strict-format` by default, thus it is seems quite likely that a significant part of the ecosystem are already using the flag. I fear that the change will end up simplifying the configuration of dune and other build tools at the cost of potentially breaking few out-of-date packages

Overall, I think that the compromise is sensible but it can wait for 5.1 .

**Comment by nojb** [comment]
@sim642 would you like to try making a PR for this change? It should be fairly easy, a "good first issue" :)

**Comment by sim642** [comment]
> Moreover, `dune` uses `-strict-format` by default

That's nice, I wasn't aware.


> @sim642 would you like to try making a PR for this change? It should be fairly easy, a "good first issue" :)

Sure, I can give it a shot sometime.

**Comment by shindere** [comment]
Simmo Saan (2022/09/11 07:02 -0700):
> > Moreover, `dune` uses `-strict-format` by default
>
> That's nice, I wasn't aware.
>
>
> > @sim642 would you like to try making a PR for this change? It should be fairly easy, a "good first issue" :)
>
> Sure, I can give it a shot sometime.

I have just started a PR to stop using `-safe-string` to build the
compiler since it's the default and the only possibility anyway.

Given that this PRand the `-strict-formats` change will touch the same
parts of the code, I think, may I grab the idea and include the fix in
the PR I am working on?

**Comment by sim642** [comment]
> Given that this PRand the `-strict-formats` change will touch the same parts of the code, I think, may I grab the idea and include the fix in the PR I am working on?

Feel free to, I don't mind.

I think there are two levels to this issue though:
1. Just making `-strict-formats` the default, but still allowing `-no-strict-formats` to disable it.
2. Completely removing the legacy behavior as the `fmt_ebb_of_string` comment suggests, which means no `-no-strict-formats` and also affects some `Scanf` thing which also uses that function at runtime (and defaults to the legacy behavior).

**Comment by shindere** [comment]
Simmo Saan (2022/09/11 07:19 -0700):
> Feel free to, I don't mind.
>
> I think there are two levels to this issue though:
> 1. Just making `-strict-formats` the default, but still allowing `-no-strict-formats` to disable it.
> 2. Completely removing the legacy behavior as the `fmt_ebb_of_string`
> comment suggests, which means no `-no-strict-formats` and also affects
> some `Scanf` thing which also uses that function at runtime (and
> defaults to the legacy behavior).

Oh, that' a bit ore abitious than I thought. It may be better t deal
with the two things serarately then.

**Comment by gasche** [comment]
Let's definitely keep `-no-strict-formats` for now, it is simpler and might solve user issues if some show up during the transition. (But when dune enables it by default, it means there are few users not using it already.)
