### ISSUE TITLE
Regression in #show_module_type

### ISSUE THREAD

**Issue by yminsky** [ocaml/ocaml#11533]
The version as of OCaml 4.14 seems useless, as far as I can tell. Here's an example from 4.13.1:

```
# #show_module_type Base.Comparator.S;;
module type S =
  sig
    type t
    type comparator_witness
    val comparator : (t, comparator_witness) Base.Comparator.comparator
  end
```

And here's the same example with 4.14:

```
# #show_module_type Base.Comparator.S;;
module type S = Base.Comparator.S
```

This created regressions in Real World OCaml, which is how I noticed it.

**Comment by gasche** [comment]
The regression was caused by additional strengthening in b44e5fdf70f65a29da53c405f6885fdf5611b362, which is part of #10599.

(Edit: I originally pointed to the parent commit 3fb495f9c3f42c2d56ddfd191a264875293d247b which is a mistake, as it is not the culprit.)

**Comment by yminsky** [comment]
Well, that's a worthy PR to have created this (small) bug.

Perhaps this suggests there should be some more testing of the #show directives? Almost any test at all of #show_module_type would have uncovered this bug.

**Comment by gasche** [comment]
Indeed, I expect that whoever comes up with a fix will add regression tests for #show directives.

**Comment by gasche** [comment]
In fact there is a mildly-interesting reason why our testsuite did not catch it. It seems that, during environment lookup, more strengthening happens on modules or module types that come from other compilation units. The tests for `#show` are in a file that tries to be self-contained, so it shows locally-defined modules and module types which work as expected. The "obvious" fix is to show a module from the stdlib in addition, but those tend to grow over time requiring tedious testsuite promotion. (At least for module types we don't have this problem, `Set.OrderedType` is set in stone as it is used contravariantly.)

**Comment by dbuenzli** [comment]
This has been fixed and can be closed.

**Comment by gasche** [comment]
Thanks!
