### ISSUE TITLE
Installation instructions on website are wrong and don't work

### ISSUE THREAD

**Issue by Sod-Almighty** [ocaml/ocaml#11532]
Your website says that, to install ocaml, I should install opam and then type:

```
opam init
eval `opam env`
opam switch create 4.14.0
```

`opam env` fails with the error `opam: unknown command 'env'.`

`opam switch create 4.14.0` fails with the error `opam: Invalid switch subcommand "create"`

If opam no longer understands these commands, then don't you think you ought to update your instructions? Else nobody will be able to install ocaml. (Me, for example.)

**Comment by gasche** [comment]
What version of `opam` are you using? (`opam --version` will tell you).

> then don't you think you ought to update your instructions? 

Wow.

**Comment by nojb** [comment]
> If opam no longer understands these commands, then don't you think you ought to update your instructions?

It is the opposite, you are using an outdated `opam` that doesn't understand these commands. OPAM 2.0 (released in 2018) should work.

**Comment by Sod-Almighty** [comment]
Version 1.2.2, apparently.

Your instructions don't say anything like "make sure it's version 1.5.1 or greater" or any such thing. It just says "install opam using apt-get". _Which I did._

> Wow

Well? I followed your instructions _to the letter,_ and they didn't work. Of course I'm going to sound unimpressed and a little testy. Either the opam commands are wrong, or the "install opam" instructions are missing **crucial** information like "minimum required version".

And believe me, I am usually much more sarcastic than that when stuff that ought to work doesn't. But I was being _polite._

**Comment by gasche** [comment]
> > Wow
> 
> Well? I followed your instructions _to the letter,_ and they didn't work. Of course I'm going to sound unimpressed and a little testy. Either the opam commands are wrong, or the "install opam" instructions are missing **crucial** information like "minimum required version".
> 
> And believe me, I am usually much more sarcastic than that when stuff that ought to work doesn't. But I was being _polite._

I'm closing this because your insulting behavior is an unacceptable way to treat the people giving their time to maintain and improve the system.

**Comment by dra27** [comment]
@Sod-Almighty - what Linux distribution and version are you using?

**Comment by Sod-Almighty** [comment]
Oh, you want insulting do you? You've just wasted my time, due to your instructions being WRONG! How polite do you EXPECT me to be??

**Comment by Sod-Almighty** [comment]
If it was my fault - if I'd done something wrong - you'd have a point. But this is YOUR ERROR. Not mine.
