### ISSUE TITLE
"Cheap" mutation operator

### ISSUE THREAD

**Issue by recoules** [ocaml/ocaml#11578]
Hi,

As far as I understand the OCaml runtime, allocation is kind of cheap, but stress out the garbage collector cycles, mutation of *young* values is cheap too, but mutation of *old* values may be costly because the GC needs to track the *old* to *young* references.

I think it would be beneficial to propose a new mutation operator that will either mutate in place the value if the best condition are met or allocate a new value otherwise.
Here is a proposition of syntax:
```ocaml
type ('a, 'b, 'c) t = { mutable a : 'a; mutable b : 'b; mutable c : 'c }

...

let v = { a; b; c} in
let a' = ... and b = ... in
let v' = { v. <- a = a'; b } in
...  
```
This would be equivalent to:
```ocaml
if not (is_young v) && (is_young a' || is_young b)  then
  { v with a = a'; b }
else (
 v.a <- a';
 v.b <- b;
 v
)
```

Regards,

**Comment by gasche** [comment]
This is a weird idea because it becomes difficult to reason about further mutations of `v` and `v'`, that may or may not be aliases of each other. Besides, it is not clear that it would be any faster than the current write barrier (your slow path, an allocation, is not clearly faster than the usual write slow path, that allocates into the remembered set).

To consider this any further I would expect actual performance numbers to measure whether it is worth it. You can do them on your side by writing the relevant operator as a C function. (Or possibly even write the whole benchmark in C to avoid the FFI costs.) Do you have a reasonably representative test in mind, an expensive computation where you would want to use this operator, that you could use for a benchmark?

**Comment by Octachron** [comment]
On a more theoretical side, this proposal also couples the implementation of GC and the semantics of program, without using weaks pointer or ephemerons. This seems like a behavior that we really want to avoid.

**Comment by recoules** [comment]
@gasche The structure is not implemented yet, but I have in mind a mutable map (balanced tree) that can become *lazily* persistent on demand in order to share it.

In the expected use case, the number of keys is finite but it is unknown in advance.  The map will first grow and balance until the "final" shape is reached and then, elements will be updated in place until the map is "committed".
Then, new operations will have to make a copy of the nodes to own them before mutating it in-place again, etc.

> This is a weird idea because it becomes difficult to reason about further mutations of `v` and `v'`

In my use case, old `v` will always be thrown away after mutation.
```ocaml
let v = { v. <- a = a'; b } in
...
```

Yet, you are right, this clearly fall in early optimizations, and only a proper benchmark can help to conclude if it is better or not.
But I would expect that, if the map lives long enough to be promoted, then every mutations will have the cost of the memory barrier slow path, whereas if the nodes are reallocated in the minor heap once by minor GC, every mutations will follow the fast path. Thus, it clearly depends on the cost of allocates into the remembered set against the cost of node reallocations.

**Comment by gasche** [comment]
Another way to think of your idea is as follows. For values that are uniquely owned, copies-with-modifications can be optimized into in-place update (this is a use of linear types in Cogent, or Koka's "functional but in-place" dynamic optimization using reference counting). You are suggesting an additional refinement to this approach where some of the copies remain copies to keep the values in the minor heap and avoid the write barrier.

I'm not convinced:

- We don't have the static discipline in OCaml to make this easy to reason about.
- The idea of keeping some values perpetually in the minor collection to avoid the write barrier seems like a cure worse than the disease. It shrinks our valuable young-value space. It is done by consistently waiting for a value to be promoted before we copy it into a young value again, so fundamentally it relies on wasted work.

>  if the map lives long enough to be promoted, then every mutations will have the cost of the memory barrier slow path

The memory-barrier slow path only occurs when you had an old value or an immediate in the reference and replace it by a young value. Any young->young update after this will be a fast path. In particular, if you only assign young values, you pay a slow path only once per minor generation. (More if you alternate between young values and immediates.)

**Comment by recoules** [comment]
> Any young->young update after this will be a fast path. In particular, if you only assign young values, you pay a slow path only once per minor generation.

I missed this part. In this condition, it is hard to think of a case where reallocation is better than updating the remembered set for a realistic mix of updates.

You can simply forget this idea. Thank you for your time.
