### ISSUE TITLE
OCaml C FFI manual still contains naked pointers

### ISSUE THREAD

**Issue by edwintorok** [ocaml/ocaml#11573]
IIUC naked pointers won't work with OCaml 5.0 anymore, but the manual still contains one instance that seems like a naked pointer to me:
https://github.com/ocaml/ocaml/blob/trunk/manual/src/cmds/intf-c.etex#L147-L165

```
CAMLprim value input(value channel, value buffer, value offset, value length)
{
  return Val_long(getblock((struct channel *) channel,
                           &Byte(buffer, Long_val(offset)),
                           Long_val(length)));
}
```

I'm assuming this should use something like the macro in io.h:
`runtime/caml/io.h:#define Channel(v) (*((struct channel **) (Data_custom_val(v))))`

**Comment by xavierleroy** [comment]
Well spotted.  I guess we need to find a simpler example -- one that uses integers and strings/byte arrays, but not custom types.  Suggestions welcome.
