### ISSUE TITLE
Documentation: "good break" in Format module.

### ISSUE THREAD

**Issue by johnridesabike** [ocaml/ocaml#11616]
From the Format documentation, emphasis mine:

> `@;`: output a 'full' break hint as with `print_break`. The `nspaces` and `offset` parameters of the break hint may be optionally specified with the following syntax: the `<` character, followed by an integer `nspaces` value, then an integer `offset`, and a closing `>` character. If no parameters are provided, the **good break** defaults to a 'space' break hint.

<https://v2.ocaml.org/releases/4.14/api/Format.html#fpp>

This is the only instance of "good break" I can find in the documentation. I assume it should say "full break" instead, or does "good break" have a certain meaning?

**Comment by Octachron** [comment]
The use of `good` is indeed a typo for `full` here.
