### ISSUE TITLE
ocamlopt reports incorrect error locations for unfound identifiers

### ISSUE THREAD

**Issue by JasonGross** [ocaml/ocaml#11629]
Consider the following example, minimized from Coq's extraction:
```ocaml
module Coq__1 = struct end

type t = { f1 : int ; f2 : int }

let f () = { f1 = 0
        ; Coq__10.f2 = 0 }
```
I get
```
$ ocamlopt foo.ml
File "foo.ml", line 5, characters 13-15:
5 | let f () = { f1 = 0
                 ^^
Error: Unbound module Coq__10
Hint: Did you mean Coq__1?
$ ocamlopt -v
The OCaml native-code compiler, version 4.11.2
Standard library directory: /home/jgross/.opam/4.11.2+fp/lib/ocaml
```
I understand what's going on here (OCaml will assume that all constructors come from the same module and hence will qualify all of them similarly), but it's still confusing to have it highlight a bit of code that does not reference the unbound module, especially when I did not write the OCaml code myself because it was generated by Coq.

**Comment by nojb** [comment]
Possible fix in #11630
