### ISSUE TITLE
`Domain.DLS`: overflow and release_key function

### ISSUE THREAD

**Issue by lyrm** [ocaml/ocaml#11625]
After trying to use domain local storage ([`Domain.DLS`](https://github.com/ocaml/ocaml/blob/33e2d04b9b0a4ce9c10069eb87b3e92c01c5d7c2/stdlib/domain.ml#L47)) to implement a data structure, I would like to suggest a few improvements to its  API. 

### Why ?
The current API is designed such as a `DLS key` is never released. Consequently, a code creating a large number of `DLS keys` may cause a memory overload. There is no defined hard limit in the current implementation. 

### Context
To put this issue in a context, here is a brief description of how I encountered it.  I was working on implementing a lockfree data structure that requires some domain local variables. I used  `DLS` for it. So each time one such data structure is created a new `DLS key` is required. 
I got memory overflow while running tests on it, as each test creates one data structure and is run multiple times, generating a lot of `DLS keys`.

### Proposed solution
While a more complex solution with ephemerons  may be put in place at some point in the future, I would like to suggest a simple short term solution, based on two additions:
- a hard limit on the `dls_state`  array size (and the corresponding DLS overflow exception). It is artificial but enables to detect a bad use of `DLS` instead of losing time trying to figure what is wrong,
- a `release_key` function, that simply put a released key index in a `queue` of available indexes, that can then be used when creating a new key.

**Comment by gasche** [comment]
Note in passing; `release_key` looks like a simple and good idea, but I think it is not simple: one can safely "release" a key only if the corresponding values are erased from all domains (otherwise we could reread the key and observe a stale value... at another type), and making sure that the values are erased requires global synchronization between all domains. (Currently we synchronize by performing an atomic increment when we create a new key, which is much simpler.)

**Comment by dra27** [comment]
Could `release_key` be made to work if the internal representation of `Domain.DLS.key` has a mutable `int` value, allowing the _existing_ key to be invalidated?

**Comment by gasche** [comment]
I think that could work, but it means that `get` is not domain-local anymore, in the sense that it has to perform some global synchronization -- just an atomic read, which is probably just fine.
