### ISSUE TITLE
ocamldebug: cannot install a printer after setting a breakpoint

### ISSUE THREAD

**Issue by garrigue** [ocaml/ocaml#11668]
I am using `ocamldebug` heavily to debug the type checker itself, and I came upon this strange behavior:
(replace `objgraph.ml` by any file you want to typecheck)

```
./debugger/ocamldebug -I utils -I parsing -I typing ./ocamlc -c -i objgraph.ml
	OCaml Debugger version 5.1.0+dev1-2022-06-09

(ocd) break @ ctype 810
Loading program... done.
Breakpoint 1 at 3:1452032: file typing/ctype.ml, line 810, characters 3-230
(ocd) install Printtyp.raw_type_expr
Unbound identifier Topdirs.printer_type_new
```

On the other hand it is possible to install it before setting a checking, and in this case it works fine.
```
./debugger/ocamldebug -I utils -I parsing -I typing ./ocamlc -c -i objgraph.ml
	OCaml Debugger version 5.1.0+dev1-2022-06-09

(ocd) install Printtyp.raw_type_expr
The debugger does not contain the code for Printtyp.raw_type_expr.
Please load an implementation of Printtyp first.
(ocd) load printtyp.cmo
Error during code loading: The module `Printtyp' is already loaded (either by the main program or a previously-dynlinked library)
(ocd) install Printtyp.raw_type_expr
```

Note that one needs the `load printtyp.cmo` line, despite the error.

All this is rather confusing.

**Comment by dra27** [comment]
5.0 includes some changes which affect the _toplevel's_ loading of `topdirs.cmi`, but IIRC the debugger's version should be unaffected.

That said, the set-up you're running looks potentially brittle - what's the shebang line for `debugger/ocamldebug`... this runs `ocamldebug` from the build tree but it will be using both a runtime and `dllunix.so` from an installed compiler (is that intentionally your setup, or accidental)?

Do you know at this stage if this is a regression relative to 4.14?

**Comment by garrigue** [comment]
Using 4.14, there was no problem of timing: you could install a printer at any time.
The error message when loading `printtyp.cmo` was already there, but it was just an annoyance.

Concerning the interaction with installed files, I get exactly the same error if I call `make install` just before, so I don't think this is the cause.
