### ISSUE TITLE
Segfault in bytecode program using effects

### ISSUE THREAD

**Issue by shym** [ocaml/ocaml#11669]
We noticed a segfault appearing in the bytecode backend since the release of 5.0.0 β1, triggered by a test exercising effects in @jmid’s multicoretests: [effect_lin_tests_dsl](https://github.com/jmid/multicoretests/blob/main/src/neg_tests/effect_lin_tests_dsl.ml).

Unfortunately I didn’t manage to create a smaller example, but I bisected the compiler and found the bug appears with commit [ce080dae](https://github.com/ocaml/ocaml/commit/ce080dae) which might give a clue where it stems from. See the logs [before](https://github.com/shym/multicoretests/actions/runs/3329054369/jobs/5505792490) and [after](https://github.com/shym/multicoretests/actions/runs/3329054368/jobs/5505792489) that commit.

It can be reproduced thus:

```
opam switch create bug-repro --empty --no-switch
eval $(opam env --switch=bug-repro --set-switch)

git clone https://github.com/ocaml/ocaml
cd ocaml
git checkout ce080dae # or later, such as 5.0.0-beta1 or 5.0
opam install -y ocaml-option-bytecode-only .
eval $(opam env)
cd ..

git clone https://github.com/shym/multicoretests.git --depth=1 -b effect-bug
cd multicoretests
opam install -y qcheck-core dune

export CI=true
# This setting removes constant progress messages. Without it, the bug
# does not trigger...
dune exec src/neg_tests/effect_lin_tests_dsl.bc -- -v -s 134165266
```

**Comment by shym** [comment]
I notice now that I can’t reproduce it on trunk, so it is maybe already fixed.

**Comment by Octachron** [comment]
Can you reproduce the issue on the 5.0 branch? More generally, how fragile is the segfault in your tests?

The commit that you linked is not supposed to introduce any semantics changes but it does change the call graph in case of unhandled exceptions and the memory layout of the Effect module. At first glance, it seems possible that that my commit is accidentally triggering a deeper bug.

**Comment by shym** [comment]
I finally managed to get a segfault also on `trunk`, but with a different seed and not exactly at the same point of the execution.
```
dune exec src/neg_tests/effect_lin_tests_dsl.bc -- -v -s 169255427
```

**Comment by shym** [comment]
@Octachron It is robust. I repeated the test 10 times in a row on the commit `ce080dae` (failure every time) and `ce080dae^` (success every time). I can reproduce it on `69c5a2bb32` (current `5.0` tip).

**Comment by shym** [comment]
[Log](https://github.com/shym/multicoretests/actions/runs/3327302313/jobs/5501954431) on `5.0.0+trunk` a bit earlier today.

**Comment by lthls** [comment]
I tried to reproduce the bug (on trunk), and I can reproduce the bug if I run the command through `dune exec` but not if I run the exact same command manually. This is quite puzzling, and makes debugging very complicated.
I would appreciate if you found a way to trigger the bug without `dune exec`.

**Comment by stedolan** [comment]
> I tried to reproduce the bug (on trunk), and I can reproduce the bug if I run the command through dune exec but not if I run the exact same command manually. This is quite puzzling, and makes debugging very complicated.

This may be because `dune exec` sets up various environment variables. Try doing `dune exec bash` and then running the command manually from within the resulting shell.

**Comment by lthls** [comment]
> > I tried to reproduce the bug (on trunk), and I can reproduce the bug if I run the command through dune exec but not if I run the exact same command manually. This is quite puzzling, and makes debugging very complicated.
> 
> This may be because `dune exec` sets up various environment variables. Try doing `dune exec bash` and then running the command manually from within the resulting shell.

Within `dune exec bash`, nothing segfaults, not even running with `dune exec` again.

**Comment by shym** [comment]
I realise now that reproducibility is a bit more brittle than what I thought. In my tests, I sometimes encounter seeds that make it segfault every time, sometimes not.
Anyway, I’ve pushed on my [`effect-bug`](https://github.com/shym/multicoretests/tree/effect-bug) branch a `Makefile` to investigate this without dune. In particular it provides a `look-for-seed` peusdo-target that tries random seeds until the test fails. I find it’s a good way to find a seed that will make it crash “reliably”, as it were.

**Comment by shym** [comment]
With that new strategy of trying many random seeds, I ran again bisection. Three times in a row (so trying completely different seeds), it ends up pointing to c77ce613de51671f425d6a3e30ac5fd05417f286 (see for instance [log](https://github.com/shym/multicoretests/actions/runs/3344758175/jobs/5540627921#step:5:79361) of the last run). Which is modifying the C code of the interpreter, a more likely culprit.

**Comment by shym** [comment]
I just double-checked: I can’t reproduce the bug neither on current 5.0 branch nor on c77ce61 + that patch.
:+1:
