### ISSUE TITLE
Introduce a one-liner comment syntax?

### ISSUE THREAD

**Issue by mimoo** [ocaml/ocaml#11689]
Hey hey. I've been wondering why OCaml doesn't have a one liner comment syntax, something like `#` or `//` in other languages. I find it quite tedious to always have to close a comment opener for short comments, or quick commenting.

**Comment by dra27** [comment]
See #671 🍿

**Comment by Octachron** [comment]
Let me close this duplicate issue.

**Comment by mimoo** [comment]
@Octachron can you link to the other issue that's open?

**Comment by Octachron** [comment]
You can discuss on the closed issue and see if you can bring enough arguments to convince people to reopen the issue.

**Comment by Octachron** [comment]
I forgot that #671 was a PR . Let's avoid putting more pressure on the PR author and let's use this issue for discussion purpose.

This doesn't change the fact that there is no plan to introduce one-line comment without a well-though proposition that preserves backward compatibility.

**Comment by mimoo** [comment]
I'm fine with `(*)` personally, I don't care much as long as there's something

**Comment by damiendoligez** [comment]
@Octachron should this be turned into a discussion ?
