### ISSUE TITLE
Recursion depth can be limited by the complexity of "unrelated" code paths

### ISSUE THREAD

**Issue by alainfrisch** [ocaml/ocaml#11687]
This is a "spin-off" of #11684, to serve as a documentation for a behavior that users might not be aware of, and possibly as a place to discuss possible improvements.

Consider some code like:
````ocaml
type t = A | B of t | C of t

let d = ref 0

let rec eval = function
  | A -> 0
  | B x -> incr d; 1 + eval x
  | C y ->
    eval y + eval y + eval y + eval y + eval y + eval y + eval y + eval y + eval y +
    eval y + eval y + eval y + eval y + eval y + eval y + eval y + eval y + eval y +
    eval y + eval y + eval y + eval y + eval y + eval y + eval y + eval y + eval y +
    eval y + eval y + eval y + eval y + eval y + eval y + eval y + eval y + eval y +
    eval y + eval y + eval y + eval y + eval y + eval y + eval y + eval y + eval y +
    eval y + eval y + eval y + eval y + eval y + eval y + eval y + eval y + eval y +
    eval y + eval y + eval y + eval y + eval y + eval y + eval y + eval y + eval y +
    eval y + eval y + eval y + eval y + eval y + eval y + eval y + eval y + eval y +
    eval y + eval y + eval y + eval y + eval y + eval y + eval y + eval y + eval y +
    eval y + eval y + eval y + eval y + eval y + eval y + eval y + eval y + eval y +
    eval y + eval y + eval y + eval y + eval y + eval y + eval y + eval y + eval y +
    eval y + eval y + eval y + eval y + eval y + eval y + eval y + eval y + eval y +
    eval y + eval y + eval y + eval y + eval y + eval y + eval y + eval y + eval y +
    eval y + eval y + eval y + eval y + eval y + eval y + eval y + eval y + eval y +
    0

let rec mk acc = function
  | 0 -> acc
  | n -> mk (B acc) (n - 1)

let v = mk A 1_000_000

let () =
  try ignore (eval v)
  with Stack_overflow -> Printf.printf "Max recursion depth : %d\n%!" !d
````

The complex expression for the `C` case needs to spill many values to stack slots (arguably, the compiler could do better by computing partial sums and reusing stack slots, but this is another story, and one could always build examples requiring such large stack frame). The large stack frame will limits the maximum recursion depth (before overflowing the Stack) even if we don't actually use the `C` constructor.  On my machine, the programs prints 8181 with the default stack size.  Simplifying the `C` case to a constant brings that number to 523874. Another way to achieve that recursion depth is to lift the `B` case to its own function:

````ocaml
let rec eval = function
  | A -> 0
  | B x -> eval_b x
...

and eval_b x = incr d; 1 + eval x
````

With this rewriting, the large stack frame for `eval` is released upon the tail call to `eval_b`, which itself needs a much smaller frame.

The oversized stack frame also results in slower execution (probably due to extra cache misses) : the same program, with a value of size 8000 (instead of 1 000 000), executing the `eval` function 10 000 times gives the following timing:

   - 4.0s for the original code
   - 1.0s for the original code, replacing the `C` case with a constant
   - 1.0s for the original code, lifting the `C` case to its own function
   - 1.17s for the original code, lifting the `B` case to its own function (so, another extra tail-call at each recursion)
   - 1.4s for the original code, simplifying the `C` case with only 9 recursive calls

There is a tiny overhead for the extra tail-call, but it gives a clear gain when it allows shrinking the stack frame size (even without going to extreme cases like the original program). This suggests that doing this rewriting automatically could be worthwhile (under some heuristics to be decided). It might even be possible to arrange the stack frame in a way which would allow to shrink it in some branches, without actually introducing some tail-calls (keeping values in their existing locations).

It might also be useful to get some warnings when the stack frame for some (recursive) function is above a certain threshold, since it might lead to degraded performance and/or limited maximum recursion depth.

**Comment by jberdine** [comment]
I have seen significant performance gains from manually performing transformations analogous to lifting the C case to its own function. In my cases the key was to make the hot case a separate function that was then small enough that flambda would/could productively unroll and inline it. (The results are more dramatic when the B case is not even recursive, but then that is far from the concern about stack frame sizes.)

**Comment by xavierleroy** [comment]
You definitely want the stack frame for a function to be allocated in full at the beginning of the function.  Allocating and releasing as you go through the function would be significantly more expensive, esp. on architectures that don't have "push" or "store and update stack pointer" instructions.  

Putting big but rarely executed code in its own function is a good idea performance-wise, but I don't think the compiler can figure it out itself, at least without copious profiling information.

As I don't see what the compiler could do to help in this case, I move to close this issue.
