### ISSUE TITLE
use of undeclared identifier 'asm'  (c11)

### ISSUE THREAD

**Issue by mobileink** [ocaml/ocaml#11691]
I'm working on support for alternate C compilers (zig, llvm) and cross-compilation using Bazel. I came across this minor problem when compiling with `--std=c11`:

```
runtime/caml/platform.h:40:3: error: use of undeclared identifier 'asm'
  asm volatile("pause" ::: "memory");
  ^
```

The fix is easy, just use `__asm__` instead of `asm`.  See [Alternate Keywords](https://gcc.gnu.org/onlinedocs/gcc-7.2.0/gcc/Alternate-Keywords.html#Alternate-Keywords).

**Comment by nojb** [comment]
Sounds reasonable.
