### ISSUE TITLE
bug in yacc/closure.c

### ISSUE THREAD

**Issue by mobileink** [ocaml/ocaml#11700]
Sorry I'm not set up to make a PR yet, but for the record:

The prototype of `print_closure` is off.  I think it should be:

```
#ifdef        DEBUG
void print_closure (int n);
#endif
```

https://github.com/ocaml/ocaml/blob/2bfc020aa75fdf00f0d51e9d16ffccad2e074345/yacc/closure.c#L31

https://github.com/ocaml/ocaml/blob/2bfc020aa75fdf00f0d51e9d16ffccad2e074345/yacc/closure.c#L192-L194

https://github.com/ocaml/ocaml/blob/2bfc020aa75fdf00f0d51e9d16ffccad2e074345/yacc/closure.c#L207-L217

**Comment by nojb** [comment]
Clearly correct, fix in #11703
