### ISSUE TITLE
Hardcoded #define NDEBUG in yacc/defs.h

### ISSUE THREAD

**Issue by mobileink** [ocaml/ocaml#11714]
https://github.com/ocaml/ocaml/blob/43c320501271c031052e2b62ec34e933a0d8f36a/yacc/defs.h#L18-L20

On a Mac (12.6, Apple clang version 14.0.0 (clang-1400.0.29.202)) this causes an error when -DNDEBUG is passed on the command line:

```
In file included from yacc/error.c:20:
yacc/defs.h:19:9: error: 'NDEBUG' macro redefined [-Werror,-Wmacro-redefined]
#define NDEBUG
        ^
<command line>:9:9: note: previous definition is here
#define NDEBUG 1
```

**Comment by dra27** [comment]
In terms of understanding the problem, why are you passing `-DNDEBUG` on the command line?

**Comment by dra27** [comment]
That said, the macro has been defined in one way or another since the very beginning (61bd8ace6b), but as far as I can see never used - a PR to remove those lines should clearly be fine (still curious as to how you hit this, though 🙂)

**Comment by mobileink** [comment]
The Bazel CC toolchain on the Mac inserts it when run with `--compilation_mode=opt`.

I was a little surprised this hasn't come up before, given that the point of NDEBUG as far as I can see is to allow disabling asserts by passing -DNDEBUG. But evidently assert is not used in the runtime, only in yacc and some testsuite code. I gather yacc is very stable and little used.

**Comment by dra27** [comment]
Indeed, I can see why it became defined this way in #1114 (in terms of what was being done to OCaml's build system at the time), but it looks like that was a mistake.

Would you be able to submit a PR removing those lines?

**Comment by mobileink** [comment]
I'll put it on my todo list. Might not be able to get to it in the immediate future, but it's not high priority I think.

**Comment by shindere** [comment]
Just opened https://github.com/ocaml/ocaml/pull/11724 to fix this issue

**Comment by shindere** [comment]
I think, see #11719 for a cleaner resolution.
