### ISSUE TITLE
single-handler exception functions

### ISSUE THREAD

**Issue by gasche** [ocaml/ocaml#11740]
Quirky syntax proposals never die... This is a revamp of `let exception with <handler> in <body>` (#11720) following a suggestion from @lthls.

### Context

A recommended approach to emulate `break` or `continue` in a loop is to use exceptions for local control flow:

```ocaml
let exception Break in
try while <cond> do
  ... raise Break ...
done with Break -> ()

while <cond> do
  let exception Continue in
  try
    ... raise Continue ...
  with Continue -> ()
done
```

Here we use not only exceptions but locally-declared exceptions. This makes sense given that (1) the local-exception syntax was introduced with optimizations-into-local-control-flow analyses in mind, and (2) declaring custom exceptions instead of reusing `Exit` is more readable and extends gracefully to the case where we want to return values when breaking.

```ocaml
let findi p arr =
  let exception Found of int in
  try
    for i = 0 to Array.length arr - 1 do
      if p arr.(i) then raise (Found i)
    done;
    None
  with Found i -> Some i
```

### Proposal

We could make this pattern lighter by merging the local-exception declaration and the single handler:

```ocaml
let exception <lident> p1.. pn = <expr> in <body>
````

This is syntactic sugar for:

```ocaml
let exception Uident of ... in
try
  let <lident> x1..xn = raise (Uident (x1, ..., xn)) in
  <body>
with Uident (p1, ..., pn) -> <expr>
```

Full examples:

```ocaml
let exception break () = () in
while <cond> do
  ... break () ...
done

while <cond> do
  let exception continue () = () in
  ... continue () ...
done

let findi p arr =
  let exception found i = Some i in
  for i = 0 to Array.length arr - 1 do
    if p arr.(i) then found i
  done;
  None
```

This was inspired by a comment of @lhtls in the previous iteration of this suggestion : https://github.com/ocaml/ocaml/issues/11720#issuecomment-1317135245 .

In the #11720, people commented that they found it odd to define the handler before raising the exception. I don't really understand the criticism, and I find it rather clear here that this works exactly like usual functions -- that perform a control effect, as we can already implement directly in OCaml.

(@lhtls also commented that he thinks the syntactic space is intrisically entangled with the optimization space. I'm still not convinced by this. It is very natural to support, say, `let[@local] exception ...`.)

**Comment by rlepigre** [comment]
Is there a good reason not to just directly add `break` and `continue` to the language?

On a similar note, I always wished OCaml had a `return` statement, which is often very useful to handle special cases early, and could well be implemented as syntactic sugar as well.

**Comment by gasche** [comment]
Note: you can also do `return` with single-handler exception functions.
(I looked for an example in the compiler codebase and my first convincing find in fact uses `return` across functions.)

```ocaml
(* before *)
let rec compare ds1 ds2 =
  let rec loop ds1 ds2 =
    match ds1, ds2 with
    | [], [] -> 0
    | _ :: _, [] -> 1
    | [], _ :: _ -> -1
    | d1 :: ds1, d2 :: ds2 ->
      let c = String.compare d1.dinfo_file d2.dinfo_file in
      if c <> 0 then c else
      let c = compare d1.dinfo_line d2.dinfo_line in
      if c <> 0 then c else
      let c = compare d1.dinfo_char_end d2.dinfo_char_end in
      if c <> 0 then c else
      let c = compare d1.dinfo_char_start d2.dinfo_char_start in
      if c <> 0 then c else
      let c = compare d1.dinfo_start_bol d2.dinfo_start_bol in
      if c <> 0 then c else
      let c = compare d1.dinfo_end_bol d2.dinfo_end_bol in
      if c <> 0 then c else
      let c = compare d1.dinfo_end_line d2.dinfo_end_line in
      if c <> 0 then c else
      loop ds1 ds2
  in
  loop (List.rev dbg1) (List.rev dbg2)

(* after *)
let rec compare ds1 ds2 =
  let exception return c = c in
  let check c = if c <> 0 then return c in
  let rec loop ds1 ds2 =
    match ds1, ds2 with
    | [], [] -> 0
    | _ :: _, [] -> 1
    | [], _ :: _ -> -1
    | d1 :: ds1, d2 :: ds2 ->
      check (String.compare d1.dinfo_file d2.dinfo_file);
      check (compare d1.dinfo_line d2.dinfo_line);
      check (compare d1.dinfo_char_end d2.dinfo_char_end);
      check (compare d1.dinfo_char_start d2.dinfo_char_start);
      check (compare d1.dinfo_start_bol d2.dinfo_start_bol);
      check (compare d1.dinfo_end_bol d2.dinfo_end_bol);
      check (compare d1.dinfo_end_line d2.dinfo_end_line);
      loop ds1 ds2
  in
  loop (List.rev dbg1) (List.rev dbg2)
```

**Comment by rlepigre** [comment]
I had actually not realized that the semantics of `break`, `continue` and `return` was so tricky due to local definitions and lambdas. I'm not sure that allowing `return` (or even `break` and `continue`) across functions is the right thing to do. Sure you can encode that using exceptions, but you need to somehow distinguish `loop` and `check` (in the example above) to say that only the latter has a handler for the `return` exception.

All in all, I think I would prefer that `return` always refers to the current function, even though this is quite limiting. One kind of example that I was hoping to get support from is something like:
```
let find_index : ('a -> bool) -> 'a list -> int = fun p l ->
  List.iteri (fun i e -> if p e then return i) l
```
But that does not fit the limitation I proposed... So, yeah, what we can and should do is totally unclear to me.

**Comment by gasche** [comment]
> Sure you can encode that using exceptions, but you need to somehow distinguish `loop` and `check` (in the example above) to say that only the latter has a handler for the `return` exception.

I don´t follow. In this example the handler is placed exactly where `let exception return`  is, that is "outside" both `loop` and `check`. (This means that this use of exception may not be optimized into local control flow, unless the optimizer notices that `loop` can be turned into a local recursive loop. I'm okay with the idea that this would not be optimized, and thus slightly slower than the current version.)

> So, yeah, what we can and should do is totally unclear to me.

I think you sort of answered your own question about why we don't have `return` in OCaml.

(`break` and `continue` are a bit harder to dispel with the same argument because they are used inside loops that arguably are less likely to contain higher-order function applications. But even for those, the added expressiveness of being able to take parameters, return value, and cross local function abstractions is nice.)

**Comment by rlepigre** [comment]
> I don´t follow.

Oh sorry, I read your code too quickly and missed the `let exception return` part. I'm less confused now.

**Comment by gasche** [comment]
I had a chat with @lthls about this feature today, he asked whether the raise (implicit in each call to the exception function) should save a backtrace. There is a tension between convenience and performance here.

We agreed on the following:

- We don't need to let the function exception definition access a backtrace; in other words, asking for `get_backtrace` within the handler could return any implementation-defined result, as if `raise_backtrace` was used.
- On the other hand, we probably want the exception to come with a backtrace if it escapes (it can escape if someone leaks the exception function outside its lexical scope), as if `raise` was used.

(To express this purely as syntactic sugar, we could have a function or primitive `drop_backtrace` that makes the backtrace state implementation-defined, and desugar `let exception foo <args> = <handler> in ...` with an exception handler `with Foo <args> -> drop_backtrace (); <handler>`.)

**Comment by Kakadu** [comment]
> ```ocaml
> let exception break () = () in
> while <cond> do
>   ... break () ...
> done
> 
> while <cond> do
>   let exception continue () = () in
>   ... continue () ...
> done
> ```

It looks like, that semantics of new 'exception' depends on the placement of declaration (outside loop for break, inside -- for continue). People may have difficulties reading that, because two syntaxes look too similar....

**Comment by wikku** [comment]
I think this is too confusing. When raised, control will jump to the handler at the top of the code and then skip the potentially huge expression after `in`. If I'm parsing correctly, the following won't print:

```
let exception break () = () in
while true do
    break ()
done;
print_endline "after loop"
```

and should be contorted into something like:

```
begin let exception break () = () in
while true do
    break ()
done end;
print_endline "after loop"
```

Similar issues were raised in the previous issue. Isn't `let` associative, in particular
```let y = let x ... = e1 in e2 in e3   ≡   let x ... = e1 in let y = e2 in e3```?
Binding operators which don't follow the monad laws already break it,
but I don't think an "official" language feature should.

So if explicit delimiters are important, what about a syntax sugar for declaring an exception in `try...with...`:

```
try <body> with new Exn payload -> <handle>
```

is sugar (or maybe a bespoke construct, no point in having Exn in scope in `<handle>`) for 

```
(let exception Exn of ... in
try <body> with Exn payload -> <handle>)
```

Isn't that more intuitive?

**Comment by gasche** [comment]
I mentioned it in a developer meeting, everyone hates this proposal. Closing.

**Comment by gasche** [comment]
I remain convinced that this would have been an interesting feature with wide applicability.

The main criticism is that `let exception` does not make it clear enough that this is a control-flow construct whose declaration site should be carefully considered -- it looks like it might commute with other `let` constructs (those that do not provoke immediate computation, at least), yet it does not.

I have tried thinking of other syntaxes that would keep the compactness of my proposal while avoid this criticism.

```ocaml
(* Original propoal:
  let exception <fun> = <expr> in <expr>,
  let effect <fun>, k = <expr> in <expr>  
*)
let exception break () = () in
....

(* try with <handler> in <expr>
   rejected: too verbose *)
let exception Break in
try with Break () -> () in
...

(* let try exception <fun> = <expr> in <expr> *)
let try exception break () = () in
...

(* try with exception <fun> = <expr> in <expr> *)
try with exception break () = () in
...
```
