### ISSUE TITLE
Transform sync_stdlib_docs into a API consistency test

### ISSUE THREAD

**Issue by Octachron** [ocaml/ocaml#11777]
To ensure that labeled and not-labeled module are not out-of-sync, we are currently generating the non-labelled version of mli files from the labelled ones.

This transformation is done through a bash script which is both limited and hard to update in a principled way.
For instance, adding an example to the `Array` module required me to add this kind of hack: https://github.com/ocaml/ocaml/pull/11237/commits/f891a7aa8adc3e080b8a28733cd0ceedb4051e45 .

I propose to relax that constraint by replacing the use of `sync_stdlib_docs` in the CI by an alternative consistency check which would only compare the types and the since annotation of the labelled and non-labelled modules and nothing else.

The idea is to free us from the strong constraint of having the same documentation text while still enforcing synchronization at the API level.

**Comment by dra27** [comment]
Doesn't the lib-stdlabels test already give us the API synchronization (and therefore the theory that any _new_ functions would receive consistent `@since` annotations)?

**Comment by nojb** [comment]
> The idea is to free us from the strong constraint of having the same documentation text while still enforcing synchronization at the API level.

Sorry, but wasn't the idea of `sync_stdlib_docs` precisely to enforce having the same documentation text between both versions? In my opinion, having the same documentation text is a _good_ thing (do you agree?); the matter is rather that the tool used to enforce this is not sufficiently flexible, easy to modify, etc... If only it was implemented in a proper scripting language 😉 ...

**Comment by dra27** [comment]
I agree, @nojb. `sync_stdlib_docs` isn't part of the build system - it can safely be written in just about anything!

**Comment by gasche** [comment]
Personally I think that the value of the check is outweighed by the pain and opacity for people modifying these files. For example, once I tried to add a labelled function in Array, and I had to work around the tool by adding a space around the colon in the .mli to avoid the tool yelling at me. This is unpleasant and fragile and I wish it would go away.

**Comment by Octachron** [comment]
The `lib-stdlabels` test is incomplete and doesn't cover since annotation.

> having the same documentation text is a good thing (do you agree?)

I don't really agree that having the same documentation text is *always* a good thing. It is however better than having inconsistent documentation. And we don't have the time to tweak the documentation for the labelled and not labelled variants, thus the current frozen solution.

My user experience of `sync_stdlib_docs` is that the tool adds a lot of friction when working on the documentation. The fact that `sync_stdlib_docs` can erase the work on an unsuspecting editor is worrying for instance.  Thus, I have very mixed feelings on the tool overall.

**Comment by bnguyenvanyen** [comment]
A simple consistency test : If the diff between labeled and unlabeled versions was committed as part of the repo, there could be a CI test that looks at the diff of diffs (between committed diff and actual diff). If there's a diff, there's something to fix, either the committed diff, or the labeled/unlabeled version.

**Comment by nojb** [comment]
> A simple consistency test : If the diff between labeled and unlabeled versions was committed as part of the repo, there could be a CI test that looks at the diff of diffs (between committed diff and actual diff). If there's a diff, there's something to fix, either the committed diff, or the labeled/unlabeled version.

This is a clever idea, but even changes that are correctly propagated between the two versions will cause changes in the diff (due to line number changes), so in practice the committed diff will need to be updated at almost every change, and this risks being rather bothersome.

**Comment by shindere** [comment]
One qeustion I tried to ask but which didn't make it through GitHub
because of issues with email configuraiton.

Couldn't we generate the non-labelled versions of the interfaces from
the labelled one? There already is `-i` so perhaps it would be doable to
add another option to ask the compiler to output an interface without
labels? Could that work?

**Comment by dra27** [comment]
> This is a clever idea, but even changes that are correctly propagated between the two versions will cause changes in the diff (due to line number changes), so in practice the committed diff will need to be updated at almost every change, and this risks being rather bothersome.

I did a quick attempt last night at diff-of-diffs on the _current_ files on all the changes to those interfaces since the script was introduced, and it's actually not that bad (it's not yet in Python, so I haven't pushed it 😉). I was going to re-try it with the changes we'd have liked to make (i.e. with no thwart comments, etc.) and see how many of those commits actually needed to alter the diff-of-diffs. A nice aspect of this approach is that it _just_ involves regenerating the diff-of-diffs file - the process never requires you to go back and change the interfaces in order to keep the lint happy.

> Couldn't we generate the non-labelled versions of the interfaces from the labelled one? There already is `-i` so perhaps it would be doable to add another option to ask the compiler to output an interface without labels? Could that work?

I think there's also the problem of being to manipulate the comments which IIRC/IIUC ocamldoc/odoc can do, but ppx can't?

**Comment by Octachron** [comment]
Generating the not labelled version from the labelled version would not solve the problem that the documentation should be equivalent rather than strictly equal. Moreover, the not-labelled version does use labels, thus it cannot be generated from the labelled version by removing all labels.

**Comment by shindere** [comment]
David Allsopp (2022/12/03 02:31 -0800):
> > Couldn't we generate the non-labelled versions of the interfaces from the labelled one? There already is `-i` so perhaps it would be doable to add another option to ask the compiler to output an interface without labels? Could that work?
> 
> I think there's also the problem of being to manipulate the comments
> which IIRC/IIUC ocamldoc/odoc can do, but ppx can't?

Well, if we were to do that I can imagine that we could have a special
mode of the compiler doing exactly this operation and preserving the
comments, does this look undoable?

**Comment by shindere** [comment]
Florian Angeletti (2022/12/03 02:37 -0800):
> Generating the not labelled version from the labelled version would
> not solve the problem that the documentation should be equivalent
> rather than strictly equal. Moreover, the not-labelled version does
> use labels, thus it cannot be generated from the labelled version by
> removing all labels.

Okay, so this can not work indeed.
