### ISSUE TITLE
unatural evaluation of boolean 

### ISSUE THREAD

**Issue by Nolord** [ocaml/ocaml#11786]
```
let ( => ) a b = (not a) || b in
let i = ref (-1) in
(!i < 0) => (incr i; false)
```

This code returns true, but should return false due to lazy evaluation.
It's returning true because i is first incremented and then compared to 0.
Replacing => by its defintion solves the issue.

**Comment by Octachron** [comment]
OCaml is an eager language, function arguments are evaluated before the function is called. The short-circuiting behavior of the built-in operators `||` and `&&` are an exception to this rule.

Thus, the behavior of `=>` is conform to specification.

**Comment by dbuenzli** [comment]
> OCaml is an eager language, function arguments are evaluated before the function is called.

and the evaluation order is unspecified – but in practice from *right to left*. So it's a good idea to avoid code of the form `f … (<side-effect>; v) …`

@Nolord if you are new to the language it's likely a good idea to post and discuss your discoveries on https://discuss.ocaml.org/ (you can log in with your github account) before opening issues here.
