### ISSUE TITLE
Surprising syntax: Attributes go after the let and before the rec in let rec?

### ISSUE THREAD

**Issue by alan-j-hu** [ocaml/ocaml#11784]
The following is a syntax error:

```ocaml
let _ =
  let rec[@a] f x = x in
  f
```

The following is allowed:

```ocaml
let _ =
  let[@a] rec f x = x in
  f
```

The relevant grammar is https://github.com/ocaml/ocaml/blob/4435ac03f1afd11504a1dac22d6b55e3be8ee85e/parsing/parser.mly#L2569-L2580.

Would the syntax be more intuitive if the attribute went after the rec and directly before the binding it applies to?

**Comment by gasche** [comment]
The attribute is consistently on the first keyword of multi-keyword constructions. I don't think requiring the other syntax would be more intuitive, but we might decide to allow to place attributes in both places (and concatenate them). I wouldn't consider this a priority.

If we want to work on attribute parsing, one thing that I find annoying is the unability to write `f[@foo] x` for application of a function with an attribute, having to write `(f[@foo]) x` instead.
