### ISSUE TITLE
Update gdb-macros and gdb_ocamlrun.py to work with current trunk

### ISSUE THREAD

**Issue by abbysmal** [ocaml/ocaml#11787]
I wanted to make this note for a while, but I think both files have severely bitrot since they were introduced and Multicore was merged.

I haven't tried them in a while, but looking at them, they still refers to the old GC coloring scheme, so I assume they are outdated.

I'm not sure how much work it would, nor how useful they would be. (if they worked, I'd assume debugging with `rr` would be nicer.)

**Comment by samwgoldman** [comment]
I have found gdb-macros to be very useful for post-mortem debugging, where I only have a core dump and a binary, but not a reproduction. We are looking into updating to OCaml 5 and having an updated version of these tools would give me some peace of mind :)

**Comment by abbysmal** [comment]
Very nice, thank you very much for working on this!

**Comment by NickBarnes** [comment]
@Engil @samwgoldman Please have a look at my PR #12179.
