### ISSUE TITLE
Missed opportunity for contification

### ISSUE THREAD

**Issue by alan-j-hu** [ocaml/ocaml#11834]
The following code:
```ocaml
let f n ls =
  let[@local] rec loop acc = function
    | [] -> acc
    | _ :: xs -> loop (acc + n) xs
  in
  loop n ls
```
results in the following compile warning:
```
2 | .......................acc = function
3 |     | [] -> acc
4 |     | _ :: xs -> loop (acc + n) xs
Warning 55 [inlining-impossible]: Cannot inline: This function cannot be compiled into a static continuation
```
The cmm looks like the following:
```
(function{test.ml:1,6-118} camlTest__f_268 (n/270: val ls/271: val)
 (let
   clos/281
     (alloc{test.ml:2,23-88} 4343 "caml_curry2" 144115188075855879
       "camlTest__loop_272" n/270)
   (if (and ls/271 1) n/270
     (app{test.ml:4,17-34} "camlTest__loop_272"
       (+ (+ n/270 (load_mut val (+a clos/281 24))) -1)
       (load_mut val (+a ls/271 8)) clos/281 val))))

(function{test.ml:2,23-88} camlTest__loop_272
     (acc/273: val param/275: val env/280: val)
 (if (and param/275 1) acc/273
   (app{test.ml:4,17-34} "camlTest__loop_272"
     (+ (+ acc/273 (load val (+a env/280 24))) -1)
     (load_mut val (+a param/275 8)) env/280 val)))

(function camlTest__entry ()
 (let f/268 "camlTest__1"
   (extcall "caml_initialize" "camlTest" f/268 ->unit))
 1)
```

Ideally, the compiled function should look like the following (pseudocode):
```
function f(n, ls) {
entry:
  goto loop(n, ls)
loop(acc, temp):
  case temp [[] -> ret, _ :: xs -> block]
block:
  temp = acc + n
  goto loop(temp, xs)
ret:
  return acc
}
```

I would like the `loop` helper function to be compiled into a static continuation, not a closure with a heap allocation.

**Comment by gasche** [comment]
For now the `@local` hint and code transformation does not support recursive functions. (I think this is the feature request?)

Note that you can remove the heap allocation by making the `loop` function closed over its arguments (lambda-lifting).

```ocaml
let f n ls =
  let rec loop n acc = function
    | [] -> acc
    | _ :: xs -> loop n (acc + n) xs
  in
  loop n n ls
```

(This still does not support `[@local]`).

**Comment by alan-j-hu** [comment]
I don't know if this is a bug or feature wish in so far as I don't know the compiler writers' intentions. There is a contification pass, and the `[@local]` annotation is supposed to assert that a function is contified, but the contification algorithm evidently misses functions that could be contified. I shall assume that the algorithm is not intended to be optimal, so this shall be a feature wish and not a bug report.

The paper [Contification Using Dominators](https://www.cs.purdue.edu/homes/suresh/502-Fall2008/papers/contification.pdf) gives an optimal algorithm for contification. It constructs a control flow graph based on return locations: For a given function call, the function is said to either return to a continuation (e.g. in `g (f x)`, `f` returns to the continuation `g []`) or from a function (e.g. in `let g x = f x x`, where `f` returns from `g` because `f` is in tail position). The entry function and all continuations are dominated by a root node (meaning that they are said to return to/from this root node). If a function is dominated by a node other than the root, then it may be contified.

This algorithm is implemented in MLton, but after first-class functions are eliminated (MLton is a whole-program optimizing compiler). For a language with first-class functions, I believe that it would be correct to adapt the algorithm so that functions that are used in a first-class way are given an edge to the root node and therefore not contified.

I think optimal contification is very important because in OCaml, recursive helper functions (functions that capture variables from the outer scope) are used for basic control flow where loops are used in other languages. For OCaml to have ideal performance and compete with other languages, these recursive helper functions should compile to a simple block that shares the same stack frame as the enclosing function. When I program, I intuitively treat such functions as if they were basic blocks.

Right now, functions are contified using [static exceptions](https://github.com/ocaml/ocaml/blob/ce1a0a50266a9a0dc770967e12e076db055395c1/lambda/simplif.ml#L785), which I assume don't support loops (as you can't raise an exception from its own handler to jump back to the handler). What would it take to support contification in the most general case?

I would be willing to implement the contification algorithm for the compiler.

**Comment by gasche** [comment]
I had a hard time finding the [documentation for @local in the manual](https://v2.ocaml.org/manual/attributes.html#ss:builtin-attributes), but the wording does broadly agree with @alan-j-hu's take:

> The attribute controls an optimization which consists in compiling a function into a static continuation. Contrary to inlining, this optimization does not duplicate the function’s body. This is possible when all references to the function are full applications, all sharing the same continuation (for instance, the returned value of several branches of a pattern matching).

This wording is consistent with also optimizing tail-recursive calls to the candidate function, such as `loop` above -- they share the same continuation as their caller.

But indeed, at the level at which the optimization is currently performed, there is no "recursive local control flow" construct available so it would be unclear how to adapt the implementation to recursive functions. At the cmm level, I believe that `catch` is now recursive so we could do it there.

cc @alainfrisch who wrote the `@local` optimization. Do you have an opinion here, and would you be willing to take on @alan-j-hu's offer to experiment with implementations, if given some directions that you find reasonable?

**Comment by lthls** [comment]
A few notes, not in any particular order:
- This has been implemented by @Ekdohibs in the flambda-backend compiler, when Flambda 2 is in use: ocaml-flambda/flambda-backend#893. Even there, we didn't go for optimal contification. Instead, we only transformed obviously tail-recursive functions into non-recursive functions with a loop, and let the regular inlining heuristics determine whether to actually inline the function, sharing the call stack and (potentially) removing the need for a closure allocation, or keep it as a separate function.
- Contification is not always a good idea for performance, even in the non-recursive case (see #11383 and issues linked from it), so I don't think we should implement it in its most general form.
- It's not obvious that sharing a stack frame between the caller and the loop (or any contifiable function in general) is a good idea. See #11687 for a related discussion, where big stack frames in one part of the code negatively impact other parts of the code.
- You can remove the closure allocation if you compile with Flambda and pass the `-unbox-closures` flag (which performs the same transformation as the one @gasche showed, but automatically). Alternatively, if you use Flambda `f` will most likely be inlined at every call site, producing specialised versions of `loop` that may not even need a closure (depending on the value of `n`).
- Tail recursive functions are eventually compiled into a loop, although that happens quite late in the native backend. So the machine code generated by the current compiler (with `-unbox-closures` or @gasche's patch) is already mostly equal to the ideal pseudo-code.

**Comment by alainfrisch** [comment]
> cc @alainfrisch who wrote the @local optimization. Do you have an opinion here

My opinion is that it's not a bug. I did not intend the optimization to be an "optimal contification" pass, only a way to expose the existing static continuation mechanism available in the compiler intermediate languages, and which allows removing some local functions (but not recursive ones).

**Comment by gasche** [comment]
I'm sympathetic to this argument (this is more or less my first response), but I think that users would deserve to know what the specification of the transformation is, what kind of examples they can expect to work or not, with enough details that they can tell that this example is or isn't intended to be accepted. Currently the manual is vague about it and I think that in this context @alan-j-hu's request is entirely legitimate. You should not need to be familiar with the lambda IR or the optimization's implementation to predict what is going to happen on some examples.

**Comment by alan-j-hu** [comment]
Hmm... So there is a contradiction of intuitions. If one reasons about the code based on their naive semantics, one would expect helper functions to have their own stack frames. However, if one reasons about the code expecting certain helper functions which are only (mutually) tail-recursive and dominated by the outer function to be treated as "basic blocks," then one would expect them to occupy the same stack frame. If certain code is intentionally split into a helper function because it uses large stack space, it would be frustrating if the contification optimization undid this deliberate choice.

My feeling then is that the optimization should be opt-in with the attribute. Without the attribute, helper functions would have their own stack frames, but with the attribute, they would be treated as basic blocks.

I'm taking look at the various compiler IRs. Both `lambda.ml` and `clambda.ml` seem to have arbitrarily nested expressions. Meanwhile, `flambda.ml` uses an ANF-style representation.

Because the contification algorithm needs to identify and manipulate places where functions return to, I think it would be most convenient if the IR had explicit continuations and called functions in CPS (meaning that the point that they return to has a name). The "continuation" can just be a name, not a first-class construct. According to MLton's developer documentation, its contify pass [differs](http://mlton.org/Contify) from the paper in that it uses "SSA" instead of "CPS," but as far as I can tell, in [MLton's SSA representation](https://github.com/MLton/mlton/blob/master/mlton/ssa/ssa-tree.sig#L114), all function applications are terminator/control transfer instructions with an explicit return point. I suspect that the distinction between "CPS" and "SSA" that MLton's developer documentation makes is the distinction [here](http://www.mlton.org/pipermail/mlton/2003-January/023054.html), where "CPS" means a lexically scoped IR and "SSA" means a non-lexically scoped IR: SSA has the advantage that compiler transformations don't need to prove that variable definitions dominate uses, while in CPS transforms, the compiler must prove this by maintaining the lexical scoping.

(The terminology is not precise enough. When I think of the difference between CPS and SSA, I think that SSA allows function calls in the middle of a basic block, like in LLVM's IR and similar to ANF, while CPS gives all function calls an explicit control transfer to a label. However, for the MLton developers, the distinction is about variable scoping. I think that a non-lexically scoped IR that names all function return points is the ideal IR for analysis.)

**Comment by gasche** [comment]
My impression is that the directions in which @alan-j-hu would want to go are too invasive in terms of implementation complexity -- we will not move the Lambda IR to a representation with explicit continuations any time soon -- and thus the PR could be closed as "won't fix" or "suspended". On the other hand, I think that we should document `@local` better to help users understand what will and will not work.

@alan-j-hu you seem interested in OCaml optimization passes. My intuition is that you could be interested in flambda2, which is a more ambitious IR that is only present in experimental forks of OCaml for now; when it gets proposed for upstreaming we will be looking for people interested in reviewing the work. Drop me an email if this is something you would be interested in.
