### ISSUE TITLE
Injectivity checker: change in behaviour since 5.0.0

### ISSUE THREAD

**Issue by yallop** [ocaml/ocaml#11869]
#11018 has changed the behaviour of injectivity checking, so that it rejects definitions that were previously accepted.  I'm not sure whether the change was deliberate, but it doesn't appear to be documented.

In OCaml 5.0.0 (and in `trunk` before #11018 was merged):
```ocaml
# module type s = sig type t end;;
module type s = sig type t end
# type !'a t = (module s with type t = 'a);;
type 'a t = (module s with type t = 'a)
```

After #11018: 
```ocaml
# module type s = sig type t end;;
module type s = sig type t end
# type !'a t = (module s with type t = 'a);;
Line 1, characters 0-40:
1 | type !'a t = (module s with type t = 'a);;
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Error: In this definition, expected parameter variances are not satisfied.
       The 1st type parameter was expected to be injective invariant,
       but it is invariant.
```
(Discovered here: https://github.com/ocaml/ocaml/pull/11830#pullrequestreview-1237097898)

**Comment by gasche** [comment]
#11018 was not supposed to change the behavior in general, but it did in a few places. I would hazard the guess that the regression you notice is related to this discussion during review: https://github.com/ocaml/ocaml/pull/11018#discussion_r815290820 . Quoting @garrigue:

> Indeed, the behavior here changes. I came to the conclusion that the previous check was potentially wrong: we allow subsumption of module types through subtyping, and as a result a variable might disappear. It is only in the Inv case that we can guarantee that there is no way to make it disappear. I couldn't build a counter-example, but it seems better to stay on the safe side.

It would be easy to revert this change I believe, but we might want to hear @garrigue on whether this example is indeed unfairly rejected by the new version, or something that is in the "potentially wrong" category.

**Comment by garrigue** [comment]
Unfortunately this example was not in test suite...
The original code for `Tpackage` looked strange, and we opted for the safe side, i.e. make the parameters invariant only in an invariant context.
However, now that I think of it, type components of a signature are invariant by definition, so we should actually have strengthened it.
Will fix ASAP.
