### ISSUE TITLE
A seek on a closed channel can allow invalid `input`s

### ISSUE THREAD

**Issue by shym** [ocaml/ocaml#11878]
While running some [qcheck-lin](https://github.com/ocaml-multicore/multicoretests) tests of `In_channel`, I ran into a problem which boils down to this test:
```
let _ =
  let f = open_in Sys.argv.(0) in
  seek_in f 1 ;
  close_in_noerr f ;
  seek_in f 0 ;
  Printf.printf "Read: %d\n%!" (input_byte f) ;
  Printf.printf "Read: %d\n%!" (input_byte f)
```
yielding:
```
Read: 0
Fatal error: exception Sys_error("Bad file descriptor")
Raised by primitive operation at Seekextra in file "seekextra.ml", line 7, characters 31-45
```
Replacing the first `seek_in` by `seek_in f 10` would allow inputting 10 bytes before getting an exception.
In this example, the extra byte(s) we input were never really read from the file, they are what’s currently in the buffer (which is not initialized, I think, which would explain that random testing it could find such a code giving non-deterministic results).

As I understand [`caml_ml_close_channel`](https://github.com/ocaml/ocaml/blob/d70eae08210564f242b4a6557528763ed932ca03/runtime/io.c#L671), we want to avoid testing explicitly whether the channel is indeed open in every function and rather rely on failing syscalls to detect it. So I checked that simply resetting the offset when closing the file:
```diff
@@ -681,6 +681,7 @@ CAMLprim value caml_ml_close_channel(value vchannel)
      immediate caml_flush_partial or caml_refill, thus raising a Sys_error
      exception */
   channel->curr = channel->max = channel->end;
+  channel->offset = 0;
 
   /* If already closed, we are done */
   if (channel->fd != -1) {
```
is enough to get an exception on the first `input` after closing. It does still allow for the `seek_in` on the closed channel, so that’s maybe not the best way to go.

**Comment by xavierleroy** [comment]
Interesting example, thanks!  I'm surprised that "the extra byte(s) we input were never really read from the file".  Seeking can move within data already read in the buffer, but should not expose parts of the buffer that have not been read.  Maybe this is the root of the problem, independently of whether the channel is closed between the two `seek_in`.

**Comment by shym** [comment]
Here is, step by step, my understanding of what happens in that example.
First we open the file with `caml_open_descriptor_in`, `offset` is set to 0, `curr` and `max` point to the beginning of the buffer.
https://github.com/ocaml/ocaml/blob/d70eae08210564f242b4a6557528763ed932ca03/runtime/io.c#L171-L174
Then we seek to position 1 with `caml_seek_in`, `offset` is 1, `curr` and `max` are assigned again at the beginning of the buffer.
https://github.com/ocaml/ocaml/blob/d70eae08210564f242b4a6557528763ed932ca03/runtime/io.c#L437-L443
Then we close the channel with `caml_ml_close_channel`, `curr` and `max` are set to the end of the buffer but, critically, `offset` is not modified (so keep at 1).
https://github.com/ocaml/ocaml/blob/d70eae08210564f242b4a6557528763ed932ca03/runtime/io.c#L680-L683
Then we seek back with `caml_seek_in`, but this time the condition is true, the function assumes that we are seeking inside data in the buffer (note though that no `read` ever happened), so `curr` points now to the last byte of the buffer.
https://github.com/ocaml/ocaml/blob/d70eae08210564f242b4a6557528763ed932ca03/runtime/io.c#L431-L434
Then the next input will read that byte, because it is deemed valid.

**Comment by xavierleroy** [comment]
Thanks for the step-by-step.  It's now clear in my mind that the problem is with `close_in`.
