### ISSUE TITLE
improving the {In,Out}_channel documentation

### ISSUE THREAD

**Issue by gasche** [ocaml/ocaml#11883]
(I made this suggestion in https://github.com/ocaml/ocaml/pull/10545#issuecomment-1330909234 , but I am moving it to its own issue to make it easier to discuss. I think it could be a nice contribution from someone unfamiliar with the OCaml compiler codebase.)

> I had a look at the documentation of `In_channel` in the manual, and I think that it would benefit from a better organization.
>
> Current .mli definition:
> https://github.com/ocaml/ocaml/blob/8e12c01/stdlib/in_channel.mli
>
> It would be nice to have:
> -  sections that group the function in related clusters, with the more common first (we probably don't need functions about seeking mixed in the middle of the documentation, for example)
> - a code example or two that demonstrates the basic features that everybody needs (`with_open` and `input_all`, I guess?)
>
> (Same for Out_channel I guess?)
>
> Related work:
> - @dbuenzli has done similar work on [String](https://github.com/ocaml/ocaml/pull/9891) and [Set and Map](https://github.com/ocaml/ocaml/pull/11410).
> - @c-cube has worked on [examples](https://github.com/ocaml/ocaml/pull/11476) for various stdlib modules; note the suggested approach to have the examples at the end of the module with a forward reference at the beginning. The [queue.mli](https://github.com/ocaml/ocaml/blob/6978b365cd2bedd989fb5a735c9326d3448d20f8/stdlib/queue.mli#L19) documentation can be taken as an example to reproduce this pattern.

We could of course consider all the modules of the standard library, and we definitely should! But {In,Out}_channel are very recent so we have a chance to make the documentation good before most prospective users encounter it.

**Comment by kiranandcode** [comment]
I'd like to take a stab at this!

**Comment by gasche** [comment]
This is great, thanks @Gopiandcode!

**Comment by dbuenzli** [comment]
This can be closed.

**Comment by gasche** [comment]
Now which module should we open an issue about next?
