### ISSUE TITLE
add warning: "missing mli file"

### ISSUE THREAD

**Issue by mobileink** [ocaml/ocaml#11890]
This is a low-priority feature request.

When the compiler needs to find a cmi file, it evidently looks for the mli file first, in the directory containing the ml file.  If it cannot find it, it infers the signature from the ml file, even if the cmi file exists, which may result in a compilation error for the ml file.

This may be unlikely to happen in most situations (using makefiles, dune, etc.) but it can be a problem for build tooling.  It would be helpful if the compiler were to issue an alert if it finds the cmi file but not the mli file.

Example: utils/load_path.ml.  Compiling this without the corresponding cmi file yields:

```
let auto_include_otheribs =
    ^^^^^^^^^^^^^^^^^^^^^
The type of this expression
(string -> unit) ->
(Dir.t -> '_weak1 -> '_weak2 option) -> '_weak1 -> '_weak2,
contains type variables that cannot be generalized"
```

since the type decl in load_path.mli is

```
val auto_include_otherlibs :
  (string -> unit) -> auto_include_callback
```

The problem I had is that `load_path.cmi` was compiled and present in the directory containing `load_path.ml`, but `load_path.mli` was not in that directory.  This was a bug in my build code, which took a little time to figure out. It would have been immediately obvious if the compiler were to have issued a warning conveying the message "hey, I could not find load_path.mli but I found load_path.cmi in the directory where I expected to find load_path.mli.  So I'm going to infer load_path.mli from load_path.ml, which might not be what you want."

An alternative would be to just use the cmi file even in the absence of the mli file.  Which is what I would expect, intuitively.

**Comment by gasche** [comment]
The problem here is that, if the module does not have a .mli, then the .cmi is generated from the .ml itself. So:
- we cannot warn about this situation
-  if we used the .cmi to type-check the .ml, we would just check the .ml file against the interface of an older version of itself, which is probably very wrong.

The relation between "OCaml concepts inside the language" and "files" is a bit messy in various places, and the notion of "compilation unit" as a pair of an interface and an implementation is a bit fragile in edge cases (.ml with no .mli, .mli with no .ml, trying to have them in different places etc.).

**Comment by gasche** [comment]
I believe that none of the suggestions in the feature request can be acted upon, due to our support for single-.ml compilation units. Is it okay to close the issue?

**Comment by mobileink** [comment]
I just want a warning.  If I have foo.ml and foo.cmi but no foo.mli in the same directory, something is probably wrong. I don't see why we cannot warn about this.

In my view this is doubly warranted, since it is by no means clear to newcomers that searching for a cmi file involves the mli file.

**Comment by mobileink** [comment]
Also you mentioned "if the module does not have a .mli, then the .cmi is generated from the .ml itself. So:we cannot warn about this situation"

But in this case the module does have an mli file. Its just not where the compile expects it. But the user knows its there.

**Comment by gasche** [comment]
I don't follow. If I do, in an empty directory

```
$ echo "let x = 1" > foo.ml
$ ocamlc -c foo.ml         # creates foo.cmi and foo.cmo
$ echo "let x = true" > foo.ml
$ ocamlc -c foo.ml
```

at this point we have `foo.cmi` and `foo.ml` and `foo.cmo` in the load path, and we are asking the compiler to compile `foo.ml`. We don't want a warning here (or an error), things should just work. How would your suggestion work in this case?

**Comment by anmonteiro** [comment]
Out of curiosity, how is this different from warning 70?

**Comment by dbuenzli** [comment]
Also sometimes you actually do want your `mli` in another dir and yet make them constrain a .ml file (This was not possible until recently, see https://github.com/ocaml/ocaml/issues/9717). You don't want a warning in that case either.

**Comment by mobileink** [comment]
@gasche Fudge, I forgot about leftovers.  I wonder if the compiler could detect that the cmi file was create by inference from the ml file and not from an mli file.

@anmonteiro Good question. The manual says 70 is "missing-mli" but does not say what would trigger it.

@dbuenzli I had not noticed `-cmi-file`. That's great, makes cmi deps explicit.  I think that will work for my use case.

Thanks all.
