### ISSUE TITLE
OCaml 5 regression: custom finalizers not running at shutdown

### ISSUE THREAD

**Issue by gadmm** [ocaml/ocaml#11909]
In OCaml 4, finalizers of custom blocks (which are C functions that normally do not access the runtime) are guaranteed to be called during shutdown. In OCaml 5, it seems that this behaviour has been removed; however I have not seen a discussion about this change being deliberate.

This is to discuss whether this is a regression, and if so, to track progress in reimplementing it.

**Comment by kayceesrk** [comment]
This is not deliberate and a regression if OCaml 4 custom finalisers are guaranteed to be called at shutdown. Would you be able to point to the documentation where it says so?

**Comment by gadmm** [comment]
As it turns out, this is written in https://v2.ocaml.org/manual/intfc.html#sec516. (It could have been that this was not documented, but I think this sort of reliable and expectable behaviour could have become depended-upon implicitly.)

**Comment by kayceesrk** [comment]
The linked documentation describes the behaviour of `caml_shutdown` and unloadable runtime. But what you are saying is that the behaviour that custom finalisers are always run isn't documented but depended on in practice. Is that right? 

I also wondered whether this relates to memory cleanup at exit, which is known not to work in OCaml 5 https://github.com/ocaml/ocaml/issues/10865.

**Comment by gadmm** [comment]
As I look closer, I realise that caml_shutdown is only called automatically when the cleanup_at_exit mode is on. This was an oversight on my part. So in fact custom finalizers were not always running on shutdown. What is left of this issue is indeed redundant with #10865, so let me close it.
