### ISSUE TITLE
`fenceless_get` to avoid pessimistic memory model on ARM

### ISSUE THREAD

**Issue by polytypic** [ocaml/ocaml#11902]
Consider the following prototypical template for lock-free algorithms:

```ocaml
let rec prototypical_lock_free_algorithm () =
  let expected = Atomic.get atomic in
  let desired = (* pure computation from expected *) in
  if not (Atomic.compare_and_set atomic expected desired) then
    (* lost the race - maybe retry *)
  else
    (* won the race *)
```

The above effectively performs two acquire fences: both the `Atomic.get` and the `Atomic.compare_and_set` perform an acquire (or stronger) fence.

The first fence, by `Atomic.get`, is not necessary for the correctness of the algorithm.

The unnecessary fence is "free" on x86 (as there is no way to avoid it), but, according to my experiments, on ARM (Apple M1) the unnecessary fence can be quite expensive.

One can work around this by introducing a [`fenceless_get`](https://ocaml-multicore.github.io/multicore-magic/multicore-magic/Multicore_magic/index.html#val-fenceless_get) operation:

```ocaml
let fenceless_get (atomic : 'a Atomic.t) = !(Obj.magic atomic : 'a ref)
```

And replace `Atomic.get` with `fenceless_get`:

```ocaml
let rec prototypical_lock_free_algorithm () =
  let expected = fenceless_get atomic in
  let desired = (* pure computation from expected *) in
  if not (Atomic.compare_and_set atomic expected desired) then
    (* lost the race - maybe retry *)
  else
    (* won the race *)
```

I have measured noticeable performance improvements in lock-free algorithms on ARM (Apple M1) using `fenceless_get`.  One example [here](https://github.com/ocaml-multicore/kcas/pull/20#issuecomment-1385073524) is public at the moment.  More work needs to be done to properly quantify the issue, but it does seem significant.

I would consider it unfortunate if the OCaml memory model would impose a significant penalty on ARM for such a common lock-free programming pattern.

There are probably many ways to address this. Adding `fenceless_get` is perhaps one potential approach, but it would require changes to the memory model.

**Comment by bnguyenvanyen** [comment]
Relevant: https://github.com/ocaml/ocaml/pull/10798
Adding `modify` as it is does not avoid the `get`, but it could use a `fenceless_get` inside `Atomic` without exposing it.

**Comment by kayceesrk** [comment]
CC @stedolan @maranget since this is related to relaxed memory model.

**Comment by gadmm** [comment]
The use of `fenceless_get` is likely discouraged as it stands, as it probably can be subject to code transformations you do not expect.

However, the conclusion of the memory model paper left the door open to future introduction of relaxed atomic operations. So it's nice to collect use-cases. Another use-case was the optimal implementation of thread-safe lazys (briefly discussed inside https://github.com/ocaml-multicore/ocaml-multicore/issues/750).

Lastly if an atomic operation was introduced to map to `ldr`, another point to consider is that it would be nice to bake into its model the dependency ordering, whereby one can reason that first-published writes are seen, which makes it stronger and more useful than C `relaxed` for the same cost (previously discussed inside https://github.com/ocaml/ocaml/pull/10995).

**Comment by polytypic** [comment]
> The use of `fenceless_get` is likely discouraged as it stands, as it probably can be subject to code transformations you do not expect.

What would be an example of such a transformation?

The idea with `fenceless_get` is that it is essentially a read of a mutable location (and in this pattern it is followed by a mutation of an atomic location) and that should limit the potential transformations that might be applied.

**Comment by gadmm** [comment]
In this case I do not know, but the burden of proof is on you :) When I was exploring such hacks, I was contemplating something similar but with `Sys.opaque_identity` inside of `!` to prevent any movement.

**Comment by polytypic** [comment]
> the burden of proof is on you

When it comes to code transformation it is easy to avoid this issue altogether: simply make it so that `fenceless_get` is treated the same as `Atomic.get` when it comes to code transformations.

Q.E.D.

*Addition*: The workaround implementation of `fenceless_get` is just to illustrate the idea.  An actual implementation, of course, may require compiler support.

**Comment by kayceesrk** [comment]
@gadmm Do you mean something like

```ocaml
let fenceless_get (atomic : 'a Atomic.t) = !(Sys.opaque_identity (Obj.magic atomic : 'a ref))
```

**Comment by gadmm** [comment]
> When it comes to code transformation it is easy to avoid this issue altogether: simply make it so that fenceless_get is treated the same as Atomic.get when it comes to code transformations.

@polytypic But you were proposing `fenceless_get` as defined above, which you have also published in your library `multicore-magic` on opam. (Edit: your _addition_ as an edit did not appear in the e-mail I received.)

Adding relaxed atomics to OCaml requires an extension of the memory model, and the way the present issue can help in my opinion is in collecting interesting use-cases and benchmarks.

@kayceesrk Yes, this is my first idea to fix the usage I proposed at #10995, but note that it might not be this exactly in the end or might not work at all.

**Comment by gadmm** [comment]
I propose to change the title of this issue, to something like "Add relaxed atomic operations to OCaml".

**Comment by gasche** [comment]
I mentioned this to @fpottier who asked how that fits the operational semantics of OCaml's memory model. Currently non-atomic references have a "frontier" of values, while atomic references have exactly one value. My intuition is that one would basically make the product of both notions, a mixed atomic/non-atomic references with a frontier of values, which includes a designated "atomic value" that is observed by atomic reads (which also remove the other values from the frontier), while non-atomic reads can observe any value from the frontier and do not update the frontier.

**Comment by gadmm** [comment]
You are starting from the definition of fenceless_get above and trying to work a memory model starting from the operational model. I can see how your proposition makes sense (for instance, in the example, if the race is lost then one re-tries and the second non-atomic read gets the updated value).

Does this say anything about the available programs transformations for non-atomic reads for those mixed locations?

Can the very first non-atomic read in the loop be moved earlier by transformation after inlining? This could make the first value systematically stale, force a re-try, and double the cost of the happy path in your lock-free operation.

Furthermore, if such transformations are not possible or disabled (for those mixed locations), users are likely to find a use of non-atomic reads with a read-copy-update strategy. (It would be very hard to _not_ have it work in practice given the memory safety guarantees.) If one wants to match the theory with the likely practice, the memory model needs to be improved to properly account for initializing writes (in a way that better matches the notion of first publishing write used by the runtime implementation). But that is bit of a tangent.

This is all I have to say off the top of my head.

**Comment by gasche** [comment]
It's not really about the definition, but from the intent I believe which is to have a "relaxed" read -- the OCaml memory model has no notion of "relaxed", so let's say just a "non-atomic" read. In the C runtime code we already discussed the fact that certain locations are accessed with a mix of atomic and non-atomic accesses. I find it natural to consider the same thing within the OCaml memory model, which probably has a simpler description (than C) in this case. (I don't know if we want to seriously consider this, there is a lot of value in keeping a simple memory model. But if we want to think about it, I think this mixed non-atomic/atomic model is the right approach.)

> Does this say anything about the available programs transformations for non-atomic reads for those mixed locations?

I would say: let's allow things that are sound for the operational semantics I sketched above.

> Can the very first non-atomic read in the loop be moved earlier by transformation after inlining?

Absolutely.

> This could make the first value systematically stale, force a re-try, and double the cost of the happy path in your lock-free operation.

Yes.

But in the uncontended cases this makes the happy path cheaper. I think of this as an optimistic optimization, assuming lack of contention, and I think it makes some sense. (Again, I'm not saying that we should necessarily encourage it as a language feature.)

**Comment by kayceesrk** [comment]
Would it matter if we disable all compiler optimisations on `fenceless_get` (using `Sys.opaque_identity` or implementing it in a more complicated fashion as a compiler primitive)? The observation from @polytypic is that it is the fences in `Atomic.get` that kills the performance. `fenceless_get` is used by experts where they're trying to read a "recent" value without having to pay the cost of reading the "latest" value. So for

> Can the very first non-atomic read in the loop be moved earlier by transformation after inlining?

I would say no, and

> This could make the first value systematically stale

I wouldn't want the value to be systematically stale.

This also makes integrating `fenceless_get` into the memory model and ensuring that LDRF is preserved easier.

**Comment by gadmm** [comment]
@gasche: note that the model describes allowable transformations, and the compiler is free to treat differently non-atomic reads and relaxed reads according to heuristics that are specific to each. So one could still disable optimizations for `fenceless_get`. One only cannot rely on this model to reason about this non-staleness.

I think we globally agree; however it is still unclear to me that @gasche's reasoning is enough to show that `fenceless_get` as defined above implements this model. (Here it is simpler if optimizations are removed, maybe this is what @kayceesrk means.)

**Comment by kayceesrk** [comment]
> Here it is simpler if optimizations are removed, maybe this is what @kayceesrk means.)

Yes. This is what I mean.

**Comment by polytypic** [comment]
> I propose to change the title of this issue, to something like "Add relaxed atomic operations to OCaml".

I have no (strong) objection to this.

The reason for proposing only `fenceless_get` is that such an operation seems to be highly common in lock-free algorithms and seems to provide significant benefits on ARM.

There are definitely other potentially useful relaxed atomic operations.  In particular, it is not uncommon in lock-free algorithms to rely only on release fences to ensure that mutations are published to other cores in a desired order.  For example, the [Chase-Lev work-stealing deque](https://www.dre.vanderbilt.edu/~schmidt/PDF/work-stealing-dequeue.pdf) relies on that.  When an element is pushed to the deque by the owner, it is (only) necessary to ensure that the element is written to the backing array before an index is incremented which makes the added element visible to thieves.  Dually, when an item is popped, the owner first decrements the index, to stop thieves, and then proceeds to try to get an element.  In both cases full fences are not necessary.  Unfortunately, at the moment, it is difficult to properly measure the performance penalty from not having a release-only atomic set, because there is no way to generate such an operation in OCaml.  (I suspect the penalty is less severe as fences cannot be completely eliminated in those cases.)

**Comment by polytypic** [comment]
FYI, I experimented further with `fenceless_get` and `fenceless_set` in my [Chase-Lev work-stealing deque implementation](https://github.com/polytypic/par-ml/blob/649917b5cfdc4da764bad45a7e672f02dfee92dc/src/main/DCYL.ml#L67-L184).  It seems that the use of `fenceless_get` provides measurable performance benefits on ARM (Apple M1).  OTOH, use of `fenceless_set` does not seem to improve performance on the same machine in this case.

Note that this experiment says nothing about the potential benefits of having a release fence (or a store operation with only a release fence).  All the `Atomic.incr dcyl.hi` calls in the code could be replaced with something like `release_fence (); fenceless_set dcyl.hi (hi + 1)` as it is only required that the writes before the update of the `hi` index be published before it.

**Comment by polytypic** [comment]
FYI, I created [a PR in `kcas` using fenceless operations](https://github.com/ocaml-multicore/kcas/pull/21/files).  In that PR there is a brief comment on each use of a fenceless operation that argues why that particular use of a fenceless operation is safe.

**Comment by kayceesrk** [comment]
@polytypic, please can you leave a comment as to why this issue is being closed?
