### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [ocaml/ocaml#11928]
:thinking: I would like to achieve further improvements for components of OCaml software.
(See also [previous clarification attempts](https://github.com/ocaml/ocaml/issues/5350 "Check return codes everywhere").)

:eyes: It can be determined by [the means of static source code analysis](https://en.wikipedia.org/wiki/List_of_tools_for_static_code_analysis#C.2C_C.2B.2B "Tools for code analysis") that several return values from function calls are not used for desirable condition checks.

:thought_balloon: Would you like to add more error handling at places like the following?
* [st_masterlock_init](https://github.com/ocaml/ocaml/blob/569fb0b93bc1c3bc5d20273332e4285609188238/otherlibs/systhreads/st_pthreads.h#L106)
  + pthread_mutex_init()
  + pthread_cond_init()
* [st_masterlock_acquire](https://github.com/ocaml/ocaml/blob/569fb0b93bc1c3bc5d20273332e4285609188238/otherlibs/systhreads/st_pthreads.h#L154)
  + pthread_mutex_lock()
  + pthread_cond_wait()
* [output_stored_text](https://github.com/ocaml/ocaml/blob/9be380d0bc15ba616d855b4f3623481cf1762557/yacc/output.c#L782)
  + fclose()
  + fprintf()
* [process_apostrophe](https://github.com/ocaml/ocaml/blob/9be380d0bc15ba616d855b4f3623481cf1762557/yacc/reader.c#L224)
  fwrite()

**Comment by dra27** [comment]
For `st_masterlock_init`:
https://github.com/ocaml/ocaml/blob/f1550145d4ebe8ee22853d13f97fca288aaef51f/otherlibs/systhreads/st_pthreads.h#L108-L113
... there is already a `FIXME` comment in the code for error handling; PR for that very much welcomed.

For `st_masterlock_acquire`:
https://github.com/ocaml/ocaml/blob/f1550145d4ebe8ee22853d13f97fca288aaef51f/otherlibs/systhreads/st_pthreads.h#L156-L161
... [`pthread_mutex_lock`](https://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_mutex_lock.html) and [`pthread_cond_wait`](https://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_cond_timedwait.html) are not permitted to be interrupted (no `EINTR` return) and all their other error codes would relate to programming errors in the systhreads interface. I'm not sure that's something to be checked on each acquire. It _might_ be worth having in debug mode, but at the moment we don't have specific stubs for the debug runtime for systhreads.

For the ocamlyacc parts, the principal advice is to use Menhir, and the core development team aren't focused on ocamlyacc development. That said, PRs to it are reviewed, if you wish to open one.

I'm not sure that any of these changes require a specific tracking issue (i.e. I think this issue could be closed).

**Comment by elfring** [comment]
Is the component “ocamlyacc” still maintained?

* :thinking: It is just safer to [handle more “exceptional” situations](https://wiki.sei.cmu.edu/confluence/display/c/EXP12-C.+Do+not+ignore+values+returned+by+functions "Do not ignore values returned by functions"), isn't it?
* :crystal_ball: How will chances evolve to benefit any more also from [the means of aspect-oriented software development](https://en.wikipedia.org/wiki/Aspect-oriented_programming "Documentation")?

**Comment by gasche** [comment]
> Is the component “ocamlyacc” still maintained?

I would say that ocamlyacc is in "low-frequency maintenance" mode; we would fix issues that affect many users, and have recently done the work of reviewing and integrating good-quality external contributions. But there is little interest from maintainers in spending their own development time on feature requests or changes that are unlikely to affect users in practice.

**Comment by elfring** [comment]
:thought_balloon: How many software users are affected by [return value ignorance](https://cwe.mitre.org/data/definitions/252.html "Checking more return values") in undesirable ways?

**Comment by gasche** [comment]
I have never received a report from an ocamlyacc user whose root cause was a failure in fclose, fwrite or fprintf. So instead I prefer to spend my time on issues where users are telling us that they are affected.

**Comment by elfring** [comment]
>… root cause was a failure in fclose, fwrite or fprintf.

:thought_balloon: Would you like to test any programs with a device like “[/dev/full](https://en.wikipedia.org/wiki//dev/full "Documentation")”?

-----

:crystal_ball: Would you become interested in [advanced handling of cross-cutting concerns](https://en.wikipedia.org/wiki/Cross-cutting_concern#Examples "Application examples")?

**Comment by gasche** [comment]
Surprisingly enough, most ocamlyacc users don't actually try to generate an OCaml parser from the `/dev/null` grammar, and would probably figure out by themselves how to avoid any weird behavior ensuing.

**Comment by xavierleroy** [comment]
@gasche: don't feed the troll.

@elfring: please take "no" for an answer, otherwise you will be banned from this Github organization, like you were banned from the previous OCaml bug tracker a long time ago.

**Comment by elfring** [comment]
>… try to generate an OCaml parser from the `/dev/null` grammar, …

:thought_balloon: How much do you care for data output failures?

-----

:thinking: Can you become aware that [error detection](https://en.wikipedia.org/wiki/Cross-cutting_concern#Examples "Documentation") belongs to known cross-cutting concerns?

**Comment by xavierleroy** [comment]
@elfring: you have been blocked from interacting with the ocaml organization for 7 days.

**Comment by elfring** [comment]
>…, like you were banned from the previous OCaml bug tracker a long time ago.

:thought_balloon: [My contributions influenced also another bit of useful collateral evolution](https://github.com/ocaml/ocaml/issues/5937#issuecomment-1016211674 "Support for passing more parameters from external files"), didn't they?
