### ISSUE TITLE
Topdirs is not loaded in the toplevel anymore in 5.1

### ISSUE THREAD

**Issue by kit-ty-kate** [ocaml/ocaml#11979]
Since https://github.com/ocaml/ocaml/pull/11745 `Topdirs` is not loaded in the toplevel by default anymore, which means that for instance, the `.ocamlinit` script added automatically in ancient versions of opam (1.2 :grimacing:) doesn't work anymore:
```
File "/home/kit_ty_kate/.ocamlinit", line 3, characters 6-27:
3 |   try Topdirs.dir_directory (Sys.getenv "OCAML_TOPLEVEL_PATH")
          ^^^^^^^^^^^^^^^^^^^^^
Error: Unbound module Topdirs
```
In practice this particular code doesn't do anything anymore and was just an old artifact but breaking similar scripts might not be an intended effect of https://github.com/ocaml/ocaml/pull/11745 so I'm opening this issue to make sure this is intended.

**Comment by nojb** [comment]
At the very least, I think #11745 should be marked as a breaking change.

**Comment by dbuenzli** [comment]
This will likely prove problematic for [`omod`](https://erratique.ch/software/omod)'s bootstrap [here](https://github.com/dbuenzli/omod/blob/2c432f3e51579aa4c4dedd53f46e657c896db78f/src/omod_top.ml) and [here](https://github.com/dbuenzli/omod/blob/master/src/omod_nattop.ml) (`ocamlnat`). 

Is it just the `cmi` not being visible or did it get expunged ? The latter would be rather problematic. If it's the former which directory needs to be included ? A `#directory` directive can be added [here](https://github.com/dbuenzli/omod/blob/2c432f3e51579aa4c4dedd53f46e657c896db78f/src/omod.top) before loading `omod.cma`.

**Comment by Octachron** [comment]
The `topdirs.cmi` file is now a normal toplevel cmi file (and not expunged) in the `compiler-libs` library which is indeed not always visible anymore.  Adding a `#directory "+compiler-libs"` will make the cmi visible. At the same time, making all modules from `compiler-libs` visible doesn't seem ideal.

**Comment by dbuenzli** [comment]
In fact I thought that https://github.com/ocaml/ocaml/pull/11007 had brought us to the one library per directory convention upstream. That doesn't seem to be the case. Is there anything preventing moving to that ? 

If we had that I could then simply add a `#directory "+compiler-libs/toplevel"` which would be more localized.

For example it seems that the `ocaml-compiler-libs` package of JaneStreet does that (it exposes the toplevel stuff in an `Ocaml_toplevel` namespace):

```
> ls $(opam var ocaml-compiler-libs:lib)/toplevel
ocaml_toplevel.a    ocaml_toplevel.cmi  ocaml_toplevel.cmx  ocaml_toplevel.cmxs
ocaml_toplevel.cma  ocaml_toplevel.cmt  ocaml_toplevel.cmxa ocaml_toplevel.ml

> cat $(opam var ocaml-compiler-libs:lib)/toplevel/ocaml_toplevel.ml
(* This file is automatically generated *)

module Genprintval = Genprintval
module Topcommon   = Topcommon
module Topdirs     = Topdirs
module Topeval     = Topeval
module Toploop     = Toploop
module Topmain     = Topmain
module Trace       = Trace

```

**Comment by dbuenzli** [comment]
Btw. I expect this also happens for `Toploop`, which means that [`down`](https://erratique.ch/software/down) must be similarly affected as it does similar gymnastics ([[1]](https://github.com/dbuenzli/down/blob/09b1cedda9a372fc37d95c7642e8567157717753/src/down_top.ml#L6), [[2]](https://github.com/dbuenzli/down/blob/09b1cedda9a372fc37d95c7642e8567157717753/src/down_nattop.ml)) when the supporting archive is [loaded](https://github.com/dbuenzli/down/blob/09b1cedda9a372fc37d95c7642e8567157717753/src/down.top).

**Comment by dra27** [comment]
#11745 removed the need for the typing environment to be enriched with `Topdirs` by default - is it possible that we _still_ need to load topdirs.cmi as in #11382 et al just for compatibility with scripts which took advantage of others things in `Topdirs`?

**Comment by Octachron** [comment]
@dbuenzli , we have kept the existing structure of the `compiler-libs` directory for now.

But this suggests a possible bacward compatible enhancement: we could move `compilerlibs.toplevel` to its own subdirectoy and add this directory to the list of `deprecated-auto-include` directory in the toplevel. Or could it make sense to always add the `compilerlibs.toplevel` directory to the toplevel path?

Concerning `Toploop`, there should be no changes? It was already only visible once the `compiler-libs` directory was added to the path (and `down` works on trunk).

**Comment by dbuenzli** [comment]
> Concerning `Toploop`, there should be no changes? It was already only visible once the `compiler-libs` directory was added to the path (and `down` works on trunk).

In fact I got confused you likely don't need the `.cmi`s in either `omod` or `down`, they compile against `compilerlibs.toplevel` to a `.cma` which is `#load`ed. It's not `#use`d sources, so they don't need to see these `cmis`.

> @dbuenzli , we have kept the existing structure of the `compiler-libs` directory for now.

I don't know what the rationale was behind this move but it feels really strange to have broken compat (if any, most people use `META` files anyways) on `unix`, `str` and `dynlink` but not have followed suit with `compiler-libs`'s sub libraries. It would be nice to have more isolation on these libraries aswell.

**Comment by dra27** [comment]
As a data-point only, `topfind` adds `+compiler-libs` while loading and then removes it at the end of the script.

**Comment by Octachron** [comment]
I am tempted to merely mark the change as breaking for 5.1 rather than adding one layer of deprecation.

The other option that might work would be to split each components of the compiler-libs cmi file in their own subdirectory and make the `ocamltop` cmi visible in the toplevel by default, which would be a different breaking change.

**Comment by avsm** [comment]
Triage meeting: @Octachron will add a breaking change note near the top of the release notes.
