### ISSUE TITLE
Document Stdlib exceptions with alert instead of comment

### ISSUE THREAD

**Issue by yawaramin** [ocaml/ocaml#11994]
Idea initially brought up in https://discuss.ocaml.org/t/poor-mans-static-exception-analysis-with-alerts/11296

With the advent of alerts, we now have a compiler-checkable way to document exceptions. Currently, best practice is to add documentation in the comment, e.g.

```ocaml
val foo : int -> int
(** @raise Invalid_argument if blabla. *)
```

With alerts, we can change this in a fairly mechanical way to:

```ocaml
val foo : int -> int
[@@alert exn "Invalid_argument if blabla"]
```

Since #11024 alerts are rendered by ocamldoc. So the documentation will look effectively the same as before. But by having an alert the usage of functions which raise exceptions can be compiler-checkable, depending on the project preference (enable or disable the `exn` alert, upgrade it to an error for extra safety). The alert should be disabled by default so as to leave existing codebases unaffected.

**Comment by yawaramin** [comment]
This was one of the motivating examples of the alert feature originally: #1804

**Comment by Kakadu** [comment]
Am I understanding correctly that 'alerts' will be reported 
1) when '+exn' switch is enabled; 
2) despite exn is being catched

?

**Comment by yawaramin** [comment]
By default, yes. Alerts are triggered by default currently. And the alert doesn't understand whether an exception has been caught or not. The way to disable the alert as of right now is to explicitly turn it off. You can see examples of this in my branch: https://github.com/ocaml/ocaml/compare/trunk...yawaramin:ocaml:alert-exn

**Comment by yawaramin** [comment]
I should mention that this is already yielding good results. E.g.,

```
File ".../ocaml/stdlib/list.ml", line 196, characters 12-19:
196 |   | a::l -> compare a x = 0 || mem x l
                  ^^^^^^^
Alert exn: Stdlib.compare
Invalid_argument on comparison between function values
```

Meaning, the `List.assoc`, `assoc_opt`, `mem_assoc` and so on functions can potentially throw exceptions if the associative list keys contain function values, because they all use the polymorphic `Stdlib.compare`. Maybe someone already realized this, but the potential exceptions were never documented.

**Comment by Alizter** [comment]
Would it be possible to modify the error message for alerts so that they hint how to disable them? Seeing the current message, it is not immediately obvious what to do, especially if a user is not familiar with alerts.

**Comment by yawaramin** [comment]
The general message for alerts is in the compiler codebase, it should be possible to add a line to it referring to documentation, e.g.

```
Alert exn: Stdlib.compare
Invalid_argument on comparison between function values
🔗 ocaml.org/t/alert
```

And then if that link acted as a shortlink to redirect to the current [alerts chapter](https://v2.ocaml.org/manual/alerts.html) in the manual, that would be ideal. But that is a more general concern to do with compiler messages, I feel it is out of scope for this particular issue.

**Comment by yawaramin** [comment]
As a small and non-invasive first step, I would like to send a PR introducing the `exn` alert to functions which could throw exceptions in the `Effect` module interface.

The impact will be that anyone using `Effect.perform` and the continuation functions will get an alert about possible unhandled effects, already-resumed continuations, etc. They will then need to manually disable the alerts at those points--of course, after ensuring they are properly handling the effects or continuations.

I feel that this will give us two benefits in one: (1) introducing the `exn` alert into a 'low-traffic' part of the OCaml surface API, and (2) getting de facto compile-time effect handler checking (with a little manual work).

Any thoughts on this?

EDIT: I expect this to have low immediate impact because Eio, presumably the biggest user of `Effect`, is doing `perform` in 7 places in the code: https://github.com/ocaml-multicore/eio/search?q=%22effect.perform%22&type=

**Comment by Kakadu** [comment]
Let's imagine the situation.

The caller calls calee :) The callee uses exception-ful functions, the caller writes try-with. OCaml complains about that an exception is possible in callee. The developer decides that it is false positive, and disables it via `[@alert "-exn"]` in all places.
After some time a refactoring happens, another developer removed a few exceptionful functions and removed try-with too. Bot a small exceptionful function with silenced alerts manged to hide from the reviewer's eyes. We got a false negative scenario. 

Any thoughts?

**Comment by gasche** [comment]
My general thoughts on this issue: alerts for effect tracking are a blunt tool, and I doubt that they scale well in practice. It is fine if people want to experiment with this in specialized libraries -- where is your "alert-enabled prelude" for other people to try? But I wouldn't want to use the standard library as a prototype for such experiments.

As for myself, I would rather invest my efforts into something that brings us closer to typed effects, and content myself with what we have for now. (For me personally this means: help people refactor the type-checker so that typed effects, and many other things, become easier to implement.)

If I wanted to work on uncaught exceptions, I would maybe consider reviving the [ocamlexc](https://caml.inria.fr/pub/old_caml_site/ocamlexc/ocamlexc.htm) tool of François Pessaux. (This requires hacking on the type-checker codebase in non-trivial ways.)

**Comment by yawaramin** [comment]
I agree false negative is a problem with this approach. It depends on how heavy the usage of try-with is and how often refactorings remove try-with constructs from code. My feeling is that this is not frequent enough to make this approach generally unworkable.

Another consideration is that any silencing of the alert is very obvious in the code and at worst it takes only one runtime exception raised to notice and remove the unwarranted silencing (or handle the exception).

My aim here is not perfect coverage of all exceptions, but 'good enough' coverage of possible exceptions while making tradeoffs like 'zero runtime cost' i.e. like allocations and fiddling around with combinator operations with the `result` type.

**Comment by yawaramin** [comment]
@gasche that's a fair point and one I will try to work on to see how scalable it really is in practice.
