### ISSUE TITLE
Missed 5.0 manual change for caml_register_global_root

### ISSUE THREAD

**Issue by jberdine** [ocaml/ocaml#12016]
I suspect that the documentation for `caml_register_global_root` in "Interfacing C with OCaml" should be updated for OCaml 5. It currently states:

> Registration of a global variable v is achieved by calling caml_register_global_root(&v) just before or just after a valid value is stored in v for the first time;

Since the implementation inserts the argument into the skiplist of roots immediately, is it still safe to register a root "just before...a valid value is stored"?

**Comment by sadiqj** [comment]
This is still correct. The global roots are only scanned during a minor collection or when a new major cycle is started, both of which happen during a stop-the-world pause.

As long as there's nothing between the global root registration and a valid value being put in the root that could cause a poll in the OCaml runtime (and thus enter a stop-the-world) then this is safe.

**Comment by jberdine** [comment]
Ok great, thanks! I missed that major cycles can only start in the STW section.
