### ISSUE TITLE
[Not a bug but a 'feature']   linking of compiler itself

### ISSUE THREAD

**Issue by progman1** [ocaml/ocaml#12026]
when compiling the compiler stdlib.a gets included twice when call_linker invoked.
this appears to happen as a result of it coming in, in the code below, the objfiles list.
```
let link ~ppf_dump objfiles output_name =
  Profile.record_call output_name (fun () ->
    let stdlib = "stdlib.cmxa" in
    let stdexit = "std_exit.cmx" in
    let objfiles =
      if !Clflags.nopervasives then objfiles
      else if !Clflags.output_c_object then stdlib :: objfiles
      else stdlib :: (objfiles @ [stdexit]) in
```
and then since nopervasives is false is added a 2nd time.
of course this is not a problem for the system linker.
it seems the nopervasives check might be augmented with
no_std_include which after all means not to go looking for the stdlib, so
the code should not be prepending it to objfiles.
but on the other hand std_exit.a is still required as it doesn't appear in the objfiles
argument to 'link'.

**Comment by lthls** [comment]
How are you calling the compiler ? It seems that you may be explicitly passing `stdlib.cmxa` on the command-line, which is neither required nor advised.

**Comment by Octachron** [comment]
@progman1 did you have the time to investigate the issue? I am closing the issue temporarily, but please don't hesitate to re-open once you have a more reproducible example.

**Comment by progman1** [comment]
I was invoking the dune build of the distribution included in the distribution.
adding a print statement to the code above reveals the issue.
it isn't a bug as such because the duplicate is ignored by the system linker.
but I'm not using a system linker and put in a workaround - the extra needless processing makes this a wart.

**Comment by progman1** [comment]
I would re-open this if I knew how. I do not see any button for it.
as implied, the reproducible example comes from simply inserting a List.iter print statement as indicated. do you seriously want a repo of the ocaml sources with a single print statement added?

**Comment by lthls** [comment]
As far as I know the dune files are only used to build compiler-libs, mostly to have merlin working on the compiler's source files. Linking the compilers with dune has never been supported.

**Comment by progman1** [comment]
this doesn't have anything to do with dune. 
I repeat:  I have noticed the compiler doing something odd, have pointed out where in the code it is happening, have pointed out why it is not causing any outward problem, and have reported it here with the single step necessary to observe same.

**Comment by shindere** [comment]
progman1 (2023/09/18 13:24 -0700):
> this doesn't have anything to do with dune.

The thing is, you have said that the bug happens when you try to build
the compiler with Dune. So it is not impossible that it's Dune which is
including the stdlib twice in the invocation of the comiler, which would
indeed be a Dune potential problem to be investigated on the Dune side,
but keeping in mind that the use of Dune to build the compiler is not
officially supported.

> I repeat:  I have noticed the compiler doing something odd, have
> pointed out where in the code it is happening, have pointed out why it
> is not causing any outward problem, and have reported it here with the
> single step necessary to observe same.

I'm sorry, I didn't understand your report.

If the problem is still there, could you please provide both an example
of a source program and an example of an invocation ofthecompiler to
compile and link this source program that illustrate the issue.

**Comment by progman1** [comment]
sorry, you're right. the dune invocation does indeed include stdlib.cm(x)a
while the standard Make build does not.

**Comment by shindere** [comment]
progman1 (2023/09/19 04:23 -0700):
> sorry, you're right. the dune invocation does indeed include stdlib.cm(x)a
> while the standard Make build does not.

No problem. Happy we got this clarified. If you need to build the
compiler, I'd advise to stick to the GNU make based build system asthis
is the maintained one.
