### ISSUE TITLE
Unix.times is broken in --no-flat-float-array mode

### ISSUE THREAD

**Issue by samwgoldman** [ocaml/ocaml#12035]
The C implementation of this function returns a flat float array:

https://github.com/ocaml/ocaml/blob/71aef9e0494819ed3d200439408e96963c7d4103/otherlibs/unix/times_unix.c#L35

When this is passed back to OCaml, it is re-interpreted as a record of floats:

https://github.com/ocaml/ocaml/blob/71aef9e0494819ed3d200439408e96963c7d4103/otherlibs/unix/unix_unix.ml#L463-L467

But in --no-flat-float-array mode, a record of floats is expected to be boxed.

For example, the following program:

```
let () =
  Printf.fprintf stdout "times tag = %d, double array tag = %d\n"
    (Obj.tag (Obj.repr (Unix.times ())))
    Obj.double_array_tag
```

prints the following regardless of --no-flat-float-array:

```
times tag = 254, double array tag = 254
```

I would expect the tag to be `0` when `--no-flat-float-array` is enabled.

**Comment by gasche** [comment]
Good catch! I see two ways to fix this, broadly:

- use "normal array operations" (`caml_make_vect`, `caml_array_set`) to manipulate a float that is either flat or non-flat depending on the configuration
- use "floatarray operations" (`caml_floatarray_create`, `caml_floatarray_set`) and then `Array.Floatarray` on the OCaml side to systematically manipulate flat arrays

(Using `Array.Floatarray` without any change on the C side would be enough for now, but I would rather use the "proper" array APIs to avoid similar issues in the future.)

**Comment by samwgoldman** [comment]
I believe it should be possible to use `caml_alloc_float_array` along with `Double_field` and `Store_double_field` from the C code, and have the resulting value be usable as a `float array` or record of all-`float` values in either mode.

**Comment by nojb** [comment]
> But in --no-flat-float-array mode, a record of floats is expected to be boxed.

I don't think this is right. A record of floats is still expected to be unoxed even in `no-flat-float-array` mode.

**Comment by alainfrisch** [comment]
I don't think that's related to arrays at all (it's a "coincidence" that the representation for float records matches the one of unboxed floatarrays). On the OCaml side, we have a record with an "unboxed float" representation, we need to use C functions to manipulate such blocks:

  - Allocate the block with `caml_alloc(n_fields * Double_wosize, Double_array_tag)`
  - Set the fields with `Store_double_flat_field(v, idx, f)`

I'd suggest defining an alias for Double_array_tag, which gets rid of the "array" terminology (e.g. Flat_doubles_tag?).

**Comment by samwgoldman** [comment]
Ah, thank you for correcting my misunderstanding! C code that constructs a record of floats must use the "flat float" APIs. Closing :)

**Comment by nojb** [comment]
@samwgoldman not so fast! there _is_ a bug here, but a slightly different one: since the record always uses an unboxed representation, I believe it is _wrong_ to use `Store_double_field` because this function assumes a _boxed_ representation in `-no-flat-float-array`. One should instead use `Store_double_flat_field`.

Do you agree? Would you like to propose a patch?

**Comment by samwgoldman** [comment]
`Store_double_field` appears to check the tag at runtime, so I think it's correct, but `Store_double_flat_field` would avoid the unnecessary tag check. I will submit a patch (in the morning)

**Comment by nojb** [comment]
> `Store_double_field` appears to check the tag at runtime, so I think it's correct, but `Store_double_flat_field` would avoid the unnecessary tag check. I will submit a patch (in the morning)

Ah yes, it is me that got mixed up now...

**Comment by samwgoldman** [comment]
The `Store_double_field` vs. `Store_double_flat_field` distinction is so minor, I suggest closing this, just to avoid wasting others' time reading through the discussion :)

Maybe there is some useful follow-up, per @alainfrisch's comment, about introducing APIs for working with records-of-floats from C. I think at least some of my confusion stemmed from the "array" names in the current APIs.

**Comment by nojb** [comment]
@samwgoldman: I didn't understand if you were still meaning to submit a patch or not, but since it is such a small change, I went ahead and did it (#12036), I hope it's OK.
