### ISSUE TITLE
Out-of-memory crash when using a second domain

### ISSUE THREAD

**Issue by talex5** [ocaml/ocaml#12042]
This program crashes after a few seconds with an out-of-memory error:
```ocaml
let main () =
  while true do
    ignore (Bytes.create (64 * 1024))
  done

let () =
  Domain.spawn main |> Domain.join
```

```
$ ocamlopt --version
5.0.0

$ ocamlopt -o test.exe test.ml && ./test.exe
fish: “./test.exe” terminated by signal SIGKILL (Forced quit)
[336325.516584] Out of memory: Killed process 221782 (test.exe) total-vm:103708848kB, anon-rss:6535600kB, file-rss:0kB, shmem-rss:0kB, UID:1000 pgtables:202340kB oom_score_adj:0
```
If I remove the `Domain.spawn` bit and just run `main ()` directly, then there is no problem.

I also tested with https://github.com/ocaml/ocaml/pull/11903 at @sadiqj's suggestion and it still fails, though @kit-ty-kate noted that:
> I just tested with this branch, and while it ultimately still fails the same way, it does is significantly slower.
> - With 5.0.0 and trunk it takes just 3 seconds to OOM-kill with 32GB of RAM
> - With this branch it takes a whole good minute and some change

/cc @kayceesrk

**Comment by kayceesrk** [comment]
I confirmed this behaviour on trunk. I have also confirmed that even with #11903, which aims to fix idle domain GC, the problem is mitigated but does not go away.

**Comment by gasche** [comment]
From a distance it looks like #11903 does remove a large part of the problem, so maybe we should try to finalize this PR as a first step to work on the present bug?
