### ISSUE TITLE
Polymorphic variant tags need not be capitalized, unlike what the manual says

### ISSUE THREAD

**Issue by OlivierNicole** [ocaml/ocaml#12047]
The manual at the time I’m writing this states that polymorphic variant tags are of the form `` `tag-name ``, where `tag-name` is defined as:
https://github.com/ocaml/ocaml/blob/851b5b9a717000ba81813d3f2e213591ad4c2707/manual/src/refman/names.etex#L51-L53

However, tags starting with a lowercase letter are accepted as well:
```
OCaml version 5.0.0
Enter #help;; for help.

# let x = `test;;
val x : [> `test ] = `test
```

**Comment by gasche** [comment]
The intent was always to keep them capitalized. We are too afraid of the backward-compatibility impact of disallowing uncapitalized variant names now, but we want to keep the possibility to do it in the future by keeping the documentation restricted.
