### ISSUE TITLE
Syntax error example: dependent notation in function types

### ISSUE THREAD

**Issue by mimoo** [ocaml/ocaml#12055]
I'm getting the following error on what seemed to me at first sight valid OCaml:

```
File "src/lib/pickles_types/plonk_types.mli", line 105, characters 42-43:
105 |     (impl : 'f Snarky_backendless.Snark0.m) ->
                                                ^
Error: Syntax error
```

Took me some time to realize that in a function signature I had to remove the `impl :`, maybe a better error here to indicate that would have helped : o

**Comment by gasche** [comment]
There is long-term ongoing work on producing better explanations for syntax errors, see #11939. The present issue is mostly a duplicate (with a specific example that I emphasized with a new issue title so that people can find it back later), so I'm closing.
