### ISSUE TITLE
opam switch create fails

### ISSUE THREAD

**Issue by jeremydaw** [ocaml/ocaml#12071]
<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><><><>
-> installed base-bigarray.base
-> installed base-threads.base
-> installed base-unix.base
-> retrieved ocaml-base-compiler.4.11.1  (cached)
[ERROR] The compilation of ocaml-base-compiler.4.11.1 failed at "make -j3
        world.opt".

#=== ERROR while compiling ocaml-base-compiler.4.11.1 =========================#
# context     2.1.3 | linux/x86_64 |  | https://opam.ocaml.org#8090be62
# path        ~/.opam/coq-eq-8.16.1/.opam-switch/build/ocaml-base-compiler.4.11.1
# command     ~/.opam/opam-init/hooks/sandbox.sh build make -j3 world.opt
# exit-code   2
# env-file    ~/.opam/log/ocaml-base-compiler-8866-ec5c8e.env
# output-file ~/.opam/log/ocaml-base-compiler-8866-ec5c8e.out
### output ###
# [...]
# gcc -c -O2 -fno-strict-aliasing -fwrapv -Wall -Wdeclaration-after-statement -fno-common -fexcess-precision=standard -fno-tree-vrp -ffunction-sections -g -D_FILE_OFFSET_BITS=64 -D_REENTRANT -DCAML_NAME_SPACE   -DNATIVE_CODE -DTARGET_amd64 -DMODEL_default -DSYS_linux   -o signals_nat_n.o signals_nat.c
# signals_nat.c:198:13: error: variably modified ‘sig_alt_stack’ at file scope
#   198 | static char sig_alt_stack[SIGSTKSZ];
#       |             ^~~~~~~~~~~~~
# make[3]: *** [Makefile:343: signals_nat_n.o] Error 1
# make[3]: *** Waiting for unfinished jobs....
# make[3]: Leaving directory '/home/jeremy/.opam/coq-eq-8.16.1/.opam-switch/build/ocaml-base-compiler.4.11.1/runtime'
# make[2]: *** [Makefile:777: makeruntimeopt] Error 2
# make[2]: Leaving directory '/home/jeremy/.opam/coq-eq-8.16.1/.opam-switch/build/ocaml-base-compiler.4.11.1'
# make[1]: *** [Makefile:223: opt.opt] Error 2
# make[1]: Leaving directory '/home/jeremy/.opam/coq-eq-8.16.1/.opam-switch/build/ocaml-base-compiler.4.11.1'
# make: *** [Makefile:283: world.opt] Error 2

<><> Error report <><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
+- The following actions failed
| - build ocaml-base-compiler 4.11.1
+- 
+- The following changes have been performed (the rest was aborted)
| - install base-bigarray base
| - install base-threads  base
| - install base-unix     base
+- 

<><> ocaml-base-compiler.4.11.1 troubleshooting <><><><><><><><><><><><><><><><>
=> A failure in the middle of the build may be caused by build parallelism
      (enabled by default).
      Please file a bug report at https://github.com/ocaml/ocaml/issues
=> You can try installing again including --jobs=1
      to force a sequential build instead.

**Comment by Octachron** [comment]
You are probably missing an `opam update` since your installation did not seem to install the opam patch for compatibility with new versions of gcc on old versions of OCaml. 

Moreover, as a general advice, I recommend to use a version of OCaml at least as recent as  your version of gcc.

**Comment by dra27** [comment]
Indeed, your installation is [8090be62](https://github.com/ocaml/opam-repository/tree/8090be62) from January 2021, so you're missing https://github.com/ocaml/opam-repository/pull/19855 from January last year.
