### ISSUE TITLE
"I/O error" with `.pp.ml` file when running `dune build . -w`

### ISSUE THREAD

**Issue by mimoo** [ocaml/ocaml#12081]
I often runs into these kind of errors when running `dune build . -w`:

```
File "src/lib/snarky/src/base/checked_runner.ml", line 1:
Error: I/O error: src/lib/snarky/src/base/checked_runner.pp.ml: No such file or directory
Had errors, waiting for filesystem changes...
```

I can simply quit and restart `dune build . -w` and this always seems to fix that issue. For example, in this case I get:

```
Entering directory '/Users/david/Work/other_mina'
File "src/lib/snarky/src/base/runners.ml", line 89, characters 4-40:
89 |     Backend.Run_state.set_private_inputs state input ;
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Error: Unbound value Backend.Run_state.set_private_inputs
Hint: Did you mean get_private_inputs?
Had errors, waiting for filesystem changes...
```

First, I'm not sure what's a `.pp.ml` and I don't think this extension should be exposed to developers. Second, I'm not sure if this more of an issue with `dune` and if I should post there instead.

**Comment by gasche** [comment]
Yes, this is probably a dune error, at least this is not a compiler message.

Dune uses .pp.ml as temporary files to store the output of pre-processing a file of source code. This is an internal choice of dune (whose knowledge might be convenient to users if they want to inspect the postprocessed input), not a decision of the compiler.
