### ISSUE TITLE
Possible data race in `runtime/unix.c`

### ISSUE THREAD

**Issue by gadmm** [ocaml/ocaml#12096]
The code below uses unsynchronized runtime initialization of a local static variable, and it is not clear to me by looking at the callers that the initial call is performed non-concurrently.

https://github.com/ocaml/ocaml/blob/ac52c3ab4a545d77eea034993a0947ba5e79762b/runtime/unix.c#L433-L442

**Comment by NickBarnes** [comment]
Indeed, there is a race here, in the sense that it is possible for multiple threads to call `mach_timebase_info()`. This is generally viewed as harmless (see https://github.com/apple/darwin-xnu/blob/2ff845c2e033bd0ff64b5b6aa6063a1f8f65aa32/libsyscall/wrappers/mach_timebase_info.c#L33-L36, where Apple themselves encounter the same problem in the implementation of this function, in the C library). Worth adding a comment to that effect, I guess. We could do better with a CAS or similar. Assuming this code is for MacOS, note that [Apple deprecate](https://developer.apple.com/documentation/driverkit/3438076-mach_absolute_time) use of this function and `mach_absolute_time()` (a few lines lower), in favour of `clock_gettime_nsec_np(CLOCK_UPTIME_RAW)`.
