### ISSUE TITLE
warning [ignored-partial-application] does not fire on ignoring matches

### ISSUE THREAD

**Issue by gasche** [ocaml/ocaml#12093]
## Context

Yesterday I had a frustrating debugging session with Olivier Martinot. We have a parser in our codebase (very simplified below), and some of the tests of our testsuite check that certain inputs are *rejected* by the parser as they should be.

```ocaml
  let parse input =
    if input = "correct" then `Correct
    else failwith "Parse error"
  
  let test_incorrect input =
    match parse input with
    | exception Failure _ -> true
    | _ -> false
```

Some changes we made to the machinery to display better error messages on parse errors had the surprising effect that our `test_incorrect` tests started failing (the inputs were passing instead of being rejected by the parser as expected). After a frustrating debug session, we realized that the cause was a change to our `parse` function to add a filename parameter:

```ocaml
  let parse ~filename input =
    ignore filename; (* feed it to the lexbuf etc. *)
    if input = "correct" then `Correct
    else failwith "Parse error"
  
  let test_incorrect input =
    match parse input with
    | exception Failure _ -> true
    | _ -> false
```

The bug is caused by the fact that `parse input` is now a partial application expecting a filename parameter, and in particular does not run any computation and never raises the `Failure` exception.

If we had written one of the following equivalent versions, we would have immediately caught our mistake thanks to Warning 5;

```ocaml
  let test_incorrect input =
    try let _ = parse input in true
             (* ^^^^^^^^^^^ *)
    with Failure _ -> false

  let test_incorrect input =
    try parse input; true
     (* ^^^^^^^^^^^ *)
    with Failure _ -> false

  (*
  Warning 5 [ignored-partial-application]: this function application is partial,
  maybe some arguments are missing.
  *)
```

(Note: other ways to avoid the issue would have been to add a typing annotation on the result of `parse input`, or to use a `result` type instead of an exception.)

## Proposal

I propose to extend warning 5 [ignored-partial-application] to matches that ignore their scrutinees, in addition to `ignore` and let-bindings that ignore their scrutinee.

**Comment by smuenzel** [comment]
> ## Proposal
> 
> I propose to extend warning 5 [ignored-partial-application] to matches that ignore their scrutinees, in addition to `ignore` and let-bindings that ignore their scrutinee.

This sounds like a good idea. As an aside, I was always confused why the following code segments are treated differently, even though the seem to do the same thing:
```
match x with | pattern -> ...
```
```
let pattern = x in ...
```
Maybe there are other cases where treating them differently leads to non-intuitive behaviour?

**Comment by nojb** [comment]
> I propose to extend warning 5 [ignored-partial-application] to matches that ignore their scrutinees, in addition to `ignore` and let-bindings that ignore their scrutinee.

Sounds like a good idea. However, we need to have a way to indicate when we actually want to pattern match on a partial application. For example, in the compiler there are several uses of the following pattern:

https://github.com/ocaml/ocaml/blob/bcffd84a9b0e38a3ca02a1ffd2de54541f3bcb9f/typing/env.ml#L2594-L2597

which ~~triggers~~ would trigger the warning.

**Comment by gasche** [comment]
No, actually the warning would not be triggered if the partial application result is named, only if the only value pattern is `_`; this is similar to `let _ = ...` vs. `let mark = ...`. Furthermore, for the `let` and `ignore` forms it is already possible to silence the warning by adding a type annotation, I expect that the same would work for `match`.

@smuenzel I agree in theory but I'm not willing in practice to go through the type-checking code for both (which is quite complicated) and try to reason about whether they do the same thing in the special cases of `match` with only toplevel patterns.

**Comment by nojb** [comment]
I gave it a try: #12094
