### ISSUE TITLE
Consider licensing the Stdlib sample code under public domain/CC0

### ISSUE THREAD

**Issue by dbuenzli** [ocaml/ocaml#12095]
For users it's nice to be able to cut and paste sample code and remix it the way they see it fit without being encumbered by licensing duties. 

One way of doing this is to license the sample code present in Stdlib reference docs under a public domain/[CC0](https://creativecommons.org/share-your-work/public-domain/cc0/) license.

If there's agreement that this is a good thing then a blurb could be added [here](https://github.com/ocaml/ocaml/blob/trunk/manual/src/library/stdlib-blurb.etex) in the manual. Something like "All the sample code found in the reference documentation is in the public domain or available under a CC0 license".

(Note I'm not talking about the code in the tutorials, though that could be considered as well).

**Comment by xavierleroy** [comment]
I'm in favor of applying CC0 to all examples in the Stdlib reference and in the tutorial chapters.  This could be mentioned in the Foreword chapter, at the same place where we say that the OCaml manual is CC-BY-SA.

**Comment by avsm** [comment]
As a point of reference, all the code examples on the ocaml.org website are under the UNLICENSE (https://github.com/ocaml/ocaml.org/blob/main/LICENSE#L41).

The CC0 is preferable to the UNLICENSE these days (as the former is OSI approved), so if the compiler manual switches to CC0 then I can start a switchover of the website content to the same license.

**Comment by xavierleroy** [comment]
I didn't know this UNLICENSE thing, but I feel it fails to address the moral rights issue (*), while CC0 is a lot more careful to abandon copyrights only to the fullest extent allowed by law.  It looks like CC0 is the better choice.

(*) Depending on jurisdiction, moral rights can be transferred, or cannot be transferred but can be waived, or are completely inalienable, making naive public domain dedication statements meaningless.  See https://en.wikipedia.org/wiki/Moral_rights

**Comment by avsm** [comment]
Agreed. There's a [long discussion of CC0 vs UNLICENSE](https://web.archive.org/web/20170301020915/https://lists.opensource.org/pipermail/license-review/2012-January/001386.html) on the OSI mailing lists, and it seems to boil down to the fact that the UNLICENSE is written for humans, and CC0 is "compiled" to be applicable in as many jurisdictions as possible.

**Comment by xavierleroy** [comment]
> the UNLICENSE is written for humans

It is written for US and UK residents, where "waiving all IP rights" makes sense.  It makes little sense in France or Germany, for instance.
