### ISSUE TITLE
The `PrioQueue` example in chapter 2 of the reference manual has wrong complexity

### ISSUE THREAD

**Issue by xavierleroy** [ocaml/ocaml#12090]
The binary tree becomes unbalanced after a number of `insert` and `remove_top` operations.  Indeed, `insert` is the standard algorithm for heaps represented as Braun trees, so when given a Braun tree (balanced) it produces a Braun tree (balanced too).  But `remove_top` does not preserve the Braun tree invariant at all.

An `extract` operation that preserves Braun-ness can be found in Paulson, _ML for the working programmer_, section 4.16.  But it's quite complex and may not make the best of examples for an abstract data type.

Leftist heaps (see Okasaki, _Purely Functional Data Structures_, section 3.1) require less code, but the structural invariant is less obvious than Braun-ness.

A simpler example of abstract data type for chapter 2 could be queues or dequeues implemented as a pair of lists.

**Comment by Octachron** [comment]
Fixed in #12201 .
