### ISSUE TITLE
Curious behavior with module substitution

### ISSUE THREAD

**Issue by Ngoguey42** [ocaml/ocaml#12100]
The following works fine.
```ml
module type CONFIG = sig
  type t
end

module type MAKE = functor (C : CONFIG) -> sig
  type config := C.t
  type t
  val create : config -> t
end

module Make : MAKE = functor (C : CONFIG) -> struct
  type config = C.t
  type t = { config : config }
  let create config = { config }
end
```

Replacing `type config := C.t` by `type config = C.t` still works.

The following works fine too.
```ml
module type CONFIG = sig
  type t
end

module type MAKE = functor (C : CONFIG) -> sig
  module Config := C
  type t
  val create : Config.t -> t
end

module Make : MAKE = functor (C : CONFIG) -> struct
  module Config = C
  type t = { config : Config.t }
  let create config = { config }
end
```

However, replacing `module Config := C` by `module Config = C` fails with the following error:

```
11 | .............................(C : CONFIG) ->
12 |   struct
13 |     module Config = C
14 |     type t = { config : Config.t }
15 |     let create config = { config }
16 |   end
Error: Signature mismatch:
       Modules do not match:
         functor (C : CONFIG) ->
           sig
             module Config : sig type t = C.t end
             type t = { config : Config.t; }
             val create : Config.t -> t
           end
       is not included in
         MAKE
       ...
       In module Config:
       Modules do not match:
         sig type t = Config.t end
       is not included in
         (module C)
```

I'm having a hard time understanding the problem. Is this a bug?

I'm using OCaml 5.0.0.

**Comment by nojb** [comment]
I believe this is a known limitation: in a module alias such as `module Config = C`, `C` cannot refer to a functor parameter, see https://v2.ocaml.org/manual/modulealias.html#s:module-alias. As the module equality is not preserved in the body of `Make`, the compiler correctly complains that its signature doesn't match `MAKE`.

![image](https://user-images.githubusercontent.com/113560/224471884-49a680a9-d5ca-4711-9b51-8f3b87de152f.png)

**Comment by gasche** [comment]
I agree with the analysis and I think this can be closed.

Note: there is a real possibility that we would get some form of transparent ascription and in particular module aliases on functor arguments in the medium-term future -- maybe from work around @lpw25, maybe from work by @clementblaudeau, maybe both.
