### ISSUE TITLE
Debug information is incorrect for installed bytecode packages

### ISSUE THREAD

**Issue by richardlford** [ocaml/ocaml#12106]
When modules of libraries of a package are compiled in bytecode mode with debugging enabled (-g), the compiler writes debugging information into the output (.cmo file) and these may be aggregated into bytecode libraries (.cma). The debug information for a module consists of two parts:
- A list of directories used as a path for finding the source file. The compiler fills this in with the absolute path to the build-time workspace root, and possibly some subdirectories of it.
- A list of Instruct.debug_event records. Part of the information in an event is the starting and ending location of the event, each of which may include a relative path to the source code for the module (usually as relative to the built-time workspace root).

When a package is installed, the package artifacts are copied to the installation location, usually in a directory named
`<prefix>/lib/<package-name>`, where `<prefix>` is the root of the OCaml installation. After the installation, it may be that the build directory is deleted, so the directories in the debug information point to non-existent locations.

Another factor invalidating the directories in the debug information is Dune's workspace_root-mapping feature, which replaces the build-time workspace root with `/workspace_root`. 

The relative source-code paths in the debug events can also be wrong after installation. For example, if a Dune project contains multiple packages at nested locations, a module `mod.ml` in library `lib1` of a package
`<package-name>` may be located (relative to the build-time workspace root) at 

`lib/lib1/mod.ml`

The debug information in the events will have `lib/lib1/mod.ml` as the module location.
However, with Dune at least, such a module will be installed at a location:

`<prefix>/lib/<package-name>/lib1/mod.ml`

One might think we could set the directory in the debug information to `<prefix>/lib/<package-name>`
and that then the source would be found. But it would not, as the effective path would be
`<prefix>/lib/<package-name>/lib/lib1/mod.ml`, which does not match the actual location.

But there is actually enough information in a package at its installation location to correct the debugging information.
The modules of a package must have distinct basenames, so in the debug events, we can take the basename
of the module location and look up the real location of the module in the installation. We can then fix it by storing the 
corrected path relative to the package root (i.e. `<prefix>/lib/<package-name>/`). In the example above,
we would change `lib/lib1/mod.ml` to `lib1/mod.ml` in the debug events.

As far as the directories to place in the debug information, all the prior directories can be discarded (as they are stale).
Instead, we can replace them with `<prefix>/lib/<package-name>/`, and possibly subdirectories of it containing other things we might want to load (e.g. .cmo or .cma files).

I have a prototype tool that I call `ocamledit` which is able to correct the debug information contained in a package, as described above. I plan to submit a PR for it soon.

When such a tool is available, it can be used by a build system as part of the installation process, to correct the debug information.

**Comment by gasche** [comment]
The design you have in mind is that Dune would invoke the compiler "naively" with the source layout paths, which get stored in the build artifacts, and then someone would call a "clever" tool at install time to remap the paths in the build artifacts from the source layout to the installation layout.

An alternative design that comes to mind would be to have Dune pass enough information to the compiler to use the installation layout paths from the start, so that no intermediate transformation is required at installation. This sort of rewriting could possibly be done with the existing BUILD_PATH_PREFIX_MAP support.

The second option sounds more in line with how we typically do things, and it has the advantage of requiring few compiler-side changes. (In particular the compiler needs to know about neither Dune nor opam's layout conventions.) Can you articulate why you prefer to propose the first option instead?

(One downside of the second option I can see is that it is harder to use the build artifacts from within the uninstalled Dune project, as they are configured for post-install use. I wonder if it is possible to change the build layout to mirror the install layout to make this issue go away, or maybe to have dune subcommands invoke the tools on the build artifacts with yet another well-chosen BUILD_PATH_PREFIX_MAP invocation to solve this. In a previous discussion some people  suggested having a flag to reverse BUILD_PATH_PREFIX_MAP lookup, which might also be relevant here.)

**Comment by richardlford** [comment]
@gasche, There are a number of reasons to favor the first approach:
1. It does not require any compiler changes at all, though it does require the "clever" tool. The tool will need to be invoked as part of the installation process (or by an end-user to fix a package).
2. I think the difficulty of using the uninstalled build artifacts is a show-stopper for the alternate approach. I think it would be complicated to try to run a program configured for the installation path if it is not there. That would also seem to go against the push for "reproducible builds".
3. As far as making the build time layout match the installation layout, that would require Dune changes and it would then deviate from the current scheme of making the build directory mirror the user source layout. Dune users can modify the locations of installed components using stanzas, so predicting the installation layout is not easy. On the other hand, discovering where things have been installed after the fact is easier.
4. My plan for the tool is that it be built separately from the compiler, and designed to be buildable with older versions of OCaml. So incorrect debugging information can be remedied sooner than other compiler/Dune changes could be deployed.
5. The tool allows users of a third-party package to fix the debugging information, which is needed, for example, if they built their package with Dune's workspace mapping feature (because they wanted reproducible builds). 
6. The tool will also have a feature to check and/or correct the debugging information for all of the installed packages, or just of selected packages.

**Comment by richardlford** [comment]
@gasche, here is some additional data. I used my tool to check my installed packages which currently includes 73 packages and 97 .cma files. There were 373 instances like this:

```
Correction: src/alcotest-engine/callsite_loc.ml -> engine/callsite_loc.ml.
```
where the source location at build time, relative to the build root, does not agree with the install-time relative location. And usually parts of the build-time path do not exist at install time. With some effort this could be fixed by the developers of the package, but errors like this are likely to creep in. Using a tool to fix the debug information is more reliable.

Of course, the debug directories are all wrong.

I also diagnose source files that are missing from the package. There were 433 missing source files. For example, the source files for compiler-lib are not available. Of course, some of these are probably missing for good reason. But they make it harder for users to step into the libraries to see what is going on. I personally would like to have the compiler-libs available, since I've been writing some tools (like the one I'm proposing) that use the compiler-libs, and I'd sometimes like to step into them.

**Comment by dbuenzli** [comment]
@richardlford the trend is rather to go towards immutable install hierarchies (cue `nix` and co.) and there are good reasons for that (caching, reproducibility, security, etc.). I don't think running tools over files owned by package managers to fix them is a very good approach.

As I said [there](https://github.com/ocaml/ocaml/issues/12083#issuecomment-1464376200) I think it would be better to define a standard virtual hierarchy convention for build systems to follow and play appropriately with `BUILD_PATH_PREFIX_MAP`.

**Comment by richardlford** [comment]
@gasche. So @dbuenzli, you are proposing, as we mentioned earlier, making sure that dune compiles each module in an environment isomophic to the the install environment. If a module, to the compiler, appeared to be at `lib/packagename/otherdir/mod.ml`, (so the debug information would have that as the location) and that module was installed at `opamroot/lib/packagename/otherdir/mod.ml`, then a simple `-I opamroot` supplied to ocamldebug would allow it to find the source. 

Or if we wanted to have some kind of marker, e.g. `/workspace_root`, as Dune currently uses, then the debug directory stored with the debug information could just be `/workspace_root/` In that case, ocamldebug would need to be modified to use `BUILD_PATH_PREFIX_MAP`, which I don't believe it does currently.

I can see that that would all work out eventually if someone were to put the work into Dune (I don't think I'm expert enough in Dune to do it). But that may take a while before all that is put into place (maybe months to get implemented, years to being used by everyone). So I think a tool such as I propose would be worthwhile in the interim. I would think I'm not the only one who likes to step into library functions to see what they do. And that is currently broken and even optimistically will probably continue to be broken for some time to come. [The one exception is stepping into standard library functions, since ocamldebug automatically installs the `opamroot/lib/ocaml` directory, and apparently there is no mismatch between relative locations for the standard library.]

If ocaml does not want this as part of their sources, I can keep it on my own github, and perhaps publish to opam to see if others are interested. Personally I expect to find it very useful.

**Comment by richardlford** [comment]
@gasche, @dbuenzli: I have done some further research. A developer using Dune can achieve the install-time layout already with the existing Dune. To do it they need a build-time layout like this:

- `dune-project`
  - `mypackage`
    - `lib1`
      - `dune` (that says lib1 belongs to `mypackage`
      - `mod1.ml` (etc.)

When they do this, the debug information in mod1.cmo will show `mypackage/lib1/mod1.ml` as the location, and (if Dune workspace mapping is enabled), the debug directories in mod1.cmo (and lib1.cma) will be:
- `/workspace_root` (all that is needed to find source code)
- `/workspace_root/myproject/lib1` (needed to find the `lib1.cma`, as well as mod1.{cmi,cmt})
- `/workspace_root/myproject/lib1/.lib1.objs/byte` (needed if you want to find `mod1.cmo`
The last of these is a build-time artifact that is not installed (at least not by default), but its presence is harmless.

Given that a package developer can achieve this, the goal of having ocamldebug able to find the source code (and `.cm*` files) can be achieve by having ocamldebug support `BUILD_PATH_PREFIX_MAP`. 

The `BUILD_PATH_PREFIX_MAP` standard (https://reproducible-builds.org/specs/build-path-prefix-map/) allows `:`s in the destination of a mapping (encoded as `%.`). This would allow a mapping of `/workspace_root` to multiple directories. 

This would be needed, e.g. when debugging in the build environment. In that case, `/workspace_root` should be mapped to the following (in decreasing priority):
- The source root, `root`. This is first so the modules in the source would be found first, before their image in _build.
- `root/_build/<config>/`, to find build binaries, of both the user app, and other libraries under development (which might also be installed--but we want the developed version).
- `opamroot/lib`, to find sources installed libraries.

So I see two action items out of this:
1. Implement `BUILD_PATH_PREFIX_MAP` support in ocamldebug (I don't believe it does currently, but helpers are already present in the compiler sources)
2. Document in Dune the layout needed in order to have correct install-time debug information.

So the timeline for when this might happen is not as grim as I suggested earlier. Nevertheless, until those have had time to take effect, my tool would still be useful as an interim measure, or as long as some developers fail to use the proper layout.

**Comment by gasche** [comment]
Implementing BUILD_PATH_PREFIX_MAP handling in more compiler tools has my support. The previous discussion also suggested that it would be convenient to have a way to 'reverse' a mapping, so that build systems such as Dune could pass a mapping when building, and pass the exact same mapping with a "reverse" flag when executing commands inside the pre-install artifacts. I would also be happy to support this.

**Comment by lpw25** [comment]
I don't think you need to make the build directories match the install directories at all. Finding install directories is why we also add the path to any `.cmo` files at *link time*. That ensures that the directories in which `.cmo` files have been installed are included when the debugger looks for files.

**Comment by lpw25** [comment]
(Which was added in #157)

**Comment by richardlford** [comment]
> I don't think you need to make the build directories match the install directories at all. Finding install directories is why we also add the path to any `.cmo` files at _link time_. That ensures that the directories in which `.cmo` files have been installed are included when the debugger looks for files.

@lpw25, that helps for finding the .cma files, but if the relative paths to the source files are inconsistent with the install locations, that will not help. The example I gave earlier shows why:

In that example, in the source/build tree, the file was located at 

```src/alcotest-engine/callsite_loc.ml ```

but when installed it was located at 

```
engine/callsite_loc.ml
```

The `acotest_engine.cma` is also located in the `engine` directory. So it is true that the debugger has been given the directory containing the `callsite_loc.ml` file. But in the debug events it gives a relative location of the file as

```
src/alcotest-engine/callsite_loc.ml 
```

The debugger finds files by going through the list of directories, and for each one it prepends the directory to the relative path from the event. So it would look for the file at:

```
engine/src/alcotest-engine/callsite_loc.ml 
```
and not find it.

One could imagine that if the file was not found that way, that it could also search with the simple name, but ocamldebug does not do that currently.

One other point is that, if the executable bytecode file is to be reproducible, regardless of where it was built, the BUILD_PATH_PREFIX_MAP would need to have a mapping to replace the library location (e.g. .opam/switch) with and abstract path. Then if the executable was delivered to some other location, the inverse path could be applied. 

Currently Dune only maps the workspace root, but not the location of the installed libraries.

**Comment by lpw25** [comment]
> The debugger finds files by going through the list of directories, and for each one it prepends the directory to the relative path from the event.

Pretty sure it’s just a bug that it does that for the directories added in linking. The whole point of adding them is that they are adjacent to the relevant ml files. I think it’s also probably the wrong behaviour more generally. The stored directories should be the directories that contain the files and the files should be looked up without their relative paths.

I surprised that it isn’t just storing the absolute path to the file, I could have sworn that is what it used to do. Obviously you then have to deal with the build prefix path stuff, but that seems unavoidable for reproducible builds anyway.

**Comment by richardlford** [comment]
> I surprised that it isn’t just storing the absolute path to the file, I could have sworn that is what it used to do. Obviously you then have to deal with the build prefix path stuff, but that seems unavoidable for reproducible builds anyway.

Actually, the current ocamlc does store the absolute path in the debug event when the user specified an absolute path to the compiler. And it stores a relative path if the user specified a relative path. My current changes are making it absolute and then doing the BUILD_PATH_PREFIX_MAP mapping.

**Comment by lpw25** [comment]
So if you fix that and then make sure it looks for files based on just their basename in all directories in the list then everything will work without the need for any special handling of install directories.

**Comment by richardlford** [comment]
> So if you fix that and then make sure it looks for files based on just their basename in all directories in the list then everything will work without the need for any special handling of install directories.

That appears to be almost true. I wrote a test case with Dune using its "include_subdirs" stanza.

Here is an excerpt from my dune-project file:

```
(lang dune 3.7)
(name rlf-multilevel)
(package
 (name rlf-multilevel))
```

And here is the "lib/lib1/dune" file:

```
(include_subdirs unqualified)
(library
 (name lib1)
 (public_name rlf-multilevel.lib1)
 (flags (:standard -w "-9"))
 (wrapped false)
 (modes byte)
 )
```

 Here is the source layout:

- dune-project
- lib/
  - lib1/
    - dune
    - level1/
      - liba.ml
      - liba.mli
      - level2/
        - libb.ml
    - otherdir/
      - lib1.ml

So library "lib1" has three modules, "lib1", "liba" and "libb".

The following debug directories were produced in the 'lib1.cma':
- /Workspace_root
- /workspace_root/lib/lib1/level1/level2
- /workspace_root/lib/lib1/.lib1.objs/byte
- /workspace_root/lib/lib1/level1
- /workspace_root/lib/lib1/otherdir

So in fact there is a directory reference for every source file, though not for the .cma file which, as seen below, is in the `lib1` directory. Of course, this is an unusual test case as I had none of the source modules at the top level. 

I did a `dune install --prefix _install` and here is the layout it produced:

- _install/
  - lib/
    - rlf-multilevel/
      - dune-package
      - META
      - opam
      - lib1/
        - lib1.cma
        - lib{1,a,b}.cm{i,t,ti}
        - level1/
          - liba.ml
          - liba.mli
          - level2/
            - libb.ml
        - otherdir/
          -  lib1.ml

Now we would like, during the deployment phase, to have `opamroot/lib` as one of the replacements for `/workspace_root`. But if we used that on one of the directories above, e.g. `/workspace_root/lib/lib1/level1/level2`, we get `opamroot/lib/lib/lib1/level1/level2`, but what we want is `opamroot/lib/rlf-multilevel/lib1/level1/level2`.

Dune could have accomplished that when doing the compile if instead of mapping

`cwd` -> `/workspace_root`

it had mapped

`cwd/lib` -> `/workspace_root/rlf-multilevel`

where `rlf-multilevel` is just my example package name. So Dune needs to ensure that each library belonging to a package is mapped in such a way that the package name appears in the directories, and any enclosing directory names are stripped away (in this case, `lib`).

It does appear, however, that if Duen does that for the directories, that using basenames for the files in the debug events will be sufficient.

**Comment by lpw25** [comment]
I don't think you should aim to map `workspace_root` -- which represents the source directory -- mapped to `opamroot/lib` which is the installed directory. Your description above is missing a key step: **where is the executable that you are going to debug?** When you attempt to create that executable it will need to link your library, doing so will separately add `opamroot/lib/rlf-multilevel/lib1` to the list of debug directories for the executable. That is the directory entry that should be being used to find the installed sources.

The only issue with your above setup is that dune seems to install the source files in the wrong place when you have multiple directories for a library. It should be producing:

- _install/
    - lib/
        - rlf-multilevel/
            - dune-package
            - META
            - opam
            - lib1/
                - lib1.cma
                - lib{1,a,b}.cm{i,t,ti}
                - liba.ml
                - liba.mli
                - libb.ml
                - lib1.ml

I guess no one has noticed this issue because dune wasn't originally designed to support spreading one library across multiple directories -- and personally I'd still recommend not doing that.

If you fix that issue with dune then I think everything will just work. (Modulo getting build prefix map stuff working -- which you seem to be fixing in another PR).

**Comment by richardlford** [comment]
> Your description above is missing a key step: **where is the executable that you are going to debug?** When you attempt to create that executable it will need to link your library, doing so will separately add `opamroot/lib/rlf-multilevel/lib1` to the list of debug directories for the executable. That is the directory entry that should be being used to find the installed sources.

The significance of your comment did not sink in when I first read it. But on reflecting further I see its importance.

First of all, the fact that the location of the library '.cma' (or ".cmo") is added to the debug directory list means this is another source of absolute build-time path leakage. When the executable gets installed, it will leak the location of the opam library from the build environment. This means, that for a reproducible build, `opamroot/lib` should also be mapped to something, either `/workspace_root` (which will work with the scheme I was proposing), or perhaps to something else, like `/opamrootlib`. 

Of course, with the current Dune, the opam root is not mapped (and the build is not reproducible), and your suggestion to just use the absolute path added at link time will just work, without the need to add the opam root to the reverse BUILD_PATH_PREFIX_MAP mapping.

So mapping the `opamroot/lib` is something Dune should be doing (to get truly reproducible builds).

But the fact that `opamroot/lib/rlf-multilevel/lib1` was added to the directory list, means that, after mapping (assume using `/workspace_root`), that `/workspace_root/rlf-multilevel/lib1` will be added to the directory list. So, whereas in the `.cma` debug information there was not a path to the `.cma` (in my example above), in an executable using the `.cma` there will be a reference. This, along with the source paths already in there, means there are debug directories for all the sources (even if not in the `.cma` directory), as well as the `.cma` (added during linking).

One other missing piece, slightly unrelated, is debugging an executable that has been installed (i.e. you do not have a build environment for it). If its sources have been installed as well, say someplace under `opamroot/lib`, then just mapping `/workspace_root` to `opamroot/lib` should be sufficient to find its sources and the sources of libraries it used. If its sources are not installed, you are probably better off to just clone its repo and build it from source.
