### ISSUE TITLE
Error: The module _ is an alias for module _, which is missing

### ISSUE THREAD

**Issue by mimoo** [ocaml/ocaml#12111]
I'm hitting this error but I don't think this is normal.

```
Error: The module Pickles.Backend.Tick is an alias for module Kimchi_backend.Snarky.Tick, which is missing
```

Here `pickles/backend/dune`:

```lisp
(library
 (name backend)
 (public_name pickles.backend)
 ;; ... 
 (libraries kimchi_backend kimchi_backend.pasta kimchi_backend.pasta.basic))
```

and `pickles/backend` is simply a file that contains some aliases to its dependency:

```ocaml
module Tick = Kimchi_backend.Snarky.Tick
module Tock = Kimchi_backend.Snarky.Tock
```

Here's the wird part, `Pickles.Backend.Tick` is called from some other internal library that has this dune:

```lisp
(library
 (name genesis_constants)
 (public_name genesis_constants)
 (library_flags -linkall)
 ;; ...
 (libraries
  pickles.backend
 ;; ...
```

as you can see, there's no `kimchi_backend` as dependency to this library. But there's no reason it should have one. Adding `kimchi_backend` as a dependency fixes the issue though. I'm not sure I understand why that module needs to be aware of transitive dependencies

**Comment by kit-ty-kate** [comment]
You're using `(implicit_transitive_deps false)` in Dune, which is an unstable feature and not officially supported by the compiler. Support in the compiler will be added if/whenever https://github.com/ocaml/ocaml/pull/11989 is merged. In the meantime I believe this is expected behaviour.

**Comment by mimoo** [comment]
Just here again because I ran in another error related to this configuration, and it's sometimes really hard to tell it is because of a missing dependency because the errors don't talk about that at all sometimes >.<

**Comment by gasche** [comment]
My understanding, confirmed by @kit-ty-kate message above (hi!), is that currently this is a Dune-side issue, not a compiler issue, but that the best currently-known approach to fix the Dune-side issue is to improve the compiler to better support Dune's workflow. There is ongoing work in this direction, a collaboration between Dune contributors and compiler contributors, in #11989.

The present issue is useful as a way to confirm that the current behavior is confusing to fresh users and should be improved, but there is little specific that we want to do besides pushing further on #11989 (which is *not* as simple as initially hoped it would be).

On the basis of this analysis, I am thinking of closing the present issue, as morally a "duplicate" -- it does not denote additional work that would be required on the compiler and is not already tracked somewhere.

**Comment by Octachron** [comment]
I am closing it as a duplicate.
