### ISSUE TITLE
Building ocaml fails with "make inconsistent assumptions over interface Stdlib__Format'

### ISSUE THREAD

**Issue by brucerennie** [ocaml/ocaml#12137]
make[3]: Entering directory '/home/bruce/src/git/github/ocaml'
  OCAMLC typing/outcometree.cmi
  OCAMLC utils/misc.cmi
  OCAMLC file_formats/cmo_format.cmi
File "/home/bruce/src/git/github/ocaml/file_formats/cmo_format.mli", line 1:
Error: The files /home/bruce/src/git/github/ocaml/utils/misc.cmi
       and /home/bruce/src/git/github/ocaml/typing/ident.cmi
       make inconsistent assumptions over interface Stdlib__Format
make[3]: *** [Makefile:1555: file_formats/cmo_format.cmi] Error 2
make[3]: Leaving directory '/home/bruce/src/git/github/ocaml'
make[2]: *** [Makefile:228: coreall] Error 2
make[2]: Leaving directory '/home/bruce/src/git/github/ocaml'
make[1]: *** [Makefile:299: opt.opt] Error 2
make[1]: Leaving directory '/home/bruce/src/git/github/ocaml'
make: *** [Makefile:376: world.opt] Error 2

This build is occurring with recent github release from yesterday

[damiendoligez] [fix overcounting of minor collections (]https://github.com/ocaml/ocaml/pull/12132[)]   [dbd36ae]

Built on MX Linux

**Comment by nojb** [comment]
How are you building OCaml? Did you start from a clean tree? In general, if your tree is not clean, you may run into this error because not all dependencies are correctly specified in the build system. However, if starting from a clean tree, the build should complete successfully.

**Comment by brucerennie** [comment]
I did start from a clean tree as directly downloaded from github. This error is the initial error I had. I have since updated a number of times since.

However, I have just done the following sequence 

make clean
configure
make

and this has worked. I will use this sequence in all future updates.

I have done a test of just doing 

configure
make

and this now works. I do not know why, but as it now works, this problem can be closed.

I have also tested completely removing the ocaml tree from my machine and cloning again. This also works now.

Greatly appreciate your comments and help. Thank you.

**Comment by shindere** [comment]
The only explanatin that I can see is that you somehow had left-overs.
Forthe clean stage you can even use make distclean or git clean -xffd to
make sure you are really starting from a clean stage. The git clean is
interesting because it tells you what exactly has to be removed (because
it's there), whereas make distclean willshow you the sequence of removal
commands but not what actually gets removed.
