### ISSUE TITLE
Add support for dune tests in ocaml/testsuite

### ISSUE THREAD

**Issue by richardlford** [ocaml/ocaml#12135]
I'm currently adding support for BUILD_PATH_PREFIX_MAPPING for `ocamldebug`.
I'd like to be able to write some automated tests in `ocaml/testsuite` that use Dune,
since it is one of the build systems that support such mapping, in order to verify that
`ocamldebug` can correctly deal with executables produced by Dune.

What would be required to support Dune testing? Here is a list of possibilities:

- Dune itself must be installed or available.
- Do we need a way of controlling which version of Dune is available, or to select a particular Dune version?
- There must be a way to configure Dune so that it uses the compiler that is under test.

Regarding the last point, a dune-workspace file has the ability to specify an opam switch
to use. If the CI system created a switch with a known name based on the compiler-under-test
then the dune tests could specify that switch.

I've manually created such a switch for local tests and verified that Dune is using the ocaml compiler from that switch and that it behaves as expected. 

Creating such a switch involves:

```sh
cd <ocamlroot>
opam switch create ocamlut --empty
opam install .
```

But one would not want to have to create such a switch for each Dune test, but if the
CI setup created it, it could be used by test.

Here is what a sample `dune-workspace` file might look like:

```
(lang dune 3.7)
(context
 (opam
  (switch ocamlut)
  (name ocamlut)
  ))
```

There probably are other ways to setup Dune to use the ocaml under test, perhaps by
setting the `env` stanza.

Any opinions or suggests regarding ocaml tests using Dune?

**Comment by Octachron** [comment]
As a generic rule, dune tests belong to dune CI; not to the compiler testsuite.

**Comment by richardlford** [comment]
> As a generic rule, dune tests belong to dune CI; not to the compiler testsuite.

I've decided that is more practical for now. I can make a switch with my compiler-under-test and then run the dune tests I write. I can wait until after my ocaml changes are in the trunk before getting the new dune tests added to the dune test suite. It does seem that part of making an ocaml release would be running the dune test suite to make sure the compiler has not broken anything. Perhaps that is done.

**Comment by richardlford** [comment]
I will close this issue as it does seem more appropriate to do it in the dune test suite.

**Comment by Octachron** [comment]
Making sure that core opam packages works is part of the release process of new version of the compiler. Moreover, since dune is a build dependency of many packages, it is tested thoroughly starting with the first alpha release of new versions.
