### ISSUE TITLE
Marshal module: marshal to/from a bigarray [feature]

### ISSUE THREAD

**Issue by UnixJunkie** [ocaml/ocaml#12167]
https://discuss.ocaml.org/t/could-the-marshal-module-from-the-stdlib-support-marshal-to-from-a-char-bigarray/11831

If people are interested, please let me know.

**Comment by gasche** [comment]
This looks fairly related to what [Ancient](https://github.com/UnixJunkie/ocaml-ancient) was doing (or the more recent work at Facebook/Meta on shared hashtables for Flow). You seem to have worked on Ancient before, and the README says:

> Secondly, this module allows you to share those structures between
processes.

**Comment by UnixJunkie** [comment]
This has nothing to do with Ancient.
Jane Street has an implementation, but it is included in Core, so a pretty heavy dependency:
https://ocaml.janestreet.com/ocaml-core/109.20.00/doc/core/Bigstring_marshal.html

**Comment by nojb** [comment]
I think that marshalling to- and from- "char bigarrays" makes sense. But I would rather see that as part of a larger addition that would also add other "char bigarray" operations, such asreading and writing from `Unix` file descriptors and standard I/O channels.

But before considering this, I think all these additions should be experimented with in an external library.

A quick google search shows https://github.com/inhabitedtype/bigstringaf which includes some C primitives to blit between "char bigarrays" and `bytes`. One could imagine extending this library with I/O primitives as mentioned (or in a separate library altogether).

**Comment by gasche** [comment]
> This has nothing to do with Ancient.

I'm confused, your Discuss post that you linked starts with the following:

> That would be a useful feature, since memmapped bigarrays are the de facto shm
on Unix-likes for multi process programs.

Marshalling OCaml values into memory shared with other processes does seem related to Ancient which was designed (see quote above), among other things, to share OCaml values between processes. Am I missing something?

**Comment by alainfrisch** [comment]
In Ancient, values would be stored in pages outside the control of the GC but using the normal representation for OCaml values. No marshalling was involved.

**Comment by UnixJunkie** [comment]
1) Ancient is no more maintained. This is an abandonware.
2) The main goal of ancient was to be able to store very large values out of the regular garbage collected memory region (as far as I understand).

**Comment by gasche** [comment]
@nojb you have been elected to shepherd this issue. Personally I would like to understand the motivation better (if the idea is to share OCaml values between processes, avoiding the cost of a copy but paying the code of repeated (un)marshalling seems strange to me). But this is not my problem anymore :-)

**Comment by nojb** [comment]
I re-read the discussion. I understand this issue is "only" about avoiding a copy `bytes -> bigarray` when marshalling values that are ultimately stored in bigarrays. My opinion is still as [before](https://github.com/ocaml/ocaml/issues/12167#issuecomment-1501644745): the request is reasonable in abstract, but too specific to consider adding it to the standard library in isolation. The feature in question already exists (or exited) in one of the Jane Street libraries. Why not extract the relevant code and make a self-contained library out of it?

On that note, I will close this feature request. Thanks for the proposal in any case!
