### ISSUE TITLE
The stdlib doesn't allow to create a mmapped bigarray from an existing bigarray [feature request]

### ISSUE THREAD

**Issue by UnixJunkie** [ocaml/ocaml#12177]
Hello,

The Unix.map_file function only allows to create a fresh (as in "uninitialized") bigarray.

I wonder if it would be possible to add the functionality to map to disk
an already initialized bigarray.
This would avoid having to copy one bigarray into another, at mmap time.

Thanks,
F.

**Comment by copy** [comment]
Is there an efficient way to do this using POSIX mmap?

**Comment by UnixJunkie** [comment]
Not to my knowledge.
Unless there is a way to get a file descriptor for an existing (and already initialized but not yet mmapped) bigarray.

**Comment by smuenzel** [comment]
If posix mmap cannot support this use-case, it will be very difficult for Ocaml to, since we're really just wrapping the OS functionality.

**Comment by UnixJunkie** [comment]
We could get a file view of the existing bigarray using fmemopen.

**Comment by UnixJunkie** [comment]
I guess there will still be a copy of the existing bigarray to the fresh one which is mmapped.
Currently, I use Bigarray.Genarray.blit, so I guess there is not much to be gained.
