### ISSUE TITLE
Universal quantification fails when mixed with polymorphic variants in OCaml 5.1.0~alpha1

### ISSUE THREAD

**Issue by kit-ty-kate** [ocaml/ocaml#12189]
The following test-case:
```
let f :
  type a.
  a ->
  [> `A of a ] =
  fun x -> `A x
```
compiles fine with OCaml 5.0.0 and below but fails with 5.1.0~alpha1 with the following error message:
```
File "test.ml", lines 1-5, characters 4-15:
1 | ....f :
2 |   type a.
3 |   a ->
4 |   [> `A of a ] =
5 |   fun x -> `A x
Error: This expression has type 'a -> [> `A of 'a ]
       but an expression was expected of type 'a -> [> `A of 'a0 ]
       The universal variable 'a0 would escape its scope
```
This only seems to be the case when polymorphic variants are involved as removing them in the code above makes it compile fine again.

**Comment by gasche** [comment]
I suppose that this change comes from https://github.com/ocaml/ocaml/pull/11600, and there are discussions there on the fact the type `type a . a -> [> `Foo of a ]` is "arguably wrong" -- in the context of polymorphic methods rather than local abstract types: https://github.com/ocaml/ocaml/pull/11600/files#r1011511497

An intuitive explanation for the new behavior is that the implicit quantification in `[> ...]` is scoped outside the quantification `type a .`, so the content cannot mention `a`. (This being said, it does feel like a limitation and I am not sure why we are not considering that `type a.` introduces a binding site for implicit quantifications and inference variables like `'b`.)

**Comment by Octachron** [comment]
Locally abstract types are not that relevant here
```ocaml
let f: 'a. 'a -> [> `X of 'a ] = fun x -> `X x
```
fails too. But yes, I remember now that the fix is supposed to quantify all row variables:
```ocaml
let f: 'a 'r. 'a -> ([> `X of 'a ] as 'r) = fun x -> `X x
```
which is a bit worrying since it probably affects a non-zero number of definitions of mutually recursive functions on polymorphic functions.

**Comment by gasche** [comment]
(cc @garrigue of course)

**Comment by gasche** [comment]
One issue with the proposed fix is that it does not work with locally abstract types, as the syntax `[> X of a ] as r` is not supported -- we have no such thing as locally abstract row types. This means that the `type a . ...` syntax is not usable anymore in presence of polymorphic rows, which feels like a regression to me.

**Comment by garrigue** [comment]
My answer is going to be the same here. The implementation makes the assumption that types sharing the same row variable are identical. If we allow locally quantifying on parts of the type while keeping a shared row variable, it becomes possible to create types which are different and share the same row variable, with possible unsoundness. The fact we have not seen such examples yet is no proof of soundness...
Of course we could modify the implementation not to make this assumption. But this requires changing both the theory and the implementation, so this is much more work than rolling back a change.
As for introducing a way to quantify rows with locally abstract types, this requires some new syntax but should not be too much work. The easiest way would be to extend the `(type a)` syntax to mutually recursive types, such as `(type a and r = [> X of a])`. Allowing `type a r. [> X of a] as r` would be more intuitive, but this requires some extra work (in particular in the current syntax sugar based approach).

**Comment by garrigue** [comment]
Modifying `Pexp_newtype` to include multiple types and a type annotation for the body would probably make sense, and allow the `as r` syntax.
