### ISSUE TITLE
Flag to enable warnings by compiler version

### ISSUE THREAD

**Issue by lukemaurer** [ocaml/ocaml#12183]
Common practice for the `-w` flag is to pass something like `+a-4-9-40`, thereby enabling all warnings except a chosen few. This is a pain when a new compiler version introduces a new warning, especially if the project also uses `-warn-error`, since if anything trips the new warning, the package fails to build at all with the new compiler. Current workarounds include having Dune ignore warnings altogether when building for release, which is unsettling.

The crux is that `+a` is very useful but it is troublesome - its semantics changes with _every .x release_. A simple solution, then, would be to let the user pick which version they're enabling warnings for, say by writing `+a~5.1`. Then version 5.2 will simply remember which warnings 5.1 had and only enable those.

**Comment by Octachron** [comment]
Are you aware that dune is already using its own list of default warnings?

Your proposed change will be invisible to all dune users. In other words, using warnings like `+a-4-9-40`  is not a common practice anymore.

Moreover, the semantics of individual warnings tend to be refined from time to time. Your proposed change will therefore not reach its objective.

Finally, you have yet to detail why disabling `-warn-error` on release build is unsettling.

Overall, ignoring warnings on release build seem the better solution to me.

**Comment by gasche** [comment]
I have a slightly less grumpy take on this feature request than @Octachron, a nice change of role as I'm usually the bad cop. I think that, yes, it would be nice to ask the compiler to "behave as if you were past version N", no, we will never be able to promise this *exactly*, but maybe there are reasonable approximations that exist and could be implementable without too much maintenance work (the Dune people say that it's not so hard).

(This has been proposed in the past, but I can't find the issue anymore.)

The current issue proposes to approximate "the behavior of version N" by "the set of warnings by default". This has the benefit of being very simple to implement. Maybe we could do better with a reasonable amount of work?
