### ISSUE TITLE
Explicit coercion in value bindings does not work in OCaml 5.1.0~alpha1

### ISSUE THREAD

**Issue by kit-ty-kate** [ocaml/ocaml#12188]
```
let x : [`A | `B] = `A

let y : [`A | `B] :> [`A | `B | `C] = x
```
compiles just fine with OCaml 5.0.0 but fails with OCaml 5.1.0~alpha1 with:
```
File "test.ml", line 3, characters 38-39:
3 | let y : [`A | `B] :> [`A | `B | `C] = x
                                          ^
Error: This expression has type [ `A | `B ]
       but an expression was expected of type [ `A | `B | `C ]
       The first variant type does not allow tag(s) `C
```
This behaviour can only be observed when the coercion is in the binding. When it is in the expression section it works fine:
```
let y = (x : [`A | `B] :> [`A | `B | `C])
```

**Comment by Octachron** [comment]
This is a bug in #12119: I didn't catch the fact that coercions are allowed on value binding. I will have a fix shortly, and since it requires an update to the parsetree, I will publish another alpha to try to stabilize the intermediary representation during the alpha releases.
