### ISSUE TITLE
Fix to documentation of String.index_from

### ISSUE THREAD

**Issue by jimgrundy** [ocaml/ocaml#12219]
The documentation of String.index_from is as follows:

```
val index_from : string -> int -> char -> int
(** [index_from s i c] is the index of the first occurrence of [c] in
    [s] after position [i].

    @raise Not_found if [c] does not occur in [s] after position [i].
    @raise Invalid_argument if [i] is not a valid position in [s]. *)
```

Note that it says that the function  returns the first occurrence of `c` in `s` **after** position `i` 
(my emphasis). But, to me, "after" suggests that if there is an occurrence of `c` at `i`,
then `index_from` will not return `i`, but rather the index of a later occurrence (or fail).
This, however, is not what happens. In this case it will return `i`.  Witness the following:

```
utop # String.index_from "01234567890" 0 '0';;
- : int = 0
```

The failure behavior is not exactly as described either. Consider again the string `"01234567890"`. This string has length 11 with valid positions 0...10. 

Witness that 11 is not a valid position:

```
utop # String.get "01234567890" 11;;
Exception: Invalid_argument "index out of bounds".
```

However, searching in this string with with `index_from` from index `11` does not produce an 
`Invalid_argument` exception as claimed:

```
utop # String.index_from "01234567890" 11 'x';;
Exception: Not_found.
```

You have to start your search one beyond that point to get the `Invalid_argument` exception:
```
utop # String.index_from "01234567890" 12 'x';;
Exception: Invalid_argument "String.index_from / Bytes.index_from".
```

I suggest that the documentation be updated as follows:

```
(** [index_from s i c] is the index of the first occurrence of [c] in
    [s] searching from position [i].

    @raise Not_found if [c] does not occur in [s] searching from position [i].
    @raise Invalid_argument if [i] is negative or greater than [length s]. *)
```

**Comment by nojb** [comment]
Note that "position" is used in a specific sense, explained at the top of the module:
https://github.com/ocaml/ocaml/blob/23dab79a4e42856aa33816b9c79c3d4d79959cb9/stdlib/string.mli#L45-L49
In other words, "position" refers to the space between the characters of the string, and the zero-th position refers to the space _before_ the first character. The current docstring is coherent with this notion as far as I can see...

**Comment by jimgrundy** [comment]
Sounds good. Thanks
