### ISSUE TITLE
Enabling/disabling more warnings with global attributes

### ISSUE THREAD

**Issue by lthls** [ocaml/ocaml#12233]
An user was trying to disable inlining-related warnings using global attributes (`[@@@ocaml.warning "-53-55"]`) and this didn't work (see https://discuss.ocaml.org/t/capnproto-functor-inlining/12111/9).
I think that it would be nice to make that work. If I understand correctly, currently only warnings emitted during type-checking can take these attributes into account, as they are discarded when translating to Lambda.
It would be nice to have a way to keep either the attributes themselves, or the relevant meaning, into the rest of the compiler so that it these can be taken into account.

**Comment by gasche** [comment]
Note: I think this is related to https://github.com/ocaml/RFCs/pull/26 .
