### ISSUE TITLE
ocamlnat: `Invalid_argument("index out of bounds")` when using external with flambda enabled

### ISSUE THREAD

**Issue by copy** [ocaml/ocaml#12257]
This is on 5.0 with `--enable-native-toplevel --enable-flambda`:

```
% ./install/bin/ocamlnat
OCaml version 5.0.0+dev6-2022-07-21 - native toplevel
Enter #help;; for help.

# external foo : int -> int -> int = "%addint" let x = 42;;         
Fatal error: exception Invalid_argument("index out of bounds")
Raised by primitive operation at Topeval.toplevel_value in file "toplevel/native/topeval.ml", line 67, characters 2-40
Called from Topeval.pr_item.(fun) in file "toplevel/native/topeval.ml", line 110, characters 36-55
Called from Printtyp.print_items.extend_val in file "typing/printtyp.ml", line 1944, characters 50-69
Called from Stdlib__List.map in file "list.ml", line 92, characters 20-23
Called from Stdlib__List.concat_map.aux in file "list.ml", line 268, characters 16-19
Called from Topeval.pr_item in file "toplevel/native/topeval.ml" (inlined), line 107, characters 2-197
Called from Topeval.execute_phrase.(fun) in file "toplevel/native/topeval.ml", line 236, characters 37-57
Called from Misc.try_finally in file "utils/misc.ml", line 31, characters 8-15
Re-raised at Misc.try_finally in file "utils/misc.ml", line 45, characters 10-56
Called from Printtyp.wrap_printing_env in file "typing/printtyp.ml" (inlined), line 710, characters 7-30
Called from Topeval.execute_phrase in file "toplevel/native/topeval.ml", line 221, characters 16-738
Re-raised at Topeval.execute_phrase in file "toplevel/native/topeval.ml", line 252, characters 32-39
Called from Toploop.loop in file "toplevel/toploop.ml", line 221, characters 12-41
Re-raised at Location.report_exception.loop in file "parsing/location.ml", line 959, characters 14-25
Called from Toploop.loop in file "toplevel/toploop.ml", line 226, characters 11-42
Called from Topmain.main in file "toplevel/native/topmain.ml", line 112, characters 2-35
Called from Topstart in file "toplevel/topstart.ml", line 16, characters 13-29
```

Inspecting the lambda output (`(let (x/295 =[int] 42) (makeblock 0 x/295))`) shows that the module representation only includes `x`, but [`remember`](https://github.com/ocaml/ocaml/blob/5.0/toplevel/native/topeval.ml#L39) also counts externals (`remember` iterates over the signature of the toplevel phrase and produces a mapping from ident to index in the memory representation of the module).

The following patch fixes the problem:

```diff
diff --git a/toplevel/native/topeval.ml b/toplevel/native/topeval.ml
index ff56c27953..6b02d2428d 100644
--- a/toplevel/native/topeval.ml
+++ b/toplevel/native/topeval.ml
@@ -36,6 +36,8 @@ let remembered = ref Ident.empty
 
 let rec remember phrase_name i = function
   | [] -> ()
+  | Sig_value  (_, { val_kind = Val_prim _; _ }, _) :: rest ->
+      remember phrase_name i rest
   | Sig_value  (id, _, _) :: rest
   | Sig_module (id, _, _, _, _) :: rest
   | Sig_typext (id, _, _, _) :: rest
```

Which I'd happily submit as a PR, but makes me wonder if there isn't a more robust way to obtain the aforementioned mapping.

**Comment by gasche** [comment]
I wonder: did something change in the compiler that broke this, or was ocamlnat just never tested with flambda (and external primitives) before? (Does it work for older versions of OCaml?)

**Comment by copy** [comment]
It should be noted that the bug is only triggered if an external appears in the same toplevel phrase as a regular value binding. The external itself is applied correctly, the bug is in computing the offset of the value binding after the external. So it's possible that this bug has been existed since the first release. Indeed, this code hasn't changed since the first release of flambda.

**Comment by gasche** [comment]
I would be in favor of you submitting the PR bugfix, which I believe makes sense (even though indeed the existing logic is a bit fragile). Flambda people can possibly devise a better approach later, but this can always come as a follow-up.

**Comment by lthls** [comment]
Yes, please submit a PR. If you can it would be nice to check if module aliases work correctly too (`module S = String let x = 42 ;;`).
