### ISSUE TITLE
ocamlopt's new name mangling is hard to use from gdb

### ISSUE THREAD

**Issue by xavierleroy** [ocaml/ocaml#12274]
Since #11430, to mangle compound identifiers like `Mod.ident`, ocamlopt generates `camlMod.ident_NN` (with a dot) instead of `camlMod__ident_NN` (with a double underscore) like before.

What I did not anticipate is that these dots in identifiers make low-level debugging with gdb more difficult, since many gdb commands interpret dots as C record accesses.  For instance:
```
(gdb) break camlStdlib.abs_66
Breakpoint 1 at 0x82eb94: file stdlib.ml, line 75.
(gdb) disass camlStdlib.abs_66
'camlStdlib' has unknown type; cast it to its declared type
(gdb) x/10i camlStdlib.abs_66
'camlStdlib' has unknown type; cast it to its declared type
```

It might be wise to revert to the `camlMod__ident_NN` encoding, with a different solution for the collision problems reported in https://github.com/ocaml/ocaml/issues/8998 and in https://github.com/ocaml/ocaml/issues/11321.

Alternatively, is there a GDB syntax to quote symbols containing dots or other unusual characters?

**Comment by nojb** [comment]
> Alternatively, is there a GDB syntax to quote symbols containing dots or other unusual characters?

If memory serves, you can use single quotes to quote symbols containing special characters: `x 'camlStdlib.foo'`.

**Comment by xavierleroy** [comment]
Ah, cool!  I knew I was missing something.  Then perhaps this issue is moot.  What do others think?

**Comment by lthls** [comment]
I've hit the issue too, and once I've found about the quotes I haven't had any more problems. I'd rather we keep the dot as separator.

**Comment by xavierleroy** [comment]
OK, let's close this report, then.

**Comment by xavierleroy** [comment]
For the record: I'm still running in this problem with lldb.  Single quoting doesn't avoid the issue.
