### ISSUE TITLE
Build issue with Linux i386 from ocaml 4.13.0 upwards

### ISSUE THREAD

**Issue by rochus-keller** [ocaml/ocaml#12287]
Releases which successfully build:

- 4.0.1
- 4.08.1
- 4.10.1
- 4.12.1

Releases with build error:

- 4.13.0
- 4.13.1
- 4.14.0
- (5.0 not yet tested)

When building I get the following output:

```
$ make
make coldstart
make[1]: Entering directory `/home/me/Downloads/ocaml-4.13.0'
make -C runtime all
make[2]: Entering directory `/home/me/Downloads/ocaml-4.13.0/runtime'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/home/me/Downloads/ocaml-4.13.0/runtime'
make -C stdlib \
	  OCAMLRUN='$(ROOTDIR)/runtime/ocamlrun' \
	  CAMLC='$(BOOT_OCAMLC) -use-prims ../runtime/primitives' all
make[2]: Entering directory `/home/me/Downloads/ocaml-4.13.0/stdlib'
../runtime/ocamlrun ../boot/ocamlc -use-prims ../runtime/primitives -strict-sequence -absname -w +a-4-9-41-42-44-45-48-70 -g -warn-error +A -bin-annot -nostdlib -principal -safe-string -strict-formats   \
	         -o stdlib__Bigarrayp.cmo -c 
../runtime/ocamlrun ../boot/ocamlc -use-prims ../runtime/primitives -a -o stdlib.cma camlinternalFormatBasics.cmo camlinternalAtomic.cmo stdlib.cmo stdlib__Pervasives.cmo stdlib__Seq.cmo stdlib__Option.cmo stdlib__Either.cmo stdlib__Result.cmo stdlib__Bool.cmo stdlib__Char.cmo stdlib__Uchar.cmo stdlib__Sys.cmo stdlib__List.cmo stdlib__Int.cmo stdlib__Bytes.cmo stdlib__String.cmo stdlib__Unit.cmo stdlib__Marshal.cmo stdlib__Obj.cmo stdlib__Array.cmo stdlib__Float.cmo stdlib__Int32.cmo stdlib__Int64.cmo stdlib__Nativeint.cmo stdlib__Lexing.cmo stdlib__Parsing.cmo stdlib__Set.cmo stdlib__Map.cmo stdlib__Stack.cmo stdlib__Queue.cmo camlinternalLazy.cmo stdlib__Lazy.cmo stdlib__Stream.cmo stdlib__Buffer.cmo camlinternalFormat.cmo stdlib__Printf.cmo stdlib__Arg.cmo stdlib__Atomic.cmo stdlib__Printexc.cmo stdlib__Fun.cmo stdlib__Gc.cmo stdlib__Digest.cmo stdlib__Random.cmo stdlib__Hashtbl.cmo stdlib__Weak.cmo stdlib__Format.cmo stdlib__Scanf.cmo stdlib__Callback.cmo camlinternalOO.cmo stdlib__Oo.cmo camlinternalMod.cmo stdlib__Genlex.cmo stdlib__Ephemeron.cmo stdlib__Filename.cmo stdlib__Complex.cmo stdlib__ArrayLabels.cmo stdlib__ListLabels.cmo stdlib__BytesLabels.cmo stdlib__StringLabels.cmo stdlib__MoreLabels.cmo stdlib__StdLabels.cmo stdlib__Bigarrayp.cmo
File "_none_", line 1:
Error: Cannot find file stdlib__Bigarrayp.cmo
make[2]: *** [stdlib.cma] Error 2
make[2]: Leaving directory `/home/me/Downloads/ocaml-4.13.0/stdlib'
make[1]: *** [coldstart] Error 2
make[1]: Leaving directory `/home/me/Downloads/ocaml-4.13.0'
make: *** [world.opt] Error 2

```

**Comment by dra27** [comment]
The versions affected somewhat implicate `runtime/sak` (which suggests that the branch I have in my fridge for removing `runtime/sak` completely should probably get opened sooner rather than later).

The base images are successfully building on i386 - I'd like to manage to reproduce the failure. What's the exact setup you're on? It's possibly also worth eliminating the obvious - could you check that `stdlib/StdlibModules` definitely has `bigarray` in the `STDLIB_MODULES_BASENAMES` variable? Could you try a build where you swap the `stdLabels` and `bigarray` entries in that variable (i.e. stop having `bigarray` as the _last_ entry in `STDLIB_MODULE_BASENAMES`?

Do you just happen to using 32 bit Linux, or are you also _not_ seeing this with 64 bit?

**Comment by rochus-keller** [comment]
> Do you just happen to using 32 bit Linux 
> I'd like to manage to reproduce the failure
> What's the exact setup you're on?

The machine where I would like it to run is a HP EliteBook 2530p (Intel Core2 Duo, 4 GB RAM) running a 32 bit version of Linux Mint Rebecca (Linux Kernel 3.13) with GCC 4.8. I'm running the standard build procedure (./configure, make), just with a custom prefix to my home directory. I first tried 4.0.1 which worked, and then 4.13.1 which failed during make, and then sampled all mentioned versions as listed. If the failure happens, it is always the same. I didn't investigate the reason yet, but assume that for the link step an object file is listed which is not used (for my architecture and/or the version in place).

> are you also not seeing this with 64 bit?

Didn't try that yet; will do that on a 64 bit machine, but I assume that it works because otherwise you would very likely have heard of it.

**Comment by xavierleroy** [comment]
> Didn't try that yet; will do that on a 64 bit machine, but I assume that it works because otherwise you would very likely have heard of it.

This is true.  On the other hand, the Github CI for OCaml does build on i386, so when it breaks there we hear about it too.  We have a bit of a puzzle here !

**Comment by dra27** [comment]
> 32 bit version of Linux Mint Rebecca (Linux Kernel 3.13) with GCC 4.8

That's a bit old! I'm just pulling an ISO to spin up a VM with it because the bug is nonetheless interesting. You'll need to upgrade if you want to run OCaml 5+ which requires C11 atomic support added in GCC 4.9 (`configure` will fail).

**Comment by rochus-keller** [comment]
> the Github CI for OCaml does build on i386

That's likely a 64 bit machine with an i386 subsystem; the machine I'm using is physically 32 bit.

> We have a bit of a puzzle here 

If it's a lot of investigation effort feel free to ignore the issue; I'm happy with 4.12.1.

**Comment by avsm** [comment]
It's good to root-cause these issues so we understand where the build failure is coming from. 

>  I'm running the standard build procedure (./configure, make), just with a custom prefix to my home directory. 

Would you mind putting in the exact commands you used, including how you did the prefix override?

**Comment by dra27** [comment]
I have reproduced this in a Mint 17.1 VM and am now properly nerd-swiped. More shortly...

**Comment by dra27** [comment]
sak is off the hook - it’s a bug in GNU make. Present in 3.81 in Mint and 3.82 from Savannah - fixed somewhere between 3.82 and 4.0. I want to dig a little further to be sure there’s no implication for macOS (which uses 3.81).

**Comment by rochus-keller** [comment]
> Would you mind putting in the exact commands you used, including how you did the prefix override?

./configure -prefix /home/me/Programme/ocaml-4.13.0

**Comment by rochus-keller** [comment]
> it’s a bug in GNU make

If you're looking for a better build system, here is my proposal: https://github.com/rochus-keller/BUSY

**Comment by dra27** [comment]
> > it’s a bug in GNU make
> 
> If you're looking for a better build system, here is my proposal: https://github.com/rochus-keller/BUSY

It's a bit of leap from a bug in a 17 year old version of a piece software fixed in a release of that software 9½ years ago to completely replacing it 🙂

**Comment by rochus-keller** [comment]
It's never too late to get rid of make, especially if you have to bootstrap on different platforms ;-)

**Comment by rochus-keller** [comment]
As I said, feel free to ignore and close this issue; I'm happy with ocaml 4.12.1, which is far more than good enough for my experiments.

**Comment by dra27** [comment]
This patch should work for you for 4.13 and 4.14 (as I said, 5.0 will require an upgrade anyway):

```diff
diff --git a/stdlib/StdlibModules b/stdlib/StdlibModules
index fb846b0973..c3cfccd0ee 100644
--- a/stdlib/StdlibModules
+++ b/stdlib/StdlibModules
@@ -53,5 +53,5 @@ STDLIB_PREFIXED_MODULES = \
 # executed either once or not at all, giving us GNU make's equivalent of a
 # string lazy_t.
 STDLIB_MODULES = \
-  $(eval STDLIB_MODULES := $$(shell \
-          $(SAK) add-stdlib-prefix $(STDLIB_MODULE_BASENAMES)))$(STDLIB_MODULES)
+  $(if $(forward_STDLIB_MODULES),,$(eval forward_STDLIB_MODULES := $$(shell \
+    $(SAK) add-stdlib-prefix $(STDLIB_MODULE_BASENAMES))))$(forward_STDLIB_MODULES)
```

The issue was originally reported in April 2011 against [GNU make 3.82](https://savannah.gnu.org/patch/?7534) and was fixed in [e4d5d4](https://git.savannah.gnu.org/cgit/make.git/commit/?id=e4d5d434247b720a3f78e1f7279168b5e6bf628e). It was originally reported [to RedHat](https://bugzilla.redhat.com/show_bug.cgi?id=703104) and Fedora carried the patch prior to the release of GNU make 4 - in particular, it means that F19 and consequently CentOS/RedHat 7 do not fail.

Apple do not appear to have back-ported the fix (cf. https://github.com/apple-oss-distributions/gnumake). That said, we've seen no reports of this on macOS, and this issue doesn't seem to trigger at all in 64-bit on any Linux system I've tried.

As I said in https://github.com/ocaml/ocaml/issues/12287#issuecomment-1576402019, there's a patch incoming which removes `runtime/sak` from the computation of `$(STDLIB_MODULES)` anyway and a side-effect of that is that `$(STDLIB_MODULES)` ceases to need lazy evaluation (which is the bug) so, given that the only supported OS with a version of GNU make old enough to be affected is also only available in 64-bit and so doesn't appear to suffer, I'm not going to propose a PR for the tiny patch above.

**Comment by rochus-keller** [comment]
Wow, that's remarkable, thank you very much for your support!

With your patch I was able to successfully build version 4.14.0.

I will use this version for my experiments.

Do you mind if I ask this here: if I generate Ocaml bytecode files, is it possible to feed them somehow to the native compiler, or does the native compiler require more information than included in the bytecode files?

**Comment by dra27** [comment]
My pleasure! From our perspective, at present OCaml bootstraps on macOS with only the Xcode tools, but that comes with the pain of a truly ancient version of GNU make so, for now at least, there's still value in bug reports on ancient GNU make versions. I'm tempted to add an error for GNU make 3.x on anything other than macOS at some point, given the discovery of this issue, though...!

> Do you mind if I ask this here: if I generate Ocaml bytecode files, is it possible to feed them somehow to the native compiler, or does the native compiler require more information than included in the bytecode files?

Questions in general are better suited to [Discuss](https://discuss.ocaml.org) just for increased visibility. The common part of the pipeline between bytecode and native is one level higher than the emitted bytecode in Lambda (representation in lambda/lambda.mli). Although the virtual machine's bytecode is close to lambda, they're not the same (representation or, rather, the instructions in bytecode/instruct.mli) - see bytecomp/bytegen.ml for the conversion.

It's possible that with our various `-d` functions and the start-after/stop-after flags that there's just enough to get lambda from one call to ocamlc and feed it directly into ocamlopt, but I don't _think_ we have the machinery to do that directly at the moment.

**Comment by rochus-keller** [comment]
Thanks again. 

I will ask more questions on Discuss, though unfortunately I have to go to another machine for that because it doesn't work with my browser.

I've read that Lambda is not (officially) documented and thus assume that it changes often; or would it be reasonable to directly generate Lambda instead of bytecode? Do you happen to know projects other than the Ocaml frontend which do so?

If you don't mind I close this issue.

**Comment by dra27** [comment]
OCaml 5.0.0 added quite a lot to Lambda, but that was unusual - primitives get added from time-to-time, but it's pretty stable. You may be interested to see https://github.com/stedolan/malfunction for targeting lambda directly! (note also the compiler's `-dlambda` option)

**Comment by lthls** [comment]
Note that in general, the lambda code generated by `ocamlc` is not the same as the one generated by `ocamlopt`. Trying to restart the native compilation from the bytecode version of the lambda code is not supported.
