### ISSUE TITLE
Data race in weak.c

### ISSUE THREAD

**Issue by OlivierNicole** [ocaml/ocaml#12282]
When performing unsynchronized `Weak.set` and `Weak.get`, we get a race between:
https://github.com/ocaml/ocaml/blob/224c14c41089c12c2f2c1c2f91e88915f62604f5/runtime/weak.c#L192
and
https://github.com/ocaml/ocaml/blob/224c14c41089c12c2f2c1c2f91e88915f62604f5/runtime/weak.c#L250
This _could_ be OK if we are fine with stepping out of the C11 memory model and considering volatile accesses to be like relaxed atomics, like we are forced to do in some cases for backward compatibility of the FFI (see #10992), but… do we really want to do that in this code?

**Comment by kayceesrk** [comment]
I suspect that this surfaced with TSan tests? Accessing `Field` is now volatile access, so it is ok by the argument in #10992. 

If we were to introduce a fix for weak arrays, shouldn't we also fix regular arrays? Why are weak arrays special?

**Comment by OlivierNicole** [comment]
The state of discussions in #10992 suggests that for values that are accessed only from C, we want to stay within the bounds of C11. At least from my external point of view, this is what I take out from [this big summary by the end of the issue](https://github.com/ocaml/ocaml/issues/10992#issuecomment-1112394309).

> If we were to introduce a fix for weak arrays, shouldn't we also fix regular arrays? Why are weak arrays special?

Unlike arrays, weak arrays seem to be only accessed from C functions.

**Comment by kayceesrk** [comment]
For this to be fixed, every access to the fields in a weak array needs to be made relaxed atomic? This includes those accesses by the GC. Unsure what a comprehensive fix would look like. Do you have thoughts on this?

**Comment by OlivierNicole** [comment]
You’re right, the GC also accesses these fields, so I have to backtrack on what I said. The consensus seems to lean toward accessing those values that are in the OCaml heap with `volatile`.

**Comment by kayceesrk** [comment]
Best to go retain the volatile access on weak array fields and add a whitelist for TSAN.

**Comment by OlivierNicole** [comment]
Thanks. I’m therefore closing this.
