### ISSUE TITLE
Data race on caml_gc_phase when printing debug message

### ISSUE THREAD

**Issue by OlivierNicole** [ocaml/ocaml#12291]
Running tests with ThreadSanitizer shows that a data race was recently introduced at https://github.com/ocaml/ocaml/blob/a84586d387d2aa24a781a0724dd549da90c229b1/runtime/major_gc.c#L608-L619: the read of the global `caml_gc_phase` is done without any synchronization, unlike other accesses. It is probably without consequences in practice but technically UB.

This could be fixed by using relaxed atomics for all possibly racing accesses, at the cost of making them slightly less readable. That, or maybe there is a simpler way, e.g. using the same kind of synchronization that is used to order the other accesses to this variable.

**Comment by gasche** [comment]
I propose the following bugfix, can you test it?

```diff
+++ b/runtime/major_gc.c
@@ -1678,7 +1678,7 @@ mark_again:
     ("Major slice [%c%c%c]: %ld sweep, %ld mark (%lu blocks)",
               collection_slice_mode_char(mode),
               !caml_incoming_interrupts_queued() ? '.' : '*',
-              caml_gc_phase_char(caml_gc_phase),
+              (mode == Slice_opportunistic ? 'O' : caml_gc_phase_char(caml_gc_phase)),
               (long)sweep_work, (long)mark_work,
               (unsigned long)(domain_state->stat_blocks_marked
                                                       - blocks_marked_before));
``

**Comment by OlivierNicole** [comment]
It didn’t work, because the conflicting accesses in this case are writes, rather than loads. I probably should have provided a log of the TSan output.
You can find the log for running the testsuite with your patch here: https://github.com/ocaml-multicore/ocaml-tsan/actions/runs/5205067801/jobs/9390270579

**Comment by gasche** [comment]
I think that actually I 'fixed' the wrong read of `caml_gc_phrase` in a different part of the file. Sorry. (The fix is still probably correct and fixing a potential issue of a race between opportunistic slices and non-opportunistic slices.)

**Comment by gasche** [comment]
I have a new fix attempt at

  https://github.com/gasche/ocaml/commits/caml_gc_phase_race

but I am not fully satisfied with it.

(If you want me to test it myself, it would help to have a short repro case. I think maybe just `ocamltest testsuite/tests/parallel/constpromote` is a repro case? In any case, if you are kind enough to test on your side, it's just as well with me for now.)

**Comment by OlivierNicole** [comment]
I have launched a run at https://github.com/ocaml-multicore/ocaml-tsan/actions/runs/5213740528/jobs/9409128205.

> I think maybe just ocamltest testsuite/tests/parallel/constpromote is a repro case?

Yes. The most consistently failing is `weak-ephe-final/finaliser_handover`.

**Comment by OlivierNicole** [comment]
Up to moving the definition of `collection_slice_mode` to `major_gc.h`, it’s a fix!

**Comment by gasche** [comment]
Thanks for the testing report, and apologies for sending a not-quite-compiling patch (oops). There is a small hack in the patch, and I would like to figure out how to rewrite it in a "nice" way but it is not completely obvious; I'm thinking of sending a PR next week.
