### ISSUE TITLE
Non-shortened path in interface generation when using -no-alias-deps and -open

### ISSUE THREAD

**Issue by Chaarlesss** [ocaml/ocaml#12302]
# Description of the bug

In some rare cases, having a weird compilation scheme using `-no-alias-deps` and `-open` may result in an incorrect path when generating an interface file, for instance with `Foo.Bar` instead of `Bar`, even if `Foo` was declared open during the compilation.

This bug is present in 4.14.0 and 5.0.0 (and maybe in older versions).

# Reproducibility procedure

Given the following files:

**foo.ml**
```ocaml
module Ast = Foo__Ast
module Parser = Foo__Parser
```

**ast.ml**
```ocaml
module Retstat = struct
  type t = int list
end

module Block = struct
  type t = Retstat.t option
end
```

**parser.ml**
```ocaml
let (xv_retstat, xv_block) =
  let _f (retstat : 'tv_retstat) = (Some retstat : Ast.Block.t) in
  (raise Not_found : 'tv_retstat * Ast.Block.t)
```

When compiling `foo.ml` (being the root module) and `ast.ml`, and then generating the interface of `parser.ml` when specifying that the module Foo should be open (for instance for type inference), it produces the following result:
```ocaml
val xv_retstat : Foo.Ast.Retstat.t
val xv_block : Ast.Block.t
```
The expected interface should be (notice that the prefix Foo is not present on the first line):
```ocaml
val xv_retstat : Ast.Retstat.t
val xv_block : Ast.Block.t
```

For reference, here are the commands I used:
1.  `ocamlc -w -a -no-alias-deps -o foo.cmo -c -impl foo.ml`
2. `ocamlc -w -a -open Foo -o foo__Ast.cmo -c -impl ast.ml`
3. `ocamlc -w -a -short-paths -open Foo -short-paths -i -impl parser.ml`

(credits to @bbc2 for the example)

# Some words about the bug

This bug was triggered in some cases when using Menhir and dune, and was already reported [here in Menhir](https://gitlab.inria.fr/fpottier/menhir/-/issues/26) and [here in dune](https://github.com/ocaml/dune/issues/2450), but no solution was found at that time. This explains why the compilation scheme seems weird (from dune) and why one would want to generate the interface of a strange file (from menhir).

Moreover, the example at the end of [this page from the manual](https://v2.ocaml.org/releases/5.0/htmlman/modulealias.html) let me think that this bug is not the result of an unspecified behavior. Also, changing the interface by hand does not seem to be a satisfactory solution for me, because in practice, with dune and Menhir, the interface is generated and used automatically by the compilation chain.

**Comment by lthls** [comment]
There's one thing I don't understand with your case: the generated signature is correct, so I don't see any bugs.
From the other bug reports you linked to, it seems that the only issue is that dune complains when its implementation details leak into unexpected places. If you can get dune to stop complaining about that you should be fine.

**Comment by gasche** [comment]
As far as I understand the path being used (`Foo.Ast` instead of `Ast`) is also correct/valid, the two are equivalent. I don't really agree with the phrasing of the issue which suggests an incorrect/invalid path.

This does seem to go against the specification of `-short-paths`, but I tend to think of `-short-paths` as a best-effort thing rather than providing optimality guarantees. (It would of course be nice to get the shorter behavior here.)

Two questions:
- This seems to be a pressing issue for you, can you explain how the extra module name negatively affects your workflow? In short, why do you care?
- Do you still observe the issue when `-short-paths` is passed to all compilation commands, not just the last one? (I don't see why this would make a difference, but who knows.)

**Comment by acorrenson** [comment]
Hello there,

I reproduced the scenario proposed by @Gogume1er, and I found interesting insights.
First, to answer the question of @gasche, adding `-no-alias-deps` does not seem to change anything ^^.
Second, the `Foo.` prefix is not generated in the `.mli` if the two modules in ast.ml are nested as follows:

```ocaml
(* ast.ml *)
module Block = struct
  module Retstat = struct
    type t = int list
  end
  type t = Retstat.t option
end
```

Same if the type definitions are taken out of the sub-modules :

```ocaml
(* ast.ml *)
type retstat_t = int list
type block_t = retstat_t option
```

I do not have a good understanding of the internals of the OCaml compiler, but based on the last message of @gabriel, these two examples seem to indicate that we are facing a corner case not covered by the heuristics of `-short-path`.
It is not critical, and we could ignore it, but I'm curious:  do you happen to know where this could come from? I would be interested in having a look, but I don't know where to start.

**Comment by Chaarlesss** [comment]
> As far as I understand the path being used (`Foo.Ast` instead of `Ast`) is also correct/valid, the two are equivalent. I don't really agree with the phrasing of the issue which suggests an incorrect/invalid path.
> 
> This does seem to go against the specification of `-short-paths`, but I tend to think of `-short-paths` as a best-effort thing rather than providing optimality guarantees. (It would of course be nice to get the shorter behavior here.)

Sorry for the confusion, I wasn't very clear in my explanation. But you get it correctly, I was surprised that the path was not fully shortened as I expected it would.
However, if `-short-paths` is only a best-effort, it is clear that the problem comes from dune which assumes that this option provides a guarantee.

> * This seems to be a pressing issue for you, can you explain how the extra module name negatively affects your workflow? In short, why do you care?

This issue is not pressing at all! The other issues I have linked provide tweaks to (temporarily) fix this problem, but I thought it would be nice to fix the problem at the root.
As explained in the other issues, this problem/limitation makes dune to detect a dependency cycle inside the module containing the parser (which is used to generate an interface), and causes the compilation to fail.

**Comment by gasche** [comment]
> As explained in the other issues, this problem/limitation makes dune to detect a dependency cycle inside the module containing the parser (which is used to generate an interface), and causes the compilation to fail.

`ocamldep` supports the option `-map <file>` to pass file(s) containing module aliases (here `foo.ml`) as extra information, and correctly understands that `Foo.Ast` does not actually depend on `Foo` but only on `Foo__Ast` (given the alias definition). I wonder why dune, which has full control over the alias mapping logic, does not use the mappings for dependency reasoning in a similar way.

**Comment by Octachron** [comment]
@acorrenson , the current compiler short-path algorithm is exploring part of the typing environment on the fly when printing (in the `Printtyp` module). There are no guarantees on when it will discover canonical path. Moreover, the current implementation will be completely replaced by Merlin's version at some point ... hopefully in 5.2 if I find enough time.

Overall, relying on interface file generated by `-i` in a build system is an explicitly unsupported use case. In particular, the printed interface file is not even guaranteed to be a valid mli file (due to signature avoidance issue).

**Comment by acorrenson** [comment]
> @acorrenson , the current compiler short-path algorithm is exploring part of the typing environment on the fly when printing (in the `Printtyp` module). There are no guarantees on when it will discover canonical path. Moreover, the current implementation will be completely replaced by Merlin's version at some point ... hopefully in 5.2 if I find enough time.
> 
> Overall, relying on interface file generated by `-i` in a build system is an explicitly unsupported use case. In particular, the printed interface file is not even guaranteed to be a valid mli file (due to signature avoidance issue).

Thanks a lot for the detailed answer!

**Comment by Octachron** [comment]
Rereading the discussion, it seems that the discussion was mostly settled. Even if the behavior of `-short-path` might improve in the future, the output of `-i` is not stable enough to use in a build system.
