### ISSUE TITLE
open_process kill pid

### ISSUE THREAD

**Issue by craff** [ocaml/ocaml#12329]
If we start a server with `open_process` and alike, killing the pid returned by `open_process_pid` only kill the shell on my configuration. More generally, the pid should be the pid of the process running in the shell not the pid of the shell so we can send signal to the process.

**Comment by craff** [comment]
You can assign me, I will submit a PR rapidely.

**Comment by Octachron** [comment]
First, there is no `open_process_pid` function.

Second, the process id returned by `create_process` is the pid of the child process, not the pid of the shell.

Could you please try to write down a small reproducible example exhibiting the behavior that you are describing?

**Comment by craff** [comment]
Here is a reproducing program to compile with `ocamlopt -I +unix unix.cmxa test.ml`

```

let loop = (Sys.argv.(1) = "--loop")

let _ =
  if loop then
    while true do
      Unix.sleep 100
    done
  else
    let chs = Unix.open_process (Sys.argv.(0) ^ " --loop") in
    let pid = Unix.process_pid chs in
    let delay = int_of_string Sys.argv.(1) in
    Printf.printf "killing %d in %d second\n%!" pid delay;
    let _ = Unix.sleep delay in
    Unix.kill pid Sys.sigint
```

Running will give:

```
raffalli@oulala:~/Programming/open_process_test/bin$ ./a.out 2 &
[4] 676087
raffalli@oulala:~/Programming/open_process_test/bin$ killing 676088 in 2 second
ps -ax | grep a.out
 676088 pts/2    S      0:00 /bin/sh -c ./a.out --loop
 676089 pts/2    S      0:00 ./a.out --loop
 676091 pts/2    S+     0:00 grep --color=auto a.out
[4]-  Fini                    ./a.out 2
```

pid is 676088, which is the pid of the shell and the loop is never killed.

**Comment by craff** [comment]
I tested with 5.0 and 5.1 alpha2 and debian 12

**Comment by nojb** [comment]
This is expected behaviour as far as I can see:

- `open_process` uses a shell to execute a command line, so it returns the PID of the shell (what else could it return? suppose you do `open_process "foo | bar"`, which PID should it return?).
- killing a process (or, more generally, sending a signal) does not cause its child process(es) to be killed: this is the standard behaviour in Linux; read about "process groups" https://en.wikipedia.org/wiki/Process_group to learn how to control the distribution of a signal to the children of a process.

**Comment by Octachron** [comment]
It might be a good idea to update the documentation of `process_pid`:

> Return the pid of a process opened via Unix.open_process or Unix.open_process_args

to mention that `Unix.open_process` opens a shell:

> Return the pid of a process opened via Unix.open_process_args, or the pid of a shell opened by Unix.open_process

to make it more explicit that the child `process` created by `open_process_args` and `open_process` are not the same.

**Comment by xavierleroy** [comment]
It could make sense to use process groups for commands spawned by `Unix.open_process*`.  Is there anywone who knows this stuff well and could tell us?  Also, it could be interesting to see how Perl implements the similar "open pipe to a process" functionality.

**Comment by craff** [comment]
I think, as suggested by @Octachron , that saying 'pid of the shell' in the documentation of
`Unix.process_pid̀ whould have avoided my confusion.

Further more if the shell started by Unix.open_process was in its own process group,
using `setpgid(mypid,mypid);`, then

```
let pid = Unix.process_pid chs in
Unix.kill (-pid) Sys.sigint;
```

Would send signal to the shell and all its children

`setpgid` is available on POSIX, but I don't know for windows.

**Comment by craff** [comment]
The PR for the doc is merged, but do we want to continue talking about process group on this issue ?

**Comment by gasche** [comment]
Note: only `open_process_{in,out,full}` use a shell, because they take their command as a `string`, the `open_process_args*` functions do not use a shell, because they take their command as a `string * string array`. So my recommendation for the code example above would be to move to using an `_args` function.

**Comment by gasche** [comment]
The documentation problem has been fixed, now the `open_process_{in,out,full}` are documented as calling a shell and recommend calling `open_process_args_*` instead. I don't think we will ever change the implementation of `open_process_{in,out,full}` to avoid a shell, as this would require parsing the `string` and we don't want that. Closing.
