### ISSUE TITLE
Hooks for running code at module "destruction"

### ISSUE THREAD

**Issue by rlepigre** [ocaml/ocaml#12332]
When implementing a library, it is often necessary to run some initialisation code, which can be made to run using something like the following.
```ocaml
module M : sig
  val peek : unit -> int 
end = struct
  let init () = ...
  let peek () = ...

  let _ = init ()
end
```
The point being that users of the library do not have to explicitly care about initialisation, since the fact that using the module will do that for them.

Now, if the `init` function in the above example allocates resources (say, a file descriptor) via C stubs, then it would be great if there was a way to run code at module "destruction" (not sure what the right terminology is). This feature could, I believe, be simply provided as a hook. So we would get something like the following.
```ocaml
module M : sig
  val peek : unit -> int 
end = struct
  let init () = ...
  let drop () = ...
  let peek () = ...

  let _ =
    add_program_end_hook drop;
    init ()
end
```

I know that `Gc.finalise` can be used to obtain that kind of behaviour, but that only works when the resources allocated at module initialisation can be tied to an OCaml heap-allocated value, but that is not always the case. An artificial such value could potentially be kept around, but would make the code uselessly more complicated.

**Comment by dbuenzli** [comment]
What about `Stdlib.at_exit` ?

**Comment by rlepigre** [comment]
Ah, that is exactly what I was looking for. For some reason I could not find it. Thanks!
