### ISSUE TITLE
open_process_args and first element of the array

### ISSUE THREAD

**Issue by craff** [ocaml/ocaml#12330]
The documentation of `open_process_args` does not say that the first element of the `args` array must be the command name. It should also say how the first argument of `open_process_args` and the first element of the array are used (name of the command and argv[0] I guess?). It should be written so that ocaml programmer not familiar to `exec` family of commands can use it directly.

**Comment by craff** [comment]
You can assign me, I will submit a PR rapidely.

**Comment by Octachron** [comment]
Note that the convention for the first argument of argv is OS dependent and even on unix, the convention is quite vague. However, documenting that this argument might have a special meaning is probably a good idea.

**Comment by craff** [comment]
> 

Maybe, ocaml could make a clear choice ?

**Comment by craff** [comment]
Just submitted a PR.

Maybe OCaml could impose a strict choice for the first argument of the array ? This might make code that do not work on all plateform ?

**Comment by craff** [comment]
PR is merged, closing
