### ISSUE TITLE
Give warning for unused module alias inside a function

### ISSUE THREAD

**Issue by bikallem** [ocaml/ocaml#12351]
It would be nice if the OCaml compiler generated warning for the code below.

```ocaml
let f () =
  let module O = Option in
  print_string "hello, world!"
```
The module alias `O` in `let module O = Option` in unused in function `f`. Could the OCaml compiler give similar warning as un-used open/value warning, i.e.

**Comment by Octachron** [comment]
This is already the case:
```
2 |   let module O = Option in
                 ^
Warning 60 [unused-module]: unused module O.
```

**Comment by bikallem** [comment]
Do you have to use some sort of command line switch to get the warning?
I tried the following but none of them seem to generate the warning.

```
$ cat a.ml
let f () =
  let module O = Option in
  print_string "hello, world!"

let () = f ()
$ ocaml a.ml
$ ocamlc a.ml
$ ocamlopt.opt a.ml
$ dune b a.ml
```

**Comment by anmonteiro** [comment]
`-w +60` for example.

**Comment by bikallem** [comment]
I managed to find this https://github.com/ocaml/ocaml/blob/trunk/utils/warnings.mli but not sure if this is the definitive list.  Are these warnings documented in the manual somewhere perhaps?

**Comment by nojb** [comment]
> Are these warnings documented in the manual somewhere perhaps?

They are documented in the tool itself (`ocamlc -warn-help`) and in the manual, in the documentation of the `-w` flag: https://v2.ocaml.org/manual/comp.html#s%3Acomp-options.

**Comment by Octachron** [comment]
There are also documented in the manpage of `ocamlc`.
