### ISSUE TITLE
Constant variant types as a subtype of int

### ISSUE THREAD

**Issue by craff** [ocaml/ocaml#12366]
I would really be nice to allow (t :> int) when t is a variant type with only constant constructors. 
And in the same time to allow to choose the integer representation. 

Here is a possible application (it currently compiles using fake constructor and Obj.magic)

```
type t =
  | Unused1 (*could be removed*)
  | A (*[@@ eq 1]*)
  | C (*[@@ eq 2]*)
  | Unused2 (*could be remove*)
  | D (*[@@ eq 4]*)

let subint : t -> int = Obj.magic (* subint x to be replaces by (x : t :> int) *)

let frequencies : t list -> float array = fun l ->
  let nbs = Array.make (subint D + 1) 0 in
  List.iter (fun x -> nbs.(subint x) <- nbs.(subint x) + 1) l;
  Array.map (fun x -> float x /. float (List.length l)) nbs

module Set  : sig
    type set
    val empty : set
    val singleton : t -> set
    val add : t -> set -> set
    val union : set -> set -> set
    val inter : set -> set -> set
    val mem : t -> set -> bool
end = struct
  type set = int
  let empty = 0
  let singleton x = subint x
  let union = (lor)
  let inter = (land)
  let add x s = union (singleton x) s
  let mem x s = (subint x) land s <> 0
end
```

**Comment by copy** [comment]
Note that the OCaml compiler already recognizes identity functions from variant constructors to int: https://godbolt.org/z/PWWfGK6Wb

**Comment by craff** [comment]
@copy And unfortunately, this does not:

```
type u
type v
type _ tmp =
| U0 : u tmp
| A  : v tmp
| B  : v tmp
| U3 : u tmp
| C  : v tmp
| U5 : u tmp
| U6 : u tmp
| U7 : u tmp
| D  : v tmp

type t = v tmp

let to_int : t -> int = function
  | A -> 1
  | B -> 2
  | C -> 4
  | D -> 8
  | _ -> .
```
```
$ ocamlc -dlambda constants.ml -c
(setglobal Constants!
  (let
    (to_int/279 =
       (function param/280[int] : int
         (catch
           (switch* (-1+ param/280)
            case int 0: (exit 1)
            case int 1: 2
            case int 2: (exit 1)
            case int 3: 4
            case int 4: (exit 1)
            case int 5: (exit 1)
            case int 6: (exit 1)
            case int 7: 8)
          with (1) 1)))
    (makeblock 0 to_int/279)))
```

The dlambda is actually a bit surprinsing ?

**Comment by yallop** [comment]
I think it's unlikely that we'll do this without introducing more general support for subtyping between types with related representations.  It would be odd if for types 

```ocaml
type ab = A | B
type abc = A | B | C
```

both `ab` and `abc` were subtypes of `int` without `ab` also being a subtype of `abc`.  And it would be odd, too, to arbitrarily restrict representation subtyping to variants with only nullary constructors.

There's some related discussion under https://github.com/ocaml/ocaml/issues/9459 for the special case of the empty variant (although, in accordance with tradition, the discussion mostly switched to focus on the scholastic question of whether there should be a single incorporeal empty variant type or an innumerable multitude).

**Comment by gasche** [comment]
I broadly agree with @yallop. I'm not fond of adding more subtyping relations for low-level efficiency hacks, but I would be in favor of ensuring that conversion functions written as a pattern match get compiled efficiently.
