### ISSUE TITLE
Stdlib: `seek_in ch (-1)` should fail

### ISSUE THREAD

**Issue by vouillon** [ocaml/ocaml#12400]
Trying to seek to a negative position fails, except for position `-1`:
```
# seek_in stdin (-2);;
Exception: Sys_error "Illegal seek".
# seek_in stdin (-1);;
- : unit = ()
```

**Comment by nojb** [comment]
This seems to be system-dependent: on OS X, `seek_in stdin n` seems to work for many negative values of `n`.

**Comment by gasche** [comment]
The reason why `-1` works is in the runtime code:

```c
CAMLexport void caml_seek_out(struct channel *channel, file_offset dest)
{
  /* ... */
  if (lseek(channel->fd, dest, SEEK_SET) != dest) {
    caml_leave_blocking_section();
    caml_sys_error(NO_ARG);
  }
  /* ... */
}
```

`lseek` returns the offset it actually set. If you observe the error value `-1` when asking to set to offset `-1`, the test passes and the function considers it a success.

I don't understand why OSX would accept other negative values, as the OSX manpage for `lseek` says that it should return `-1` on error. Oh well.

**Comment by nojb** [comment]
> The reason why `-1` works is in the runtime code:

Thanks, I hadn't grasped this.
