### ISSUE TITLE
Issues with dynlink on Cygwin

### ISSUE THREAD

**Issue by maroneze** [ocaml/ocaml#12419]
I'm having a few issues related to Dynlink on Cygwin.

As an example, the following program compiles and runs without issue on my Linux (after installing package `num`):

```ml
let () =
  Dynlink.loadfile "/home/user/.opam/<version>/lib/ocaml/nums.cmxs"
```

I'm running `ocamlopt dynlink.cmxa file.ml && ./a.out` to compile and run it.

The `nums.cmxs` file has the following permissions: `-rw-r--r--`.

On Cygwin, however, the same program, when compiled and run as:

```
ocamlopt dynlink.cmxa file.ml && ./camlprog
```

Results in:

    Fatal error: exception Dynlink.Error (Dynlink.Cannot_open_dll "Dynlink.Error (Dynlink.Cannot_open_dll \"Failure(\\\"Permission denied\\\")\")")

So, the first issue is: on Cygwin, the *error message does not contain the filename*.

Reading the source code, it seems like the filename should be printed as expected (as is the case on Linux, when there is a permission error), but there seems to be another exception that is raised when trying to print its name, resulting in a somewhat unhelpful message.

The second issue is: why, only on Cygwin, is there a permission denied? Or, more specifically, why does Dynlink require execution permission on `.cmxs` files being loaded?

I found out that by running `chmod u+x /home/user/.opam/<version>/lib/ocaml/nums.cmxs`, the execution of `./camlprog` works on Cygwin.

I'm using `nums.cmxs` as an example since it's the simplest to install package that does not have its execute bit set on the `.cmxs` file (its installer is pre-dune; packages installed by dune seem to have the execute bit set by default), but it probably also happens with a few other packages. For instance, in my local installation, I also found `.cmxs` without execute bit in: `why3`, `rresult`, `uutf`, `topkg`, `react`.

**Comment by nojb** [comment]
> The second issue is: why, only on Cygwin, is there a permission denied? Or, more specifically, why does Dynlink require execution permission on `.cmxs` files being loaded?

Dynlinking depends on the dynamic linker which is system-specific. On Windows (including Cygwin), the dynamic linker requires the executable bit to be set.

**Comment by nojb** [comment]
> So, the first issue is: on Cygwin, the _error message does not contain the filename_.

I believe this has been fixed in #12213 (cc @shym).

**Comment by maroneze** [comment]
> Dynlinking depends on the dynamic linker which is system-specific. On Windows (including Cygwin), the dynamic linker requires the executable bit to be set.

Thanks, I wasn't aware of that, and I believe that to be the case for many package developers. Would there be a way to systematically detect and warn about missing execute bit in installed .cmxs files, to help improve Windows compatibility?

I wonder if a mention to it in [Dynlink's API](https://v2.ocaml.org/api/Dynlink.html) would be helpful or unnecessary.

Maybe this would be better handled at the opam or opam-repository levels.

**Comment by nojb** [comment]
> Would there be a way to systematically detect and warn about missing execute bit in installed .cmxs files, to help improve Windows compatibility?

My feeling is that the compiler is not the right place to handle this: staying as naïve as possible with respect to the underlying system infrastructure simplifies debugging whenever things stop working.

> Maybe this would be better handled at the opam or opam-repository levels.

It seems Dune already does the right thing here: it uses the `libexec:` section to install `.cmxs` files, which automatically sets the executable bit (see https://opam.ocaml.org/doc/Manual.html#installfield-libexec).

https://github.com/ocaml/dune/blob/d7d5c18a3be7d991a9948ae34776f6f4126b183c/src/dune_rules/install_rules.ml#L106

It seems to me that the simplest thing would be to to alert the relevant upstream developers that they should be using `libexec:` rather than `lib:` when installing `.cmxs` files. For example, `topkg` currently uses `lib:` by default for all library files (cc @dbuenzli):

https://github.com/dbuenzli/topkg/blob/cb02c52c04ed5080ac4a219756c2f5e4381fd465/src/topkg_install.ml#L170

**Comment by xavierleroy** [comment]
I sympathize with @nojb's viewpoint: the OCaml compiler has no idea what permissions a .cmxs file must have, because it relies on a external tool (the linker) to create .cmxs files.  The issue seems to be with installation procedures in libraries  and packages that don't preserve the "x" bit.

**Comment by maroneze** [comment]
Ok, I will try to propose some checks for opam-ci. Thanks for the link to the PR which fixed the error message.
