### ISSUE TITLE
runtime/floats.c: error: implicit declaration of function 'copysign' on NetBSD 9.0ｰ9.2

### ISSUE THREAD

**Issue by omasanori** [ocaml/ocaml#12413]
While NetBSD's libm provides C99 `copysign`, `math.h` hides it unless certain condition satisfies:
```c
#if (!defined(_ANSI_SOURCE) && !defined(_POSIX_C_SOURCE) && \
    !defined(_XOPEN_SOURCE)) || ((_POSIX_C_SOURCE - 0) >= 200809L || \
     defined(_ISOC99_SOURCE) || (__STDC_VERSION__ - 0) >= 199901L || \
     (__cplusplus - 0) >= 201103L || defined(_NETBSD_SOURCE))
#define __MATH_C99_FEATURES
#endif

(...)

#if defined(__MATH_C99_FEATURES) || (_XOPEN_SOURCE - 0) >= 600 || \
    (_POSIX_C_SOURCE - 0) >= 200112L

(...)

double	copysign(double, double);

(...)

#endif /* !_ANSI_SOURCE && ... */
```
which causes a warning:
```
runtime/floats.c: In function 'caml_copysign':
runtime/floats.c:1071:10: error: implicit declaration of function 'copysign' [-Werror=implicit-function-declaration]
   return copysign(x, y);
          ^~~~~~~~
runtime/floats.c:1071:10: error: incompatible implicit declaration of built-in function 'copysign' [-Werror]
runtime/floats.c:1071:10: note: include '<math.h>' or provide a declaration of 'copysign'
```
Defining `_NETBSD_SOURCE` in addition to `_GNU_SOURCE` in `runtime/floats.c` seems enough to fix it.

Full build log: https://builds.sr.ht/~omasanori/job/1028642

**Comment by omasanori** [comment]
The proper fix may be adding `-std=c99` (or even `-std=c11`?) to `CFLAGS` if CC is GCC or Clang, though.

**Comment by omasanori** [comment]
Well, NetBSD developers are actually aware of this: https://github.com/NetBSD/pkgsrc/blob/trunk/lang/ocaml/patches/patch-runtime_floats.c

**Comment by gasche** [comment]
This seems to be a NetBSD issue rather than an OCaml issue. The NetBSD downstream workaround patch says:

> Not filed upstream pending discussion within NetBSD.

Do you know if there was a discussion and how it went? (cc @jaapb)

**Comment by omasanori** [comment]
I have managed to find the thread: [math.h, copysign, visibility defines](https://marc.info/?t=164570766200002)

**Comment by omasanori** [comment]
The patch was committed to the NetBSD 9 branch in May 2022 https://github.com/NetBSD/src/commit/20a720250ce41d61aec383f71e8a80e39634bb5d and NetBSD 9.3 was released in August 2022. The CI server uses NetBSD 9.2 released in May 2021, so that was not fixed yet. I got it.

**Comment by avsm** [comment]
If there is a released version of NetBSD without this bug (NetBSD 9.3), then I don't think we should add the workaround `#define`.  Might you be able to request an upgrade of the CI server image and see if the build is clean there?

**Comment by omasanori** [comment]
> If there is a released version of NetBSD without this bug (NetBSD 9.3), then I don't think we should add the workaround #define.

Fair point. It is okay to me to close this and https://github.com/ocaml/ocaml/pull/12414, though I think https://github.com/ocaml/ocaml/issues/12417 is still valid.

> Might you be able to request an upgrade of the CI server image and see if the build is clean there?

Yes, I did: https://lists.sr.ht/~sircmpwn/sr.ht-discuss/%3Cff415d94-6d7f-45aa-a5a1-fd4d6e293dbf%40cern.ch%3E

**Comment by omasanori** [comment]
NetBSD VM on sr.ht has been updated to 9.3 and the build error disappeared: https://builds.sr.ht/~omasanori/job/1054372
The failure of tests above was already reported btw: https://github.com/ocaml/ocaml/issues/12415

**Comment by omasanori** [comment]
As it is confirmed that this issue does not affect the latest release of NetBSD 9 series, I close it as not planned.
