### ISSUE TITLE
Document that `Unix.fork` cannot be used after `Domain.spawn`

### ISSUE THREAD

**Issue by igarnier** [ocaml/ocaml#12435]
`Unix.fork` cannot be used after any domain was created, even after those domains are joined. It seems this is not documented. The error message is perhaps clear enough but adding another layer of explanation would not hurt.

Example program that one may wrongly expect to not fail:

```ocaml
(* ocamlopt -I +unix unix.cmxa ./test.ml *)

let () = Domain.spawn Fun.id |> Domain.join

let () =
  let _pid = Unix.fork () in
  exit 0

(* Fatal error: exception Failure("Unix.fork may not be called while other domains were created") *)
```

**Comment by nojb** [comment]
> It seems this is not documented.

This was done in #11386:

https://github.com/ocaml/ocaml/blob/2a1cdfaa9d1d0b545ce9dc7ba7bf36232e59a56e/otherlibs/unix/unix.mli#L245-L255

**Comment by igarnier** [comment]
Great news! Closing this, then.
