### ISSUE TITLE
Stdlib.sincos [feature request]

### ISSUE THREAD

**Issue by UnixJunkie** [ocaml/ocaml#12463]
Currently, we have Stdlib.sin and Stdlib.cos.
I guess it would be not much work to also bind sincos from math.h (sin and cos also come from there).

I tried to start a discussion there:
https://discuss.ocaml.org/t/we-dont-have-sincos-in-the-stdlib/12756

**Comment by lthls** [comment]
What type would you give this function ? `float -> float * float` means that you have to allocate a tuple for the result, and cannot unbox the result. `float -> Float.array` is a bit better, as you can store the float results unboxed, but it's not very intuitive (and you need array accesses to get the results). You could use `float -> sin:float ref -> cos:float ref -> unit`, to follow the C function, but it doesn't feel natural in OCaml.

More importantly, I expect that all these solutions are more expensive than just calling `cos` and `sin` separately, even if `sincos` is as fast a a single call to `sin` or `cos`.

Could you at least provide an example of how you would use this function ?

**Comment by xavierleroy** [comment]
I agree this function doesn't play well with unboxing of FP numbers.  Plus, `sincos` is not standard  from the C math library, it's a GNU extension.

**Comment by UnixJunkie** [comment]
I did not have any interface in mind currently.
But, since this is for performance reasons, I guess "float -> sin:float ref -> cos:float ref -> unit" might be the proper interface.
Of course, if even a "performance oriented" interface like this ends up in a function that is more expensive to call than
calling sin then cos separately, then you can reject my feature request.

**Comment by xavierleroy** [comment]
> a "performance oriented" interface like this ends up in a function that is more expensive to call than calling sin then cos separately

You could write your own binding(s) to the `sincos` function and report your performance figures here, that would be a great way to know what to do with this feature request.

**Comment by UnixJunkie** [comment]
Ok, I will try to do that.
Maybe this week I will have some time.

**Comment by yawaramin** [comment]
Apparently Apple `math.h` added `__sincos` in 10.9 according to https://github.com/NixOS/nixpkgs/issues/31725#issuecomment-538356259

On MSVC, the dotnet people got a report that running the binding for sincos is slower than calling sin/cos separately: https://github.com/dotnet/runtime/issues/48776

**Comment by UnixJunkie** [comment]
I did a naive binding in there: https://github.com/UnixJunkie/ocaml_sincos/
a la Stdlib.modf (because this is the only binding I can write easily).

If my tests are meaningful, on my computer this binding of sincos is ~150% slower than sin and cos.

**Comment by gasche** [comment]
I don't think this makes any difference, but the binding code is currently wrong:

```c
CAMLprim value caml_sincos_float(value f)
{
  CAMLparam0 ();
  CAMLlocal2 (sine, cosine);
  value res = caml_alloc_small(2, 0);
  double x;
  double y;

  sincos(Double_val(f), &x, &y);

  sine = caml_copy_double(x);
  cosine = caml_copy_double(y);
  Field(res, 0) = sine;
  Field(res, 1) = cosine;
  CAMLreturn (res);
}
```

You need to either register `f` as a root (`CAMLparam1 (f);`), or call `sincos` before the call to `caml_alloc_small` that may invalidate `f`.

Note: I think that if you wanted to get better performance you should try returning a flat float array rather than a pair. (You could also take a flat float array of length 2 as input, but this gets unnatural for callers.)

**Comment by UnixJunkie** [comment]
Apparently, even using an already allocated struct w/ two mutable floats to hold the result doesn't make sincos go faster than sin then cos.

**Comment by gasche** [comment]
I sent you a PR to improve your benchmarks at https://github.com/UnixJunkie/ocaml_sincos/pull/1

The result still suggest that indeed there are no clear benefits to calling `sincos` rather than `sin` and `cos`. Should we consider closing this feature request?

**Comment by UnixJunkie** [comment]
Ok, so even bindings written by an expert (@gasche) don't provide some very significant performance gain from sincos over sin then cos. I think this can be closed.

**Comment by tannergooding** [comment]
> don't provide some very significant performance gain

Notably, the significant performance gain can exist on some platforms, it just may not exist on all platforms and may vary based on the underlying `libm` implementation.
