### ISSUE TITLE
Comments are parsed incorrectly by ocamldoc

### ISSUE THREAD

**Issue by 314eter** [ocaml/ocaml#12469]
Ocamldoc uses a simple lexer to support nested comments, but OCaml comments are more complicated than that. String, character and quoted string literals in comments should be parsed too.

Is ocamldoc still actively used and maintained, or is everyone using odoc (which doesn't have this issue)? I can look into fixing it, but it will require rewriting most of the ocamldoc lexer, so I'm not sure it's worth the effort.

### Examples

This valid comment will crash ocamldoc, since it thinks the `(*` starts a nested comment.
```ocaml
(** "(*" *)
```

The content of the special comment should be `"*)"`, but ocamldoc only sees `"`.
```ocaml
(** "*)" *)
```

The special comment will be silently ignored (ocamldoc doesn't complain if a normal comment is not closed).
```ocaml
(* "(*" *)
(** test *)
```

This should be one single comment, but ocamldoc thinks there are three (and recognizes the special comment).
```ocaml
(* " *)
(** test *)
(* " *)
```

**Comment by gasche** [comment]
> Is ocamldoc still actively used and maintained, or is everyone using odoc (which doesn't have this issue)? I can look into fixing it, but it will require rewriting most of the ocamldoc lexer, so I'm not sure it's worth the effort.

As far as I know:
- The vast majority of users are using dune, which only supports odoc.
- Ocamldoc has been in almost-no-maintenance mode for years with various non-critical bugs such as this one, and most users got the message and switched to odoc (which has its own bugs, but is being actively maintained)
- One notable user of ocamldoc remains the OCaml manual; odoc support has in theory been implemented but is not currently used to generate the module-documentation parts of the manual (in particular the standard library). Doing this (used to be blocked by limitations of odoc, such as the absence of a TeX backend) is probably not too much work, but the person for which this would be easiest is @Octachron and he already has his plate full with other things.

**Comment by Octachron** [comment]
I agree with the stale bot on this matter: it is better to encourage people to switch to ocamldoc rather than rewriting the ocamlodoc lexer.
