### ISSUE TITLE
Compiler behaviour on `-o foo` and no input files

### ISSUE THREAD

**Issue by shindere** [ocaml/ocaml#12497]
`gcc -o foo` says `gcc: fatal error: no input files` and fails (exit code 1).

When given `-o foo` as arguemnts, both ocamlc and ocamlopt will succeed
(exit with 0), emit no error message but not write an executable file either.

Am I correct that this is a bug rather than a feature?

Would be happy to provide a fix because, while working on the compiler's
build system, I'm regularly bitten by this when, for some reason,
the GNU make variable that is supposed to contain the list of input
files turns out to be empty.

**Comment by gasche** [comment]
There would be one sensible behavior for `ocamlc -o foo`, which is to emit a program that does nothing. We are doing something else, so the current behavior is buggy, and I believe it is okay to change it to something else. So yes, from a distance I think that emitting an error in this case would be a reasonable change.
