### ISSUE TITLE
ocamlyacc allows for rules with ocaml keyword names

### ISSUE THREAD

**Issue by CharlesAverill** [ocaml/ocaml#12565]
Had this rule in my grammar:

```
type :
    UNIT 
      { UnitT }
    | type ARROW type 
      { ArrowT ($1, $3) }
```

And it generated code like this:

```
; (fun __caml_parser_env ->
    Obj.repr(
# 45 "lib/lang/parser.mly"
      ( UnitT )
# 212 "lib/lang/parser.ml"
               : 'type))
; (fun __caml_parser_env ->
    let _1 = (Parsing.peek_val __caml_parser_env 2 : 'type) in
    let _3 = (Parsing.peek_val __caml_parser_env 0 : 'type) in
```

which threw a generic syntax error (due to `type` being a reserved OCaml keyword).

`ocamlyacc` should warn about this instead of silently generating invalid code.

**Comment by Octachron** [comment]
Note that `menhir` fails with an explicit error when using an OCaml keyword as a symbol: the bug fix is thus probably to switch to `menhir`.
