### ISSUE TITLE
fatal error: zstd.h: No such file or directory

### ISSUE THREAD

**Issue by smorimoto** [ocaml/ocaml#12564]
I just found that when I try to install the OCaml compiler with `ocaml-variants.5.1.0+options`, I get the following error:

```
  #=== ERROR while compiling ocaml-variants.5.1.0+options =======================#
  # context     2.1.5 | linux/x86_64 | ocaml-option-flambda.1 ocaml-option-musl.1 ocaml-option-static.1 | git+https://github.com/ocaml/opam-repository.git
  # path        ~/work/setup-ocaml/setup-ocaml/_opam/.opam-switch/build/ocaml-variants.5.1.0+options
  # command     ~/.opam/opam-init/hooks/sandbox.sh build make -j2
  # exit-code   2
  # env-file    ~/.opam/log/ocaml-variants-3297-c170a7.env
  # output-file ~/.opam/log/ocaml-variants-3297-c170a7.out
  ### output ###
  #   CC runtime/sak.o
  #   MKEXE runtime/sak
  # make coldstart
  # make[1]: Entering directory '/home/runner/work/setup-ocaml/setup-ocaml/_opam/.opam-switch/build/ocaml-variants.5.1.0+options'
  # make runtime-all
  # make[2]: Entering directory '/home/runner/work/setup-ocaml/setup-ocaml/_opam/.opam-switch/build/ocaml-variants.5.1.0+options'
  #   GEN runtime/ld.conf
  #   GEN runtime/caml/opnames.h
  #   GEN runtime/caml/jumptbl.h
  #   GEN runtime/build_config.h
  #   GEN runtime/primitives
  #   CC runtime/addrmap.b.o
  #   CC runtime/afl.b.o
  #   CC runtime/alloc.b.o
  #   CC runtime/array.b.o
  #   CC runtime/backtrace.b.o
  #   CC runtime/bigarray.b.o
  #   CC runtime/callback.b.o
  #   CC runtime/codefrag.b.o
  #   CC runtime/compare.b.o
  #   CC runtime/custom.b.o
  #   CC runtime/debugger.b.o
  #   CC runtime/domain.b.o
  #   CC runtime/dynlink.b.o
  #   CC runtime/extern.b.o
  #   CC runtime/fiber.b.o
  # runtime/extern.c:37:10: fatal error: zstd.h: No such file or directory
  #    37 | #include <zstd.h>
  #       |          ^~~~~~~~
  # compilation terminated.
  # make[2]: *** [Makefile:971: runtime/extern.b.o] Error 1
  # make[2]: *** Waiting for unfinished jobs....
  # make[2]: Leaving directory '/home/runner/work/setup-ocaml/setup-ocaml/_opam/.opam-switch/build/ocaml-variants.5.1.0+options'
  # make[1]: *** [Makefile:209: coldstart] Error 2
  # make[1]: Leaving directory '/home/runner/work/setup-ocaml/setup-ocaml/_opam/.opam-switch/build/ocaml-variants.5.1.0+options'
  # make: *** [Makefile:375: world.opt] Error 2
```

https://github.com/ocaml/setup-ocaml/actions/runs/6191691853/job/16810453662?pr=696#step:3:1167

The log says that it has not been able to find `zstd` well, but that seems to have been found in an earlier log. It seems like a bug, in fact, since `zstd` is installed by default for GitHub Actions runners.

```
  - configure: compressed marshaling supported
```

https://github.com/ocaml/setup-ocaml/actions/runs/6191691853/job/16810453662?pr=696#step:3:1058

**Comment by xavierleroy** [comment]
One possibility is that `musl-gcc` doesn't look in `/usr/include`, while OCaml's configure relies on pkg-config, which assumes that `/usr/include` is always on the include search path.  Can you reproduce the problem outside of github actions?

**Comment by xavierleroy** [comment]
I would suggest that the ocaml-variant package for 5.1 configures with `--without-zstd` if `musl-gcc` is used as the C compiler, i.e. if the "musl" variant is selected and we're not running Alpine.  This should work around the problem.  Cc @octachron .

**Comment by copy** [comment]
> The log says that it has not been able to find zstd well, but that seems to have been found in an earlier log. It seems like a bug, in fact, since zstd is installed by default for GitHub Actions runners.

This is a common issue when using musl-gcc (or in general, musl as a secondary libc): You can't use libraries that were compiled against glibc with musl. Those libraries need to be compiled manually, with the prefix set to musl's prefix (`/usr/lib/musl` for Arch).

> One possibility is that musl-gcc doesn't look in /usr/include, while OCaml's configure relies on pkg-config, which assumes that /usr/include is always on the include search path.
>
> I would suggest that the ocaml-variant package for 5.1 configures with --without-zstd if musl-gcc is used as the C compiler, i.e. if the "musl" variant is selected and we're not running Alpine. This should work around the problem.

This is also my understanding, although a better fix would be to set `PKG_CONFIG_LIBDIR`. Then the configure script could properly pick up libzstd if it's installed in the musl prefix.
