### ISSUE TITLE
Why do we skip the forward-shortcut optimization on values with tag `Forward`?

### ISSUE THREAD

**Issue by gasche** [ocaml/ocaml#12567]
A lazy value is either a "thunk" that is not computed yet or is being computed, or a "result" that has already been evaluated and will be returned unchanged. Thunks are blocks of tag Lazy_tag or Forcing_tag, and results may be represented as a single-argument block of tag Forward_tag. But the OCaml runtime performs a "forward shortcutting" optimization, where it may remove the Forward block and use the value directly as the result, which gives a more compact memory representation.

Shortcutting is decided dynamically in the runtime system, and is not performed if the underlying value has tag Lazy_tag or Forcing_tag (it is itself a thunk), Forward_tag (it is itself a result block), or Double_tag (to respect the "float separation" property required for flat-float-array soundness.).

For example, in the serialization code:

https://github.com/ocaml/ocaml/blob/4a458b91ab585629c08af1f0adbd848f32a276eb/runtime/extern.c#L788-L803

**Question**: why do we prevent shortcutting if the value has tag `Forward_tag`?

I have the impression that it would be perfectly sound to also shortcut the `Forward` type on values that are themselves `Forward` blocks.

### 

One can approximate the representation of `lazy` values as the following:

```ocaml
type 'a lazy = 'a lazy_cell Atomic.t
type 'a lazy_cell =
  | CThunk of (unit -> 'a) (* tag Lazy_tag *)
  | CForcing of unit (* tag Forcing_tag *)
  | CForward of 'a (* tag Forward_tag *)
```

but in fact the implementation uses an optimized version

```ocaml
type 'a lazy_cell_opt =
  | Thunk of (unit -> 'a) (* tag Lazy_tag *)
  | Forcing of unit (* tag Forcing_tag *)
  | Forward of 'a (* tag Forward_tag *)
  | Shortcut of 'a (* unboxed, just the ['a] at runtime *)

let of_opt : 'a lazy_cell_opt -> 'a lazy_cell = function
| Thunk f -> CThunk f
| Forcing () -> CForcing ()
| Forward v -> CForward v
| Shortcut v -> CForward v
```

Shortcutting is a smart constructor `forward : 'a -> 'a lazy_cell`, whose specification is that `of_opt (forward v) = CForward v`. Currently it is implemented as follows (let's forget about floats completely):

```ocaml
let forward v =
  match v with
  | Thunk _ | Forcing _ | Forward _ -> Forward v
  | other ->
    (* the tag is not Lazy, Forcing or Forward *)
    Shortcut other
```

This respects the `forward` specification, in particular we have for `v := Forward v'` we have

```ocaml
  of_opt (forward (Forward v'))
= of_opt (Forward (Forward v'))
= CForward (Fordward v')
```

But I believe that we could also use the following

```ocaml
let forward2 v =
  match v with
  | Thunk _ | Forcing _ -> Forward v
  | other ->
    (* the tag is not Lazy or Forcing *)
    Shortcut other

  of_opt (forward2 (Forward v'))
= of_opt (Shortcut (Forward v'))
= CForward (Forward v')
```

We could possibly even go further and use the following, but it becomes sensibly harder to reason about. (I think that we need to quotient the values by the equation "`Forward v ~ Shortcut v` whenever the tag of `v` is not `{Lazy,Forcing}_tag`"). I am not suggesting this.

```ocaml
let rec forward3 v =
  match v with
  | Thunk _ | Forcing _ -> Forward v
  | Forward v -> forward3 v
  | other ->
    (* the tag is not Lazy or Forcing or Forward *)
    Shortcut other
```

**Comment by lthls** [comment]
```ocaml
let v = lazy (lazy 0.) (* Two forwards then a float *)
let a = Array.make 2 (Lazy.force v) (* Array of non-float values *)
let () = a.(0) <- lazy 0.
let r = a.(0)
```
If you shortcut the extra forward tag, then `Lazy.force` reads through the last remaining forward block and returns the float, which makes the runtime assume that you're building an array of floats. The assignment will then try to store the lazy value in a flat float array, and I expect that you will then read garbage (a pointer interpreted as a float).

Even forgetting floats, I believe that shortcutting on forward tags could create cases where you evaluate lazy expressions too early:
```ocaml
let v : int Lazy.t = lazy (failwith "Don't force this")
let v2 = Lazy.from_val (Lazy.from_val v)
let r = Lazy.force (Lazy.force v2)
(* Should not have raised so far *)
```

If I understand correctly your reasoning, the flaw is in assuming that `of_opt` is well-defined. In particular, since you can't distinguish at runtime between `Forward v` and `Shortcut (Forward v)`, you have no guarantee that `of_opt (forward2 v)` will not end up evaluated as `CForward v`

**Comment by gasche** [comment]
I'm convinced! Thanks. Closing.

**Comment by gasche** [comment]
Let us say that a value of the form `Forward (Forward (... (Forward (v))))` with `v` a non-Forward is "unsafe" has tag Double, Lazy or Forcing, and "safe" otherwise. If I understand correctly, Forward blocks can always be shortcut on safe values, and they can never be shortcut on unsafe values. Checking this at runtime adds complexity for cases that occur very rarely, so it is simpler to never shortcut Forward blocks.
