### ISSUE TITLE
Should the compiler's compile-time CFLAGS be hardcoded into ocamlc/ocamlopt?

### ISSUE THREAD

**Issue by purplearmadillo77** [ocaml/ocaml#12578]
Hi,

I have been running into some unexpected behavavior with the default C compiler flags of ocamlc/ocamlopt on Cygwin64 with OCaml 4.14.0.

See some initial discussion here: https://cygwin.com/pipermail/cygwin-apps/2023-August/043106.html 

When `ocamlc` compiles C programs, it gets passed some options
```
$ ocamlc hello.c -verbose
+ gcc -O2 -fno-strict-aliasing -fwrapv -pthread  -ggdb -O2 -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector-strong --param=ssp-buffer-size=4 -fdebug-prefix-map=some_build_path1=/usr/src/debug/ocaml-4.14.0-1 -fdebug-prefix-map=some_build_path2=/usr/src/debug/ocaml-4.14.0-1 -D_FILE_OFFSET_BITS=64 -U_WIN32    -c    -I'/usr/lib/ocaml' 'hello.c'
```
which are a superset of the package-time `CFLAGS` used to build the OCaml compiler itself. The package-time `CFLAGS` are hardcoded into the `ocamlc` executable itself.

Reading https://github.com/ocaml/ocaml/pull/9824, this appears to be an intentional design choice on OCaml's part but it can still cause odd behavior.

In short, all end user C programs compiled with ocamlc will inherit the options that were used to compile the compiler (that could range from very helpful to rather unnecessary options for most cases). However, it's possible some end user programs might not want some of the package-time options (`-O2`, `-Wall`, `-Werror`, `-fdebug-prefix-map`, etc.)

It is possible to negate some of these options on the user side; for example, if one wants to compile without debug info they need to remember to always call `ocamlc -ccopt -ggdb0`.

Even this might not always work: as far as I understand, GCC options with the property "RejectNegative" (https://gcc.gnu.org/onlinedocs/gccint/Option-properties.html) don't have a negative form and thus most of them can't be disabled in an obvious way. 

Previous proposals to include more flags in `ocamlopt` have been wary about defaults that are too strict; e.g. https://github.com/ocaml/ocaml/issues/12050

>"Enabling -ccopt "-Werror -Wall" when using ocamlc/ocamlopt to build C files is a choice of the build system, not something to be decided by the compiler itself."

However, the "compiler deciding itself" is effectively what happens when package time `CFLAGS` are hardcoded into `ocamlc`.

This places a silent but unexpected burden on users to inspect the `ocamlc` default compiler flags and disable ones they deem unnecessary. Is this phenomenon supposed to be part of the intended design choice?

**Comment by glondu** [comment]
I agree with the general idea that not all CFLAGS should be hardcoded into ocamlc/ocamlopt.

> However, it's possible some end user programs might not want some of the package-time options (`-O2`, `-Wall`, `-Werror`, `-fdebug-prefix-map`, etc.)

We've [been hit](https://bugs.debian.org/1030785) by that in Debian and [filter out](https://salsa.debian.org/ocaml-team/ocaml/-/blob/debian/sid/debian/patches/0008-Filter-out-f-debug-file-prefix-map-from-ocamlc_cflag.patch) some options in what ends up hardcoded in the compilers.

**Comment by shindere** [comment]
Many thanks for the report.

From the point of view of OCaml's build system, it' is totally possible
to distinguish C flags and C preprocessar flags used interanlly, on the
one side, from those used when ocmalc/ocamlopt are invoked to compile a
third-party C source file.

My understanding at this stage is that two questions needto be
understood.

1. Are we talking about developer or release compilation mode of OCaml?

In the example that you show, there are options turning warnings into
errors and enabling many warnings, for instance. As far as I could see
those are not turned offin release mode, not even internally.

I am not saying that there is nothing to fix, but rather that, when
fixing, weshold tke the  two modes (release and developemnt) into
account and make sure we fix both.

2. Which C flags and/or C preprocessor flags do you think should not be
used when compiling third-party Csources?

For those interested, the flags the compilers will use to compile C
sources are defined in the `OCAMLC_CFLAGS` variable, defined in
`Makefile.config` and whose value is computed during the configure
stage.

Moreover, `configure.ac` does maintain two lists of C flags and C
preprocessor flags, une to use internally and one to  be used by the
compiler when compiling third-party C sources. See `common_cflags` for
flags to be used in both contexts and \ internal_cflags` for those to be
used internally only, and  their cpp counterparts.

**Comment by purplearmadillo77** [comment]
Thanks for the response and the explanation about the two lists of flags – I'll try my best to clarify things.

> 1. Are we talking about developer or release compilation mode of OCaml?

I think both. That is, the "hardcoding" behavior I describe occurs with both development and release builds, and it can cause surprises in both cases.

> 2. Which C flags and/or C preprocessor flags do you think should not be used when compiling third-party Csources?

As far as I understand, anything provided in `CFLAGS` or `CPPFLAGS` by the person compiling OCaml. Namely, the code in question is the following snippet from `./configure`:

```
ocamlc_cflags="$common_cflags $sharedlib_cflags \$(CFLAGS)"
ocamlc_cppflags="$common_cppflags \$(CPPFLAGS)"
```

where substituting the (internal, package-time) `$CFLAGS` and `$CPPFLAGS` into `ocamlc_cflags` will cause those flags to also be used to compile third-party C source files. 

For example, if one were to configure and build OCaml with 

`CFLAGS="-Dfoo=1 -Dbar=2"`

then, after distributing the resulting compiler executables, user code by default will also compile with the "foo" and "bar" macros defined. 

A more concrete example: for standardization/performance/security purposes, some groups (e.g. Cygwin) might configure compiler packages by default with

`CFLAGS="-ggdb -O2 -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector-strong --param=ssp-buffer-size=4"`

This will result in these ostensibly internal-only options being used to compile external third-party C sources, as shown in the example:

```
$ ocamlc hello.c -verbose
+ gcc -O2 -fno-strict-aliasing -fwrapv -pthread  -ggdb -O2 -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector-strong --param=ssp-buffer-size=4 -fdebug-prefix-map=some_build_path1=/usr/src/debug/ocaml-4.14.0-1 -fdebug-prefix-map=some_build_path2=/usr/src/debug/ocaml-4.14.0-1 -D_FILE_OFFSET_BITS=64 -U_WIN32    -c    -I'/usr/lib/ocaml' 'hello.c'
```

> In the example that you show, there are options turning warnings into errors and enabling many warnings, for instance. As far as I could see those are not turned offin release mode, not even internally.

In contrast, a more "normal" release version of OCaml (such as installing OCaml through opam which I assume configures with nothing in `CFLAGS`) no longer includes the extraneous warnings and options.

```
$ ocamlc hello.c -verbose
+ gcc -O2 -fno-strict-aliasing -fwrapv -pthread   -D_FILE_OFFSET_BITS=64 -U_WIN32    -c    -I'/home/.opam/4.14.0/lib/ocaml' 'hello.c'
```

**Comment by shindere** [comment]
Okay I think I understand the problem and opened #12589 to address it,
at least the fact that configured CFLAGS and CPPFLAGS should not be
stored in the compiler.

Can you please give it a try?

**Comment by purplearmadillo77** [comment]
Yep, with this change it looks like ocamlc no longer passes in the extra options.
```
$ ./ocamlc -verbose hello.c
+ gcc -O2 -fno-strict-aliasing -fwrapv -pthread  -D_FILE_OFFSET_BITS=64 -U_WIN32   -c    -I'/usr/lib/ocaml' 'hello.c'
```
Thank you so much!

**Comment by shindere** [comment]
purplearmadillo77 (2023/09/28 07:09 -0700):
> Yep, with this change it looks like ocamlc no longer passes in the extra options.
> ```
> $ ./ocamlc -verbose hello.c
> + gcc -O2 -fno-strict-aliasing -fwrapv -pthread  -D_FILE_OFFSET_BITS=64 -U_WIN32   -c    -I'/usr/lib/ocaml' 'hello.c'
> ```

It indeed works in this way, but the PR should not be used as-is because
in its current state, the extra C flagsyou pass to configure are not
propagated far enough, i.e. they are not correctly propagated to the
whole build of the compiler itself.

Will make my best to provide a more accurate version ASAP. Sorry for the
inconvenience.

**Comment by purplearmadillo77** [comment]
I dug around a little more and initial evidence suggests the PR does propagate the flags at least as far as they are currently propogated. I compiled ocaml 4.14.1 with `make --trace -j1` both with and without the mentioned edits to configure (the lines for mkexe don't exist for 4.14.1, so those weren't included). I then diffed the trace output and the only place they differ is the actual value of the CFLAGS and related variables.
```
--- ocamlc_cflags_with_cflags.log	2023-12-31 17:56:02.696251600 -0500
+++ ocamlc_cflags_with_patch.log	2024-01-02 13:48:41.870808600 -0500
@@ -1365,10 +1365,10 @@
     -e 's!%%MKMAINDLL%%!flexlink -chain cygwin64 -merge-manifest -stack 16777216 -maindll!' \
     -e 's!%%MODEL%%!default!' \
     -e 's!%%NATIVECCLIBS%%!-lm !' \
-    -e 's!%%OCAMLC_CFLAGS%%!-O2 -fno-strict-aliasing -fwrapv -pthread  -ggdb -O2 -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector-strong --param=ssp-buffer-size=4 -fdebug-prefix-map=/mnt/share/cygpkgs/ocaml/ocaml-4.14.1-1.x86_64/build=/usr/src/debug/ocaml-4.14.1-1 -fdebug-prefix-map=/mnt/share/cygpkgs/ocaml/ocaml-4.14.1-1.x86_64/src/ocaml-4.14.1=/usr/src/debug/ocaml-4.14.1-1!' \
-    -e 's!%%OCAMLC_CPPFLAGS%%!-D_FILE_OFFSET_BITS=64 -U_WIN32 !' \
-    -e 's!%%OCAMLOPT_CFLAGS%%!-O2 -fno-strict-aliasing -fwrapv -pthread  -ggdb -O2 -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector-strong --param=ssp-buffer-size=4 -fdebug-prefix-map=/mnt/share/cygpkgs/ocaml/ocaml-4.14.1-1.x86_64/build=/usr/src/debug/ocaml-4.14.1-1 -fdebug-prefix-map=/mnt/share/cygpkgs/ocaml/ocaml-4.14.1-1.x86_64/src/ocaml-4.14.1=/usr/src/debug/ocaml-4.14.1-1!' \
-    -e 's!%%OCAMLOPT_CPPFLAGS%%!-D_FILE_OFFSET_BITS=64 -U_WIN32 !' \
+    -e 's!%%OCAMLC_CFLAGS%%!-O2 -fno-strict-aliasing -fwrapv -pthread !' \
+    -e 's!%%OCAMLC_CPPFLAGS%%!-D_FILE_OFFSET_BITS=64 -U_WIN32!' \
+    -e 's!%%OCAMLOPT_CFLAGS%%!-O2 -fno-strict-aliasing -fwrapv -pthread !' \
+    -e 's!%%OCAMLOPT_CPPFLAGS%%!-D_FILE_OFFSET_BITS=64 -U_WIN32!' \
     -e 's!%%PACKLD%%!ld -r -o !' \
     -e 's!%%PROFINFO_WIDTH%%!0!' \
     -e 's!%%RPATH%%!!' \
```
Inspection of the traces also suggests in every place where the current build system calls `gcc (CFLAGS) file`, the new patch also calls `gcc (CFLAGS) file` with the same options. Therefore it looks like the compiler files themselves are still compiled with CFLAGS passed as before.

**Comment by shindere** [comment]
@purplearmadillo77 I just submitted an updated version of #12589 which hopefully does the right thing.

See [this comment](https://github.com/ocaml/ocaml/pull/12589#issuecomment-2186748464) for the relevant explanations.

Would you be willing to give it a try?

**Comment by purplearmadillo77** [comment]
Thank you! Will give it a try - response in #12589.
