### ISSUE TITLE
Test failure when glibc has frame pointers

### ISSUE THREAD

**Issue by jamesjer** [ocaml/ocaml#12587]
I attempted a test build of OCaml 5.1.0 for the Fedora Linux distribution, but all of the frame-pointers tests failed.  The first failure looks like this:
```
Running tests from 'tests/frame-pointers' ...
 ... testing 'c_call.ml' with 1 (frame_pointers) => passed
 ... testing 'c_call.ml' with 1.1 (native) sh: line 1: : command not found
=> failed (program output /builddir/build/BUILD/ocaml-5.1.0/testsuite/_ocamltest/tests/frame-pointers/c_call/ocamlopt.byte/c_call.opt.output differs from reference /builddir/build/BUILD/ocaml-5.1.0/testsuite/tests/frame-pointers/c_call.reference: 
)
> Specified modules: c_call.ml
> Source modules: c_call.ml
> Running test frame_pointers with 1 actions
> 
> Running action 1/1 (frame_pointers)
> Action 1/1 (frame_pointers) => passed (frame-pointers available)
> Running test native with 8 actions
> 
> Running action 1/8 (setup-ocamlopt.byte-build-env)
> Action 1/8 (setup-ocamlopt.byte-build-env) => passed
> 
> Running action 2/8 (ocamlopt.byte)
> Compiling program /builddir/build/BUILD/ocaml-5.1.0/testsuite/_ocamltest/tests/frame-pointers/c_call/ocamlopt.byte/c_call.opt from modules  fp_backtrace.c c_call_.c c_call.ml
> Commandline: /builddir/build/BUILD/ocaml-5.1.0/runtime/ocamlrun /builddir/build/BUILD/ocaml-5.1.0/ocamlopt -I /builddir/build/BUILD/ocaml-5.1.0/runtime -ccopt -I/builddir/build/BUILD/ocaml-5.1.0/runtime -nostdlib -I /builddir/build/BUILD/ocaml-5.1.0/stdlib -o /builddir/build/BUILD/ocaml-5.1.0/testsuite/_ocamltest/tests/frame-pointers/c_call/ocamlopt.byte/c_call.opt fp_backtrace.c c_call_.c c_call.ml
>   Redirecting stdout to /builddir/build/BUILD/ocaml-5.1.0/testsuite/_ocamltest/tests/frame-pointers/c_call/ocamlopt.byte/ocamlopt.byte.output 
>   Redirecting stderr to /builddir/build/BUILD/ocaml-5.1.0/testsuite/_ocamltest/tests/frame-pointers/c_call/ocamlopt.byte/ocamlopt.byte.output 
> Action 2/8 (ocamlopt.byte) => passed
> 
> Running action 3/8 (check-ocamlopt.byte-output)
> Comparing compiler output /builddir/build/BUILD/ocaml-5.1.0/testsuite/_ocamltest/tests/frame-pointers/c_call/ocamlopt.byte/ocamlopt.byte.output to reference /builddir/build/BUILD/ocaml-5.1.0/testsuite/tests/frame-pointers/c_call.compilers.reference
> Action 3/8 (check-ocamlopt.byte-output) => passed
> 
> Running action 4/8 (run)
> Entering run_hook for hook /builddir/build/BUILD/ocaml-5.1.0/testsuite/tests/frame-pointers/c_call.run
> Hook should write its response to /tmp/ocamltest-1d976d.response
> Action 4/8 (run) => passed
> 
> Running action 5/8 (check-program-output)
> Comparing program output /builddir/build/BUILD/ocaml-5.1.0/testsuite/_ocamltest/tests/frame-pointers/c_call/ocamlopt.byte/c_call.opt.output to reference /builddir/build/BUILD/ocaml-5.1.0/testsuite/tests/frame-pointers/c_call.reference
> Action 5/8 (check-program-output) => failed (program output /builddir/build/BUILD/ocaml-5.1.0/testsuite/_ocamltest/tests/frame-pointers/c_call/ocamlopt.byte/c_call.opt.output differs from reference /builddir/build/BUILD/ocaml-5.1.0/testsuite/tests/frame-pointers/c_call.reference: 
> 
> )
```

That `sh: line 1: : command not found` text had me scrambling all over the makefiles, looking for some command being invoked that is not present in the buildroot.  That turned out to be a red herring.  The real problem is that the expected and actual outputs differ, and the `filecompare.ml` code reported the difference.  When that happens the difference is reported as failure to find a command, which is misleading.  But that's not what this issue is about.

Fedora builds all amd64 packages with frame pointers.  The output of the `c_call` test looks like this:
```
fp_backtrace_many_args
caml_c_call_stack_args
camlC_call.f
camlC_call.entry
caml_program
caml_start_program
caml_main/caml_startup
main
_start
caml_c_call
camlC_call.f
camlC_call.entry
caml_program
caml_start_program
caml_main/caml_startup
main
_start
camlC_call.f
camlC_call.entry
caml_program
caml_start_program
caml_main/caml_startup
main
_start
```

This differs from the expected output because each stack trace has `_start` after `main`, due to glibc having been built with frame pointers.  The frame-pointers tests should not fail because of the presence of `_start`.

**Comment by xavierleroy** [comment]
Related to #12437 .  In both cases I think the solution is to cut the backtrace at `caml_start_program`, so that it contains no C code.

**Comment by xavierleroy** [comment]
@shindere : do you understand the `line 1: : command not found` error in this example?  Could this be a configuration problem?

**Comment by fabbing** [comment]
Oh, that's an interesting one!
Stack walking with frame-pointers was more affected by the lack of a `NULL` saved-rbp (which I expected) in `main` than by an extra one into `_start`!

The changes proposed in PR #11594 should fix this problem: as we also encounter issues with the C compiler's inlining decisions, and stopping the stack unwinding at `caml_program` prevents mismatches in the tests reference. It should also work in this case too.
Could you please give it a try? You don't need to recompile the compiler, just overwrite the files in `testsuite/tests/frame-pointers` with the ones from #11594, `cd` into the `testsuite` directory and run `make one DIR=tests/frame-pointers/`.

Also, if it's not confidential, I'm curious about your use case for frame-pointers with OCaml programs!

**Comment by shindere** [comment]
Many thanks for the detailed report.

Jerry James (2023/09/19 12:41 -0700):
> That `sh: line 1: : command not found` text had me scrambling all over
> the makefiles, looking for some command being invoked that is not
> present in the buildroot.  That turned out to be a red herring.

It's the `testsuite/tests/frame-pointers/c_call.run` script which
invokes `/bin/sh`. Is it perhaps the case that this file is not provided
in your build root? Do we need to revrite such scripts somehow?

I thought `#!/bin/sh` is Posix?

**Comment by shindere** [comment]
Xavier Leroy (2023/09/20 00:37 -0700):
> @shindere : do you understand the `line 1: : command not found` error
> in this example?  Could this be a configuration problem?

Yes, as said earlier I understand it as meaning that `/bin/sh` is not
provided by the build environment, which might be the case since it
seems to be a sandbox.

I am unsure about how to fix this, though.

Would it be a solution to have the convention that the hooks do not
specify which shell to use to run them and that the responsibility of
calling the right shell would be left to ocamltest?

**Comment by shindere** [comment]
Yeah #11594 looks like a pretty cool solution, removing all the hooks
machinery.

Even if it works, it'd stillb be useful to understand the issue with
`/bin/sh` not being found, as we have other hooks in the testsuite
relying on `/bin/sh` being there.

**Comment by gasche** [comment]
I propose #12588 which presumably (also) solves the present issue -- although I haven't checked that this specific issue is gone -- by stopping the backtrace at `caml_startup | caml_main`.

**Comment by jamesjer** [comment]
I can confirm that https://github.com/ocaml/ocaml/pull/11594 solves the issue.  I have not tried https://github.com/ocaml/ocaml/pull/12588, but can do so if that is the preferred solution.

The use case for frame pointers in general is described [here](https://fedoraproject.org/wiki/Changes/fno-omit-frame-pointer); i.e., to permit full system profiling and improve the debugging experience.  I decided to build OCaml with frame pointers so that the OCaml ecosystem can participate in that effort.  If frame pointers prove too expensive, we can easily turn them back off.

Our buildroots do have /bin/sh in them.  The third colon in `sh: line 1: : command not found` should be preceded by the name of the command that was not found.  It is the empty string.  The shell was invoked with an empty command name.

I can reproduce this by editing `testsuite/tests/frame-pointers/c_call.reference` to remove one line, then running `OCAMLTESTDIR=$PWD/_ocamltest ../ocamltest/ocamltest.opt -timeout 600 tests/frame-pointers/c_call.ml`.  When I run that under strace, I see the following passed to execve:

`sh -c -- '' /builddir/build/BUILD/ocaml-5.1.0/testsuite/tests/frame-pointers/c_call.reference /builddir/build/BUILD/ocaml-5.1.0/testsuite/_ocamltest/tests/frame-pointers/c_call/ocamlopt.byte/c_call.opt.output >/tmp/ocamltestf54c36diff`

**Comment by damiendoligez** [comment]
It looks like `ocamltest` is trying to run the `diff` command but its configuration says the name of the command is the empty string. Can you tell us the definition of the variable `diff` in `ocamltest/ocamltest_config.ml`?

**Comment by damiendoligez** [comment]
It's possible to get an empty `diff` by running `configure` with `--disable-ocamltest` and then compiling `ocamltest` manually.

**Comment by shindere** [comment]
Damien Doligez (2023/10/12 05:33 -0700):
> It's possible to get an empty `diff` by running `configure` with
> `--disable-ocamltest` and then compiling `ocamltest` manually.

Hah, thanks for having investigated, @damiendoligez.

I can see ways of fixing this, but do we want to support such scenarios
in the first place?

**Comment by jamesjer** [comment]
Aha, we weren't passing `--disable-ocamltest` to configure, but we also weren't passing `--enable-ocamltest`.  For years, we've simply been running `make tests` to run the tests.  I guess `--enable-ocamltest` became necessary at some point and we didn't notice.  Chalk this one up to user error.  With `--enable-ocamltest`, the `diff` and `diff_flags` settings are nonempty.

**Comment by shindere** [comment]
The thing that remains unclear to me here is how it was even possible to
run the testsuite if ocamltest was disabled?

Because `testsuite/Makefile` has code to not run the testsuite if
ocamltest does not exist, and I am guessing that you didn't build it
manually eitherso how did we end up in this situation?

**Comment by shindere** [comment]
In any case, #12706 has a commit that hardens the build system by making it completely impossible to build ocamltest, even manually, if it has been disabled at configure time. This is achieved by including its buid rules only if it has been enabled. If #12706 gets merged I think we can consider it will fix the present issue.
