### ISSUE TITLE
Segmentation fault with recursive lazy values

### ISSUE THREAD

**Issue by lthls** [ocaml/ocaml#12585]
The following program currently segfaults:
```ocaml
let rec x =
  let y () = (Lazy.force x) () in
  let z = if Sys.opaque_identity true then y else fun () -> () in
  lazy z
let () = (Lazy.force x) ()
```
The core issue: expressions of the form `lazy expr` are considered as Static by `Rec_check`, but the optimisations around lazy expressions mean that it could be translated to `expr`, which has no particular reason to be allowed as a recursive binding. The actual let-rec compilers then get an expression that doesn't have an obvious size, so assumes it must be non-recursive, and generates wrong code.

Among the solutions I can think of:
- Replicate the logic in `translcore.ml` for lazy expressions in `rec_check.ml`, rejecting definitions that would be compiled incorrectly (annoying, but doable)
- Prevent optimisations of lazy expressions occurring as the definition of a recursive binding (obviously correct, but involves patching `translcore.ml` in invasive ways)

My work on recursive bindings does not offer a solution to this problem; in fact, it only made it obvious that this case was not handled properly and needs a dedicated fix.

I'm not mentioning the more obviously correct solution of forbidden lazy recursive bindings as it is actually used in `camlinternalMod.ml`.

**Comment by yallop** [comment]
> Replicate the logic in `translcore.ml` for lazy expressions in `rec_check.ml`, rejecting definitions that would be compiled incorrectly (annoying, but doable)

I think this would be okay.  We already use `Typeopt.classify_lazy_argument` in the mode computation, so it's not too bad to use it a second time in the static/dynamic classification.
