### ISSUE TITLE
Lack of optimization in floating point operations

### ISSUE THREAD

**Issue by arthur0963** [ocaml/ocaml#12600]
Currently, when you perform a floating point multiplication, it does not optimize and ends up performing an unnecessary multiplication, here it follows an example:
```ocaml
let mul x = x *. 2.0;;

let () =
    let n = mul 5.0 in
    print_float n;
```
When we compile into Assembly, we get:
```s
.L103:
        leaq    8(%r15), %rbx
        movq    $1277, -8(%rbx)
        movsd   .L104(%rip), %xmm0
        mulsd   (%rax), %xmm0
        movsd   %xmm0, (%rbx)
        movq    %rbx, %rax
        addq    $8, %rsp
        ret
```
The problem centers on not optimizing the call of a multiplication operation when we treat it as floating point. Here it follows an example with integers:
```ocaml
let mul x = x * 2;;

let () =
    let n = mul 5 in
    print_int n;
```
In which the Assembly returns:
```s
.L103:
        subq    $8, %rsp
        movl    $21, %eax
        call    camlStdlib__print_int_1165@PLT
.L104:
        movl    $1, %eax
        addq    $8, %rsp
        ret
.L102:
        push    $34
        call    caml_call_realloc_stack@PLT
        popq    %r10
        jmp     .L103
```

**Comment by gasche** [comment]
My understanding is that the compiler in fact behaves as expected here. Constant folding does happen (on several OCaml versions I could test, without flambda), and the compiler uses the constant `10.` for `n`. The `mulsd` operation is present in the generated assembly for the `mul` function, which is generated but not actually called in the rest of the program.

To see that constant folding happens, see the `-dcmm` output for your program (or look into the details of the assembly code):

```
(data int 3063 "camlTest__4": addr "camlTest__mul_268" int 72057594037927941)
(data int 1792 global "camlTest" "camlTest": int 1)
(data
 global "camlTest__gc_roots"
 "camlTest__gc_roots":
 addr "camlTest"
 int 0)
(function{test.ml:1,8-20} camlTest__mul_268 (x/270: val)
 (alloc{test.ml:1,12-20} 1277 (*f (load float64 x/270) 2.)))

(data int 2045 "camlTest__3": double 10.)
(data int 2045 "camlTest__2": double 5.)
(data int 2045 global "camlTest__1" "camlTest__1": double 2.)
(function camlTest__entry ()
 (let mul/268 "camlTest__4"
   (extcall "caml_initialize" "camlTest" mul/268 ->unit))
 (let
   *match*/274
     (app{stdlib.ml:488,20-60} "camlStdlib__output_string_248"
       (load_mut val (+a "camlStdlib" 304))
       (app{stdlib.ml:488,41-60} "camlStdlib__string_of_float_189"
         "camlTest__3" val)
       val)
   [])
 1)
```

In this `dcmm` output we see that `string_of_float` is called with `camlTest__3`, a compile-time constant defined as `10.` above.

**Comment by xavierleroy** [comment]
> The compiler uses the constant 10. for n. The mulsd operation is present in the generated assembly for the mul function, which is generated but not actually called in the rest of the program.

Correct.  Similar code is generated in the integer variant of this example.  The generic `mul` function cannot be eliminated, since it can be referenced from other modules, but constant propagation takes place and the multiplication is computed at compile-time.
