### ISSUE TITLE
grammar corner case?

### ISSUE THREAD

**Issue by c-cube** [ocaml/ocaml#12648]
This `let open struct…` works:

```ocaml
let f () =
  let open struct
    type t = int
  end in
  (42 : t)
```

but this one doesn't (with 5.1.0):

```ocaml
class f =
  let open struct
    type t = int
  end in
  object
    method x = (42 : t)
  end
```

that seems like an oversight in the grammar? Why is `let open` weaker in a class, given that `let open M in …` works fine?

**Comment by gasche** [comment]
`let module M = ... in ...` is not supported in class expressions, so it sort of makes sense that existing module paths can be opened but not new module expressions. I am not sure that the limitation is just an oversight, the type-checking and compilation of let-bindings in class expressions is separate from those in normal expressions.

But I would guess that it is possible to add support for this, and also `let module ... in` in class expressions -- but not necessarily easy, this probably requires duplicating non-trivial code to handle the expression-side constructs. (This not just a matter of adding a case or two to the parser.)

**Comment by yallop** [comment]
> But I would guess that it is possible to add support for this, and also let module ... in in class expressions -- but not necessarily easy, 

@garrigue said something similar the last time this was discussed: https://github.com/ocaml/ocaml/issues/6271#issuecomment-473023872

**Comment by c-cube** [comment]
Oh I didn't realize there were actual typechecking hurdles, apologies! That's somewhat surprising but very interesting :)

**Comment by Octachron** [comment]
I am closing the issue since it is not really a grammar corner case but more a `feature wish`: `local module in classes`.
