### ISSUE TITLE
Support native compilation on big-endian ppc64

### ISSUE THREAD

**Issue by sideeffect42** [ocaml/ocaml#12656]
When I try to compile the OCaml compiler from Git trunk on my POWER9 system the configuration step fails:

```console
$ ./configure --enable-native-compiler
...
configure: error: the native compiler is not supported on this platform
```

Checking the configure script suggests that only `powerpc64le*-*-linux*` is whitelisted with `has_native_backend=yes`.

Since the README says that native compilation on the Power architecture will be supported again in OCaml 5.2, please also add `powerpc64-*-linux-*` to the list of supported native backends.

**Comment by xavierleroy** [comment]
5.2 supports POWER in little-endian mode only (`powerpc64le`).  Most Linux distributions no longer support POWER64 big-endian (`powerpc64`), and the corresponding ABI is difficult to support in a compiler, so OCaml 5 will not support `powerpc64` ever.

This said, it could also be a wrong autodetection of the system's configuration.  What Linux distro are you running on this POWER9 machine?  What does `uname -a` report?

**Comment by sideeffect42** [comment]
Autodetection is correct. I'm running a big endian Gentoo installation on my workstation.

`uname -a` is:
`Linux blackbird 6.5.7-gentoo-ppc64 #1 SMP PREEMPT Wed Oct 11 18:03:56 CEST 2023 ppc64 POWER9, altivec supported PowerNV C1P9S01 REV 1.02 GNU/Linux`

@xavierleroy I don't know what you mean with "the corresponding ABI is difficult to support in a compiler".
AFAIK there are two ppc64 ABIs commonly called ELFv1 (big-endian only) and ELFv2 (endian agnostic).

**Comment by xavierleroy** [comment]
> I don't know what you mean with "the corresponding ABI is difficult to support in a compiler".
> AFAIK there are two ppc64 ABIs commonly called ELFv1 (big-endian only) and ELFv2 (endian agnostic).

I mean that the ELFv1 ABI is a real pain and will not be supported in OCaml >= 5.

> I'm running a big endian Gentoo installation on my workstation.

You're on your own.

**Comment by sideeffect42** [comment]
@xavierleroy even if ELFv1 is such a pain to support this does not explain why ppc64 could not be supported when the ELFv2 ABI is used.

AFAIK glibc does not provide an ELFv2 triplet for ppc64 (currently), but musl libc uses ELFv2 on both little and big endian.
There are multiple distributions supporting ppc64 on musl and thus using ELFv2, like Adélie Linux, Chimera Linux, Gentoo using a musl profile, or VoidPPC.

All of these could still benefit from ppc64 support even if only ELFv2, until glibc also gets updated to ELFv2.

**Comment by pkubaj** [comment]
@xavierleroy 
There are Linux distros supporting ppc64 (BE) on ELFv2, e.g. Chimera Linux. Also, ppc64 is supported on FreeBSD and OpenBSD, where it's also exclusively ELFv2.

**Comment by awilfox** [comment]
This would definitely affect Adélie's ability to package OCaml since big-endian ppc64 is a Tier 1 architecture for us, and yes, we are exclusively ELFv2 ABI.  How can we move forward with adding that support, since the ABI is not an issue?

**Comment by xavierleroy** [comment]
Just to summarize:
- Native-code generation for big-endian PPC64 ABIv2 is being added in #12667, and it is very simple indeed.  Autodetection may need more work in the future, but nothing serious.
- Native-code generation for PPC64 ABIv1 (such as the Gentoo distribution of the original poster) will not be supported in OCaml >= 5 ever.  It remains supported in 4.14, which is an LTS release.
- Even when native-code generation is not available for a given platform, OCaml can still be used (with reduced performance) via the bytecode compiler, which is highly portable.  For example, OCaml 5 removes native-code generation for all 32-bit platforms, but runs fine in bytecode on these platforms.
