### ISSUE TITLE
More docs on cross compilation support of ocaml

### ISSUE THREAD

**Issue by ChenQi1989** [ocaml/ocaml#12663]
I've searched the official website of OCaml, and I've used google to search other sites. But I cannot find anything about the cross compilation support of OCaml.

I'm new to OCaml. Does it support cross compilation? Where to find related resources?

**Comment by Octachron** [comment]
Open-ended discussions on how to use `ocaml` and cross-compilation support will be more at home at https://discuss.ocaml.org . I am closing this issue, please feel free to open a discussion at https://discuss.ocaml.org  .

**Comment by ChenQi1989** [comment]
@Octachron Thanks for your prompt response.
I did search the https://discuss.ocaml.org/ before I created this issue. Unfortunately, I didn't find what I want, i.e., how to build from source an ocaml cross compiler and how to use it. 
If you have something bump into your head, please let me know.
I created this issue because I'm wondering if OCaml plans to add more doc regarding cross compilation. I guess other people might also be interested.
Anyway, I'll search more next week and will probably create new threads on https://discuss.ocaml.org.

**Comment by gasche** [comment]
There is no clean, upstream support for cross-compilation in the upstream compiler build system. This is something we would like to see done, but has not been done yet -- see #4303 for older discussions about this. Various people have worked around this limitation by hacking various approaches to their own specific cross-compilation need, see for example the Discuss thread https://discuss.ocaml.org/t/cross-compiling-implementations-how-they-work/8686 .
