### ISSUE TITLE
Break breaks Semaphore 

### ISSUE THREAD

**Issue by polytypic** [ocaml/ocaml#12675]
Consider the following interaction with the OCaml toplevel:

```
OCaml version 5.1.0
# #thread;;
# let s = Semaphore.Binary.make false ;;
val s : Semaphore.Binary.t = <abstr>
# Semaphore.Binary.acquire s ;;
Interrupted.
# Semaphore.Binary.release s ;;
Exception: Sys_error "Mutex.lock: Resource deadlock avoided".
```

What happened above is that I pressed Ctrl-C to interrupt the `Semaphore.Binary.acquire s` call.  This leaves the semaphore in a broken state.  Consider the implementation of `acquire`: https://github.com/ocaml/ocaml/blob/e397ed28bcef85fdc1f0f007af481ef201fb1fd7/stdlib/semaphore.ml#L43-L47

What happened is that the Ctrl-C caused the call of `Condition.wait` call made by `acquire` to raise the asynchronous `Sys.Break` exception.  Even in that case `Condition.wait` returns with the mutex locked.  So, as the exception is propagated, the mutex is left locked.  The semaphore is now essentially broken and cannot be used anymore.

In general, the programming pattern that [the current documentation of the `Condition` module](https://v2.ocaml.org/api/Condition.html) puts forth

```ocaml
     Mutex.lock m;
     while not P do
       Condition.wait c m
     done;
     <update the data structure>;
     Mutex.unlock m
```

is unsafe with respect to asynchronous exceptions.

Asynchronous exceptions are a thorny topic in OCaml.  However, I would still consider this to be a bug and would suggest that the uses of `Condition.wait` in the Stdlib and in the documentation would be changed to use a pattern where the associated mutex is unlocked even in the case that `Condition.wait` raises an exception.  Basically something like this:

```ocaml
     Mutex.lock m;
     match
       while not P do
         Condition.wait c m
       done
     | () ->
       <update the data structure>;
       Mutex.unlock m
     | exception exn ->
       (* maybe capture backtrace here *)
       Mutex.unlock m;
       raise exn
```

**Comment by gasche** [comment]
The standard library now offers `Mutex.protect`, which should handle asynchronous exceptions correctly.

```ocaml
let acquire s = 
  Mutex.protect s.mut (fun () ->
    while s.v = 0 do Condition.wait s.nonzero s.mut done; 
    s.v <- s.v - 1
  )
```

**Comment by polytypic** [comment]
> The standard library now offers `Mutex.protect`, which should handle asynchronous exceptions correctly.

Yes, that is nice, although it imposes allocations, which can be a performance issue.

Just to be clear, all the three uses of `Condition.wait` under the `stdlib` directory (two in `semaphore.ml` and one in `domain.ml`) currently have the problem that the uses are not safe against asynchronous exceptions.  I would also strongly recommend mentioning this problem in the documentation of `Condition`.

Sorry for the distraction, but while we are on this topic, [the documentation of `Fun.protect`](https://v2.ocaml.org/api/Fun.html) seems misleading to me.   It says:

> However, it does not protect against unexpected exceptions raised inside finally () such as [Out_of_memory](https://v2.ocaml.org/api/Stdlib.html#EXCEPTIONOut_of_memory), [Stack_overflow](https://v2.ocaml.org/api/Stdlib.html#EXCEPTIONStack_overflow), or asynchronous exceptions raised by signal handlers (e.g. [Sys.Break](https://v2.ocaml.org/api/Sys.html#EXCEPTIONBreak)).

To me that gives the impression that the implementation of `finally` or of `Fun.protect` is somehow responsible for not offering protection against asynchronous exceptions.  AFAIU, the fundamental problem is that calling `Fun.protect` potentially includes a safe point for the allocation of the two closures and it might be that an asynchronous exception is raised at that safe point.  The correct way, AFAICT, to perform resource acquire and release is to make sure that no safe point exists between acquire and setup of release.

The natural follow up question to that would be: Why doesn't the Stdlib include a helper to perform safe resource acquire and release?  Something roughly like

```ocaml
let[@inline never] ( let@ ) (release, acquire) body =
  let x = acquire () in
  match body x with
  | y ->
      release x;
      y
  | exception exn ->
      (* you'll probably want a bit more complexity here *)
      release x;
      raise exn
```

which could then be used e.g. to implement the condition wait pattern safely

```ocaml
let@ m = Mutex.unlock, fun () -> Mutex.lock m; m in
while not P do
  Condition.wait c m
done
```

But yes, this is a separate issue.

**Comment by gasche** [comment]
> Yes, that is nice, although it imposes allocations, which can be a performance issue.

I would assume that mutex/condition operations are slower than allocations, but you have better intuition than I do here.

For your further questions on asyc-safety, I am afraid that this is a discussion to be had with gadmm.

**Comment by lthls** [comment]
> The natural follow up question to that would be: Why doesn't the Stdlib include a helper to perform safe resource acquire and release? Something roughly like
> 
> ```ocaml
> let[@inline never] ( let@ ) (release, acquire) body =
>   let x = acquire () in
>   match body x with
>   | y ->
>       release x;
>       y
>   | exception exn ->
>       (* you'll probably want a bit more complexity here *)
>       release x;
>       raise exn
> ```

The answer is probably the one from your own post:

> Yes, that is nice, although it imposes allocations, which can be a performance issue.

> Sorry for the distraction, but while we are on this topic, [the documentation of `Fun.protect`](https://v2.ocaml.org/api/Fun.html) seems misleading to me. It says:
> 
> > However, it does not protect against unexpected exceptions raised inside finally () such as [Out_of_memory](https://v2.ocaml.org/api/Stdlib.html#EXCEPTIONOut_of_memory), [Stack_overflow](https://v2.ocaml.org/api/Stdlib.html#EXCEPTIONStack_overflow), or asynchronous exceptions raised by signal handlers (e.g. [Sys.Break](https://v2.ocaml.org/api/Sys.html#EXCEPTIONBreak)).
> 
> To me that gives the impression that the implementation of `finally` or of `Fun.protect` is somehow responsible for not offering protection against asynchronous exceptions. AFAIU, the fundamental problem is that calling `Fun.protect` potentially includes a safe point for the allocation of the two closures and it might be that an asynchronous exception is raised at that safe point.

I don't remember why the documentation ended up this way, but I don't think it refers to the closure allocations (although that could also be an issue).
I can see two other issues it might be referring to:
- The fact that some allocations occur if `finally` raises, so you can get an asynchronous exception instead of `Finally_raised`.
- The fact that the `finally` function could raise exceptions (asynchronous or not), failing to actually do its intended work. Asynchronous exceptions are particularly worrying because there is currently no formal specification of what language constructions can include poll points, so no way to be sure that a piece of code is poll-free without checking the generated code (or using the `[@poll error]` attribute, which checks the generated code for you).

I suspect that the comment refers to the second one, but I agree that it is confusing.
