### ISSUE TITLE
partially installed compiler

### ISSUE THREAD

**Issue by Azatic** [ocaml/ocaml#12695]
when I write opam switch create 5.1.0 (for example) and finish the process before completion, I still get 5.1.0 in the available versions of the compiler, although there are many errors when using it
I would like it to be visible when writing opam switch, which compiler is partially installed

**Comment by Octachron** [comment]
This an opam issue (for which the solution is to answer no when opam is asking you to keep the partially installed switch) and not related to the compiler.
