### ISSUE TITLE
NULL dereference in the "header" stub of bytecode executables for Windows

### ISSUE THREAD

**Issue by vadim-z** [ocaml/ocaml#12722]
Hello,

Bytecode executable files made under Windows fail with segmentation violation when the runtime (ocamlrun) cannot be found in a path.

They write "Cannot exec" and raise segmentation error instead of writing the runtime name.

The reason is the following:

The "header" stub of executable (file "camlheader") tries to find a runtime file (typically "ocamlrun.exe") using the function SearchPath in the lines
https://github.com/ocaml/ocaml/blob/bdd8d960345a293f6643f279ab535b5637b4a34e/stdlib/headernt.c#L125-L126

Runtime string is passed as the second argument and also as the last argument by pointer. MSDN [marks](https://learn.microsoft.com/en-us/windows/win32/api/processenv/nf-processenv-searchpathw) the last argument as "output". It does not specify what happens if the file is not found in a path. But I noticed that at least for my W10 installation the function SearchPath nullifies the last argument in this case.

So, when runtime file cannot be found in the path, the "runtime" pointer is wiped with NULL. Attempt to print it in line https://github.com/ocaml/ocaml/blob/bdd8d960345a293f6643f279ab535b5637b4a34e/stdlib/headernt.c#L130 leads to NULL pointer dereference. I have observed this behavior with gdb.

With best regards,
Vadim

**Comment by nojb** [comment]
Hello, thank you for the report, and the good detective work! I am able to reproduce the issue. Your analysis sounds quite probably correct. Would you like to attempt a fix?

**Comment by vadim-z** [comment]
AFAIU, after call to SearchPath the "runtime" variable is used  for diagnostics only.

Therefore it is safe to replace the last argument with &dummy, where dummy is a pointer to wchar_t. Or, as this argument is optional according to MSDN, you can even put NULL here.

Unfortunately, I can neither provide a patch nor test it due to my workspace restrictions. But the fix appears trivial.

**Comment by nojb** [comment]
> Unfortunately, I can neither provide a patch nor test it due to my workspace restrictions. But the fix appears trivial.

No worries, I'll submit a patch shortly.
