### ISSUE TITLE
ocamlyacc should produce an error when a token has multiple definitions

### ISSUE THREAD

**Issue by redianthus** [ocaml/ocaml#12723]
I noticed it was not producing an error in the [Wasm reference interpreter](https://github.com/WebAssembly/gc/pull/474).

Menhir is producing an error in this case: `Error: the token REF_I31 has multiple definitions.`.

**Comment by nojb** [comment]
Hello, as a general rule, `ocamlyacc` is considered legacy and new developments should instead use Menhir, which has many advantages over `ocamlyacc`, the most important one being that it is actively maintained.
