### ISSUE TITLE
OCaml 5.1.1 cross-compilation fails (symbols in wrong format)

### ISSUE THREAD

**Issue by anmonteiro** [ocaml/ocaml#12798]
I'm trying to build an aarch64 cross-compiler with the tip of the [5.1 branch](https://github.com/ocaml/ocaml/tree/5.1) and I'm seeing a failure related to `zstd.npic.o`. 

This failure isn't present on OCaml 5.1

Relevant logs below:

```
  LINKOPT ocamlc.opt
/nix/store/p58l5qmzifl20qmjs3xfpl01f0mqlza2-binutils-2.40/bin/ld: compilerlibs/ocamlcommon.a(zstd.npic.o): Relocations in generic ELF (EM: 183)
/nix/store/p58l5qmzifl20qmjs3xfpl01f0mqlza2-binutils-2.40/bin/ld: compilerlibs/ocamlcommon.a(zstd.npic.o): Relocations in generic ELF (EM: 183)
/nix/store/p58l5qmzifl20qmjs3xfpl01f0mqlza2-binutils-2.40/bin/ld: compilerlibs/ocamlcommon.a(zstd.npic.o): Relocations in generic ELF (EM: 183)
/nix/store/p58l5qmzifl20qmjs3xfpl01f0mqlza2-binutils-2.40/bin/ld: compilerlibs/ocamlcommon.a(zstd.npic.o): Relocations in generic ELF (EM: 183)
/nix/store/p58l5qmzifl20qmjs3xfpl01f0mqlza2-binutils-2.40/bin/ld: compilerlibs/ocamlcommon.a(zstd.npic.o): Relocations in generic ELF (EM: 183)
/nix/store/p58l5qmzifl20qmjs3xfpl01f0mqlza2-binutils-2.40/bin/ld: compilerlibs/ocamlcommon.a(zstd.npic.o): Relocations in generic ELF (EM: 183)
/nix/store/p58l5qmzifl20qmjs3xfpl01f0mqlza2-binutils-2.40/bin/ld: compilerlibs/ocamlcommon.a: error adding symbols: file in wrong format
collect2: error: ld returned 1 exit status
```

[full build logs](https://github.com/nix-ocaml/nix-overlays/actions/runs/7040132453/job/19160584054?pr=1169)

**Comment by anmonteiro** [comment]
One clarification: this build doesn't include zstd.

**Comment by Octachron** [comment]
Did you update your patch to take in account the new call to ar when building `ocamlcommon.a`?

**Comment by xavierleroy** [comment]
I don't know what your cross-compilation build system looks like, and I don't want to look at it.  At any rate:
- if you're building ocamlc.opt and ocamlopt.opt as cross compilers (run on the host, produce code for the target), you need to build `runtime/zstd.npic.o` for the host system
- otherwise, if ocamlc.opt and ocamlopt.opt are intended to run on the target, build `runtime/zstd.npic.o` for the target.

Even if you configure without ZSTD support, `runtime/zstd.c` needs to be build (it contains a trivial function saying "ZSTD is not available") and attached to compilerlibs/ocamlcommon.cmxa.

**Comment by xavierleroy** [comment]
Also: in the Makefile line that adds zstd.npic.o to ocamlcommon.a, make sure to use the appropriate "ar" (i.e. the host "ar" if this is code for the host, and the target "ar" otherwise).

**Comment by anmonteiro** [comment]
Thanks for the pointers.

It will work, indeed, if `zstd.npic.o` is compiled by the host compiler rather than the target cc.

There isn't, however, a way that I've found (yet?) to compile _everything else_ with e.g. `aarch64-unknown-linux-gnu-gcc` and `zstd.npic.o` with `gcc`. I might have to separate that out in the Makefile in a patch.

**Comment by anmonteiro** [comment]
Thinking more about this. If `runtime/zstd.npic.o` should be compiled with the host C compiler, perhaps the Makefile should model that by using `$(SAK_CC)` instead, which already accounts for cross-compilation:

https://github.com/ocaml/ocaml/blob/d5b5c34971ed4291c385852f820554ad57adba84/Makefile#L1272-L1274


The patch would effectively be:

```diff
+ runtime/zstd.npic.$(O): CC=$(SAK_CC)
```


EDIT: I suppose that doesn't work in isolation if the runtime then also needs to be linked with target programs.

**Comment by xavierleroy** [comment]
For the record: the handling of the `zstd.c` runtime module will probably change in 5.2, see #12758 for the current proposal.  Here, a `libcomprmarsh.a` library is built at the same time as `libasmrun.a`, then used to build `ocamlc.opt` and the like.  So, for cross-compilation, whatever work you did to build both host and target versions of `libasmrun.a` should apply to `libcomprmarsh.a` as well.

**Comment by anmonteiro** [comment]
Thank you for the pointer, I’ll take a look at the linked PR.
