### ISSUE TITLE
SIGSEGV with to caml_unix_alloc_sockaddr

### ISSUE THREAD

**Issue by talex5** [ocaml/ocaml#12796]
This program segfaults on OCaml 5.1.0:
```ocaml
let () =
  let a, b = Unix.(socketpair PF_UNIX SOCK_DGRAM 0) in
  let buf = Bytes.create 1 in
  while true do
    let sent = Unix.send_substring a "!" 0 1 [] in
    assert (sent = 1);
    let got, addr = Unix.recvfrom b buf 0 1 [] in
    assert (got = 1);
  done
```
```
$ ocamlopt -I +unix unix.cmxa test.ml && ./a.out
fish: Job 1, './a.out' terminated by signal SIGSEGV (Address boundary error)
```
(this was originally seen as an occasional hang in Eio's tests)

I believe this is due to this code in `caml_unix_alloc_sockaddr` failing to restore `caml_state->local_roots` on exit:

https://github.com/ocaml/ocaml/blob/c2476e3db91949fe1d4355ec69e2860623c860c1/otherlibs/unix/socketaddr.c#L111-L121

**Comment by gasche** [comment]
This looks likely, would you like to submit a fix as a PR? (For example you could use `CAMLreturn` instead.)
