### ISSUE TITLE
The primitive `caml_ml_domain_unique_token` is unused and should be removed.

### ISSUE THREAD

**Issue by kayceesrk** [ocaml/ocaml#12813]
https://github.com/ocaml/ocaml/blob/3838bbfffcb80dae8d2713be475d57c937c874d9/runtime/domain.c#L1308-L1311

Needs bootstrap, following the steps 3 to 5 mentioned [here](https://github.com/ocaml/ocaml/blob/trunk/BOOTSTRAP.adoc#adding-removing-and-renaming-primitives).

**Comment by shindere** [comment]
Thanks, I have just submitted #12816 to fix this.
