### ISSUE TITLE
OCaml 5.1.x: out of range branch on s390x

### ISSUE THREAD

**Issue by jamesjer** [ocaml/ocaml#12829]
The combination of OCaml 5.1.0 or 5.1.1, coq 8.18.0, and flocq 4.1.3 reliably segfaults for me when trying to build for Fedora Rawhide on s390x.  The segfault happens at the end of camlMicromega_plugin__Coq_micromega.xwitness_list_25687.  There is a brasl instruction that jumps to an invalid address, leading to the segfault.  On an x86_64 machine, the equivalent call instruction jumps to caml_call_realloc_stack.  With GDB, I see that the brasl instruction jumps to 0x208025ca320, but caml_call_realloc_stack is actually at 0x2aa025ca320, a difference of 0xa200000000.  The brasl instruction in question is emitted at asmcomp/s390x/emit.mlp line 754 in the OCaml 5.1.1 release.  My understanding is that the brasl instruction can only handle 32-bit offsets, and this particular jump is more than a 32-bit offset away, so it appears that the upper bits are silently dropped.

For what it's worth, I do not have any trouble building coq 8.18.0 itself.  All of its tests pass.  I also don't see this happen with coq 8.17.1 + flocq 4.1.1.

Note that the Fedora build of OCaml 5.1.1 contains the changes in https://github.com/ocaml/ocaml/pull/11594, since the test suite was failing without it.

**Comment by lthls** [comment]
@jamesjer I believe #12831 will fix this issue, is it possible for you to test the fix before we merge it ?

**Comment by xavierleroy** [comment]
Let's wait for feedback from @jamesjer before closing.  The missing PLT indirection when calling `caml_call_realloc_stack` is definitely an issue for shared libraries, but it's surprising that the linkers (static and dynamic) didn't catch it, and that the dynamic loader produced wrong code (by ignoring the overflow).

**Comment by jamesjer** [comment]
Thank you for the rapid response!  I will queue up some test builds and let you know how it goes.

**Comment by jamesjer** [comment]
I can confirm that flocq 4.1.3 builds successfully on s390x with https://github.com/ocaml/ocaml/pull/12831.  Thank you!

**Comment by rwmjones** [comment]
I'll see if I can rebuild Fedora package(s) early next week.

**Comment by rwmjones** [comment]
Fedora rebuild with this patch is underway now.  I backported the upstream patch to our OCaml downstream repo here.  It didn't directly apply because of whitespace changes but I believe my cherry pick is correct:
https://pagure.io/fedora-ocaml/c/81d3fb3e20afede32298e4d3e78bcebf6a22858a?branch=fedora-40-5.1.1

Built packages here:
https://koji.fedoraproject.org/koji/builds?inherited=0&tagID=79788&order=-build_id&latest=1

**Comment by xavierleroy** [comment]
Thanks for the confirmations!  Time to close this issue.
