### ISSUE TITLE
Documentation on Essential Editor Features for OCaml Beginners

### ISSUE THREAD

**Issue by PizieDust** [ocaml/ocaml#12870]
# Update Documentation on using editors with OCaml

The documentation on setting up editors for OCaml, [Configure your editor](https://ocaml.org/docs/configuring-your-editor), is quite summarized and does not cover some useful features of the editor (VS Code), especially for beginners, whom I assume the article is directed towards.
This proposal is to enhance the documentation on ocaml.org to include detailed information. While these are not specific to OCaml, it will be very helpful for those beginners who are introduced to programming with OCaml as their first language.

The main things to include are listed below:
### Hovering for Type Information:
Description: The ability to hover over variables or functions to view their type information is a fundamental feature that aids in understanding code without having to navigate elsewhere.
Example: Hovering over a variable should display its type information in a tooltip.

### Ctrl + Hovering for Go-to-Definition:
Description: This feature allows users to navigate directly to the definition of a variable or function by holding down the Ctrl key and hovering over the identifier.
Example: Ctrl + Hovering over a function should provide a clickable link or open the file where the function is defined.

### Ctrl + P + [Command]:
Description: The ability to use a shortcut (Ctrl + P on Linux; find corresponding keys for Windows and Mac) followed by a specific command (e.g., OCaml) to find and run commands within the development environment.
Example: Ctrl + P + OCaml should allow users to quickly find and execute OCaml-specific commands.

### Click on Lightbulb for Code Actions:
Description: The lightbulb icon, often displayed next to code snippets, indicates available code actions. Clicking on it should reveal a list of suggestions for improving or modifying the code.
Example: Clicking on the lightbulb should show options like fixing syntax errors, optimizing imports, etc.

### Merlin as a superpower
Description: Merlin is a very useful addon especially for beginner programmers. A little intro about Merlin and how beginners can use it to their advantage will go a long way to simplify their OCaml journey. 
Example: How to use the `Document` command of Merlin to find documentation or `TypeOf` to get the type of a variable in an editor like Vi.

cc @pitag-ha

**Comment by dra27** [comment]
Thanks for this! I think the issue is intended for [ocaml/ocaml.org](https://github.com/ocaml/ocaml.org) though? I don’t have permissions to transfer it - it might be fastest just to open a new issue there and close this one.

**Comment by PizieDust** [comment]
Thank you @dra27. I have moved the issue to the correct repository.
