### ISSUE TITLE
Typo in the documentation: which vs that in A Tour of OCaml

### ISSUE THREAD

**Issue by julbinb** [ocaml/ocaml#12913]
In [A Tour of Ocaml, Records section](https://ocaml.org/docs/tour-of-ocaml#records), there is a sentence

> Here, the pattern `{ age = x; _ }` is typed with the most recently declared record type**, which** has an `age` field of type `int`.

The use of ", which" indicates that the type checker uses the most recently declared record type (period). Thus, if there is no "age" field in the most recent record, it would be an error.

Judging by the behavior of the OCaml compiler, the sentence should say "the most recently declared record type **that** has an `age` field" (no comma).

**Comment by nojb** [comment]
Hello, thank you for your suggestion! However, this repository is for the development of the compiler toolchain itself. For `ocaml.org`-related issues, the right repository is https://github.com/ocaml/ocaml.org.

**Comment by julbinb** [comment]
My bad, thank you! Submitted a new issue to the right place :) https://github.com/ocaml/ocaml.org/issues/1972
