### ISSUE TITLE
Package `with type` constraints do not work on `@@immediate` types

### ISSUE THREAD

**Issue by ccasin** [ocaml/ocaml#12924]
This program does not typecheck, but should:

```ocaml
module type S = sig
  type t [@@immediate]
end

type t = (module S with type t = int)
```

Error:
```
File "/home/ccasinghino/tmp/bar.ml", line 5, characters 9-37:
5 | type t = (module S with type t = int)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Error: In this with constraint, the new definition of t
       does not match its original definition in the constrained signature:
       Type declarations do not match:
         type t
       is not included in
         type t [@@immediate]
       The first is not an immediate type.
       File "/home/ccasinghino/tmp/bar.ml", line 2, characters 2-22:
         Expected declaration
       File "/home/ccasinghino/tmp/bar.ml", line 5, characters 9-37:
         Actual declaration
```

As far as I can tell, it is impossible to use a with type constraint for an immediate type in a package type.  The direct cause is that the "fake" module type constructed by `Typetexp.create_package_mty` doesn't keep the manifests from the with type constraints, though a fix is not so simple as keeping them.

I thought this had been reported before, but I can't find a ticket - apologies if this is a duplicate.

**Comment by gasche** [comment]
You are probably the best person to work on immediacy checking in the compiler right now. Are you volunteering to eventually fix your own issue report?

**Comment by ccasin** [comment]
> You are probably the best person to work on immediacy checking in the compiler right now. Are you volunteering to eventually fix your own issue report?

I think this has more to do with first-class modules than immediacy checking. I think the best way to fix it is to rewrite the `Ptyp_package` case of `Typetexp.transl_type_aux` to explicitly check the package and its with type constraints rather than constructing a fake module type and relying on the existing translation of those.  But yes, I'm likely to take a stab at that eventually if no one beats me to it or has a better idea.

**Comment by Octachron** [comment]
I am closing this issue since the corresponding PR has been merged.
