### ISSUE TITLE
'ocamlc -output-complete-exe' is not compatible with a MSVC toolchain

### ISSUE THREAD

**Issue by F-Loyer** [ocaml/ocaml#12944]
Trying to compile a dummy program with `ocamlc -output-complete-exe program.ml` fails:

```
link: missing operand
Try 'link --help' for more information.
link: extra operand '/libpath:C:/Users/frede/AppData/Local/opam/4.14.1+msvc64c/lib/ocaml'
Try 'link --help' for more information.
** Fatal error: Error during linking
```

Since the `-output-complete-exe` option is required to build `dune`, this makes the `ocaml-variants.4.14.1+msvc64c` compiler more or less useless.

This has been tested with `opam-2.2.0~beta1`.

**Comment by nojb** [comment]
I think your environment is not correctly set up: the `link` command of the MSVC toolchain has the same name as another, unrelated, command from Cygwin. As explained in https://github.com/ocaml/ocaml/blob/trunk/README.win32.adoc, you must make sure that the MSVC tool appear first in your PATH (this can also be done by using `tools/msvs-promote-path` in this repository).

**Comment by F-Loyer** [comment]
Yes, I can close the issue.
