### ISSUE TITLE
5.2.0~alpha1: ocamlc -pack changed the expected naming convention for the cmi files

### ISSUE THREAD

**Issue by kit-ty-kate** [ocaml/ocaml#12984]
The following test case works with OCaml 5.1 but fails with OCaml 5.2:
```
touch test.ml test.mli

ocamlc -c -o test.cmi test.mli
ocamlc -g -c -o test.d.cmo test.ml
ocamlc -g -pack -o pack.d.cmo test.d.cmo
```
with the following error message:
```
Error: I/O error: test.d.cmi: No such file or directory
```

I'm not seeing any related items in the changelog of 5.1.0\~alpha1 so i believe this is an unexpected regression.

The test-case shown above can be seen with build-systems such as ocamlbuild.

**Comment by gasche** [comment]
My money is on #12389 and #12545.

**Comment by lthls** [comment]
There's no `-for-pack` involved ? I'm very much convinced that we shouldn't support the sequence of compilation commands shown above.
I'll try to look at ocamlbuild's code and see if I can make a patch.
Is there a specific package I can use to reproduce the error ?

**Comment by kit-ty-kate** [comment]
> There's no `-for-pack` involved ?

there is, i just wanted to make the test-case here as short as possible.

> Is there a specific package I can use to reproduce the error ?

yes, i originally noticed this issue in `Snowflake.0.02.03`
