### ISSUE TITLE
Wrong interface mli generation in for loops

### ISSUE THREAD

**Issue by vog** [ocaml/ocaml#13032]
I noticed a corner case where the interface generation produces a wrong result.

Steps to reproduce:

```
cat >Test.ml <<'EOF'
let iter_digits f =
  for i = 0 to 9 do
    f i
  done
EOF

ocamlc -i Test.ml
```

Expected output:

```
val iter_digits : (int -> unit) -> unit
```

Actual output:

```
val iter_digits : (int -> 'a) -> unit
```

Compiler version:

```
$ ocamlc --version
5.1.1
```

**Comment by gasche** [comment]
This is the expected behavior: by default OCaml allows expressions of any type to be used as statements (their result is ignored), it does not force them to have type `unit`. You can get the behavior you expect by using the `-strict-sequence` option.
