### ISSUE TITLE
undefined symbol: caml_zstd_initialize when building ppx using OCaml built with --without-zstd

### ISSUE THREAD

**Issue by samwgoldman** [ocaml/ocaml#13031]
I am trying to use OCaml 5.2.0~alpha1 using the --without-zstd option because my company's internal toolchain makes the dependency on shared libraries awkward.

I am able to produce a compiler, but I can't produce a binary that links against ocamlcommon.a due to a linker error. I can see that `caml_zstd_initialize` is defined in `runtime/zstd.c`. In that file, there is a preprocessor macro that looks for `HAS_ZSTD` and defines the function correctly in either case: https://github.com/ocaml/ocaml/blob/5.2/runtime/zstd.c#L110-L113

My build tooling uses ocamlcommon to build ppx binaries. We don't need to read compressed objects because we never produce them. The binaries we ultimately want to produce do not link against ocamlcommon.

To reproduce, it should be enough to install ocaml-variants.5.2.0~alpha1+ocaml-option-no-compression, then build a binary that links against compiler-libs/ocamlcommon.a.

**Comment by samwgoldman** [comment]
Sorry, I think this might be an issue with our internal build rules. I can see that libcomprmarsh.a defines `caml_zstd_initialize`, but we must not be picking up this dependency.

I tried to reproduce using a standard opam install and had no problem compiling the following program:

```
let () =
  ignore (Compression.compression_supported : bool)
```

using the simple build step:

```
ocamlopt -I +compiler-libs ocamlcommon.cmxa test.ml
```

**Comment by anmonteiro** [comment]
hey @samwgoldman, perhaps some of the comments in [this issue](https://github.com/ocaml/ocaml/issues/12798) are helpful to demystify what's going on. I opened that issue because I was confused about the build rules related to ocamlcommon and zstd.
