### ISSUE TITLE
ThreadSanitizer CI failures on a PR are not shown in the Github UI

### ISSUE THREAD

**Issue by OlivierNicole** [ocaml/ocaml#13041]
The TSan CI is no longer listed in the list of checks at the bottom of a PR, even when someone labels the PR with `run-thread-sanitizer`. On the one hand, PRs now look nicer when that label is absent, because when all checks pass, Github folds them into a single, satisfying green mark (I remember @dra27 was sad that the skipped TSan checks used to show in grey and prevent such folding). On the other hand, when the label `run-thread-sanitizer` is added, one can see “All checks passed” even when the TSan CI failed, which is clearly not ideal.

**Comment by dra27** [comment]
I'm confused - at the moment the PR does show the TSAN in the list, or is that now because it's merged?

**Comment by OlivierNicole** [comment]
Mmh, strange, it used not to show TSan before the merge. I’m certain of that.

**Comment by dra27** [comment]
There's I think some similar strangeness which can still happen with the no-changes-entry-needed label as well where the checks status after merge is different from the status before... let's definitely keep this open until we're sure what's going on with it!

**Comment by OlivierNicole** [comment]
This no longers shows up, so I’ll assuem it was a Github bug and close this. We can reopen if the issue ever reappears.
