### ISSUE TITLE
Check the result of caml_stat_alloc_noexc in runtime/major_gc.c (cycle_major_heap_from_stw_single)

### ISSUE THREAD

**Issue by damiendoligez** [ocaml/ocaml#13212]
Opening this issue to properly keep track of https://github.com/ocaml/ocaml/pull/12579/files#r1335472123

**Comment by NickBarnes** [comment]
This seems like a very simple fix (basically, skip recording the overhead if we can't allocate this buffer). However, I notice that this linked list of buffers (`caml_stat_space_overhead`) grows without bound, adding one `double` slot per major cycle, which is probably not a good idea in very-long-lived processes. That could be fixed, by having a single buffer with some book-keeping slots and doing the Welford's algorithm filtering-and-accumulation (currently in `caml_mean_space_overhead`) each time the buffer fills up. But maybe @kayceesrk (as the original author of this code) could comment, as this whole mechanism appears only to be used to compute a single value, reported by `caml_do_exit` if the GC logging parameter has a particular bit set. The questions are:

- do we care about this value at all? If not, let's delete all this code and not report the value.
- do we care that it's accurate in all cases? If so, let's do the extra work to maintain it in constant storage. If not, let's just do the trivial fix to stop maintaining it if this allocation fails.

**Comment by gasche** [comment]
My impression is that `caml_stat_space_overhead` is useful to track dynamically (this requires a bit of book-keeping, but no dynamic allocations), and `caml_mean_space_overhead` is probably less useful. I'm also not sure what it means, as we compute the arithmetic mean of ratios/percentages. Someone who needs this information for profiling/instrumentation (maybe not in production) can set the appropriate logging level for GC verbosity, grep the output and compute statistics themselves.

**Comment by NickBarnes** [comment]
At least in this repo, `caml_stat_space_overhead` is only used in `caml_mean_space_overhead()`, which is in turn only used in `caml_do_exit()`. I believe that @kayceesrk added it, and perhaps @stedolan or @sadiqj used it, to help guide development of the multicore major GC. There may be forks of the runtime which use `caml_stat_space_overhead` more broadly, but a quick check doesn't show any on GitHub at least. I'm running an `opam grep` now, to check for uses of `caml_mean_space_overhead` out there in the broader ecosystem.

**Comment by kayceesrk** [comment]
I don’t think anyone uses mean space overhead, and I wouldn’t mind if it were deleted. In practice, I find the metric to be all over the place compared to the space overhead parameter. It hasn’t been very useful so far.

**Comment by gasche** [comment]
@NickBarnes: I think that `caml_space_overhead` can be observed through the `caml_gc_log` call at

https://github.com/ocaml/ocaml/blob/8ffd7e1a2568d3193834366fc45619e9601fc942/runtime/major_gc.c#L1413

(This was already around in OCaml 4, 

https://github.com/ocaml/ocaml/blob/adfd44d497be7b51708e31f0fa9a942f7336f1e9/runtime/major_gc.c#L1144-L1145

where it was also used as a heuristic to provoke compaction

https://github.com/ocaml/ocaml/blob/adfd44d497be7b51708e31f0fa9a942f7336f1e9/runtime/major_gc.c#L1147
)

I'm not sure that we sometimes want to observe this value in the log to reason about a program behavior, but it seems trivial to keep it around, and yet remove the linked list of buffers used to store all its previous values, as was required to compute `min_overhead`.
