### ISSUE TITLE
ppc64le: operand out of range

### ISSUE THREAD

**Issue by jamesjer** [ocaml/ocaml#13220]
The Fedora project recently updated to OCaml 5.2.0.  Frama-C 28.1 built without issue on all architectures.  I just attempted to update to Frama-C 29.0 for Fedora Rawhide (the future Fedora 41).  The build failed on ppc64le only:
```
File "src/plugins/wp/.wp.objs/native/_unknown_", line 1, characters 0-0:
Command [4866] exited with code 2:
$ (cd _build/default && /usr/bin/ocamlopt.opt -open Frama_c_kernel -w -40 -w -9 -g -I src/plugins/wp/.wp.objs/byte -I src/plugins/wp/.wp.objs/native -I /usr/lib64/ocaml/apron -I /usr/lib64/ocaml/astring -I /usr/lib64/ocaml/bigarray-compat -I /usr/lib64/ocaml/bos -I /usr/lib64/ocaml/ctypes -I /usr/lib64/ocaml/ctypes/stubs -I /usr/lib64/ocaml/dune-private-libs/dune-section -I /usr/lib64/ocaml/dune-private-libs/meta_parser -I /usr/lib64/ocaml/dune-site -I /usr/lib64/ocaml/dune-site/linker -I /usr/lib64/ocaml/dune-site/plugins -I /usr/lib64/ocaml/dune-site/private -I /usr/lib64/ocaml/dynlink -I /usr/lib64/ocaml/fmt -I /usr/lib64/ocaml/fpath -I /usr/lib64/ocaml/gmp -I /usr/lib64/ocaml/integers -I /usr/lib64/ocaml/logs -I /usr/lib64/ocaml/menhirLib -I /usr/lib64/ocaml/mlmpfr -I /usr/lib64/ocaml/num -I /usr/lib64/ocaml/ocamlgraph -I /usr/lib64/ocaml/parsexp -I /usr/lib64/ocaml/ppx_deriving/runtime -I /usr/lib64/ocaml/re -I /usr/lib64/ocaml/rresult -I /usr/lib64/ocaml/sexplib -I /usr/lib64/ocaml/sexplib/num -I /usr/lib64/ocaml/sexplib0 -I /usr/lib64/ocaml/str -I /usr/lib64/ocaml/threads -I /usr/lib64/ocaml/unix -I /usr/lib64/ocaml/why3 -I /usr/lib64/ocaml/yaml -I /usr/lib64/ocaml/yaml/bindings -I /usr/lib64/ocaml/yaml/bindings/types -I /usr/lib64/ocaml/yaml/c -I /usr/lib64/ocaml/yaml/ffi -I /usr/lib64/ocaml/yaml/types -I /usr/lib64/ocaml/yaml/unix -I /usr/lib64/ocaml/yojson -I /usr/lib64/ocaml/zarith -I /usr/lib64/ocaml/zip -I /usr/lib64/ocaml/zmq -I src/.frama_c_kernel.objs/byte -I src/.frama_c_kernel.objs/native -I src/init/.frama_c_very_first.objs/byte -I src/init/.frama_c_very_first.objs/native -I src/libraries/qed/.qed.objs/byte -I src/libraries/qed/.qed.objs/native -I src/plugins/eva/.eva.objs/byte -I src/plugins/eva/.eva.objs/native -I src/plugins/postdominators/.postdominators.objs/byte -I src/plugins/postdominators/.postdominators.objs/native -I src/plugins/rte/.RteGen.objs/native -I src/plugins/rte/.RteGen.objs/public_cmi -I src/plugins/server/.server.objs/byte -I src/plugins/server/.server.objs/native -intf-suffix .ml -no-alias-deps -open Wp__ -o src/plugins/wp/.wp.objs/native/wp__WpTipApi.cmx -c -impl src/plugins/wp/wpTipApi.ml)
/tmp/build_f37dce_dune/camlasm1ce00c.s: Assembler messages:
/tmp/build_f37dce_dune/camlasm1ce00c.s:26026: Error: operand out of range (0x8018 is not between 0xffffffffffff8000 and 0x7ffc)
File "src/plugins/wp/wpTipApi.ml", line 1:
Error: Assembler error, input left in file /tmp/build_f37dce_dune/camlasm1ce00c.s
```

I can reproduce by entering the buildroot and running that ocamlopt command directly.  The C compiler is gcc-14.1.1-4.fc41, with binutils-2.42.50-11.fc41.  The line that is indicated as containing the bad operand (26026) is the last instruction of this block:
```
.L2228:
        .loc    8       170
        ld      0, 0(30)
        addi    31, 31, -56
        cmpld   31, 0
        bltl-   .L2261
```

Label .L2261 is defined on line 35303.  Perhaps "operand out of range" for a branch instruction means that the target is too far away?  I have saved the .s file if anybody wants to look at it.

**Comment by jmid** [comment]
Is it correctly understood that Fedora enables flambda by default?
https://src.fedoraproject.org/rpms/ocaml/blob/rawhide/f/ocaml.spec#_263

**Comment by gasche** [comment]
I just merged @dustanddreams' proposed fix ( #13221 ) in trunk. I believe that the fix should backport cleanly to the 5.2 branch, and I wonder if we should do this. @jamesjer is there a reasonably easy way for you to test that the fix really makes the issue go away? (It is a correct fix to *some* issues with the power backend, but we did not check that Frama-C builds again on ppc64le, so there might be other issues lurking around.)

**Comment by jamesjer** [comment]
@jmid, yes, Fedora does have flambda enabled. @gasche, yes I can try the indicated fix, but it will probably take me a little time, as I will have to rebuild everything under frama-c first, right?  I'll get that started and let you know when I have results.  Thank you for the quick response.

**Comment by jamesjer** [comment]
I can confirm that frama-c 29.0 builds successfully with https://github.com/ocaml/ocaml/pull/13221.

**Comment by gasche** [comment]
Great, thanks! (and thanks to @dustanddreams for the fix)

**Comment by rwmjones** [comment]
FYI I'm rebuilding the Fedora packages with the patch: https://koji.fedoraproject.org/koji/builds?inherited=0&tagID=91297&order=-build_id&latest=1
