### ISSUE TITLE
Warning 34 (unused type) no longer fires on unused locally-abstract types

### ISSUE THREAD

**Issue by ncik-roberts** [ocaml/ocaml#13254]
#12236 unintentionally introduced a bug where Warning 34 is not raised on locally-abstract types, i.e. types introduced via the `(type a)` or `type a.` syntax.

Behavior prior to that PR:
```ocaml
$ ocaml -w +34
# fun (type a) -> ();;
Warning 34 [unused-type-declaration]: unused type a.
```

At the current `trunk` (`a36d997`), the above program is accepted without warning. I'll open a PR fixing this shortly.

**Comment by Octachron** [comment]
The issue was fixed by #13255.
