### ISSUE TITLE
Installation documentation... .... confusing

### ISSUE THREAD

**Issue by christopherreay** [ocaml/ocaml#13264]
On this page:
https://ocaml.org/docs/installing-ocaml

the linux instructions require that installation is done as root / sudo
but it seems very likely to me that `opam init -y` should be run as the intended user.

**Comment by gasche** [comment]
This is a reasonable point, but could you open an issue at <https://github.com/ocaml/ocaml.org>, which is for the website, instead of the present repository which is for the compiler implementation?

**Comment by Octachron** [comment]
I don't see where the linux instructions require root permission? (Except for installing opam with a distribution package manager).

**Comment by christopherreay** [comment]
Yes, they dont say that. totally agree.

so where it says "use apt install...." the implication is that it is necessary to use sudo/root, where then that implication doesnt have a clear bounds to remove it when running opam as a user

**Comment by christopherreay** [comment]
> This is a reasonable point, but could you open an issue at https://github.com/ocaml/ocaml.org, which is for the website, instead of the present repository which is for the compiler implementation?

yes, sorry will do tyty
