### ISSUE TITLE
`Stdlib.Format` sometimes produces lines with trailing whitespace

### ISSUE THREAD

**Issue by mdelvecchio-jsc** [ocaml/ocaml#13278]
`Stdlib.Format` is used by `Sexplib0.Sexp.to_string_hum` similar to the example below. In some cases, the resulting string has trailing whitespace on some of the lines, which can cause problems for some tooling (e.g. editors which automatically strip trailing whitespace).

I tried debugging this myself, but got stuck on some of the internal logic of the pretty-print state machine.

I tried to minimize the example as much as possible, but most further simplifications fail to trigger the bug.

Compiler: `ocaml-base-compiler.5.2.0`

Program:
```
open Format

let () =
  let buffer = Buffer.create 1024 in
  let ppf = formatter_of_buffer buffer in
  let indent = 1 in
  let atom len = pp_print_string ppf (String.make len 'x') in
  let list f =
    pp_open_box ppf indent;
    pp_print_string ppf "(";
    f ();
    pp_print_string ppf ")";
    pp_close_box ppf ()
  in
  let space () = pp_print_space ppf () in
  let () =
    list (fun () ->
      list (fun () ->
        list (fun () ->
          atom 65;
          space ();
          atom 65;
          space ();
          list (fun () -> atom 5);
          space ();
          atom 1)))
  in
  let result = Buffer.contents buffer in
  let result =
    String.map
      (function
        | ' ' -> '#'
        | x -> x)
      result
  in
  print_string result;
  print_newline ()
;;
```

Output:
```
(((xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
###xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx#
###(xxxxx)#x)))
```

**Comment by Octachron** [comment]
The output in your example is correct according to `Format` specification: the margin is 78, and `max_indent` is 68.
Thus, the box for the fourth inner list cannot be opened on the current line which is beyond `max_indent`, and is rejected to the next line.

**Comment by ccasin** [comment]
> The output in your example is correct according to `Format` specification: the margin is 78, and `max_indent` is 68. Thus, the box for the fourth inner list cannot be opened on the current line which is beyond `max_indent`, and is rejected to the next line.

I think the newlines here are fine, but am surprised that lines 2 ends in whitespace.  I think in this example spaces are only printed by `pp_print_space`, and my reading of the mli is that it should either print a space or break the line, but not both.

(Perhaps I misunderstand your comment though)

**Comment by ccasin** [comment]
Ah, I see, you're saying the space is printed by `pp_print_space` and the newline is created by the box.  OK, I retract my comment and I think I agree this is not a bug.

**Comment by mdelvecchio-jsc** [comment]
`pp_print_space` is implemented as `pp_print_break state 1 0`, i.e. print one horizontal space if the next item fits, and no horizontal spaces if the next item breaks. I interpret that as this should not add a horizontal space in this case?

**Comment by Octachron** [comment]
The `max_indent` rule implementation is equivalent to adding a implicit break hint (which only breaks when we are beyond `max_indent`) when opening new boxes. With this interpretation, the next item is a break hint and fits on the line.

I tend to agree that having this implicit break hint at the same level of priority as standard break is not ideal.
