### ISSUE TITLE
Comment on Array.sort is incorrect

### ISSUE THREAD

**Issue by SkySkimmer** [ocaml/ocaml#13291]
https://github.com/ocaml/ocaml/blob/0d18e1287e49e92cf37824559cda5c09a2438b32/stdlib/array.mli#L327-L329
~~~
   When [sort] returns, [a] contains the same elements as before,
   reordered in such a way that for all i and j valid indices of [a] :
-   [cmp a.(i) a.(j)] >= 0 if and only if i >= j
~~~
but if the array contains 2 equal elements, `cmp a.(0) a.(1) = 0 >= 0` but  `not (0 >= 1)` (ie the "only if" part is only true for strict inequalities)

**Comment by nojb** [comment]
Thanks. We agree that we can replace `if and only if` by `if` to make the specification hold in all cases?

**Comment by xavierleroy** [comment]
Yes, we agree.  The "only if" for strict inequalities is a consequence of the weaker specification, if I'm not mistaken.
