### ISSUE TITLE
Format.pp_set_margin not respected

### ISSUE THREAD

**Issue by SkySkimmer** [ocaml/ocaml#13305]
~~~ocaml

let test margin =
  let () = Format.pp_set_margin Format.std_formatter margin in

  let () =
    Format.printf "@[<hov>foo =@ @[<hov>@[<hov 2>fun@ @[<hov 1>A : bool@]@]@ =>@ @[<hov 1>(@[<hov>@[<hov>@[<hov>@[<hov>@[<hov>@[<hov>@[<hov>@[<hov>@[<hov>@[<hov>@[<hov>@[<hov>@[<hov>@[<hov>A &&@ A@] &&@ A@] &&@ A@] &&@ A@] &&@ A@] &&@ A@] &&@ A@] &&@ A@] &&@ A@] &&@ A@] &&@ A@] &&@ A@] &&@ A@] &&@ A@])@]%%bool@]@]@."
  in

  let () =
    let s = String.init margin (fun i -> if i = margin - 1 then '^' else ' ') in
    Format.printf "%s@." s
  in
  ()
;;

let () = test 73;;
(*
foo =
fun A : bool =>
(A && A && A && A && A && A && A && A && A && A && A && A && A && A && A)%bool
                                                                        ^
*)

let () = test 72;;
(*
foo =
fun A : bool =>
(A && A && A && A && A && A && A && A && A && A && A && A && A && A &&
 A)%bool
                                                                       ^
*)
~~~
(test 73 should be breaking more, I guess it should produce the same as test 72)

(from https://github.com/coq/coq/issues/19168)

**Comment by jberdine** [comment]
At the end of the format string there is `A@])@]%%bool`. Here the box closed by `@]` does fit within the margin, and so is not broken. Then there is no break hint before the `)`, so the line cannot be broken there.

It may be inconvenient behavior, but I don't think this is a bug.

**Comment by SkySkimmer** [comment]
I guess we would need to add a break hint such as `A@]@,)@]%%bool`

**Comment by jberdine** [comment]
If you don't want a break before the `)`, moving the `)` and whatever follows  into the preceding box could be preferable.

In general, keep in mind that Format decides to break a box or not depending on what comes before the box close marker, it does not look forward to see if it can fit what comes next without violating the margin.

**Comment by SkySkimmer** [comment]
I guess you mean something like
~~~
"@[<hov 1>(@[<hov>@[<hov>@[<hov>@[<hov>@[<hov>@[<hov>@[<hov>@[<hov>@[<hov>@[<hov>@[<hov>@[<hov>@[<hov>A &&@ A@] &&@ A@] &&@ A@] &&@ A@] &&@ A@] &&@ A@] &&@ A@] &&@ A@] &&@ A@] &&@ A@] &&@ A@] &&@ A@] &&@ A@] &&@ A)%%bool@]@."
~~~
(end of hov 1 moved after `bool`, outermost hov 0 removed)
but IDK if that's something we can generate in practice
