### ISSUE TITLE
Insecure C binding example in the manual

### ISSUE THREAD

**Issue by dbuenzli** [ocaml/ocaml#13346]
Opening an issue because I don't have the time for a PR right now. Happy to review if someone does it before I do.

The sample binding `stub_gethostbyname` in the manual [here](https://ocaml.org/manual/5.2/intfc.html#ss:parallel-execution-long-running-c-code) has a security issue. The OCaml string should be checked that it is C safe by invoking `caml_string_is_c_safe`. Like `caml_unix_gethostbyname` [does](https://github.com/ocaml/ocaml/blob/af33f3f992319c6d2e248b562a7d8cb89ef06946/otherlibs/unix/gethost.c#L141).

**Comment by gasche** [comment]
@MisterDA, would you by any chance be interested in submitting a PR to do this?

**Comment by MisterDA** [comment]
Tangentially, `gethostbyname` has been deprecated in favor of `getaddrinfo`. Maybe we could find another function to use? (`getaddrinfo` is way too complex for the manual).
Also, I find this comment about freeing the string before releasing the runtime system dubious: we're not using this pattern _at all_ in the runtime or the unix library, where we try to enclose as tight as possible blocking functions in the release/acquire pairs.
```c
  /* Free the copy of the string, which we might as well do before
     acquiring the runtime system to benefit from parallelism. */
  caml_stat_free(name);
  /* Re-acquire the OCaml run-time system */
  caml_acquire_runtime_system();
```

**Comment by dbuenzli** [comment]
I don't mind changing to another paradigmatic real world blocking function here, then perhaps we simply don't need `caml_string_is_c_safe`. I just think the example should be examplar and it's not at the moment.

Also that's another issue but I realize `caml_string_is_c_safe` is not even mentioned in the manual. This is a very bad omission in my opinion. While I think it could benefit of a few paragraphs and a concrete example, at the minimum it should be mentioned in `String_val` [here](https://ocaml.org/manual/5.2/intfc.html#ss:c-block-access).

**Comment by dbuenzli** [comment]
Note that it's the merge of #13351 that will close this.
