### ISSUE TITLE
surprising interaction between `[@inline]` and `Array.unsafe_get`

### ISSUE THREAD

**Issue by c-cube** [ocaml/ocaml#13448]
I got a [bug report](https://github.com/c-cube/ocaml-containers/issues/454) in containers[^1] that I think is actually linked to the compiler. To repro, assume we have this file:

main.ml:
```ocaml
module Vec = struct

type 'a t = { mutable vec: 'a array }

let push self x = self.vec <- [|x|]

let[@inline] get self i =
  if i >= Array.length self.vec then invalid_arg "ohno";
  Array.unsafe_get self.vec i
end

let () =
  let arr : Int32.t Vec.t = { vec= [| |] } in
  Vec.push arr (Int32.of_int 123456) ;
  Format.printf "%d\n" (Int32.to_int (Vec.get arr 0));
  let x = Vec.get arr 0 in
  Format.printf "%d\n" (Int32.to_int x)
```

compiled using `ocamlfind ocamlopt main.ml -o main`.

The bug:
```sh
$ ocamlfind ocamlopt main.ml -o main; ./main
123456
1024
```

The expected behavior is that it should print `123456` twice. Somehow this doesn't seem to happen if everything is in the same file. With bytecode it works normally.

[^1]: I added a `Sys.opaque_identity` in some places which seems to be an adequate workaround.

**Comment by nojb** [comment]
Smaller repro:
```
let () =
  let arr = [| 123456l |] in
  print_endline (Int32.to_string (Array.unsafe_get arr 0));
  let get = Array.unsafe_get in
  let x = get arr 0 in
  print_endline (Int32.to_string x)
```
The code works correctly in 4.14, and produces:
```
cmm:
(data)
(data int 768 global "camlFoo" "camlFoo":)
(data global "camlFoo__gc_roots" "camlFoo__gc_roots": addr "camlFoo" int 0)
(data int 3071 "camlFoo__1": addr "caml_int32_ops" int32 123456 int32 0)
(function camlFoo__entry ()
 (let
   *match*/363
     (let arr/269 (alloc{foo.ml:2,12-25} 1024 "camlFoo__1")
       (app{foo.ml:3,2-58} "camlStdlib__print_endline_367"
         (app{foo.ml:3,16-58} "camlStdlib__Int32__to_string_380"
           (load_mut val arr/269) val)
         unit)
       (let x/358 (load_mut val arr/269)
         (app{foo.ml:6,2-35} "camlStdlib__print_endline_367"
           (app{foo.ml:6,16-35} "camlStdlib__Int32__to_string_380" x/358 val)
           val)))
   [])
 1)

(data)
```
However, in OCaml 5 it produces:
```
cmm:
(data)
(data int 768 global "camlFoo" "camlFoo":)
(data global "camlFoo.gc_roots" "camlFoo.gc_roots": addr "camlFoo" int 0)
(data int 3071 "camlFoo.1": addr "caml_int32_ops" int32 123456 int32 0)
(function camlFoo.entry ()
 (let
   *match*/364
     (let arr/269 (alloc{foo.ml:2,12-25} 1024 "camlFoo.1")
       (app{foo.ml:3,2-58} "camlStdlib.print_endline_369"
         (app{foo.ml:3,16-58} "camlStdlib__Int32.to_string_381"
           (load_mut val arr/269) val)
         unit)
       (let
         x/367
           (if (!= (load_mut unsigned int8 (+a arr/269 -8)) 254)
             (load float64 (load_mut val arr/269))
             (load_mut float64 arr/269))
         (app{foo.ml:6,2-35} "camlStdlib.print_endline_369"
           (app{foo.ml:6,16-35} "camlStdlib__Int32.to_string_381"
             (alloc{foo.ml:4,12-28} 1277 x/367) val)
           val)))
   [])
 1)

(data)
```
The difference is that the `let x = get arr 0` is compiled as if `arr` was an array of `float`s (!). And indeed, the bug goes away if one annotates `x`:
```
let () =
  let arr = [| 123456l |] in
  print_endline (Int32.to_string (Array.unsafe_get arr 0));
  let get = Array.unsafe_get in
  let x : int32 = get arr 0 in
  print_endline (Int32.to_string x)
```

**Comment by yallop** [comment]
I see the same problem with OCaml 4.14.1 and with older versions (e.g. 4.12.1).

**Comment by nojb** [comment]
> I see the same problem with OCaml 4.14.1 and with older versions (e.g. 4.12.1).

I tried with 4.14.2 myself and did not see the issue.

**Comment by nojb** [comment]
The "float" cmm can be observed with the even smaller
```
let _ =
  let arr = [| 123456l |] in
  let get = Array.unsafe_get in
  get arr 0
```

**Comment by nojb** [comment]
One difference between 4.14.2 and 5 is that in 4.14.2 the lambda code looks like
```
(seq
  (seq
    (let (arr/269 = (makearray[int] 123456) prim/322 = 0)
      (array.unsafe_get[addr] arr/269 prim/322))
    0)
  0)
```
while in OCaml 5 it looks like:
```
(seq
  (seq
    (let (arr/269 = (makearray[int] 123456) prim/322 = 0)
      (array.unsafe_get[gen] arr/269 prim/322))
    0)
  0)
```
where `[addr]` has changed into `[gen]`. [This may actually be due to the fact that my 4.14 switch has flat float arrays disabled.]

**Comment by nojb** [comment]
> > I see the same problem with OCaml 4.14.1 and with older versions (e.g. 4.12.1).
> 
> I tried with 4.14.2 myself and did not see the issue.

Ah, another thing: I tested with a compiler where "flat float arrays" are disabled; I suspect this may make the bug go away.

**Comment by yallop** [comment]
I tried with 4.10.2 (which has the bug) and 4.09.1 (which doesn't seem to have it), both just installed from opam, and both configured with `flat_float_array: true`.

**Comment by gasche** [comment]
The bug comes from `Cmmgen.is_unboxed_number_cmm`, which infers the "unboxing type" of its argument and/but propagates this knowledge across if-then-else branches. Weirdly enough, there seems to be a protection against this in the code, but it appears to be ineffective:

https://github.com/ocaml/ocaml/blob/550f3710c2f90b112f78cc8f4dbc7de4a47d1ec6/asmcomp/cmmgen.ml#L1183-L1189

**Comment by nojb** [comment]
> The bug comes from `Cmmgen.is_unboxed_number_cmm`, which infers the "unboxing type" of its argument and/but propagates this knowledge across if-then-else branches. Weirdly enough, there seems to be a protection against this in the code, but it appears to be ineffective:
> 
> https://github.com/ocaml/ocaml/blob/550f3710c2f90b112f78cc8f4dbc7de4a47d1ec6/asmcomp/cmmgen.ml#L1183-L1189

Actually I think it is the previous case (where we pass `~strict:false`), because in the example we know statically that the element type is `int32`.

**Comment by gasche** [comment]
Yes, I think that the bug is that we pass `~strict:false`, but in fact this is wrong. If we know the final type ahead of time, we could use it to "cull" the incompatible branches instead of letting them pollute the result. Passing `strict:true` would probably be a better first step.

**Comment by nojb** [comment]
The code was introduced in 258a33579123388d7c2e3927052551e25bc30983 cc @alainfrisch.

**Comment by nojb** [comment]
Isn't the problem that one cannot apply this optimization in the presence of flat float arrays where "generic" array accesses produce if-then-elses with different types in each branch?

**Comment by gasche** [comment]
Well GADTs could also suffer from the same issue, even without flat float arrays.

**Comment by gasche** [comment]
I propose a fix in #13449.

**Comment by gasche** [comment]
Fixed! Thanks @c-cube and @RafaelBocquet for the bug report. I feel bad at the thought that we had this bug lurking around for years, but also good at the thought that you *rarely* need to report compiler bugs. (Is it the first over the lifetime of containers?)

The fix should be present in future releases of OCaml 4.x and 5.x, starting at OCaml 5.3.

**Comment by c-cube** [comment]
Thank you @gasche ! I… think this is the first one indeed! :grin: The robustness of the OCaml compiler is certainly one of its biggest strengths compared to other non-behemoth-sized languages out there.

I think Rafael should be co-credited for reporting in the changelog!
