### ISSUE TITLE
The runtime events tests fail sporadically.

### ISSUE THREAD

**Issue by kayceesrk** [ocaml/ocaml#13446]
The test `tests/lib-runtime-events/test_dropped_events.ml` fails in #13408 ([failure](https://github.com/ocaml/ocaml/actions/runs/10627990145/job/29462019993#step:13:1879)) and #13407 ([failure](https://github.com/ocaml/ocaml/actions/runs/10771211633/job/29866558627?pr=13407#step:5:1834)). 

The test `tests/lib-runtime-events/test_create_cursor_failures.ml` fails in #13407 ([failure](https://github.com/ocaml/ocaml/actions/runs/10771211633/job/30191687315?pr=13407#step:7:1901)).

CC @sadiqj @talex5.

**Comment by kayceesrk** [comment]
If we are not able to fix this quickly, we should consider disabling the test as the unrelated, sporadic failure is distracting.

**Comment by ghost** [comment]
Should have been fixed by #13529 and #13522.
