### ISSUE TITLE
Hashtbl.create with negative initial guess

### ISSUE THREAD

**Issue by nikolaushuber** [ocaml/ocaml#13469]
The documentation of `Hashtbl.create` says 

> `Hashtbl.create n` creates a new, empty hash table, with initial size `n`. For best results, `n` should be on the order of the expected number of elements that will be in the table. The table grows as needed, so `n` is just an initial guess.

It is curious, that this function does not raise any exception when `n` is negative. It seems, that `Hashtbl.create (-10)` is the same as `Hashtbl.create 0`. While not a bug in itself, it does seem a bit strange at first, and there is no explanation in the documentation. 

We stumbled upon this while working on [ortac/qcheck-stm](https://github.com/ocaml-gospel/ortac), and I was encouraged by @jmid to report it here. (The Gospel contracts for the `Hashtbl` module can be found [here](https://github.com/ocaml-gospel/ortac/blob/0753c72567b83f50ff1d66342c12aafe7dd881b5/plugins/qcheck-stm/test/hashtbl.mli))

**Comment by MisterDA** [comment]
The minimal size is `16` and the maximum size is `Sys.max_array_length`. IMO the wording "initial guess" is vague enough to allow this. The initial minimum size is retained by calls to `clear` and `reset`.
https://github.com/ocaml/ocaml/blob/67c5d4bd6dfde5361bc5ba7a70177db82449a61e/stdlib/hashtbl.ml#L68-L74

**Comment by jmid** [comment]
I can see OCaml code in the wild passing 0 as their initial guess: https://sherlocode.com/?q=Hashtbl.create
which is certainly a fair use to express "I have no good initial guess". I also found it perculiar that, e.g., `Hashtbl.create (-1234)` is allowed and indeed encouraged @nikolaushuber to share his finding of this percularity here.
