### ISSUE TITLE
String.concat suboptimal:

### ISSUE THREAD

**Issue by craff** [ocaml/ocaml#13609]
- The code could include a special case for list of length 1 that would allocate nothing ?
- Just a question: the ensure_ge test is to avoid integer overflow with very large strings ?

**Comment by gasche** [comment]
- Yes, it could. I think the current implementation comes from when we still had mutable string, and we needed to copy the input in all cases.
- Yes, I think `ensure_ge` is designed to avoid overflow issues.

**Comment by gasche** [comment]
(I suppose that you are thinking of sending a PR to improve the one-element case. Do we need to keep the present issue open, or can we close it if you are satisfied with the answers?)

**Comment by craff** [comment]
> * Yes, it could. I think the current implementation comes from when we still had mutable string, and we needed to copy the input in all cases.
> 
>     * Yes, I think `ensure_ge` is designed to avoid overflow issues.

I think the test in the blit phase could be a bit faster? Worth trying. Furthermore, this will probably never going to happen as 32 bits are rare and 1Gb string too ? But this is not in the Ocaml spirit to drop such a test ?

There is also a point on recursive list, but it takes forever to raise the exception on a 64 bits machine, so this is not the correct way to detect that case if we wanted too. Is there a way to know rapidly that a list is recursive (a special tag) ?

**Comment by craff** [comment]
By the way, split_on_char could also avoid copying the string when the char is not present. I could include this in the same P.R.

**Comment by craff** [comment]
> (I suppose that you are thinking of sending a PR to improve the one-element case. Do we need to keep the present issue open, or can we close it if you are satisfied with the answers?)

I you think such a PR is a good idea, you can close the issue and I will do the PR. Even for such a small change, making a PR is time consuming and if you think it is not worth it, I better not do a PR.

Thanks for your comments

**Comment by gasche** [comment]
I think that the one-element case is probably common enough to warrant a PR now that you did the work of noticing and bringing it to our attention. I would be okay with doing the PR myself if you prefer. I would not bother changing the overflow-checking logic -- I would be surprised if its performance was noticeable in practice.

**Comment by craff** [comment]
This is addressed by PR #13620.
