### ISSUE TITLE
ubuntu install failed again

### ISSUE THREAD

**Issue by cctv130** [ocaml/ocaml#13633]
![1732587793031](https://github.com/user-attachments/assets/d07dcc72-b1d3-43ea-a10f-efb378148d0d)

**Comment by kit-ty-kate** [comment]
i'm not seeing the failure here. Could you highlight it? I'm guessing your screenshot was cropped too short because it only shows the opam installer log, not anything related to the ocaml compiler

**Comment by cctv130** [comment]
It seems that the last line does not need to be displayed

**Comment by Octachron** [comment]
I am afraid I don't see any errors related to the compiler in this report, I am thus closing the issue. Please don't hesitate to seek help on https://discuss.ocaml.org .
