### ISSUE TITLE
incompleteness of subtyping ?

### ISSUE THREAD

**Issue by craff** [ocaml/ocaml#13647]
Do we really want to reject the last line here ?
Clearly there is an ambiguity as 'a could be instantiated with int or M.t
but in both case, the subtyping is correct and accepted. 

```
module M : sig
  type t = private int
  val from_int : int -> t
end = struct
  type t = int
  let from_int (x : int) = (x : t)
end
open M
let _ = (from_int :> int -> int)
let _ = (from_int :> M.t -> M.t)
let _ = (from_int :> 'a -> 'a)
```

**Comment by Octachron** [comment]
Rejecting the ambiguous coercion seems the most reasonable behavior to me.
I don't see a point to accept `(from_int :> 'a -> 'a )` when no one can predict what `'a -> 'a` would end up being.

**Comment by craff** [comment]
> Rejecting the ambiguous coercion seems the most reasonable behavior to me. I don't see a point to accept `(from_int :> 'a -> 'a )` when no one can predict what `'a -> 'a` would end up being.

This seems indeed reasonable. 

How is this achieved in the code ? This is not clear to me. If 'a was instantiated much before could make sense ?

**Comment by samsa1** [comment]
The way this is achieved in the code is that subtyping does not have the same semantic when the types are both closed or if one of them is opened.

You can see an example of this behaviour in : https://github.com/ocaml/ocaml/issues/13120

**Comment by craff** [comment]
Thanks for the explanations. Closing the issue.
