### ISSUE TITLE
Potential GC issue (causes segfaulting)

### ISSUE THREAD

**Issue by dc-mak** [ocaml/ocaml#13648]
Hi, apologies if a red-herring but would be good to get help triage this. 

https://github.com/ott-lang/ott/issues/116

Looks like a GC issue is causing a segfault (the same code works on 4.14.1). Have managed to get a reliable segfault on my machine (WSL2 Ubuntu 22.04 with OCaml 5.2.0). It's unlikely the Ott code itself is doing anything particularly suspicious except for using the Marshal module in a very straightforward way.

Happy to try help with gathering extra info with guidance (though I am writing a thesis at the moment so I may not be able to work on this promptly).

**Comment by bacam** [comment]
FWIW, it was a red-herring, we had a silly marshalling problem:  it turns out that earlier versions of OCaml somehow coped with being asked to demarshall to a larger tuple.
