### ISSUE TITLE
The native-code compiler is not supported on this platform: ocaml-4.14.2 won't compile in loong64 architecture

### ISSUE THREAD

**Issue by LoongUser77** [ocaml/ocaml#13653]
Looks like my CPU is not supported by ocalm, but I need it to compile some apps.

This is the error: 

```
/usr/bin/ld: warning: -z pack-relative-relocs ignored
Successfully remade target file 'sak'.
make[1]: Leaving directory '/home/loongson/pkgbuilds/ocaml4/src/ocaml-4.14.2/runtime'
Updating goal targets....
Considering target file 'world.opt'.
 File 'world.opt' does not exist.
 Considering target file 'checknative'.
  File 'checknative' does not exist.
 Finished prerequisites of target file 'checknative'.
 Must remake target 'checknative'.
Makefile:990: *** The native-code compiler is not supported on this platform.  Stop.
==> ERROR: A failure occurred in build().
    Aborting...
```

Some info abut the system:

                   -`                    loongson@loongson01 
                  .o+`                   ------------------- 
                 `ooo/                   OS: Arch Linux loongarch64 
                `+oooo:                  Host: Loongson-3A6000-HV-7A2000-1w-V0.1-EVB 
               `+oooooo:                 Kernel: 6.10.0-2 
               -+oooooo+:                Uptime: 1 hour, 28 mins 
             `/:-:++oooo+:               Packages: 666 (pacman) 
            `/++++/+++++++:              Shell: bash 5.2.26 
           `/++++++++++++++:             Resolution: 1920x1080 
          `/+++ooooooooooooo/`           Terminal: /dev/pts/0 
         ./ooosssso++osssssso+`          CPU: Loongson-3A6000-HV (8) 
        .oossssso-````/ossssss+`         GPU: 00:06.1 Loongson Technology LLC Display Controller 
       -osssssso.      :ssssssso.        Memory: 556MiB / 15970MiB

**Comment by Octachron** [comment]
You can use the bytecode compiler on architectures not supported by the native compiler.

**Comment by LoongUser77** [comment]
Thanks Octachron.
But I have no idea how to do that, do you have any documentation or manual?

**Comment by nojb** [comment]
> Thanks Octachron. But I have no idea how to do that, do you have any documentation or manual?

The basic approach is to pass the flag `--disable-native-compiler` to the `./configure` script.

**Comment by jmid** [comment]
IIUC, there's also https://github.com/ocaml/ocaml/pull/11974 with pointers to an out-of-tree branch offering support: https://github.com/loongson/ocaml

**Comment by LoongUser77** [comment]
--disable-native-compiler  fails too: 

```
GNU Make 4.4.1
Built for loongarch64-unknown-linux-gnu
Copyright (C) 1988-2023 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Reading makefiles...
Reading makefile 'Makefile'...
Reading makefile 'Makefile.common' (search path) (no ~ expansion)...
Reading makefile 'Makefile.config_if_required' (search path) (no ~ expansion)...
Reading makefile 'Makefile.build_config' (search path) (no ~ expansion)...
Reading makefile 'Makefile.config' (search path) (no ~ expansion)...
Directory . cache invalidated (count 1 != command 2)
Reading makefile 'stdlib/StdlibModules' (search path) (no ~ expansion)...
Reading makefile 'compilerlibs/Makefile.compilerlibs' (search path) (no ~ expansion)...
Reading makefile 'Makefile.menhir' (search path) (no ~ expansion)...
Reading makefile '.depend.menhir' (search path) (no ~ expansion)...
Reading makefile '.depend' (search path) (no ~ expansion)...
Updating makefiles....
Updating goal targets....
Considering target file 'world.opt'.
 File 'world.opt' does not exist.
 Considering target file 'checknative'.
  File 'checknative' does not exist.
 Finished prerequisites of target file 'checknative'.
 Must remake target 'checknative'.
Makefile:987: *** The source tree was configured with --disable-native-compiler!.  Stop.
==> ERROR: A failure occurred in build().
    Aborting...
```

but I will  check what jmid says. thanks!

**Comment by kit-ty-kate** [comment]
> --disable-native-compiler fails too:

The PKGBUILD file that you seem to be using from AUR uses `world.opt` which explicitly says it wants a native compiler (https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=ocaml4#n24)
Fixing this should be as simple as removing `world.opt` from that line

**Comment by LoongUser77** [comment]
Thanks, that did the trick, it compiled removing world.opt from configure command in PKGBUILD
Thanks
