### ISSUE TITLE
Stdlib Out_Channel: add a blackhole channel that directs to `/dev/null`

### ISSUE THREAD

**Issue by glyh** [ocaml/ocaml#13651]
I'm using stdlib to handle logging, and one particular pattern that is useful is to use /dev/null to supress log messages. It would be nice to have this integrated into Out_channel, rather than letting end user to open `/dev/null` manually as it's not portable.

**Comment by nojb** [comment]
Hello, note that there is `Filename.null` for a portable way to refer to the null device.

**Comment by glyh** [comment]
That make senses, does it work well with Out_Channel?

One of the reason I'm confused is that, do I need to close the out channel if it's /dev/null?

**Comment by nojb** [comment]
> That make senses, does it work well with Out_Channel?

Yes, of course.

> One of the reason I'm confused is that, do I need to close the out channel if it's /dev/null?

Yes, absolutely. File descriptors to `/dev/null` (or `Filename.null`) consume system resources, even if all output is discarded.

**Comment by glyh** [comment]
Okay, I think that should fulfill this. Thanks :)
