### ISSUE TITLE
5.3: some constrained types are not generalized

### ISSUE THREAD

**Issue by Octachron** [ocaml/ocaml#13688]
The typechecker in `-principal` mode currently fails to generalize `x` in

```ocaml
type 'e opt = 'e option constraint 'e = [> `A ]
let f: unit -> [> `A] opt = fun () -> None
let x = f ()
```
>  val x : ([> `A ] as '_weak1) opt = None

(and it is possible to construct examples that don't require `-principal`).
This bug is here since the switch to automatic generalize in #12946 .

**Comment by garrigue** [comment]
It took me a while before seeing the light: #13690.
Fortunately, almost all the logic of automatic generalization is inside `Ctype.with_local_level_gen`.
I should have looked there first.
