### ISSUE TITLE
Feature Wish : cmxa and cma manipulation tool like ar

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#2375]
**Original bug ID:** 2375
**Reporter:** administrator
**Status:** acknowledged
**Resolution:** open
**Priority:** normal
**Severity:** feature
**Category:** tools (ocaml{lex,yacc,dep,debug,...})
**Tags:** junior_job
**Parent of:** #8490

## Bug description

Full_Name: Benjamin Monate
Version: 3.07+2
OS: All
Submission from: is002447.saclay.cea.fr (132.166.134.145)

Bonjour,

Un outil de manipulation des bibliothèques OCaml serait très utile pour
les gros projets.

Il faudrait des fonctions similaires à celles de gnu ar : 
- extraire les unités de compilation contenues dans la lib (ar x)
- récupérer la liste des noms des unités de compilation de la lib (ar t)
- récupérer la liste des informations d'"auto-link" (--clib, -I, ...) contenues
dans la lib.

Moins utiles mais quand même intéressant :
- ajouter/remplacer/supprimer une unité dans une lib existante
- ajouter/supprimer des options d'auto-link
- fusionner des libs

En vous remerciant pour la qualité d'OCaml
Benjamin

**Comment by vicuna** [comment]
**Comment author:** administrator

Suggestion makes a lot of sense.

**Comment by vicuna** [comment]
**Comment author:** @mshinwell

Maybe ocamlobjinfo suffices?

**Comment by avsm** [comment]
I ran this through Google Translate:

> An OCaml library manipulation tool would be very useful for big projects.
> It would need functions similar to those of gnu ar:
> - extract the compilation units contained in the lib (ar x)
> - get the list of names of lib (ar t) compilation units
> - retrieve the list of "auto-link" information (--clib, -I, ...) contained in lib.
>
> Less useful but still interesting:
> - add / replace / delete a unit in an existing lib
> - add / remove auto-link options
> - merge libs
>
> Thanking you for the quality of OCaml
> Benjamin

**Comment by xavierleroy** [comment]
I'm going to put this feature wish to rest after all these years.

I know Unix `ar` is not just a library builder, but actually a file archiver.  I also know that the last time I used `ar` to extract `.o` files from a `.a` archive was 30 years ago.

Other toolchains (e.g. MSVC) have tools to build libraries from object files but nothing to extract object files from a library or replace them.

As to getting information on what's in a `.cma` or `.cmxa` archive, `ocamlobjinfo` does the job already.
