### ISSUE TITLE
ocamlbrowser and load path ...

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#2902]
**Original bug ID:** 485
**Reporter:** administrator
**Status:** acknowledged
**Resolution:** open
**Priority:** normal
**Severity:** feature
**Category:** tools (ocaml{lex,yacc,dep,debug,...})

## Bug description

Hello, ...

I just got a mail from one lablGL use which wanted to use ocamlbrowser to
check lablGL stuff.

I kindly indicated the path editor to him, and noticed that ocamlbrowser don't
seem to remember the path between two launches. Is this an error in my debian
package or the way this is now.

Also, is there not an easier way to select the installed subdir of the ocaml
LIBDIR, and have direct access to the installed libraries ? maybe having a use
library button/menu entry, or a tree widget to show the modules, and have each
library become an entry, which expanded would show all the modules of this
library ?

This would go nicely with the +library option, and also hints more at using a
subdirectory for each library, since the current situation would encourage
people to just put the library stuff directly in the ocaml libdir.

I just hope i am not speaking nonsense here ...

Friendly,

Sven Luther

**Comment by vicuna** [comment]
**Comment author:** administrator

> I kindly indicated the path editor to him, and noticed that ocamlbrowser
don't
> seem to remember the path between two launches. Is this an error in my debian
> package or the way this is now.

This is not a bug. You can use the -I option at launch time if you want
to use repeatedly some specific directory.

There may be some saved preferences in the future, but I would like to have
a standard way to do that.

I take your other comments as suggestions. I'm not yet sure of how it can be
done, particularly since there is no tree widget in Tk.

Cheers,

Jacques Garrigue

**Comment by vicuna** [comment]
**Comment author:** administrator

no preferences currently.  This one is for Jacques to decide...

**Comment by dbuenzli** [comment]
ocamlbrowser is no longer part from the distribution since 4.02. 

It is developed on the OCaml forge [here](https://forge.ocamlcore.org/projects/labltk/). I think this can be closed. /cc @garrigue

**Comment by damiendoligez** [comment]
I re-reported this to the new issue tracker of ocamlbrowser at https://forge.ocamlcore.org/tracker/index.php?func=detail&aid=1767&group_id=343&atid=1353
