### ISSUE TITLE
passer l'option -o au compilateur C

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#2915]
**Original bug ID:** 2915
**Reporter:** administrator
**Status:** acknowledged
**Resolution:** open
**Priority:** normal
**Severity:** feature
**Category:** compiler driver
**Has duplicate:** #3904

## Bug description

Bonjour,

quelques remarques à propos du CVS 3.08:

- dans otherlibs/unix/write.c (unix_single_write), le `ret' devrait être
initialisé à 0 pour le cas où `len' est égal à 0.

- les compilateurs utilisent maintenant l'option -o en mode
compilation pour les fichiers .ml/.mli, mais pas pour les fichiers .c:
il suffirait juste de passer le -o au compilateur C.

-- 
   Olivier

**Comment by vicuna** [comment]
**Comment author:** administrator

1- fixed 2004-07-08 by XL.
2- is feature wish.

**Comment by vicuna** [comment]
**Comment author:** @mshinwell

The compiler does still ignore "-o" when compiling C files.  Does anyone argue for changing this?

**Comment by vicuna** [comment]
**Comment author:** @mshinwell

(Xavier previously argued that there is no standard convention for C compilers as to how "-o" works.)

**Comment by mshinwell** [comment]
No-one has answered my question in the last 2.5 years, so closing.

**Comment by dbuenzli** [comment]
There is still an issue about the second point here https://github.com/ocaml/ocaml/issues/7677
