### ISSUE TITLE
Varying semantics of Unix.utimes

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#3145]
**Original bug ID:** 797
**Reporter:** administrator
**Status:** acknowledged
**Resolution:** open
**Priority:** normal
**Severity:** feature
**Category:** otherlibs

## Bug description

Full_Name: Zhe Yang
Version: 3.04
OS: Windows
Submission from: saul.cis.upenn.edu (158.130.12.4)

On the Windows platform, the Unix.utimes function behaves differently 
in the native, MSVC-based version and in the cygwin-based version.  The Posix
interpretation of utimes allows setting the time of read-only files, if the UID
of the process is the same as the owner of the file.  Using the cygwin-based 
version, utimes succeeds in this case, but using the MSVC-based version, utimes
fails with an exception.  

Could the utimes in the MSVC-based version of Ocaml be corrected?

Thanks, Zhe

**Comment by vicuna** [comment]
**Comment author:** administrator

To be fixed some day, but we first need to understand how Cygwin does it.

**Comment by xavierleroy** [comment]
The Win32 implementation of `Unix.utimes` was rewritten recently (commit af20b3e53) and seems to work fine with readonly files.
