### ISSUE TITLE
ocamlyacc - line numbers for undefined symbols

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#3222]
**Original bug ID:** 3222
**Reporter:** administrator
**Status:** acknowledged
**Resolution:** open
**Priority:** normal
**Severity:** feature
**Category:** tools (ocaml{lex,yacc,dep,debug,...})

## Bug description

Full_Name: Ethan Aubin
Version: 3.08.1
OS: windows
Submission from: foster-miller.com (64.119.130.179)

Following along the line of bug report <a
href="http://caml.inria.fr/bin/caml-bugs/wish%20granted?id=3048;expression=ocamlyacc;user=guest">3048</a>

Could the error message for undefined symbols in ocamlyacc print the file
location along with the symbol? Thanks - EA

**Comment by vicuna** [comment]
**Comment author:** administrator

not easy to do

**Comment by nojb** [comment]
Menhir is the recommended parser generator for OCaml, ocamlyacc is legacy software and will not be changed except to fix serious bugs.
