### ISSUE TITLE
ocamlmklib and .cmxa

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#3249]
**Original bug ID:** 3249
**Reporter:** administrator
**Status:** acknowledged
**Resolution:** open
**Priority:** normal
**Severity:** feature
**Category:** tools (ocaml{lex,yacc,dep,debug,...})

## Bug description

Full_Name: Pascal
Version: 3.08 (Debian)
OS: Linux
Submission from: indigo.recherche.enac.fr (195.220.159.164)

ocamlmklib allows to include .cma libraries (by the way, it is not documented
but it works as expected):

        ocamlmklib ... str.cma ...

but not .cmxa :

        brisset@sepia:~% ocamlmklib ... str.cmxa ...
        /usr/lib/ocaml/3.08/str.cmxa is not a compilation unit description.

--Pascal

**Comment by vicuna** [comment]
**Comment author:** administrator

Same behavior with ocamlc -a vs ocamlopt -a.  Wish: ocamlopt -a that accepts
.cmxa as arguments.  Require hacking around "ar" limitations.

**Comment by dbuenzli** [comment]
This problem still exists on 4.07.1 e.g.: 
```
> ocamlmklib -verbose -o bla hmap.cma
+ /Users/dbuenzli/.opam/4.07.1/bin/ocamlc -a    -o bla.cma  hmap.cma -dllib -lbla -cclib -lbla
    
> ocamlmklib -verbose -o bla hmap.cmxa
+ /Users/dbuenzli/.opam/4.07.1/bin/ocamlopt -a   -o bla.cmxa  hmap.cmxa -cclib -lbla    
Option -a cannot be used with .cmxa input files. 
```
though I fail a bit to see the use case (repacking a set of libraries as a larger one ?). 

That being said the synopsis of `ocamlmklib` seems to be a bit misleading:
```
> ocamlmklib -help
Usage: ocamlmklib [options] <.cmo|.cma|.cmx|.cmxa|.ml|.mli|.o|.a|.obj|.lib|.dll|.dylib files>
```
or at least widly different from what is specified in [the manual](https://caml.inria.fr/pub/docs/manual-ocaml/intfc.html#sec481). 

A look at the [implementation](https://github.com/ocaml/ocaml/blob/e141d9e2401d01c6ecb34ba7bf11dc1e50024437/tools/ocamlmklib.ml#L96-L108) seems to indicate that the synopsis is right. But the implementation strategy seems to be let's give all that to `ocamlc` and `ocamlopt` and see whatever happens.

**Comment by nojb** [comment]
My understanding is that this limitation stems from there being no simple way to merge static libraries in a portable way. Including all that intricate logic in the compiler does not seem to fit with its overarching philosophy. With that, I move to close this issue.

**Comment by xavierleroy** [comment]
Yes, `ocamlc -a` can combine several `.cma` into a single `.cma`, but `ocamlopt -a` cannot do the same because `ar` is unable to combine several `.a` archive files, at least not without awful hacks.  

The `ocamlmklib` synopsis should be fixed, indeed.  I believe no other change is necessary.
