### ISSUE TITLE
Unix.open_flag is missing O_BINARY and O_TEXT

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#3265]
**Original bug ID:** 3265
**Reporter:** administrator
**Status:** acknowledged
**Resolution:** open
**Priority:** normal
**Severity:** feature
**Category:** otherlibs

## Bug description

Full_Name: George Necula
Version: 3.08.1
OS: cygwin
Submission from: raw.cs.berkeley.edu (128.32.153.230)

Hi,

 I tracked down a bug in the Unison file synchronizer, which was using
Unix.openfile to copy a binary file. I could not fix the bug easily because
Unix.open_flag is missing O_BINARY. There is a workaround (use the standard IO)
but I wonder why is O_BINARY missing. It would be useful in cygwin, and can be
ignored otherwise.

 Thanks,
George.

**Comment by vicuna** [comment]
**Comment author:** administrator

Cygwin is the only system where BINARY and TEXT mode need to be applied at the
Unix level (the native windows ports need them only at the channel level).  I'll
leave this as a feature wish for the time being, but I don't like the idea of
polluting the API just for Cygwin.  XL, 2004-02-02

**Comment by xavierleroy** [comment]
At some point in the 00's, Cygwin switched the default mode for mount points to binary, meaning that `open()` opens files in binary mode by default.  This is exactly the behavior we want for `Unix.openfile` (no translation of file contents ever), so we are good.
