### ISSUE TITLE
Wish: Need netmask support in Unix

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#3378]
**Original bug ID:** 3378
**Reporter:** administrator
**Status:** acknowledged
**Resolution:** open
**Priority:** normal
**Severity:** feature
**Category:** otherlibs

## Bug description

Full_Name: Berke Durak
Version: 3.08.2
OS: Debian
Submission from: vol75-1-81-57-79-249.fbx.proxad.net (81.57.79.249)

Hello,

It would be nice to either :

a) have conversion functions int32 <-> inet_addr
b) have functions like
     Unix.get_network_address : ~address:inet_addr -> ~mask:inet_addr ->
inet_addr
     Unix.get_local_address : ~address:inet_addr -> ~mask:inet_addr ->
inet_addr

--
Berke Dural

**Comment by vicuna** [comment]
**Comment author:** anonymous

Not IPv6 compatible :)

**Comment by mshinwell** [comment]
If functions like these are still desired a PR should be submitted.

**Comment by avsm** [comment]
For the record, all of this functionality is now supported by the [ipaddr library](https://github.com/mirage/ocaml-ipaddr/tree/master/lib).
