### ISSUE TITLE
Adding SO_REUSEPORT to Unix lib

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#3512]
**Original bug ID:** 3512
**Reporter:** administrator
**Status:** acknowledged
**Resolution:** open
**Priority:** normal
**Severity:** feature
**Category:** otherlibs

## Bug description

Full_Name: Alon Kama
Version: 3.08-2
OS: OS X (darwin)
Submission from: 85-64-152-87.barak.net.il (85.64.152.87)

On 4.4BSD, In order to use IP Multicasting, the SO_REUSEPORT must be given as a
parameter to setsockopt.  On other Unixes and Linux, SO_REUSEADDR is good
enough.

Ocaml 3.08 supports calling SO_REUSEADDR but not SO_REUSEPORT.  I've manually
changed the code and added this option, and have verified that it works as
necessary.  I'm requesting to add this option to the next release. 

Thanks.

**Comment by vicuna** [comment]
**Comment author:** administrator

> On 4.4BSD, In order to use IP Multicasting, the SO_REUSEPORT must be
> given as a parameter to setsockopt.  On other Unixes and Linux,
> SO_REUSEADDR is good enough.  Ocaml 3.08 supports calling
> SO_REUSEADDR but not SO_REUSEPORT.

Well, SO_REUSEPORT is a BSD-ism that isn't present everywhere.  It is
not in the Single Unix Specification, in particular, and that's the
spec we try to stick to in the OCaml Unix library.

Also, http://www.unixguide.net/network/socketfaq/4.11.shtml quotes
Richard Stevens (someone I tend to listen to) as writing:

  But when binding a multicast address (its main use), SO_REUSEADDR is
  considered identical to SO_REUSEPORT (p. 731, "TCP/IP Illustrated,
  Volume 2").  So for portability of multicasting applications I always
  use SO_REUSEADDR.

So, there might be something non-standard in MacOS X about this.

Regards,

- Xavier Leroy

**Comment by vicuna** [comment]
**Comment author:** administrator

BSDism, not standard enough?  XL, 2005-03-08

**Comment by vicuna** [comment]
**Comment author:** administrator

Hello Xavier, thanks for the response.

You're right that it is a BSDism, though I don't believe that Darwin 
has any plans to change this.  Thus, IP multicast with OCaml is broken 
for that platform.  I have seen that Ruby and Perl have added this 
socket option, as have I for my source-compiled OCaml build.  Can you 
think of an alternative way to set this option without explicitly 
including it in the socket option list?

Thanks,

-Alon.

**Comment by vicuna** [comment]
**Comment author:** @mshinwell

It sounds like SO_REUSEPORT has become more widespread now (2016) so we might consider adding this.

**Comment by vicuna** [comment]
**Comment author:** @xavierleroy

Stevens must be spinning in his grave...  A pull request on Github implementing this feature would be welcome.

**Comment by xavierleroy** [comment]
I'm willing to admit that `SO_REUSEPORT` is more widely available now, with slightly different semantics from `SO_REUSEADDR` (https://lwn.net/Articles/542629/).  A pull request, please?
