### ISSUE TITLE
Bug in the Unix.sleep when used after Graphics.synchronize

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#3666]
**Original bug ID:** 3666
**Reporter:** administrator
**Status:** acknowledged
**Resolution:** open
**Priority:** normal
**Severity:** feature
**Category:** otherlibs
**Monitored by:** @Chris00

## Bug description

Full_Name: Damien Bobillot
Version: 3.08.3
OS: Linux (Redhat & Gentoo)
Submission from: 132.227.81.31 (132.227.81.31)

==== test.ml ====
Graphics.open_graph "";
Graphics.synchronize ();
Printf.printf "cou%!";
Unix.sleep 60;
Printf.printf "cou\n%!";
=============

> ocamlopt.opt -c test unix.cmxa graphics.cmxa test.ml

When running ./test, the program dont wait 1 minute between printf "cou" calls.

This bug doesn't appear in the Mac OS X version.

I've tried to block all signals (with Unix.sigprocmask Unix.SIG_SETMASK
[-1;-2;...;-20;-21]), but it doesn't solve anything.

**Comment by vicuna** [comment]
**Comment author:** administrator

It's not a bug, it's a SIGIO signal that interrupts Unix.sleep (under Unix --
MacOS X restarts the syscall).  Feature wish: a Graphics library that does not
use signals (but e.g. threads).

**Comment by xavierleroy** [comment]
Since 4.07, `Unix.sleep` is resilient to interrupts.  This seems to solve this old issue.
