### ISSUE TITLE
[wishlist] ocamldep -native should list .o files

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#3764]
**Original bug ID:** 3764
**Reporter:** administrator
**Status:** acknowledged
**Resolution:** open
**Priority:** normal
**Severity:** feature
**Category:** tools (ocaml{lex,yacc,dep,debug,...})
**Monitored by:** scientician nogin

## Bug description

Full_Name: Mike Furr
Version: 3.08.3
OS: Linux
Submission from: pcp0010743271pcs.howard01.md.comcast.net (69.243.84.108)

ocamlopt produces both a .cmx file and a .o file, however ocamldep -native
produces a dependency only on the .cmx file.  Some source code changes (like to
constant strings) only show up in the .o files and thus a build system which is
based on md5sums instead of simply timestamps will fail to see any updates.  It
would be nice if dependencies were produced for both .cmx and .o files.

**Comment by vicuna** [comment]
**Comment author:** administrator

DD thinks if we do that, make will build the files twice.

**Comment by vicuna** [comment]
**Comment author:** anonymous

Well, would be a huge hassle to add a "-my-make-is-not-broken" option which would cause ocamldep to emit both .cmx and .o dependencies?

**Comment by mshinwell** [comment]
I doubt this remains a problem with modern build systems (and the proposal did not seem to garner a lot of support 15 years ago either).
