### ISSUE TITLE
PRIVATE: I like the "old" behavior of ocamlc -i

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#3861]
**Original bug ID:** 3861
**Reporter:** administrator
**Status:** acknowledged
**Resolution:** open
**Priority:** normal
**Severity:** feature
**Category:** typing
**Related to:** #6102

## Bug description

Full_Name: John G Malecki
Version: 3.09.0
OS: linux
Submission from: ip-64-139-3-84.sjc.megapath.net (64.139.3.84)

Ocamlc is so fast that I enjoyed watching it spit out the inferred
types every time I compiled a file.  The "new" behavior of -i, while
sensible, is not as sensual as the old behavior.  A compiler flag
allowing simultaneous compilation and inferred type printing could be
a step in the right direction -- toward more fulfilling and thrilling
compilations.

**Comment by mshinwell** [comment]
"Sensual"?
 I'm not sure any further comment on this now-PUBLIC issue would be appropriate, so closing.
