### ISSUE TITLE
ocaml won't compile correctly with icc 9.0 (many standard library calls with end up ending up in Invalid_argument)

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#3917]
**Original bug ID:** 3917
**Reporter:** monniaux
**Status:** acknowledged (set by @damiendoligez on 2005-12-15T12:23:39Z)
**Resolution:** open
**Priority:** normal
**Severity:** feature
**Version:** 3.09.0
**Category:** configure and build/install
**Tags:** patch
**Related to:** #7000
**Monitored by:** jmeber

## Bug description

If cc is icc (Intel's compiler) version 9, config/auto-aux/hasgot will fail to detect most library functions.

The reason is that hasgot tests whether library function f exists by compiling and linking the following template file:

main() {
  f();
}

icc refuses to compile such a file if f is a C standard library function and the number of arguments of f does not correspond to that in the C standard.

The result is that, for instance, HAS_GETTIMEOFDAY will be undefined and the corresponding OCaml function will always raise Invalid_argument.

## Additional information

Such behaviour is apparently correct with respect to the C99 standard, section 7.1.4, as recalled in appendix J.2 (i.e. calls to library functions with incorrect number of arguments have undefined behaviour).

I do not know whether it is possible to stop icc from doing so, I do not see any applicable option (safe perhaps for telling it not to use stdlib).

My personal fix is to test for the library functions using gcc, but it is obviously broken in general.

I suggest the hasgot script should be replaced by a script testing for the functions using appropriate arguments.

## File attachments

- [hasgot-icc.patch](https://gist.githubusercontent.com/vicuna/0cb8e86de3ce65ea2b5668a8f805b8ec/raw/a521b74ceee6fb65d75f1a495eea4eae9be0aa97/hasgot-icc.patch)

**Comment by vicuna** [comment]
**Comment author:** @damiendoligez

This is going to take a lot of work to fix properly.

**Comment by vicuna** [comment]
**Comment author:** monniaux

One dirty practical hack is to configure under gcc, save s.h, configure with icc, and put back the saved s.h.

**Comment by vicuna** [comment]
**Comment author:** @oandrieu

I disagree with david's analysis :) I believe the UB in section 7.1.4 is about incorrect number of arguments in calls to library functions with *variable* number of parameters. Here the problem is simply that there is no declarator at all for the called function.

Adding a (bogus) declarator one is enough to turn the compiler error into a warning.

**Comment by xavierleroy** [comment]
Configuration has been entirely rewritten using GNU autoconf, which has different, more clever ways to test availability of library functions.  Optimistically, I think the present issue goes away, and so I'm closing it.  There might remain other issues with ICC, though.
