### ISSUE TITLE
structural equality for cyclic data structure cannot be interrupted

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#3921]
**Original bug ID:** 3921
**Reporter:** sumii
**Status:** acknowledged (set by @damiendoligez on 2005-12-15T12:20:27Z)
**Resolution:** open
**Priority:** low
**Severity:** feature
**Version:** 3.09.0
**Category:** standard library
**Related to:** #7502 #7524

## Bug description

In the interactive toplevel of ocaml, the "infinite loop"

  let rec x = 1 :: x in x = x

cannot be interrupted by Ctrl-C _despite_ the following paragraph in
Chapter 9 of the manual:

> At any point, the parsing, compilation or evaluation of the current
> phrase can be interrupted by pressing ctrl-C (or, more precisely, by
> sending the INTR signal to the ocaml process). The toplevel then
> immediately returns to the # prompt.

The problem reproduces on any UNIX system to which I have access.

See also: http://caml.inria.fr/pub/ml-archives/caml-list/2005/12/c270081cc11641447bc76557d0f1dabe.en.html

By the way, the behavior of *not* checking == first in = seems to have been adopted in recent versions of ocaml, but its implications are not quite well-documented in the "Changes" file (though the manual seems to be up to date).

**Comment by vicuna** [comment]
**Comment author:** @damiendoligez

Maybe we could poll for signals, but there are subtleties.

**Comment by vicuna** [comment]
**Comment author:** @stedolan

I think a reasonable way to implement polling would be to abort the comparison if a signal is detected (i.e. return from compare_val and free the compare stack if necessary), then handle the signal and restart the comparison from the beginning. Trying to keep the compare stack alive across a signal handler sounds like much more trouble than it's worth.

We'll probably need to fix this for multicore, at least: a single thread diverging shouldn't prevent others from making progress, and we rely on the signal-polling mechanism to synchronise GC.

**Comment by damiendoligez** [comment]
Reopening this, now that we have a PR that will close it...

**Comment by yallop** [comment]
Reclosing now that #12128 is merged.
