### ISSUE TITLE
More detailed specification of the behaviour of Unix.select

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#3942]
**Original bug ID:** 3942
**Reporter:** @mmottl
**Status:** acknowledged (set by @damiendoligez on 2006-01-05T13:19:34Z)
**Resolution:** open
**Priority:** normal
**Severity:** feature
**Version:** 3.09.0
**Category:** standard library
**Monitored by:** @mmottl

## Bug description

According to the C-implementation of "Unix.select", file descriptors in ready sets are returned in the reverse order in which they appeared in the argument lists.  Could this please be explicitly specified as a guarantee in the documentation?

This way the user may be able to find out much more quickly (in O(1)) whether I/O is possible on a particular descriptor in a large set by simply making it the last one in the argument list and checking the first returned descriptor for equivalence.

**Comment by vicuna** [comment]
**Comment author:** @damiendoligez

IMO, if you want to know whether I/O is possible on a particular descriptor, the proper
solution is to call select with only that descriptor.

**Comment by vicuna** [comment]
**Comment author:** @mmottl

The reason why this is not a good solution for us is, because we are implementing a messaging library that should have very low latency and very high throughput (> 100000 msgs/sec).  System calls are extremely expensive and even just one superfluous call more quite noticably lowers throughput.  Unfortunately, Linux still doesn't have a reasonable implementation of asynchronous I/O, which would be the optimum solution for this problem.

**Comment by xavierleroy** [comment]
I'd rather treat the lists returned by `Unix.select` as sets, i.e. not specify anything about the order.

Searching a FD in one of the returned lists takes time O(length) indeed, but constructing the list in the first place (in the stub code for `Unix.select`) also took time O(length), so the overall complexity is unchanged.

Nowadays, applications that need to poll on many file descriptors don't use `select`.  An example of an OCaml library for efficient polling: https://mmzeeman.home.xs4all.nl/ocaml/event-doc/Libevent.html .

**Comment by mmottl** [comment]
Agreed, `select` should be avoided for applications that require a lot of connections now that mature alternatives are available.
