### ISSUE TITLE
Regular expressions should support non-capturing groups

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#3969]
**Original bug ID:** 3969
**Reporter:** rillig
**Status:** acknowledged (set by @damiendoligez on 2006-03-29T14:27:01Z)
**Resolution:** open
**Priority:** normal
**Severity:** feature
**Version:** 3.09.0
**Category:** otherlibs
**Tags:** patch

## Bug description

In Perl, one can write qr"start(?:alt1|alt2|alt3)(.*)end" to compile a regular expression that has only one capturing group, namely the second one. The first "group" is just an alternative. I have written a patch to support this feature in O'Caml too, since I don't know of another way to write the regexp above that is similarly short and readable.

## Additional information

Unfortunately, this patch might change the behavior of some regular expressions that look like foo\(?, because a question mark that appears at the start of a regular expression is taken literally.

## File attachments

- [patch-ca](https://gist.githubusercontent.com/vicuna/54506e3226855c64bdfb928170d4daff/raw/fb891080ea565c0da55f963bcbe407aa69bd7e21/patch-ca)

**Comment by mshinwell** [comment]
@xavierleroy Could you please advise what should be done for feature requests on the `Str` library like this one?

**Comment by xavierleroy** [comment]
I would say that that the Str library is in maintenance mode: bugs will be fixed, but it's probably not getting new features.  This, plus the fact that the proposed feature is not completely backward-compatible, suggest that we should close this PR.
