### ISSUE TITLE
Allocating a bigarray from C

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#3997]
**Original bug ID:** 3997
**Reporter:** sayan
**Status:** acknowledged (set by @damiendoligez on 2006-08-29T15:45:44Z)
**Resolution:** open
**Priority:** normal
**Severity:** feature
**Version:** 3.09.1
**Category:** otherlibs
**Tags:** patch
**Monitored by:** @whitequark @Chris00

## Bug description

Please add the following comment to the bigarray documentation: 
/* [alloc_bigarray] will allocate a new bigarray object in the heap.
   If [data] is NULL, the memory for the contents is also allocated
   (with [malloc]) by [alloc_bigarray].
   [data] cannot point into the Caml heap.
   [dim] may point into an object in the Caml heap.
*/

## Additional information

This is a simple and GC-friendly way to allocate memory for a bigarray structure directly within C instead of calling Bigarray.genarray.create in Caml.

**Comment by xavierleroy** [comment]
`caml_ba_alloc` is documented in the reference manual, section 20.10: https://caml.inria.fr/pub/docs/manual-ocaml/intfc.html#sec468 . I think that's enough documentation.
