### ISSUE TITLE
Error message Cannot_open_dll should contain list of  searched files

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#4060]
**Original bug ID:** 4060
**Reporter:** Christoph Bauer
**Status:** acknowledged (set by @damiendoligez on 2006-08-29T15:05:17Z)
**Resolution:** open
**Priority:** normal
**Severity:** feature
**Version:** 3.09.2
**Category:** dynlink and natdynlink
**Tags:** patch

## Bug description

on my windows system i get this message when a
dll is missing:

Error on dynamically loaded library: Das angegebene Modul wurde nicht gefunden.
The list of searched files could be useful, e.g. this patch for bytelink.ml

+      raise(Error(Cannot_open_dll ((String.concat ", " sharedobjs) ^ ": " ^ reason)))
-      raise(Error(Cannot_open_dll reason))

**Comment by nojb** [comment]
The filename that could not be opened is shown in the error message since b0041ea9631ec5938bd7931128be484bd1a00bd3, so closing!
