### ISSUE TITLE
Small tweak for some numeric functions in Pervasives

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#4070]
**Original bug ID:** 4070
**Reporter:** @mmottl
**Status:** acknowledged (set by @damiendoligez on 2006-08-29T14:59:36Z)
**Resolution:** open
**Priority:** normal
**Severity:** feature
**Version:** 3.08.4
**Target version:** undecided
**Category:** runtime system and C interface
**Tags:** patch
**Monitored by:** @jmeber @hcarty @Chris00 @mmottl

## Bug description

The functions caml_frexp_float and caml_modf_float in byterun/floats.c could be implemented slightly more efficiently:

Both protect parameter "f", which is not necessary, because it is converted to a C-double before the next allocation anyway, and is not needed afterwards.  Instead of "caml_alloc_tuple" it would be more efficient to use "Alloc_small", which would avoid unnecessary function calls.  Finally, local value "res" does not need to be protected, because there are no allocations after it has been created.

Here are the alternative functions (untested):

CAMLprim value caml_frexp_float(value f)
{
  CAMLparam0 ();
  CAMLlocal1 (mantissa);
  int exponent;
  value res;

  mantissa = caml_copy_double(frexp (Double_val(f), &exponent));
  Alloc_small(res, 2, 0);
  Field(res, 0) = mantissa;
  Field(res, 1) = Val_int(exponent);
  CAMLreturn (res);
}

CAMLprim value caml_modf_float(value f)
{
#if __SC__
  _float_eval frem;       /* Problem with Apple's <math.h> */
#else
  double frem;
#endif
  CAMLparam0 ();
  CAMLlocal2 (quo, rem);
  value res;

  quo = caml_copy_double(modf (Double_val(f), &frem));
  rem = caml_copy_double(frem);
  Alloc_small(res, 2, 0);
  Field(res, 0) = quo;
  Field(res, 1) = rem;
  CAMLreturn (res);
}

**Comment by vicuna** [comment]
**Comment author:** @damiendoligez

Needs careful review and testing.

**Comment by damiendoligez** [comment]
Do we really care all that much about the performance of these function? If so, will someone take this code and update it, then submit a PR?

cc @jmeber @hcarty @Chris00 @mmottl
