### ISSUE TITLE
Str.split is not tail recursive

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#4100]
**Original bug ID:** 4100
**Reporter:** pvernaza
**Status:** acknowledged (set by @damiendoligez on 2006-09-11T09:20:58Z)
**Resolution:** open
**Priority:** normal
**Severity:** feature
**Version:** 3.09.2
**Category:** otherlibs

## Bug description

It would be useful if Str.split were documented as not being tail recursive, since it can lead to mysterious failures when parsing large strings.  Furthermore, perhaps a tail-recursive Str.rev_split could be added?

**Comment by xavierleroy** [comment]
This seems to have been fixed in commit 7e9f606dee71af1127d0f6daa74913f60087a6b4 .
