### ISSUE TITLE
Condition.timedwait missing in threads library

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#4104]
**Original bug ID:** 4104
**Reporter:** @mmottl
**Status:** acknowledged (set by @damiendoligez on 2006-09-11T09:18:14Z)
**Resolution:** open
**Priority:** normal
**Severity:** feature
**Version:** 3.09.3
**Category:** otherlibs
**Tags:** patch
**Monitored by:** @mmottl

## Bug description

The POSIX-standard supports the function pthread_cond_timedwait, which would be very useful for many systems applications.  The POSIX-threads version is trivial to write (took me only a few minutes) so it would be great if it could be made part of the standard distribution.

I don't know how hard it would be to implement for byte code threads, but most people probably don't care much about the latter anyway so one could just leave it unimplemented for those if it's too time consuming to do right now.

## Additional information

The function interface (the function returns false on timeouts):

  val timedwait : Condition.t -> Mutex.t -> float -> bool

Here is the C-stub:

  CAMLprim value caml_condition_timedwait(value v_cnd, value v_mtx, value v_timeo)
  {
    CAMLparam2(v_cnd, v_mtx);
      int ret;
      pthread_cond_t *cnd = Condition_val(v_cnd);
      pthread_mutex_t *mtx = Mutex_val(v_mtx);
      double timeo = Double_val(v_timeo);
      struct timespec ts;
      ts.tv_sec = timeo;
      ts.tv_nsec = (timeo - ts.tv_sec) * 1e9;
      enter_blocking_section();
        ret = pthread_cond_timedwait(cnd, mtx, &ts);
      leave_blocking_section();
      if (ret == ETIMEDOUT) CAMLreturn(Val_false);
      caml_pthread_check(ret, "Condition.timedwait");
    CAMLreturn(Val_true);
  }

Note that the timeout parameter is an absolute time for good reason (see the man page for this function to know why) so the OCaml-interface should keep this specification.

**Comment by xavierleroy** [comment]
The main reason against `Condition.timedwait` was that it was difficult to implement in the VM threads library.  Since the VM threads library is now gone, we can reconsider the addition of `Condition.timedwait`.  If anyone cares enough to submit a pull request...

**Comment by rixed** [comment]
I would be happy to submit a PR filling the void for Unix but I wouldn't be able to implement it for windows.
Would that still be useful?

**Comment by xavierleroy** [comment]
The Windows implementation doesn't look much more difficult than the Unix implementation, so I'd rather have both at the same time.
