### ISSUE TITLE
man page for ocamlbrowser

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#4270]
**Original bug ID:** 4270
**Reporter:** eda
**Assigned to:** @garrigue
**Status:** assigned (set by @xavierleroy on 2007-11-10T14:35:00Z)
**Resolution:** open
**Priority:** normal
**Severity:** feature
**Version:** 3.09.2
**Category:** documentation
**Tags:** patch

## Bug description

Written a man page for ocamlbrowser according to The Objective Caml user's manual.

## File attachments

- [ocamlbrowser.1](https://gist.githubusercontent.com/vicuna/e4b33f9381dd5d44cf2aec69749739c5/raw/99e4a8a2bd90f8074c05d9604ce64d98aeefd3a0/ocamlbrowser.1)

**Comment by xavierleroy** [comment]
ocamlbrowser is now developed separately, along with LablTK: https://forge.ocamlcore.org/projects/labltk/
