### ISSUE TITLE
ocamldoc -css-style doesn't seem to work.

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#4430]
**Original bug ID:** 4430
**Reporter:** @dbuenzli
**Assigned to:** @zoggy
**Status:** confirmed (set by @damiendoligez on 2012-07-11T14:04:25Z)
**Resolution:** reopened
**Priority:** normal
**Severity:** feature
**Version:** 3.10.0
**Category:** ocamldoc

## Bug description

ocamldoc when invoked with -css-style doesn't generate any css file.

**Comment by vicuna** [comment]
**Comment author:** @dbuenzli

Sorry, replace ocamlbuild by ocamldoc.

[ed: done]

**Comment by vicuna** [comment]
**Comment author:** @zoggy

This option does not generate a css file, but is used to indicate the url of the style sheet to reference in the html files generated by ocamldoc. A css file is generated in the output directory, called style.css. This file is always generated, except if it already exists.

**Comment by vicuna** [comment]
**Comment author:** @dbuenzli

Hello Maxence,

Sorry, I didn't understand. But then I suggest you clarify the documentation since it says :

-css-style filename
Use filename as the Cascading Style Sheet file.

So I thought filename would be used to generate style.css. Maybe :

-css-style uri
Use uri as the Cascading Style Sheet file of generated files.

However I think something as I understood is needed because the current behaviour of not generating a file only if style.css is already present in the directory does not play nicely with ocamlbuild which generates everything in a directory that can be safely erased. Thus if you want to use a custom style file you need to copy your style.css after generation in the documentation directory (i.e. understand too much of the underdocumented ocamlbuild). An easy way of having a custom style while using ocamlbuild .odocl would be nice. But I don't know if it is a matter of changing ocamlbuild or ocamldoc.

Best,

Daniel

P.S.
Just to clarify, you say a style.css is always generated unless it already exists, to which I add or if -css-style is not used.

**Comment by vicuna** [comment]
**Comment author:** @dbuenzli

In my preceding message _not used_ -> used.

**Comment by vicuna** [comment]
**Comment author:** @damiendoligez

Fix the documentation, then reclassify this as a feature wish.

**Comment by vicuna** [comment]
**Comment author:** @zoggy

Documentation fixed in revision 12955.

**Comment by dbuenzli** [comment]
This can be closed.

**Comment by vicuna** [comment]
Thanks!
