### ISSUE TITLE
support O_APPEND in Unix.openfile for Win32

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#4431]
**Original bug ID:** 4431
**Reporter:** @xavierleroy
**Status:** acknowledged (set by @xavierleroy on 2017-02-16T09:56:14Z)
**Resolution:** open
**Priority:** normal
**Severity:** feature
**Version:** 3.10.0
**Target version:** later
**Category:** otherlibs
**Tags:** junior_job
**Related to:** #4397
**Monitored by:** @dbuenzli

## Bug description

The O_APPEND flag is currently ignored by the Win32 implementation of Unix.openfile.  The MSDN page for CreateFile suggests a cheap way to implement the O_APPEND behavior.  Consider updating otherlibs/win32unix/open.c accordingly.

**Comment by vicuna** [comment]
**Comment author:** @xavierleroy

I'm "un-assigning" this PR from myself as I've been sleeping on it for too long.  Anyone who cares enough about this tiny feature is welcome to handle it: it looks pretty easy.

**Comment by xavierleroy** [comment]
13 years later it is safe to say that nobody cares about this little feature.  So, as the original reporter, I'm closing it.
