### ISSUE TITLE
Function for determining mmap status missing

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#4464]
**Original bug ID:** 4464
**Reporter:** @mmottl
**Status:** acknowledged (set by @damiendoligez on 2007-12-06T14:35:02Z)
**Resolution:** open
**Priority:** normal
**Severity:** feature
**Version:** 3.11+dev
**Category:** otherlibs
**Monitored by:** @Chris00 @mmottl

## Bug description

It is currently not possible to determine from within OCaml whether a bigarray is memory-mapped or not.  Could you please add such a function to the bigarray module? - Thanks!

**Comment by mshinwell** [comment]
It doesn't look like anyone has had time since 2007 to implement this, so I'm going to close the issue.  @mmottl If you would still like this functionality, perhaps you could submit a PR?  (Note that the bigarray code was refactored recently and part of it is now in the stdlib.)

**Comment by mmottl** [comment]
@mshinwell This is apparently an ancient request on behalf of Jane Street.  I believe it was intended to determine whether operations on passed bigarrays could conceivably block for a long time.  I personally don’t need it.
