### ISSUE TITLE
Request for unsigned in32 support in Bigarray module

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#4496]
**Original bug ID:** 4496
**Reporter:** @hcarty
**Status:** acknowledged (set by @damiendoligez on 2008-02-19T13:52:12Z)
**Resolution:** open
**Priority:** normal
**Severity:** feature
**Version:** 3.11+dev
**Category:** otherlibs

## Bug description

This is a request that unsigned 32bit integers be added to the supported data types in the Bigarray module.

I am willing to (try to) write a patch for this if it would be accepted.

**Comment by mshinwell** [comment]
@hcarty If you are still interested in this support one decade later, please propose a PR (although bear in mind we don't currently have specific types for unsigned integers on the OCaml side).
