### ISSUE TITLE
Better location format for reporting errors in ocamldoc

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#4518]
**Original bug ID:** 4518
**Reporter:** @dbuenzli
**Status:** acknowledged (set by @damiendoligez on 2008-03-07T12:36:25Z)
**Resolution:** open
**Priority:** normal
**Severity:** feature
**Category:** ocamldoc
**Tags:** junior_job
**Related to:** #6069

## Bug description

Related to ocaml/ocaml#4515 the format used by ocamldoc to report errors does not allow to use emacs' next error to directly jump at the location. E.g. :

/Users/dbuenzli/devel/xmlm/src/xmlm.mli : Syntax error in text:
Same as {!input_tree} but reads a complete {{:#TYPEsignal}valid}  
    sequence of signals. 

    {b Raises {!Error} on input errors.
line 3, character 39:
    {b Raises {!Error} on input errors.

should be something like :

File "src/xmlm.mli", line 3, character 39:
...

Thanks,

Daniel

**Comment by vicuna** [comment]
**Comment author:** lebedev

I've started working and this and I'm not sure if warnings should have the same location information header? Any suggestions?

**Comment by vicuna** [comment]
**Comment author:** lebedev

This has been merged as #29.

**Comment by dbuenzli** [comment]
This can be closed.

**Comment by vicuna** [comment]
Thanks!
