### ISSUE TITLE
Patch implementing inter-thread shared variable without creating a new thread.

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#4554]
**Original bug ID:** 4554
**Reporter:** ogasawara
**Status:** acknowledged (set by @damiendoligez on 2008-09-23T17:41:07Z)
**Resolution:** open
**Priority:** normal
**Severity:** feature
**Version:** 3.10.2
**Category:** otherlibs
**Tags:** patch

## Bug description

Hello,
First of all, thanks for the excellent job.

I would like to suggest a new feature about Event module.

Event module provides CML style synchronous communication methods, 
but does not support shared variables like ivar, mvar. 
These variables are REALLY necessary for multi-thread programming.

So, I have implemented shared variable module called 'Cell'.

1. With 'Cell', we can make ivar, mvar, thread-safe queue, broadcast channel, 
 and timeout event easily.

2. 'Cell' dose not create a new thread. This is IMPORTANT.  It means the shared 
variable is GC target. If the variable has a thread, it is impossible to garbage 
collect automatically.
**But, to make such shared variable with Event module, Cell module is inside of 
Event module because implementation detail of Event.event type is needed.**

Type of Cell module inside Event module is as follow:
```ocaml
module type Cell = sig
  type 'a t
  val make : unit -> 'a t
  val init_make : 'a -> 'a t
  val put : 'a t -> 'a -> unit Event.event
  val take : 'a t -> 'a Event.event
  val read : 'a t -> 'a Event.event
  val overwrite : 'a t -> ('a -> 'a) -> unit Event.event
end
```
I'm sending a patch to Event module with some sample code for testing.

Thanks,

   ogasawara

## File attachments

- [event_module_patch.tar.gz](https://gist.githubusercontent.com/vicuna/9492e39c351a1fc60c8bf2e286830f0b/raw/3af33972863b698a8cfbdc6a30522fa4853f53c8/event_module_patch.tar.gz)
- [event_module_patch_2.tar.gz](https://gist.githubusercontent.com/vicuna/9492e39c351a1fc60c8bf2e286830f0b/raw/0bc901033aff827e789cd8d05f9254c176e43dfd/event_module_patch_2.tar.gz)

**Comment by vicuna** [comment]
**Comment author:** ogasawara

I found that first version patch had several bugs.
I have made more tested version and uploaded.

**Comment by mshinwell** [comment]
@kayceesrk Presumably multicore will provide other methods of dealing with such problems, so it would be appropriate to close this?

**Comment by kayceesrk** [comment]
Yes. Domainslib already provides [channels](https://github.com/ocaml-multicore/domainslib/blob/master/lib/chan.mli) (without selective communication a la CML). These features do not (and should not) need to live in the compiler distribution. Hence, it is appropriate to close this one.
