### ISSUE TITLE
Object inheritance in recursive modules

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#4559]
**Original bug ID:** 4559
**Reporter:** Radzevich Belevich
**Status:** acknowledged (set by @xavierleroy on 2012-08-06T16:26:43Z)
**Resolution:** open
**Priority:** normal
**Severity:** feature
**Version:** 3.10.1
**Target version:** later
**Category:** typing
**Tags:** recmod

## Bug description

Ancestor's class methods defined in recursive module are lost during compilation

## File attachments

- [test.ml](https://gist.githubusercontent.com/vicuna/7691c51591d6de971356b6b913c9c16a/raw/8374c2b3a9dfda36dbdbd33ba5f68a807b9e065c/test.ml)

**Comment by vicuna** [comment]
**Comment author:** @xavierleroy

I've been sleeping on these PR for too long, and still have no idea how to address them.  Unassigning them from myself.

**Comment by lpw25** [comment]
Same as #6491
