### ISSUE TITLE
Big_Int random numbers

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#4652]
**Original bug ID:** 4652
**Reporter:** hugo
**Status:** acknowledged (set by @damiendoligez on 2008-12-03T13:12:55Z)
**Resolution:** open
**Priority:** normal
**Severity:** feature
**Version:** 3.10.2
**Category:** otherlibs
**Related to:** #4641

## Bug description

A recent request (0004641) was filed asking for bit twiddling functions for the
Big_Int in the Num library. In the same vein I would like to ask if random number
generation may also be added the Num library, specifically for the integers.

## Additional information

I am working on a simulator to test a machine learning algorithm and require
the use of arbitrary precision integers and the generation of random
values of such integers. Currently to do this I must use the GMP library 
(http://gmplib.org/) which I could otherwise avoid.

**Comment by nojb** [comment]
The `num` library has been split off from the compiler codebase: https://github.com/ocaml/num
This issue has been submitted there: https://github.com/ocaml/num/issues/12
