### ISSUE TITLE
Patch to add "Rest" option to ocaml toplevel

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#4671]
**Original bug ID:** 4671
**Reporter:** mwahab
**Assigned to:** @diml
**Status:** feedback (set by @diml on 2017-01-05T13:40:32Z)
**Resolution:** open
**Priority:** normal
**Severity:** feature
**Version:** 3.11.0+beta
**Category:** toplevel
**Tags:** patch
**Monitored by:** @whitequark @glondu

## Bug description

It would be useful to be able to pass command line options to
libraries linked into the ocaml toplevel. Attached is a patch to add
the Arg.Rest option '--' to the ocaml toplevel and function
Toploop.get_cli_strings to get the strings after the -- option.

## Additional information

Example usage:
> ocaml -I +camlp4 -- other options
# Toploop.get_cli_strings();;
- : string list = ["other"; "options"]

Patch is against CVS head

## File attachments

- [cli_args.tar.gz](https://gist.githubusercontent.com/vicuna/0861e092432af01aeb3cd678ee30e008/raw/4760b83475ed5964158e2b7e41ada055fdee478e/cli_args.tar.gz)

**Comment by vicuna** [comment]
**Comment author:** @diml

Do you have a use case for this? If all libraries see the same command line, it might not be clear how to dispatch arguments. Another way would be to allow libraries to register new command line arguments for the toplevel.

**Comment by whitequark** [comment]
I still think this would be useful for scripting in OCaml.

**Comment by gasche** [comment]
Note: there already is a different mechanism for this when calling ocaml with a "script file": only the arguments after the script file will be part of `Sys.argv`.

```
$ echo Array.iter print_endline Sys.argv > test.ml

$ ocaml -I ~
        OCaml version 4.09.0
# #use "test.ml";;
/home/gasche/.opam/4.09.0/bin/ocaml
-I
/home/gasche
- : unit = ()

$ ocaml -I ~ test.ml foo bar
test.ml
foo
bar

$ cat test.ml | ocaml -I ~ "" foo bar

foo
bar

$ cat test.ml | ocaml -I ~ -stdin foo bar
-stdin
foo
bar
```

Given this facility, I am a bit hesitant to add a new mechanism as suggested in this feature wish.

**Comment by xavierleroy** [comment]
Yes, the feature wish is about interactive use, as far as I understand; scripting is already OK.

**Comment by gasche** [comment]
Maybe we could follow the suggestion of allowing `-- <extra args>`, and then use the same (slightly hackish) behavior as for scripting, namely overriding `Sys.argv`. This is close to what we are already doing, and it is backward-compatible: invocations without `--` still see all arguments as today.

**Comment by whitequark** [comment]
That sounds very nice.
