### ISSUE TITLE
Better alpha support

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#4763]
**Original bug ID:** 4763
**Reporter:** @Chris00
**Status:** acknowledged (set by @damiendoligez on 2009-04-29T13:45:44Z)
**Resolution:** open
**Priority:** normal
**Severity:** feature
**Version:** 3.11.0+beta
**Category:** otherlibs
**Monitored by:** @Chris00

## Bug description

At the moment, the Graphics module only supports a fully transparent color.  It would be nice if the unused 7 bits (on a 32 bit platform) of any color were used to hold transparency information.  One could even provide a full (8 bits) alpha channel on 64 bits platforms in a platform independent way if one requires the colors to be declared through

val rgba : int -> int -> int -> int -> color

Also, an interface with int32 bigarrays would be nice for 64 bits platforms where images take up twice as much space as they really need.

**Comment by stedolan** [comment]
The Graphics module is a thin layer around the X11 / Windows GDI drawing primitives, which as far as I know don't support alpha blending. For drawing with transparency and other features, [cairo](https://www.cairographics.org/cairo-ocaml/) is a better bet.

**Comment by Chris00** [comment]
See also [cairo2](https://github.com/Chris00/ocaml-cairo) with a more structured interface.
