### ISSUE TITLE
Support for look-around in regular expressions

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#4872]
**Original bug ID:** 4872
**Reporter:** elfring
**Status:** acknowledged (set by @damiendoligez on 2011-05-31T14:35:46Z)
**Resolution:** open
**Priority:** normal
**Severity:** feature
**Version:** 3.11.1
**Category:** otherlibs

## Bug description

The module Str provides some functionality for regular expressions.
http://caml.inria.fr/pub/docs/manual-ocaml/libref/Str.html

Would you like to support improved matching capabilities like look-around (look-behind/ahead)?

## Additional information

References:
- http://www.regular-expressions.info/lookaround.html

- Article "Power Regexps, Part II" by Simon Cozens
  http://www.perl.com/pub/a/2003/07/01/regexps.html

**Comment by nojb** [comment]
The `str` library has many shortcomings (global state, clunky API, etc) and it is highly unlikely it will be developed further (in fact it will be split off the compiler distribution when it is feasible).
