### ISSUE TITLE
Requesting unsigned types

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#4908]
**Original bug ID:** 4908
**Reporter:** goswin
**Status:** acknowledged (set by @damiendoligez on 2011-05-31T14:41:26Z)
**Resolution:** open
**Priority:** normal
**Severity:** feature
**Category:** standard library
**Duplicate of:** #7280
**Monitored by:** @gasche @yallop @hcarty "Richard Jones"

## Bug description

It would be nice if ocaml had types uint, uint32 and uin64. The later two should be trivial to add. The uint is more tricky but just an UInt module (like Int32) with compiler primitives would suffice for a start.

**Comment by dbuenzli** [comment]
@yallop proposed a design in PR https://github.com/ocaml/ocaml/pull/1201 however @xavierleroy made it [clear](https://github.com/ocaml/ocaml/pull/1201#issuecomment-311363619) he's against this.

Instead unsigned operation on Int32, Int64 and nativeint where added by @nojb in https://github.com/ocaml/ocaml/pull/1458 and will be available starting from 4.08. 

I think we can close this.

**Comment by xavierleroy** [comment]
Closing as suggested.
