### ISSUE TITLE
ocamldep should be able to compute dependencies of *.mllib files

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#4931]
**Original bug ID:** 4931
**Reporter:** @glondu
**Status:** acknowledged (set by @damiendoligez on 2009-12-08T16:30:55Z)
**Resolution:** open
**Priority:** normal
**Severity:** feature
**Version:** 3.11.1
**Category:** tools (ocaml{lex,yacc,dep,debug,...})

## Bug description

Hello,

*.mllib files turn out to be useful even in Makefiles. The Coq (Makefile-based) build system has been simplified using them and currently, coqdep is able to compute dependencies for such files. For example:

glondu@aspirine:/tmp/foo/z$ ls
a.ml  b.ml  lib.mllib
glondu@aspirine:/tmp/foo/z$ cat lib.mllib 
A
B
glondu@aspirine:/tmp/foo/z$ coqdep -I . -c lib.mllib
lib.cma: a.cmo b.cmo
lib.cmxa: a.cmx b.cmx

Then, one can use an implicit rule to build %.cma out of %.mllib...

It would be nice to have this feature directly in ocamldep.

Cheers,

-- 
Stéphane

**Comment by ejgallego** [comment]
Not sure if this is still useful for others, in Coq we are close to using Dune and this is not needed anymore.

**Comment by nojb** [comment]
No other activity for close to 10 years, I think this can be closed.
