### ISSUE TITLE
ocamldoc lost "with type" in "include ... with type ..."

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#5002]
**Original bug ID:** 5002
**Reporter:** Julien Signoles
**Assigned to:** @zoggy
**Status:** assigned (set by Julien Signoles on 2010-03-11T12:17:10Z)
**Resolution:** open
**Priority:** normal
**Severity:** minor
**Version:** 3.11.1
**Category:** ocamldoc
**Monitored by:** @Yakobowski

## Bug description

Hello,

Consider:
=== a.ml ===
module type X = sig type t end
module type Y = sig include X with type t = int end
============

$ ocamldoc -html a.ml

The file A.Y.html is incorrect since the "with type" part is lost:
============
module type Y = sig .. end

include A.X
============

**Comment by vicuna** [comment]
**Comment author:** @Armael

An other manifestation of the problem (after an include, ocamldoc only tries to print the name of the signature that is included) is when including an anonymous signature:

```
include sig type t = int end
```

is outputted as

```
include ??
```

I tried a bit to find a fix for that, but failed... :(. I would be quite happy to see this issue fixed. It's a tad annoying when one has an interface with "include"s; then there is no way to get correct documentation for it.

**Comment by Armael** [comment]
I suggest that we close the issue, as this is unlikely to be solved in ocamldoc, is solved in odoc, and ocamldoc is in progress of being replaced by odoc anyway.
