### ISSUE TITLE
Lowlevel interface to Digest and Bigarray support

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#5005]
**Original bug ID:** 5005
**Reporter:** goswin
**Status:** acknowledged (set by @damiendoligez on 2011-06-01T15:08:48Z)
**Resolution:** open
**Priority:** normal
**Severity:** feature
**Version:** 3.11.2
**Category:** otherlibs
**Tags:** patch
**Monitored by:** @gasche tgazagna @glondu @Chris00

## Bug description

Hi,

the attached patches add a more lowlevel interface to the Digest module allowing the creation of a context and updating the context with any number of strings before finaling it to create the overall digest. It further adds a Bigarray.Array1.Digest module that allows computing the digest of an array or updating a context with an array. The more lowelevel interface allows creating a digest from e.g. a rope, which internally is a sequenze of strings.

As a special bonus the digesting of a bigarray is done with caml_enter/leave_blocking_section() and can run concurrently with other threads to take advantage of multiple cores. It might be wise to add a size check and only go into a blocking section if the array is larger than for example Page_size.

Unfortunately the same can't be done for strings as the GC can move them while being digested in a blocking section. So digesting strings can not take advantage of multiple cores.

MfG
   Goswin

## Additional information

The patch is split into 2 parts. The changes to md5.c/md5.h must be applied first and the compiler must be bootstraped to get the new functions listed as primitives. Only then, in a second pass, can the remaining patch be build.

## File attachments

- [0008-md5-rewrite.patch](https://gist.githubusercontent.com/vicuna/0ad7102c962982a6e7428026be6dfc1d/raw/70654295ee6149c0a0be98acbfaa1432e09e6cfa/0008-md5-rewrite.patch)
- [0009-digest-rewrite.patch](https://gist.githubusercontent.com/vicuna/0ad7102c962982a6e7428026be6dfc1d/raw/447ac6efd0803088abd0f423a68300098dbc869c/0009-digest-rewrite.patch)

**Comment by vicuna** [comment]
**Comment author:** @whitequark

I have to mention that "The digests are of cryptographic quality: it is very hard, given a digest, to forge a string having that digest." is no longer true. It is trivial to forge an md5 digest, e.g. see http://fixunix.com/linux/494226-md5-collisions-made-easy.html.

I want to point out that improving the Digest module would invite new usage of it, whereas the right thing to do is to use SHA256 or newer hash functions from cryptokit or a similar external package.

**Comment by xavierleroy** [comment]
I'll update the documentation of the Digest module.  I agree with @whitequark that it is best to leave the Digest module as it is today and turn to external libraries that provide cryptographically-strong hash functions.  For example, [nocrypto](https://github.com/mirleft/ocaml-nocrypto) works over `Cstruct.t`, which are essentially bigarrays of bytes.  This could be a good match for the use case proposed in this issue.

**Comment by xavierleroy** [comment]
The actively-maintained version of nocrypto is part of Mirage: https://mirage.github.io/mirage-crypto/doc/mirage-crypto/Mirage_crypto/index.html
