### ISSUE TITLE
improve type checking of applicative functors

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#5058]
**Original bug ID:** 5058
**Reporter:** sweeks
**Status:** acknowledged (set by @mshinwell on 2010-05-24T08:16:19Z)
**Resolution:** open
**Priority:** normal
**Severity:** feature
**Target version:** later
**Category:** typing
**Related to:** #3476 #6467
**Monitored by:** @ygrek

## Bug description

Issue #3476 identified a weakness in the type checking of applicative functors.  It was marked as "won't fix" back in 2006.  However, in March 2007, on the OCaml list, Derek Dreyer had a proposed improvement to the type system that would fix some such problems, and which Xavier thought was both sound and not too hard to implement.

Here's the simplest example I know of the problem.

module F (M : sig end) : sig type t end = struct type t = int end
module T = struct
  module M = struct end
  include F(M)
end
include T
let f (x : t) : T.t = x (* type error -- OCaml doesn't know that [t = T.t] *)

This problem does crop up from time to time, and it would save repeated rediscovery and workarounds if it got fixed.  I am creating this issue to see if the solution could be reconsidered.  Thanks.

Here's what Xavier said back in March 2007.

> Very interesting.  So now, looking back at Xavier's POPL'95 paper on
> applicative functors, I see what he means by saying it's a fundamental
> problem with how applicative functors work in OCaml.  I.e. it's not
> just a bug in the typechecker, but in the type system in the original
> paper.  In particular, the definition of signature strengthening on
> page 7 of that paper includes the following case:
>
> (module x_i : M; S)/p =
>    module x_i : (M/p.x); S/p
>
> But I believe this is a mistake, and instead of S/p it should be
>  (S{x_i <- p.x})/p

Thanks for this very interesting suggestion.

As Derek knows, there are two deep limitations in the syntactic
type system for modules used in OCaml, namely

1) at most one type equality can be recorded per type declaration, and
2) structure equality is not tracked, therefore the types F(M).t and F(N).t
  (assuming t is abstract in F's result signature) are distinct even if
  N is an alias for M.

I managed to convince myself that the problems with applicative functors
discussed e.g. in #3476 cannot be solved without lifting one of
these limitations, which is something I don't know how to do (neither
theoretically nor implementation-wise).

Derek's suggestion seems to prove me wrong.  The two definitions of
signature strengthening (the one in my papers, used in OCaml, and
Derek's proposal) appear to have the same expressive power in a system
with generative functors, but Derek's definition is definitely
stronger in conjunction with applicative functors.

> In other words, first replace references to x_i (esp. in functor
> applications in types) inside S with references to p.x, and then
> proceed with selfification as usual.  Is there some reason this would
> not work or would be difficult to implement?

Difficult to implement: I don't think so.  Would not work: some formal
soundness argument would be nice of course :-), but there is a
strong intuition that at the point of the ";" in the equation above,
the two paths "x_i" and "p.x" carry the same amount of typing information,
so replacing the latter by the former appears sound.

**Comment by vicuna** [comment]
**Comment author:** @xavierleroy

For the record: I implemented Dreyer's alternate strengthening algorithm at that time, but it turned out to be incomparable with the current strengthening algorithm: some examples that fail today are accepted with the alternate algo, but some examples that typecheck today (IIRC, the ocamlgraph library) are rejected.  

In the particular example given, the best thing to do is perhaps to turn applicative functors off entirely, using the -no-app-funct option that is being introduced in 3.12.

**Comment by vicuna** [comment]
**Comment author:** @lpw25

This example now works in 4.02.1 because of module aliases.

**Comment by Octachron** [comment]
Since the example works (due to module aliases lifting the restriction 2), I am closing the issue. See #9566 for adding the corresponding examples to the testsuite.
