### ISSUE TITLE
bool Bigarray

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#5187]
**Original bug ID:** 5187
**Reporter:** @Chris00
**Status:** acknowledged (set by @damiendoligez on 2011-05-17T15:36:14Z)
**Resolution:** open
**Priority:** normal
**Severity:** feature
**Version:** 3.13.0+dev
**Category:** otherlibs
**Monitored by:** @glondu thelema @hcarty @dbuenzli @Chris00

## Bug description

It would be nice to have a bigarray of booleans, using a single bit per bool.

**Comment by mshinwell** [comment]
Many things would indeed be nice, of which this is perhaps one, but given no other interest has been expressed in this for nearly ten years I am closing the issue.
