### ISSUE TITLE
Make unix.{localtime,gmtime} use reentrant c calls

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#5193]
**Original bug ID:** 5193
**Reporter:** till
**Status:** acknowledged (set by @damiendoligez on 2010-12-14T15:10:34Z)
**Resolution:** open
**Priority:** normal
**Severity:** feature
**Target version:** later
**Category:** otherlibs
**Tags:** patch

## Bug description

Attached is a patch to make it call out to {localtime,gmtime}_r which are the reentrant versions of these calls.

## File attachments

- [reentrant.patch](https://gist.githubusercontent.com/vicuna/083d2d9afd9a26dfca7abf95f4480035/raw/cfe11778aa4b0c7098f4d85033f0f42137f02463/reentrant.patch)

**Comment by vicuna** [comment]
**Comment author:** till

oops the category should have been the compiler. Please reassign.

**Comment by vicuna** [comment]
**Comment author:** @xavierleroy

This change has been proposed before, but I am reluctant to implement it, for several reasons:

- gmtime_r() is "less standard" than gmtime(), the latter being in ISO C.
- All C libraries worth their salt implement gmtime() using thread-local storage, and are therefore thread-safe.
- Two gmtime() calls from Caml cannot execute concurrently because of the global lock, so the only risk of a race is with a gmtime() executing concurrently in a C thread.

All in all, I'd rather not change the current code until the problem above manifests itself in practice.

**Comment by yallop** [comment]
See also: #3784.
