### ISSUE TITLE
Apply const int optimizations to const natint

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#5195]
**Original bug ID:** 5195
**Reporter:** meurer
**Status:** feedback (set by @mshinwell on 2016-12-07T13:45:23Z)
**Resolution:** open
**Priority:** normal
**Severity:** feature
**Version:** 3.12.1+dev
**Category:** back end (clambda to assembly)
**Tags:** patch
**Monitored by:** @gasche @Chris00

## Bug description

This patch alters selectgen.ml and amd64/selection.ml to apply the same optimizations to operations with Cconst_natint that are already applied to operations with Cconst_int. It's really straight-forward. Adds a new virtual method is_immediate_natint to the selector class, which will have to be added to the other backends as well.

## File attachments

- [ocamlopt-natint.patch](https://gist.githubusercontent.com/vicuna/0589eb75090243707a187f1b403ef462/raw/5f3b94aa4cec0f814473ec4aa14655e83b13d389/ocamlopt-natint.patch)

**Comment by vicuna** [comment]
**Comment author:** @mshinwell

@meurer: If this is still important to you, please make a Github pull request with this patch, and close this issue.  Thanks.

**Comment by mshinwell** [comment]
There was no feedback following a ping at the end of 2016, so closing.  @bmeurer Please submit a PR if this is still important, thanks.
