### ISSUE TITLE
Feature request: Hashtbl.adjust

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#5220]
**Original bug ID:** 5220
**Reporter:** Christoph Bauer
**Status:** acknowledged (set by @damiendoligez on 2011-05-17T14:17:55Z)
**Resolution:** open
**Priority:** normal
**Severity:** feature
**Version:** 3.11.2
**Category:** standard library
**Related to:** #7309
**Monitored by:** "Pascal Cuoq" "Julien Signoles" @hcarty

## Bug description

If you have a Hashtable of counters and you want to increment one, you have to do it that way:

  Hashtbl.replace t key (1+Hashtbl.find t key)

There could be a more efficient way to do this with a helper function

  Hashtbl.adjust t key f

with the type

  Hashtbl.adjust : ('a, 'b) Hashtbl.t -> 'a -> ('b -> 'b) 

Hashtbl.adjust looks up the key in t and replaces it associated value b with (f b). It might raise Not_found.

I guess it's not possible to implement this function in BatHashtbl.

**Comment by vicuna** [comment]
**Comment author:** Christoph Bauer

The type is 

 Hashtbl.adjust : ('a, 'b) Hashtbl.t -> 'a -> ('b -> 'b) -> unit

**Comment by vicuna** [comment]
**Comment author:** Christoph Bauer

Here an implementation:

 let adjust h key f =
  let rec replace_bucket = function
  Empty ->
    raise Not_found
    | Cons(k, i, next) ->
      if compare k key = 0
      then Cons(k, f i, next)
      else Cons(k, i, replace_bucket next) in
  let i = (hash key) mod (Array.length h.data) in
  let l = h.data.(i) in
  h.data.(i) <- replace_bucket l

**Comment by gasche** [comment]
This is a sensible feature request, but several libraries out there call it `modify`, so maybe there is some naming study to do. In any case, someone interested should consider just opening a Pull Request with a proposed implementation.
