### ISSUE TITLE
Unified API to grab a file descriptor in unixsupport.h

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#5249]
**Original bug ID:** 5249
**Reporter:** toots
**Status:** acknowledged (set by @damiendoligez on 2011-05-02T10:55:43Z)
**Resolution:** open
**Priority:** normal
**Severity:** feature
**Version:** 3.12.0
**Category:** otherlibs
**Tags:** patch
**Monitored by:** @ygrek

## Bug description

It would be nice to have a unified API to get an integer representing a file descriptor in both win32 and unix cases.

Please consider the attached patch that (trivially) add this feature.

## File attachments

- [unified_fd_of_val.patch](https://gist.githubusercontent.com/vicuna/41f406efd0909e395a9bf40e3a11f173/raw/561f37837d233c10e7636c5c39aa4e18ac2244af/unified_fd_of_val.patch)

**Comment by mshinwell** [comment]
I don't think this feature is likely to be accepted in its current form (although I think external libraries may end up using `Obj.magic` to get access to these descriptors, so there is something to potentially improve here).

**Comment by mshinwell** [comment]
Actually, I am mistaken, this is only a C binding change.  However the lack of interest does not excite.  @ygrek Do you still want this?

**Comment by gasche** [comment]
Note: The OCaml side of this question was discussed (and rejected) in #1990.

**Comment by ygrek** [comment]
I am ok with current macros avaialble
