### ISSUE TITLE
variance not inferred for package type

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#5337]
**Original bug ID:** 5337
**Reporter:** sweeks
**Assigned to:** @garrigue
**Status:** assigned (set by @mshinwell on 2016-12-07T15:38:04Z)
**Resolution:** open
**Priority:** normal
**Severity:** feature
**Version:** 3.12.0
**Category:** typing
**Related to:** #7151
**Monitored by:** @yallop yminsky

## Bug description

OCaml doesn't accept the following program, because it does not infer that type `t` is
covariant.
```ocaml
  module type S = sig
    type t
    val x : t
  end
  
  type +'a t = (module S with type t = 'a)
```
It would be nice if OCaml's variance inference would look inside package types.

**Comment by vicuna** [comment]
**Comment author:** yminsky

Note that this also fails in 3.12.1

```
# module type S = sig type t val x : t end;;
module type S = sig type t val x : t end
# type +'a t = (module S with type t = 'a);;
Error: In this definition, expected parameter variances are not satisfied.
The 1st type parameter was expected to be covariant,
but it is invariant
```

**Comment by vicuna** [comment]
**Comment author:** @garrigue

Unfortunately, there is no cheap solution.
Computing the variance of a module would require going through all syntactic constructs, which probably means a huge number of lines of code.
An easy workaround is to use objects in place of first-class modules, at least when you need variance :-)

**Comment by vicuna** [comment]
**Comment author:** @mshinwell

Jacques: is this ever going to be fixed?

**Comment by vicuna** [comment]
**Comment author:** @garrigue

A fix would require a breakthrough in our understanding of the interaction between modules and variance.
So I see no general fix anytime soon.

**Comment by vicuna** [comment]
**Comment author:** @mshinwell

For things like this I wonder if we should have a "known list of limitations" to which these items can be added, rather than keeping Mantis issues open for many years.  Is there anything like that (or could we start something like that?) for the type checker?

**Comment by garrigue** [comment]
@mshinwell suggested a solution to this entry, in the form of a list of known limitations.
I see a number of potential entries. Where should it go?
