### ISSUE TITLE
Inline submodules, single-page HTML

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#5407]
**Original bug ID:** 5407
**Reporter:** @mjambon
**Assigned to:** @zoggy
**Status:** assigned (set by @mjambon on 2012-03-14T22:45:36Z)
**Resolution:** reopened
**Priority:** normal
**Severity:** feature
**Version:** 3.12.1
**Category:** ocamldoc
**Tags:** html, ocamldoc
**Monitored by:** ronan.lehy@gmail.com tgazagna @ygrek @hcarty

## Bug description

Would it be possible to have the two following options:

1. keep the documentation of submodules on the same HTML page as the parent module (or compilation unit)

2. produce a single HTML page instead of about one per source file (implies option (1))

Both would make search easier, especially when the modules or submodules are many and small.

## Steps to reproduce

This is a very specific need. I suggest you develop your own custom generator for that (not much work: some methods to override).

**Comment by vicuna** [comment]
**Comment author:** @mjambon

This doesn't strike me as particularly specific. How do you search for a given functionality within a library?

**Comment by vicuna** [comment]
**Comment author:** @zoggy

grepping in mli files ?
Argot is what you're looking for: http://argot.x9c.fr/
It includes a local search capability, including searching on type and handling type isomorphism.

**Comment by vicuna** [comment]
**Comment author:** @mjambon

While I appreciate the effort made by Argot, what I really want is native full-text search (Ctrl-f) that would be straightforward if ocamldoc-generated manuals came in a single-page variant, just like OMake's manual (http://omake.metaprl.org/manual/omake.html) atdgen's manual produced with Hevea (http://oss.wink.com/atdgen/atdgen-1.2.2/manual/atdgen-manual.html), the GNU Emacs manual (http://www.gnu.org/software/emacs/manual/emacs.html) and others.

I think it would benefit a large number of users without requiring any special-purpose search mechanism.

I don't completely exclude to do it myself, but it seems more easily done by the original author. Also the patch would need to be integrated in the official OCaml distribution.

**Comment by vicuna** [comment]
**Comment author:** @zoggy

Another solution would be to generate a latex document, then use hevea to translate it to html :-)

I don't have time to develop this new generator, but if you create it, we can integrate it.

Here is how I see it:
- It would be an extension of the default html generator, so you can develop it separately,
- After integration, it would be choosen with a -one-html option.

You will have to handle, in links, the fact that everything is in one file. If it appears that it would be made easier if the Odoc_html.Naming module was a class, to change some methods, just tell me.

At last, interface to define a custom generator will change in next release, you can have a loot, for example, at
  https://gitorious.org/ocamldoc-generators/ocamldoc-generators/blobs/master/odoc_todo.ml
(if you already use the ocaml-4.00 branch)

**Comment by vicuna** [comment]
**Comment author:** @alainfrisch

We would also like to have the option to generate sub-modules on the same HTML page. (No real need on our side to generate everything on one big page.)  A related topic: another option to "inline" included signatures.

**Comment by vicuna** [comment]
**Comment author:** lebedev

Having an option, which allows to inline included signatures would be useful. See for example how Core containers are documented [1, 2], each module includes a private signature 'Creators', which is not accessible via the generated documentation.

[1]: https://ocaml.janestreet.com/ocaml-core/latest/doc/core/Hashtbl.Poly.html
[2]: https://ocaml.janestreet.com/ocaml-core/latest/doc/core/Hash_set.html

**Comment by Drup** [comment]
As with the other ocamldoc feature requests, I suggest we close.
