### ISSUE TITLE
On the mantis, non developer can't define relationship between bugs

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#5452]
**Original bug ID:** 5452
**Reporter:** pilki
**Assigned to:** @damiendoligez
**Status:** assigned (set by @mshinwell on 2016-12-09T07:41:29Z)
**Resolution:** open
**Severity:** feature
**Category:** misc
**Monitored by:** @protz

## Bug description

Non developer should at least be allowed to define relationship between there own bugs/feature wishes, to help classify stuff!

**Comment by vicuna** [comment]
**Comment author:** @lefessan

Indeed, it might be useful to allow reporters to create links between bugs.
Who is admin on mantis ?

**Comment by vicuna** [comment]
**Comment author:** @protz

Xavier is, I think he's going to make admin too so that I can have the pleasure of spending an entire afternoon figuring out how to make this work :)

**Comment by vicuna** [comment]
**Comment author:** @mshinwell

@doligez I'm tempted to say we should close this, what do you think?

**Comment by mshinwell** [comment]
We are no longer using Mantis.  (And I was tempted to close this 2.5 years ago.)
