### ISSUE TITLE
warning for inherited library classes

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#5536]
**Original bug ID:** 5536
**Reporter:** Hendrik Tews
**Assigned to:** @zoggy
**Status:** feedback (set by @zoggy on 2012-03-14T20:59:41Z)
**Resolution:** open
**Priority:** normal
**Severity:** minor
**Version:** 3.12.1
**Category:** ocamldoc

## Bug description

Inheriting from a library class gives a warning, while normally
types from libraries appearing in the interface do not produce a
warning.

## Steps to reproduce

run ocamldoc -I +ocamldoc on

class a =
object
  inherit Odoc_html.html
end

## Additional information

also present in 4.00.0+dev13 (2012-03-08)

**Comment by vicuna** [comment]
**Comment author:** @zoggy

I don't have any smart idea on how to prevent this. The only way I see is to filter one some constant names but it's not very elegant. This may also be a bug in case of a name conflict.
Any suggestion ?

**Comment by gasche** [comment]
Unfortunately, we don't have much manpower to improve these non-trivial aspects of ocamldoc in the future, so it is likely that the issue will remain unaddressed -- I will close it now to focus on issues that are more likely to be revisited in the future. There is more momentum towards using `odoc`, whose design may be more amenable to solve this kind of issues.
