### ISSUE TITLE
Flexdll's dll produced from several object files fails to load

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#5613]
**Original bug ID:** 5613
**Reporter:** joedralliam
**Assigned to:** @alainfrisch
**Status:** assigned (set by @alainfrisch on 2012-05-15T12:22:27Z)
**Resolution:** open
**Priority:** normal
**Severity:** minor
**Platform:** Visual C++
**OS:** Windows
**OS Version:** Windows 7
**Version:** 3.12.1
**Target version:** later
**Category:** platform support (windows, cross-compilation, etc)

## Bug description

Launching a byte-code executable which uses primitives defined in the dll (mixed C/C++) fails with following output:
No master relocation table
Fatal error: unknown C primitive `foo__impl'

Removing '/Ox' compilation option fix the 'bug'.
Replacing the object constructors/destructor behaviour (calling caml_release_runtime_system and caml_acquire_runtime_system) by explicit calls fix also the 'bug'.

Is this behaviour expected ?

## Steps to reproduce

cl /MD /Ox /EHs /DCAML_NAME_SPACE /IC:/ocamlms/lib /c foo.cpp
cl /MD /Ox /EHs /DCAML_NAME_SPACE /IC:/ocamlms/lib /c bar.cpp

flexlink -chain msvc64 -merge-manifest foo.obj bar.obj -o dlltest.dll
cp dlltest.dll $(shell ocamlc -where)/lib/stublibs/dlltest.dll

ocamlc -c test.ml -o test.cmo
ocamlc -a test.cmo -o test.cma -dllib -ltest
ocamlc test.cma test_prog.ml -o test_prog.exe

## File attachments

- [test_corrected.tar.gz](https://gist.githubusercontent.com/vicuna/776cbd2076a298d5375ae1ede966ecb2/raw/3a44725fb7c48a445cc9662c6a1a59fb8a0c4d53/test_corrected.tar.gz)

**Comment by vicuna** [comment]
**Comment author:** joedralliam

I'm sorry, I uploaded the wrong archive ("test.tar.gz", the correct one is "test_corrected.tar.gz"). But I can't delete it ??

**Comment by vicuna** [comment]
**Comment author:** @damiendoligez

Is flexdll even supposed to work with C++ code?

**Comment by vicuna** [comment]
**Comment author:** @alainfrisch

There has been some effort to have flexdll support C++ code, but no guarantee is provided.  I'll happily integrate patches that fix the mentionned problem, but won't be able to investigate myself.

Anyway, this is an old problem, which would most likely be addressed in flexdll, not OCaml, so there is no reason to delay the release of OCaml for this one.

**Comment by xavierleroy** [comment]
Looks like a FlexDLL issue.
