### ISSUE TITLE
no uninstall target in the Makefile

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#5684]
**Original bug ID:** 5684
**Reporter:** berenger
**Status:** confirmed (set by @damiendoligez on 2012-07-17T12:48:44Z)
**Resolution:** open
**Priority:** high
**Severity:** feature
**Platform:** all
**OS:** unix-like
**OS Version:** all
**Version:** 4.00.0+beta2/+rc1
**Target version:** undecided
**Category:** configure and build/install
**Monitored by:** @hcarty

## Bug description

Hi,

When there is a make install, it's useful
to also have a make uninstall.

Thanks,
F.

**Comment by vicuna** [comment]
**Comment author:** @johnwhitington

If uninstalling is too delicate or difficult to maintain, one way to fix this might be to simply warn if the target directories already exist, and suggest the user delete them.

Simply overwriting what is there can lead to subtle errors, which are hard to track down. For example:

https://github.com/ocaml/opam/issues/3665 (OPAM broken by new stdlib__ prefix if unprefixed files still exist in system ocaml).

ocamlfind's ./configure also can not complete with 3.07.1 installed over an older ocaml, presumably due to the same problem -- it looks for x.cmi before stdlib__x.cmi.

**Comment by nojb** [comment]
For the record, the `stdlib__` issue was fixed #1724
