### ISSUE TITLE
Feature wish: a way to know at runtime which version of the thread library

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#5767]
**Original bug ID:** 5767
**Reporter:** @garrigue
**Status:** confirmed (set by @damiendoligez on 2012-09-29T20:28:45Z)
**Resolution:** open
**Priority:** normal
**Severity:** feature
**Version:** 4.00.2+dev
**Category:** otherlibs
**Monitored by:** mehdi @hcarty

## Bug description

OCaml has two thread libraries, systhreads and vmthreads.
One has to choose between the two at compile time, but they are essentially compatible.
However, they do have different behavior with respect to callbacks for instance.
My first wish would be a library function that tells which library is used, so that
one could write code compatible with both.
If this is granted, my second wish would be cmi compatibility between these two libraries,
so that one could choose which one to use at link time (small extra comfort).

**Comment by vicuna** [comment]
**Comment author:** @damiendoligez

Correct me if I'm wrong, but in order to be able to choose at link time (rather than compile time), the MD5 of the cmi files must be the same, which is a really strong constraint. Essentially, the two mli files must be identical.

**Comment by stedolan** [comment]
vmthreads is dead now (#2289), so this is moot.
