### ISSUE TITLE
Function signatures be dropped out from recursive modules within higher order functor

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#5818]
**Original bug ID:** 5818
**Reporter:** tianyicui
**Assigned to:** @lpw25
**Status:** acknowledged (set by @damiendoligez on 2013-01-04T14:23:17Z)
**Resolution:** open
**Priority:** normal
**Severity:** feature
**Version:** 4.00.1
**Target version:** undecided
**Category:** typing
**Tags:** recmod
**Related to:** #4134
**Monitored by:** @gasche @alainfrisch

## Bug description

The background can be seen from the stackoverflow question (http://stackoverflow.com/questions/13304044/implementing-okasakis-bootstrapped-heaps-in-ocaml-why-doesnt-it-compile), below is a reduced example, in which, it seems the signature of HigherOrderFunctor.Base and HigherOrderFunctor2.Base are the same, but the later will not compile.

```ocaml
module type ORDERED =
sig
  type t
  val compare : t -> t -> int
end

module type CARRY = sig
  module M : ORDERED
end

(* works *)
module HigherOrderFunctor
  (Make : functor (X : ORDERED) -> (CARRY with module M = X))
= struct
  module rec Base
    : (ORDERED with type t = string)
    = String
  and Other
    : (CARRY with module M = Base)
    = Make(Base)
end

(* does not work *)
module HigherOrderFunctor2
  (Make : functor (X : ORDERED) -> (CARRY with module M = X))
= struct
  module rec Base
    : sig
      (* 'compare' seems dropped from this signature *)
      type t = string
      val compare : t -> t -> int
    end
    = String
  and Other
    : (CARRY with module M = Base)
    = Make(Base)
end
```

## File attachments

- [fix-5818.patch](https://gist.githubusercontent.com/vicuna/00505b69839ea6d9009d60740b04919f/raw/12c90e9048469455056109d64216b54fe8aa20ff/fix-5818.patch)

**Comment by vicuna** [comment]
**Comment author:** @mshinwell

This bug was discussed.  It is suspected that it's a shortcoming in the type checker, but that there should be work-arounds.  May be re-visited for a future release.

**Comment by vicuna** [comment]
**Comment author:** @lpw25

The issue here is that inclusion checks can fail spuriously when there are module type approximations in the environment. The attached patch fixes this by weakening inclusion checks whenever the environment contains approximations. This is safe because the checks will be run again later with the correct types, and inclusion checks don't generate any information required in the rest of type-checking.

**Comment by vicuna** [comment]
**Comment author:** @alainfrisch

Note that Env.t has now a flags field which is a bit mask (this is currently only in the 4.02 branch, not integrated in trunk yet).  This could be used to avoid adding an extra field for contains_approx.

**Comment by vicuna** [comment]
**Comment author:** @lpw25

I think this patch also fixes #4134

**Comment by vicuna** [comment]
**Comment author:** @garrigue

@lpw25: If you're sure that your fix doesn't break existing programs, you may go foward.
On recursive modules, I must admit that I'm not competent enough to do any kind of review.

**Comment by yallop** [comment]
Both `HigherOrderFunctor` and `HigherOrderFunctor2` are rejected as of 4.08 (as a result of #1626, I think):

```
Line 8, characters 29-33:
8 |     : (CARRY with module M = Base)
                                 ^^^^
Error: Illegal recursive module reference
```

**Comment by garrigue** [comment]
@lpw25 Are we still waiting for a PR with the attached patch?

**Comment by lpw25** [comment]
My old patch allows ill-formed types and paths to be formed temporarily. I'm not a huge fan of that. Since I don't think people hit these cases very often, and recursive modules are incomplete in all kinds of ways, we can probably just leave this. If more people starting running into such problems it would be easy to resurrect the patch.
