### ISSUE TITLE
Ocamldoc: "Module or module type ?? not found" when including a functor application

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#5843]
**Original bug ID:** 5843
**Reporter:** jpdeplaix
**Assigned to:** @zoggy
**Status:** assigned (set by jpdeplaix on 2012-12-04T22:31:23Z)
**Resolution:** open
**Priority:** normal
**Severity:** minor
**Version:** 4.00.0
**Target version:** later
**Category:** ocamldoc
**Related to:** #3947

## Bug description

I'm trying to include a functor application when the functor is defined in the same module (otherwise it seems to work) and ocamldoc warns with:

Warning: Module or module type ?? not found

I've attached a test-case.

## Steps to reproduce

ocamldoc -html ocamldoc.mli

## File attachments

- [ocamldoc.mli](https://gist.githubusercontent.com/vicuna/2a3794664b3fffaa7e01bea6a94903ab/raw/7ee2e7e69e0ec39d5316a570246f39f4b21b7da1/ocamldoc.mli)

**Comment by vicuna** [comment]
**Comment author:** @zoggy

This is due to the fact that ocamldoc does not support environments. Here the include requires to access the environment to be able to know the origin of the included module type.
This is a long-time missing analysis in ocamldoc, requiring quite a lot of work.

**Comment by avsm** [comment]
For the record, this will be fixed comprehensively in odoc when https://github.com/ocaml/odoc/pull/439 is merged and released. All functor applications should render correctly in the new model present in that PR.
