### ISSUE TITLE
OCamldoc could produce nice mathematical symbols

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#5857]
**Original bug ID:** 5857
**Reporter:** meyer
**Assigned to:** @zoggy
**Status:** assigned (set by meyer on 2012-12-17T22:49:14Z)
**Resolution:** open
**Priority:** normal
**Severity:** feature
**Category:** ocamldoc

## Bug description

It would be nice to see unicode greek letters as type variables and unicode arrows in type definitions. For example enable in Emacs and tuareg mode:

(setq tuareg-font-lock-symbols t)

**Comment by dbuenzli** [comment]
This is not a good idea as it would break cut and paste from ocamldoc output to your editor. I would move on to close this.

**Comment by trefis** [comment]
I wonder if, at least for the html backend, there wouldn't be some (CSS ? JS ? Whatever ?) magic to make the text that is copied different from what you actually see in the browser. (Actually, I can't see how such an obviously useful feature couldn't exist)

But I agree it's a bad idea in general, also I'm not sure anyone's really looking into adding new features to ocamldoc nowadays. So indeed, let's close.

**Comment by Drup** [comment]
@trefis Well, another way to do this is to play (arguably silly) games with ligatures.

Personally, I think this is pointless. We already are accustomed to the signatures without any of those fancy chars, the readability improvements will be negligible or non-existent.
