### ISSUE TITLE
ocamldebug documentation issues

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#5860]
**Original bug ID:** 5860
**Reporter:** @damiendoligez
**Status:** acknowledged (set by @damiendoligez on 2013-01-04T14:26:01Z)
**Resolution:** open
**Priority:** normal
**Severity:** minor
**Platform:** all
**OS:** all
**OS Version:** all
**Version:** 4.01.0+dev
**Category:** tools (ocaml{lex,yacc,dep,debug,...})
**Tags:** junior_job
**Monitored by:** meyer

## Bug description

- #3555 was implemented, but the feature is not documented anywhere
- The ocamldebug documentation states that it doesn't work on Windows, which is not true anymore
- There is no category in the BTS for reporting problems in ocamldebug: the "Ocaml tools" category is too
limitative.

**Comment by vicuna** [comment]
**Comment author:** @damiendoligez

(3): done

**Comment by damiendoligez** [comment]
FTR: these are all fixed as of the current release (4.11.0).
