### ISSUE TITLE
polymorphic variant typing error message not meaningful

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#5889]
**Original bug ID:** 5889
**Reporter:** @bobzhang
**Status:** confirmed (set by @damiendoligez on 2013-06-28T16:17:27Z)
**Resolution:** open
**Priority:** normal
**Severity:** text
**Target version:** later
**Category:** typing
**Related to:** #5888
**Monitored by:** @gasche @hcarty

## Bug description

type 'a u3 = [< `b | `a of  & int & bool ] as 'a;;
File "", line 1:
Error: Type declarations do not match:
         type 'a u3 = 'a constraint 'a = [< `a of & int & bool | `b ]
       is not included in
         type 'a u3 = 'a constraint 'a = [< `a of & int & bool | `b ]

**Comment by yallop** [comment]
This is fixed, possibly by #5927, and the code is now accepted as written.
