### ISSUE TITLE
ocamlc does not fully take into consideration -o parameter

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#5890]
**Original bug ID:** 5890
**Reporter:** kosik
**Assigned to:** @shindere
**Status:** assigned (set by @damiendoligez on 2017-03-24T12:06:38Z)
**Resolution:** open
**Priority:** normal
**Severity:** feature
**Version:** 3.12.1
**Category:** compiler driver
**Has duplicate:** #7573
**Related to:** #6191 #6475
**Monitored by:** @hcarty

## Bug description

When one tries to build an Ocaml library directly from multiple ml-files this way:

  ocamlc -a -o library.cma foo.ml bar.ml baz.ml

things work fine. Essential *.cmi and *.cmo files are created in the same place as library.cma target.

However, when one tries to specify non-current output directory:

  ocamlc -a -o /tmp/library.cma foo.ml bar.ml baz.ml

then *.cmo and *.cmi files are created in the current directory and only library.cma file is created in the designated /tmp directory.

While the manual page does not explicitly make any promises in this regard, the current behavior is surprising. It does not seem probably that user would want object files to be generated in one directory and resulting library in a different directory.

**Comment by vicuna** [comment]
**Comment author:** kosik

ocamlopt has a similar (surprising) property

**Comment by vicuna** [comment]
**Comment author:** @damiendoligez

I personally don't find this surprising at all, but this is related to a feature wish I seem to remember, for a "-odir" option to specify in what directory to put the generated files that are not specified with -o and thus have an implicit file name.

**Comment by vicuna** [comment]
**Comment author:** @damiendoligez

This PR suggests putting auxiliary files in the same directory as the -o file.
That may fail if we have write access to the -o file but not its directory, so this would be a slightly dangerous change.

The -odir option seems safer and easier to use.

**Comment by shindere** [comment]
Yes, the issue is still there and really needs to be fixed.

**Comment by shindere** [comment]
It's being addressed, but bugs have been discovered recently, see e.g.
https://github.com/ocaml/ocaml/pull/9960#issuecomment-889663598

Will try submit a PR for the problems described there, sorry for having
introduced them in the first place.

**Comment by shindere** [comment]
I think this will be fixed in 4.13, by #9960 and #10619 (about to be
merged).

@kosik are you happy with the proposed fixes? Canthis be closed?

**Comment by shindere** [comment]
I am closing this issue because, as reported above, I think it is fixed in OCaml 4.13.0.
