### ISSUE TITLE
Constraints on type declarations can be of the form "typexpr = typexpr", not only "'ident = typexpr"

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#5987]
**Original bug ID:** 5987
**Reporter:** @alainfrisch
**Status:** confirmed (set by @damiendoligez on 2013-06-19T11:57:36Z)
**Resolution:** open
**Priority:** normal
**Severity:** minor
**Category:** documentation
**Monitored by:** @hcarty @garrigue

## Bug description

The manual says:

type-constraint ::= constraint 'ident = typexpr  

but the parser recognizes:

constrain:
        core_type EQUAL core_type          { $1, $3, symbol_rloc() }
;

(I wonder whether even the simpler form of constraints on type declarations is actually used...)

**Comment by vicuna** [comment]
**Comment author:** @gasche

Yes, I think constraints have some use (besides backporting a soundness bug to old OCaml versions in the raging bugtracker discussion). I personally used them in conjunction with phantom object types in Macaque, to get a form of type-level records:

type 'phant binary_op = 'a t -> 'b t -> 'c t
  constraint 'a = < t : 'in_t; nul : 'n; .. >
  constraint 'b = < t : 'in_t; nul : 'n; .. >
  constraint 'c = < t : 'out_t; nul : 'n >
  constraint 'phant =
    < in_t : 'in_t; out_t : 'out_t; nul : 'n; a : 'a; b : 'b >

(Only the last constraint is really necessary, the others are here for readability)

**Comment by vicuna** [comment]
**Comment author:** @damiendoligez

This appears to be deliberately documented that way. Should we change the documentation or restrict the parser?

**Comment by vicuna** [comment]
**Comment author:** @garrigue

I see no gain in restricting the parser (being syntactically a variable does not mean anything semantically). So I suppose fixing the documentation is the way to go.

**Comment by garrigue** [comment]
Fix as suggested. Waiting for a review.

**Comment by gasche** [comment]
Closed by merging #9568. Thanks!
