### ISSUE TITLE
Calling a method from a super class on a modified version of self

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#5990]
**Original bug ID:** 5990
**Reporter:** @alainfrisch
**Status:** acknowledged (set by @damiendoligez on 2013-06-19T10:45:12Z)
**Resolution:** open
**Priority:** low
**Severity:** feature
**Category:** language features

## Bug description

A common idiom when using objects and classes to define customizable iterators is the following:

<pre>
let o = object
  inherit generic_iterator as super

  val path = []

  method! foo x = {< path = x.name :: path >} # super_foo x
  method super_foo = super # foo
end
</pre>

i.e. one wants to call a method from a super class on a modified version of self (using functional object update).  I'm wondering whether it would make sense to have a new language construction allowing such a call directly without going through a "trampoline" method like above; something like:

<pre>
let o = object
  inherit generic_iterator as super

  val path = []

  method! foo x = {< super with path = x.name :: path >} # foo x
end
</pre>

**Comment by mshinwell** [comment]
I don't know whether @alainfrisch is still wondering 7 years later, but if he is, I would suggest an RFC would be the next step if this is to be taken forward.
