### ISSUE TITLE
GADT typing and exhaustiveness bugs

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#5998]
**Original bug ID:** 5998
**Reporter:** @garrigue
**Assigned to:** @garrigue
**Status:** assigned (set by @garrigue on 2013-04-23T00:05:23Z)
**Resolution:** open
**Severity:** feature
**Category:** typing
**Related to:** #6598
**Parent of:** #5425 #5427 #5689 #5713 #5724 #5736 #5780 #5785 #5848 #5853 #5867 #5892 #5906 #5948 #5981 #5985 #5989 #5997 #6220 #6241 #6395 #6403 #6405 #6437 #6801 #7074 #7233 #7269 #7374 #7378 #7390 #7592

## Bug description

This is a parent PR for all GADT problems.

**Comment by Octachron** [comment]
Is there any objections to transforming this issue into a `GADT typing` label?

**Comment by garrigue** [comment]
I'm fine with the label approach.

**Comment by Octachron** [comment]
I added a new shiny `typing-GADTs` labels to all related issues. I am closing this meta-issue.
