### ISSUE TITLE
Format.{pp_print_opt, pp_print_list, pp_print_text}

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#6009]
**Original bug ID:** 6009
**Reporter:** @dbuenzli
**Status:** acknowledged (set by @gasche on 2013-05-07T14:45:15Z)
**Resolution:** open
**Priority:** normal
**Severity:** feature
**Version:** 4.00.1
**Category:** standard library
**Tags:** patch
**Monitored by:** meyer @hcarty

## Bug description

Ok, this time I got too tired of copy pasting that code. 

First an option pretty printer.

```ocaml
(** [pp_print_opt pp_none pp_v ppf o] prints the optional value v. [pp_v] is used if [o] is [Some], 
     [pp_none] if [o] is [None] (default prints nothing). *)

let pp_print_opt ?(pp_none = fun ppf () -> ()) pp_v ppf = function 
| None -> pp_none ppf ()
| Some v -> pp_v ppf v
```

Then a list pretty printer.

```ocaml
(** [pp_print_list pp_sep pp_v ppf l] prints the list [l]. [pp_v] is used on the elements of [l] and 
     each element is separated by a call to [pp_sep] (defaults to {!pp_print_cut}). Does nothing on 
     empty lists. *)

let rec pp_print_list ?(pp_sep = Format.pp_print_cut) pp_v ppf = function 
| [] -> ()
| v :: vs -> 
    pp_v ppf v; if vs <> [] then (pp_sep ppf (); pp_print_list ~pp_sep pp_v ppf vs)
```

Then a string printer that hints newlines and spaces with Format's functions.

```ocaml
(** [pp_print_text ?nl ppf s] prints [s] with spaces and newlines respectively printed with
     {!pp_print_space} and {!pp_force_newline}. *)

let pp_print_text ppf s =          (* hint spaces and new lines with Format's funs *)
  let len = String.length s in
  let left = ref 0 in
  let right = ref 0 in 
  let flush () =
    Format.pp_print_string ppf (String.sub s !left (!right - !left)); 
    incr right; left := !right;                      
  in
  while (!right <> len) do 
    if s.[!right] = '\n' then (flush (); Format.pp_force_newline ppf ()) else
    if s.[!right] = ' ' then (flush (); Format.pp_print_space ppf ()) else 
    incr right
  done;
  if !left <> len then flush ()
```

## File attachments

- [0001-Format-pp_print_list-and-pp_print_text-contributed-b.patch](https://gist.githubusercontent.com/vicuna/4c58c48faa551947ca99e4a72fb5de22/raw/c66c5997371f0954205b7d193ad8d7c5d1398cb7/0001-Format-pp_print_list-and-pp_print_text-contributed-b.patch)

**Comment by vicuna** [comment]
**Comment author:** @gasche

That's mildly unrelated, but have you considered using Pprint ( http://gallium.inria.fr/~fpottier/pprint/ ) instead of the Format module? You may appreciate the simplicity and smaller codebase.

**Comment by vicuna** [comment]
**Comment author:** @dbuenzli

Thanks for the pointer but the problem is that I'm writing OCaml libraries. I always provide pretty printers for values of the type they define so that users can quickly perform printf debugging or use in the toplevel. There would be no point in having a dependency on the library you mention however good it may be.

**Comment by vicuna** [comment]
**Comment author:** @gasche

Good point.

**Comment by vicuna** [comment]
**Comment author:** meyer

I support having need of such an extended interface. I needed to write again and again given functions. Eventually I turned this into mini module and copied across the project. At least pp_print_list is useful, and pp_print_text is something I didn't think of, but it looks also very useful.

**Comment by vicuna** [comment]
**Comment author:** @gasche

I just uploaded an equivalent patch that applies as-is against the current trunk. I'm wary of optional parameters in the API (especially since Format does not use any so far), but didn't find a better way to express pp_print_list -- and omitted pp_print_opt for now because I'm not satisfied with the interface.

**Comment by nojb** [comment]
These functions have all been merged into the stdlib.
