### ISSUE TITLE
extensible records

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#6066]
**Original bug ID:** 6066
**Reporter:** meyer
**Status:** acknowledged (set by @damiendoligez on 2014-08-21T09:46:16Z)
**Resolution:** open
**Priority:** low
**Severity:** feature
**Category:** typing
**Monitored by:** @gasche @ygrek @jberdine @hcarty

## Bug description

It would be good to support extensible records in the same way as inheritance hierarchy with objects, with the difference that no dynamic dispatch would be involved, thus making them more efficient.

The syntax would be:
<pre>

record foo = { x : int; y : int }
(* will type to: <@ x : int; y : int ... > *)
record bar = { foo with z : int  }
(* will type to: <@ x : int; y : int; z : int; ... > *)
</pre>

**Comment by mshinwell** [comment]
There have been no comments since 2013, so closing.  If the feature is desired and someone has the resources to implement it, please produce an RFC.
