### ISSUE TITLE
ocamlbuild documentation with ocamlfind

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#6086]
**Original bug ID:** 6086
**Reporter:** william
**Status:** acknowledged (set by @damiendoligez on 2014-04-02T14:37:55Z)
**Resolution:** open
**Priority:** normal
**Severity:** feature
**Category:** documentation
**Tags:** patch

## Bug description

Hello,
I had a look at the recommanded tutorial for ocamlbuild. There is a section "Using an external library" that brings to :
http://brion.inria.fr/gallium/index.php/Using_an_external_library

It is too bad an example is not given using ocamlfind in _tags files. To that end, I send you a little working example using cairo.
Best regards

## File attachments

- [ocamlbuild_ocamlfind.tar.gz](https://gist.githubusercontent.com/vicuna/6ecfc1487c490c061d23c3599d456ba3/raw/98b977de91532cac6f268c7ccb54f255865f0b95/ocamlbuild_ocamlfind.tar.gz)

**Comment by mshinwell** [comment]
No longer relevant to the compiler distribution.
