### ISSUE TITLE
is_inet6_addr from unix.ml should be exposed in unix.mli

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#6105]
**Original bug ID:** 6105
**Reporter:** qrntz
**Status:** confirmed (set by @damiendoligez on 2013-08-28T09:16:26Z)
**Resolution:** open
**Priority:** normal
**Severity:** feature
**Platform:** i686
**OS:** Gentoo Linux
**OS Version:** Rolling release
**Version:** 4.00.1
**Category:** otherlibs
**Tags:** patch, junior_job

## Bug description

I don't see the reasoning behind is_inet6_addr from unix.ml not being exposed in the interface; there is no other way to identify an inet_addr's address family once one has been created and while the function is fairly trivial in itself, the same code wouldn't work outside of Unix because the type abbreviation of inet_addr = string is hidden (and I would really rather not resort to type magic for something as simple as this).

There is domain_of_sockaddr that can return either PF_INET or PF_INET6 (and uses is_inet6_addr to determine that) but it's unintuitive what with being a level of abstraction higher.

## File attachments

- [6105_is_inet6_addr.patch](https://gist.githubusercontent.com/vicuna/a150f6c1e8a099444ac3c7e762f375cd/raw/b42e6cfd3b93bb9a3928ce1af8ca5a7389016b81/6105_is_inet6_addr.patch)

**Comment by vicuna** [comment]
**Comment author:** dsheets

Patch attached.

**Comment by nojb** [comment]
Duplicate of #4535
