### ISSUE TITLE
Use compilerlibs instead of explicit lists of modules from the compiler

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#6195]
**Original bug ID:** 6195
**Reporter:** @alainfrisch
**Status:** confirmed (set by @xavierleroy on 2013-10-03T12:26:00Z)
**Resolution:** open
**Priority:** normal
**Severity:** feature
**Target version:** later
**Category:** configure and build/install

## Bug description

Some tools which are part of the standard distribution (ocamldoc, ocamldebug, read_cmt, objinfo) embed some modules from the compiler.  Instead of listing required modules explicitly, we could link against ocamlcommon.cma (and ocamlbytecomp.cma, if needed).  This would simplify the Makefiles and make them more robust w.r.t. modifications of dependencies within compiler modules.

**Comment by vicuna** [comment]
**Comment author:** @xavierleroy

Good idea.  Any takers?

**Comment by vicuna** [comment]
**Comment author:** @alainfrisch

ocamldoc: done.  Note that it is compiled with -linkall (not sure why), so linking against ocamlcommon.cma includes some unused modules (mostly, the type-checker).  I think we don't care.

**Comment by vicuna** [comment]
**Comment author:** @xavierleroy

> Note that it is compiled with -linkall (not sure why)

Because ocamldoc can dynamically load plugins, I think.  (Hence all stdlib modules and all ocamldoc modules must be linked in.)

**Comment by vicuna** [comment]
**Comment author:** @zoggy

Exactly.

**Comment by vicuna** [comment]
**Comment author:** @alainfrisch

Note that ocamldoc modules are explicitly included (as opposed to linking odoc_info.cma + other modules).  Point taken for the stdlib.  This makes me wonder whether we should have a way to force including an entire library (i.e. -linkall restricted to a single library).

**Comment by vicuna** [comment]
**Comment author:** @alainfrisch

read_cmt: done in commit 16417.

**Comment by vicuna** [comment]
**Comment author:** @alainfrisch

This is about ongoing internal cleanup, not something blocking for 4.03.

**Comment by xavierleroy** [comment]
If I'm not mistaken, only ocamldebug remains to be cleaned up?

**Comment by nojb** [comment]
I think `ocamlobjinfo` also remains to be treated.

**Comment by xavierleroy** [comment]
Looking at `tools/Makefile` it seems like ocamlobjinfo links with compilerlibs.  Am I missing something?

**Comment by nojb** [comment]
- `ocamlobjinfo` still links against some individual modules of `ocamloptcomp`:
https://github.com/ocaml/ocaml/blob/798dc35c9e61bfa70e5332325519b938888e6cb0/tools/Makefile#L327-L335

- `ocamlmktop` also does not link against compiler-libs:
https://github.com/ocaml/ocaml/blob/798dc35c9e61bfa70e5332325519b938888e6cb0/tools/Makefile#L167-L172

- `ocamlprof`:
https://github.com/ocaml/ocaml/blob/798dc35c9e61bfa70e5332325519b938888e6cb0/tools/Makefile#L112-L121

- and `ocamlcp`: https://github.com/ocaml/ocaml/blob/798dc35c9e61bfa70e5332325519b938888e6cb0/tools/Makefile#L123-L127

**Comment by mshinwell** [comment]
The `ocamlobjinfo` part of this will be fixed by my middle-end rearrangements (#2281 / #2288).
