### ISSUE TITLE
Generate links to exception definitions referenced in @raise tags

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#6254]
**Original bug ID:** 6254
**Reporter:** jtoman
**Assigned to:** @zoggy
**Status:** assigned (set by jtoman on 2013-12-01T06:42:07Z)
**Resolution:** open
**Severity:** feature
**Category:** ocamldoc
**Tags:** patch

## Bug description

It would be nice if the Ocamldoc tool automatically generated links to exceptions referenced in doc comments via the @raise tag.

Attached are two patches that contain potential starting points for this feature (both of which have been applied against trunk).

About these patches:
Both add a new option to ocamldoc, -link-raise which will, when possible, generate cross links between exceptions referenced in @raise comments and their definition. If the cross referencing is impossible due to limitations on the output format (or a cross reference wasn't found) the old style comments are generated instead. 

The first approach, link_raise_field.patch, adds a new option field to the raised_exception type. A value of "None" for this field indicates no cross-reference was found (or the user did not opt into cross-referencing). A value of "Some path" indicates the reference exception was found and the string path is a fully qualified path which can be used to generate a link. This approach will break any custom generators and required touching more code.

The second approach, link_raise_bc.patch adds a new field, i_linked_exc which is an associative list mapping the exception name in i_raised_exc to it's full path (for linking). The absence of an exception from the link indicates that no cross-reference was found, or that the user did not opt-into the cross-referencing. This approach was more backwards compatible with existing code, hence the name.

## File attachments

- [link_raise_bc.patch](https://gist.githubusercontent.com/vicuna/9f4a20a82bd840b6a33230689d774b09/raw/06888c54db9a3c793d4065b0f9916ad5c3e889a7/link_raise_bc.patch)
- [link_raise_field.patch](https://gist.githubusercontent.com/vicuna/9f4a20a82bd840b6a33230689d774b09/raw/f553fe332279561d657e0eef96985184d556d954/link_raise_field.patch)

**Comment by avsm** [comment]
I've filed this on the odoc tracker at https://github.com/ocaml/odoc/issues/440
