### ISSUE TITLE
Mantis bugtracker has hundreds of spam-created users making searching by username difficult

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#6288]
**Original bug ID:** 6288
**Reporter:** @johnwhitington
**Assigned to:** @dra27
**Status:** assigned (set by @mshinwell on 2016-12-09T07:38:26Z)
**Resolution:** open
**Priority:** normal
**Severity:** minor
**Target version:** later
**Category:** misc

## Bug description

Try the user menu of the search interface.

**Comment by vicuna** [comment]
**Comment author:** @damiendoligez

Does anyone know of a way to (semi-)automate the task of deleting them?

**Comment by vicuna** [comment]
**Comment author:** @mshinwell

@dra Do you know how to fix this by chance?

**Comment by vicuna** [comment]
**Comment author:** @dra27

It would be a fairly simple DELETE query on whatever table stores user details in Mantis - is it possible to have access to a copy?

However, these lists are still likely to be quite long - unfortunately, without wishing to keep labouring the point, the bigger problem is the UI!

**Comment by mshinwell** [comment]
We are no longer using Mantis.
