### ISSUE TITLE
new function in Printf : kksprintf

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#6297]
**Original bug ID:** 6297
**Reporter:** @hhugo
**Status:** feedback (set by @damiendoligez on 2014-07-16T13:05:50Z)
**Resolution:** open
**Priority:** normal
**Severity:** feature
**Category:** standard library
**Related to:** #6017
**Monitored by:** @hcarty @dbuenzli

## Bug description

let kksprintf : ((('b,unit,string,'a) format4 -> string) -> 'a) -> ('b,unit,string,'a) format4 -> 'b = fun f fmt -> ...

a usecase is for it: implement i18n features
let i18n fmt = kksprintf (fun callwith -> match get_traduction fmt with None -> "<untranslated>" | Some fmt' -> callwith fmt') fmt

I don't have a strong opinion on the naming.
could this make its way into trunk (after ocaml/ocaml#6017) ? is there a 'safe' way to implement it otherwise ?

**Comment by vicuna** [comment]
**Comment author:** @dbuenzli

I'm not sure how this really helps for i18n. What you really want is positional specifiers but it seems that they are not part of the feature set see #4204.

**Comment by vicuna** [comment]
**Comment author:** @damiendoligez

Just by reading the type, I don't know what this function is supposed to do.

**Comment by stedolan** [comment]
Closing because it's unclear from this description what the proposed feature actually is. (@hhugo: if you still want this, feel free to reopen)
