### ISSUE TITLE
Improve the printing of exceptions (pp registered)

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#6301]
**Original bug ID:** 6301
**Reporter:** @Chris00
**Status:** acknowledged (set by @damiendoligez on 2014-07-16T11:44:33Z)
**Resolution:** open
**Priority:** normal
**Severity:** minor
**Platform:** x86_64
**OS:** GNU/Linux
**OS Version:** 3.10.25
**Version:** 4.01.0
**Category:** standard library
**Monitored by:** @dbuenzli

## Bug description

The documentation of Printexc.catch says it is deprecated because "the runtime system is now able to print uncaught exceptions as precisely as [Printexc.catch] does".  However, that is not entirely true (even) when exception pp are registered.  On my machine, the attached code prints:

Uncaught exception: Err.E(A)
Fatal error: exception Err.E(0)

## File attachments

- [err.ml](https://gist.githubusercontent.com/vicuna/2fbeb217f58cfa4a06c825f9bcd1d6c9/raw/67cdf3d86f793c0333bd4bf1961ac058cc230286/err.ml)

**Comment by vicuna** [comment]
**Comment author:** @damiendoligez

Maybe we should just un-deprecate Printexc.catch.

Having the runtime's generic exception printer call back to user code seems like a lot of trouble.

**Comment by xavierleroy** [comment]
> Having the runtime's generic exception printer call back to user code seems like a lot of trouble.

Someone took that trouble: #5941 .  The test now produces the expected result.
