### ISSUE TITLE
Generic operation canary

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#6338]
**Original bug ID:** 6338
**Reporter:** @ppedrot
**Status:** acknowledged (set by @damiendoligez on 2014-07-16T13:32:12Z)
**Resolution:** open
**Priority:** normal
**Severity:** feature
**Version:** 4.01.0
**Category:** standard library
**Tags:** patch

## Bug description

I would like OCaml to have a dedicated object guaranteed to fail when trying to use generic equality, hash or (de)serialization on it (or any combination of those three). This useful to check that in a huge codebase someone does not use such abstraction-breaking operations on it. In particular, I believe we need it in Coq quite badly.

This can be done using custom blocks. I give the particular example we need in Coq (which is serializable but neither comparable nor hashable) as an attachment.

I assume it would be better in the stdlib, because it requires writing C stubs, which is bad from the point of view of (Coq's) self-containedness. Feel free to reject this request if you think it has nothing to do there...

## File attachments

- [canary.c](https://gist.githubusercontent.com/vicuna/18673113cf4dbe68eb9be24a68e8ac30/raw/e59b7be5379135e6f73d91a4f934fad401bc1037/canary.c)

**Comment by ejgallego** [comment]
Umm, I am not sure a "canary" is the right solution here; it seems to me that the right solution would be to mask the corresponding `Stdlib` module and make those operators unavailable.

**Comment by nojb** [comment]
See also #1642

**Comment by alainfrisch** [comment]
@ejgallego : Hiding the generic operations and all Stdlib functions that rely on them (the whole non-functorized Hashtbl, List.assoc, etc) is not realistic in practice (at least before we get modular implicits), and there are many legitimate use cases.  Being able to mark values in order to detect wrong use of the generic operations on specific data structures is a simple and nice addition, IMO.

**Comment by ejgallego** [comment]
Oh indeed very good point; I was thinking more of the original context to avoid using the polymorphic operators in Coq; IMHO there we should just enforce that by hiding.
