### ISSUE TITLE
Report unbound variables before other errors

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#6381]
**Original bug ID:** 6381
**Reporter:** @dbuenzli
**Status:** feedback (set by @mshinwell on 2014-05-30T12:29:06Z)
**Resolution:** open
**Priority:** normal
**Severity:** feature
**Version:** 4.01.0
**Target version:** later
**Category:** typing
**Monitored by:** @hcarty

## Bug description

Would it be possible to always report unbound variable error before other errors ? Sometimes with optional arguments we get misleading errors. Here is an example:

```ocaml
# let f ?(opt = 2) x y = x + y;;
# f 2 zorglub 3;;
Error: The function applied to this argument has type ?opt:int -> int
This argument cannot be applied without label
```

Thanks.

**Comment by vicuna** [comment]
**Comment author:** @mshinwell

Does anyone else have any opinions on the proposal?

**Comment by vicuna** [comment]
**Comment author:** @damiendoligez

Is it worth making the typechecker even more complex? I don't find the example particularly convincing.

**Comment by vicuna** [comment]
**Comment author:** @alainfrisch

> Would it be possible to always report unbound variable error before other errors ?

I don't see how this could be done (easily).  Knowing which variable is in scope depends quite a bit on the rest of the type-checking process (think about local open, includes, inherit), so as long as the type-checker fails on the first error, I don't see how this could be implemented in general.

**Comment by dbuenzli** [comment]
Given the general scepticism I think this can be closed.
