### ISSUE TITLE
Cleanup camlinternalFormat

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#6458]
**Original bug ID:** 6458
**Reporter:** @alainfrisch
**Status:** feedback (set by @damiendoligez on 2014-07-16T14:11:26Z)
**Resolution:** open
**Priority:** normal
**Severity:** feature
**Version:** 4.02.0+beta1 / +rc1
**Category:** standard library
**Monitored by:** @jmeber @yallop

## Bug description

This module does not seem as "internal" as other camlinternalModules.  In particular, the make_printf function and the acc type could very well, and quite simply, be used in client code.  Actually, I don't think the compiler generate references to this module.

It seems its interface could be cleaned up quite a bit.  All char_set related functions seem to be used purely internally.  heter_list could go to scanf.

What about renaming the module to Format_strings, and drop its "internal" status?

**Comment by vicuna** [comment]
**Comment author:** @damiendoligez

What is "internal" about this module is that it is subject to change without notice and without much consideration of backward compatibility. What you are asking for is legitimate but it has a cost in terms of maintenance burden.

I think we should at least wait until the module has become quite stable.

**Comment by vicuna** [comment]
**Comment author:** @alainfrisch

I'm certainly not asking for any compatibility guarantee, but I see a difference between internal (==> to be used by the compiler/stdlib only) and likely to change in the future (==> there are legitimate uses, but use at your own risk).

**Comment by gasche** [comment]
@alainfrisch a new opinion on this PR after a while? It's not bad, but not terribly exciting either, so I would not personally do the work unless there is a clear use-case.

**Comment by alainfrisch** [comment]
Yeah, no, let's close it.
