### ISSUE TITLE
tokens ignored in top level command line after ';;'

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#6472]
**Original bug ID:** 6472
**Reporter:** jrrk101
**Status:** confirmed (set by @damiendoligez on 2014-07-08T08:49:30Z)
**Resolution:** open
**Priority:** low
**Severity:** tweak
**Platform:** x86_64
**OS:** OSX
**OS Version:** 10.9
**Version:** 3.12.1
**Target version:** later
**Category:** toplevel
**Monitored by:** @gasche

## Bug description

After a certain statement ending in ;; the next tokens are ignored to end of line

## Steps to reproduce

Jonathans-MacBook-Air:~ jrrk$ ocaml
        Objective Caml version 3.12.1

# let x = 65;; print_char (char_of_int x);;
val x : int = 65
# let x = 65;; hello xavier;;
val x : int = 65
#

## Additional information

4.0 series seems affected. Seems to be a parser bug.

**Comment by vicuna** [comment]
**Comment author:** @damiendoligez

It's been there for decades. Most people don't ever notice it.

**Comment by Octachron** [comment]
This is more of a specification: The double semicolon `;;` marks the end of the phrase sent to the toplevel.

**Comment by dbuenzli** [comment]
It seems the same was reported in the still open https://github.com/ocaml/ocaml/issues/8813.

Personally I see it as an issue since you cannot cut and paste code from a script into a toplevel prompt and expect the same as if you had run the script.

**Comment by pw374** [comment]
> This is more of a specification: The double semicolon `;;` marks the end of the phrase sent to the toplevel.

How about we finally change this broken specification? :p
