### ISSUE TITLE
approx_type ignores structural types

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#6478]
**Original bug ID:** 6478
**Reporter:** @lpw25
**Assigned to:** @garrigue
**Status:** confirmed (set by @garrigue on 2014-07-06T00:59:24Z)
**Resolution:** open
**Priority:** normal
**Severity:** minor
**Version:** 4.02.0+dev
**Category:** typing
**Monitored by:** @gasche

## Bug description

`approx_type` (which approximates the type of a constraint in a recursive definition) does not handle structural types. This can lead to some surprising behaviour, since using an alias of a structural type does work.

For example:

    Process ocaml-toplevel finished
            OCaml version 4.03.0+dev0-2014-05-12

    # #warnings "-10";;

    # let k = object method m : 'a. 'a -> 'a = fun x -> x end;;
    val k : < m : 'a. 'a -> 'a > = <obj>

    # let rec x =
        lazy (x#m ());
        lazy (x#m "hello");
        (k : < m : 'a. 'a -> 'a >);;
          Characters 45-52:
          lazy (x#m "hello");
                    ^^^^^^^
    Error: This expression has type string but an expression was expected of type
             unit

    # type t = < m : 'a. 'a -> 'a >;;
    type t = < m : 'a. 'a -> 'a >

    # let rec x =
        lazy (x#m ());
        lazy (x#m "hello");
        (k : t);;
          val x : t = <obj>

Ideally, the constraints in recursive definitions would be properly typed during approximation, although I assume there is some reason this is not already the case.

Even if there is a good reason this cannot be done, it is potentially confusing, so I thought it was worth creating an issue for.

**Comment by vicuna** [comment]
**Comment author:** @garrigue

Indeed, there is something wrong here.
I don't know why approx_type handles named types to start with: originally it was intended for labels and optional arguments.

**Comment by vicuna** [comment]
**Comment author:** @damiendoligez

I may be totally wrong, but I seem to remember that approx_type was extended to get better type errors for let rec.

[edit: IIRC it was extended by Alain]

**Comment by vicuna** [comment]
**Comment author:** @alainfrisch

After a quick look at the history, it seems that the only changes I did on Typecore.approx_type were related to changes in the definition of the Parsetree (no changes on the behavior).

**Comment by garrigue** [comment]
Probably worth having another look at it.
