### ISSUE TITLE
Recursive modules do not correctly handle class inheritance

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#6491]
**Original bug ID:** 6491
**Reporter:** @lpw25
**Status:** acknowledged (set by @damiendoligez on 2014-07-30T20:39:30Z)
**Resolution:** open
**Priority:** normal
**Severity:** feature
**Target version:** later
**Category:** typing
**Tags:** recmod
**Monitored by:** @gasche

## Bug description

Recursive modules can contain classes or class types which inherit from each other. However, since inheritance is done by copying the methods and values, the information only passes through one layer of inheritance. For example the `x` method is missing from `Baz.c` in the following:

    # module rec Foo : sig class type c = object method x : int end end = Foo
      and Bar : sig class type c = object inherit Foo.c end end = Bar
      and Baz : sig class type c = object inherit Bar.c end end = Baz;;
        module rec Foo : sig class type c = object method x : int end end
    and Bar : sig class type c = object method x : int end end
    and Baz : sig class type c = object  end end

Module types would suffer from the same problem, but instead it gives an error:

    # module rec Foo : sig module type c = sig val x : int end end = Foo
      and Bar : sig module type c = sig include Foo.c end end = Bar
      and Baz : sig module type c = sig include Bar.c end end = Baz;;
        Characters 111-116:
        and Bar : sig module type c = sig include Foo.c end end = Bar
                                                  ^^^^^
    Error: Illegal recursive module reference

The same could be achieved for inheritance by calling `find_class_type` on any inherited class types during `approx_class`.

**Comment by garrigue** [comment]
* There is no specification of what recursive modules should do w.r.t. class inheritance.
* I don't think we are going to the suggested behaviour anytime soon.
So I would suggest closing this one.

**Comment by lpw25** [comment]
> The same could be achieved for inheritance by calling find_class_type on any inherited class types during approx_class.

I think this would fix the issue and probably break no programs in practice. Should I make a quick PR to do this? or do you think there will be some issue with this approach.

**Comment by garrigue** [comment]
You mean, having an error rather than inferring a wrong type?
In this case I think this is fine indeed. Just have to check that this doesn't break existing programs, but I agree that would be very surprising.
