### ISSUE TITLE
Parsetree.row_field.Rtag should have constructor location

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#6499]
**Original bug ID:** 6499
**Reporter:** @whitequark
**Assigned to:** @diml
**Status:** assigned (set by @whitequark on 2017-01-06T21:26:21Z)
**Resolution:** open
**Priority:** normal
**Severity:** feature
**Version:** 4.02.0+beta1 / +rc1
**Category:** lexing and parsing

## Bug description

There's a TODO in parsetree.mli about that, but I'll file a bug for posterity anyway, since this is quite annoying.

**Comment by vicuna** [comment]
**Comment author:** @damiendoligez

It's a good idea to file a report here. TODO in source file is largely ignored, PRs here have more visibility.

**Comment by vicuna** [comment]
**Comment author:** @diml

I second this request, not having a location here is annoying. Although it seems to me that [Rinherit _] should have a location as well, for consistency. Maybe we should split the [row_field] type between a wrapper record and a [row_field_desc] type as it is done for the other nodes?

**Comment by vicuna** [comment]
**Comment author:** @whitequark

> Maybe we should split the [row_field] type between a wrapper record and a [row_field_desc] type as it is done for the other nodes?

I agree that this makes sense.

**Comment by whitequark** [comment]
Still an issue.

**Comment by Octachron** [comment]
This was fixed by #1903 as far as I can see.

**Comment by whitequark** [comment]
Ah, I missed that! Thanks.
