### ISSUE TITLE
New functions for bytes/strings

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#6500]
**Original bug ID:** 6500
**Reporter:** @alainfrisch
**Status:** feedback (set by @damiendoligez on 2014-08-20T08:24:44Z)
**Resolution:** open
**Priority:** normal
**Severity:** feature
**Category:** standard library
**Tags:** patch
**Monitored by:** braibant @whitequark

## Bug description

Some useful functions to create string (esp. String.init, which avoids the need to go through a bytes than copy it):

String.init: int -> (int -> char) -> string
Bytes.init: int -> (int -> char) -> bytes

Some more useful functions to avoid copying between bytes and string, at least explicitly (this is much lower priority, I'd say):

Buffer.sub_bytes: t -> int -> int -> bytes
Format.print_bytes: bytes -> unit
Format.print_bytes_as: int -> bytes -> unit
Lexing.from_bytes: bytes -> lexbuf
Pervasives.print_bytes_endline: bytes -> unit
Pervasives.prerr_bytes_endline: bytes -> unit
Pervasives.read_line_bytes: unit -> bytes
Pervasives.input_line_bytes: in_channel -> bytes
Scanf.from_bytes: bytes -> in_channel
Stream.of_bytes : bytes -> char t

(There are a few more in Scanf, Printf.)

## File attachments

- [mapi.patch](https://gist.githubusercontent.com/vicuna/3787db6de93d900efcc6e4e3dc49dc64/raw/3fc07d867b2c048043a3da9c429f8b7c9c118fc9/mapi.patch)

**Comment by vicuna** [comment]
**Comment author:** @alainfrisch

Commit 15029 on 4.02 (15030 on trunk) adds String.init, Bytes.init, Labels couterparts, Stream.of_byte.

**Comment by vicuna** [comment]
**Comment author:** @gasche

The attached patch implements String.mapi, and Bytes.mapi in passing. If that is all right, I'd like to commit it eventually. I also specified the iteration order of init/map/mapi: in my experience users rely on it anyway, so we cannot change it, and it's better to not worry and just document it from the start.

I think the functions you listed are important and we should provide them to have a smooth transition. I can help with the implementation -- in any case I plan to document Bytes.unsafe_to_string and Bytes.unsafe_of_string, and try to minimize use of the latter.

**Comment by vicuna** [comment]
**Comment author:** @alainfrisch

Gabriel: please commit mapi (also updating StringLabels/BytesLabels).

Also, the type bytes is really just an optimized implementation of "char array", and it thus makes sense to have the Bytes module implements all relevant operations from Array.  The ones currently missing:

val to_list: bytes -> char list
val of_list: char list -> bytes
val fold_left: ('a -> char -> 'a) -> 'a -> bytes -> 'a
val fold_right: (char -> 'a -> 'a) -> 'bytes -> 'a -> 'a
val {sort, stable_sort, fast_sort}: (char -> char -> int) -> bytes -> unit

We should also consider renaming Bytes.cat to Bytes.append.  Bytes.concat is a little bit problematic, since Array.concat also exists, but without the delimiter, and we want to keep the same name as String.

**Comment by vicuna** [comment]
**Comment author:** @damiendoligez

Most of these function types don't make sense to me: a single "bytes" argument is pretty useless, you should almost always take three arguments: bytes, offset, length.

**Comment by vicuna** [comment]
**Comment author:** kaustuv

Also worth adding: Format.pp_print_bytes. This should then also be a registered printer in the toplevel if it is invoked with -safe-string.

**Comment by yallop** [comment]
The standard library has `String.init` and `Bytes.init`, since 4.02.

**Comment by whitequark** [comment]
Still an issue.
