### ISSUE TITLE
Type-based selection for rebinding constructors of extensible types

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#6514]
**Original bug ID:** 6514
**Reporter:** @alainfrisch
**Status:** acknowledged (set by @damiendoligez on 2014-08-18T13:12:39Z)
**Resolution:** open
**Priority:** low
**Severity:** feature
**Target version:** later
**Category:** typing

## Bug description

By uniformity with the type-based selection of constructors in expression and patterns, the following should be accepted:

type t = ..
type s = ..

type t += A
type s += A

type t += B = A

**Comment by vicuna** [comment]
**Comment author:** @alainfrisch

https://github.com/ocaml/ocaml/pull/1706

**Comment by garrigue** [comment]
Seems I missed this one. While this makes sense, I'm a bit concerned that this selection has semantics implications: for extensible types, two constructors with the same name are _not_ equivalent.
```ocaml
type t = ..
module A = struct type t += C end
module B = struct type t += C end
open A
let a : t = C
open B
let b : t = C
let e = (a = b) ;;
val e : bool = false
```
Here we are talking of real overloading. This is already bad to have it inside expressions, but suggesting to allow it inside types to is just one more degree.
