### ISSUE TITLE
Reveal the type of Unix.inet_addr

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#6568]
**Original bug ID:** 6568
**Reporter:** vbmithr
**Status:** acknowledged (set by @damiendoligez on 2014-09-22T19:12:18Z)
**Resolution:** open
**Priority:** normal
**Severity:** feature
**Version:** 4.02.0+beta1 / +rc1
**Target version:** undecided
**Category:** standard library
**Tags:** patch

## Bug description

It would be useful to expose the type Unix.inet_addr, see related patch.

## Additional information

https://github.com/ocaml/ocaml/pull/101

**Comment by vicuna** [comment]
**Comment author:** @gasche

Postponing this to 4.04 as was decided on github.

**Comment by stedolan** [comment]
(Closing for the reasons given by @alainfrisch and @mshinwell in #101)
