### ISSUE TITLE
Allow _ in module type constraints

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#6620]
**Original bug ID:** 6620
**Reporter:** @yallop
**Status:** acknowledged (set by @damiendoligez on 2014-12-17T23:06:29Z)
**Resolution:** open
**Priority:** normal
**Severity:** feature
**Category:** typing
**Tags:** junior_job

## Bug description

For uniformity, and in the interests of not having to name things that aren't used, it'd be useful to be able to leave type parameters in module type constraints unnamed:

   module type S = sig type _ t end
   module type T = S with type _ t = unit

**Comment by vicuna** [comment]
**Comment author:** @damiendoligez

That's not very good for readability.

Ideally, you'd give your type variable a name that documents the role of the type parameter, but unfortunately that's not in the OCaml culture.

**Comment by yallop** [comment]
This is fixed in `trunk` (perhaps by the switch to Menhir?):

```
# module type S = sig type _ t end;;
module type S = sig type _ t end
# module type T = S with type _ t = unit;;
module type T = sig type _ t = unit end
```
