### ISSUE TITLE
Error message for module used where a module type is expected is confusing

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#6633]
**Original bug ID:** 6633
**Reporter:** @whitequark
**Status:** acknowledged (set by @damiendoligez on 2014-12-22T20:51:24Z)
**Resolution:** open
**Priority:** normal
**Severity:** feature
**Version:** 4.02.1
**Target version:** undecided
**Category:** typing
**Monitored by:** @gasche

## Bug description

E.g.:

equal.ml:

      module type Equal = sig .. end

foo.ml:

      module Foo = Functor (Equal : Equal) -> struct .. end

Actual: `Error: Unbound module type Equal`
Expected: something like `Equal is a module and it cannot be used as module type`

**Comment by vicuna** [comment]
**Comment author:** @garrigue

The message is correct: there is indeed no module type Equal in scope inside foo.ml.
Moreover, since the name spaces for modules and module types are distinct, the fact there is a module Equal does not seem to be relevant here. I don't see in which way the suggested message would improve.
I we were to visit all imported modules, one could attempt to say that there is indeed a module type Equal.Equal, but looking for it can be very expensive.

**Comment by vicuna** [comment]
**Comment author:** @whitequark

Well, I suppose it makes sense. I'm reporting on behalf on someone from IRC, who found it confusing. I do find the fact that modules and module types have different namespaces confusing, as well.

**Comment by vicuna** [comment]
**Comment author:** @damiendoligez

Maybe it would make sense to append a note saying that there is a module by that name, but it's not a module type, as an extension of the spell-checking idea.

Indeed all these namespaces are sometimes confusing.

**Comment by vicuna** [comment]
**Comment author:** @whitequark

I like this solution.

**Comment by whitequark** [comment]
Still an issue.

**Comment by garrigue** [comment]
Anybody has a PR for this?

**Comment by Drup** [comment]
(I think we should have a label for not-so-difficult-to-improve error messages)

**Comment by gasche** [comment]
We have `newcomer-job-advanced` for things that are accessible to people unfamiliar with the compiler codebase, but that still require an "advanced" OCaml programming level and/or dealing with a somewhat complex problem. If you think it applies here, it could act as a superset of your label idea. (And if it does not, it's not clear what "not so difficult" means.)

(Usually when we apply the label we also explain what said newcomer should look at to attack the issue: the broad lines of what we would do ourselves to solve it, starting with which files to look for modification or documentation.)

**Comment by Drup** [comment]
Sounds good. Can you add it ?

I think this one is pretty straightforward: the error message is created in `Typemod.report_error`. When formatting such lookup module type error, we simply need to look in the environment if a module of the same name exists and return an "advice" (attached to the original error). A similar approach is already implemented for spelling suggestions.
