### ISSUE TITLE
custom tags not handled for some elements

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#6707]
**Original bug ID:** 6707
**Reporter:** @kenichi-asai
**Assigned to:** @zoggy
**Status:** confirmed (set by @gasche on 2014-12-12T14:50:47Z)
**Resolution:** open
**Priority:** normal
**Severity:** feature
**Platform:** Apple
**OS:** MacOS X
**OS Version:** 10.8
**Version:** 4.01.0
**Category:** ocamldoc
**Monitored by:** @gasche @hcarty

## Bug description

It appears that custom tags are not handled in:
- the very first comment,
- special comments between elements, and
- comments for type constructors, etc.
cf. Sections 15.2.1 and 15.2.3 of
http://caml.inria.fr/pub/docs/manual-ocaml/ocamldoc.html
I would request that custom tags are handled uniformly in all the elements.

## Steps to reproduce

Attached file contains an example where documents are written both in English (after @en tag) and in Japanese (after @ja tag).  By passing "-lang en" or "-lang ja" argument to ocamldoc, I want to select the corresponding documents.  However, the documents in the html-* directories obtained by executing "make" are not as expected.
- the first text "module header in *" is ignored, but it should appear in index.html.  (If I remove "@en", the text appears there.)
- the two "Session header" texts are ignored, but they should appear in Test.html.
- the texts for "A" and "B" are ignored, but they should appear in Test.html.

## File attachments

- [test.tar.gz](https://gist.githubusercontent.com/vicuna/9fdf8196d5a5b41d49ff76c00875fea6/raw/6c414ad28940c8afcece1dc718d595112d4f8e77/test.tar.gz)

**Comment by vicuna** [comment]
**Comment author:** @gasche

I reproduced the issue -- I also tried to see how to fix it, but I don't understand ocamldoc's internals well enough for that. It would be interesting to have a workaround of the form "just overload this other method and you'll be able to override this default behavior".

**Comment by kenichi-asai** [comment]
I tested the situation in 4.11.0+alpha1.  

> * the first text "module header in *" is ignored, but it should appear in index.html.  (If I remove "@en", the text appears there.)

It appears this case is properly handled now.  I did not see the problem arises any more.

> * the two "Session header" texts are ignored, but they should appear in Test.html.
> * the texts for "A" and "B" are ignored, but they should appear in Test.html.

The problem persists in these two.  In both cases, if I remove "@en", the text appears there.

**Comment by kenichi-asai** [comment]
I tested the situation in 4.12.0.  I reported last year that the first problem went away in 4.11.0+alpha1, but I was wrong.  All the three problems persist in 4.12.0.

**Comment by Octachron** [comment]
Note that the feature is unlikely to be ever implemented in ocamldoc. Ocamldoc is in maintenance mode and further development efforts are focused on odoc.
