### ISSUE TITLE
Specify the filename to use for locations

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#6718]
**Original bug ID:** 6718
**Reporter:** @diml
**Status:** confirmed (set by @damiendoligez on 2014-12-16T20:08:35Z)
**Resolution:** open
**Priority:** normal
**Severity:** feature
**Category:** compiler driver
**Tags:** junior_job
**Monitored by:** @whitequark @gasche

## Bug description

We'd like to be able to specify the filename to use in locations. Basically having some command line argument [-loc-filename fname] that would be the same as adding this at the beginning of the file:

```
# 1 "fname"
```

This would replace some hackery used in syntax extensions of the core suite to add prefixes to filenames:

  https://github.com/janestreet/herelib/blob/master/lib/pa_here.ml

We do this because ocamlc/ocamlopt is invoked in the sub-directory of the library and we only get the basename in the location. But this hack doesn't set the filename for [assert], [__LOC__], ... and wouldn't work well with this proposal: https://github.com/ocaml/ocaml/pull/126.

We could of course generate the line directive with a pre-processor but it'd be just another hack and other Makefile-based build system might benefit from this too.

**Comment by vicuna** [comment]
**Comment author:** @damiendoligez

I'd like to second this feature request. I have a program (tlapm) whose makefiles would benefit.

**Comment by vicuna** [comment]
**Comment author:** @whitequark

Is this really a good idea? Most languages I know, starting with C, embed the full path to the module into the location. Not only this is much less ambiguous (where does this "src/cset.ml" come from?), but also easier to use by tools. ocamldebug in particular has to rely on a crutch to locate the sources, currently.

**Comment by vicuna** [comment]
**Comment author:** @gasche

If/when we do this we probably want OCAMLPARAM handling as well.

**Comment by vicuna** [comment]
**Comment author:** @diml

@whitequark: you can already do that in OCaml, just pass the full filename to ocamlc/ocamlopt instead of the relative one

@gashe: actually it's not obvious to me we want it in OCAMLRUNPARAM. This would be a per-file setting as it would always depend on the filename. Another possibility is to pass a format string.

**Comment by vicuna** [comment]
**Comment author:** @whitequark

@dim, my point is that I think ocamlc should always expand the path, fixing this issue and others. Alternatively it could be an OCAMLPARAM setting (and possibly also a command-line switch) that forces path expansion, if the change would be too invasive otherwise--I think it's a much better solution than providing the ability to change the filename in arbitrary ways.

**Comment by vicuna** [comment]
**Comment author:** @diml

Having the full path is indeed good for local development/debugging but it shouldn't be the default. For instance it is often wrong for binary distribution. Having it as an OCAMLPARAM setting seems good, but it doesn't supersede this feature. This is really for projects that don't run all tools from their root directory.

**Comment by vicuna** [comment]
**Comment author:** @whitequark

The current behavior is also incorrect for binary distribution (or anything really), because it does not allow to unambiguously locate the source. Ideally, the path would include the package name and then the path from the root of the package.

Hm, and your suggestion actually handles that. Perhaps it is a good idea after all.

**Comment by whitequark** [comment]
Still an issue.

**Comment by nojb** [comment]
cc @jeremiedimino

**Comment by ghost** [comment]
I guess that'd still be useful, though I ran out of steam on this one. Additionally, since Dune run compilation commands from the root of the workspace it is less of an issue for Dune projects and so this seems less high priority to me.

Unless someone wants to take ownership of this, I'll leave the stable label and let the issue get closed.

**Comment by ghost** [comment]
I removed the `newcomer-job` tag though because it's not that simple.
