### ISSUE TITLE
Pass -g to ocamlc compiling C files when tagged with "debug"

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#6720]
**Original bug ID:** 6720
**Reporter:** @whitequark
**Status:** acknowledged (set by @damiendoligez on 2017-03-01T13:32:54Z)
**Resolution:** reopened
**Priority:** normal
**Severity:** tweak
**Category:** compiler driver
**Tags:** patch
**Monitored by:** @whitequark

## Bug description

E.g.:

    flag ["c"; "compile"; "debug"] & A"-g";

## File attachments

- [ocamlc-g.patch](https://gist.githubusercontent.com/vicuna/7b765f5a2e1d00fe8df7fe52628c55ad/raw/e8e29f2818008c354be49ed59d9ef5281301ef6e/ocamlc-g.patch)

**Comment by vicuna** [comment]
**Comment author:** @gasche

Implemented in trunk.

**Comment by vicuna** [comment]
**Comment author:** @whitequark

This is actually not useful, because ocamlc -g does not pass -g through to the compiler.

**Comment by vicuna** [comment]
**Comment author:** @whitequark

Attached a patch which fixes this.

**Comment by vicuna** [comment]
**Comment author:** @gasche

Fixed in trunk.

**Comment by vicuna** [comment]
**Comment author:** @whitequark

I think this needs to be backported to 4.02, as 6641 and 6720 was also backported.

**Comment by vicuna** [comment]
**Comment author:** @gasche

I was uneasy about pushing this to the stable branch because it's not just a new feature but changes an existing behavior (that people may or may not rely). I just did it, though.

**Comment by vicuna** [comment]
**Comment author:** @alainfrisch

The MSVC compiler doesn't recognize "-g".  It doesn't fail on it, but simply report a warning: 

  cl : Command line warning D9002 : ignoring unknown option '-g'

I don't know if it is preferable to simply do nothing with MSVC ports, or rather to pass another debug-related option.  I reopen the ticket so that we don't loose track of this.

(Note that -o also produces a warning:

  cl : Command line warning D9035 : option 'o' has been deprecated and will be removed in a future release
)

**Comment by vicuna** [comment]
**Comment author:** @damiendoligez

Note that this is not about ocamlbuild any more, but about the interaction between ocamlc/ocamlopt and the C compiler.

**Comment by xavierleroy** [comment]
The current situation is that `-g` is passed on to the C compiler, unless it is MSVC, in which case nothing is passed:
https://github.com/ocaml/ocaml/blob/37c5bd87a9f6a1e543517e6815feea304f58bbb3/utils/ccomp.ml#L113

If someone cares about passing the right options to MSVC, go ahead and submit a pull request, it's a 1-line change.  Meanwhile, I'll close this issue as pretty well addressed already.
