### ISSUE TITLE
Do not display warning 40 in a non-ambiguous match

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#6731]
**Original bug ID:** 6731
**Reporter:** @whitequark
**Status:** acknowledged (set by @damiendoligez on 2014-12-23T17:01:55Z)
**Resolution:** open
**Priority:** normal
**Severity:** feature
**Version:** 4.02.1
**Category:** middle end (typedtree to clambda)
**Monitored by:** @gasche

## Bug description

The following match contains no ambiguity:
```ocaml
let lwt_log_level_to_enum =
  function
  | Lwt_log.Debug -> 0
  | Info -> 1
  | Notice -> 2
  | Warning -> 3
  | Error -> 4
  | Fatal -> 5
```
However, warning 40 is still displayed.

**Comment by vicuna** [comment]
**Comment author:** @lpw25

I suspect this gets quite tricky for nested patterns, which is why we give no special treatment to sibling patterns (e.g. there was never any equivalent to the { Foo.bar; baz } record syntax). For similar reasons patterns like this will give a principality warning if the patterns require disambiguation.

**Comment by vicuna** [comment]
**Comment author:** @gasche

> I suspect this gets quite tricky for nested patterns

Barring GADTs, is there a fundamental reason why that would be trickier than nested record constructions?

**Comment by vicuna** [comment]
**Comment author:** @lpw25

>  Barring GADTs, is there a fundamental reason why that would be trickier than nested record constructions? 

I'm not sure what you mean by "nested record constructors".

**Comment by vicuna** [comment]
**Comment author:** @gasche

It seems that { x = { a; b }; y; } displays the same sort of (non-)difficulties as the clauses (X A -> ... | X B -> ... | Y -> ... ).

**Comment by vicuna** [comment]
**Comment author:** @lpw25

> It seems that { x = { a; b }; y; } displays the same sort of (non-)difficulties as the clauses (X A -> ... | X B -> ... | Y -> ... ). 

Well `{a; b}` is a single expression/pattern, so `a` and `b` can be reliably linked together syntactically. The trick which turns `{ Foo.a; b }` into `{Foo.a; Foo.b}` can be done completely syntactically.

Whereas `A` and `B` in your second example are two separate patterns that are in some sense only related by their types. You can try to link them together via the idea that two patterns with the same type and the same "head" (`X` in your example) must have "sub-patterns" (`A` and `B` in your example) with the same type, but that clearly fails in the presence of things like existentials.

**Comment by trefis** [comment]
I don't think this is going to change in the near future (nor do I think that it should).
So I'm closing.

**Comment by whitequark** [comment]
Yes, on reflection I agree that this would not be a desirable feature due to the complex rules that would be necessary for disambiguation.
