### ISSUE TITLE
`as` ignored on types containing universal variables

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#6745]
**Original bug ID:** 6745
**Reporter:** @lpw25
**Assigned to:** @garrigue
**Status:** assigned (set by @garrigue on 2015-11-30T08:46:58Z)
**Resolution:** open
**Priority:** normal
**Severity:** minor
**Category:** typing
**Monitored by:** @hcarty

## Bug description

It seems that an `as` constraint on a type containing a univar is silently ignored:

    # type 'a r = { x: 'b. 'b list as 'a };;
    type 'a r = { x : 'b. 'b list; }

compared to:

    # type 'a r = { x: 'b. int list as 'a };;
    type 'a r = { x : 'a; } constraint 'a = int list

**Comment by vicuna** [comment]
**Comment author:** @garrigue

I have opened a pull-request:
https://github.com/ocaml/ocaml/pull/322

However, it is not easy to get the right behavior without breaking symmetry, or requiring multiple passes on the whole syntax tree (as in SML).
Maybe this should rather go with a rework of type variable scope.

**Comment by lpw25** [comment]
This is still an issue
