### ISSUE TITLE
singly unlinkable cma orders silently allowed

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#6778]
**Original bug ID:** 6778
**Reporter:** dsheets
**Status:** acknowledged (set by @damiendoligez on 2015-02-18T22:58:36Z)
**Resolution:** open
**Priority:** normal
**Severity:** minor
**Version:** 4.02.1
**Category:** compiler driver
**Duplicate of:** #3488
**Has duplicate:** #7566
**Monitored by:** @whitequark @gasche elfring @alainfrisch

## Bug description

.cma files retain the order used in their construction from a command-line. This order is then used during linking even when only a subset of units are used from the archive. Dependencies from early units to later units in a cma are permitted by the compiler. Unfortunately, these cma orders can never link because the later units are not in scope at the time the earlier units are read.

It should be a warning or error to attempt to produce an cma which is unlinkable with only a single provision to a compile command.

## Steps to reproduce

1. Run `make`
2. Run `make reverse-cma`

## File attachments

- [cma-order.tar.gz](https://gist.githubusercontent.com/vicuna/c9422557c2246a6d5593e36e1d659b03/raw/91b91202ba609304f0e76b08a19f7826fc961a4c/cma-order.tar.gz)

**Comment by elfring** [comment]
I am still curious how affected software components will be improved also for this issue.

**Comment by whitequark** [comment]
Still an issue AFAIK.

**Comment by damiendoligez** [comment]
When we build a `.cma`, do we have easy access to the dependency relation between the `.cmx` that go into it?

**Comment by dbuenzli** [comment]
For each object you are trying to put in the archive you [know](https://github.com/ocaml/ocaml/blob/fb99b2be83b6edd4d9bf97c45e6af32c8614d97f/file_formats/cmx_format.mli#L42-L43) which interfaces it imports so you can certainly check that the user provided order makes sense when the archive is built.

**Comment by nojb** [comment]
I guess we could perform the same check that is done when linking an executable but at library-construction time, assuming all modules that go into the library are being "linked".

**Comment by lthls** [comment]
I've made a branch with a possible implementation of this check [here](https://github.com/lthls/ocaml/tree/library_order_check).
It only checks the order for bytecode libraries (mirroring the behaviour of the link check, which only gives helpful errors in bytecode).
I can turn it into a PR if needed.

**Comment by nojb** [comment]
> I can turn it into a PR if needed.

I think that would be a good idea. I have a couple of questions but I'll wait until there is a PR for review.
