### ISSUE TITLE
Make ocamlc -c recognize .cpp files

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#6798]
**Original bug ID:** 6798
**Reporter:** @whitequark
**Status:** acknowledged (set by @damiendoligez on 2015-04-21T15:29:27Z)
**Resolution:** open
**Priority:** normal
**Severity:** feature
**Category:** compiler driver
**Duplicate of:** #5823
**Related to:** #5254
**Monitored by:** @ygrek @hcarty

## Bug description

Currently a horrible workaround is needed: https://stackoverflow.com/questions/21728826/building-c-code-with-ocamlbuild

Telling ocamlc to treat .cpp files by passing them to $(BYTECC) together with -x cpp option (overridable default at configure time) seems much better.

The commands to link the standard library (like -lstdc++) could also be present in Makefile.config / Config.ml, so that user code would not have to replicate detection in every package.

**Comment by vicuna** [comment]
**Comment author:** @ygrek

related ocaml/ocaml#5823
Same wish - consider .cxx and .cc also

**Comment by whitequark** [comment]
Still an issue.

**Comment by ygrek** [comment]
I think first step is simple - just treating file extensions as C source - and then it will be user responsibility to make C compiler actually a c++ compiler (e.g. via `-ccopt -xc++`)
The second part - detecting c++ compiler in configure and supplying -lstdc++ is more involved, so can be left for later (moreover c++ is not required by ocaml build itself, so it will raise more questions)

**Comment by ygrek** [comment]
Still want :)

**Comment by xavierleroy** [comment]
> Still want :)

I'm afraid you'll have to submit a PR yourself, since nobody else seems to care.
