### ISSUE TITLE
simplify using gadt with lambda

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#6800]
**Original bug ID:** 6800
**Reporter:** @hhugo
**Status:** confirmed (set by @damiendoligez on 2015-03-03T20:15:36Z)
**Resolution:** open
**Priority:** normal
**Severity:** feature
**Version:** 4.02.1
**Target version:** undecided
**Category:** typing
**Related to:** #6806
**Monitored by:** @gasche @yallop @hcarty

## Bug description

Would it be possible to have the `fail1` add/or `fail2` to be accepted by the typer ?
```ocaml
type _ t =
  | Int : int t
  | String : string t

(* This works as expected *)
let work1 (type s) (x : s t) : s =
  match x with
  | Int -> 0
  | String -> ""

let (>>=) : 'a -> ('a -> 'b) -> 'b = fun x f -> f x

(* This doesn't *)
let fail1 (type s) (x : s t) : s =
  x >>= fun x ->
  match x with
  | Int -> 0
  | String -> ""

(* giving a hint for the type of x doesn't work *)  
let fail2 (type s) (x : s t) : s =
  x >>= fun x ->
  match (x : s t) with
  | Int -> 0
  | String -> ""

(* giving a hint for the return of the match works.
   however the following does not because the first
   case got typed first *)
let fail3 (type s) (x : s t) : s =
  x >>= fun x ->
  match x with
  | Int -> 0
  | String -> ("" : s)

let work2 (type s) (x : s t) : s =
  x >>= fun x ->
  match x with
  | Int -> (0 : s)
  | String -> ""
```
## File attachments

- [prefix_type_constraint.diff](https://gist.githubusercontent.com/vicuna/038a78059848f4e49f00a28d60d7d3dc/raw/366203fcbb473b6761898e336f7edd1399f49f03/prefix_type_constraint.diff)

**Comment by vicuna** [comment]
**Comment author:** @gasche

Hugo's question is about expected type propagation, but one think I would like is to be able to write "fun x .. z : ty -> ..." to signify the expected return type of a function abstraction. This would allow to *conveniently* write the GADT-annotation at the proper place here, but would also be helpful in other situations. Note that "fun x .. z -> ( ... : ty )" is available but doesn't scale as well in terms of readability.

**Comment by vicuna** [comment]
**Comment author:** @damiendoligez

As far as I can tell, the "proper place" for a GADT annotation is around the `match` itself, which suggests the we should introduce a syntax for type annotations where the type comes first: instead of
```
  (expr : type)
```
one could write
```
  (type ??? expr)
```
The problem is, I don't know what kind of punctuation (or keyword) would be appropriate for this.

**Comment by vicuna** [comment]
**Comment author:** @gasche

Not quite: GADT annotations need to share a type constructor (the "type a" kind of variables) between the scrutinee of the match and the return type of the clauses. This cannot be done a posteriori if the scrutinee is already in context, so it occurs on fun-bindings (sometimes artificially introduced for this purpose, it is the so-called "convoy pattern") rather than the match itself.

**Comment by vicuna** [comment]
**Comment author:** @hhugo

Also
```ocaml
let work3 (type s) f g (x : s t) : s =
  x >>= fun x ->
  match x with
  | Int -> f 0 
  | String -> g "";;

let fail4 (type s) f g (x : s t) : s =
  x >>= fun x ->
  match x with
  | Int -> f 0 
  | String -> "";;

let fail5 (type s) (f : int -> int) g (x : s t) : s =
  x >>= fun x ->
  match x with
  | Int -> f 0 
  | String -> g "";;

let f_infered_with_s (type s) f (x : s t) : s =
  x >>= fun x ->
  match x with
  | Int -> (f 0 : s) 
  | String -> "";;

let f_infered_with_int (type s) f (x : s t) : s =
  x >>= fun x ->
  match x with
  | Int -> (f 0 : int :> s) 
  | String -> "";;
```

**Comment by vicuna** [comment]
**Comment author:** @alainfrisch

> I would like is to be able to write "fun x .. z : ty -> ..."

I fully support that.  Even more importantly, it would also be useful to allow specifying the argument and/or return types in "function p1 -> e1 | ... | pn -> en" with something lighter than "((function ...) : t -> s)".  Specifying input/output types has become more important since the introduction of type-based disambiguation for constructors.   At least, if we had a prefix form for type constraint as Damien suggests, this be already be better.

>  (ty ??? expr)

Even if we find a good pick for "???", I'm afraid this would result in many conflicts in the grammar.

What about:
```
  (: ty) expr
```
?


With it, one could write e.g.:
```
  (: arg_ty -> ret_ty) function
    | p1 -> e1
    | ...
```

**Comment by vicuna** [comment]
**Comment author:** @garrigue

I concur. Both `fun x ... z : ty -> ...` and `(: ty) ...` make sense.
Note however that there is a slight difficulty the later, as if we see `(: ty)` as a function, only a simple expression can occur after it. I.e., you would have to write:
```
 (: arg_ty -> ret_ty) (function
    | p1 -> e1
    | ...)
```
From a parsing point of view there is of course no problem in being more laxist.
Anyway, I kind of see that as a detail, since the `fun x ... z : ty -> ...` covers most of the cases not handled yet.

**Comment by vicuna** [comment]
**Comment author:** @alainfrisch

Note that "fun x : ty -> ..." has been implemented as part of #6806.

**Comment by vicuna** [comment]
**Comment author:** @alainfrisch

Attached a patch which implements prefix type constraint syntax "(:ty) expr".  This is not parsed as function application, and it allows "expr" to be e.g. a pattern matching or a function:

  (: _ -> int) fun x -> x;;

**Comment by garrigue** [comment]
I think that #6806 solves this issue. Or is there something left?

**Comment by gasche** [comment]
Well I still agree that `(: ty) expr` would be nice syntax. @alainfrisch, would you like to open a Pull Request to propose it? (Or we could discuss with other people to see if we want the syntax before implementing, which I suppose would require a fair amount of rebasing work, at least in the parser.)

**Comment by garrigue** [comment]
I would not characterise `(: ty) expr` as nice.
Is it supposed to look like a C coercion?
Then I suppose we would also need `(:> ty)` and `(: ty :> ty')` for completeness, but what is the real benefit compared to the current syntax, which at least makes the target of the coercion explicit?

**Comment by gasche** [comment]
Whenever the type is small and the expression is large, it is very useful to be able to annotate with the type going first. See the example of @alainfrisch above about being able to write `(: foo -> bar) function ...`, which is not possible with current syntax.

This would also be useful with the new binding operators `let* p = def in body` (typically for monadic bind): for now we do not support the syntax `let* p : ty = def in body`, which is a bit tricky as it is unclear whether we should expect the type of `p` (eg. `'a`) or the type of `def` (eg. `'a m`). On the other hand, `let* p = (: ty) def in body` is an almost-readability-preserving version of the same thing: it's a completely local reformulation, whereas `let* p = (def : ty) in body` is impractical in many cases (the type is too far from the place where it would improve readability).
