### ISSUE TITLE
Check that loaded dll*.so have matching ABI

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#6807]
**Original bug ID:** 6807
**Reporter:** @whitequark
**Status:** acknowledged (set by @damiendoligez on 2015-03-18T13:58:02Z)
**Resolution:** open
**Priority:** normal
**Severity:** feature
**Category:** dynlink and natdynlink
**Monitored by:** @diml @ygrek @hcarty

## Bug description

Every once in a while (quite often actually) I have a variation on this conversation:

<xxx> [ 1125.114750] camlp4[4634]: segfault at 41 ip 00007f505b8b7bd0 sp 00007fff24a3f610 error 4 in dllbigarray.so[7f505b8b5000+5000]
<xxx> unsure what to make of this (from dmesg)
<xxx> [trying to compile a project on debian]
<whitequark> xxx: most likely you are trying to use opam with camlp4 from a different switch
<whitequark> or system camlp4
<whitequark> try doing `which camlp4` and `echo CAML_LD_LIBRARY_PATH`
<whitequark> if one refers to opam and other does not, you have a problem
<xxx> they do, thanks

This is very confusing to a newcomer who does not understand the intricacies of OCaml's runtime system. Yet it would be very easy to look up a symbol inside a dll and verify that it matches a symbol inside the runtime, thus verifying that the ABI matches.

This mechanism would be imperfect, since you can't easily fingerprint a C library ABI, but even if the fingerprint would be just the compiler version, it would fix the all the failures of this kind I've seen.

**Comment by vicuna** [comment]
**Comment author:** @damiendoligez

FTR this looks like a good idea.

**Comment by whitequark** [comment]
Still an issue.
