### ISSUE TITLE
Provide Thread.set_uncaught_exception_handler

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#6813]
**Original bug ID:** 6813
**Reporter:** @whitequark
**Assigned to:** @diml
**Status:** assigned (set by @diml on 2015-03-14T10:21:20Z)
**Resolution:** open
**Priority:** normal
**Severity:** feature
**Target version:** 4.07.0+dev/beta2/rc1/rc2
**Category:** otherlibs
**Monitored by:** @hcarty

## Bug description

Original summary was: Uncaught exceptions inside threads don't trigger handler set via Printexc.set_uncaught_exception_handler

See summary.

**Comment by vicuna** [comment]
**Comment author:** @diml

I'm not sure uncaught exceptions inside threads should call the handler set via [Printexc.set_uncaught_exception_handler]: the doc says it is executed after [at_exit] handlers and doesn't require the callback to be thread-safe.

On the other hand it's easy to add a [Thread.set_uncaught_exception_handler]. For multi-threaded programs the handler should probably print the thread id so it make sense to have two different functions.

**Comment by vicuna** [comment]
**Comment author:** @whitequark

That would work, indeed.

**Comment by vicuna** [comment]
**Comment author:** @diml

I had another look at this, it should be simpler than the global uncaught exception handler given that the exception is caught on the OCaml side. Do you think you could submit a PR for this? I can review it

**Comment by vicuna** [comment]
**Comment author:** @whitequark

I don't have time for this.

**Comment by whitequark** [comment]
Still an issue.

**Comment by whitequark** [comment]
Still an issue.

**Comment by gasche** [comment]
If we wait again for a few years to fix this issue, it will probably happen on the Multicore runtime. I wonder how uncaught exceptions are handled there; @kayceesrk, @Engil?

**Comment by abbysmal** [comment]
@gasche On Multicore, uncaught exceptions in (sys)threads are handled in the same way.
There is a default handler around every `Thread.t` created through `Thread.create`, calling back to `caml_thread_uncaught_exception` to print the backtrace and thread id.

I think the proposal to add `Thread.set_uncaught_exn` works and it may be easy enough to implement:
- In Multicore, how do we handle this in a multi-domains, multi-systhreads setting? I think this could survive as a global, assuming users are making sure the default handler is set only once, by one domain. We can just _CAS_ it away as well.
- In both trunk and Multicore: this handler should not raise an exception. I think we can have the suggested `Thread.set_uncaught_exception_handler` install a default handler as well on top of it. (in the same way it is done in `Thread.new`, except for the custom handler itself.)

As far as Multicore is concerned, this is different for the `Domain` API: uncaught exception within a `Domain` are only propagated on `join`.
The custom default exception handler is only called when such exception are propagated to the initial domain if I'm not mistaking. (@kayceesrk may confirm this)

**Comment by gasche** [comment]
Thanks for the answer. Here is what I understand:
- domains propagate uncaught exceptions to their "joiner", so there is no need for a domain-specific mechanism
- for threads the question is the same on Multicore and non-Multicore, we want a runtime global (not domain-local) that stores the current thread-exception-handler.

Would you by chance be interested in submitting a PR to implement this?

**Comment by abbysmal** [comment]
Sure enough, I will give it a try in the next few days.

**Comment by Octachron** [comment]
There is still some planned work in OCaml 5 (after 5.0)  to better handle uncaught exceptions on both threads and domains.

**Comment by dbuenzli** [comment]
There's an issue and discussion here https://github.com/ocaml/ocaml/issues/11074

**Comment by dbuenzli** [comment]
Albeit deemed [unsatisfactory](https://github.com/ocaml/ocaml/issues/11074#issuecomment-1099998167), formally OCaml 5 provides that. I think this can be closed. https://github.com/ocaml/ocaml/issues/11074 has a larger discussion on trying to improve things.

**Comment by gasche** [comment]
Thanks!
