### ISSUE TITLE
Recursive signatures

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#6818]
**Original bug ID:** 6818
**Reporter:** @yallop
**Status:** acknowledged (set by @damiendoligez on 2015-06-15T15:07:29Z)
**Resolution:** open
**Priority:** normal
**Severity:** feature
**Category:** typing
**Related to:** #4899
**Monitored by:** runhang

## Bug description

It would be useful to have support for recursive signatures.  The most common need is in code involving first-class modules, where I'd like to write

```ocaml
   module type rec R =
   sig
     val f : (module R) -> unit
   end
```

Of course, there's a workaround, but it's rather clunky:

```ocaml
   module rec R :
   sig
      module type T =
      sig
        val f: (module R.T) -> unit
      end
   end = R
```

Now that we have both recursive and non-recursive type bindings it would be more uniform to also support both recursive and non-recursive module type bindings.

**Comment by vicuna** [comment]
**Comment author:** @yallop

PR #4899 is similar, but suggests changing the semantics of the existing 'module type' construct to support recursion.  As Jacques said, that's not a workable approach, since it breaks backwards compatibility.  The approach I'm proposing here -- adding an optional 'rec' -- is entirely backwards compatible.

**Comment by smuenzel** [comment]
I don't believe this should have been closed

**Comment by gasche** [comment]
#14743 shows that the type-checker does not work well with recursive signatures today. This class of issue should probably be looked at carefully (solved ?) before we consider making them easier to use in practice.
