### ISSUE TITLE
Feature wish: ocamldebug-breakpoints:    break  [ @ module ] function

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#6825]
**Original bug ID:** 6825
**Reporter:** oliver
**Status:** feedback (set by @xavierleroy on 2015-03-31T08:15:51Z)
**Resolution:** open
**Priority:** normal
**Severity:** feature
**Platform:** ./.
**OS:** ./.
**OS Version:** ./.
**Version:** 4.02.1
**Category:** tools (ocaml{lex,yacc,dep,debug,...})

## Bug description

Very helpfu would be, if it's possible to set breakpoints also this way:

break [ @ module ] function

for example

break @ main foobar

**Comment by vicuna** [comment]
**Comment author:** oliver

This feature-wish is meant in the following way:


One restriction of 
"break function"
is: "(...) this command cannot be used at the very beginning of the program execution (...)" (chapter 16.5 of refman).

I hope that with implementing the 
break [ @ module ] function
this restriction somehow can be kicked out.

**Comment by vicuna** [comment]
**Comment author:** @xavierleroy

Normally, "break Main.foobar" should work.

The restriction (wait until module Main is initialized) cannot be lifted.

**Comment by xavierleroy** [comment]
Closing, since "The restriction (wait until module Main is initialized) cannot be lifted.".
