### ISSUE TITLE
Get rid of #ml from config/Makefile

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#6860]
**Original bug ID:** 6860
**Reporter:** @whitequark
**Status:** acknowledged (set by @damiendoligez on 2015-05-08T21:08:37Z)
**Resolution:** open
**Priority:** normal
**Severity:** feature
**Version:** 4.02.2+dev / +rc1
**Target version:** undecided
**Category:** configure and build/install
**Monitored by:** @gasche

## Bug description

Currently, #ml in config/Makefile require using sed[1] in configuration scripts instead of variables[2]. It's only used for ocamlmklib and it should not be hard to make it depend on the Config module.

[1]: https://github.com/whitequark/opam-android/blob/master/packages/ocaml-android32.4.02.2/opam#L6
[2]: https://github.com/whitequark/opam-android/blob/master/packages/ocaml-android32.4.02.2/files/config/Makefile.in#L3

**Comment by vicuna** [comment]
**Comment author:** @damiendoligez

As far as I know, this #ml annotation is for ocamlbuild. What I'm not sure is if it's still used or if it was only used by the ocamlbuild-based build of ocaml itself. @gasche?

**Comment by vicuna** [comment]
**Comment author:** @whitequark

I have specifically looked at the #ml annotation when I was doing the Android port and it's only used for ocamlmklib. ocamlmklib was a part of ocamlbuild some time ago, but now it seems to be a standalone tool.

**Comment by vicuna** [comment]
**Comment author:** @alainfrisch

> ocamlmklib was a part of ocamlbuild some time ago

I don't think so.  ocamlmklib was there a long time before ocamlbuild was born.

**Comment by stedolan** [comment]
This was fixed by b799715caee3d45a9fd2d11dc1fa6a6d45da3178.
