### ISSUE TITLE
get the name of a function from its body, in order to write precise error message

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#6887]
**Original bug ID:** 6887
**Reporter:** Nimant
**Status:** acknowledged (set by @damiendoligez on 2015-06-05T21:09:22Z)
**Resolution:** open
**Priority:** normal
**Severity:** feature
**Category:** language features
**Monitored by:** @hcarty

## Bug description

add a __FUNCTION__ functionnality to provide the name of the current function. To be used in error messages.

**Comment by vicuna** [comment]
**Comment author:** berenger

Archives of the discussion on caml-list:
https://groups.google.com/forum/#!topic/fa.caml/_KStwfV3gjM

I'll try to find back an even older thread.

**Comment by vicuna** [comment]
**Comment author:** berenger

I am interested in this feature for logging purposes.

**Comment by vicuna** [comment]
**Comment author:** @gasche

There are many questions on what "the current function" means.

1) non-function toplevel bindings: what is the function name in

  let data_table =
    let file = open_in my_file in
    Log.debug "building data table" __FUNCTION__;
    let result = read_data file in
    close_in file;
    result

2) local functions: what is the function name in

  let f x =
    let g y =
      Log.debug "g" __FUNCTION__; y in
    g x

  let g x = x
  

3) anonymous functions

  let table =
    List.map
      (fun x -> Log.debug "building table" __FUNCTION__; foo x)
   data_list

  let build_table handle =
    List.map
      (fun x -> Log.debug "building table" __FUNCTION__; foo ~handle x)
    data_list

4) Functors

  module F (X : Plugin) : strut end = struct
    Log.debug ("instantiating F with " ^ X.name) __FUNCTION__;;
    PluginTable.register X.main();;
  end

For any of those cases (and I'm sure there are many others) the answer might be "fail (at parse time) in this corner case".

I think that __FUNCTION__ is maybe not the right intuition because there is a lot of code that may not be in a __FUNCTION__. Hongbo Zhang reported his implementation of a __BIND__ syntax extension that would return the name of the toplevel binding above it (be it a function, toplevel binding, functor, whatever).

Finally, how many __RANDOM_STUFF__ are we going to add? It may be time of thinking of a single location-sensitive magic constant, eg. __LOCATION__ (__LOC__ is unfortunately already taken), with an abstract type and an access interface somewhere in the stdlib, so that we could arbitrary fields to it in the future if users demand.

**Comment by vicuna** [comment]
**Comment author:** berenger

Just an idea: maybe %anonymous or %inlined could be a valid answer in some
cases (rather than failing).
For gasche's case 2): I personally feel "f.g" or "g" could be good candidates
for function names.

**Comment by vicuna** [comment]
**Comment author:** berenger

__FUNCTION__ is not a random stuff.
It is something than many C programmers just love. ;)

**Comment by vicuna** [comment]
**Comment author:** @sliquister

This can be implemented in a preprocessor, it's not clear why it should be in the compiler.

**Comment by vicuna** [comment]
**Comment author:** @damiendoligez

Indeed, this should be an extension, for example [%function], interpreted by some ppx preprocessor.

**Comment by vicuna** [comment]
**Comment author:** Nimant

"This can be implemented in a preprocessor, it's not clear why it should be in the compiler"

I prefer not to use a preprocessor. I think this functionnality should be provided by any language.

**Comment by vicuna** [comment]
**Comment author:** @mshinwell

It doesn't seem unreasonable to me to have this functionality without using a preprocessor.  gasche's idea of some kind of magic constant sounds quite interesting.

I don't think there is any problem with finding function names: it could just use the same names as the gdb branch assigns to functions based on the static scope.  For the above examples:

1. The path of the module ("M")
2. "f.g"
3. "anon_fn" + the source location
4. The path of the functor ("M.F")

This could be done before inlining to avoid any problems in that regard.

**Comment by nojb** [comment]
Maybe one can reuse some of the work that went into #9096 ?
