### ISSUE TITLE
Regression with -principal type inference

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#6922]
**Original bug ID:** 6922
**Reporter:** jhw
**Assigned to:** @garrigue
**Status:** assigned (set by jhw on 2017-04-06T19:54:52Z)
**Resolution:** open
**Priority:** normal
**Severity:** minor
**Version:** 4.03.0+dev / +beta1
**Category:** typing

## Bug description

Regression with -principal type inference.

## Steps to reproduce

Compile the debug configuration of v1.0.11 of the Oni package, which uses -principal and -warn-error A. With OCaml 4.02, this succeeds. With current 4.03+trunk, this fails because of "type not principal" warnings (errors) in Cf_journal and Cf_gadget.

## Additional information

The source code for the Oni package is on Bitbucket at <https://bitbucket.org/jhw/oni>.

## File attachments

- [type_error.ml](https://gist.githubusercontent.com/vicuna/8a3169ec080832ca1d7f12887711bf13/raw/ff039a2bb1903a56dfe9f02c2c0e73c71d6c44a8/type_error.ml)

**Comment by vicuna** [comment]
**Comment author:** @garrigue

You should probably report this first to the authors of Oni: a released package should never use -warn-error A, as this may break when warnings become stricter.
Then the authors of this package should check whether the warnings make sense or not.

**Comment by vicuna** [comment]
**Comment author:** jhw

Jacques, I am the author of the Oni package. The release configuration of the package doesn't use -warn-error A or -principle. Only the debug configuration does. I have a patch that works around the problem I'm reporting at the cost of losing the generality afforded by polymorphic methods, I'm hoping to discover that I won't need it because this problem turns out indeed to be a regression in 4.03. On the other hand, it may turn out that 4.03 actually has an improved type checker and my previously logic should never have been accepted when -principle is used. I'm interested to know which it will be.

**Comment by vicuna** [comment]
**Comment author:** @garrigue

Can you provide a shorter repro case?
I'm still trying to have omake working here...

**Comment by vicuna** [comment]
**Comment author:** jhw

I haven't forgotten about this. Just gotten busy with mundane seasonal distractions.

**Comment by vicuna** [comment]
**Comment author:** jhw

I was able to work around this problem in the release of Oni 1.0.12 with the following commit. I'm not sure if the workaround should be necessary.

https://bitbucket.org/jhw/oni/commits/ac4738c26d52228db1c69382d5ef1842db9d0b3b

**Comment by vicuna** [comment]
**Comment author:** @garrigue

Still waiting to see whether this is really a regression or not.

**Comment by vicuna** [comment]
**Comment author:** jhw

Uploaded a test file. Work around is commented out.

$ ocamlc -principal -warn-error A -i -c type_error.ml
File "type_error.ml", line 184, characters 12-20:
Warning 18: this use of a polymorphic method is not principal.
File "type_error.ml", line 188, characters 12-20:
Warning 18: this use of a polymorphic method is not principal.
File "type_error.ml", line 192, characters 12-20:
Warning 18: this use of a polymorphic method is not principal.
File "type_error.ml", line 196, characters 12-20:
Warning 18: this use of a polymorphic method is not principal.
File "type_error.ml", line 200, characters 12-20:
Warning 18: this use of a polymorphic method is not principal.
File "type_error.ml", line 204, characters 12-20:
Warning 18: this use of a polymorphic method is not principal.
File "type_error.ml", line 208, characters 12-20:
Warning 18: this use of a polymorphic method is not principal.

**Comment by vicuna** [comment]
**Comment author:** @garrigue

Apparently, inherited methods are not properly marked as known.

Here is a lighter workaround for now : in basic_agent, add

        method private virtual put:
            'a 'b. 'level -> ('event -> 'b) ->
            ('a, unit, string, 'b) format4 -> 'a

**Comment by trefis** [comment]
Apparently this was solved by #8955.
