### ISSUE TITLE
OCaml inappropriately installs binaries in the library directory

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#6959]
**Original bug ID:** 6959
**Reporter:** michi
**Assigned to:** @shindere
**Status:** assigned (set by @shindere on 2017-02-16T14:16:40Z)
**Resolution:** open
**Priority:** normal
**Severity:** tweak
**Version:** 4.02.2
**Target version:** 4.07.0+dev/beta2/rc1/rc2
**Category:** configure and build/install
**Monitored by:** @gasche

## Bug description

On some UNIX-like systems, the preferred place to install program
utilities run by another program is the libexec folder the lib folder
is reserver for libraries.

The two programs installed under

  lib/ocaml/expunge
  lib/ocaml/extract_crc

could therefore be installed under

  libexec/ocaml/expunge
  libexec/ocaml/extract_crc

This practice is standard on BSD and while it is also encouraged by GNU, it does not seem to otherwise have the status of a standard on Linux.

I do not know what these programs do, would it be worth the trouble of moving them?  Maybe having shell wrappers in the lib/ocaml directory calling the new tools in libexec/ocaml after having issued a warning for some transition period.

**Comment by shindere** [comment]
I guess this still needs to be fixed.

Will try to provide a fix ASAP.

**Comment by bschommer** [comment]
#9523 deals with a similar issue due to the fact that header files are installed in the library dir, maybe one could combine a fix for both.

**Comment by shindere** [comment]
Bernhard Schommer (2020/06/04 15:16 +0000):
> #9523 deals with a similar issue due to the fact that header files are
> installed in the library dir, maybe one could combine a fix for both.

Do you really mena `.h` files?

From what I can see in `runtime/Makefile` those seem to be installed in
`$(INSTALL_INCDIR)`...

**Comment by bschommer** [comment]
> Bernhard Schommer (2020/06/04 15:16 +0000):
> #9523 deals with a similar issue due to the fact that header files are installed in the library dir, maybe one could combine a fix for both.
> Do you really mena `.h` files? From what I can see in `runtime/Makefile` those seem to be installed in `$(INSTALL_INCDIR)`...

The Problem is that the `$(INSTALL_INCIDIR)` is equivalent to `$(LIBDIR)`. Currently `ocamlopt` adds a `-I $(LIBDIR)` to the call to the C compiler and as described in issue #9523 there is a  C++ standard header `version` that clashes with the file `VERSION`, at least for a case insensitive file systems (such as windows).

If you split the install directories of the binaries and libraries one could additionally change the way the includes are installed, but I'm unsure if that would be a practical solution.

On the other hand if the binaries are no longer installed in `LIBDIR` one could argue that just not installing `VERSION` would fix #9523. Then the only files which could clash are the libraries files which are unlikely to be used as header names, in contrast to for example `expunge` which might be used as header name.

**Comment by shindere** [comment]
I'll have to investigate whether autoconf provides support for header
directories as it does for library directories. Not sure.

**Comment by bschommer** [comment]
> I'll have to investigate whether autoconf provides support for header directories as it does for library directories. Not sure.

I think it does as `@includedir@` but adding support for this might result in problems if one manually invokes the C compiler and uses for `$(ocamlc -where)` for adding the include path as it is currently recommended in the manual.

**Comment by xavierleroy** [comment]
> adding support for this might result in problems if one manually invokes the C compiler and uses for $(ocamlc -where) for adding the include path as it is currently recommended in the manual.

I was about to write exactly the same thing.  We could un-recommend this usage in the manual, but a lot of makefiles use it in the wild.  I think we can find a different solution for #9523.

**Comment by bschommer** [comment]
> > adding support for this might result in problems if one manually invokes the C compiler and uses for $(ocamlc -where) for adding the include path as it is currently recommended in the manual.
> 
> I was about to write exactly the same thing. We could un-recommend this usage in the manual, but a lot of makefiles use it in the wild. I think we can find a different solution for #9523.

After thinking about this a little more I would argue that if this issue is fixed, i.e. the binaries are no longer installed in `LIBDIR`, it would suffice to just not install the file `VERSION` to fix #9523.

**Comment by shindere** [comment]
Still relevant, I think.

**Comment by shindere** [comment]
Sorry, I'm getting confused. What's the status of this?

Is the problem solved? Or it doesn't interest people any longer, or
what?

**Comment by lthls** [comment]
As far as I can tell the problem is still there.
However the solution might be to stop installing these executables completely.
`expunge` is used to create the toplevel, but doesn't need to be installed (I don't know about other toplevels, but `utop` at least doesn't rely on it).
I don't even know what `extract_crc` is used for. It appears to have been present since 1995, but I can't find a single use of it anywhere. I guess it was probably used for debugging before `ocamlobjinfo` was introduced.

**Comment by xavierleroy** [comment]
> However the solution might be to stop installing these executables completely.

Good lateral thinking!

> expunge is used to create the toplevel, but doesn't need to be installed

I thought `ocamlmktop` might use `expunge`, but it does not and apparently never did.  Caml Light's `camlmktop` did use `expunge`, which might explain why `expunge` is still installed?

> I don't even know what extract_crc is used for.

It was used in conjunction with a function from the `Dynlink` module that was removed a long time ago: https://github.com/ocaml/ocaml/commit/5e152f79453c9f5678f92b02851ff897839f93f5 .

**Comment by shindere** [comment]
I'll submit a PR to stop installing those programs.

**Comment by dbuenzli** [comment]
Just for the reference I thought `utop` might be using the `expunge` binary but it seem it has its [own version](https://github.com/ocaml-community/utop/tree/master/src/top/expunge).

**Comment by shindere** [comment]
Vincent Laviron (2021/08/12 06:36 -0700):
> As far as I can tell the problem is still there.
> However the solution might be to stop installing these executables completely.
> `expunge` is used to create the toplevel, but doesn't need to be installed (I don't know about other toplevels, but `utop` at least doesn't rely on it).
> I don't even know what `extract_crc` is used for. It appears to have
> been present since 1995, but I can't find a single use of it anywhere.
> I guess it was probably used for debugging before `ocamlobjinfo` was
> introduced.

Thanks. I have implemented your suggestion in #10379, see
https://github.com/ocaml/ocaml/pull/10739
