### ISSUE TITLE
ocamldep -one-line doesn't work with -sort

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#6968]
**Original bug ID:** 6968
**Reporter:** @dbuenzli
**Status:** confirmed (set by @gasche on 2015-08-25T17:43:22Z)
**Resolution:** open
**Priority:** normal
**Severity:** minor
**Version:** 4.02.3
**Category:** tools (ocaml{lex,yacc,dep,debug,...})
**Tags:** junior_job
**Monitored by:** @dbuenzli

## Bug description

> ocamldep -sort -one-line src/*.mli
src/uunf.mli src/uunf_string.mli

**Comment by vicuna** [comment]
**Comment author:** @gasche

The --help documentation is rather bad, but the semantics are as follow:

<pre>
  -sort enabled: just output the list of files in topological order 
  -sort not enabled: output pairs (target_files : dependencies)
     -one-line enabled: all dependencies on one line
     -one-line not enabled: with line cuts to not overflow 80 columns
</pre>

The semantics of (-sort -one-line) is currently not defined, and in fact the current implementation of -sort will always print the list of files on one line only.

Would you prefer the combination -sort -one-line to be rejected, or some other semantics to be given to it?

**Comment by vicuna** [comment]
**Comment author:** @dbuenzli

I think it would be nice that it does what it is supposed to do. For example this could be useful for tools to correctly handle the cases when paths have spaces in them.

**Comment by vicuna** [comment]
**Comment author:** @gasche

I don't follow: what is `-sort -one-line` supposed to do? Can you explain why it does not do it?

**Comment by vicuna** [comment]
**Comment author:** @dbuenzli

> ocamldep -sort -one-line src/*.mli
src/uunf.mli 
src/uunf_string.mli

**Comment by vicuna** [comment]
**Comment author:** @dbuenzli

Ah sorry just completely misundestood.

**Comment by vicuna** [comment]
**Comment author:** @dbuenzli

My brain was reading one-per-line.

**Comment by vicuna** [comment]
**Comment author:** @dbuenzli

Well actually it's not only my brain :

> ocamldep -help | grep "one-line"
  -one-line  Output one line per file, regardless of the length

**Comment by vicuna** [comment]
**Comment author:** @gasche

The "one line per file" comment is trying to say that for each target, all its dependencies are displayed on the same line (instead of having line cuts to not overflow 80 columns).

Regardless of what the documentation says or the implementation does, I find the output you suggest rather counter-intuitive for an option whose name suggest that the output will be "on one line" -- and it would be contradictory with the behaviour of -one-line in absence of -sort, which is the one that is actually implemented and that (I suppose) some people use.

I'm open to suggestions of how to fix the documentation and/or implementation.

**Comment by vicuna** [comment]
**Comment author:** @dbuenzli

Well I don't really care about the name but at least documentation should be fixed since reading: 

> ocamldep -help | grep "sort\|one-line"
  -one-line  Output one line per file, regardless of the length
  -sort  Sort files according to their dependencies

You can legitimately see why I understand this that way. Besides I really think that what I understood should be provided. In the current state it's impossible to use ocamldep with file paths that have spaces in them.

**Comment by vicuna** [comment]
**Comment author:** @gasche

I do understand your point, and I agree the documentation should be fixed.

How does make handle files with spaces in them? ocamldep should be Makefile-compatible, but if for example always quoting filenames that have spaces preserves compatibility, we could do that.

(I would also be fine with changing "ocamldep -sort -one-line" to do as you expect. In that case, I would be interested in a suggestion for a -help message for -one-line and/or -sort that would clarify the behavior of -one-line both with and without -sort. Don't be shy, I know you rock at documentation.)

**Comment by vicuna** [comment]
**Comment author:** @dbuenzli

>  I would be interested in a suggestion for a -help message for -one-line and/or -sort that would clarify the behavior of -one-line both with and without -sort.

Well if you fix it for `-sort` then it makes all sense as it is no ?

**Comment by vicuna** [comment]
**Comment author:** @gasche

Fair enough. Thanks!

**Comment by vicuna** [comment]
**Comment author:** @gasche

In https://github.com/ocaml/ocaml/pull/2189 I proposed a -one-file-per-line option for ocamldep, and Nicolás suggested to drop the option and instead make it the default behavior (this will be available in 4.08). This suggests that -sort should use newlines between each file, unless -one-line is specified.

**Comment by dbuenzli** [comment]
I think @gasche PR's solves this issue and it can be closed.

**Comment by dbuenzli** [comment]
Actually it's not. But I think it's easier for me to work around.
