### ISSUE TITLE
iOS support for OCaml

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#6986]
**Original bug ID:** 6986
**Reporter:** gerd
**Assigned to:** @shindere
**Status:** assigned (set by @damiendoligez on 2017-03-01T10:36:08Z)
**Resolution:** open
**Priority:** normal
**Severity:** feature
**Version:** 4.02.3
**Category:** platform support (windows, cross-compilation, etc)
**Monitored by:** @diml @hcarty

## Bug description

Creating this bug to have a place for discussing iOS support. So far, there is a PR:

https://github.com/ocaml/ocaml/pull/182

For recent OCaml versions, there are special per-release branches, e.g.
https://github.com/gerdstolpmann/ocaml/tree/gs-4.02.3+ios

## Additional information

Largely, the PR just changes assembler conventions. There is one bigger change, though, because Apple doesn't use the EABI in the same way GNU does (on 32 bit). In particular, floats are passed via int register pairs and not via stack.

The PR now also changed to UAL mnemonics. This should work on GNU, too.

**Comment by vicuna** [comment]
**Comment author:** markghayden

I had a problem building the 64-bit IOSSIM version.  config/s.h is not being populated with values, I believe because the BSD socket calls are not detected.  The resulting unix library generates Invalid_argument() exceptions on socket calls.  Copying

  config/cross-fixup-arm64-macosx-s.h

to

  config/cross-fixup-amd64-macosx-s.h

and reconfiguring seems to fix the problem.

For some reason, this does not seem to be an issue in the 32-bit IOSSIM build.

**Comment by vicuna** [comment]
**Comment author:** @xavierleroy

A quick update following discussions at the developers's meeting last Wednesday.  We are very much interested in integrating this iOS port eventually, but it needs more work than we can allocate by the next major release (OCaml 4.03).  Ideally, the integration should be done in 2016 as part of a more general work on cross-compilation support.  Thanks for your patience.

**Comment by XVilka** [comment]
Should be solved in https://github.com/ocaml/ocaml/pull/1084

**Comment by XVilka** [comment]
See also https://github.com/ocaml/ocaml/pull/9699

**Comment by EduardoRFS** [comment]
We can also close this

**Comment by nojb** [comment]
Fixed by #9699
