### ISSUE TITLE
consider not relying on libbfd

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#7001]
**Original bug ID:** 7001
**Reporter:** @whitequark
**Status:** acknowledged (set by @xavierleroy on 2015-11-24T10:37:29Z)
**Resolution:** open
**Priority:** normal
**Severity:** feature
**Target version:** later
**Category:** tools (ocaml{lex,yacc,dep,debug,...})
**Monitored by:** @gasche @diml

## Bug description

libbfd is not easily available, e.g. it does not ship with the stock Android toolchain. This presents a problem if someone wants to use native code plugins on Android. This is a milder version of bug ocaml/ocaml#6779, in essence.

(This is not a problem on iOS because iOS does not have dynamic libraries.)

See also https://github.com/whitequark/opam-android/issues/11.

**Comment by vicuna** [comment]
**Comment author:** @johnwhitington

libbfd doesn't ship with OS X currently, either:

[WARNING] BFD library not found, 'objinfo' will be unable to display info  on .cmxs files.

I believe this is a recent change, since I don't remember warnings on ./configure until recently.

**Comment by vicuna** [comment]
**Comment author:** @xavierleroy

libbfd is used in one rarely-used OCaml tool (ocamlobjinfo), in the rarely-exercised case where ocamlobjinfo is given a .cmxs file.  If libbfd is not there, everything else will still work (AFAIK).

Besides, it's not like we can reimplement libbfd ourselves, the various formats of shared object files are just too complicated for that.

Concerning MacOS X, you may have to install it using Macports or Homebrew.

Unless you have a better alternative to libbfd to propose, I move to close this PR.

**Comment by vicuna** [comment]
**Comment author:** @whitequark

> Besides, it's not like we can reimplement libbfd ourselves, the various formats of shared object files are just too complicated for that.

I entirely disagree.

First we don't need to; platforms already have the format descriptions in the C bindings (the kernel header elf.h on Linux; winnt.h and its IMAGE_FILE_* structures on Windows; mach_* on OS X).

Second, we don't need all of libbfd, we only need to look up one symbol, which is trivial; the libbfd-independent code shouldn't even be longer than the existing code, with the catch that it has to be in triplicate.

**Comment by vicuna** [comment]
**Comment author:** @xavierleroy

We're not big fans of libbfd either, which is why it is not used by the OCaml compilers, despite some temptation to use it (e.g. #6779, #6845).  

Nonetheless, I think we all collectively have many more urgent things to do than reimplement parts of libbfd in OCaml so that an obscure use case of an obscure tool works on systems that lack libbfd.

I move to resolve/suspend this PR.

**Comment by vicuna** [comment]
**Comment author:** @whitequark

I still disagree because I think that, if implemented, such support for symbol lookup without libbfd would be useful in cross-compilation as well.

**Comment by vicuna** [comment]
**Comment author:** @xavierleroy

All right, I keep this PR alive, but with a target after 4.03, and a "feature wish" tag.

**Comment by whitequark** [comment]
This issue can be closed, I think.

**Comment by xavierleroy** [comment]
Closing as suggested.  Nonetheless, I'd be interested to know what alternatives to libbfd exist already.

**Comment by whitequark** [comment]
@xavierleroy I'm not aware of anything lightweight that would be appropriate for use in OCaml. I know of LLVM machine code libraries (that depend on LLVM), and there are Rust libraries (that depend on Rust), but it seems that your original judgement about this (as quoted below) was spot-on and no one is particularly interested in solving this specific problem.

> Nonetheless, I think we all collectively have many more urgent things to do than reimplement parts of libbfd in OCaml so that an obscure use case of an obscure tool works on systems that lack libbfd.

**Comment by dbuenzli** [comment]
FWIW there has been renewed interest (at least by me) in the context of the library linking proposal see e.g. https://github.com/ocaml/ocaml/issues/9306 and https://github.com/ocaml/RFCs/pull/17 in particular for the Dynlink API.

**Comment by xavierleroy** [comment]
I agree with @dbuenzli that if we had a "good" alternative to libbfd (portable, widely available, license-compatible, and actively maintained by someone else), we'd have other uses for it.  Thanks @whitequark for the pointers.

**Comment by XVilka** [comment]
There is also a [LIEF](https://lief.quarkslab.com/) but it's [written in C++](https://github.com/lief-project/LIEF) and quite heavy for this use, it also focuses on the instrumenting and patching binaries instead.
