### ISSUE TITLE
Feature proposal: provide type specialization function for boolean and give an warning when a generic comparison is used

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#7044]
**Original bug ID:** 7044
**Reporter:** @bobzhang
**Status:** acknowledged (set by @damiendoligez on 2017-04-13T11:07:52Z)
**Resolution:** open
**Priority:** normal
**Severity:** feature
**Category:** typing

## Bug description

Currently only int, float, string, nativeint, int32, int64 are specialized, it would be nice to also specialize boolean.
In some cases, using generic comparison function is un-intentional, it would be nice to have a warning for this (at least abstract type comparison)

**Comment by stedolan** [comment]
The first feature-wish is already implemented: comparison functions are specialised for booleans. (The specialisation also works for user-defined types with only constant constructors).

The second feature-wish (warnings on generic compare) is being discussed at #7524
