### ISSUE TITLE
[OCaml] Typechecking limitation in presence of mutually recursive modules

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#7077]
**Original bug ID:** 7077
**Reporter:** Iguernlala
**Status:** acknowledged (set by @damiendoligez on 2016-02-03T16:20:16Z)
**Resolution:** open
**Priority:** normal
**Severity:** feature
**Version:** 4.02.3
**Target version:** undecided
**Category:** typing
**Tags:** recmod

## Bug description

The attached code does not typecheck unless type annotation is
put on line "L29", or lines "L29" and "L30" are swapped.

Maybe the information which says that "Th.term" and "term" are
equal is lost when comparing module's inferred signature with the
required one (?). Compiling with "-short-paths" to choose "term"
as a representative of "Th.term" does not resolve the problem.

## File attachments

- [ex.ml](https://gist.githubusercontent.com/vicuna/cfa2c720d3646c0697d3c167254527fe/raw/7094d1b18af826ec1877286ce95fb25f4356920b/ex.ml)

**Comment by vicuna** [comment]
**Comment author:** @garrigue

Since there is no specification for recursive modules, there are no bugs :-)

**Comment by jberdine** [comment]
Still repros FWIW. Do I understand correctly that this is an instance of classic "double-vision"?

**Comment by lpw25** [comment]
This is worse than double-vision. In normal double-vision issues the compiler is not aware that a type and the same type accessed via recursion are the same. Here, we are getting some kind of principality failure because the type-checker is treating two types that are known to equal differently.
