### ISSUE TITLE
ocamldoc parsing error issues incorrect line number

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#7084]
**Original bug ID:** 7084
**Reporter:** junsli
**Status:** acknowledged (set by @gasche on 2015-12-11T05:57:07Z)
**Resolution:** open
**Priority:** normal
**Severity:** minor
**Version:** 4.02.3
**Category:** documentation
**Has duplicate:** #7187
**Related to:** #5901

## Bug description

Take this example in foo.ml
```
(** This comments should associate with function xxx
    @version 1
    @param x {!class1:my_class111}
    @param1 y {!class:my_class123}}
    *)
let xxx x y = x - y
```
It reports the following parsing error:
```
File "foo.ml", line 0, character 23:
y {!class:my_class123}}
                       ^
1 error(s) encountered
```
"line 0" is incorrect, as ocamldoc extracts each comment block (and inner element) out and parses them separately as strings, which causes the global location information missing.

(See also issue #5901, where the location info is not provided in the warning. The two bugs suffers from the same design issue, and probably shares the same solution)

**Comment by gasche** [comment]
ocamldoc is being phased out to be replaced by [odoc](https://github.com/ocaml/odoc), and no one seems interested in fixing small interface bugs. Closing.
