### ISSUE TITLE
Unix.system (Win) should report when cmd.exe is not found

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#7088]
**Original bug ID:** 7088
**Reporter:** @Chris00
**Status:** acknowledged (set by @damiendoligez on 2017-04-13T11:12:05Z)
**Resolution:** open
**Priority:** normal
**Severity:** minor
**Platform:** x86_64
**OS:** Windows
**Version:** 4.02.3
**Category:** otherlibs
**Monitored by:** @hcarty @Chris00

## Bug description

The API call system¹ documentation says "If the command interpreter is not found, returns 0 and sets errno to ENOENT." It seems that this behavior is not taken into account by the C function win_system.

¹ https://msdn.microsoft.com/en-us/library/277bwbdz.aspx

## Additional information

See https://github.com/ocaml/ocaml/pull/349

**Comment by vicuna** [comment]
**Comment author:** @damiendoligez

Note that the Microsoft documentation referenced above is self-contradictory: it says the return value will be both 0 and -1 when `cmd.exe` is not found.

**Comment by xavierleroy** [comment]
I think this is the wrong reading of the MSDN documentation.  Let me rewrite it in structured programming style:

If command is NULL:
- if the command interpreter is found, returns a nonzero value
- If the command interpreter is not found, returns 0 and sets errno to ENOENT.

If command is not NULL,  system returns the value that is returned by the command interpreter.
- It returns the value 0 only if the command interpreter returns the value 0.
- A return value of - 1 indicates an error, and errno is set to one of the following values: ... ENOENT The command interpreter cannot be found.

We're in case "command is not NULL", and there is no problem.
