### ISSUE TITLE
Implement `nice` on Windows

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#7089]
**Original bug ID:** 7089
**Reporter:** @Chris00
**Status:** acknowledged (set by @shindere on 2017-02-24T16:09:42Z)
**Resolution:** open
**Priority:** low
**Severity:** feature
**Category:** otherlibs
**Monitored by:** @Chris00 @xavierleroy

## Bug description

nice is not implemented on Windows. However, Windows has a SetPriorityClass¹ which could somewhat provide an alternative.

¹ https://msdn.microsoft.com/en-us/library/ms686219%28v=vs.85%29.aspx

## Additional information

See https://github.com/ocaml/ocaml/pull/349

**Comment by vicuna** [comment]
**Comment author:** @shindere

That indeed seems _nice_ to have. ;-)

**Comment by vicuna** [comment]
**Comment author:** @shindere

Tu auras peut-être envie de le coder? Cela semble supporté depuis assez longtemps...

**Comment by Chris00** [comment]
@dra27 Your opinion?

**Comment by dra27** [comment]
I agree, it'd be a good addition

**Comment by dra27** [comment]
Inching forwards with a little progress for this one, linking in the [MSDN page on Scheduling](https://docs.microsoft.com/en-us/windows/win32/procthread/scheduling-priorities) and a bit of [prior art](https://www.mkssoftware.com/docs/man3/setpriority.3.asp) for `setpriority` mappings.

**Comment by dra27** [comment]
This would be nice to have (🤦‍♂️) - PR welcomed.
