### ISSUE TITLE
The "ocaml" toplevel should accept "-verbose"

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#7099]
**Original bug ID:** 7099
**Reporter:** @alainfrisch
**Status:** acknowledged (set by @damiendoligez on 2016-11-08T10:30:45Z)
**Resolution:** open
**Priority:** low
**Severity:** feature
**Category:** toplevel
**Tags:** junior_job
**Monitored by:** @nojb @gasche @diml

## Bug description

This would be useful to trace calls to external ppx programs.  In "-verbose" mode, the toplevel should perhaps print the "context" passed to and received from ppxs, in particular the "cookies" field.  This could be very useful to track bugs such as #7098 or other bugs in ppxs themselves.

[Edit: I initially wrote "-v" but of course I meant "-verbose" as for ocamlc/ocamlopt.]

**Comment by vicuna** [comment]
**Comment author:** @gasche

When I saw the mantis ticket title, I thought that this would be a synonym to -version. Maybe -debug or -verbose would be better names.


I do some amount of debugging in the toplevel using -dsource or -dparsetree. Would it be possible for a refinement of those options (for example, having options to print the source before and after preprocessing, and similarly for parsetree) support your use-case? They could also be useful for debugging interactions with ocamlc.

**Comment by vicuna** [comment]
**Comment author:** @alainfrisch

Indeed, being able to show the AST sent to or received from each PPX would be useful (that's how I debugged #7098).  Should this be a new option, or just triggered when both -dparse (resp. -dsource) and -verbose are enabled?

**Comment by vicuna** [comment]
**Comment author:** kaaira

can i please work on this? do reply so that i can know if i need to look for some other issue. Thanks.

**Comment by vicuna** [comment]
**Comment author:** @alainfrisch

Yes, feel free to pick up this work if you interested in it!

**Comment by vicuna** [comment]
**Comment author:** @gasche

In case this can help, here is maybe a more detailed description of what the issue is about.

Currently if you run "ocaml -dsource" and enter the following commands:

    #use "topfind";; (* this enables lookup of findlib packages *)
    #require "ppx_deriving.show";; (* this enables the ppx_deriving ppx *)
    type t = Foo of int [@@deriving show];;

then the last line will show the source code interpreted by the toplevel, that is, the source generated by the ppx_deriving preprocessor. This is useful for users wishing to understand what the ppx does, but not so much for people trying to debug it when it behaves wrongly, which would also need to see the input sent to the ppx by the toplevel.

Alain is proposing that such a mode be enabled when both -dsource and -verbose are active. (Another option different from -dsource is -dparsetree, which shows the complete AST rather than the concrete syntax, and it would behave similarly.) So the output of the last line could be something like

    (* content sent to the ppx processor "ppx_deriving" *)
    <source code before processing, including ppx-context>

    (* content receive from the ppx processor "ppx_deriving" *)
    <source code after processing, including ppx-context>

Final tips:
- The code that applies the ppx rewriters is in driver/pparse.
- What Alain calls the "cookies" above is special metadata exchanged by the compiler and the ppx processor, as part of the "ppx context". The compiler tells the preprocessor about compilation options, and the preprocessor also return similar metadata.
- While driver/pparse contains the high-level logic for preprocessors, most of the logic is actually in parsing/ast_mapper, in particular the PpxContext submodule which contains the cookie logic.

My gut feeling, but I'm not sure, is that it should suffice to modify driver/pparse to implement this logic (in particular the "apply_rewriters_*" functions), without touching parsing/ast_mapper, but reading that file may still be useful to understand the context.

**Comment by ulugbekna** [comment]
I'd want to work on this if no one is already.

**Comment by nojb** [comment]
Go for it!

Just for information, someone else had expressed interest (user `kaaira` above), but I don't think there has been any news since.

**Comment by gasche** [comment]
This remains a useful feature request and a valuable "newcomer job".
