### ISSUE TITLE
Allow easy retrieval of Makefile.config's values

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#7116]
**Original bug ID:** 7116
**Reporter:** adrien
**Status:** feedback (set by @shindere on 2017-02-22T15:11:36Z)
**Resolution:** open
**Priority:** normal
**Severity:** feature
**Category:** configure and build/install
**Related to:** #4957

## Bug description

Currently the values in Makefile.config are difficult to extract. While looking at ocamlbuild's #38 PR on github I tried to get a cleaner way to get them and found out that someone has already done it elegantly and explained it well: http://blog.jgc.org/2015/04/the-one-line-you-should-add-to-every.html .

Basically, adding the following to a Makefile creates a pattern rule than can then be used to print the value of the variable which name is used in the pattern.

    print-%:
            @echo $*=$($*)

For instance, on my machine, "make -f config/Makefile print-MKEXE" will print "MKEXE=gcc". We can also skip the "MKEXE=" part if we want (I think it makes more sense for us actually).

This would greatly simplify changes in various places and avoid having to "include" the config makefile which means overwriting all the corresponding variables. It would help a lot to have it in 4.03.

**Comment by vicuna** [comment]
**Comment author:** @gasche

One other approach to do this which I also considered is to make it easier to extract information from $(ocamlc -config) without parsing step. For example, $(ocamlc -config-key ext_obj) would be the string ".o".

I'm fine with adrien's proposal which seems easier to implement (-config exposes more information than Makefile.config, but in practice the information I needed is available in both).

**Comment by vicuna** [comment]
**Comment author:** @shindere

Isn't ocamlc -config enough? Can you give an example of a place where this would improve the situation?

**Comment by vicuna** [comment]
**Comment author:** @gasche

#1430 proposes a -config-var option for 4.07:

  https://github.com/ocaml/ocaml/pull/1430

**Comment by xavierleroy** [comment]
Wish fulfilled in #1430.
