### ISSUE TITLE
[cross-compilation] Use -I otherlibs/$(UNIXLIB) when building systhreads

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#7122]
**Original bug ID:** 7122
**Reporter:** adrien
**Status:** acknowledged (set by @damiendoligez on 2016-02-08T11:39:07Z)
**Resolution:** open
**Priority:** normal
**Severity:** minor
**Category:** configure and build/install
**Tags:** cross-compilation, patch

## Bug description

Together with #7121, this is basically the last patches that I've needed in order to get a cross-compiler to Windows when updating to trunk (my non-trivial GUI + threads program works, meaning enough is supported; not everything is however).

This one is very simple: in otherlibs/systhreads/Makefile, there is a couple of -I that hardcode their path to $(ROOTDIR)/otherlibs/unix and this simply changes the paths to $(ROOTDIR)/otherlibs/$(UNIXLIB) (i.e. either "unix" or "win32unix").

Thinking more about it, it might read better to replace the use of "$(UNIXLIB)" with "$(IS_WIN32)unix" where IS_WIN32 is either "win32" or "". That's something that would be done later on however.

## File attachments

- [0001-systhreads-allow-usage-of-win32unix-when-using-non-..patch](https://gist.githubusercontent.com/vicuna/adc4296873a2b68a3908735086d6c591/raw/3371e2db847ecee9abc54e4c7a399334cc402c51/0001-systhreads-allow-usage-of-win32unix-when-using-non-..patch)

**Comment by xavierleroy** [comment]
The proposed change seems to have been performed already as part of the great unification between Makefile and Makefile.nt.
