### ISSUE TITLE
ref_table grows without bound

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#7128]
**Original bug ID:** 7128
**Reporter:** @stedolan
**Status:** acknowledged (set by @damiendoligez on 2016-02-03T11:00:36Z)
**Resolution:** open
**Priority:** normal
**Severity:** minor
**Version:** 4.02.3
**Target version:** later
**Category:** back end (clambda to assembly)
**Monitored by:** @gasche @hcarty

## Bug description

The ref_table is added to whenever a pointer is created from the old to the young generation. Unfortunately, this can happen an unbounded number of times between two safepoints, since safepoints are only at allocations in the native compiler.

The attached program runs using less than 1MB of memory with the bytecode interpreter. However, when compiled with ocamlopt, it allocates 4GB of ref_table and then crashes, as ocamlopt must wait for a safepoint to clear the ref_table.

## File attachments

- [safepoints.ml](https://gist.githubusercontent.com/vicuna/026393a6a554daad799a463dbc6dd5e1/raw/0cc8f7e4622b8e7f88c07c3b3ba1be5310c113db/safepoints.ml)

**Comment by vicuna** [comment]
**Comment author:** @stedolan

The easiest solution here is to emit safepoints (e.g. a zero-byte allocation) inside loops and at function entry, so that the amount of time between safepoints can be bounded. Such extra safepoints are also useful for multicore, which needs to bound the time between safepoints to handle inter-thread synchronisation.

**Comment by vicuna** [comment]
**Comment author:** @mshinwell

I'm going to move this to the code generation category, which seems more appropriate.

**Comment by vicuna** [comment]
**Comment author:** @xavierleroy

This is a known issue.  It can also postpone indefinitely signal handling and thread preemption.  

The insertion of "safe points" is the solution indeed, but done naively it can be quite costly in run-time.  You shoud read "Polling efficiently on stock hardware" by Marc Feeley (FPCA'93, oldie but goldie).

**Comment by dc-mak** [comment]
Just wanted to link a few related issues around the repos here:
Relevance to multi-core https://github.com/ocaml-multicore/ocaml-multicore/issues/187
[Report is here](https://github.com/ocaml/ocaml/files/4148541/mcd-report.pdf)
Code (horribly organised) https://github.com/ocaml/ocaml/compare/trunk...dc-mak:trunk

**Comment by gasche** [comment]
I went to read [the nice PDF report](https://dhruvmakwana.com/s/mcd-report.pdf) and I thought it could be helpful to summarize a bit more information for people ending up on the present PR:

- @dc-mak did an advanced-compiler-class project to implement Marc Feeley's algorithm for OCaml -- as a transformation on the Cmm code. The result does work as intended, and it seems to have been done properly: it takes into account subtleties such as being careful not to insert safepoints at places where non-traceable data is live in registers.
- The report contains benchmarks; the code size doesn't increase much, but on micro-benchmarks with tight loops there is a marked decrease in performance (Feeley observed that trivial loop could run 80% slower; here similar 70-90% have been observed in the worst case). On realistic programs the slowdowns should be much smaller, but not much serious measurement has been made there (nobody really knows how to do that well).

**Comment by xavierleroy** [comment]
This issue appears to be fixed in 4.14 thanks to the new, proper "safepoints" implementation.
