### ISSUE TITLE
Annotations for cross-platform development

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#7143]
**Original bug ID:** 7143
**Reporter:** @damiendoligez
**Status:** acknowledged (set by @shindere on 2017-02-24T15:48:32Z)
**Resolution:** open
**Priority:** normal
**Severity:** feature
**Version:** 4.03.0+dev / +beta1
**Category:** platform support (windows, cross-compilation, etc)
**Monitored by:** @diml @jmeber @hcarty

## Bug description

In ocaml/ocaml#5253#c15148, Christophe Troestler wrote:

With the advent of ppx however, I was wondering if, in addition to the documentation, it would not be desirable to introduce a new attribute to say that some function is only on some os_type. An associated warning (turned off by default) would make possible to be sure that a given code does not use functions specific to a given platform (that would also be useful for some external libraries I think).

I think this is a good idea, so I want it to have its own PR, lest it be forgotten.

**Comment by shindere** [comment]
No reaction since this has been submitted so I'd suggest to close, at
least for the moment.

**Comment by damiendoligez** [comment]
It does look like a good idea, though. But I would invert the logic: annotate functions that are *missing* on a given platform.

**Comment by alainfrisch** [comment]
And use alerts, I guess.
