### ISSUE TITLE
Confusing error message when parentheses are added around an expression

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#7148]
**Original bug ID:** 7148
**Reporter:** @dbuenzli
**Status:** acknowledged (set by @damiendoligez on 2017-04-13T11:21:39Z)
**Resolution:** open
**Priority:** normal
**Severity:** minor
**Version:** 4.02.3
**Target version:** later
**Category:** lexing and parsing
**Child of:** #5068
**Monitored by:** @diml @hcarty

## Bug description

I find the following quite confusing 

```ocaml
 ocaml
        OCaml version 4.02.3                                                                                                                                    
# f bla:i;;
Error: Syntax error
# (f bla:i);;
Error: Unbound type constructor i
```

The error came up while forgetting to add the ~ to a labelled argument.

**Comment by vicuna** [comment]
**Comment author:** @damiendoligez

I'm not sure I understand what's confusing about these errors and what we could do to get better messages.

**Comment by vicuna** [comment]
**Comment author:** @dbuenzli

What the author wants to write here is `... (f ~bla:i) ...`. The reported error being so far away from the initial aim, it just doesn't make the programmer think about the right way to fix it and leaves him head scratching.

Much better error messages can be given in this case by suggesting in a "Did you mean" fashion that this could be either a type constraint or a misspelled labelled application. This can be achieved by reasoning on the current type and value identifiers in scope. E.g. if `i` is in the value scope and not in the type scope and `bla` is not in the value scope it seems more likely to be a labelled application that is missing a ~.

**Comment by dbuenzli** [comment]
I suspect I'm speaking nonsense here since I doubt the actual information I'm mentioning is available when the error occurs. Maybe this should be closed.

**Comment by gasche** [comment]
I agree that the solution you propose looks a bit too sophisticated, but I'll leave the issue open as a valuable example of "plausible mistake that needs better ergonomics".
