### ISSUE TITLE
Interfacing with C missing documentation and helper macros and functions

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#7179]
**Original bug ID:** 7179
**Reporter:** goswin
**Status:** acknowledged (set by @damiendoligez on 2016-03-14T13:34:46Z)
**Resolution:** open
**Priority:** normal
**Severity:** minor
**Category:** documentation
**Monitored by:** @jmeber

## Bug description

When an ocaml function is used as callback from C code and the last thing the callback does is call a C stub returning unit and the return register happens to contain ((x & 3) == 2) then this is taken as an exception. When caml_callback() is used this carshes and when caml_callback_exn is garbage is returned from Extract_exception().

Ocaml should sanitize the return register after calling the C stub.

## Steps to reproduce

% make
ocamlopt -g -c -o main.cmx main.ml
gcc -O2 -W -Wall -g -c -o stubs.o stubs.c
ocamlopt -o test main.cmx stubs.o
./test
test(0x61ea78)
fail
test: callback got exception 0x0

==> Makefile <==
        ocamlopt -o $@ $+

%.cmx: %.ml
        ocamlopt -g -c -o $@ $<

%.o: %.c
        gcc -O2 -W -Wall -g -c -o $@ $<

clean:
        rm -f test *.o *.cmx *.cmi *~

==> main.ml <==
external fail : unit -> unit = "fail"
external test : (unit -> unit) -> unit = "test"

let callback () =
  fail ()
   
let () =
  test callback

==> stubs.c <==
    CAMLparam1(callback);
    CAMLlocal1(res);
    printf("%s(0x%lx)\n", __PRETTY_FUNCTION__, callback);
    res = caml_callback_exn(callback, Val_unit);
    if (Is_exception_result(res)) {
        res = Extract_exception(res);
        fprintf(stderr, "%s: callback got exception 0x%lx\n", __PRETTY_FUNCTION__, res);
    }
    CAMLreturn0;
}

## Additional information

https://github.com/mrvn/ocam-problems/tree/false-exception

**Comment by vicuna** [comment]
**Comment author:** mfp

AFAICS CAMLreturn0 is not supposed to be in the outermost C function 
(the one called by OCaml), but only in void-returning "procedures".
Indeed, as per 19.1.2 in the manual, primitives should always be declared
with  CAMLprim value  and would thus use CAMLreturn(Val_unit).

**Comment by vicuna** [comment]
**Comment author:** @mshinwell

Hmm, I wonder if all this needs is a clarification in the manual that you must use one of the macros that actually returns a value at the return point to OCaml.

**Comment by vicuna** [comment]
**Comment author:** goswin

It does. I would like to re-title this issue to "Interfacing with C missing documentation and helper macros and functions"

I just looked over the chapter and spotted a few other things missing:

- Nowhere in 19.1.2 does it say that returning value is a requirement. All the examples return a non-void result so that gives no hint.

- In 19.5.1 the docs say to use CAMLreturn0 for methods returning void. It does not mention that that is not allowed for the interface between C and ocaml.

- There is no example for CAMLreturnT.

- CAMLnoreturn is not explained

- Weak.t is not mentioned (see other issue)

- 19.3.4 lists unit as Val_int(0) instead of Val_unit, true/false as Val_int but there is Val_bool, Val-true, Val_false, Val_not, Bool_val, [] not as Val_emptylist, x::xs not with Tag_cons

- option types and references are not explained

- mlvalues.h: Val_none and Tag_some missing, Some_val(), Is_none() or Is_some() missing

- alloc.h: caml_alloc_some(value) missing

**Comment by vicuna** [comment]
**Comment author:** @damiendoligez

Indeed this part of the documentation needs some work.

I've re-titled this PR.

**Comment by bschommer** [comment]
I think the Interfacing with C needs some general update, since at the moment a lot of this stuff is still not documented and for example the documentation for `CAMLreturn0` can lead to the impression for functions returning `unit` one should use `void` as return type and `CAMLreturn0`.

**Comment by gasche** [comment]
This should be an easy documentation improvement: clarify the documentation of the C interface in the manual to explain that `CAMLreturn0` should only be used for internal FFI procedures of type `void`, and that `CAMLreturn(Val_unit)` should be used for functions that return an OCaml `unit` value.

**Comment by kirisky** [comment]
Hi @gasche! Can I take this issue?
