### ISSUE TITLE
A command-line option to tell the compiler to behave (somehow) as a specific version

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#7184]
**Original bug ID:** 7184
**Reporter:** @alainfrisch
**Status:** acknowledged (set by @mshinwell on 2016-12-08T15:06:44Z)
**Resolution:** open
**Priority:** normal
**Severity:** feature
**Category:** misc
**Monitored by:** @gasche @diml @hcarty

## Bug description

I suggest to introduce a command-line option to tell the compilers to emulate (to some extent) the behavior of a specific older version of OCaml.  E.g. "ocamlc -as-of 4.03 ...".  This could include things such as:

  - Choices for various modes (safe-string, strict-formats, strict-sequence).

  - Default warning configuration (and the meaning of "a").

  - Rejecting new linguistic features (implemented e.g. within the AST invariant checker).

There would be two goals:

  - Give a quick way to check that the code base of a specific project does not start using features from a newer version of OCaml while the project is supposed to still support older versions.  This would not be a bullet-proof check, of course, just a first quick check against using e.g. "match with exception" or GADT when targeting an older version.

  - Allow distributed source packages to "immunize" themselves against changes to default mode/warning configurations in future versions of OCaml, and thus allow OCaml to change those default configuration with more freedom.  E.g. one could decide to turn safe-string on by default at some point, and packages which come with an explicit "as-of" flag would not be affected.

**Comment by vicuna** [comment]
**Comment author:** @lefessan

If we go along this path (which I have think is good), a few remarks:
* We could try to use the same options as some other compilers. For example, "javac" has a "-source" option for that, maybe easier to understand than "-as-of"
* I don't think we should aim at satisfying the two goals of Alain, but only the second one. Compatibility with a given version should be enforced by a style-checker, not the compiler itself. Also, the goal for me would be to specify that a package, in OPAM, at a given point, compiles with a given version, so the maintainer could use "ocamlc -source 4.04" to be sure that it will keep compiling, even if "-safe-string" is set in 4.05. Now, if, for a bug fix, I start using a feature of 4.05, I don't think it should prevent the package from compiling.

**Comment by vicuna** [comment]
**Comment author:** @dbuenzli

I'd be rather against this kind of proposal. They make it easier to split the ecosystem into packages and people using different languages while our goal should be to try to move the whole ecosystem so that we are all experiencing the same the language. It also makes debugging issues more difficult.

Regarding rejecting linguistic features I think these kind of things are best left to a separate linter tool (which could be distributed with OCaml).

**Comment by vicuna** [comment]
**Comment author:** @lefessan

@Daniel: you could see it the other way around. Such an option will help anybody to use the library from somebody else, even if that particular library was not designed to work with the same version of the compiler. So, it will actually help people to use each other's work, by removing a barrier that is currently present (and it will make the opam-repository more stable and resilient to compiler policy changes).

**Comment by vicuna** [comment]
**Comment author:** @dbuenzli

Well I don't see it the other way round. This introduces more build noise and complexity in the system.

**Comment by vicuna** [comment]
**Comment author:** @mshinwell

I tend to agree with dbuenzli that this seems likely to introduce more complexity than it solves.  Would anyone else like to weigh in?

**Comment by vicuna** [comment]
**Comment author:** @damiendoligez

For alain's first goal, just use `opam switch` to check with the actual version.

The second goal is more interesting, but I see this feature as complex and not well-specified. Which language and compiler features would be affected exactly? What about the standard library? And can you guarantee that code compiled with different versions will interoperate?

**Comment by ghost** [comment]
We have some experience about this in Dune since this is effectively what we do. In the case of Dune, this works really well. We can effectively go through breaking changes without pain and the latest `dune` binary is able to understand a wide range of projects written against different versions of Dune. We also provide an automatic upgrade tool to make it easy for authors to bring their project up to the latest standards.

However, this is manageable in the case of Dune because the surface API of Dune is small and we introduced this concept early on. Retrofitting this concept into OCaml would likely be a lot more work.
