### ISSUE TITLE
ocaml script mode, some errors are reported on stdout and do not lead to non-zero exit

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#7202]
**Original bug ID:** 7202
**Reporter:** @dbuenzli
**Status:** confirmed (set by @damiendoligez on 2016-04-05T14:34:13Z)
**Resolution:** open
**Priority:** normal
**Severity:** minor
**Version:** 4.02.3
**Category:** toplevel
**Monitored by:** @hcarty @dbuenzli

## Bug description

This seems right:
```
> cat script.ml 
#!/usr/bin/env ocaml

let (
> ocaml script.ml > /tmp/bla
File "script.ml", line 4, characters 0-0:
Error: Syntax error: operator expected.

> echo $?
2
```
However if I have:
```
> cat script.ml
#!/usr/bin/env ocaml

#mod_use "bli.ml"

> ocaml script.ml > /tmp/bla
> echo $?
0
> cat /tmp/bla
Cannot find file bli.ml.
```

**Comment by vicuna** [comment]
**Comment author:** @damiendoligez

The compiler should output error messages to stdout (because they are normal output of the compiler) and stop on error.
The toplevel should probably also output everything to stdout, but not stop on error.
The script mode should output errors to stderr and stop on error.

Currently, the script mode is heavily based on the toplevel. so this will probably need some non-trivial refactoring of the code.

**Comment by dbuenzli** [comment]
As far as the output is concerned what @damiendoligez suggests seems sensitive. In script mode either the runtime system should abort or exit via a specific high exit code (e.g. 125).
