### ISSUE TITLE
Polymorphic variant pattern syntax is too permissive

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#7213]
**Original bug ID:** 7213
**Reporter:** @yallop
**Status:** acknowledged (set by @gasche on 2016-04-05T14:43:15Z)
**Resolution:** open
**Priority:** normal
**Severity:** minor
**Target version:** later
**Category:** lexing and parsing
**Monitored by:** @gasche @diml @hcarty

## Bug description

The following should be rejected, for consistency with the expression syntax:

    function `A `B `C -> ()

**Comment by vicuna** [comment]
**Comment author:** @xavierleroy

Note that it "works" also with normal variants:

type t = A of t | B of t | C
let f = function A B C -> ()

What do we gain by complicating the parser to reject this?

**Comment by vicuna** [comment]
**Comment author:** @yallop

Well, it's a bit odd for constructor application to be right associative in patterns when expression application is left associative.

Oddness aside, bringing pattern and expression syntax into line could be used to simplify the parser, since the common bits could be factored out in some way, especially if we switch to menhir.

Even without refactoring, the change shouldn't complicate the parser.  Something like the following should do it:

```diff
diff --git a/parsing/parser.mly b/parsing/parser.mly
index f444810..fbb0619 100644
--- a/parsing/parser.mly
+++ b/parsing/parser.mly
@@ -1733,3 +1733,3 @@ pattern_gen:
       { mkpat(Ppat_construct(mkrhs $1 1, Some $2)) }
-  | name_tag pattern %prec prec_constr_appl
+  | name_tag simple_pattern %prec prec_constr_appl
       { mkpat(Ppat_variant($1, Some $2)) }
```

**Comment by Drup** [comment]
I ... actually like that feature. I use it occasionally (and I've seen it in the wild, so I'm not the only one). I'm not sure it's worth breaking existing code for this.

**Comment by trefis** [comment]
Agreed.
