### ISSUE TITLE
ocamlmklib should respect OCAMLPARAM

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#7219]
**Original bug ID:** 7219
**Reporter:** @whitequark
**Status:** acknowledged (set by @gasche on 2016-04-11T20:29:34Z)
**Resolution:** open
**Priority:** normal
**Severity:** feature
**Version:** 4.02.3
**Category:** tools (ocaml{lex,yacc,dep,debug,...})
**Tags:** junior_job
**Monitored by:** @gasche

## Bug description

... specifically, at least ccopts and cclib, but probably other variables too.

This makes it very annoying to pass -I/-L paths to native dependencies through e.g. OASIS.

**Comment by vicuna** [comment]
**Comment author:** @gasche

I think this is a fine feature suggestion, but the implementation is a bit tedious because ocamlmklib currently implements its own bare-metal argument handling logic, sensibly simpler than the rest of the compiler. That means you cannot just call the compiler OCAMLPARAM-parsing function and be done with it; the best way to go is probably to reimplement the command-line argument parsing logic of ocamlmklib.

Would anyone be interested in proposing a patch to do this?

**Comment by vicuna** [comment]
**Comment author:** @whitequark

What I did for now is implemented an OCAMLMKLIBPARAM (https://github.com/whitequark/opam-cross-android/blob/master/packages/ocaml-android32.4.02.3/files/patches/ocamlmklib.patch). But this is rather suboptimal.

**Comment by vicuna** [comment]
**Comment author:** @whitequark

FWIW ocamlmklib's options are sufficiently different from ocamlc's that I'm not sure if it even makes sense to reuse Compenv.read_OCAMLPARAM; what I would do is to call Compenv.parse_args, and then manually reimplement the parameters relevant for ocamlmklib, of which there are very few.

**Comment by whitequark** [comment]
With the broad migration to dune this issue is much less relevant and I suspect it can be simply ignored until the need for ocamlmklib goes away.

**Comment by xavierleroy** [comment]
That makes sense.  Closing.
