### ISSUE TITLE
Pack, CMI and module aliases

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#7223]
**Original bug ID:** 7223
**Reporter:** @let-def
**Status:** acknowledged (set by @damiendoligez on 2016-04-14T15:35:20Z)
**Resolution:** open
**Priority:** normal
**Severity:** minor
**Version:** 4.02.3
**Category:** misc
**Related to:** #4148
**Monitored by:** @hcarty

## Bug description

The issue is two fold:

First, the -pack option of the compiler seems to accept cmi files (interface only) as input.
There is extensive code in the compiler to support this (PM_intf in */*packager.ml files), so I guess this is a desired feature.
However I couldn't find corresponding documentation or specification, so I am unsure what the intended behavior is. Could this be clarified in the manual?

Finally, an inconsistent behavior appears between native and bytecode backends when mixing module aliases and packed interfaces.
Packing a CMI and referring to it via a module alias `module A = My_packed_intf` in another packed module fails in bytecode but succeeds in native.

## Steps to reproduce

Launching make with the three files provided triggers the issue.
A and B are setup as described above and the Makefile packs both with a bytecode and a native target.

Expected output:

$ make
ocamlopt -for-pack Fail -c a.mli
ocamlopt -for-pack Fail -c b.ml
ocamlopt -pack -o fail.cmx a.cmi b.cmx
ocamlc -for-pack Fail -c a.mli
ocamlc -for-pack Fail -c b.ml
ocamlc -pack -o fail.cmo a.cmi b.cmo
File "_none_", line 1:
Error: Forward reference to A in file b.cmo
Makefile:9: recipe for target 'byte' failed
make: *** [byte] Error 2

## Additional information

Also fails on 4.03.0+beta2

## File attachments

- [reproduce.tar](https://gist.githubusercontent.com/vicuna/bab81eb17b176584f3923794f8b2813c/raw/7dccf4411ee8300a23ed0b1e6cb0921ef320a0fa/reproduce.tar)

**Comment by lpw25** [comment]
There is some ongoing work to tidy up the implementation of `-pack`. We should consider this issue as part of that work.
