### ISSUE TITLE
Format only flushes std_formatter by at_exit.

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#7235]
**Original bug ID:** 7235
**Reporter:** furuse
**Assigned to:** @pierreweis
**Status:** assigned (set by @damiendoligez on 2017-02-23T15:29:02Z)
**Resolution:** open
**Priority:** normal
**Severity:** minor
**Version:** 4.02.3
**Category:** standard library
**Monitored by:** @gasche

## Bug description

I have just noticed that the following code of stdlib/format.ml:

(* Output everything left in the pretty printer queue at end of execution. *)
let () = at_exit print_flush

This code only flushes Format.std_formatter.  I am not sure it is easily possible to flush all the formatters associated with out_channels alive when at_exit is called but at least we can flush Format.err_formatter here too.

**Comment by vicuna** [comment]
**Comment author:** @pierreweis

Thank for the report.

Indeed, we should also flush err_formatter at end of program.

Extending this benavior to all formatters created by the library is more problematic since it could lead to excessive memory consumption (keeping track of all allocated formatters in a list or adding a closure for each new formatter to the list of thunks to execute at exit).

**Comment by dbuenzli** [comment]
It would be a good idea to do what Furuse suggested.

**Comment by gasche** [comment]
This was in fact done by Pierre Weis in a000769c8d813f7228211bd2cfb10467b564f86b in 2018 (gone into 4.08 I think), but this issue was not closed then.
