### ISSUE TITLE
document how to use the bug tracker (including for release triaging)

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#7236]
**Original bug ID:** 7236
**Reporter:** @gasche
**Status:** acknowledged (set by @gasche on 2016-04-20T15:35:52Z)
**Resolution:** open
**Priority:** low
**Severity:** feature
**Target version:** 4.07.0+dev/beta2/rc1/rc2
**Category:** documentation
**Monitored by:** runhang @hcarty

## Bug description

There are many tips that we could provide to our users about how to use the bug tracker, for example in the CONTRIBUTING.md document. Some useful information would be:

- how to search for similar bugs (I use google "site:caml.inria.fr/mantis" and it's surprisingly effective)
- how to choose a reporting category or Target version
- how to contribute if they want to help triaging:
  -- suggesting "related" bugs
  -- how to filter for bugs to solve or triage before the next release,
     what kind of triaging works helps accelerate the release process

**Comment by vicuna** [comment]
**Comment author:** @hcarty

It would be very nice to have a prominent link that takes you directly to the list of bugs assigned to the next release.  That would avoid the need to explain "how to search mantis" to someone who wants to help with higher priority (from a release standpoint) issues.

**Comment by vicuna** [comment]
**Comment author:** junsli

@hcarty: I think that is what the Roadmap link in heading for, isn't it?

**Comment by vicuna** [comment]
**Comment author:** @hcarty

Thanks for pointing me to that, I didn't realize that's what it was! Which somewhat illustrates my point: it would be nice to have a link directly to that view of mantis from CONTRIBUTING.md.

**Comment by vicuna** [comment]
**Comment author:** @hcarty

Another nice link to include would be http://caml.inria.fr/mantis/search.php?project_id=1&sticky_issues=1&sortby=last_updated&dir=DESC&highlight_changed=24&hide_status_id=90&tag_string=junior_job listing all of the junior_job-tagged tickets (courtesy of the OCaml Labs compiler hacking page).

**Comment by mshinwell** [comment]
@gasche Shall we close this?

**Comment by gasche** [comment]
Well I think we should still document how we use the Github bug tracker.
