### ISSUE TITLE
Provide %-primitives for operations on raw pointers

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#7252]
**Original bug ID:** 7252
**Reporter:** dobenour
**Status:** acknowledged (set by @damiendoligez on 2016-11-08T10:54:20Z)
**Resolution:** open
**Priority:** normal
**Severity:** feature
**Target version:** later
**Category:** standard library

## Bug description

I am writing an FFI module for OCaml and have noticed a lack of %-primitives to operate on raw pointers represented as nativeints

**Comment by vicuna** [comment]
**Comment author:** @diml

dobenour, what operations are you thinking about? If your pointers are represented as [Nativeint.t] values, can't you use functions from the [Nativeint] module?

**Comment by vicuna** [comment]
**Comment author:** dobenour

I am talking about operations that dereference the pointers.  This could be achieved by the following C external (for machine words, with [@@unboxed]):
```
  CAMLprim intptr_t dereference_pointer8(intptr_t ptr) {
    return *(uint8_t*)ptr;
  }
```
but that would be very slow for what should be a single instruction.

Both versions that require alignment and do not require alignment should be provided.

**Comment by vicuna** [comment]
**Comment author:** @xavierleroy

The return of PEEK and POKE... (https://en.wikipedia.org/wiki/PEEK_and_POKE)

I spent my computing life fleeing away from BASIC, either towards lower-level languages (C, assembly) where low-level stuff can be done properly, or towards higher-level languages (Pascal, Lisp, Caml, Coq) where all that low-level crap disappears.  Because of that I feel sad when people insist on doing low-level crap in Caml.

**Comment by vicuna** [comment]
**Comment author:** dobenour

The popularity of ctypes shows that people want to be able to interface with C using pure OCaml.  That means pointers.  Furthermore, Jane Street can use this feature (per a GPR), and I am certain that MirageOS can as well.

**Comment by vicuna** [comment]
**Comment author:** dobenour

Can you explain why low-level work cannot be done in OCaml?  C lacks a lot of features that OCaml has.  Not all low-level code must run without allocation.

**Comment by mshinwell** [comment]
We have discussed this before and I think it is clear that the proposals in their existing form are unsatisfactory.

**Comment by gasche** [comment]
Cross-link: this was proposed (and rejected) in #724.
