### ISSUE TITLE
meta-issue on consistency of command-line arguments across tools

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#7275]
**Original bug ID:** 7275
**Reporter:** @gasche
**Status:** confirmed (set by @gasche on 2017-02-24T20:40:42Z)
**Resolution:** open
**Priority:** normal
**Severity:** feature
**Target version:** later
**Category:** tools (ocaml{lex,yacc,dep,debug,...})

## Bug description

The -open argument was introduced in 4.02.0, but support for -open in ocamldoc was proposed just today in trunk:
  https://github.com/ocaml/ocaml/pull/613

This meta-issue is meant to track similar mismatches, and encourage us to check that various ocaml tools support the new options that make sense for each of them.

**Comment by vicuna** [comment]
**Comment author:** @shindere

As such I find this issue a bit vague. Would it be possible to add issues for each such inconsistency? Such more precise issues would be easier to work on and close.

**Comment by vicuna** [comment]
**Comment author:** @gasche

Yes, the idea is to open issues for each such inconsistency, but to mark them all as children of this meta-issue (an issue about issues), so that it is easy to navigate from one to another of these issues -- this issue effectively collects a list, as well as giving us a central place in which to have discussions about command-line mismatches in general.

(You may ask what's the difference between meta-issues and tags. I have a personal tendency to use meta-issues to group related bugs together, and tags to describe a cross-cutting methodology aspect of an issue, but I'm not sure this distinction is always consistently done.)

**Comment by shindere** [comment]
This meta-issue has been silent so I will close it now.

It can always be reopened if it becomes useful again in the future.
