### ISSUE TITLE
Parenthesis surprisingly needed by immediate objects

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#7308]
**Original bug ID:** 7308
**Reporter:** SpiceGuid
**Status:** acknowledged (set by @xavierleroy on 2017-02-23T16:07:04Z)
**Resolution:** open
**Priority:** low
**Severity:** feature
**Version:** 4.03.0
**Category:** lexing and parsing

## Bug description

This is a oneliner :

object method one = 1 end # one;;

Trivially corrected as :

(object method one = 1 end) # one;; 

Immediate objects also must also be parenthesised when used as a function actual argument.

## Additional information

My intuition is that the end keyword closes a parenthesis.
I don't understand why i should add more nesting.

**Comment by garrigue** [comment]
Anybody has an opinion on this ?
I don't quite remember why I chose to keep immediate objects as complex expressions.
On the other hand, I personally think that keeping the parentheses makes the code more readable, but other may think differently.

**Comment by Drup** [comment]
I remember being surprised multiple times that `f object ... end` didn't parse.

**Comment by damiendoligez** [comment]
I'd rather let it parse. You'll still be able to add parentheses to make it more readable.
