### ISSUE TITLE
Build compiler distribution tools with $(EXE) extension from the start

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#7312]
**Original bug ID:** 7312
**Reporter:** @gasche
**Assigned to:** @shindere
**Status:** assigned (set by @shindere on 2016-12-13T08:44:13Z)
**Resolution:** open
**Priority:** normal
**Severity:** feature
**Version:** 4.03.0
**Target version:** later
**Category:** configure and build/install

## Bug description

In #729

  https://github.com/ocaml/ocaml/pull/729

Alain Frisch and Sébastien Hinderer remarked that currently, ocaml (and now ocamlnat) are built with the $(EXE) extension from the start, while most other tools are built without extensions and given an extension at install time.

It would be more consistent to build all tools directly with an $(EXE) extension.

## Additional information

The makefile rules to have both (ocamlnat) and (ocamlnat$(EXE)) work as Makefile targets (so that "make ocamlnat" keeps working on Windows after the change) is a bit tricky to setup as just "ocamlnat: ocamlnat$(EXE)" could give an infinite loop, see

https://github.com/ocaml/ocaml/blob/e1b57c4a39c72ab06d7f7b7816cc8b4c16815775/Makefile.shared#L326-L334

**Comment by vicuna** [comment]
**Comment author:** @xavierleroy

If it's just a question of consistency, we could also build everything without the $(EXE) suffix.  What are the pros and cons for building with $(EXE) from the start?

**Comment by vicuna** [comment]
**Comment author:** @gasche

Sébastien's argument in the github discussion was as follows:

> First it seems a bit more logical to me,
> second and perhaps more concretely it lets one
> run the executable without having to
> install it outside of a Cygwin environment.

**Comment by shindere** [comment]
This issue still needs to be worked on.

It is assigned to me and I am happy to work on it.

**Comment by shindere** [comment]
Fixed by #9652. Closing.
