### ISSUE TITLE
information in the typing error message could be made more precise

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#7318]
**Original bug ID:** 7318
**Reporter:** kosik
**Status:** acknowledged (set by @damiendoligez on 2016-11-08T10:49:30Z)
**Resolution:** open
**Priority:** low
**Severity:** feature
**Version:** 4.03.0
**Target version:** 4.05.0 +dev/beta1/beta2/beta3/rc1
**Category:** typing

## Bug description

When I type:

```ocaml
  module M1 =
  struct
    type t = V0 | V1
  end

  (* M1 and M2 are equivalent *)
  module M2 =
  struct
    type t = M1.t = V0 | V1
  end

  (* M1 and M3 are not equivalent *)
  module M3 =
  struct
    type t = V0 | V1
  end

  module M4 =
  struct
    type t = {f0 : unit * unit * unit * M1.t * unit * unit * unit;
              f1 : unit * unit * unit * M1.t * unit * unit * unit}
  end

  (* A failed attempt to define a module equivalent to M4 *)
  module M5 =
  struct
    type t = M4.t = {f0 : unit * unit * unit * M2.t * unit * unit * unit;
                     f1 : unit * unit * unit * M3.t * unit * unit * unit}
  end
```

then the compiler (correctly) complains that:

```
  Error: This variant or record definition does not match that of type M4.t
         The types for field f1 are not equal.
```

The compiler marks the whole record definition.

Couldn't compiler mark the location of the particular field of the record whose type breaks the desired equality? (in this case "`f1 : unit * unit * unit * M3.t * unit * unit * unit`")

Or, even better, would it be possible to mark the location of the specific type-sub-term that breaks the equality? (in this case "`M3.t`")?

**Comment by Drup** [comment]
This has been improved significantly, here's the current error message:
```
Error: This variant or record definition does not match that of type M4.t
       Fields do not match:
         f1 : unit * unit * unit * M1.t * unit * unit * unit;
       is not compatible with:
         f1 : unit * unit * unit * M3.t * unit * unit * unit;
       The types are not equal.
```
