### ISSUE TITLE
Provide a way to ignore existentials in GADT pattern matching

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#7319]
**Original bug ID:** 7319
**Reporter:** @alainfrisch
**Status:** acknowledged (set by @damiendoligez on 2016-09-27T14:23:18Z)
**Resolution:** open
**Priority:** normal
**Severity:** feature
**Target version:** later
**Category:** typing
**Has duplicate:** #7091
**Related to:** #5736
**Monitored by:** @yallop @Chris00

## Bug description

Consider:

<pre>
type _ ty =
  | Int: int ty
  | String: string ty
  | Bool: bool ty

let to_int: type t. t ty -> t -> int = fun ty x ->
  match ty with
  | Int -> x
  | String -> failwith "..."
  | Bool -> failwith "..."
</pre>

One cannot share the last two cases with a simple or-pattern, because the type of ty is refined to two incompatible types (even if this type is not used).

Of course, one can share by introducing a function and call it in each case, but this is still quite a bit heavier than just <tt>String | Bool -> failwith "..."</tt>.  The risk is that users simply write <tt>| _ -> ...</tt> in such cases, which is more fragile.

I'm wondering if something could be done to address that, either requiring some explicit syntax (to tell the type-checker not to refine the type) or not (delaying refinement until the case needs it?).  If we add some syntax to name existentials, could we reuse it with "_" as the name to ignore one specific existential?

**Comment by trefis** [comment]
This particular situation is now handled since 4.08, as a result of #2110.
