### ISSUE TITLE
Ocamldoc does not recognize included module

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#7332]
**Original bug ID:** 7332
**Reporter:** andy
**Status:** acknowledged (set by @Octachron on 2017-02-23T23:38:50Z)
**Resolution:** open
**Priority:** low
**Severity:** minor
**Platform:** x64
**OS:** Linux Mint
**OS Version:** 17.3
**Version:** 4.03.0
**Target version:** later
**Category:** ocamldoc
**Monitored by:** @gasche @Yakobowski

## Bug description

Any use of the `include` construct incurs a warning that the included module was not found.

## Steps to reproduce

mkdir repro && cd repro
echo "include String" > main.ml
ocamldoc -html main.ml

Output: "Warning: Module or module type String not found"

**Comment by Drup** [comment]
I suggest we close this (and focus any work in the area on odoc).
