### ISSUE TITLE
meta-issue on confusing type error messages

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#7338]
**Original bug ID:** 7338
**Reporter:** @gasche
**Status:** confirmed (set by @gasche on 2016-08-30T06:30:10Z)
**Resolution:** open
**Priority:** normal
**Severity:** text
**Version:** undecided
**Target version:** later
**Category:** typing
**Parent of:** #5888 #6173 #7336 #7565 #7574
**Monitored by:** @Drup @hcarty @dbuenzli

## Bug description

The ticket #5068 serves as a parent issue for reports of confusing syntax error messages. This ticket can serve as parent issue for reports of confusing typing error messages.

## Additional information

It may not be obvious for beginners to tell whether an error is a type error or syntax error (syntax errors have "Syntax error" in the error message and occur before -dsource output), and some typos at the syntactic level result in typing errors, but experienced users would do the triaging. The reason to separate them is that the ways to fix them, and thus the cost/benefit analysis inherent in any discussion, are very different.

**Comment by Drup** [comment]
What do we want to do with such meta-issues ? I'm not sure how useful they are. Maybe we should turn them into tags ?

**Comment by gasche** [comment]
Are you sure how useful tags are? Meta-issues also provide a place for discussion, and are easy to use using the cross-reference mechanisms between issues.

**Comment by Octachron** [comment]
There are still live issues connected to this meta-issue.

**Comment by XVilka** [comment]
There is a label "error-messages", I suggest to assign it to this issue, it will finding all these error message improvements easier:
https://github.com/ocaml/ocaml/labels/error-messages
