### ISSUE TITLE
callbacks from C to ocaml need nested functions where it shouldn't need to

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#7340]
**Original bug ID:** 7340
**Reporter:** goswin
**Status:** feedback (set by @mshinwell on 2016-12-08T07:42:36Z)
**Resolution:** open
**Priority:** normal
**Severity:** feature
**Target version:** undecided
**Category:** runtime system and C interface

## Bug description

When you have a callback from C to ocaml and support blocking sections then 2 functions are needed over and over again in the same pattern:

```C
    void outer(const char *name) {
        caml_leave_blocking_section();
        inner(name);
        caml_enter_blocking_section();
    }

    void inner(const char *name) {
        CAMLparam0();
        CAMLlocal1(_name);
        _name = caml_copy_string(name);
        caml_callback1(_func, _name);
        CAMLreturn0;
    }
```

There should be a macro `CAMLenter()` that combines `caml_leave_blocking_section();` with `CAMLparam0();`
 and macros `CAMLleave0()` and `CAMLleaveT(type, arg)` that combine `caml_enter_blocking_section()` with the respective `CAMLreturn*` macros.

Note: The inner function can never return a value so the equivalent of `CAMLreturn(value)` makes no sense. Should there be a `CAMLleave()` that doesn't create a local copy of the return value instead?

**Comment by vicuna** [comment]
**Comment author:** @ygrek

There is CAMLdrop now, see ocaml/ocaml#4891

**Comment by vicuna** [comment]
**Comment author:** goswin

Yes, but that's only have the solution imho.

**Comment by vicuna** [comment]
**Comment author:** @ygrek

You mean "half of the solution"?
I think it is adequate solution and nothing more to fix here.

**Comment by vicuna** [comment]
**Comment author:** @mshinwell

@goswin Please explain why you think CAMLdrop is insufficient.

**Comment by yallop** [comment]
I think Goswin's concern may be that the call to `CAMLlocal1` needs to be preceded by a call to `CAMLparam0`, and the documentation for `CAMLparam0` says:

```
   The function body must start with one of the [CAMLparam] macros.
```

so it appears that the body of `inner` can't be inlined into `outer`, since that would place `CAMLparam0` after the call to `caml_leave_blocking_section` (i.e. not at the beginning of the function).

I think `CAMLparam0` can probably be safely be placed after the call to `caml_leave_blocking_section`, and the documentation is a bit too restrictive.  If that's true then we can fix this issue by clarifying the documentation.

**Comment by stedolan** [comment]
If compiling with a C90 compiler, the `CAMLparam0` must be at the start of a block but that need not be at the start of a function. So the following works:

```c
void foo(const char *name) {
    caml_leave_blocking_section();
    {
        CAMLparam0();
        CAMLlocal1(_name);
        _name = caml_copy_string(name);
        caml_callback1(_func, _name);
        CAMLdrop;
    }
    caml_enter_blocking_section();
}
```
