### ISSUE TITLE
With mix of packs and objects, ocamlc accepts wrong code or displays wrong error message

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#7359]
**Original bug ID:** 7359
**Reporter:** sebmondet
**Assigned to:** @garrigue
**Status:** assigned (set by @xavierleroy on 2017-02-18T11:16:25Z)
**Resolution:** open
**Priority:** normal
**Severity:** minor
**Target version:** 4.06.0 +dev/beta1/beta2/rc1
**Category:** typing
**Monitored by:** @hcarty

## Bug description

This happened in big libraries and was difficult to spot (https://github.com/hammerlab/{ketrew,biokepi,epidisco}).
I have extracted the reproduction of the bug to 3 files that do not have dependencies:

https://gitlab.com/smondet/repro_ocaml_pack_problem

The reproduction there uses OCaml 4.02.3.

With 4.03.0, this seems partially fixed (?), at least in the same case we get an error but the error message still points at the wrong field:

 $ File "mod_c.ml", line 5, characters 2-27:
Error: This expression has type Mod_a.product Lib_a.Mod_a.Container.t
       It has no method product
Hint: Did you mean product?

(while the method that does not exist is `path`)

Not sure if this exhibits a deeper issue, or if it has been really fixed in 4.03.0.

**Comment by vicuna** [comment]
**Comment author:** @xavierleroy

The repro case still fails in 4.05.0 beta.

Concerning the error, it definitely complains that "(Lib_b.Mod_b.get_mod_a p)" has no (visible) method named "product".  The #path is not even typechecked.  So, there are two independent questions here:
- Why is t that the "suggestion" code sees a method named "product" while the type-checker does not?
- Is it the case that there is no visible method named "product" here?

@garrigue could you please have a quick look at this issue?  We'll probably move it to 4.06 anyway.

**Comment by vicuna** [comment]
**Comment author:** @Octachron

If it helps, I have a somewhat simplified test case in https://github.com/Octachron/ocaml/tree/MPR7359/testsuite/tests/typing-pack .

**Comment by vicuna** [comment]
**Comment author:** @gasche

This may slide into 4.07 if Jacques still doesn't have time to look at it.

**Comment by garrigue** [comment]
Checking with trunk (before 4.12), the hint has disappeared. I don't know where it happened.

The error is still there, but it seems correct: the problem is the same module is used as packed for a value, and through the original cmi for a type. Since this type is structural, there is no error at this point. Later the type is no longer accessible, which makes it implicitly abstract, hence the error.
