### ISSUE TITLE
support --external-tokens like menhir(ocamlyacc)

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#7380]
**Original bug ID:** 7380
**Reporter:** @bobzhang
**Status:** feedback (set by @shindere on 2017-02-24T15:24:19Z)
**Resolution:** open
**Priority:** normal
**Severity:** feature
**Category:** tools (ocaml{lex,yacc,dep,debug,...})

## Bug description

currently the ocamlyacc will impose lexer depends on parser. 
This is not necessary, and sometimes you have more tokens than the parser need

**Comment by vicuna** [comment]
**Comment author:** @gasche

I don't understand why people are still using ocamlyacc in this day and age, Menhir is superior in many different respects and ocamlyacc should be deprecated. I don't want to invest work in improving ocamlyacc myself. Of course, if you find people willing to write a patch and others to review it, feel free to.

I would be more interested in hearing about the issues that make people prefer ocamlyacc over Menhir. I know that, for existing parsers, transitioning is not so easy because of the different interface to access source locations. Are there other issues that should be considered?

**Comment by vicuna** [comment]
**Comment author:** @bobzhang

@gasche, I understand menhir is superior to ocamlyacc. 

The main reason is dependencies. In commercial environment(does not apply to academy or startups), every piece of software has to be carefully reviewed by lawyers, this may take several months if lucky. In most cases, developers won't bother, just use the software already boss approved (here the official ocaml distribution: ocamlyacc)

I am happy to write patches for it.

**Comment by vicuna** [comment]
**Comment author:** @shindere

Why would a project that needs such a feature use ocamlyacc rather than menhir, actually?
Given the legacy status of ocamlyacc and the discussions around its replacement by Menhir even for the OCaml parser itself it seems unlikely to me that such a feature will be implemented in Menhir one day so I'm tempted to say this won't be fixed and close this issue.

**Comment by xavierleroy** [comment]
We're in 2020, Menhir is the recommended parser generator for OCaml, ocamlyacc is legacy software and will not be chnaged except to fix serious bugs.
