### ISSUE TITLE
meta-issue on type and path propagation

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#7409]
**Original bug ID:** 7409
**Reporter:** @gasche
**Status:** confirmed (set by @gasche on 2016-11-12T15:19:49Z)
**Resolution:** open
**Severity:** feature
**Version:** undecided
**Category:** typing
**Parent of:** #6784 #7386 #7388 #7389

## Bug description

This meta-issue is meant to gather and reference issues that are related to the propagation of type information or type annotation during type-checking (typically for GADT typing and for disambiguation of type-ambiguous variant constructors and fields), as well as more syntactic techniques that also correspond to a propagation of path information (eg. turning { M.x = e1; y = e2 } into { M.x = e1; M.y = e2 }).

**Comment by vicuna** [comment]
**Comment author:** @gasche

In #285 ( https://github.com/ocaml/ocaml/pull/285 ), Frédéric Bour proposed to propagate when typing the argument of an application the result of unifying the expected return type of the application with the function-result type obtained by inferred the applied function expression.

**Comment by garrigue** [comment]
Meta issues should not be stale. Or does it apply to all feature wishes?

**Comment by Octachron** [comment]
I am removing the stale label due to the last active issue linked to this meta-issue.

**Comment by ygrek** [comment]
related https://github.com/ocaml/ocaml/issues/10572
