### ISSUE TITLE
excessive inlining of jump tables

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#7449]
**Original bug ID:** 7449
**Reporter:** markghayden
**Assigned to:** @chambart
**Status:** assigned (set by @chambart on 2017-01-03T20:59:28Z)
**Resolution:** open
**Priority:** normal
**Severity:** minor
**Platform:** AMD64
**OS:** MacOS
**OS Version:** 10.12.2
**Version:** 4.04.0
**Category:** middle end (typedtree to clambda)
**Tags:** flambda
**Monitored by:** @gasche @ygrek

## Bug description

See the attached code.  The [to_string] function is inlined at all call sites, even with no optimization specified at the command line (!?!).  Note that each call site includes a full copy of the jump table and all the jump branches.  The test case here has 30 items.  I've seen this with larger cases (300 items).  Maybe I'm missing something, but it seems this is really off here since this behavior can result in significant code growth.  A work-around is to annotate with '[@inline never]'.

## Steps to reproduce

Compile with 4.04.0 or 4.05.0.dev trunk.  Note that for 4.05.0.dev, the lookup table is used if all the return values are constants and perhaps that is OK to inline.  Added a [failwith] for one of the cases forces the use of jump tables, at least on AMD64.

  ocamlopt  -c -S du.ml

## Additional information

See attached ML file.  Assembler output will follow.

## File attachments

- [du.ml](https://gist.githubusercontent.com/vicuna/733c0e55d549bc98266f7120833c7ed1/raw/cfb34474ec5add4608232604d68dc9ad17debfa6/du.ml)
- [du.s](https://gist.githubusercontent.com/vicuna/733c0e55d549bc98266f7120833c7ed1/raw/533850dce9799aa42b01200713ca8cbbba009034/du.s)

**Comment by vicuna** [comment]
**Comment author:** @alainfrisch

Is this this flambda?  I cannot reproduce in non-flambda mode, except by passing a large -inline command-line argument to ocamlopt.

**Comment by vicuna** [comment]
**Comment author:** markghayden

All my testing was with flambda-enabled compilers.

**Comment by lthls** [comment]
I can confirm that this bug is still present; the size estimation for switches doesn't seem to take the size of the actions into account.
Cc @chambart
