### ISSUE TITLE
constant blocks are in random order

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#7450]
**Original bug ID:** 7450
**Reporter:** markghayden
**Assigned to:** @chambart
**Status:** assigned (set by @chambart on 2017-01-03T21:03:08Z)
**Resolution:** open
**Priority:** normal
**Severity:** feature
**Platform:** AMD64
**OS:** MacOS
**OS Version:** 10.12.2
**Version:** 4.04.0
**Category:** middle end (typedtree to clambda)
**Tags:** flambda

## Bug description

Compile a file such as:

let v0 = [0;1;2;3;4;5;6;7;8;9;10;11;12;13;14;15;16;17] ;;

Then review the order of the constant blocks in the resulting assembly (attached).  They appear to be in a random order, perhaps as though they were dumped from a hash table.

It is understood that with shared constant blocks the order may at times depend on the specifics of the sharing.  However, it seems like a better idea would be to follow some heuristic order rather than scrambling them. with a goal to achieve better locality and cache-behavior.  For instance, in this case it might be better if the order were in depth-traversal so that scanning the list resulted in reading forward through memory.  Perhaps enumerating constant blocks first by file-order in which the containing block first appeared and then by depth traversal order would be simple and effective.

## Steps to reproduce

Compiled with 4.05.0+flambda trunk.

## File attachments

- [cc.s](https://gist.githubusercontent.com/vicuna/d003ce68ee4c60992bb4582aae407eab/raw/256e4b00a2f9e861baed5164ce0f90f7fe89369c/cc.s)

**Comment by lthls** [comment]
I think this one has been fixed some time ago. At least with the provided example, the constant blocks appear in the source file order in this particular case.

Feel free to reopen if you find other examples of bad ordering.
