### ISSUE TITLE
ocamllex and ocamlyacc should check that there are balanced parentheses in code blocks

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#7455]
**Original bug ID:** 7455
**Reporter:** dobenour
**Status:** acknowledged (set by @xavierleroy on 2017-02-19T16:59:08Z)
**Resolution:** open
**Priority:** normal
**Severity:** minor
**Version:** 4.04.0
**Target version:** 4.07.0+dev/beta2/rc1/rc2
**Category:** tools (ocaml{lex,yacc,dep,debug,...})
**Monitored by:** bikal

## Bug description

ocamllex and ocamlyacc both fail to check for balanced parentheses in code blocks.  This allows for invalid OCaml code to be generated.  In the case of ocamlyacc, it might be possible to break the type system due to the use of Obj in the generated code, though I don't think so.

## File attachments

- [conflict.mly](https://gist.githubusercontent.com/vicuna/3e6f72b23f9d561ef5dcfa4b82bfbe53/raw/883a36012e078b4d66eacc54642ff3bf22ee731f/conflict.mly)

**Comment by vicuna** [comment]
**Comment author:** @dra27

Out of curiosity, do you have a nefarious example which actually compiles?

**Comment by vicuna** [comment]
**Comment author:** dobenour

I just attached conflict.mly.  When processed with ocamlyacc, it produces a file conflict.ml which segfaults when run.

**Comment by vicuna** [comment]
**Comment author:** @dra27

https://github.com/ocaml/ocaml/pull/1012

**Comment by vicuna** [comment]
**Comment author:** @Octachron

Note: the above PR has been merged in 4.06 trunk and fixes the issue on the ocamlyacc side, but not the ocamllex side.

**Comment by gasche** [comment]
It looks like no one is willing to put the work to solve this issue (for ocamllex; the ocamlyacc part has been solved). Maybe it's okay to officially give up and close it for good?
