### ISSUE TITLE
Printing of type aliases in signatures could be improved (with nonrec)

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#7458]
**Original bug ID:** 7458
**Reporter:** @yallop
**Assigned to:** @garrigue
**Status:** assigned (set by @damiendoligez on 2017-02-23T16:03:12Z)
**Resolution:** open
**Priority:** normal
**Severity:** feature
**Target version:** later
**Category:** typing
**Related to:** #4791 #6634
**Monitored by:** @gasche @hcarty

## Bug description

Type aliases declared with nonrec are printed with nonrec, as expected:

     # module type S = sig type t module M : sig type nonrec t = t end end;;
     module type S = sig type t module M : sig type nonrec t = t end end

but type aliases resulting from substitution are printed incorrectly:

     # module type S = sig type t module M : sig type t end with type t = t end;;
     module type S = sig type t module M : sig type t = t end end

**Comment by vicuna** [comment]
**Comment author:** @garrigue

This is just a fresh instance of the "unprintable signature bug", with the variant that here, there is a way to print it correctly.
Unfortunately, this is not so easy in general.
For instance, consider:

module type S = sig type t module M : sig type u = U of v * t and t and v = u end with type t = t end

In order to print this type correctly, one would have to reorder the definitions, to remove t from its recursive group, and have it come first. This is doable, but not completely trivial. And there is the question of whether we want to do that always, or only when needed (requires some detection code), i.e. avoid to change the apparence of the signature when this is not needed.

So my feeling is that it is doable (move each instantiated definition just before its recursion group, and add a nonrec keyword), but requires a bit of code to do it, and more code if we want to be conservative.

**Comment by shindere** [comment]
@garrigue To me, it seems that what needs to be done here is above all
to decide whether this is going to be fixed or not. It does not seem to
be a problem to not fix this right now, but it feels it would be nice to
at least make a decision. What do you think?

Also, when you mention the "unprintable signature bug", do you refer to
a precise issue? Would you be able to link to it, if that's the case?

**Comment by yallop** [comment]
Local substitutions should make this easier.  For example, @garrigue's example now has a straightforward solution:

```ocaml
module type S = sig
  type t
  module M : sig
    type t' := t
    type u = U of v * t
     and t = t'
     and v = u
  end
end
```

as does my original example:

```ocaml
module type S = sig
   type t
   module M : sig
     type t' := t
     type t = t'
   end
end
```

**Comment by trefis** [comment]
#6634 seems to be the place where the discussion is happening; so I'm closing this.
