### ISSUE TITLE
Strange interpretation of a free type variable in a method type in a signature

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#7465]
**Original bug ID:** 7465
**Reporter:** @fpottier
**Assigned to:** @garrigue
**Status:** confirmed (set by @garrigue on 2017-01-24T07:54:20Z)
**Resolution:** open
**Priority:** normal
**Severity:** feature
**Category:** typing
**Monitored by:** @gasche @yallop

## Bug description

See attached file bizarre.ml.

The comparison between the signatures M1 and M3 fails,
whereas I thought it should succeed.
The type error message shows that the type of the method check,
which is declared as "method check: 'c",
is interpreted as "method check: 'c . 'c".
Is this behavior intended?
It seems to me that there should NOT be an implicit universal quantification
over 'c at the level of the method.

This is all the more surprising since the comparison between M1 and M2 succeeds.
(This seems correct.)
This shows that the declaration "method check: 'a . 'c"
is correctly interpreted as "method check: 'c"
where 'c is a free variable.

## File attachments

- [bizarre.ml](https://gist.githubusercontent.com/vicuna/a0df713d675cc29ad13cb0caeac13b65/raw/520972c14b069e4ec4dd3319ba5d03438b8da6c3/bizarre.ml)

**Comment by vicuna** [comment]
**Comment author:** @garrigue

This is the expected behavior: in a class type, a free type variable in a method is generalized, as otherwise the class type would be invalid, hence the meaning for M3.
However, if the type variable already appears in a constraint (M1) or if an explicit polymorphic type is given (M2), this is not the case.

This behavior was chosen to simplify the writing of polymorphic methods, particularly when there are row types involved.

But you have a point here: since in M3 the type of self is captured by a type variable, and as a result the type where 'a is not quantified would still be valid,, it would be more natural to have the same behavior as M1 and M2. In theory, this is a change in behavior, but in practice I would not expect this to break anything. We would still need a clear criterion for that.

**Comment by vicuna** [comment]
**Comment author:** @fpottier

Hi Jacques.
Yes, my thinking is that if the class is parameterized over the type of self, then the equality constraint 'self = < list of all methods; .. > should be implicitly added to the class type. That should allow the method types to  contain free type variables, without creating problems.

**Comment by garrigue** [comment]
@fpottier I don't see why it should be so. Currently the criterion is that any type variable in a method type that is not explicitly bound in a class parameter or a contraint is interpreted as universal in the method type. This seems a simple enough criterion. It would be strange that just having the type of self appear in a parameter should change this behaviour, and there is nothing wrong in having polymorphic methods appear in the type of self.

**Comment by fpottier** [comment]
I am not suggesting any change. Actually, the behavior that surprised me at the time is documented in the manual ("The polymorphism may be left implicit in public method specifications: any type variable which is not bound to a class parameter and does not appear elsewhere inside the class specification will be assumed to be universal, and made polymorphic in the resulting method type. Writing an explicit polymorphic type will disable this behaviour."). But, because the manual does not contain any examples, it is actually fairly difficult to understand what it means...

**Comment by gasche** [comment]
So you are suggesting to add examples to the manual. Would you be willing to submit them as a PR?

**Comment by fpottier** [comment]
I wrote about some of my findings in the [visitors manual](http://cambium.inria.fr/~fpottier/visitors/manual.pdf) (Section 4), but I wouldn't have time at the moment to turn that into a PR, sorry.
