### ISSUE TITLE
Compiler flag to disable the "implicit interface" feature.

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#7493]
**Original bug ID:** 7493
**Reporter:** @damiendoligez
**Status:** confirmed (set by @damiendoligez on 2017-02-24T14:17:53Z)
**Resolution:** open
**Priority:** normal
**Severity:** feature
**Version:** 4.05.0 +dev/beta1/beta2/beta3/rc1
**Category:** compiler driver
**Tags:** junior_job

## Bug description

Following the discussion in https://github.com/ocaml/ocaml/pull/217, the core team agreed that we would like a command-line option to make the compiler raise an error when compiling a .ml file if the corresponding .mli is missing.

**Comment by Octachron** [comment]
A warning would probably be a better option than a compiler flag in this case.

**Comment by Anukriti12** [comment]
Hi, I am an outreachy applicant. Can i work on this issue?

**Comment by Anukriti12** [comment]
Hi, I am an outreachy applicant. I'd like to work on this issue.

**Comment by Anukriti12** [comment]
Hi! I'm an Outreachy applicant. I looked up the source code and found parse_intf function of `compile_common.ml` is responsible for compilation of .mli interface file. I would like to work on this issue. As @Octachron  suggested it's better to put a warning then a compiler flag I can put a wrapper which will check mli file path before actually compiling it.

**Comment by gasche** [comment]
The PR #9407 is in almost-mergeable state; I think we should make a decision there, either finish and merge it, or decide that we don't really want the feature and close the PR and the issue.
