### ISSUE TITLE
Infer variance for GADTs without equality

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#7494]
**Original bug ID:** 7494
**Reporter:** @yallop
**Assigned to:** @garrigue
**Status:** assigned (set by @yallop on 2017-02-24T14:28:33Z)
**Resolution:** open
**Priority:** normal
**Severity:** feature
**Category:** typing
**Related to:** #5688 #7004
**Monitored by:** @gasche

## Bug description

The current approach to variance for GADT-style definitions is overly conservative.

For example, the following program is currently accepted:

   type 'a t = T of 'a
   type +'a s = 'a t

but the following program, which ought to be equivalent, is rejected:

   type 'a t = T : 'a -> 'a t
   type +'a s = 'a t

The second program can be fixed by adding a variance annotation to 't' -- i.e., variance for GADT-style definitions is checked, but not inferred.

It would be safe, consistent, and convenient to infer variance for parameters of GADT-style definitions that don't partake in any equalities (i.e. that are not refined in the return types of constructors).

**Comment by vicuna** [comment]
**Comment author:** @gasche

I thought I'd add a reference to my work on variance of GADTs, that discusses whether it is possible to also infer variances for variables that *do* participate in GADT equations (in short: yes, but it requires making assumptions on the language that are true today but would not necessarily be preserved by new typing features):

  GADTs meet subtyping
  Gabriel Scherer, Didier Rémy, 2013
  https://arxiv.org/abs/1301.2903

**Comment by garrigue** [comment]
This issue seems to be about something much simpler: currently, a variant type is consider to be a GADT as soon as one of its constructors is given with an explicit return type. But this syntax can also be used for normal constructors (involving no equation). It would be better to have a semantic criterion.
This said, the syntactic criterion also has advantages, as changes In behaviour are immediately visible from the syntax.

**Comment by gasche** [comment]
Well I assume that @yallop would also be interested in constructors that do contain existential types, or add equality constraints on some other type parameters. The point is to ask whether the non-guarded parameters could have their variance inferred.
