### ISSUE TITLE
Odd behaviour of refutation cases with polymorphic variants

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#7520]
**Original bug ID:** 7520
**Reporter:** @lpw25
**Status:** acknowledged (set by @xavierleroy on 2017-09-30T09:08:45Z)
**Resolution:** open
**Priority:** normal
**Severity:** minor
**Version:** 4.04.0
**Target version:** later
**Category:** typing
**Monitored by:** @gasche @yallop

## Bug description

Refutation cases have some odd behaviour with polymorphic variants. Given an uninhabited type:
```ocaml
type ('a, 'b) eq = Refl : ('a, 'a) eq
type empty = (int, string) eq
```
The following fails:
```
  # let f = function `Foo (_ : empty) -> .;;
  Characters 17-33:
    let f = function `Foo (_ : empty) -> .;;
                     ^^^^^^^^^^^^^^^^
  Error: This match case could not be refuted.
         Here is an example of a value that would reach it: `Foo _
```
It continues to fail if the variant type is constrained:
```
  # let f : [< `Foo of empty] -> int = function `Foo (_ : empty) -> .;;
  Characters 44-60:
    let f : [< `Foo of empty] -> int = function `Foo (_ : empty) -> .;;
                                                ^^^^^^^^^^^^^^^^
  Error: This match case could not be refuted.
         Here is an example of a value that would reach it: `Foo _
```
But it works of the type is fixed:
```
  # let f : [`Foo of empty] -> int = function `Foo (_ : empty) -> .;;
  val f : [ `Foo of empty ] -> int = <fun>
```
Or if we add a second empty refutation case:
```
  # let f : [< `Foo of empty] -> int = function `Foo _ -> . | _ -> .;;
  val f : [ `Foo of empty ] -> int = <fun>
```

**Comment by vicuna** [comment]
**Comment author:** @lpw25

This seems to be a regression between 4.03.0 and 4.04.0.

**Comment by vicuna** [comment]
**Comment author:** @garrigue

OK, the situation is rather complicated.
The problem here is that, when checking inhabitedness, the type annotation on _ is no longer available.
It disappears when we move from parse tree to typed tree and back.
The type of the whole pattern is available, and correctly pushed in, but when checking inhabitedness,
unification ignores the "second true" in Reither (the one that force the unification of the argument) for soundness reasons. So in the end, the type "empty" is not propagated to the wild card argument to `Foo,
no splitting is done.

The natural fix here would be to reconstruct the type annotation to the wild card, which is available in the typed tree but discarded in the translation (it cannot occur for generated patterns). But this requires writing a new translation to parsetree types. It might be possible to use Untypeast.typ, but I'm concerned that the scoping might be wrong... or is it really ok?

By the way, the behavior when adding an extra refutation is strange. The type inferred seems wrong anyway.

**Comment by vicuna** [comment]
**Comment author:** @garrigue

Actually, I understand what's happening in the last case: pressure_variants is called with all the cases (including the refutations), and assumes that this is an open variant type, which later by unification makes it a fixed one.
Not sure what the correct behavior should be. Probably remove all the refutation cases when calling pressure_variants.

BTW, in what kind of code does this pattern arise?

**Comment by vicuna** [comment]
**Comment author:** @garrigue

Tentative fix at https://github.com/ocaml/ocaml/pull/1328, using Untypeast.

Note that I didn't fix the second problem (with an extra refutation case), because removing refutation cases breaks the logic of pressure_variants. It seems better to assume that adding an extra refutation cases implies a real intent wrt. the inferred type.

**Comment by vicuna** [comment]
**Comment author:** @xavierleroy

Tentative fix didn't work.  Pushing this for after 4.06.

**Comment by lpw25** [comment]
Is this issue made any easier to fix by the various changes to typing pattern matching?

Personally, I still think that the general approach of generating actual Parsetree fragments and re-typechecking them is a mistake that is destined to always cause issues like this one. Is there a particular reason that we don't have a separate data type to represent the candidate patterns (with things like type annotations and constructor identifiers already resolved) and a separate function for check that these candidate patterns are well typed?

**Comment by garrigue** [comment]
For me this rather falls in the category: combination of GADT and polymorphic variant is unsupported.
And no, the changes to type_pat do not help, they have just made the code more complicated.

**Comment by garrigue** [comment]
Looking back at #7269, which is the source of the `passive_variants` mode, it seems that always setting `passive_variants` changes nothing in the test suite. This probably related to the fact type checking of counter-examples is now more relaxed.

If I remove `passive_variants`, this solves this problem, so I'm tempted to do that. It was just a hack anyway.

**Comment by gasche** [comment]
> And no, the changes to type_pat do not help, they have just made the code more complicated.

⸮

**Comment by garrigue** [comment]
I should have add: for me.
Since I understood well the code from the beginning, all your "improvement" do not help me.
But I understand that they can help others.
