### ISSUE TITLE
Spurious unused module warning (warning 60) with recursive modules

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#7522]
**Original bug ID:** 7522
**Reporter:** @SkySkimmer
**Status:** acknowledged (set by @dra27 on 2017-04-27T19:43:56Z)
**Resolution:** open
**Priority:** normal
**Severity:** tweak
**Version:** 4.04.1
**Category:** misc
**Child of:** #7314
**Monitored by:** @Yakobowski

## Bug description

This is mentioned at the end of #7314 by @eponier whose reproduction is smaller than mine.

## Steps to reproduce

module M : sig module A : sig type t end end =
struct
  module rec A : sig type t end = struct type t = B.t end
  and B : sig type t end = struct type t = A.t list end
end

With 4.04.1, "ocamlc -w A" returns "Warning 60 : unused module B".

**Comment by lpw25** [comment]
This was fixed by #9393.
