### ISSUE TITLE
Improve sharing of values

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#7535]
**Original bug ID:** 7535
**Reporter:** Eugene
**Status:** acknowledged (set by @xavierleroy on 2017-09-30T16:09:30Z)
**Resolution:** open
**Priority:** normal
**Severity:** feature
**Version:** 4.04.1
**Category:** back end (clambda to assembly)

## Bug description

Given following snippet of a code:

  type 'a id = Id of 'a

  let make (Id x) = Id x

allocation happens every time 'make' called (using flambda-enabled compiler).
Unfortunately it prevents a lot of further optimizations that could happen if it was compiled as simply

  let make (Id _ as x) = x

It seems that flambda already capable of eliminating some allocations, i.e.

  let make x =
    let f (Id x) = Id x in
    f @@ f @@ f @@ f @@ f x

allocates only one block.

**Comment by vicuna** [comment]
**Comment author:** @sliquister

In this specific example, you'd be better off adding [@@unboxed] on the type definition (or using the command flag that adds it implicitely).

But it's true that sometimes, the compiler could avoid reallocating things, especially when the workaround is not expressible in the source like:

function
| [] -> assert false
| hd :: tl -> hd, tl

**Comment by nojb** [comment]
I believe this is implemented in #8958 (but the PR seems to have stalled).
