### ISSUE TITLE
@inlined doesn't seem to work with module aliases

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#7538]
**Original bug ID:** 7538
**Reporter:** talex
**Assigned to:** @mshinwell
**Status:** assigned (set by @mshinwell on 2017-05-23T13:46:02Z)
**Resolution:** open
**Priority:** normal
**Severity:** minor
**Version:** 4.04.1
**Category:** middle end (typedtree to clambda)

## Bug description

When building a project with @inlined annotations using jbuilder, OCaml complains that 'the "inlined" attribute cannot appear in this context'. Turning off "wrapped" mode made the warning go away. It looks like @inlined doesn't work with module aliases.

## Steps to reproduce

(simplified by lpw25)

module M = Map.Make[@inlined](String);;

works, but:

module N = Map
module M = N.Make[@inlined](String);;

gives:

Warning 53: the "inlined" attribute cannot appear in this context

**Comment by vicuna** [comment]
**Comment author:** @mshinwell

Before anyone else spends time on this: Leo and I are aware of various other problems relating to inlining annotations on functors (including their failure to work when functors have multiple arguments and/or coercions).  We will produce fixes as soon as we can.

**Comment by lpw25** [comment]
The weird difference in behaviour with aliases for the warning has been fixed. Although I should point out that placing the annotation there in both cases will do nothing useful. Probably we should be warning in both cases.

**Comment by lpw25** [comment]
Fix for this in #9669. It will now give the warning on all the cases.
