### ISSUE TITLE
"lazy" example in the tutorial part of the manual

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#7547]
**Original bug ID:** 7547
**Reporter:** @Octachron
**Status:** acknowledged (set by @Octachron on 2017-07-11T19:45:18Z)
**Resolution:** open
**Priority:** low
**Severity:** feature
**Category:** documentation
**Tags:** manual, junior_job
**Monitored by:** @gasche

## Bug description

Lazy expressions (and patterns) are only described in the language part of the manual and the "Lazy" module documentation. Since the existence of this feature is hard to infer from the rest of the language, it would be nice to have at least one short example of lazy expression in the tutorial part of the manual and a link to the module documenation. One possible good emplacement for this example might be a new "Lazy expressions" section right the after the "Exceptions" section (http://caml.inria.fr/pub/docs/manual-ocaml/coreexamples.html#sec13) in the core language chapter.

**Comment by vicuna** [comment]
**Comment author:** @ulugbekna

If no one minds, I will work on this.

**Comment by ulugbekna** [comment]
Afaiu, this issue is closed already.

**Comment by vicuna** [comment]
Fixed in #2273

**Comment by vicuna** [comment]
Thanks!
