### ISSUE TITLE
printf or format example in the tutorial part of the manual

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#7548]
**Original bug ID:** 7548
**Reporter:** @Octachron
**Status:** acknowledged (set by @Octachron on 2017-07-11T19:45:06Z)
**Resolution:** open
**Priority:** low
**Severity:** feature
**Category:** documentation
**Tags:** manual, junior_job
**Monitored by:** @gasche

## Bug description

Currently, the tutorial part of the manual takes some time to describe the pretty printing of symbolic expressions at http://caml.inria.fr/pub/docs/manual-ocaml/coreexamples.html#sec15 . However, this example uses neither the "Printf" nor the "Format" module. Since pretty printing is a major use of both modules and "Printf" and "Format" relies on a potentially surprising feature of OCaml, it would be nice to extend the existing example with a version using either "Printf" or "Format".

**Comment by vicuna** [comment]
**Comment author:** lereena

I will work on this issue

**Comment by vicuna** [comment]
**Comment author:** sshv

Can I work on this?

**Comment by vicuna** [comment]
**Comment author:** lereena

@sshv I have already completed it, you should choose another issue

**Comment by vicuna** [comment]
**Comment author:** @gasche

@lereena's proposed patch is undergoing review at
  https://github.com/ocaml/ocaml/pull/2272

**Comment by gasche** [comment]
#2272 has now been merged: we have a nice explanation of `Printf` in the manual. I'll leave this issue open to track the idea of also having a presentation of `Format`, but personally I'm not sure it belongs to the "tutorial" part of the manual, as Format is sensibly more specialized. I would rather have a nice documentation at the beginning of the Format module (so at the beginning of `format.mli`).

**Comment by Octachron** [comment]
Let's close the issue for now. We can open an issue for a format tutorial if the need arises.
