### ISSUE TITLE
Support selection of source file names also for other export formats than make rules

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#7558]
**Original bug ID:** 7558
**Reporter:** @elfring
**Status:** acknowledged (set by @xavierleroy on 2017-06-22T18:07:45Z)
**Resolution:** open
**Priority:** normal
**Severity:** feature
**Version:** 4.03.0
**Category:** tools (ocaml{lex,yacc,dep,debug,...})
**Related to:** #7576
**Parent of:** #7559 #7560

## Bug description

The description for the parameter “-modules” of the tool “ocamldep” contains the following information.

“Output raw dependencies of the form …, but these names are not resolved to source file names.”

I would appreciate if referenced OCaml modules could be exported with their names resolved to appropriate paths.
How are the chances to offer another data export variant there?

## Additional information

It seems that such name conversion is only performed for make file rules so far.

**Comment by elfring** [comment]
I am still curious how affected software components will be improved also for this issue.
