### ISSUE TITLE
Support export of software dependencies from OCaml modules in the format “XML”

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#7559]
**Original bug ID:** 7559
**Reporter:** @elfring
**Status:** acknowledged (set by @xavierleroy on 2017-06-22T18:11:28Z)
**Resolution:** open
**Priority:** normal
**Severity:** feature
**Version:** 4.03.0
**Category:** tools (ocaml{lex,yacc,dep,debug,...})
**Related to:** #7560
**Child of:** #7558

## Bug description

I imagine that it would be occasionally nice to perform higher level data processing with dependency information.
How do you think about to export corresponding data from referenced OCaml modules in the format “Extensible Markup Language” (by the tool “ocamldep”)?

## Additional information

https://en.wikipedia.org/wiki/XML

**Comment by vicuna** [comment]
**Comment author:** @gasche

Sure, what is the format that you would like? Would you care to implement yourself and submit a Pull Request? The part of ocamldep's logic you would care about is in driver/makedepend.ml

  https://github.com/ocaml/ocaml/blob/trunk/driver/makedepend.ml

and I think it should not be too difficult to add another output format with the same output structure.

**Comment by vicuna** [comment]
**Comment author:** @gasche

(Note that it would probably also be rather easy to do this as an external tools relying on compilerlibs. Whether you need the feature to be in "ocamldep" itself probably depends on your use-case.)

**Comment by vicuna** [comment]
**Comment author:** @elfring

If you would like to support XML export in a safe way, I imagine also that it will be needed to clarify the use of file formats like the following.

* Document type definition

* RELAX NG

* XML Schema


I am not going to contribute a pull request for affected OCaml software components (for a while).

**Comment by vicuna** [comment]
**Comment author:** @xavierleroy

I find JSON simpler and more palatable, but that's personal taste.

**Comment by dbuenzli** [comment]
I can't think of an existing XML format and associated software for which this would be useful right away. 

*If* a more machine readable output is really needed I #7560 seems more reasonable in the world we live now. Given it's the same person who reported, I bet he would be equally satisfied. 

I would move on to close this.

**Comment by elfring** [comment]
I am still curious how affected software components can be improved also for this issue.
