### ISSUE TITLE
Fix position information for diagnostics by the OCaml linking software

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#7568]
**Original bug ID:** 7568
**Reporter:** @elfring
**Status:** acknowledged (set by @dra27 on 2017-06-26T16:55:22Z)
**Resolution:** open
**Priority:** normal
**Severity:** tweak
**Platform:** openSUSE Tumbleweed
**Version:** 4.03.0
**Category:** compiler driver
**Tags:** junior_job
**Related to:** #7566
**Monitored by:** @hcarty

## Bug description

I tried a software development approach out where I adjusted some variables in build scripts. This had the “side effect” (for a moment) that an order of object files was chosen for an executable file which the OCaml linker did not like.

The error message contained the information “File "_none_", line 1:”. I suggest to improve the software diagnostics around such places.

This request is the continuation for a detail from my previous bug report “Checking processes for resolving of references from module implementations by the OCaml linker”.

## Additional information

ocaml/ocaml#7566#c17997

**Comment by vicuna** [comment]
**Comment author:** @dra27

Request is to eliminate the sentinel location value in transcripts such as:

<pre>
/usr/bin/ocamlopt.opt … -o spatch.opt … ctl/ctl.cmxa …
File "_none_", line 1:
Error: No implementations provided for the following modules:
         Pretty_print_ctl referenced from ctl/ctl.cmxa(Ctl_engine)
</pre>

(for example, either not displaying the File line, or including a different message such as "Linker error")

**Comment by elfring** [comment]
I am still curious how affected software components will be improved also for this issue.

**Comment by damiendoligez** [comment]
The `File` line should not be eliminated because it marks the beginning of the error message that can be automatically recognized by tools such as emacs.

Whatever you do to this line, in the end it must match one of the regular expressions used by emacs to parse error messages. In practice that means you can only change the file name (the part between quotes) and the line number.
