### ISSUE TITLE
Make the dependency generator for OCaml better usable for out-of-source builds

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#7577]
**Original bug ID:** 7577
**Reporter:** @elfring
**Status:** closed (set by @dra27 on 2017-07-03T10:38:54Z)
**Resolution:** not a bug
**Priority:** normal
**Severity:** feature
**Version:** 4.03.0
**Category:** tools (ocaml{lex,yacc,dep,debug,...})

## Bug description

I started to experiment a bit more for build script adjustments for another free software.

elfring@Sonne:~/Projekte/Bau/OCamlbuild> ocamldep -one-line -I ~/Projekte/OCaml/OCamlbuild/lokal/src ~/Projekte/OCaml/OCamlbuild/lokal/src/command.mli
/home/elfring/Projekte/OCaml/OCamlbuild/lokal/src/command.cmi : /home/elfring/Projekte/OCaml/OCamlbuild/lokal/src/tags.cmi /home/elfring/Projekte/OCaml/OCamlbuild/lokal/src/signatures.cmi

This tool is writing references for compiled interface descriptions with paths of the source file directory.
How can be achieved that this program will use the working directory (or an other specification for the desired software build folder) for these cmi files?

**Comment by vicuna** [comment]
**Comment author:** @dra27

You have repeatedly been asked to post questions to caml-list (which I know you're on) or discuss.ocaml.org

**Comment by vicuna** [comment]
**Comment author:** @elfring

I have reported a specific detail in the data display which I find inappropriate in the mentioned use case.
Please let us fix the affected software somehow.

**Comment by vicuna** [comment]
**Comment author:** @dra27

You have not reported anything - you have asked a question as to whether ocamldep can work as you require and I have told you to ask your question elsewhere.

Please stop re-opening these reports.

**Comment by elfring** [comment]
Can the clarification of affected software components be continued also for this issue?

**Comment by dra27** [comment]
This issue doesn’t need continuing - it was closed with a specific remedy which as far as I’m aware hasn’t been followed.
