### ISSUE TITLE
CAMLlocalN does not compile with msvc compiler

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#7581]
**Original bug ID:** 7581
**Reporter:** @nojb
**Status:** acknowledged (set by @xavierleroy on 2017-07-12T17:07:22Z)
**Resolution:** open
**Priority:** normal
**Severity:** minor
**Target version:** 4.07.0+dev/beta2/rc1/rc2
**Category:** runtime system and C interface
**Monitored by:** @ygrek @oandrieu

## Bug description

The msvc compiler allows variable declarations only after opening braces.  As such the CAMLlocalN macro does not errors out.

Is there some C macro wizardy that would make this work ?

**Comment by vicuna** [comment]
**Comment author:** @yallop

The difficulty is apparently caused by the loop that initializes 'x':

```C
  for (caml__i_##x = 0; caml__i_##x < size; caml__i_##x ++) { \
    x[caml__i_##x] = Val_unit; \
  } \
```

`CAMLlocalN` inserts the output of `CAMLxparamN` (i.e. some additional declarations) after the loop, but this kind of mixing of declarations and code is not allowed in C89.

One possible fix is to move the array initialization code to an inline function (assuming it can be guaranteed that the function is actually always inlined) and replace the loop by a dummy declaration whose rhs calls the function:

```C
  CAMLunused_start int caml__dummy_##x = (caml_initialize_array(x, size), 0);
```

**Comment by vicuna** [comment]
**Comment author:** @xavierleroy

Would it be possible to initialize the array with zeros instead of Val_unit?  (I think it's OK with the current GC but maybe not with the no-naked-pointer stuff.)  In this case, 

  int x[N] = {0, };

is enough to initialize the local array x with all zeroes, regardless of its size N.

**Comment by vicuna** [comment]
**Comment author:** @xavierleroy

Wading through history, I see zero-initialization was used (correctly) until commit https://github.com/ocaml/ocaml/commit/05100e597e4296a2e79e6c2d9cd75b7e1cc595c9 and following, which insisted on Val_unit initialization.

**Comment by vicuna** [comment]
**Comment author:** @nojb

From Github's discussion: this issue only affects versions prior to Visual 2013.

**Comment by vicuna** [comment]
**Comment author:** @stedolan

It's also possible to just add some more curly braces. C89 insists that declarations come at the start of a block, not necessarily at the start of a function.

Something like this should work:

{ \
  int caml__i_##x; \
  for (caml__i_##x = 0; caml__i_##x < size; caml__i_##x ++) { \
    x[caml__i_##x] = Val_unit; \
  } \
}

**Comment by vicuna** [comment]
**Comment author:** @nojb

This works if CAMLlocalN is the last declaration in the enclosing function.

**Comment by vicuna** [comment]
**Comment author:** @stedolan

> This works if CAMLlocalN is the last declaration in the enclosing function.

Of course, you're right. I think yallop's solution works in all cases, as does zero-initialisation (with the appropriate check in caml_do_local_roots).

**Comment by vicuna** [comment]
**Comment author:** @xavierleroy

We need to decide a course of action.  

One possibility is to partially revert https://github.com/ocaml/ocaml/commit/05100e597e4296a2e79e6c2d9cd75b7e1cc595c9 and following commits by supporting (again) zero-initialization of local roots (but only local roots).  What this means is just an extra test "root != NULL" in the "Local C roots" part of [caml_oldify_local_roots].

Another possibility is to say that versions of MSVC prior to Visual 2013 are no longer officially supported.

**Comment by vicuna** [comment]
**Comment author:** @mshinwell

@lpw25 and I were discussing adding an explicit Obj.null value (which would usually be represented by an actual zero).  Doing this would necessitate the GC being safe against it even in no-naked-pointers mode.  That value could then be used for the initialisation of the arrays in this issue.

For the moment I would suggest trying the inline function version, although I don't think you will be obtain a guarantee that the function is inlined.

**Comment by mshinwell** [comment]
I think we're planning to produce a patch with an explicit `Obj.null` in the near future, so the zero-initialisation approach could then be used here.

**Comment by damiendoligez** [comment]
ISTR that we stopped restricting ourselves to C89 some time ago. For example, there are a number of `//` comments in the C code.
