### ISSUE TITLE
manual: document .cmt* files in the "overview" of ocaml{c,opt}

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#7584]
**Original bug ID:** 7584
**Reporter:** @gasche
**Status:** acknowledged (set by @gasche on 2017-07-12T19:07:31Z)
**Resolution:** open
**Priority:** low
**Severity:** text
**Target version:** 4.07.0+dev/beta2/rc1/rc2
**Category:** documentation
**Tags:** junior_job

## Bug description

The "overview of the compiler" sections of the ocamlc and ocamlopt sections of the manual give a summary of the role of various file extensions consumed or produced by the ocaml compilers

  http://caml.inria.fr/pub/docs/manual-ocaml/comp.html#sec265
  http://caml.inria.fr/pub/docs/manual-ocaml/native.html#sec286

Unfortunately, they were never updated to describe .cmt* files, so users that look at the build artifacts of a project may not know what those are.

**Comment by Lereena** [comment]
If nobody minds, i will try to work on this issue.

**Comment by Octachron** [comment]
Sure, go ahead.

**Comment by Lereena** [comment]
I see that in these chapters there is a lot of almost identical information about files of various formats and their processing during compilation. Should I duplicate information about .cmt/cmti in both chapters?

**Comment by damiendoligez** [comment]
ping @Octachron

**Comment by Octachron** [comment]
Except if you want to backport the manual addition to 4.08.1, the issue can be closed.
