### ISSUE TITLE
“ocamldep -all” does not express dependencies on MLI files.

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#7593]
**Original bug ID:** 7593
**Reporter:** @elfring
**Status:** closed (set by @xavierleroy on 2017-07-21T15:26:11Z)
**Resolution:** not a bug
**Priority:** low
**Severity:** trivial
**Version:** 4.03.0
**Category:** tools (ocaml{lex,yacc,dep,debug,...})

## Bug description

I wonder why dependencies are incompletely exported for module interface source files.

## Steps to reproduce

I have tried the following command out.
```
elfring@Sonne:~/Projekte/OCaml/OCamlbuild/lokal> ocamldep -all -one-line src/*.ml* > ../dep-all1.txt
```
## Additional information

Development status of the dependency generator for OCaml
https://sympa.inria.fr/sympa/arc/caml-list/2017-07/msg00087.html

**Comment by vicuna** [comment]
**Comment author:** @xavierleroy

"I wonder why" is not a problem report.  Please keep those questions for caml-list, as you have already been instructed to do several times.

**Comment by vicuna** [comment]
**Comment author:** @elfring

Please fix the data set which is written by the command “ocamldep -all”.

**Comment by elfring** [comment]
Will other users care for the affected software components any more?

**Comment by damiendoligez** [comment]
Sample output from the reporter's command line:
```
bar.cmo : bar.cmi bar.ml
bar.cmx bar.o : bar.cmi bar.ml
bar.cmi :
foo.cmo : bar.cmi foo.cmi foo.ml
foo.cmx foo.o : bar.cmi bar.cmx foo.cmi foo.ml
foo.cmi :
```

Note that it does say that `bar.cmo` depends on `bar.ml` but not that `bar.cmi` depends on `bar.mli`. Is there a reason for this discrepancy? Do we want to fix it?

**Comment by rixed** [comment]
I guess the suggestion is that ocamldep should also output "bar.cmi : bar.mli" when it sees that a bar.mli file is present, and maybe "bar.cmi : bar.ml" when only bar.ml is present?

It might be confusing when/if one generates the mli file out of the ml file though (`ocamlc -i`).

Other than that, I can't understand why it's been designed this way; which is not to say I do not believe there is/was a valid reason.
