### ISSUE TITLE
Document why, when and how to update magic numbers

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#7599]
**Original bug ID:** 7599
**Reporter:** @gasche
**Status:** acknowledged (set by @xavierleroy on 2017-09-21T08:32:40Z)
**Resolution:** open
**Priority:** low
**Severity:** text
**Target version:** 4.07.0+dev/beta2/rc1/rc2
**Category:** documentation
**Tags:** junior_job
**Related to:** #7598 #7600

## Bug description

Currently external contributors may not know about magic numbers, when to update them, and what is the process to update them (in particular, I believe that a bootstrap is needed?).

This could be explained in comments in utils/config.mlp (I like having documentation close to the code) or maybe in utils/HACKING.adoc.

**Comment by vicuna** [comment]
**Comment author:** @alainfrisch

Cf discussion on https://github.com/ocaml/ocaml/pull/1402 . In particular, Xavier suggested the following scheme:

> @damiendoligez and I were discussing an even more radical solution: just
> derive the magic numbers from the version number, e.g. CamlTMMmmpp, where T
> identifies the type of file, MM the major version number, mm the minor
> version number, and pp the patchlevel. No more bumping necessary!

**Comment by Octachron** [comment]
The magic numbers have been documented in `utils/HACKING.adoc`. (Improvements are always possible)
