### ISSUE TITLE
Document the commit process around bootstrapping

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#7600]
**Original bug ID:** 7600
**Reporter:** @gasche
**Status:** acknowledged (set by @xavierleroy on 2017-09-30T09:06:22Z)
**Resolution:** open
**Priority:** low
**Severity:** text
**Version:** 4.06.0 +dev/beta1/beta2/rc1
**Target version:** later
**Category:** documentation
**Related to:** #7599

## Bug description

There is documentation about the bootstrap process in two places:

- in INSTALL.adoc#bootstrap, there are accessible explanations on what a bootstrap from a working compiler does
- in Makefile, the "hard bootstrap how-to" explains how to do bootstrap across changes that break stuff (and thus require a bootstrap)

To my knowledge there is no public description of when to bootstrap, and of the commit process around a bootstrap. (I believe both changed in the last couple years, with the primitive stuff requiring less bootstraps and the consensus to separate bootstrap commits from the rest.)

## Additional information

This is related to #7599 (documentation for magic number updates) given that documenting the commit process around magic numbers requires being able to explain the bootstrap part.

**Comment by vicuna** [comment]
**Comment author:** @xavierleroy

Any volunteers?

**Comment by dbuenzli** [comment]
There is now a good [`BOOTSTRAP.adoc`](https://github.com/ocaml/ocaml/blob/trunk/BOOTSTRAP.adoc)  document for these things in the source tree. 

Sorry to hijack the autoclose but people searching the issue tracker may fall on this. I think this issue can be closed. 

Meta note. I find a little bit sad that the OCaml project decided to declare bug bankruptcy by going to such extremes as labelling one year old bug as stale while it could have gradually have closed say 20-30 bugs per months starting by *the oldest ones* that were filed 18 years ago.

**Comment by xavierleroy** [comment]
> it could have gradually have closed say 20-30 bugs per months starting by the oldest ones that were filed 18 years ago.

Do you think we are so stupid that we didn't think of that?  

All the old bugs were "touched" on March 19, 2019, when they were automatically migrated to Github issues.  Hence, from the bot's viewpoint, these migrated issues are one year old.

**Comment by dbuenzli** [comment]
> Do you think we are so stupid that we didn't think of that?

No, I thought you would have programmed a bot less stupid than that. As far as I can see the original date of the report was migrated correctly. All these github APIs exist for something.
