### ISSUE TITLE
compiler error with flambda

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#7645]
**Original bug ID:** 7645
**Reporter:** @c-cube
**Assigned to:** @chambart
**Status:** confirmed (set by @chambart on 2017-10-02T18:27:44Z)
**Resolution:** open
**Priority:** normal
**Severity:** minor
**Version:** 4.05.0
**Category:** middle end (typedtree to clambda)
**Duplicate of:** #3922
**Related to:** #7349
**Monitored by:** @gasche @mshinwell @chambart

## Bug description

When compiling the (very ugly) ml file in the linked archive, ocaml 4.05.0+flambda gives the following error:

Warning 58: no cmx file was found in path for module CCFun, and its interface was not compiled with -opaque
>> Fatal error: Map.disjoint_union Logtk.camlLogtk__Util__set_of_closures_anon-fn[/home/simon/.opam/4.05.0+flambda/build/ocaml/stdlib/format.ml:1248,4--46]_10533 => Util._1 <> Logtk._976
Fatal error: exception Misc.Fatal_error

## Steps to reproduce

archive: https://cedeela.fr/~simon/files/bugflambda.tar.gz

- switch to 4.05.0+flambda
- install containers
- `$ tar xvf bugflambda.tar.gz`
- `$ ocamlfind ocamlopt -c -package containers logtk.cmxa -I . parse_dk.ml`

should yield the error. Sorry for the size of the archive, it only seems to happen when .cmx files are present (not if there's only a cmxa), so I suspect it's related to inlining.

**Comment by vicuna** [comment]
**Comment author:** @c-cube

I think the error is caused by the same module (`Util`) being present both in packed and unpack forms. This is the case because I forgot an `open` in an oasis project, and the error doesn't happen if `Util` is only accessed through the pack.

However the error should probably be caught earlier! :)

**Comment by vicuna** [comment]
**Comment author:** zozozo

The error seems similar to the one I reported in ocaml/ocaml#7349

**Comment by vicuna** [comment]
**Comment author:** @xavierleroy

Pierre or Mark, could you please have a look at this one?

**Comment by vicuna** [comment]
**Comment author:** @chambart

Yes this looks likely to be the pack problem. I can't be absolutely certain without the whole build, but this is highly probable given the contents of the cmx files.

I suggest that we simply forbid (or at least quite visibly warn) linking to a module built with -for-pack when not using the same -for-pack.

**Comment by vicuna** [comment]
**Comment author:** @chambart

The gpr https://github.com/ocaml/ocaml/pull/1391 proposes such a change.

**Comment by lthls** [comment]
There is ongoing work on improving the situation with packs (and a few other related issues). There is an RFC describing the proposal at ocaml/RFCs#13.
Until then the problem remains.

**Comment by gasche** [comment]
This should be solved by #1391, but that PR is in a suspend state with neither @chambart nor @mshinwell available to look at it.

**Comment by lthls** [comment]
Note: I've got a rebased version of #1391 [here](https://github.com/lthls/ocaml/tree/pack-consistency).
I'll try to do a few checks on opam packages, and will work with @chambart next week on getting it merged.
