### ISSUE TITLE
Out of range jumps to caml_call_gc labels

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#7667]
**Original bug ID:** 7667
**Reporter:** @kayceesrk
**Status:** acknowledged (set by @xavierleroy on 2017-11-05T17:42:51Z)
**Resolution:** open
**Priority:** normal
**Severity:** minor
**Platform:** powerpc64le
**OS:** Linux
**Category:** back end (clambda to assembly)
**Related to:** #3086 #3117
**Monitored by:** @gasche

## Bug description

On PowerPC Linux, trunk OCaml generates out of range jumps to caml_call_gc label. The bug was triggered while installing alt-ergo.1.01 and magic-mime.1.1.0. 

----

debian@ocaml-debian-le:~/.opam/4.07.0+trunk+bench/.opam-switch/build/alt-ergo.1.01$ make
ocamlopt.opt -c -annot -inline 100 -I /home/debian/.opam/4.07.0+trunk+bench/lib/zarith  -I /home/debian/.opam/4.07.0+trunk+bench/lib/lablgtk2 -I +threads -I src/util -I src/structures -I src/theories -I src/instances -I src/sat -I src/preprocess -I src/parsing -I src/gui -I src/main -I non-free/plugins/common -I non-free/plugins/satML -I non-free/plugins/profiler -I non-free/plugins/fm-simplex src/theories/intervals.ml
/tmp/camlasma487b4.s: Assembler messages:
/tmp/camlasma487b4.s:15010: Error: operand out of range (0x00000000000080a8 is not between 0xffffffffffff8000 and 0x0000000000007ffc)
File "src/theories/intervals.ml", line 1:
Error: Assembler error, input left in file /tmp/camlasma487b4.s
Makefile.users:229: recipe for target 'src/theories/intervals.cmx' failed
make: *** [src/theories/intervals.cmx] Error 2

----

This bug is a duplicate of #3117 (ocaml/ocaml#3117&history=1) which is marked as fixed (?). Wondering whether the change suggested in #3117 should be incorporated.

**Comment by vicuna** [comment]
**Comment author:** @xavierleroy

770 [#3117] and 723 [#3086] were for PowerPC 32 bits, while this one is PowerPC 64 bits little-endian, and since they were fixed in 2001-2002 the code for PowerPC branch relaxation was rewritten.

**Comment by vicuna** [comment]
**Comment author:** @xavierleroy

I don't have access to a POWER8 (ppc64le) machine, so someone who does should handle this MPR.

**Comment by vicuna** [comment]
**Comment author:** @kayceesrk

I have access to a ppc64le machine. I'll handle this MPR.

**Comment by nojb** [comment]
Has this been fixed @kayceesrk ?
