### ISSUE TITLE
Sys.command and Windows quoting

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#7672]
**Original bug ID:** 7672
**Reporter:** @Chris00
**Status:** acknowledged (set by @xavierleroy on 2017-11-17T18:21:08Z)
**Resolution:** open
**Priority:** normal
**Severity:** minor
**Platform:** x86_64
**OS:** GNU/Linux
**OS Version:** Debian testing
**Version:** 4.06.0
**Category:** standard library
**Related to:** #6107 #7794
**Monitored by:** @gasche

## Bug description

When quoting several arguments in a command that will be sent to Sys.command, on must also quote the whole string for Windows cmd.   This was discussed in https://github.com/janestreet/jbuilder/issues/322 ; the Windows quoting rules are at 
- https://www.borngeek.com/2011/03/22/calls-to-system-in-windows/
- https://stackoverflow.com/a/9965141
Given these unusual quoting rules, adding a function to quote a full command (such as Filename.quote_command : string list -> string) should be discussed.

**Comment by vicuna** [comment]
**Comment author:** @xavierleroy

That's not the first time we discuss the weird quoting conventions of cmd.exe.  I'll try to find the relevant problem reports and link them here.

I'm not opposed to have a quoting function for invoking Sys.command as envisioned in the PR; only, it should be called Sys.quote_command because it has nothing to do with Filenames.

**Comment by vicuna** [comment]
**Comment author:** @xavierleroy

On second thoughts, I'm not so sure that it should be called Sys.quote_command.  That would probably create a circular dependency between modules Sys and Filename.

**Comment by vicuna** [comment]
**Comment author:** @nojb

Closely related to ocaml/ocaml#6107

**Comment by vicuna** [comment]
**Comment author:** @Chris00

@xleroy Another possibility would be Sys.run : string -> string list -> int that would take care of escaping the command and its arguments.

**Comment by vicuna** [comment]
**Comment author:** @xavierleroy

Pull request here: https://github.com/ocaml/ocaml/pull/1492

The suggested "Sys.run" is unhelpful, I think, because if you want file redirections or pipes or other special shell characters in the command given to Sys.command, they must NOT be escaped.  The documentation included in the pull request points this out.

**Comment by damiendoligez** [comment]
Fixed by #1492
