### ISSUE TITLE
Clarify how `-c` and `-o` are supposed to work.

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#7677]
**Original bug ID:** 7677
**Reporter:** @dbuenzli
**Status:** acknowledged (set by @xavierleroy on 2017-11-26T16:25:09Z)
**Resolution:** open
**Priority:** normal
**Severity:** minor
**Version:** 4.06.0
**Target version:** 4.07.0+dev/beta2/rc1/rc2
**Category:** documentation
**Monitored by:** @dbuenzli @Yakobowski

## Bug description

The release notes of 4.04.0 point to 

 https://github.com/ocaml/ocaml/commit/da56cf6dfdc13c09905c2e07f1d4849c8346eec8

as explaining that. However it seems that part of this work was invalidated by: 

https://github.com/ocaml/ocaml/pull/761

and nowadays trying to use `ocamlc -o DEST -c file.c` results in the following error: 

  Options -c and -o are incompatible when compiling C files

It seems build systems using ocaml are doomed for life to need to move the produced `file.o` manually from the `cwd` to the desired destination directory.

**Comment by vicuna** [comment]
**Comment author:** @xavierleroy

Yes, it's a mess.  Let's try to at least agree on what behavior is intended.  I'll restart the discussion at https://github.com/ocaml/ocaml/pull/761

**Comment by vicuna** [comment]
**Comment author:** @damiendoligez

If I remember correctly, some C compilers do not support outputting files in a different directory. When given "-o outdir/outfile", they would create "outfile" in the current directory. Hence the restriction added by Fabrice.

**Comment by dbuenzli** [comment]
AFAIR this is still a mess and should be clarified.

**Comment by shindere** [comment]
I just checked and even cl knows how to put object files in a directory
different from the one containing the C source file.

I thus think this issue could and should be fixed and shall work on it.

**Comment by shindere** [comment]
It is my belief that the present issue has been fixed by #9960, which
has just been merged into trunk. Thus closing.
