### ISSUE TITLE
32-bit gcc potential segfault whith -malign-double

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#7681]
**Original bug ID:** 7681
**Reporter:** @nojb
**Status:** acknowledged (set by @xavierleroy on 2017-12-20T16:57:36Z)
**Resolution:** open
**Priority:** normal
**Severity:** minor
**Category:** runtime system and C interface
**Monitored by:** @gasche @alainfrisch

## Bug description

We recently encountered a segfault caused by a 32-bit gcc using -malign-double by default. This option means that all doubles are assumed aligned by gcc, a hypothesis that is typically false for doubles allocated in the OCaml heap.

We saw this problem with i686-w64-mingw32-gcc 6.4.0 under Windows (which activates the -malign-double option by default) with high enough optimisations ("-msse2 -O3").

For correctness it seems it would be best to pass -mno-align-double explicitly to all 32-bit gcc targets (or at the very least for the mingw targets).

## Steps to reproduce

(see attached daxpy.c and crash.ml)

$ ocamlc -ccopt -msse2 -ccopt -O3 -ccopt -malign-double -c daxpy.c
$ ocamlopt daxpy.o crash.ml
$ ./a.out
a=0xb7ce0f34
Segmentation fault (core dumped)
$ ocamlc -ccopt -msse2 -ccopt -O3 -mno-align-double -c daxpy.c
$ ocamlopt daxpy.o crash.ml
$ ./a.out
a=0xb7cbdf34
$

## File attachments

- [crash.ml](https://gist.githubusercontent.com/vicuna/2531b295e8e88da3bdc924b6acc5279b/raw/a716b7bb941c442af4f09dbe5a38f41a9e8e3c81/crash.ml)
- [daxpy.c](https://gist.githubusercontent.com/vicuna/2531b295e8e88da3bdc924b6acc5279b/raw/9ed793ffbe6b19e3e63c931c0f440ed3c865e3fb/daxpy.c)
- [daxpy.s.diff](https://gist.githubusercontent.com/vicuna/2531b295e8e88da3bdc924b6acc5279b/raw/4db0d551f754a87f17d3ee891283a350babd276c/daxpy.s.diff)

**Comment by vicuna** [comment]
**Comment author:** @nojb

Added file daxpy.s.diff showing the diff between the generated assembly with -malign-double and -mno-align-double. You can see there that "aligned" instructions movaps and movapd are replaced by "unaligned" instructions movups and movupd.

**Comment by vicuna** [comment]
**Comment author:** @nojb

Also, you can find out your default -malign-double gcc setting by inspecting

  gcc -Q --help=target

**Comment by vicuna** [comment]
**Comment author:** @xavierleroy

There is a configure-time test to try and see whether doubles need 8-alignment, see config/auto-aux/dblalign.c.  However it is easily fooled by clever compilers, hence the many exceptions in the configure script.

**Comment by stedolan** [comment]
This looks like a bug in the attached C stub, which directly casts an OCaml value to `double*`:
```c
      daxpy(Wosize_val(a), (double *)a);
```
Accessing floats from C should be instead done using the `Double_val` macro that the FFI provides, which expands to different code depending on whether `ARCH_ALIGN_DOUBLE` is set. (This setting is detected more reliably since #8532)

**Comment by nojb** [comment]
Thanks @stedolan for the explanation, sounds right!
