### ISSUE TITLE
When warning 60 is activated, a used module is reported as "unused"

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#7684]
**Original bug ID:** 7684
**Reporter:** Iguernlala
**Status:** acknowledged (set by @gasche on 2017-12-01T21:06:14Z)
**Resolution:** open
**Priority:** normal
**Severity:** minor
**Version:** 4.06.0
**Category:** misc
**Monitored by:** @nojb

## Bug description

This happens with mutually recursive modules as shown in the example below. Module X1 is used in module M, and module M is exported in the interface. But, if warning 60 is set, an "unused module X1" warning is triggered when compiling as follows:

$ ocamlc -c -w +60 foo.mli foo.ml

File "foo.ml", line 8, characters 0-43:
Warning 60: unused module X1.

(* content of foo.ml *)
module type S = sig
  type t
end

module rec M : S = struct
  type t = X1 of X1.t
end
and X1 : S = struct
  type t = M.t list
end

(* content of foo.mli *)
module type S = sig
  type t
end

module M : S

**Comment by vicuna** [comment]
**Comment author:** @gasche

Reproduced under 4.06.0.

**Comment by vicuna** [comment]
**Comment author:** Iguernlala

I forgot to say that trying to disable this warning with an annotation `[@@@ocaml.warning "-60"]` did not work

[Edited]
Actually, I manage to disable the warning if I put the annotation before 'module rec M ...'. (I had tried to put the annotation before 'and module X1 ...' previously)

**Comment by vicuna** [comment]
**Comment author:** @mshinwell

Here is another, probably related, example which I came across this week.

w60.ml
======

module type S = sig val f : unit -> unit end

module F (X : S) = struct let f () = X.f () end

module rec A : S =
  F (struct let f () = B.f () end)
and B : S =
  F (struct let f () = failwith "ok" end)

let f = A.f

let () = f ()

w60.mli
=======

val f : unit -> unit

Using a recent trunk:

$ ocamlc w60.mli
$ ocamlc -w +60 -o w60 w60.ml
File "w60.ml", line 7, characters 0-42:
Warning 60: unused module B.
$ ./w60
Fatal error: exception Failure("ok")

The warning is bogus, as evidenced by the exception, which shows that [B] was used.

The bogus warning does not appear if the .mli file is absent.

**Comment by vicuna** [comment]
**Comment author:** @mshinwell

As an aside: the following version produces a runtime exception:

  Fatal error: exception Undefined_recursive_module("w60.ml", 23, 2)

This surprised me at first, but it appears to be related to Mantis 2629.  It would indeed be nice if there were a compile-time check for this as suggested in that issue:

module type S = sig val f : unit -> unit end

module F (X : S) = struct let f = X.f end

module rec A : S =
  F (struct let f = B.f end)
and B : S =
  F (struct let f () = failwith "ok" end)

let f = A.f

let () = f ()

**Comment by jberdine** [comment]
Duplicate of #7522 ?

**Comment by lpw25** [comment]
This was fixed by #9393
