### ISSUE TITLE
record expression deleted when all fields specified

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#7696]
**Original bug ID:** 7696
**Reporter:** @yallop
**Status:** new
**Resolution:** open
**Priority:** normal
**Severity:** minor
**Category:** typing
**Related to:** #6608
**Monitored by:** @nojb @gasche

## Bug description

In 4.03.0 the record expression in an field update was always evaluated:

   # { (assert false) with contents = 1 } ;;
   Characters 0-36:
     { (assert false) with contents = 1 } ;;
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   Warning 23: all the fields are explicitly listed in this record:
   the 'with' clause is useless.
   Exception: Assert_failure ("//toplevel//", 1, 2).

In more recent versions (4.04.2, 4.05.0, 4.06.0) the record expression is removed if all the fields are specified:

   # { (assert false) with contents = 1 } ;;
   Characters 0-36:
     { (assert false) with contents = 1 } ;;
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   Warning 23: all the fields are explicitly listed in this record:
   the 'with' clause is useless.
   - : int ref = {contents = 1}

There's previous discussion on Mantis and GitHub:

   ocaml/ocaml#6608#c16416
   https://github.com/ocaml/ocaml/pull/901#issuecomment-259717609

**Comment by xavierleroy** [comment]
This was planned to be fixed by reverting  c545e04.  @garrigue can you please have a look?

**Comment by garrigue** [comment]
It was a bad ordering of commits.
