### ISSUE TITLE
Module inclusion check and constraint in type declarations

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#7703]
**Original bug ID:** 7703
**Reporter:** igarnier
**Assigned to:** @garrigue
**Status:** feedback (set by @garrigue on 2018-01-05T05:07:34Z)
**Resolution:** open
**Priority:** low
**Severity:** feature
**Platform:** x86_64
**OS:** Linux
**Version:** 4.06.0
**Category:** typing
**Monitored by:** @Drup @gasche

## Bug description

It seems that the subtyping relation induced by the following constraints is not taken into account in the module inclusion check process. The following example (courtesy of Gabriel Radanne) doesn't type check.

module M
: sig type +'a t = [< `A | `B ] as 'a end
= struct type +'a t = [< `A ] as 'a end

**Comment by vicuna** [comment]
**Comment author:** @garrigue

I'm not sure this would be sound.
And if it is in this precise case, I'm not sure what the condition is to make it sound in general.
This may be related to @gache's work on subtyping for GADTs.

**Comment by vicuna** [comment]
**Comment author:** @Drup

That was my initial reaction as well, but I was not able to find a counter example. @gasche, do you have one?

**Comment by vicuna** [comment]
**Comment author:** @gasche

I don't understand the type-checking of "constraints" very well. When are they applied?

When experimenting with this question, in general it looks safe because the constraint is substituted for the type. For example, if you write

module type Get = sig
  type +'a t = [< `A of int ] as 'a
  val get : 'a t -> int
end

then the inferred signature is actually

  val get : [< `A of int ] t -> int

(instead of a polymorphic ('a . 'a t -> int)) so there is no way to cause mischief by injecting a `B later.

On the other hand, the following would be unsound and must be rejected:

  module Test : sig
    type +'a t = [< `A of int | `B ] as 'a
    val get : 'a t -> int
  end
  = struct
    type +'a t = [< `A of int ] as 'a
    let get = function `A n -> n
  end

Checking the implementation of `get` against its specification must happen after the constraints have been substituted in the signature of get -- if this happens, then it should be rejected.

**Comment by Drup** [comment]
Without any feedback, I propose we keep rejecting such forms and close this.

**Comment by xavierleroy** [comment]
Closing as suggested.
