### ISSUE TITLE
mcomp on polymorphic variants is a little weak

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#7707]
**Original bug ID:** 7707
**Reporter:** @lpw25
**Status:** new
**Resolution:** open
**Priority:** normal
**Severity:** minor
**Version:** 4.06.0
**Category:** typing

## Bug description

The [mcomp] function doesn't really consider the row variable in polymorphic variants. For example, the following doesn't type check:

```
  # type ('a, 'b) eq = Refl : ('a, 'a) eq;;
  type ('a, 'b) eq = Refl : ('a, 'a) eq

  # let f : (< foo : 'a . [> `Foo] as 'a >, < foo : 'b . [> `Bar ] as 'b >) eq -> 'a = function _ -> .;;
  Characters 92-93:
    let f : (< foo : 'a . [> `Foo] as 'a >, < foo : 'b . [> `Bar ] as 'b >) eq -> 'a = function _ -> .;;
                                                                                              
  ^
  Error: This match case could not be refuted.
         Here is an example of a value that would reach it: Refl
```

because [mcomp] does not notice the incompatibility between:

```
  'a. [> `Foo] as 'a
```
and
```
  'b. [> `Bar] as 'b
```
This is of course safe, since it is conservative to assume that all types are compatible. Still it would be nice if it handled these types more accurately.

At the moment [mcomp] will only consider two polymorphic variants incompatible if one of them is closed and does not contain a tag from the other. This doesn't take account of cases where the row variable is a non-aliasable constructor or a universal variable. Ideally [mcomp] would construct the rows necessary to make the variants compatible and would then compare those rows with the actual rows for compatibility.

**Comment by garrigue** [comment]
How did you stumble into this example?
I agree that fixing it should not be difficult (basically, one can take the minimal instance of each polymorphic variant type, which amount to closing, and they should be compatible), but is the extra work justified.

**Comment by lpw25** [comment]
I don't really remember, but probably by reading the code and being surprised that it didn't try comparing the `row_more` parts of the types at all.
