### ISSUE TITLE
Deprecated annotation on let-binding does not trigger

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#7719]
**Original bug ID:** 7719
**Reporter:** authchir
**Status:** new
**Resolution:** open
**Priority:** normal
**Severity:** minor
**Platform:** amd64
**OS:** linux
**OS Version:** 4.4.0-43-Microso
**Version:** 4.06.0
**Category:** compiler driver
**Monitored by:** @nojb @gasche

## Bug description

As explored in this [Stackoverflow question][1], a let-binding annotated with a `deprecated` annotation does not trigger any warning. But the annotation on type definition and constructors does work.

[1] https://stackoverflow.com/q/48579580/823955

## Steps to reproduce

Given the following file `main.ml`:

    let foo = (fun x -> x) [@@deprecated]
    type t =
      | A [@deprecated]
      | B [@deprecated]
      [@@deprecated]

    let _ = foo 0
    let _ = A
    let f (x : t) = x

The compilation output two warnings, while three would be expected:

    $ ocamlc -w +3 main.ml
    File "main.ml", line 8, characters 8-9:
    Warning 3: deprecated: A
    File "main.ml", line 9, characters 11-12:
    Warning 3: deprecated: t

**Comment by vicuna** [comment]
**Comment author:** @nojb

Related PR: https://github.com/ocaml/ocaml/pull/1822

**Comment by Drup** [comment]
This bug is still present and relevant.

**Comment by gasche** [comment]
The people who have looked most at alerts and warnings, and might look at this, are @alainfrisch and @lpw25. i don't know if other contributors ( @antalsz, @nchataing, @Drup ) would be interested in looking at it.

**Comment by nchataing** [comment]
After some investigation, what comes clear is the fact that `let f = (fun x -> x) [@@deprecated]` puts the attribute on the `value binding` (see https://github.com/ocaml/ocaml/blob/trunk/typing/typedtree.ml#L296); however if we want the deprecated warning to fire, we need an attribute on the `pattern` inside the `value binding` (which would roughly correspond to `Tpat_var "f"` in this case).

The following code will hence emit the desired warning : `let f[@deprecated] = fun x -> x in f 0`.

**Comment by nchataing** [comment]
After some thinking, one possible fix would be to propagate the `deprecated` attributes of a value binding inside its pattern, but it seems overly complicated (and it would certainly make `typecore` and `typemod` more complicated to follow).

**Comment by alainfrisch** [comment]
In `let x,y = (1, 2) [@@deprecated]`, which of `x` or `y`should be marked as deprecated?  I guess, both, but this shows pushing the alert from the whole binding to individual variables is not very natural.

As @nchataing mentioned, there is a syntax which works, and I'm tempted to believe that marking some components as deprecated within an implementation is rare enough (I've only seen case of deprecation markers in module signatures), so I'm not sure something needs to be fixed.
