### ISSUE TITLE
caml_modify with int type parameter in GADT

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#7722]
**Original bug ID:** 7722
**Reporter:** smuenzel-js
**Status:** acknowledged (set by @xavierleroy on 2018-02-17T17:07:09Z)
**Resolution:** open
**Priority:** normal
**Severity:** minor
**Version:** 4.06.0
**Category:** back end (clambda to assembly)
**Monitored by:** @hhugo @gasche

## Bug description

When mutating a member of a record with an existential type, a caml_modify is generated even though it is know that the member can only hold immediate values.

```ocaml
module Kind = struct
  type _ t =
    | Int : int t
end

module R = struct
  type t =
    | T :
        { kind : 'a Kind.t
        ; mutable m : 'a
        } -> t
end

let mutate r (v : int) =
  let open R in
  let T ({ kind = Kind.Int; _} as r) = r in
  (* caml_modify is used here, even though r.m can only
     contain ints *)
  r.m <- v
```

**Comment by vicuna** [comment]
**Comment author:** @xavierleroy

The compiler errs on the side of caution: it generates a caml_modify operation unless it can positively prove that it's not needed.  With GADTs such proofs are delicate and very error prone.  So, maybe it's for the best that we're not trying to optimize this example.

**Comment by lpw25** [comment]
This is fixed on trunk
