### ISSUE TITLE
with type removes module aliases, which breaks soundness

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#7723]
**Original bug ID:** 7723
**Reporter:** @lpw25
**Assigned to:** @lpw25
**Status:** assigned (set by @garrigue on 2018-04-03T01:43:15Z)
**Resolution:** open
**Priority:** normal
**Severity:** minor
**Category:** typing
**Monitored by:** @Drup @gasche

## Bug description

[with type] will remove module aliases. This allows inconsistent module types to be made, which can then be realized through recursive modules and used to break soundness. I don't think this can cause segfaults, but it does, for example, allow us to prove that all [Set] types are equal if their element type is equal:

    type (_, _) eq = Refl : ('a, 'a) eq

    module Equal (M : Set.OrderedType) (N : Set.OrderedType with type t = M.t) : sig
      val eq : (Set.Make(M).t, Set.Make(N).t) eq
    end = struct
      type meq = Eq of (Set.Make(M).t, Set.Make(M).t) eq
      module type S = sig
        module N = M
        type neq = meq = Eq of (Set.Make(M).t, Set.Make(N).t) eq
      end
      module type T = S with type N.t = M.t with module N := N;;
      module rec T : T = T
      let eq =
        let T.Eq eq = Eq Refl in
        eq
    end

**Comment by vicuna** [comment]
**Comment author:** @lpw25

The solution here is that the module type expression:

   S with type N.t = M.t

in the above example should check that [N.t] does equal [M.t] and then return [S] unaltered -- leaving [N] as a module alias to [M].

**Comment by vicuna** [comment]
**Comment author:** @garrigue

As it seems that you know the solution, could you provide a patch (or is it already in progress)?

**Comment by vicuna** [comment]
**Comment author:** @lpw25

Sure. I'll have a look sometime next week.

**Comment by vicuna** [comment]
**Comment author:** @lpw25

PR: https://github.com/ocaml/ocaml/pull/1698

**Comment by yallop** [comment]
@lpw25: can this be closed now that #1698 is merged?

**Comment by lpw25** [comment]
Yeah, I think this is fine now.
