### ISSUE TITLE
Failure to report escaping type variable.

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#7741]
**Original bug ID:** 7741
**Reporter:** @Drup
**Status:** new
**Resolution:** open
**Priority:** normal
**Severity:** minor
**Category:** typing
**Related to:** #6744
**Monitored by:** @Drup @gasche

## Bug description

The attached file fails with 

   The implementation blurb.ml
       does not match the interface (inferred signature):
       Values do not match:
         val x : 'a bla t
       is not included in
         val x : 'a bla t

Regardless of how confusing that error message is, I'm pretty sure this code should fail with an error of the type "The universal variable 'a would escape its scope". 

I'm not sure you can break soudness like that, but it seems very sketchy.

Similar to ocaml/ocaml#6744

## File attachments

- [blurb.ml](https://gist.githubusercontent.com/vicuna/a20102e4996056b34c121034ae0fd16d/raw/a7378981a91b183e31f7b8b82f730e51eb78daa4/blurb.ml)

**Comment by vicuna** [comment]
**Comment author:** @lpw25

Here is a simplified version:
```ocaml
  type 'a s = S

  class type ['x] c = object
   method x : 'x list
  end

  let x : 'a c = object
     method x : 'b . 'b s list = [S]
   end
```

**Comment by vicuna** [comment]
**Comment author:** @lpw25

I think this comes from the following lines in `occur_univar`:
```ocaml
  List.iter2
    (fun t v ->
       if Variance.(mem May_pos v || mem May_neg v)
       then occur_rec bound t)
```
which originate from a commit labelled "allow for phantom univars".

So it would appear this bug is deliberate. However, I really think that those lines should be replaced by something that expands the alias in the null variance case rather than just letting the universal variable escape.

This is basically a variant on the issue being discussed in this GPR: https://github.com/ocaml/ocaml/pull/1588/

**Comment by lpw25** [comment]
Despite #9040 this issue still exists. Univars are allowed to escape their scope through "bivariant" type parameters in `Ctype.occur_univar` and `Ctype.univars_escape`. @garrigue would there be any problem with changing those functions to expand type constructors when a univar would otherwise escape? This is what normal `occur` does and it prevents us from allowing ill-formed types.

**Comment by garrigue** [comment]
I'm not sure I understand your analysis.
Concerning `occur_univar`, it seems that I forgot the injective case.
So I should check for any of `May_pos`, `May_neg` or `Inj`.
(This is is sufficient because abstract types cannot be invariant.)
