### ISSUE TITLE
dose3 needs more than 8GB of memory to compile with flambda

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#7746]
**Original bug ID:** 7746
**Reporter:** sommerville
**Status:** new
**Resolution:** open
**Priority:** normal
**Severity:** minor
**Platform:** AMD64
**OS:** Linux
**Version:** 4.06.1
**Category:** back end (clambda to assembly)

## Bug description

As the title suggests I've been unable to build dose3 using OCaml 4.06.1+flambda because every single time the OOM killer intervened and killed the process.
The same package builds just fine if I use OCaml 4.06.1 w/o flambda.

**Comment by ejgallego** [comment]
Dose3 seems to build OK on 4.07.1+flambda, there were indeed a few improvements on memory use in 4.07 so maybe this issue is resolved.

**Comment by lpw25** [comment]
Based on @ejgallego's report I'll close this as fixed.
