### ISSUE TITLE
Improving the --version directive

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#7748]
**Original bug ID:** 7748
**Reporter:** igo_weiqi_baduk
**Assigned to:** @dra27
**Status:** acknowledged (set by @dra27 on 2018-02-28T18:18:38Z)
**Resolution:** open
**Priority:** low
**Severity:** tweak
**OS:** Linux x86_64
**Version:** 4.06.1
**Category:** compiler driver
**Monitored by:** @gasche

## Bug description

Displaying the full name (with the variant +afl, +flambda...) of the active compiler would be great.

Great also to have the toplevel displaying this full version name (on its first line).

**Comment by vicuna** [comment]
**Comment author:** @dra27

Note https://github.com/ocaml/ocaml/pull/465 is aimed at solving this (this GPR was approved - subject to changes discussed in it) at a developer meeting last November, but I haven't had time to rebase it yet).

I'm not sure that we can alter the format of the version returned, because there are probing scripts which depend on its format.

Note that can you already determine a lot of this from the output of ocamlc -config.

**Comment by xavierleroy** [comment]
Re-classifying as a feature wish.  @dra27: is #465 stalled completely, or do you plan to resurrect it?

**Comment by dra27** [comment]
@xavierleroy - on opam stuff for the next few months, and hoping finally to revisit #465, yes!

**Comment by gasche** [comment]
This feature request would require a substantial amount of work (depending on how it is designed), and it appears that no one is interested in working on it for now. Closing; let us know if there is interest in working on it, we can always reopen.

**Comment by dra27** [comment]
I agree - I think your new `--config-var` (#1430) in 4.08 dealt with the scripting side of this. The recent change in opam-repository to use the `ocaml-option-` packages also makes this "probing" of features slightly less unclear.

For the toplevel, it might be tempting to having a `#config` - but the main variants are mostly uninteresting in the toplevel (flambda and afl aren't relevant and no-naked-pointers, no-flat-float-array affect C the runtime, so it's not clear what displaying that in every toplevel adds)
