### ISSUE TITLE
line number/file_name changing directive sometimes does not have the desired effect

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#7755]
**Original bug ID:** 7755
**Reporter:** kosik
**Status:** acknowledged (set by @xavierleroy on 2018-05-21T17:00:20Z)
**Resolution:** open
**Priority:** low
**Severity:** minor
**Version:** 4.06.1
**Category:** lexing and parsing
**Monitored by:** @nojb @gasche

## Bug description

See "Steps To Reproduce".

## Steps to reproduce

After executing the following comments:

  ocamlc -g -o main main.ml
  OCAMLRUNPARAM=b ./main

I see:

  Fatal error: exception Main.E
  Raised at file "generated.ml", line 4002, characters 4-47
  Called from file "generated.ml", line 13002, characters 0-6

I was expecting to see:

  Raised at file "original.mly", line 8, characters 13-14

## Additional information

When I delete the following line from the attached "mail.ml" file:

  let _1 = () in

then "ocamlc" behaves in the expected way. I.e. I see:

  Fatal error: exception Main.E
  Raised at file "original.mly", line 8, characters 13-14
  Called from file "generated.ml", line 13002, characters 0-6

## File attachments

- [main.ml](https://gist.githubusercontent.com/vicuna/e15a2b73682efd730cef81735cec53b7/raw/e8cf910867665ea8a276d936480812efb7f72508/main.ml)

**Comment by vicuna** [comment]
**Comment author:** @xavierleroy

I can reproduce the problem with 4.06 but not with the current trunk.  There was some changes recently in the way # line directives are handled, but I'm surprised they make a difference here.

**Comment by xavierleroy** [comment]
The location is correct in 4.07 and in 4.08.  The problem seems to have been fixed by the lexer changes post 4.06.
