### ISSUE TITLE
Ctrl-c in interpreter OCaml crash mintty.exe

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#7759]
**Original bug ID:** 7759
**Reporter:** sampo
**Status:** new
**Resolution:** open
**Priority:** normal
**Severity:** minor
**Version:** 4.06.0
**Category:** runtime system and C interface

## Bug description

Mintty.exe crash after Ctrl-c in the interpreter.

## Steps to reproduce

Start Mintty.exe, start OCaml, type Ctrl-c for interrupted on the keyboard.

## Additional information

Description :
  Un problème a provoqué l’arrêt de l’interaction de ce programme 

avec Windows.

Signature du problème :
  Nom d’événement de problème:	AppHangXProcB1
  Nom de l'application:	mintty.exe
  Version de l'application:	2.7.9.0
  Horodatage de l’application:	ff878787
  Signature de blocage:	5c4d
  Type de blocage:	16
  Attente du nom de l’application:	bash.exe
  Attente de la version de l’application:	0.0.0.0
  Version du système:	6.0.6002.2.2.0.768.3
  Identificateur de paramètres régionaux:	1036
  Signature de blocage supplém. 1:	

abda2f538763f6895fb7c77f5b3b6add
  Signature de blocage supplém. 2:	5644
  Signature de blocage supplém. 3:	

aec4725ded8b1e0e9ef6b705bd3ded96
  Signature de blocage supplém. 4:	5c4d
  Signature de blocage supplém. 5:	

abda2f538763f6895fb7c77f5b3b6add
  Signature de blocage supplém. 6:	5644
  Signature de blocage supplém. 7:	

aec4725ded8b1e0e9ef6b705bd3ded96

**Comment by nojb** [comment]
I don't think this is an OCaml problem, but rather an issue with the interaction of Cygwin with native Console apps (which has improved since then).
