### ISSUE TITLE
Invalid [@@deprecated] attributes are ignored

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#7780]
**Original bug ID:** 7780
**Reporter:** @diml
**Status:** new
**Resolution:** open
**Priority:** normal
**Severity:** minor
**Category:** lexing and parsing
**Monitored by:** @nojb @gasche @hcarty

## Bug description

For instance if one writes [@deprecated ...] instead of [@@deprecated ...], nothing will happen and the attribute will just be ignored. This is an easy to make error, so the compiler should catch it.

**Comment by ghost** [comment]
I don't plan to work on this anytime soon, and in practice I have not been bitten by this problem much. If something thinks this problem is a serious one, please re-open an issue.
