### ISSUE TITLE
Typos in Format's documentation

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#7785]
**Original bug ID:** 7785
**Reporter:** ArthurMilchior
**Status:** new
**Resolution:** open
**Priority:** normal
**Severity:** trivial
**Category:** documentation

## Bug description

In the page https://caml.inria.fr/pub/docs/manual-ocaml/libref/Format.html
For the sake of consistency, the second argument of pp_open_tag should be tag and not string.

Function pp_set_formatter_out_channel belongs to the section
«Redirecting the standard formatter output». It appears before it, by error I presume

**Comment by Anukriti12** [comment]
This has already been resolved with this commit
https://github.com/ocaml/ocaml/commit/bbadeee53da38c157fb6b78492a85d282f48e810#diff-ecd205ea92ba9c2fdfd17d570a7ef7b0

**Comment by gasche** [comment]
Thanks for your detective work! Let's close the issue then.
