### ISSUE TITLE
Format: More refined check to evaluate whether a box shall lead to go beyond max_indent and need a break prior to opening?

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#7807]
**Original bug ID:** 7807
**Reporter:** herbelin
**Status:** new
**Resolution:** open
**Priority:** normal
**Severity:** feature
**Version:** 4.06.1
**Category:** standard library
**Related to:** #7862
**Monitored by:** ralfj @gasche @Yakobowski

## Bug description

This is a followup of a discussion at issue 7804 showing the example of a box which would fit on the line but which however forces a break just because it is opened beyond the max_indent limit.

Assuming that the specification of max_indent is strictly to not indent beyond the max_indent value, the test made at box opening to force a break if the box is opened beyong max_indent seems overly preventive. Opening a box does not mean that printing the contents of the box shall necessarily need to break a line and indent.

In particular, in a situation such as described in https://github.com/coq/coq/issues/7731, where a box is opened beyond the max_indent limit but this box is within a surrounding box and a previous break in the surrounding box has already checked that the forthcoming comments shall fit, the box may (??) trust the decision take by the previous break and not test max_indent. Would it make sense to refine the algorithm in this way? Otherwise said, looking at the implementation of `Format.format_pp_token`, is the "size" computed in the `Pp_break` clause correct enough to ensure that, if it fits, forthcoming boxes shall fit and shall not have to preventively test whether they are beyond the max_indent limit.

## Steps to reproduce

See #7804 for a simplified example, or https://github.com/coq/coq/issues/7731 for a realistic example.

**Comment by jhwoodyatt** [comment]
I encountered this problem trying to figure out why the forthcoming support in [Orsetto](https://bitbucket.org/jhw/orsetto) for the [CBOR diagnostic notation](https://tools.ietf.org/html/rfc8949#section-8) was producing poorly indented object and array elements when I was using any kind of "horizontal or vertical" box mode instead of `pp_open_vbox`. It doesn't take a very complicated object to produce box openings that would not need a line break to fit but which nevertheless get a line break anyway, which then get rejected to the left and it produces a very jagged and unreadable diagnostic notation of the object.

**Comment by gasche** [comment]
Very few people are interested in working on the Format codebase today. Your problem sounds real (just as the initial report), but it is not likely to get fixed if you don't submit a patch/pull request yourself. In the meantime I will reopen the bug report to get this issue more visibility -- but if it gets closed again for inactivity, I won't fight for it.

**Comment by jhwoodyatt** [comment]
Before I investigate, how exhaustive is the test suite for the `Format` module? The change I think we want here seems like it might not be hard to write. Hard to test and validate is my concern. If the test suite is minimal, then I think I'd almost rather write my own full replacement for `Format` than try to shepherd a change to the standard one through the integration and release process.

**Comment by gasche** [comment]
Basic functionality is tested in `testsuite/tests/lib-format`, but there is no comprehensive test for line-breaking behavior.

> I'd almost rather write my own full replacement for `Format`

There are also existing alternatives to Format that you may want to evaluate for your needs first, notably [PPrint](https://github.com/fpottier/pprint). Note however that one reason why people keep using Format is that its `Format.formatter` datatype is used as a flexible-output format by many libraries, making it hard to escape in many use-cases.
