### ISSUE TITLE
Small inconsistency with relaxed value restriction, polymorphic variants and signature inclusion check

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#7817]
**Original bug ID:** 7817
**Reporter:** mandrykin
**Status:** new
**Resolution:** open
**Priority:** low
**Severity:** tweak
**Platform:** x86_64 Linux 4.4.0
**OS:** Ubuntu
**OS Version:** 16.04.4 LTS
**Version:** 4.06.1
**Category:** typing
**Monitored by:** @nojb @yallop

## Bug description

For this example:
```
let f = let _ = ref 0 in function `A | `B -> ();;
```
Normally, the inferred type is
```
_[< `A | `B ] -> unit
```
i.e. with a weak type variable as the relaxed value restriction works only for strictly covariant positions. However,
```
include (struct
  let f = let _ = ref 0 in function `A | `B -> ()
end : sig
  val f : [< `A | `B] -> unit
end);;
```
gives
```
[< `A | `B ] -> unit
```
(polymorphic type). As far as I understand this interferes with principality as
```
let f1 = let r = ref 0 in fun x -> x;;
```
Can be given the type
```
'_weak1 -> '_weak1 (* e.g. int -> int *)
```
but also
```
include (struct
  let f2 = let r = ref 0 in fun (x : [< `A | `B]) -> x 
end : sig
  val f2 : ([<`A | `B] as 'a) -> 'a
end);;
```
which has type
```
([< `A | `B ] as 'a) -> 'a
```
and neither of the types is more general. The behavior occurs with upper bounded polymorphic variants (`[< `]) arbitrarily nested into other types in covariant positions both in usual and -principal modes. I'm actually currently writing some code, where this behavior turned out to be beneficial allowing the polymorphic types where they were actually needed without resorting to explicitly polymorphic record fields/object methods. But the question is whether this is reliable and if someone is going to eventually notice and change this or this can be admitted as a feature.

**Comment by vicuna** [comment]
**Comment author:** mandrykin

Just as an example where this can matter. If I use a (covariant) phantom type parameter for encoding mutability/immutability the following way:
 -- [`imm] means the value cannot be mutated, but can be stored in data structures shared across functions and modules
 -- [`mut] means the value can be mutated, but cannot be stored in data structures
 -- [`imm | `mut] means the value can neither be mutated nor stored in data structures
Some functions may accept [`imm | `mut] parameters, which exposes that they neither modify, nor store them and can accept [`imm], [`mut] and [`imm | `mut] values. So it's convenient for such functions to be polymorphic in the mutability parameter and they often involve types e.g. [< `imm | `mut] t. But some of those functions can use local caches or temporary mutable values that are allocated once per function and not once every call for reasons of efficiency. That's where the value restriction becomes important.

**Comment by lpw25** [comment]
As opposed to being stale, or even a principality issue, this is a soundness bug:
```
        OCaml version 4.10.0

# let r = ref None
  module M : sig
    val write : ([< `A of string | `B of int ] -> unit)
  end = struct
      let write x =
        match x with `A _ | `B _ -> r := Some x
  end;;
            val r : _[< `A of string | `B of int ] option ref = {contents = None}
module M : sig val write : [< `A of string | `B of int ] -> unit end
# let read () =
    match !r with
    | None -> "Hello"
    | Some (`A s) -> s;;
      val read : unit -> string = <fun>
# let () = M.write (`B 0)
  let () = print_string (read ());;
  
Process OCaml segmentation fault (core dumped)
```

**Comment by lpw25** [comment]
@garrigue to make sure he sees this.

**Comment by xavierleroy** [comment]
Could this issue be assigned to someone, please?
