### ISSUE TITLE
Problem with constraints, with type, and polymorphic variants

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#7834]
**Original bug ID:** 7834
**Reporter:** @lpw25
**Status:** new
**Resolution:** open
**Priority:** normal
**Severity:** minor
**Category:** typing
**Monitored by:** smuenzel-js @gasche

## Bug description

The following code seems pretty reasonable:
```ocaml
  module type Q = sig
    type 'a t constraint 'a = [< `Empty | `Filled of _ ]
    module type S = sig 
      type 'a t constraint 'a = [< `Empty | `Filled of _ ] 
    end
    module M : S with type 'a t = 'a t
  end;;
```
but fails with the following error:
```
  Error: In this `with' constraint, the new definition of t
  does not match its original definition in the constrained signature:
  Type declarations do not match:                                                                                 
       type 'a t = 'a t constraint 'a = [< `Empty | `Filled of 'b & 'c & 'd ]
     is not included in
       type 'a t constraint 'a = [< `Empty | `Filled of 'b ]
     Their constraints differ.
```

I haven't dug into this issue properly, but I can see basically how it happens. I'm not really sure there is much we can do to fix it, I suspect it would require comparing the different `&`ed types, and that has been ruled out as a too much of a PITA before. Still I figured it was worth reporting anyway.

**Comment by lpw25** [comment]
I think this bug should at least be looked at. @garrigue do you think this can be fixed without major surgery?

**Comment by garrigue** [comment]
Have to think about it. Here it seems that doing some kind of garbage collection, discarding variables that appear only once, would solve the problem, but this is hardly a general solution.

In general, this amounts to solving the equivalence of two constraints, which is hard. The next version should support that...
