### ISSUE TITLE
Shadowing standard library modules doesn't work in the toplevel

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#7841]
**Original bug ID:** 7841
**Reporter:** @dra27
**Assigned to:** @diml
**Status:** assigned (set by @dra27 on 2018-08-22T14:35:19Z)
**Resolution:** open
**Priority:** high
**Severity:** minor
**Platform:** any
**OS:** n/a
**OS Version:** n/a
**Version:** 4.07.0
**Target version:** 4.08.0+dev/beta1/beta2
**Category:** toplevel
**Monitored by:** @nojb

## Bug description

Shadowing standard library modules doesn't work in the toplevel, in particular the new Result module merged in 4.08 shadows the opam result package's Result module.

## Steps to reproduce

- Build and compile ocaml-trunk and the https://github.com/janestreet/result
 - Launch the toplevel
 - #directory "/path/to/result.cma";;
 - #load "result.cma";;
 - #show_module Result;;

The result should be a module with a single type, but the standard library's Result module will be shown instead.

## Additional information

See comments at the end of #1956 (https://github.com/ocaml/ocaml/pull/1956#issuecomment-414989280)

**Comment by vicuna** [comment]
**Comment author:** @xavierleroy

EDIT: I posted a wrong comment before, please ignore.

**Comment by vicuna** [comment]
**Comment author:** @diml

This is fixed by this PR: https://github.com/ocaml/ocaml/pull/2041

**Comment by dbuenzli** [comment]
This issue can be closed.

**Comment by nojb** [comment]
Thanks!
