### ISSUE TITLE
imenu crash when in_ appears in variable name

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#7850]
**Original bug ID:** 7850
**Reporter:** wyuenho
**Status:** new
**Resolution:** open
**Priority:** normal
**Severity:** minor
**Category:** emacs mode

## Bug description

Discovered when trying out the PR for #7844.

Given this code:

```ocaml
module rec Foo : FOO = struct
  and in_hello =
    let b in
    in_hello (* error *)
```

This backtrace is given:

```
Debugger entered--Lisp error: (wrong-type-argument integer-or-marker-p nil)
  buffer-substring-no-properties(nil nil)
  caml-match-string(5)
  tuareg-imenu-create-index()
  imenu--make-index-alist()
  imenu-list-rescan-imenu()
  imenu-list-collect-entries()
  imenu-list-update()
  purpose-x-code1-update-changed()
  #f(compiled-function () #<bytecode 0x45089141>)()
  apply(#f(compiled-function () #<bytecode 0x45089141>) nil)
  timer-event-handler([t 0 1 0 nil #f(compiled-function () #<bytecode 0x45089141>) nil idle 0])
```

**Comment by vicuna** [comment]
**Comment author:** wilfred

See pull request: https://github.com/ocaml/ocaml/pull/2078

**Comment by vicuna** [comment]
**Comment author:** wilfred

This can now be closed, as the PR has been merged.

**Comment by xavierleroy** [comment]
Closing as suggested by the original poster.
