### ISSUE TITLE
Imprecise error location when a submodule does not implement its signature

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#7859]
**Original bug ID:** 7859
**Reporter:** @samoht
**Status:** new
**Resolution:** open
**Priority:** normal
**Severity:** minor
**Version:** 4.07.1
**Category:** typing
**Monitored by:** @nojb

## Bug description

The location (and the message) for type errors regarding module not implementing a required signature is sometimes not very helpful. For instance when the signature is defined in an other module, the error message points to that other module instead of the implementation:

```sh
$ cat foo.mli
val x: int

module X: Map.OrderedType
$ cat foo.ml
let x = 2

module X = struct end
$ ocamlc -c foo.mli foo.ml
File "foo.ml", line 1:
Error: The implementation foo.ml does not match the interface foo.cmi:
       In module X:
       Modules do not match: sig  end is not included in Map.OrderedType
       In module X:
       The value `compare' is required but not provided
       File "map.mli", line 51, characters 4-31: Expected declaration
       In module X:
       The type `t' is required but not provided
       File "map.mli", line 48, characters 4-10: Expected declaration
```

The error message refers to `map.mli` which is not helpful here. No error message points me to the actual module X in the file foo.ml which needs to be corrected.

**Comment by vicuna** [comment]
**Comment author:** @samoht

(I have assigned the wrong Category to that issue but it seems that I cannot edit it... sorry about this)

**Comment by vicuna** [comment]
**Comment author:** @alainfrisch

(Moved to the "typing" category.)

**Comment by trefis** [comment]
I think (though I'm not sure) that this would have been fixed by #1737 , which unfortunately was reverted in #2092 because of issue #7852 .

I'm planning to have another stab at that issue very soon.

**Comment by Drup** [comment]
@trefis What's the status of resubmitting #1737 ?

**Comment by trefis** [comment]
See https://github.com/ocaml/ocaml/issues/7852#issuecomment-625085099

**Comment by gasche** [comment]
I'm not sure what the status of this issue here; @trefis ?

**Comment by trefis** [comment]
#10405

**Comment by Octachron** [comment]
In this case, #10405 does not change the error message, mostly because it is already pointing to the module `X`:
>```
>       In module X:
>       Modules do not match: sig  end is not included in Map.OrderedType
>       In module X:
>```
I would propose to highlight the module context (here `X`) and add some indentation, which should be fine once we limit the number of pair (context,module type) which is printed in the same error message.
