### ISSUE TITLE
missing documentation for OCAMLRUNPARAM

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#7870]
**Original bug ID:** 7870
**Reporter:** @damiendoligez
**Assigned to:** @damiendoligez
**Status:** assigned (set by @damiendoligez on 2018-11-05T14:49:28Z)
**Resolution:** open
**Priority:** normal
**Severity:** minor
**Version:** 4.08.0+dev/beta1/beta2
**Category:** documentation
**Monitored by:** @nojb

## Bug description

The following letters are used for parameters in OCAMLRUNPARAM but not documented in ocamlrun.m:
c, H, t, w, W

The following are not documented in runtime.etex:
H, t, w, W

**Comment by Anukriti12** [comment]
Hi, I am an outreachy applicant. Can i work on this issue? I've worked on a simmilar issue (#8697) before. Only c parameter is still left to do from my PR at that issue. Should I create another PR or commit to that only?

**Comment by gasche** [comment]
This is a duplicate of #8697 which has better discussion, so closing here.
