### ISSUE TITLE
Replace TypedtreeIter by Tast_iterator

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#7878]
**Original bug ID:** 7878
**Reporter:** @trefis
**Status:** acknowledged (set by @gasche on 2019-02-20T15:37:21Z)
**Resolution:** open
**Priority:** low
**Severity:** minor
**Category:** misc
**Tags:** junior_job
**Monitored by:** @nojb

## Bug description

And make it consistent with Ast_iterator.

Cf. https://github.com/ocaml/ocaml/pull/2173

**Comment by xenia-foxtrot** [comment]
Hi!

I'd like to pickup this issue for the outreachy internship. Any advice or recommendations anyone would like to share?

**Comment by xenia-foxtrot** [comment]
I guess I should ask @gasche for assistance, right?

I'm obviously rather new to OCaml, but I have worked with ASTs before. Do you think that this is something that can be done within the current timeframe? Or should I consider another issue?

**Comment by trefis** [comment]
I don't know what the timeframe is, but this seems doable in a short period of time.
Basically what you want to do is this:
- create `typing/tast_iterator.ml[i]`, that is related to `typing/tast_mapper.ml[i]` in the same way `parsing/ast_iterator.ml[i]` is related to `parsing/ast_mapper.ml[i]`.
(I suggest you diff `parsing/ast_mapper.mli` with `parsing/ast_iterator.mli` and `typing/tast_mapper.mli`)
- `git rm typing/typedtreeIter.ml typing/typedtreeIter.mli`
- replace the uses (I think there's only one) of `TypedtreeIter` that don't compile anymore, with uses of your new `Tast_iterator`
