### ISSUE TITLE
how to upgrade to the latest ocaml

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#7885]
**Original bug ID:** 7885
**Reporter:** julia
**Status:** new
**Resolution:** open
**Priority:** normal
**Severity:** minor
**Category:** documentation
**Monitored by:** @nojb

## Bug description

The information about how to install OCaml with opam on the OCaml web page is now more helpful.  It would also be helpful to give an example of how to upgrade to the latest version.  This should make it clear how OCaml versions are named.

**Comment by vicuna** [comment]
**Comment author:** @diml

Hi, what web page are you referring to? For ocaml.org, you should report issues on this github project: https://github.com/ocaml/ocaml.org. caml.inria.fr/mantis is for issues about the core OCaml system, not opam.

Regarding the opam question, I believe the answer is:

$ opam upgrade --unlock-base

**Comment by ghost** [comment]
It looks like this issue can be closed. Please re-open if you think otherwise.
