### ISSUE TITLE
Incorrect floating point optimizations with ocamlopt

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#7890]
**Original bug ID:** 7890
**Reporter:** sfuric
**Status:** new
**Resolution:** open
**Priority:** normal
**Severity:** major
**Version:** 4.07.0
**Category:** back end (clambda to assembly)
**Related to:** #3526
**Monitored by:** @nojb @shindere @gasche @Yakobowski

## Bug description

ocamlopt incorrectly assumes that multiple occurrences of the same floating point expressions necessarily reduce to the same value. This is not always the case since rounding mode can be changed by programs.

## Steps to reproduce

Compile files in attached archive with:
ocamlopt -c roundingMode_stubs.c
ocamlopt -c roundingMode.mli
ocamlopt -c roundingMode.ml
ocamlopt roundingMode.cmx roundingMode_stubs.o testRounding.ml -o not_correct
ocamlopt roundingMode.cmx roundingMode_stubs.o testRounding_modified.ml -o correct

Executing ./not_correct or ./correct should give the same result (they do with ocamlc).

## File attachments

- [rounding.tgz](https://gist.githubusercontent.com/vicuna/1891c03867e4f87161e27e880f8df5d6/raw/69d3c8b3a7882b164b886124f976e85ce258a2af/rounding.tgz)

**Comment by vicuna** [comment]
**Comment author:** @lpw25

I could be wrong, but I thought that was what the compiler's -no-float-const-prop option was for. So I don't think this is a bug, but the expected behaviour.

**Comment by vicuna** [comment]
**Comment author:** sfuric

I wasn't aware of this option (there are so many of them).
But I would certainly have preferred the opposite default behavior, i.e. no floating point "optimizations" by default, because it breaks functional abstraction (my example precisely shows that by factorizing out common operations the behavior of the program is changed), and it also breaks compatibility with ocamlc.
Why not having a -float-const-prop option instead, I mean require users to explicitly ask for constant propagation (knowing that it may change the semantics)?

**Comment by xavierleroy** [comment]
Currently, OCaml is very consistent w.r.t. this rounding mode business: the standard library provides no way to change the rounding mode, and the optimizer assumes the rounding mode is not changed (unless `-no-float-const-prop` is given).  

If you use external libraries that change the rounding mode, it is your responsibility, or the library's responsibility, to set `-no-float-const-prop`.

This behavior was discussed and agreed on with the members of the Caml Consortium, some of which have a need to change the FP rounding mode but are happy with `-no-float-const-prop`.  We will repsect this decision.
