### ISSUE TITLE
[IEEE 754] OCaml does not enable rounding direction to be specified by programs

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#7896]
**Original bug ID:** 7896
**Reporter:** sfuric
**Status:** new
**Resolution:** open
**Priority:** normal
**Severity:** minor
**Version:** 4.07.0
**Category:** language features
**Has duplicate:** #3526
**Monitored by:** @gasche

## Bug description

Some floating-point computations require rounding direction to be specified (typically to obtain safe bounds). However OCaml does not support directly this feature, so external functions have to be written (see attached code).

## Steps to reproduce

Compile files in archive with:
ocamlc -c roundingMode_stubs.c
ocamlc -c roundingMode.mli
ocamlc -c roundingMode.ml
ocamlc -custom roundingMode.cmo roundingMode_stubs.o testRounding.ml

Run:
./a.out

## File attachments

- [rounding.tgz](https://gist.githubusercontent.com/vicuna/a589fd8741b3654f1ab1a128deafbcae/raw/be3797205d1585ed8ca3dcef6ffe4de175c2d346/rounding.tgz)

**Comment by vicuna** [comment]
**Comment author:** @nojb

I'm not an expert on IEEE754, but it sounds like a potentially useful addition. Would you like to open a PR on https://github.com/ocaml/ocaml to discuss your code?

**Comment by xavierleroy** [comment]
FP rounding mode is another piece of global state, and I don't feel like exposing this to casual users.  I'd rather leave that to a specialized, external library.  Even better would be a more functional API that hides the global state.  Again such an API could be developed first as an external library.

**Comment by Chris00** [comment]
In case this is of interest, the [Interval](https://github.com/Chris00/ocaml-interval) library does this (internally).

**Comment by xavierleroy** [comment]
Yes, interval arithmetic is a great example of a nice, high-level, declarative API that changes rounding mode internally in the implementation.

Actually I wonder whether there are any other common use of non-default rounding modes beyond interval arithmetic.
