### ISSUE TITLE
compilation takes forever to compile 30 lines

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#7899]
**Original bug ID:** 7899
**Reporter:** @rixed
**Status:** new
**Resolution:** open
**Priority:** normal
**Severity:** minor
**Version:** 4.07.1
**Category:** back end (clambda to assembly)
**Monitored by:** @nojb @gasche

## Bug description

Using ocaml 4.07.1 (or 4.07.0, FWIW), a simple and boring (generated) function takes forever to compile.

This function is made of a succession of:
  let i = if some_cond then i + 1 else i in
  let i = ... etc ...

Notice that if the expression is turned into:
  let i = i + (if some_cond then 1 else 0) in
then it works.

## Steps to reproduce

$ cat > t.ml
let f a =
  let i0 = 0 in
  let i1 = if a.(0) = None then i0 + 1 else i0 in
  let i2 = if a.(1) = None then i1 + 1 else i1 in
  let i3 = if a.(2) = None then i2 + 1 else i2 in
  let i4 = if a.(3) = None then i3 + 1 else i3 in
  let i5 = if a.(4) = None then i4 + 1 else i4 in
  let i6 = if a.(5) = None then i5 + 1 else i5 in
  let i7 = if a.(6) = None then i6 + 1 else i6 in
  let i8 = if a.(7) = None then i7 + 1 else i7 in
  let i9 = if a.(8) = None then i8 + 1 else i8 in
  let i10 = if a.(9) = None then i9 + 1 else i9 in
  let i11 = if a.(10) = None then i10 + 1 else i10 in
  let i12 = if a.(11) = None then i11 + 1 else i11 in
  let i13 = if a.(12) = None then i12 + 1 else i12 in
  let i14 = if a.(13) = None then i13 + 1 else i13 in
  let i15 = if a.(14) = None then i14 + 1 else i14 in
  let i16 = if a.(15) = None then i15 + 1 else i15 in
  let i17 = if a.(16) = None then i16 + 1 else i16 in
  let i18 = if a.(17) = None then i17 + 1 else i17 in
  let i19 = if a.(18) = None then i18 + 1 else i18 in
  let i20 = if a.(19) = None then i19 + 1 else i19 in
  let i21 = if a.(20) = None then i20 + 1 else i20 in
  let i22 = if a.(21) = None then i21 + 1 else i21 in
  let i23 = if a.(22) = None then i22 + 1 else i22 in
  let i24 = if a.(23) = None then i23 + 1 else i23 in
  let i25 = if a.(24) = None then i24 + 1 else i24 in
  let i26 = if a.(25) = None then i25 + 1 else i25 in
  let i27 = if a.(26) = None then i26 + 1 else i26 in
  i27
$ ocamlopt.opt -c t.ml

Actually, each additional line approximately double the time.
ocamlopt.opt -dcmm do promptly print the cmm, then hangs.

**Comment by vicuna** [comment]
**Comment author:** @rixed

The option -linscan makes it work.

**Comment by vicuna** [comment]
**Comment author:** vlaviron

There's an exponential explosion in Coloring.iter_preferred. I don't know how to fix it, but it looks like it explores all paths of the preferred relation graph, of which there are a number exponential in the code size in this example.

**Comment by xavierleroy** [comment]
Possibly related to #9392 ?

**Comment by stedolan** [comment]
This was in fact fixed by #9392
