### ISSUE TITLE
Tail call not handled properly depending on the number of arguments (with ocamlopt)

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#7900]
**Original bug ID:** 7900
**Reporter:** Vincent Cheval
**Status:** acknowledged (set by @nojb on 2019-01-24T09:41:11Z)
**Resolution:** open
**Priority:** normal
**Severity:** major
**Platform:** Mac OS X and Unix
**OS:** MacOs 10.14 and Unbuntu
**Version:** 4.07.1
**Category:** back end (clambda to assembly)
**Monitored by:** @nojb @glondu

## Bug description

Hello,

I noticed that when we define mutual recursive functions that are tail recursive, the number of arguments  impacts  whether or not ocamlopt actually optimize the functions. More specifically, as soon as there is more than 10 arguments (strictly) then the calls are not optimized anymore. Is it an expected behavior ? If so, would it be possible that the flag [@tailcall] detects this or at least to include the expected behavior in the documentation ? Because all my examples (even the one not working do not raise any flags). 

Note that when the function is not mutual recursive, the number of argument does not seem to be problematic.

Note also that if the mutual recursive functions have less then 10 arguments but another function is defined inside them then the problem also arises.

Best,
Vincent Cheval

## Steps to reproduce

I put below different cases that I tried to determine the behavior of ocamlopt.

(* This function is tail recursive and behaves accordingly with ocamlopt *)
let rec test1 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 x13 x14 x15 =
  let stack = Gc.stat () in
  Printf.printf "test1 (%d)\n%!" stack.Gc.stack_size;
  (test1[@tailcall]) (x1+1) (x2+1) (x3+1) (x4+1) (x5+1) (x6+1) (x7+1) (x8+1) (x9+1) (x10+1) (x11+1) (x12+1) (x13+1) (x14+1) (x15+1)

let _ = test1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1

(* These functions are tail recursive and behaves accordingly with ocamlopt *)
let rec test1 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 =
  let stack = Gc.stat () in
  Printf.printf "test1 (%d)\n%!" stack.Gc.stack_size;
  (test2[@tailcall]) (x1+1) (x2+1) (x3+1) (x4+1) (x5+1) (x6+1) (x7+1) (x8+1) (x9+1) (x10+1)

and test2 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 =
  let stack = Gc.stat () in
  Printf.printf "test2 (%d)\n%!" stack.Gc.stack_size;
  (test1[@tailcall]) (x1+1) (x2+1) (x3+1) (x4+1) (x5+1) (x6+1) (x7+1) (x8+1) (x9+1) (x10+1)

let _ = test1 1 1 1 1 1 1 1 1 1 1

(* These functions are tail recursive but do not behave accordingly with ocamlopt *)
let rec test1 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 =
  let stack = Gc.stat () in
  Printf.printf "test1 (%d)\n%!" stack.Gc.stack_size;
  (test2[@tailcall]) (x1+1) (x2+1) (x3+1) (x4+1) (x5+1) (x6+1) (x7+1) (x8+1) (x9+1) (x10+1)

and test2 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 =
  let stack = Gc.stat () in
  Printf.printf "test2 (%d)\n%!" stack.Gc.stack_size;
  (test1[@tailcall]) (x1+1) (x2+1) (x3+1) (x4+1) (x5+1) (x6+1) (x7+1) (x8+1) (x9+1) (x10+1) (x10+1)

let _ = test1 1 1 1 1 1 1 1 1 1 1 1

(* These functions are tail recursive but do not behave accordingly with ocamlopt *)
let rec test1 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 =
  let stack = Gc.stat () in
  Printf.printf "test1 (%d)\n%!" stack.Gc.stack_size;
  (test2[@tailcall]) x1

and test2 x1 =
  let stack = Gc.stat () in
  Printf.printf "test2 (%d)\n%!" stack.Gc.stack_size;
  (test1[@tailcall]) (x1+1) (x1+1) (x1+1) (x1+1) (x1+1) (x1+1) (x1+1) (x1+1) (x1+1) (x1+1) (x1+1)

let _ = test1 1 1 1 1 1 1 1 1 1 1 1

(* These functions are tail recursive but do not behave accordingly with ocamlopt *)
let rec test1 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 =
  let stack = Gc.stat () in
  Printf.printf "test1 (%d)\n%!" stack.Gc.stack_size;
  let sub_test1 z =
    (test2[@tailcall]) (x1+x2+x3+x4+x5+x6+x7+x8+x9+x10+z)
  in
  (sub_test1[@tailcall]) (x1+1)

and test2 x1 =
  let stack = Gc.stat () in
  Printf.printf "test2 (%d)\n%!" stack.Gc.stack_size;
  (test1[@tailcall]) (x1+1) (x1+1) (x1+1) (x1+1) (x1+1) (x1+1) (x1+1) (x1+1) (x1+1) (x1+1)

let _ = test1 1 1 1 1 1 1 1 1 1 1

**Comment by vicuna** [comment]
**Comment author:** @nojb

My understanding is that this is expected. In native code, tail calls require all arguments be passed in registers. So the maximum number of arguments of such calls depends on the number of available registers of the particular architecture.

In my opinion, making a warning for this would be tricky since it depends on the particular native-code backend being used.

**Comment by vicuna** [comment]
**Comment author:** Vincent Cheval

I see. It makes sense. So I guess, only adding something in the manual would be sufficient.

**Comment by vicuna** [comment]
**Comment author:** @gasche

I think we could implement a warning for this (and we probably should) but it requires a fair amount of work to pass some or all annotations on the AST (which are currently dropped after Lambda, iirc.) down to the lower-level representations of the compiler. I don't think that anyone is working on this at the moment, so it probably makes sense to mark this feature request as "suspended".

**Comment by vicuna** [comment]
**Comment author:** Vincent Cheval

For knowledge sake, why is there no issue when the function is not mutual recurse (my first example) and there is more variables than registers ? Does ocamlopt directly modify the value in the stack ?

**Comment by vicuna** [comment]
**Comment author:** @nojb

In simple cases (when the tail call is a recursive call to itself) extra arguments can be passed on the stack without causing it to grow.

**Comment by vicuna** [comment]
**Comment author:** @gasche

I believe that the code responsible for the difference in behavior is select_gen:

  https://github.com/ocaml/ocaml/blob/trunk/asmcomp/selectgen.ml#L1077-L1108

(you can use "ocamlopt -dsel -c test.ml 2>&1" to see the code-selection decisions, and observe that indeed self-recursive calls become tail-calls while mutual calls become nontail-calls. -dcmm has no difference)

The code as written handles three cases, when performing a direct call (to a known function):
- if the stack offset is 0, perform a tail-call
- if the call is to the function itself, perform a tail-call
- otherwise, not a tail-call

With 11 arguments, we need to spill (only 10 immediate registers are available with register allocation on adm64), so the stack offset is not 0. As Nicolás mentions, the difference is that self-calls are compiled into tail-calls even when there is a spill.

I suspect that we could replace "is a self call" by "has the same argument arity and types" (if I understand correctly, the point is that the receiving function expects the same spilling structure, and this should be determined by the typed arity of the function, correct?), and then the mutual-call would be a tail-call as well.

**Comment by xavierleroy** [comment]
I agree this problem should be properly documented.  Actually I'm surprised it is not mentioned already in section 12.5  Compatibility with the bytecode compiler of the reference manual.

It is really tough to implement proper tail calls when some parameters are stack-allocated.  I tried at least twice in the past and failed both times.

A simpler fix would be to limit uncurrying to N arguments at most, where N is the number of registers available for parameter passing (probably minus one).  This way, tail calls with more than N arguments would incur some performance overhead (because they would not be fully uncurried) but would still run in constant stack space.

In the meantime, I'm putting a "documentation" label on this report.

**Comment by gasche** [comment]
> A simpler fix would be to limit uncurrying to N arguments at most, where N is the number of registers available for parameter passing (probably minus one). This way, tail calls with more than N arguments would incur some performance overhead (because they would not be fully uncurried) but would still run in constant stack space.

Ah, that would be nice. If we did this consistently we would never need to worry about architecture-dependent factors to reason about stack usage, and `[@tailcall]` would be more reliable.

**Comment by xavierleroy** [comment]
Tut, tut, no commenting on closed issues!  But please see my recent pull request #9620 -- one of a batch where I'd like to get more reviewing, by the way --, it provides most of the machinery to do that.
