### ISSUE TITLE
Module equality fail in functor

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#7901]
**Original bug ID:** 7901
**Reporter:** bodethau
**Status:** new
**Resolution:** open
**Priority:** normal
**Severity:** minor
**Version:** 4.07.1
**Category:** typing
**Monitored by:** @nojb @gasche

## Bug description

Type checker is unable to resolve module signature inclusion for some intricate module compositions.
I've uploaded an example where, in the end, it fails to check 

```ocaml
module type ENVIRONMENT = sig
	module Module : MODULE
end

module Make
	(M : MODULE)
	: ENVIRONMENT
= struct
	module Module = M
end
```

I feel like, independently of MODULE, it should always be possible to type this. However I get the following error :

```
File "test.ml", line 32, characters 2-31:
Error: Signature mismatch:
       ...
       In module Module:
       Modules do not match:
         sig module B = Module.B module Object = Module.Object end
       is not included in
         MODULE
       In module Module.Object:
       Modules do not match:
         (module Module.Object)
       is not included in
         (module B.Object)
```

(c.f. attached files to look at the definition of MODULE).

I you remove the module "Object" from the MODULE module type, then the error disappears.

I've tested this example with ocaml 4.07.0 : it works fine.
I've tested this example with ocaml 4.06.1 : it works file.

I think it may have been introduced by #2051.

## File attachments

- [test.ml](https://gist.githubusercontent.com/vicuna/e3bbbaa7f22ecfed75738bb59f572fe3/raw/e179b26bd220a7db171455eb00f6a3f667dfe195/test.ml)

**Comment by vicuna** [comment]
**Comment author:** @lpw25

For some definitions of `MODULE` this is an expected outcome of #2051. I hope to get rid of this in the not too distant future, but for now it is needed for soundness.

**Comment by lpw25** [comment]
This is still on the roadmap to be fixed, so I'll remove the stale tag. Ongoing work to support "transparent module ascription" will fix this issue.

**Comment by gasche** [comment]
Out of curiosity, what is the status of "ongoing work to support transparent module ascriptions"?

**Comment by lpw25** [comment]
Currently stalled by not having someone available to work on it. Still pretty high on the list of things we want though. In particular, I think it would solve a number of performance problems in the type checker.

**Comment by trefis** [comment]
I believe @Drup had also been looking at this recently, perhaps he can tell us about what's been happening on his side?

**Comment by Drup** [comment]
I'm personally rather convinced by the calculus I have, it looks fairly solid and fixes most of what we would like to fix, and the prototype works well. It's all [there](https://github.com/Drup/module-experiments).

It's currently on standby, partially because I lost steam working alone on it (which is difficult for me in the current context), and partially because i would like to prove that the resulting calculus is correct which should be *much* easier using the approach currently investigated by @diremy and his intern.

It's a change to the module system that is significant enough to deserve a bit more garantees than usual, imho.
