### ISSUE TITLE
ocaml teststuite: Most unix tests are not actually being run

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#7909]
**Original bug ID:** 7909
**Reporter:** gfxmonk
**Status:** new
**Resolution:** open
**Priority:** normal
**Severity:** minor
**Version:** 4.07.1
**Category:** configure and build/install
**Monitored by:** @nojb @gasche

## Bug description

In reporting ocaml/ocaml#7908, I found that the following test preamble is common:
```
(* TEST
   * hasunix
   include unix
*)
```
However, this results in a test case which succeeds to check for unix support (or not), and does nothing else.

I believe the correct preamble to run the default tasks (but only if the unix lib is supported) is:
```
(* TEST
* hasunix
include unix
** bytecode
** native
*)
```
## Steps to reproduce

in testsuite, run `make one DIR=tests/lib-unix/common`

Observe many tests just print something like:
```
 ... testing 'getaddrinfo.ml' with 1 (hasunix) => passed
```

with my fixed preamble from above, it prints:
```
 ... testing 'getaddrinfo.ml' with 1 (hasunix) => passed
 ... testing 'getaddrinfo.ml' with 1.1 (bytecode) => passed
 ... testing 'getaddrinfo.ml' with 1.2 (native) => passed
```

This seems like a pretty easy bug to write, so I'd expect there to be more examples aside from `hasunix`.

**Comment by nojb** [comment]
This report seems correct. Many tests in `tests/lib-unix` are affected.

cc @shindere
