### ISSUE TITLE
ocaml testsuite: script action breaks redirection for further actions

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#7910]
**Original bug ID:** 7910
**Reporter:** gfxmonk
**Status:** new
**Resolution:** open
**Priority:** normal
**Severity:** minor
**Version:** 4.07.1
**Category:** configure and build/install
**Monitored by:** @nojb @gasche

## Bug description

When adding a test for ocaml/ocaml#7908, I needed to only run the test on Linux (not other unixes). So I used this preamble:

```
(* TEST
include unix
modules = "recvfrom.ml"
script = "sh ${test_source_directory}/is-linux.sh"
* hasunix
** script
*** bytecode
*** native
*)
```

Without the `** script` line, everything was fine. But with it, my actual test's output was being sent to stdout and then the code to check actual output against expected threw an error.

I added some debug code (see steps to reproduce), and it seemed to be that the `script` line ended up setting `stdout` to the empty string, which was inherited by further steps. This didn't actually redirect anywhere, but prevented later redirects (e.g. in the `bytecode` action) from having any effect.

I'm not really sure what the right behaviour is -- it seems weird for future steps to inherit redirection settings in the first place. But I'm not very familiar with ocamltest so I'll just point it out and hope someone else has a better idea ;)

In case it's useful for others, as a workaround I added this to my script to "undo" these unwanted bindings:

```
cat > "$ocamltest_response" <<EOF
-stdout
-stderr
EOF
```

## Additional information

This hacky diff let me see which redirects were in place for each `run` action:

```
diff --git a/ocamltest/actions_helpers.ml b/ocamltest/actions_helpers.ml
index 2c5c62081..be911d99c 100644
--- a/ocamltest/actions_helpers.ml
+++ b/ocamltest/actions_helpers.ml
@@ -163,6 +163,11 @@ let run
       if redirect_output
       then begin
         let output = Environments.safe_lookup Builtin_variables.output env in
+    Printf.eprintf "REDIRECT_OUTPUT=%b -- %s\n" redirect_output output;
+    Printf.eprintf "EXISTING = %s\n" (
+    match Environments.lookup Builtin_variables.stdout env with
+      | Some x -> "[" ^ x ^ "]" | None -> "None"
+    );
         let env =
           Environments.add_if_undefined Builtin_variables.stdout output env
         in
```

**Comment by gasche** [comment]
This seems related to the work in #9596: possibly something that is easier to think about with an explicit representation of effectful test actions.

(cc @shindere @nojb)

**Comment by nojb** [comment]
> This seems related to the work in #9596: possibly something that is easier to think about with an explicit representation of effectful test actions.

Indeed. A more disciplined scoping regime for variables (currently all variables in ocamltest have global scope) would also help.

**Comment by shindere** [comment]
The script actions could (should) perhaps restore the redirections.

Meanwhile, I think there is a solution: the variables can be re-defined
within the bytecode and native tests.
