### ISSUE TITLE
mmapped bigarrays that have been sliced are never unmapped

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#7915]
**Original bug ID:** 7915
**Reporter:** danielrichman
**Status:** new
**Resolution:** open
**Priority:** normal
**Severity:** minor
**Platform:** Unix
**Version:** 4.07.0
**Category:** otherlibs
**Monitored by:** @nojb @diml

## Bug description

caml_ba_slice uses caml_ba_alloc and hence caml_ba_ops/caml_ba_finalize, even if the array you are slicing is mmapped and so it _should_ be using caml_ba_mapped_ops/caml_ba_mapped_finalize.

When the slice is garbage collected, caml_ba_finalize either asserts-0, or does nothing (if assertions are not enabled), and in particular does not decrease the refcount on the proxy.

When the original array is garbage collected, the refcount is greater than 1, so it is not freed.

## Steps to reproduce

Build and execute attached file with ocamlopt.

## File attachments

- [test.ml](https://gist.githubusercontent.com/vicuna/a85f363ed2855189eb58c19e9fc87195/raw/96bee30b11954ad47c37bffeb5be5e17cb8bd7ca/test.ml)

**Comment by xavierleroy** [comment]
Fixed by PR #8568.
