### ISSUE TITLE
Surprising priority of algebraic attributes

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#7916]
**Original bug ID:** 7916
**Reporter:** AltGr
**Assigned to:** @diml
**Status:** assigned (set by @diml on 2019-02-11T13:51:57Z)
**Resolution:** open
**Priority:** low
**Severity:** minor
**Version:** 4.07.1
**Category:** lexing and parsing
**Monitored by:** @nojb @diml

## Bug description

The manual is not very clear about the priority of the postfix `[@foo ]` notation, esp. w.r.t. infix operators. The parser defines it between `::` and INFIXOP1 (`@`, `^`), and in fact, the presence of attributes can change the meaning of an expression, which I find surprising.

There may be good reasons for this though ?

## Steps to reproduce

```ocaml
# 3 + 2 * 4;;
- : int = 11
# 3 + 2 [@foo] * 4;;
- : int = 20
```

## Additional information

Found this while debugging ocp-indent issue #275, https://github.com/OCamlPro/ocp-indent/issues/275

**Comment by vicuna** [comment]
**Comment author:** @diml

I remember changing some of the priorities of attribute attachment. I'll try to find the discussions, but the original motivation was to make the attachment of annotations in record fields and constructors more natural. In the end we decided to make the rules consistent between expressions, types, etc...

**Comment by vicuna** [comment]
**Comment author:** @diml

It was this GPR: https://github.com/ocaml/ocaml/pull/152
which followed this mantis ticket: ocaml/ocaml#6612

**Comment by vicuna** [comment]
**Comment author:** AltGr

Ah, indeed I understand the motivation better. In the GPR, only the effects on type definitions are considered, though (and those make sense!)
My issue is the result on the parsing of expressions, though.

**Comment by vicuna** [comment]
**Comment author:** @diml

That's true. And the PR actually doesn't change the parsing of expressions. We might have changed the parsing of expressions in a subsequent GPR in order to make everything more homogeneous.

Maybe the rule we used wasn't the best one, and instead it could have been: attach the attribute to the biggest syntactic element possible without changing the parsing. i.e. erasing attributes in the source code should yield the same AST modulo attributes.

It's probably quite a lot of work to change that now though.

**Comment by ghost** [comment]
It's unlike to change at this point, so closing this issue.
