### ISSUE TITLE
Non deleted object files on fatal warnings

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#7918]
**Original bug ID:** 7918
**Reporter:** cfranchini
**Status:** confirmed (set by @gasche on 2019-02-15T17:59:31Z)
**Resolution:** open
**Priority:** normal
**Severity:** major
**OS:** GNU/Linux (Arch)
**Target version:** 4.08.0+dev/beta1/beta2
**Category:** compiler driver
**Monitored by:** @nojb @diml

## Bug description

When compilation of a module failed because of warnings, the generated
object files are not removed. I attached a script that test just one
case - I didn't do exhaustive testing.

Tested on GNU/Linux (Arch) with the two following versions

branch: trunk
commit: 07794568ebdb36d121051e8003cb9ccdd88d847d
verison: 4.09.0+dev0-2019-01-18

branch: 4.08
commit: a932c1a2364c26685686a1da0d2587c1e2652d1e
version: 4.08.0+dev4-2019-02-0

## Steps to reproduce

Run the script checkspuriousobj.sh

## File attachments

- [checkspuriousobj.sh](https://gist.githubusercontent.com/vicuna/5696bb60f1935478eedc7b0fff482456/raw/95608e19ada9d3a6559fb88286ad89f1dde10b2d/checkspuriousobj.sh)

**Comment by vicuna** [comment]
**Comment author:** @gasche

Is this not a reasonable behavior? If the .cmo file is valid, keeping it on the disk sounds useful. For example, I think that the fact that .cmi files stay on the disk even if later code generation files is useful for Merlin.

**Comment by vicuna** [comment]
**Comment author:** cfranchini

No, it's not reasonable.

I type make once, it failed, if I type make again, it succeed. That's how I spotted the bug. That behavior will break all working Makefile in the Earth.

**Comment by vicuna** [comment]
**Comment author:** @diml

I would argue that make is the culprit here. A good build system should re-run actions that fail.

**Comment by vicuna** [comment]
**Comment author:** cfranchini

>I would argue that make is the culprit here.

We're talking about the program which builds gcc, linux, bash, emacs, ocaml, ... I'm sure it's behavior is the correct one.
 
>A good build system should re-run actions that fail.

[striked]I disagree, and I'm sure that a lot of people would agree with me. (Just to be sure: it's not sarcasm, is it?)[/striked]

edit: I was misunderstanding your second statement. It's not how make works.

**Comment by vicuna** [comment]
**Comment author:** @diml

That's the idea; because make is very simple, individual commands have to be more sophisticated so that builds using make behave correctly. That doesn't feel completely right.

**Comment by vicuna** [comment]
**Comment author:** @alainfrisch

Please let's stay focused here on what OCaml should do, not what a good build system should be.  make is still used quite a bit (to build OCaml itself for instance) and we should not break existing workflows.  Assuming the described behavior is a change in recent versions, I'm in favor of going back to the previous behavior.

If needed, one could add a command-line flag to control the behavior.  But:


> If the .cmo file is valid, keeping it on the disk sounds useful. For example, I think that the fact that .cmi files stay on the disk even if later code generation files is useful for Merlin.

.cmt/.cmti files should certainly be kept even in case of errors, and they contain all the information (.cmti files "include" the .cmi information as is).  Doesn't Merlin use these files?

**Comment by vicuna** [comment]
**Comment author:** @trefis

Merlin will use .cmt(i) files for a few specific operations, but the majority of what it does is done using .cmi files.

**Comment by vicuna** [comment]
**Comment author:** @gasche

I hadn't realized while reading the original report that the described behavior was specific to non-released versions of OCaml, and that 4.07 behaves differently. This indeed sounds like a regression to be fixed.

**Comment by vicuna** [comment]
**Comment author:** @gasche

I bisected the issue, it first appeared during the following commit (the creation of driver/compile_common.ml)

  abc0b7e3edf3d4aeb9396e03e7d113f43818f18e
  https://github.com/ocaml/ocaml/commit/abc0b7e3edf3d4aeb9396e03e7d113f43818f18e

**Comment by vicuna** [comment]
**Comment author:** @gasche

I propose a fix in

  https://github.com/ocaml/ocaml/pull/2257

**Comment by alainfrisch** [comment]
Fixed by #2257.
