### ISSUE TITLE
In configure, the ccfamily variable is not defined

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#7919]
**Original bug ID:** 7919
**Reporter:** Vincent L
**Assigned to:** @shindere
**Status:** assigned (set by @xavierleroy on 2019-03-09T09:37:11Z)
**Resolution:** open
**Priority:** normal
**Severity:** major
**Platform:** Darwin
**OS:** OSX
**Version:** 4.08.0+dev/beta1/beta2
**Target version:** 4.08.0+dev/beta1/beta2
**Category:** configure and build/install
**Monitored by:** @nojb

## Bug description

The configure script relies on a `ccfamily` variable to determine what program to use as assembler (https://github.com/ocaml/ocaml/blob/trunk/configure.ac#L934).

It used to be defined there: https://github.com/ocaml/ocaml/blob/c5c0bdc8313f5f356d24a65e9305e9d454996600/configure#L409

This makes compilation of OCaml 4.08.0+beta1 fail on OSX with clang and no gcc.

Example failing log: https://logs.nix.ci/?key=nixos/nixpkgs.55570&attempt_id=a52f6083-51ee-432c-bdfd-1a5704c58db1

**Comment by vicuna** [comment]
**Comment author:** Vincent L

This problem is still there with OCaml 4.08.0+beta2:

gcc -arch x86_64 -c -DSYS_macosx -I../runtime -DMODEL_default -o amd64.o amd64.S || \
{ echo "If your assembler produced syntax errors, it is probably";\
          echo "unhappy with the preprocessor. Check your assembler, or";\
          echo "try producing amd64.o by hand.";\
          exit 2; }
/nix/store/g9cis4hsnzcjkzfa77nif7kzq9bsqmpg-bash-4.4-p23/bin/bash: gcc: command not found
If your assembler produced syntax errors, it is probably
unhappy with the preprocessor. Check your assembler, or
try producing amd64.o by hand.
make[3]: *** [Makefile:370: amd64.o] Error 2

**Comment by shindere** [comment]
Closed by #2311

**Comment by vbgl** [comment]
Thank you.

**Comment by shindere** [comment]
You're welcome! You may wnat to double check this actually works!
