### ISSUE TITLE
Compiler crashes with an Invalid_argument("index out of bounds")

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#7920]
**Original bug ID:** 7920
**Reporter:** Iguernlala
**Status:** new
**Resolution:** open
**Priority:** high
**Severity:** crash
**Platform:** Linux
**OS:** Xubuntu
**OS Version:** 18.04
**Category:** middle end (typedtree to clambda)
**Has duplicate:** #7928
**Monitored by:** @nojb zozozo

## Bug description

I just installed OCaml 4.08.0+beta1 and tried to compile Alt-Ergo 1.30. But the compiler immediately crashed with an Invalid_argument("index out of bounds")

## Steps to reproduce

0. an opam switch with OCaml 4.08.0+beta1

1. install Alt-Ergo 1.30 deps:
$ opam install zarith.1.7 ocplib-simplex.0.3 num.1.1 camlzip.1.07

2. get Alt-Ergo 1.30 sources:
$ wget https://alt-ergo.ocamlpro.com/http/alt-ergo-1.30/alt-ergo-1.30.tar.gz
$ tar -xf alt-ergo-1.30.tar.gz
$ cd alt-ergo-1.30

4. Optionnaly, edit "src/util/zarithNumbers.ml" and replace Pervasives with Stdlib

5. configure and make
$ ./configure
$ make

I then get:

ocamlopt.opt -c -annot -absname -bin-annot -short-paths -strict-sequence -g -inline 100 -I /home/mi/.opam/ocaml-variants.4.08.0+beta1/lib/zarith   -I /home/mi/.opam/ocaml-variants.4.08.0+beta1/lib/camlzip/../zip -I /home/mi/.opam/ocaml-variants.4.08.0+beta1/lib/ocplib-simplex -I src/util -I src/structures -I src/theories -I src/instances -I src/sat -I src/preprocess -I src/parsing -I src/gui -I src/main -I non-free/plugins/common -I non-free/plugins/satML -I non-free/plugins/profiler -I non-free/plugins/fm-simplex src/util/zarithNumbers.ml
Fatal error: exception Invalid_argument("index out of bounds")
Makefile.users:234: recipe for target 'src/util/zarithNumbers.cmx' failed
make: *** [src/util/zarithNumbers.cmx] Error 2

Note that compiling Alt-Ergo with "make byte" succeeds

## Additional information

Backtrace:

OCAMLRUNPARAM=b ocamlopt.opt -c -annot -absname -bin-annot -short-paths -strict-sequence -g -inline 100 -I /home/mi/.opam/ocaml-variants.4.08.0+beta1/lib/zarith   -I /home/mi/.opam/ocaml-variants.4.08.0+beta1/lib/camlzip/../zip -I /home/mi/.opam/ocaml-variants.4.08.0+beta1/lib/ocplib-simplex -I src/util -I src/structures -I src/theories -I src/instances -I src/sat -I src/preprocess -I src/parsing -I src/gui -I src/main -I non-free/plugins/common -I non-free/plugins/satML -I non-free/plugins/profiler -I non-free/plugins/fm-simplex src/util/zarithNumbers.ml
Fatal error: exception Invalid_argument("index out of bounds")
Raised by primitive operation at file "bytecomp/translmod.ml", line 895, characters 46-55
Called from file "list.ml", line 92, characters 20-23
Called from file "bytecomp/translmod.ml", line 991, characters 36-54
Called from file "bytecomp/translmod.ml", line 993, characters 37-193
Called from file "bytecomp/translmod.ml", line 1190, characters 4-69
Called from file "bytecomp/translobj.ml", line 131, characters 13-18
Called from file "bytecomp/translmod.ml", line 1264, characters 18-65
Called from file "utils/misc.ml", line 31, characters 8-15
Re-raised at file "utils/misc.ml", line 45, characters 10-56
Called from file "driver/optcompile.ml", line 66, characters 2-94
Called from file "utils/misc.ml", line 31, characters 8-15
Re-raised at file "utils/misc.ml", line 45, characters 10-56
Called from file "driver/compile_common.ml", line 124, characters 6-68
Called from file "utils/misc.ml", line 31, characters 8-15
Re-raised at file "utils/misc.ml", line 45, characters 10-56
Called from file "utils/misc.ml", line 31, characters 8-15
Re-raised at file "utils/misc.ml", line 45, characters 10-56
Called from file "driver/compenv.ml", line 597, characters 6-59
Called from file "list.ml", line 110, characters 12-15
Called from file "driver/compenv.ml", line 673, characters 2-61
Called from file "driver/optmain.ml", line 267, characters 6-163
Re-raised at file "parsing/location.ml", line 904, characters 14-25
Called from file "driver/optmain.ml", line 333, characters 6-37
Called from file "driver/optmain.ml", line 337, characters 2-9

**Comment by vicuna** [comment]
**Comment author:** vlaviron

I've built a simplified repro case:

(* BEGIN *)
module Z = struct end

module type QSig = sig
  module Z : sig end
end

module Q : QSig with module Z = Z = struct
  module Z = Z
end
(* END *)

There's no need for an mli file to trigger the bug.
Turning on the commented debug line in translmod.ml:976 prints the following coercion:

coerc id Q_6: struct [-1, alias Z (id)] []

Someone suggested to me to change the index to an int option (instead of using -1) and adapt the code accordingly, but I don't know this part of the compiler enough to feel like trying it myself.

**Comment by vicuna** [comment]
**Comment author:** @lpw25

This was caused by my patch for positions. Just making a PR now.

**Comment by vicuna** [comment]
**Comment author:** @lpw25

https://github.com/ocaml/ocaml/pull/2252

**Comment by nojb** [comment]
PR merged, so closing.
