### ISSUE TITLE
Missing index of top-level libraries

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#7922]
**Original bug ID:** 7922
**Reporter:** lcorrenson
**Assigned to:** @Octachron
**Status:** acknowledged (set by @Octachron on 2019-02-15T09:31:18Z)
**Resolution:** open
**Priority:** normal
**Severity:** minor
**Category:** documentation
**Monitored by:** @nojb @gasche

## Bug description

An easy access to the index of top-level modules of the « standard library » is missing.

The only access to such an index is currently :
 - at the very end of the Stdlib section § 23.3, spawning a list over more 5 pages on 21' screen display (sic)
 - among the terribly verbose index of all module names

This is very inconvenient. In OCaml 4.07 manual, the index fits into the front page of §26 !

Source :

https://caml.inria.fr/distrib/ocaml-4.08

**Comment by vicuna** [comment]
**Comment author:** @Octachron

This seems indeed quite cumbersome for the single html page manual. I will have a look. However, an index of the standard library modules is available at https://caml.inria.fr/pub/docs/manual-ocaml-4.08/libref/ (and in 4.08, this index does not mix the standard library and compiler-libs).

**Comment by vicuna** [comment]
**Comment author:** lcorrenson

Oh, great !!

Hence just having an HTML link to this libref/index.html in the table of contents in chapter § 23 (one-click from the home page) would be very nice !

PS: the new style of the documentation is much prettier than before :-)

**Comment by vicuna** [comment]
**Comment author:** lcorrenson

Final note: currently the links to compiler-libs are broken in https://caml.inria.fr/pub/docs/manual-ocaml-4.08
But this can be only a pre-release situation.

**Comment by Octachron** [comment]
This was fixed along with the other fixes for the 4.08 manual.
