### ISSUE TITLE
Tsubst remaining in structure after call to Env.save_signature

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#7929]
**Original bug ID:** 7929
**Reporter:** @trefis
**Assigned to:** @trefis
**Status:** assigned (set by @trefis on 2019-02-21T11:15:08Z)
**Resolution:** open
**Priority:** normal
**Severity:** minor
**Version:** 4.08.0+dev/beta1/beta2
**Category:** typing
**Monitored by:** @nojb

## Bug description

Noticed when trying odoc on 4.08: https://github.com/ocaml/odoc/issues/311

The regression is due to: https://github.com/ocaml/ocaml/commit/4d4fd525c987aa80244d225b2fba09e8dd47f917#diff-668ada709c086c9f2b56861bb1872a5dR461

It made the assumption that the order in which we apply the substitution doesn't matter.
Which is wrong in that case because of: https://github.com/ocaml/ocaml/blob/trunk/typing/subst.ml#L345

The obvious fix is to replace the call to List.rev_map by List.rev followed by List.map.

Another potential option would be to introduce functions like class_declaration' (and others) which don't do the cleanup.
Use those in signature_item, and call cleanup_types only once at the end.

I'm going to experiment with that (unless someone jumps in to explain why it can't possibly be correct) and if it works I'll submit that as a fix instead of the obvious one.

**Comment by vicuna** [comment]
**Comment author:** @gasche

(My personal take-away from this is that we should ramp up on full-opam testing of typer changes.)

**Comment by vicuna** [comment]
**Comment author:** @trefis

> Another potential option would be to introduce functions like
> class_declaration' (and others) which don't do the cleanup.
> Use those in signature_item, and call cleanup_types only once at the end.

Implemented in https://github.com/ocaml/ocaml/pull/2261

**Comment by trefis** [comment]
Fixed by #2261.
