### ISSUE TITLE
Configure support for FreeBSD on ARM 64 bit

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#7930]
**Original bug ID:** 7930
**Reporter:** jfc
**Status:** new
**Resolution:** open
**Priority:** normal
**Severity:** minor
**Platform:** ARM64
**OS:** FreeBSD
**OS Version:** 13
**Category:** configure and build/install

## Bug description

configure on ARM64 FreeBSD does not know what assembler to use (there is no as) or what native code generator to use.  This patch enables native code generation.  Bootstrap is prevented by a bug in ARM64 code generation.  I will file that bug separately.

This is relative to 4.08 beta.  4.07 also fails to recognize FreeBSD-arm64 but the patch is different due to the change in configure.

## File attachments

- [o.diff](https://gist.githubusercontent.com/vicuna/24417e1deb35d53c64033d97dbd8bbff/raw/248c2d1bf1844f6d0b1c7182ff1a8bac32a96166/o.diff)

**Comment by xavierleroy** [comment]
Addressed by the merge of #1904 .  See also #7931 .
