### ISSUE TITLE
8-byte access alignment detection is wrong with autoconf

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#7938]
**Original bug ID:** 7938
**Reporter:** @Reperator
**Status:** acknowledged (set by @xavierleroy on 2019-03-09T09:32:23Z)
**Resolution:** open
**Priority:** normal
**Severity:** minor
**Version:** 4.08.0+dev/beta1/beta2
**Category:** configure and build/install
**Monitored by:** @Reperator @nojb @shindere @stedolan @hcarty

## Bug description

autoconf's AC_CHECK_ALIGNOF([long]) always returns "x8", regardless of architecture. This is not actually the legal alignment of memory accesses.

ARCH_ALIGN_INT64 used to be defined from the result of config/auto-aux/int64align.c, which actually checks for legal memory access requirements. This was changed in 4.08.

Reading int64 values from the heap is going to be slower.

https://www.gnu.org/software/autoconf/manual/autoconf-2.67/html_node/Generic-Compiler-Characteristics.html

**Comment by vicuna** [comment]
**Comment author:** @nojb

The configure script does not seem to use `AC_CHECK_ALIGNOF`. Instead it does its own test to compute alignment, see 

https://github.com/ocaml/ocaml/blob/d47ba6ec18fc72d0aedabd162e373fecba2d7eaa/configure#L13325-L13349

Is there a problem with this test?

**Comment by vicuna** [comment]
**Comment author:** @stedolan

I think that link is to the generated configure, the source is https://github.com/ocaml/ocaml/blob/d47ba6ec18fc72d0aedabd162e373fecba2d7eaa/configure.ac#L691

I think the issue is that on 32-bit platforms, ocaml will now think that 64-bit reads and writes require 8-byte alignment, which will trigger the slow path whereby 64-bit accesses are emulated as a pair of 32-bit accesses.

What the old configure script checked was "will 64-bit accesses that are only 4-byte aligned trap?", while the new configure script asks "what is the optimal alignment of a 64-bit access?". There are several platforms (e.g. x86) where the optimal alignment is 8 bytes, yet 4-byte aligned accesses work fine.

The fix is to replace AC_CHECK_ALIGNOF with a macro that checks whether 4-byte alignment traps. I'm not enough of an autoconf expert to know if there's a standard macro for this, though.

**Comment by vicuna** [comment]
**Comment author:** @nojb

Indeed, sorry for the confusion.

**Comment by vicuna** [comment]
**Comment author:** @Reperator

Indeed. I'm working on a PR that additionally needs checks for 32-bit and 16-bit accesses in order to use atomic reads/writes for bigarrays on supported platforms. If anybody with autoconf knowledge were to implement these, that'd be great.

**Comment by vicuna** [comment]
**Comment author:** @xavierleroy

The old autodetection code was fragile and unreliable, so I advise against resurrecting it.

The plan we had with @shindere was to use the C compiler alignment as the default, and hard-code a small list of exceptions for which we know that the hardware supports reduced alignment, in particular x86.

**Comment by shindere** [comment]
PR #8532 proposes a fix for this.

**Comment by shindere** [comment]
Fixed by PR#8532 in both trunk and the 4.08 branch.
