### ISSUE TITLE
feature wish: support printf "%8.8s"

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#8036]
**Original bug ID:** 1565
**Reporter:** administrator
**Status:** confirmed (set by @mshinwell on 2016-12-07T16:28:40Z)
**Resolution:** open
**Priority:** normal
**Severity:** feature
**Category:** standard library
**Has duplicate:** #8037

## Bug description

Full_Name: Eric Cooper
Version: 3.06
OS: linux
Submission from: 12-227-100-158.client.attbi.com (12.227.100.158)

Please consider supporting the "precision" field in the %s printf conversion.
In C, this limits the printed string to that many characters. For example,
printf "%8.8s" string

**Comment by vicuna** [comment]
**Comment author:** administrator

cf. #8037

**Comment by vicuna** [comment]
**Comment author:** @mshinwell

This still appears not to be supported.

**Comment by Kakadu** [comment]
seems to be a good candidate for `junior_job` tag

**Comment by gasche** [comment]
Yes and no... this interacts with the format GADTs in non-trivial ways, so it might be a good entry point for expert OCaml programmers but I wouldn't send a medium-level OCaml user this way.

**Comment by yallop** [comment]
Closing as a duplicate of #6942.  (Actually, this report is much older, but #6942 has more discussion, so I'm closing this one.)
