### ISSUE TITLE
Re: ocaml: module Graphics: type event should include a resize event

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#8170]
**Original bug ID:** 1711
**Reporter:** administrator
**Status:** acknowledged
**Resolution:** open
**Priority:** normal
**Severity:** feature
**Category:** otherlibs

## Bug description

tags 179255 upstream
severity 179255 whishlist
thanks

Bonjour,

Je suis en train de faire le menage dans le bts du package debian ocaml,
et je suis tomber sur ces deux bugreports, que je pensais avoir fait
suivre upstram precedement, mais que je ne retrouve pas dans le BTS
ocaml. Voila qui est fait donc.

Amicalement,

Sven Luther

On Fri, Jan 31, 2003 at 09:38:12PM +0100, Goswin Brederlow wrote:
> Package: ocaml
> Version: 3.06-15
> Severity: wishlist
> 
> It would be nice if one could also wait for a resize event (and maybe
> even expose events to trigger redraws when not using double buffering).
> 
> MfG
> 	Goswin
> 
> -- System Information:
> Debian Release: testing/unstable
> Architecture: i386
> Kernel: Linux dual 2.4.19 #11 SMP Thu Jan 9 00:18:31 CET 2003 i686
> Locale: LANG=C, LC_CTYPE=de_DE
> 
> Versions of packages ocaml depends on:
> ii  libc6                     2.3.1-10       GNU C Library: Shared libraries an
> ii  libncurses5-dev           5.3.20021109-2 Developer's libraries and docs for
> ii  ocaml-base [ocaml-base-3. 3.06-15        Runtime system for ocaml bytecode 
> 
> -- debconf information excluded
> 
> 
>

**Comment by nojb** [comment]
The `graphics` library has been split off into its own repository https://github.com/ocaml/graphics.
This issue has been re-submitted there: https://github.com/ocaml/graphics/issues/2
