### ISSUE TITLE
Wish: refman.info improvement

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#8247]
**Original bug ID:** 1795
**Reporter:** administrator
**Status:** acknowledged
**Resolution:** open
**Priority:** normal
**Severity:** feature
**Category:** documentation

## Bug description

Full_Name: Yamagata Yoriyuki
Version: 3.06
OS: Linux
Submission from: p2114-adsau14honb7-acca.tokyo.ocn.ne.jp (220.106.58.114)

The current refman.info doesn't seem to follow GNU convention of info.  In
particular, I'd like to suggest the following improvement.

1) It is better if chapters and sections are referred by their name, not
numbers.  This change enables a user to use "m" command to jump desired sections
and chapters.

2) Make all chapters listed in the top index, while move licence conditions or
like to their own sections.

3) Remove decorative ****** and *=*=*=*

In general, I think it is preferable to create info from texi, not directly from
latex files by havea.

**Comment by vicuna** [comment]
**Comment author:** administrator

Looks like an Hevea issue...

**Comment by dbuenzli** [comment]
Not an `info` user myself but a test with the last published info files seems to indicate that 1+3 are still present. 

@maranget do you think the "administrator" is right in pointing fingers at HeVeA ?
