### ISSUE TITLE
WISH: beginning of line regexp for ocamllex

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#8353]
**Original bug ID:** 1910
**Reporter:** administrator
**Status:** acknowledged
**Resolution:** open
**Priority:** normal
**Severity:** feature
**Category:** tools (ocaml{lex,yacc,dep,debug,...})

## Bug description

It appears that Ocamllex does not support the "^r" pattern (found in Flex
at least) that matches the beginning of line.  This is very useful for
example in a case where you want to parse the C preprocessor # line
directive.

Emulating this by hand with more complex lexers is kinda awkward.

Best regards,
Janne Hellsten

**Comment by mshinwell** [comment]
Still not implemented nearly 17 years later, so closing.
