### ISSUE TITLE
2 installation issues: permissions and emacs files

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#8361]
**Original bug ID:** 1919
**Reporter:** administrator
**Assigned to:** @shindere
**Status:** assigned (set by @shindere on 2016-12-13T08:21:57Z)
**Resolution:** open
**Priority:** normal
**Severity:** feature
**Category:** configure and build/install
**Related to:** #5219

## Bug description

Full_Name: Oleg Trott
Version: OCaml 3.07p2
OS: Linux (Debian Woody)
Submission from: tw304h3.cpmc.columbia.edu (156.111.84.180)

1. Emacs files do not get intalled automatically, and I had to do
cd emacs && make EMACSDIR=/usr/local/share/emacs/site-lisp install

2. Permissions get set correctly for camlp4, but not for ocaml and emacs files,
so I had to do

chmod -R a+rX /usr/local/bin/ocaml* /usr/local/lib/ocaml \
/usr/local/share/emacs/site-lisp/*

My regular user `umask`  (during ./configure && make && make world.opt) is 0077,

and su `umask` (during make EMACSDIR=/usr/local/share/emacs/site-lisp install)
is 0022. The former is perhaps why the permissions get mixed up.

By the way, both of these happened during ocaml-3.06 installation as well.

Thanks

**Comment by vicuna** [comment]
**Comment author:** administrator

do we want to install emacs files automatically?  feature wish
change permissions upon install?  feature wish

**Comment by dbuenzli** [comment]
This concerns installation of software that is no longer part of the distribution  (`camlp4` and `emacs` mode) and can be closed.
