### ISSUE TITLE
Name clashes

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#8395]
**Original bug ID:** 1956
**Reporter:** administrator
**Assigned to:** @damiendoligez
**Status:** acknowledged (set by @damiendoligez on 2007-11-19T18:09:46Z)
**Resolution:** open
**Priority:** high
**Severity:** minor
**Category:** runtime system and C interface
**Related to:** #8356 #4164 #4230 #4877 #5254 #6126
**Monitored by:** "Hendrik Tews"

## Bug description

Hello Lars and caml-bugs,

There is a name clash between the libcrypto and libcamlrun on the symbol
create_string. This prevents from linking statically an OCaml program that
uses the ocurl library (bindings to the libcurl, which uses libcrypto), and
I guess that horrible things may happen at runtime with dynamic linking.

Similar issues have been raised recently on the caml-list (concerning
the libsamba, libperl, and graphviz libraries).

Any plan to address these issues?

OCaml is no more faulty than these libraries, but this is not a reason not
to fix the problem :-)

A natural solution would be to prefix all the common names like
create_string or get_string. To keep the compatibility with existing C
code that uses Caml C headers, there could be two versions of these
headers (the compatibility header would #DEFINE create_string as
ocaml_create_string and so on).

  Alain

## File attachments

- [no-export-marshall-flags.patch](https://gist.githubusercontent.com/vicuna/edf9b110427e573f9951f988eb31715d/raw/0e7160f33a1620eb5e94a0a12786d8a252be139f/no-export-marshall-flags.patch)

**Comment by vicuna** [comment]
**Comment author:** administrator

see also #8356
fixed for byterun and asmrun 2004-01-07 -DD
still needs to be done for otherlibs (?)

**Comment by vicuna** [comment]
**Comment author:** @damiendoligez

done for otherlibs/bigarray (branch 3.10) 2006-01-27

**Comment by vicuna** [comment]
**Comment author:** @stedolan

Here's a list of the current offenders:
https://gist.github.com/stedolan/6115403

**Comment by vicuna** [comment]
**Comment author:** @lpw25

I attached a patch from Stephen Dolan that stops marshall_flags from being exported.

**Comment by vicuna** [comment]
**Comment author:** @damiendoligez

Patch for marshall_flags applied to 4.03 (commit 5dbea030d1f05606b5bf008c5118c04f72035d28) and trunk (commit 044901bf13bb223684535e375008f7cf105ae843).

The rest will wait till 4.04.

**Comment by vicuna** [comment]
**Comment author:** @xavierleroy

Now that the runtime is clean name-wise, and that several offending "otherlibs" are on their way out (num, str) or are disused (vmthreads), maybe we could declare victory?

**Comment by vicuna** [comment]
**Comment author:** @stedolan

Re-running the command at the top of https://gist.github.com/stedolan/6115403 indicates that there are now a few more offenders, such as invert_root in compact.c and process_debug_events in byterun/backtrace_prim.c.

**Comment by vicuna** [comment]
**Comment author:** @mshinwell

@stedolan Could you produce a patch for those?

**Comment by vicuna** [comment]
**Comment author:** @mshinwell

Consolidating this with another issue so we have a single place to keep track of namespacing problems: the runtime isn't clean yet because of macros and so forth, I suspect:

---

All function in caml C headers are prefixed with caml_.
This is not the case for typedef nor macros in mlvalues.h.
See mlvalues.h for example:
typedef intnat value;
typedef uintnat header_t;
typedef uintnat mlsize_t;
typedef unsigned int tag_t; /* Actually, an unsigned char */
typedef uintnat color_t;
typedef uintnat mark_t;
#define Is_long(x) (((x) & 1) != 0)
#define Is_block(x) (((x) & 1) == 0)
#define Val_long(x) (((intnat)(x) << 1) + 1)
#define Long_val(x) ((x) >> 1)

**Comment by vicuna** [comment]
**Comment author:** @stedolan

Macros, typedefs and static functions are not an issue.

The `caml_` prefix is only necessary for functions and globals which have external linkage. Things like `value` can only conflict with code that explicitly does `#include <mlvalues.h>` and is presumably aware of the OCaml API. Externally-linked symbols like marshall_flags will break other code that defines the same symbol regardless of header files.

I've created a pull request (#973) that removes the current offenders, and adds a tool to detect them.

**Comment by stedolan** [comment]
#973 is merged now, and there are no more un-namespaced symbols exported by `libcamlrun.a` or `libasmrun.a`.
