### ISSUE TITLE
Feature request: bigarray printers

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#8463]
**Original bug ID:** 2106
**Reporter:** administrator
**Status:** acknowledged
**Resolution:** open
**Priority:** normal
**Severity:** feature
**Category:** otherlibs

## Bug description

Hi,

could you please add standard printers for bigarrays and bignums to the
toplevel (and debugger)? This would make it very easy to use the toplevel
for doing mathematics, e.g. in education.

Best regards,
Markus

-- 
Markus Mottl          http://www.oefai.at/~markus          markus@oefai.at

**Comment by vicuna** [comment]
**Comment author:** administrator

seems like a good idea -DD
Problem: bigarrays and bignums are not linked with the default toplevel. -XL

**Comment by nojb** [comment]
Now that bigarrays are part of the stdlib, maybe printers could be considered for them?

**Comment by dbuenzli** [comment]
@nojb could you please relabel as `stdlib`.

The question is then which format and API. Here are a few references:

* @mmottl's lacaml [API](https://github.com/mmottl/lacaml/blob/41b5115d73f043c580e0688df3c21e0221a2aa25/src/io.mli) (2D matrix and vector oriented).
* @dbuenzli's gg [API](https://github.com/dbuenzli/gg/blob/8f761c278d0b2ee2adb94f9fbc033f1bfd76e536/src/gg.mli#L3499-L3507) (linear buffer oriented)
* @ryanrhymes's owl [API](https://github.com/owlbarn/owl/blob/c862c0741ceda37e160894254d93501fd50b5acc/src/base/misc/owl_pretty.mli) (nD array oriented).

These are only the ones on the top of my head, I'm sure there are others.

**Comment by xavierleroy** [comment]
I removed "bignum" from the title, since the old bignum library was split off, and the new ZArith library is external too.

**Comment by mmottl** [comment]
This request is older than 17 years and is not relevant to me personally anymore.  It is very easy to load your own pretty printers into the toplevel.  Users will typically have highly specific preferences for the output of printers anyway, e.g. concerning number precision, column and/or row headers, data alignment, ellipses, etc.  I'm fine if this doesn't make it into the OCaml distribution.
