### ISSUE TITLE
Feature wishes for int_of_string

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#8485]
**Original bug ID:** 2262
**Reporter:** administrator
**Status:** acknowledged
**Resolution:** open
**Priority:** normal
**Severity:** feature
**Category:** standard library

## Bug description

Full_Name: Shawn Wagner
Version: 3.07+2
OS: linux
Submission from: dialup-67.75.195.222.dial1.seattle.level3.net (67.75.195.222)

It'd be nice if int_of_string and related functions could skip over any leading
or trailing spaces in their arguments, rather than raising Failure like it was a
malformed numeric string. Also, versions that take a argument for what base to
convert from would be useful, instead of having to add a prefix to a string
before calling int_of_string.

**Comment by nojb** [comment]
This seems out of scope: the "XXX_of_string" functions in the stdlib are not meant to be used as general parsing functions; they are "merely" the inverses of the `string_of_XXX`.

To skip leading & trailing whitespace one can simply call `String.trim` on the argument of `int_of_string`.
