### ISSUE TITLE
Add String.{Set,Map,Tbl} ?

### ISSUE THREAD

**Issue by nojb** [ocaml/ocaml#8510]
This issue corresponds to PR #2302, where I proposed to add submodules `String.Set` and `String.Map` defined in the obvious way. One can also consider `String.Tbl` for hash tables. I am opening this issue to discuss the approach before focusing on the implementation.

The main technical objection in the linked PR was that doing so introduces a dependency between `String` and `Set` (and `Map` and `Hashtbl`) which causes these latter modules to be linked in even if we are not using the submodules in question.

To handle this I propose to introduce auxiliary modules in the stdlib, say `CamlinternalStringSet`, with the following contents:
```ocaml
include Set.Make (struct type t = string let compare = compare end)
```
Then in `string.ml{,i}` we write:
```ocaml
module Set = CamlinternalStringSet
```
The advantage of doing it this way is that thanks to the magic of module aliases, using `String` would not automatically result in linking `Set` (or `Map` or `Hashtbl`).

It is a bit ugly and haven't yet checked how this will show up in the `ocamldoc`-generator docs, but it solves the linking problem.

Opinions on this approach?

**Comment by trefis** [comment]
I don't have any objection to this approach, but I also have no idea what the generated docs will look like.

**Comment by let-def** [comment]
Add type annotation to benefit from specialization:
```ocaml
include Set.Make (struct type t = string let compare : string -> string -> int = compare end)
```

**Comment by nojb** [comment]
> Add type annotation to benefit from specialization:
> 
> ```ocaml
> include Set.Make (struct type t = string let compare : string -> string -> int = compare end)
> ```

Indeed, good point.

**Comment by mshinwell** [comment]
I'm not convinced that this extra complexity is necessary, for two reasons.  Firstly, the amount of code being pulled in seems really small (I think it's less than 15Kbytes on amd64, for example).  Secondly, we have some ideas to get native dead code elimination working more effectively, with a lower overhead than the existing Flambda+LTO implementation.

I would also suggest that if improvements are going to be made to this area in the standard library that it is worth talking to @sliquister first.  I believe he has detailed knowledge as to the various iterations we've been through at Jane Street over the years with set and map modules, concluding with the current design in `Base`.

**Comment by nojb** [comment]
> I would also suggest that if improvements are going to be made to this area in the standard library that it is worth talking to @sliquister first. I believe he has detailed knowledge as to the various iterations we've been through at Jane Street over the years with set and map modules, concluding with the current design in `Base`.

Any input you may have on this topic is warmly welcome, @sliquister.

**Comment by v-gb** [comment]
In the core interface, the main reason for Map.Make and similar functors is to provide a type of map that has [@@deriving of_sexp] (as that needs a comparison baked-in to build the map). In base, [@@deriving of_sexp] is made to work some other way, and so the functors are not needed, and we removed them and their applications in String/Int/etc to reduce cross modules dependencies, for faster build, and smaller exes in the small (and also it avoids special-casing Base.Map, custom maps can be used exactly the same as Base.Map).

I suspect not applying several functors per compilation units also has benefits in terms of cmt size, typing time, doc size and runtime cost at toplevel, but I don't have evidence for that.

The alias trick suggested here certainly helps, though it seems highly annoying to write (camlinternalint32set.ml, camlinternalint32map.ml, camlinternalint32tbl.ml, then int64, then string, etc), and might make stack traces rather ugly.

**Comment by mshinwell** [comment]
@nojb I'm going to close this, given nothing has happened for a year.  I am in support of adding this kind of functionality (sets, maps, hash tables) to relevant types in the standard library, but there are many issues to consider (see the various benchmarking on Discuss recently, for example), and I would suggest that writing a RFC with a concrete proposal and discussion would the correct starting point.
