### ISSUE TITLE
Improve subtyping support with new engine

### ISSUE THREAD

**Issue by XVilka** [ocaml/ocaml#8513]
To allow function arguments polymorphism and to solve a few other problems along with it.

See the paper https://www.cl.cam.ac.uk/~sd601/papers/mlsub-preprint.pdf and the code of MLsub https://github.com/stedolan/mlsub

Based on the question https://discuss.ocaml.org/t/function-argument-polymorphism/3224/2

Might be useful for:
- https://github.com/ocaml/ocaml/issues/6130
- https://github.com/ocaml/ocaml/issues/7151

**Comment by lpw25** [comment]
MLsub has requirements that aren't met by OCaml, in particular it requires all type contexts/parameters to be either covariant or contravariant. So the work can't be used directly as a replacement for unification in OCaml. Rewriting the type-checker to work that way would be a large amount of work.

It also wouldn't solve the problem that you reference. It would allow us to remove subtyping coercions (i.e. `( ... :> ....)`) but those records types are not subtypes of one another in OCaml.
