### ISSUE TITLE
Bigarray from string

### ISSUE THREAD

**Issue by codename68** [ocaml/ocaml#8519]
I'd like to file a feature request about adding a new function that takes:
string -> ('a, 'b) Bigarray.kind -> 'c Bigarray.layout -> int array -> ('a, 'b, 'c) Bigarray.Genarray.t
It would interpret the string's contents as contents that came from memory.

Let me just talk about the use case I've had and why I would like that.
I've tried to write a program that takes as input a dynamic array from a fifo (the type information and the length of the array are given first on the fifo, and then the array data).
The perfect candidate to store the array contents is Bigarray, it has already a perfect kind type to represent the type information.
The only function in the standard library that is able to return a Bigarray from raw data, as of now and unless I'm mistaken, is Unix.map_file.
This function is, unfortunately, not able to work on fifos, so I need to first read the data into memory, and then somehow transform that string into a bigarray.
This is impossible with the functions presently available, at least without resorting to writing that string to a file and then use Unix.map_file, which, you'll convene, is not particularly beautiful.

**Comment by nojb** [comment]
Off the top of my head, several libraries that carry a function to convert a string to a bigarray:

- [Lwt](https://github.com/ocsigen/lwt/blob/a79c1cdc6e90f367e48289e3503e71beb6b2108b/src/unix/lwt_bytes.mli#L39)
- [bigstringaf](https://github.com/inhabitedtype/bigstringaf/blob/80206b7f57311ab2a9eb3d67514bd9b615921c25/lib/bigstringaf.mli#L24)
- [ocaml-bigstring](https://github.com/c-cube/ocaml-bigstring/blob/928098eadf6fb3584fff56a0d7ff25ef1b79fc13/src/bigstring.mli#L111)
- [base_bigstring](https://github.com/janestreet/base_bigstring/blob/654c501893c41b84c2fa1af282382b275846383e/src/base_bigstring.mli#L36)

**Comment by codename68** [comment]
Hi,

none of these libraries permit to select the kind and dimensions of your data.

Maybe it would be more clear if I say that I want a function that takes a Bytes.t instead of string: I'm not interested into the character array in itself, but as a representation of underlying data.

**Comment by yallop** [comment]
> I'd like to file a feature request about adding a new function that takes:
```string -> ('a, 'b) Bigarray.kind -> 'c Bigarray.layout -> int array -> ('a, 'b, 'c) Bigarray.Genarray.t```


The [memcpy](https://github.com/yallop/ocaml-memcpy) package makes it fairly easy to write such a function:

```ocaml
open Bigarray
let bacopy : type a b. bytes -> (a, b) kind -> int array -> (a, b, c_layout) Genarray.t =
  fun src k dims ->
  let dst = Genarray.create k c_layout dims in
  Memcpy.(memcpy_from_bytes (bigarray Ctypes.genarray dims k)) ~src ~dst ~dst_off:0;
  dst
```

There's currently no support for Fortran-layout arrays, but it wouldn't be hard to add.

**Comment by codename68** [comment]
Thanks!
This is what I need.

I still think that this functionality should be present somewhere in the stdlib, as a more generic Unix.map_file; and the dependency to ctypes just to be able to reinterpret data is big.

**Comment by xavierleroy** [comment]
I think the need is uncommon enough that it's OK to require an external library.
