### ISSUE TITLE
Question: Is there a PPA to update Ubuntu 16.04 to 4.05 or newer?

### ISSUE THREAD

**Issue by BusterNeece** [ocaml/ocaml#8520]
Hello!

Some of our dependencies using OCaml have started to require a newer version than the one that ships out of the box with Ubuntu 16.04.

I know I can use OPAM to build a newer version of OCaml from source, but I distribute a piece of software that's self-installed by individual users and this causes the build times to skyrocket upwards of 15-20 minutes just for that one component. A prebuilt binary would be mighty convenient, but I haven't found any that are available for 16.04.

I figured I'd ask here to see if there were faster alternatives that I could use for users on 16.04. It isn't imperative that there be a faster solution, as most users of my software are on 18.04 or running the Docker version which builds all of this once and saves a lot of time.

**Comment by XVilka** [comment]
Both Debian and Ubuntu are terribly slow on updating many packages in line with mainstream. And OCaml is one of these: https://repology.org/project/ocaml/versions

If you don't want to compile OCaml toolchain from opam, I suggest you to use Alpine-based docker container, they recently updated to 4.07.1 version - see the link above.

P.S. Also I think this question doesn't really belong to GitHub and should have been asked on https://discuss.ocaml.org

**Comment by BusterNeece** [comment]
@SlvrEagle23 As I mentioned, the software I write is self-hosted on a number of different environments, and despite recommending 18.04 and Docker installation methods heavily, I still want to ensure those using other platforms aren't too heavily disadvantaged if I can help it. The question here was specifically for 16.04 as they're more affected in this situation than other users.

**Comment by XVilka** [comment]
@SlvrEagle23 you can try to build your binary statically, but it is highly experimental:
- https://discuss.ocaml.org/t/statically-link/1464/7
- http://rgrinberg.com/posts/static-binaries-tutorial/

**Comment by BusterNeece** [comment]
Per request, closing to move to the forum: https://discuss.ocaml.org/t/ocaml-available-via-ppa-on-ubuntu-16-04/3523
