### ISSUE TITLE
Soundness issue with class generalization

### ISSUE THREAD

**Issue by yallop** [ocaml/ocaml#8550]
There's a soundness issue with generalization of type variables in class definitions:

```ocaml
    # class ['a] r = let r : 'a = ref [] in object method get = r end;;
    class ['a] r : object constraint 'a = 'b list ref method get : 'a end
    # (new r)#get := [3];;
    - : unit = ()
    # List.hd !((new r)#get) ^ "two";;
    Segmentation fault
```

Bisecting shows that this has been around for a while: it was introduced in OCaml `4.00.0` along with GADTs (6c78f42d) for programs checked with `-principal` and more recently spread to programs without `-principal`, too (802945009).  Before these commits the program was rejected:

```
    Characters 0-63:
      class ['a] r = let r : 'a = ref [] in object method get = r end;;
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    Error: The type of this class,
           class ['a] r : object constraint 'a = '_b list ref method get : 'a end,
           contains type variables that cannot be generalized
```

**Comment by yallop** [comment]
@garrigue, you may like to take a look at this.

**Comment by garrigue** [comment]
I see. This code is utterly wrong: variables are only lowered if they are first reached through a contra variant branch! I don't know what I was drinking on that day.

**Comment by garrigue** [comment]
Actually the original code was not as absurd as I first thought, but partial generalization was probably a bad idea anyway. See #8552 for a proper solution.
