### ISSUE TITLE
with-syntax

### ISSUE THREAD

**Issue by kirillgla** [ocaml/ocaml#8553]
Hello. I'm about to try implementing with-syntax for OCaml patterns (https://github.com/ocamllabs/compiler-hacking/wiki/Add-a-%22with%22-syntax-for-patterns).

There is a branch dedicated to with patterns in OCaml compiler (https://github.com/ocamllabs/ocaml/tree/with-patterns). I wonder why it hasn't it been implemented? Are there any troubles associated with that?

Also, I was told in OCaml discord that camlwiki was grossly underestimating the difficulty of that task. Why so?

**Comment by gasche** [comment]
> I wonder why it hasn't been merged yet?

Probably because it was never submitted upstream in the first place.

This bugtracker is meant for tracking bugs (and polished feature requests). For general discussions on the language and its evolution, please use discussion channels instead -- IRC as you mention or [Discourse](https://discuss.ocaml.org/).

**Comment by kirillgla** [comment]
@gasche, I was told in Discord by @Drup to discuss this question on bugtracker

**Comment by Drup** [comment]
I did, but what I had in mind was, as @gasche would put it, "a polished feature request" that show the proposed addition and see if there is some support. Not everyone is familiar with ocamllab's feature wish list.

Also, the fork you posted doesn't have any actual patches in it.

**Comment by gasche** [comment]
Hi @kirillgla,

I apologize for being too abrupt in my first message above (it was in reply to the first version of your own message which was also somewhat abrupt). Two points:

- Anything that requires interleaving evaluation of terms with pattern-matching would be quite difficult to implement given the current state of the pattern-matching compiler, which is somewhat crufty and complex. (We are planning to rework it a bit, but it's a hard piece of code to change as regressions can introduce silent miscompilations.)
- The original `ocaml-patterns` implementation relies on expanding or-patterns to make it workable, which can result in an explosion of pattern sizes. It would be hard to convince the compiler to adopt this implementation strategy.
- Before trying to implement such a feature, a clear description of the design would be required. In particular, if the same expressions appears in two `with` parts, do we expect it to be evaluated twice, duplicating potential side-effects? (In general, how much do we know about when these expressions will be evaluated? Do we have guarantees that values that never touch this part of the pattern will not evaluate the `with`-expressions?)
