### ISSUE TITLE
Documentation OCaml release 4.08 - Broken links

### ISSUE THREAD

**Issue by Fourchaux** [ocaml/ocaml#8574]
Not sure if http://caml.inria.fr/pub/docs/manual-ocaml-4.08/index.html is the official site
but the following links are currently broken:

(500 Internal Server Error)
- Chapter 10: ... see the **Caml Hump** ...

(404 Not Found)
- Chapter 9: **Ast_mapper**
- Chapter 10: **Ast_mapper**
- Chapter 12: **Ast_mapper**
- Chapter 22: **Pparse module** - **Typemod module** - **Simplif module** - **Clflags module**
- Chapter 24: All links to **Module xxx**

**Comment by Octachron** [comment]
The caml hump page does seem broken. Moreover the corresponding paragraph could mention utop and link to https://opam.ocaml.org/ in place of the Caml Hump.

For the second part of the issue, this is a beta release bug that has been fixed during the first beta, but the manual has not be rebuilt yet.
