### ISSUE TITLE
Bug Tracker Redirect Chain Broken

### ISSUE THREAD

**Issue by dsmith47** [ocaml/ocaml#8589]
First, sorry for any formatting errors, I couldn't find styling guidelines  but I'd be happy to update for compliance.

Basically, clicking this link(copied exactly) from the README lands on a 404 error.

[http://caml.inria.fr/bin/caml-bugs](http://caml.inria.fr/bin/caml-bugs)

It looks like it was set up to redirect to the Mantis bug tracker, which in turn now redirects to the GitHub issue tracker, but it seems the redirecting page is `http://caml.inria.fr/mantis/`, while caml-bugs links to `http://caml.inria.fr/mantis` (missing the trailing slash).

Adding the trailing slash to the url seems to fix this.

**Comment by xavierleroy** [comment]
Thank you for reporting this issue.  The missing redirection was added, it should work now.
