### ISSUE TITLE
Install documention is incorrect

### ISSUE THREAD

**Issue by lleming** [ocaml/ocaml#8609]
The page is http://www.ocaml.org/docs/install.html.
command eval **`opam env`** not gonna work. 
result: 
    **opam: unknow command env**

most probably means
**opan config env**

**Comment by yallop** [comment]
Are you using Oᴘᴀᴍ 1.⋆?  The command `opam env` works with Oᴘᴀᴍ 2.

**Comment by gasche** [comment]
Hi @lleming,

Thanks for the report. This is not about the OCaml compiler distribution itself (the present repository), but an issue for the [ocaml/ocaml.org](https://github.com/ocaml/ocaml.org) project. (I'll be closing this one.)

I don't think that this is actually an issue: `opam env` is the correct command for opam 2.0 and later, and the page is explicit about the fact that it uses opam 2 ("Example using the Bash shell and opam-2.0").

You should probably try to update your programming environment to opam2, if you have control over it.

**Comment by lleming** [comment]
That is true. The default in the Ubuntu repository was opam 1.0.x  After upgrade to 2.x, the issue is gone.

**Comment by gasche** [comment]
Great! Thanks for the report and happy hacking.
