### ISSUE TITLE
[meta] Improving the buildability of the ecosystem with `trunk`

### ISSUE THREAD

**Issue by ejgallego** [ocaml/ocaml#8642]
Dear all,

I am opening this issue here as I couldn't locate a similar one and it seems to me it is most relevant to the compiler itself. I'm sure people is already working on this as I write, so of course feel free to close/redirect.

As we all know, as of today testing against the `trunk` branch is a difficult proposition, due mainly to the dependency on the compiler AST; this is a inconvenient in the current model of continuous developments. For example, in Coq, we test against against OCaml `trunk`, however, we must be very cautious on what we depend on.

The usual solution that I've seen proposed for this problem is to have the build system conserve certain build artifacts [such as PPX outputs] so the meta-generation is not needed in the `trunk` branch; however this is complex and in a few cases doesn't cut it [i.e. merlin]

What other alternatives are? IMVHO, it seems to me that the compiler itself should include a copy of the last version of the AST and mappings back and forwards _à la OMPT_.

That would impose the burden on PR authors that now would have to provide a mapping would they like to change the AST, but on the other hand it seems to me that it would relieve N projects from having to adapt each time a new version is released, which IMVHO seems like a very costly process.

WDTY?

Related:
- https://github.com/ocaml-ppx/ppxlib/issues/23
- https://github.com/ocaml-ppx/ocaml-migrate-parsetree/issues/50

**Comment by nojb** [comment]
Indeed, you have hit the nail on the head @ejgallego!

There is an ongoing project very much along the lines you suggest already in the works (spearheaded by @diml), see https://github.com/ocaml-ppx/ppxlib/wiki/roadmap-v1.

Because this is being tracked in the `ppxlib` repository, I will am closing this to focus discussion in the least number of places.

**Comment by ejgallego** [comment]
Ahh, I checked `ppxlib` issues but not the wiki; thanks @nojb
