### ISSUE TITLE
ocamldoc generates invalid html for object types in parameter lists, type parameters

### ISSUE THREAD

**Issue by wiml** [ocaml/ocaml#8645]
ocamldoc does not HTML-escape the left angle bracket (`<` → `&lt;`) when emitting documentation for object types in some circumstances, resulting in invalid HTML.

For example both of these declarations exhibit the problem:

```ocaml
val foo : int -> < bah : int -> int >

type  'a thing = < bar : ( < baz : int; .. > as 'a ); >
```
The problem doesn't seem to happen when generating html docs in a single shot, but these commands will demonstrate the problem if the above declarations are in `foo.mli`:

```bash
ocamldoc -dump foo.odoc -colorize-code foo.mli
mkdir -p somedocs
ocamldoc -load foo.odoc -colorize-code -html -d somedocs
```

**Comment by Octachron** [comment]
I don't see any difference between the html files generated directly with
```bash
ocamldoc foo.mli -html -colorize-code
```
and the one generated indirectly.

As far as I can see, the html backend only escapes `<` and `>` in the specialized path for the toplevel of a type declaration and not for generic type expressions.

**Comment by gasche** [comment]
@Octachron do you think this is an issue worth fixing, or should we decide to close as ocamldoc is on life support?

**Comment by Octachron** [comment]
I would say that the bug is sufficiently limited in scope to try to fix it. I will have a look.
