### ISSUE TITLE
OCaml build should provide a way to add extra $CFLAGS and $LDFLAGS

### ISSUE THREAD

**Issue by rwmjones** [ocaml/ocaml#8648]
Fedora (and I guess other Linux distros) want to add a standard set of hardening flags across the distribution, and they rely on `./configure` scripts obeying CFLAGS and LDFLAGS, eg:

```
./configure CFLAGS="-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection" LDFLAGS="-Wl,-z,relro   -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld"
```

However the OCaml `./configure` script doesn't do this.  I hacked the following into `configure.ac` and it works for me, although a better solution is to use autoconf's normal CFLAGS handling instead of the custom stuff.

```
diff --git a/configure.ac b/configure.ac
index 0bdb0e580..209a3cb32 100644
--- a/configure.ac
+++ b/configure.ac
@@ -549,6 +549,10 @@ AS_CASE([$host],
       internal_cflags="$gcc_warnings"],
     [common_cflags="-O"])])
 
+# Allow CFLAGS and LDFLAGS to be added.
+common_cflags="$common_cflags $CFLAGS"
+oc_ldflags="$oc_ldflags $LDFLAGS"
+
 internal_cppflags="-DCAML_NAME_SPACE $internal_cppflags"
 
 # Use 64-bit file offset if possible
```

**Comment by dra27** [comment]
Originally noted for `CFLAGS` and `LIBS` in https://github.com/ocaml/ocaml/pull/2139#pullrequestreview-182976019 on this.

**Comment by rwmjones** [comment]
I modified our downstream patch after studying the configure.ac file a bit more.  We now use:

https://pagure.io/fedora-ocaml/c/aab08177e52b9951b5e95c949c7b61c690a0efd7?branch=fedora-32-4.09.0

and now we configure OCaml using:

```
CFLAGS=... \
LDFLAGS=... \
./configure \
  OC_CFLAGS="$CFLAGS" \
  OC_LDFLAGS="$LDFLAGS" \
```

That has allowed us to pass the right flags not just to OCaml itself but also to programs that are then built with OCaml.  We are using annocheck to verify that the right flags are passed everywhere.

**Comment by glondu** [comment]
FYI, in Debian we use https://salsa.debian.org/ocaml-team/ocaml/blob/debian/sid/debian/patches/0013-Use-CCLINKFLAGS-for-linking-all-executables-and-shar.patch

**Comment by olafhering** [comment]
Cool, SUSE uses EXTRA_CFLAGS.
````diff
--- a/configure.ac
+++ b/configure.ac
@@ -1738,6 +1738,9 @@ AS_IF([test x"$DEFAULT_STRING" = "xunsaf
   [default_safe_string=false],
   [default_safe_string=true])

+# Allow user defined C Compiler flags
+common_cflags="$common_cflags $EXTRA_CFLAGS"
+
 oc_cflags="$common_cflags $internal_cflags"
 oc_cppflags="$common_cppflags $internal_cppflags"
 ocamlc_cflags="$common_cflags $sharedlib_cflags"
````

**Comment by dra27** [comment]
@rwmjones - just FYI looking at a related issue on opam-repository, the override you're using for `OC_LDFLAGS` and `OC_CFLAGS` isn't working - see the resulting definitions in `/usr/lib64/ocaml/Makefile.config`. `OC_CFLAGS` ends up as wanted because of your patch, but `OC_LDFLAGS` doesn't affect `configure`.

**Comment by dra27** [comment]
Also related to this (again, just brain-dumping!), some options are ending up in the wrong place (this from the Dune build of ocaml-r using F32 ocaml 4.10.0):

```
  ocamlmklib lib/math/dllOCamlR_math_stubs.so,lib/math/libOCamlR_math_stubs.a
Unknown option -Wl,--export-dynamic -fopenmp -Wl,-z,relro -Wl,--as-needed -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -L/usr/lib64/R/lib -lR -lRmath -lm
```

**Comment by rwmjones** [comment]
This is the rebased patch that Fedora carries against 4.13.1: https://pagure.io/fedora-ocaml/c/9966786a7389dc6621f2bc2dce7c690c5a38b67d?branch=fedora-36-4.13.1

**Comment by rwmjones** [comment]
Apparently I cannot remove the "stale" label, but I don't believe this bug is stale.  I tested it on 4.13.1 as follows (you're going to need a Fedora/RHEL system or something that has annotated binaries to do this).

With upstream OCaml 4.13.1:
```
./configure
make
```

```
$ annocheck ./ocamlopt.opt
[...]
Hardened: ocamlopt.opt: FAIL: pie test because not built with '-Wl,-pie' (gcc/clang) or '-buildmode pie' (go) 
Hardened: ocamlopt.opt: FAIL: cf-protection test because CET enabling note missing 
Hardened: ocamlopt.opt: FAIL: bind-now test because not linked with -Wl,-z,now 
Hardened: ocamlopt.opt: FAIL: fortify test because -D_FORTIFY_SOURCE=2 was not present on the command line 
Hardened: ocamlopt.opt: MAYB: test: notes because not all of the .text section is covered by notes 
Hardened: ocamlopt.opt: MAYB: test: lto because no indication that LTO was used 
```

With upstream OCaml 4.13.1, adding hardening flags:
```
./configure OC_CFLAGS="$(rpm --eval '%{optflags}')" OC_LDFLAGS="$(rpm --eval '%{__global_ldflags}')"
make
annocheck ./ocamlopt.opt
```

Same results as above.

With Fedora patch:

```
CFLAGS="$(rpm --eval '%{optflags}')" \
LDFLAGS="$(rpm --eval '%{__global_ldflags}')" \
./configure \
  OC_CFLAGS="$(rpm --eval '%{optflags}')" \
  OC_LDFLAGS="$(rpm --eval '%{__global_ldflags}')"
make
```

```
$ annocheck ./ocamlopt.opt 
annocheck: Version 10.02.
Hardened: ocamlopt.opt: FAIL: cf-protection test because CET enabling note missing 
Hardened: ocamlopt.opt: FAIL: notes test because gaps were detected in the annobin coverage 
```

Note that:
```
$ rpm --eval '%{optflags}'
-O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64  -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection
$ rpm --eval '%{__global_ldflags}'
-Wl,-z,relro -Wl,--as-needed  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 
```

**Comment by dra27** [comment]
There is some related work in https://github.com/ocaml/ocaml/pull/10413, but I don't think that addresses this issue. Is it the case in the build that you specify `CFLAGS` and `LDFLAGS` when calling `configure` but _not_ on the subsequent call to `make`? (clarifying my understanding, not suggesting any change!)

**Comment by dra27** [comment]
I _think_ that what we should be doing here is capturing `CFLAGS` and `LDFLAGS` in `configure` and using them as _defaults_ in the build system but also as a default when the compilers themselves call the C compiler/linker.

**Comment by rwmjones** [comment]
Yes we only pass CFLAGS and LDFLAGS to `./configure`.

https://src.fedoraproject.org/rpms/ocaml/blob/rawhide/f/ocaml.spec#_187

The `%confgure` macro expands to a very lengthy command which is rougly like:
```
CFLAGS=... LDFLAGS=... ./configure --libdir=/usr/lib64 ...
```

Edit: It would be possible to pass CFLAGS & LDFLAGS to make too, but we don't at the moment.

**Comment by dra27** [comment]
> I _think_ that what we should be doing here is capturing `CFLAGS` and `LDFLAGS` in `configure` and using them as _defaults_ in the build system but also as a default when the compilers themselves call the C compiler/linker.

Wait a minute! We are doing that since 4.12! Digging further...

**Comment by dra27** [comment]
With trunk in an F34 container, I'm doing (no patch):

```
CFLAGS="$(rpm --eval '%{optflags}')" \
LDFLAGS="$(rpm --eval '%{__global_ldflags}')" \
./configure
make
```
which gives:
```
[root@79d486b6445c ocaml]# annocheck ./ocamlopt.opt
annocheck: Version 9.79.
Hardened: ocamlopt.opt: FAIL: notes test because gaps were detected in the annobin coverage
Hardened: Rerun annocheck with --verbose to see more information on the tests.
```
(I don't know what the fail refers to - I have installed redhat-rpm-config). With a normal configure, I get this from annocheck:
```
annocheck: Version 9.79.
Hardened: ocamlopt.opt: FAIL: pie test because not built with '-Wl,-pie' (gcc/clang) or '-buildmode pie' (go)
Hardened: ocamlopt.opt: FAIL: bind-now test because not linked with -Wl,-z,now
Hardened: ocamlopt.opt: FAIL: notes test because gaps were detected in the annobin coverage
Hardened: Rerun annocheck with --verbose to see more information on the tests.
```

Isn't working for 4.12.0+, therefore?

**Comment by rwmjones** [comment]
The "gaps" error is the real problem here because it indicates that the whole binary hasn't been covered by the hardening flags.  Previously we decided that this was happening because of the statically linked code like the garbage collector.

Now looking back at my comment above, I see that my self-compiled Fedora OCaml + patch *has* the gaps error (bad).  However the real build does not have it the error (good):

```
$ rpm -qf /usr/bin/ocamlopt.opt 
ocaml-4.13.1-1.fc36.x86_64
$ annocheck /usr/bin/ocamlopt.opt 
annocheck: Version 9.87.
Hardened: ocamlopt.opt: FAIL: cf-protection test because CET enabling note missing 
Hardened: Rerun annocheck with --verbose to see more information on the tests.
```

(The cf-protection error is another thing but that requires proper compiler support in OCaml so we punted on it.)

So at the moment I'm not exactly sure why my local build and the real Fedora build are different.

**Comment by rwmjones** [comment]
BTW we asked the compiler team if they could extend annocheck to print some symbols from the non-hardened parts of the binary and they will implement that in a future version.

**Comment by rwmjones** [comment]
BTW#2 you can run annocheck on `*.o` and `*.a` files.  For example `annocheck runtime/libasmrun.a` tells me that the runtime is all good except for the assembler file (`amd64.o`).  It would be possible to add some suppressions into the asm file to fix this, although I don't know if that's a good idea or not (since the assembler presumably would never have that hardening).

**Comment by dra27** [comment]
It does appear to be the assembler:

```
[root@b75e895160f9 ocaml-hardened]# annocheck ./ocamlc.opt --verbose
...
Hardened: ./ocamlc.opt: gap:  (0x2a17f0..0x533050 probable component: caml_startup__code_begin) in annobin notes.
Hardened: ./ocamlc.opt: gap:  (0x55c410..0x55c760 probable component: caml_alloc1) in annobin notes.
Hardened: ./ocamlc.opt: FAIL: notes test because gaps were detected in the annobin coverage
```
and
```
[root@b75e895160f9 ocaml-hardened]# annocheck ./ocamlopt.opt --verbose
...
Hardened: ./ocamlopt.opt: gap:  (0x3887e9..0x3913c0 probable component: caml_program) in annobin notes.
Hardened: ./ocamlopt.opt: gap:  (0x3ba780..0x7158f0 probable component: camlInternal_variable_names__anon_fn_with_loc_548) in annobin notes.
Hardened: ./ocamlopt.opt: FAIL: notes test because gaps were detected in the annobin coverage
Hardened: ./ocamlopt.opt: info: not all of the .text section is covered by notes.
```

In both cases, the first symbol is one in the startup object (which is assembled) and the other is either in the assembler portion of the runtime (`caml_alloc1`) or definitely a symbol generated by the backend for assembly.

Before reading the manual, I tried with a build which assembles everything using `gcc -c` but that changes nothing... but that's consistent with the manual for annobin. I gather there are annotations which could be added to the assembler files.

**Comment by dra27** [comment]
@rwmjones - I'm not totally sure what the status of this is... I think that we do now allow the flags to be passed through the build correctly, but it's possible that there are some additional flags needed for the assembler, still? Is this still an issue with 4.14 in F37?

**Comment by shindere** [comment]
This is supposed to work now.

```
./configure CFLAGS="-foo -bar" LDFLAGS="-lbaz -L/some/dir"
```

Beware that passing the variables to make rather than to the configure
script is not possible. Neither should they be defined as
environment variable. The only supported way is the one shown above.

**Comment by rwmjones** [comment]
I will try that next time we do a Fedora build.  We are currently carrying a "dubious" patch to support setting the hardening flags, which I'm quite keen to drop:

https://pagure.io/fedora-ocaml/commits/fedora-38-4.14.0

**Comment by shindere** [comment]
rwmjones (2022/10/26 07:18 -0700):
> I will try that next time we do a Fedora build.

Please! And feel free to report any problem, I'll be eager to fix.

> We are currently carrying a "dubious" patch to support setting the hardening flags, which I'm quite keen to drop:
>
> https://pagure.io/fedora-ocaml/commits/fedora-38-4.14.0

That shouldn't be necessary any longer, hopefully. I am sorry the issue
had not been closed properly when the PR fixing it got merged. To be
precise, see PR #9837 for CFLAGS and PRs #9191, #10091 and #10182 for
LDFLAGS. Also see commit 84538f7521cbca5ad95f76efd2080fee97acc2f9.
