### ISSUE TITLE
README.win32.adoc: Support for Visual Studio 2019

### ISSUE THREAD

**Issue by jakoblichtenberg** [ocaml/ocaml#8655]
It would be nice if next version of Visual Studio had explicit support for Visual Studio 2019.  I tried this out and it works great for me with ocaml-4.08.0+beta3 .

For example the simplest version called "Visual Studio Build Tools 2019" available from https://visualstudio.microsoft.com/downloads/ .

Reference: https://github.com/ocaml/ocaml/blob/trunk/README.win32.adoc

**Comment by dra27** [comment]
Please feel free to make a pull request with the change!

**Comment by jakoblichtenberg** [comment]
David. Done.   

https://github.com/ocaml/ocaml/pull/8662 .  

Two disclaimers: 

First I have not done PRs to ocaml before, so if there are issues with how my PR is submitted I apologize and put me straight..

Second. I do not know what the proper test process for changing the build environment is (in this case upgrading compiler).  I just know that things seems to work fine for my specific case.

**Comment by jakoblichtenberg** [comment]
@dra27 , @nojb : Can I ask for help please.  What do I need to do to get this moved forward please? Who completes the PR?  Am I targeting the right branch?

**Comment by nojb** [comment]
PR merged, thanks!

**Comment by jakoblichtenberg** [comment]
@nojb .  Thank you.  Sorry for the newbie question, but I see this made it to main trunk, but it looks like 4.08 and 4.09 branches are already snapped.  Should I have targeted those branches also?  Is there any sort of integration ongoing automatically?   In other words: What actions should I take to make sure this change shows up in all future public releases of ocaml?

**Comment by xavierleroy** [comment]
Yes, we should have the fix in 4.09.  The release of 4.08 is imminent (as in: tomorrow), so let's leave it alone.

**Comment by jakoblichtenberg** [comment]
1. I specifically made the ask so as to get this into the next “official release” that is 4.08 that I have been testing with for many weeks now

2. Given this is a “doc only change” I would imagine it can easily make it to both 4.08 and 4.09.

3. I apologize if I staged the PR the wrong way at first.  I asked for help on this matter early exactly to avoid misunderstandings.

Thank you all for your consideration.

PS. The more important question (that we’ll leave for another day) is how test automation actually ensure various build environment in practice works.  At this point only thing I can state is that “it seems to work well for me”.

**Comment by nojb** [comment]
Cherry-picked to 4.09 in 7cb57b0309f4260bcbdb0cc9f7c383877a0cb000

**Comment by nojb** [comment]
> PS. The more important question (that we’ll leave for another day) is how test automation actually ensure various build environment in practice works. At this point only thing I can state is that “it seems to work well for me”.

In the CI we test that everything works with Visual Studio 2015. For other versions, we go with "it seems to work well for me".

**Comment by jakoblichtenberg** [comment]
@nojb and @xavierleroy please see my request to include this fix in 4.08. Thank you for your consideration.

**Comment by nojb** [comment]
> @nojb and @xavierleroy please see my request to include this fix in 4.08. 

As Xavier mentioned,

> The release of 4.08 is imminent (as in: tomorrow), so let's leave it alone.

**Comment by jakoblichtenberg** [comment]
OK.
