### ISSUE TITLE
INSTALL.adoc should be updated to new configure options in 4.08

### ISSUE THREAD

**Issue by gasche** [ocaml/ocaml#8658]
The INSTALL.adoc file is out of date, mentioning old configure options like `-no-shared-libs`, `no-curses`, `-{no,with}-pthread`, etc. I think that we (preferably the people that are familiar with the new configure, cc @shindere and @dra27) should update it to mirror the new configuration options -- it could also mention `./configure --help` that I'm not sure existed before.

**Comment by gasche** [comment]
I believe this is a blocker for the release.

**Comment by shindere** [comment]
Gabriel Scherer (2019/05/07 05:51 -0700):
> I believe this is a blocker for the release.

It is. Starting to work on a PR right now.

**Comment by dra27** [comment]
@shindere - have you been able to prepare this? I can work it right now, if needed.

**Comment by shindere** [comment]
David Allsopp (2019/05/21 03:15 -0700):
> @shindere - have you been able to prepare this? I can work it right
> now, if needed.

Yes, I started to work on it but it's actually a bit of work because
this file is REALLY outdated.

@dra27: do you still have your mapping between old and new configure
options? If so it would be great to incude it somewhere.

**Comment by damiendoligez** [comment]
fixed by #8688
