### ISSUE TITLE
z/OS platform support

### ISSUE THREAD

**Issue by XVilka** [ocaml/ocaml#8671]
OCaml already supports SystemZ architecture, but only for Linux operating system. It would be awesome to make it work on the z/OS itself as well. z/OS is a 64-bit operating system for IBM mainframes, produced by IBM. It derives from and is the successor to OS/390, which in turn followed a string of MVS versions. Like OS/390, z/OS combines a number of formerly separate, related products, some of which are still optional. z/OS offers the attributes of modern operating systems but also retains much of the functionality originating in the 1960s and each subsequent decade that is still found in daily use (backward compatibility is one of z/OS's central design philosophies). 

https://www.ibm.com/it-infrastructure/z/zos

See also the discussion here: https://discuss.ocaml.org/t/ocaml-and-z-os-is-there-any-port/3802

**Comment by XVilka** [comment]
Recently Travis CI added System Z and PPC64LE support, see [Build your open source projects on IBM Power and IBM Z CPU architecture](https://blog.travis-ci.com/2019-11-12-multi-cpu-architecture-ibm-power-ibm-z) blog post.

**Comment by xavierleroy** [comment]
Thanks for the tip concerning Travis.  We already have PPC64LE and zSystems machines in our CI, running Linux, like the Travis offering.

As to supporting z/OS: I am very much not in favor.  We currently support one non-Unix OS, namely MS Windows, and it's a huge burden.  At least there are users.  z/OS looks like another huge burden, and it is unclear anyone wants to run OCaml on it.

**Comment by xavierleroy** [comment]
Six months later, I'm still not in favor.  Let me close this issue.
