### ISSUE TITLE
When debugging processes which create OCaml child processes, the child tries to talk to the parent's debugger (and dies)

### ISSUE THREAD

**Issue by MSoegtropIMC** [ocaml/ocaml#8678]
Dear OCaml Team,

I am trying to debug some issues in a OCaml GTK application (CoqIDE) on Windows. I am using ocaml-4.07.1 build from sources.

The issue is that the application creates child processes which are also written in OCaml. These processes inherit the environment from the parent, including a `CAML_DEBUG_SOCKET=127.0.0.1:10172` which I guess was added to the environment of the parent by ocamldebug. In the child process `caml_main` calls `caml_debugger_init` which checks for `CAML_DEBUG_SOCKET`. If it is there, the child establishes a connection to the debugger. Opening the sockets seems to work. But then a bit later in `caml_main` calling `caml_debugger(PROGRAM_START)` fails with `exception Sys_error("Invalid argument")` and pretty much everything hangs (the debugger, the child, the parent).

How is this supposed to work? I guess one instance of ocamldebug does not support debugging two processes at a time, so the child process should not talk to the parent's debugger. Should there be some mechanism to prevent this (which then doesn't seem to work on Windows), or is debugging programs which create child processes written in OCaml generally not supported?

Is it maybe so that on Linux the debugger sets up the debug socket such that only one client can connect and further connection attempts fail?

Best regards,

Michael

**Comment by MSoegtropIMC** [comment]
Digging a bit deeper into this: in `debugger\program_management.ml` the listen command of ocamldebug reads:

      let sock = socket sock_domain SOCK_STREAM 0 in
        (try
           bind sock sock_address;
           setsockopt sock SO_REUSEADDR true;
           listen sock 3;

So the maximum connection number is 3. As far as I remember ocamldebug creates two levels of checkpoint forks on Linux (although I thought it creates many of them). Can it be that these 3 connections are for the main connection and two checkpoint connections, so that all connections are usually already used up when a child is created? On Windows that wouldn't be the case because there are no checkpoint forks.

**Comment by jhjourdan** [comment]
Normally, the debugger runtime contains some cod which deactivates the debugger for the forked child.

Is the child process created using a C call to fork? Or is it using an OCaml-side call to fork using the Unix library?

**Comment by MSoegtropIMC** [comment]
The child is created from OCaml like this:

    ide/coq.ml:

    let oc,ic,ec = Unix.open_process_full cmd (Unix.environment ()) in

**Comment by MSoegtropIMC** [comment]
I scanned the code for mechanisms which could prevent children from connecting to the debugger, but I didn't find any.

- Searching the code for CAML_DEBUG_SOCKET shows that this environment variable is set, but it is not removed which children are created.
- The number of connections to the debugger socket is set to 3 in listen, which would allow 3 connections.
- There is nothing (obvious) in the protocol to tell a process after connection, that the debugger is not debugging it.

Interestingly the issue is that the child tries to connect but fails to do so properly. The connect succeeds but subsequent reads from the debugger socket fail. On the debugger side I don't see an accept for the connect succeeding on the client side. This is clearly contrary to the MSDN winsock documentation for connect, which says that if connect returns without error, the connection is established. For non blocking connections where it cannot be told upfront if the connection is successful, the doc says that connect always returns an error. Maybe this is something around that the child inherited a socket from the parent?

The failure is way hard to hack around, because the stream read abstraction used by the debug client does not return an error but throws an error and I don't know how to do a try for OCaml exceptions on C level.

**Comment by MSoegtropIMC** [comment]
I spent a bit more time on this. Actually the connection between the child process and the debugger does succeed (some stderr traces I inserted seem to get lost somehow) and the child process receives the same list of REQ_SET_EVENT from the debugger as the parent process (although they are different binaries, so that this doesn't make a lot of sense). The child then hangs because it doesn't receive a REQ_GO from the debugger.

I would now need some information about what is supposed to happen here.

Some review notes on the Windows implementation of debugger.c:

- debugger.c does `#include <winsock.h>` while win32.c does `#include <winsock2.h>`. I would say it is sheer luck that this works at all since one links with one or the other library and the prototypes have subtle differences (it wouldn't link with C++ because parameter types are different, but it does link with C). Possibly this is the reason why we have stability issues with CoqIDE on Windows. I need to check which library is actually linked and if stability improves if one uses the matching header everywhere.

- In debugger.c the line `dbg_socket = socket(sock_domain, SOCK_STREAM, 0);` shouldn't type check because `dbg_socket` is a 32 bit integer but socket returns a 64 bit integer (on 64 bit Windows). But this is not that bad because the integers are about 4* the number of open files in the system, so unless one has 10^9 open files or sockets it should work. Still it is not nice. Btw.: gcc ignores 64 bit to 32 bit truncation even with -Wall. One needs -Wconversion to flag such things. Since 64 bit Windows is rather messy (integers are 32 bit, pointers are 64 bit) one might think about compiling the C part of the OCaml library and runtime with -Wconversion.

- In debugger.c, dbg_in and dbg_out don't have the CHANNEL_FLAG_FROM_SOCKET flag set and thus are using normal file read and write rather than recv and send (see caml_read_fd in win32.c). It is quite interesting that this actually does work. The Windows `_open_osfhandle` function used to create these handles in debugger.c might be more powerful than one might think (the documentation is sparse). It seems to be able to convert socket handles into file handles which work with read and write. But if it also works for other functions taking file handles is an interesting question. If so, one might use this to get rid of the issues in the standard library because socket handles and file hdnales are incompatible in Windows (unlike Unix). E.g. the versions of lablgtk2 and lablgtk3 have some hacky patches cause of this since years (and they remain hacky patches because it is not so obvious how this could be fixed).

One more thing I don't understand: How does it happen that `open_connection` in `program_management.ml` accepts more than one connection? I see only one accept after the listen 3 but magically it does accept two connections. I also put in traces there and I see the traces only once, but I definitely see the debugger requests arriving in parent and child. And yes, I am sure that I have only once instance of ocamldebug running and both parent and child process talk to the same port number.

@xavierleroy : since debugger.c was originally written by you, maybe you can shed some light on the question how it should be prevented that child processes inheriting the `CAML_DEBUG_SOCKET` variable from a parent don't connect to the debugger, or still work if they do.

**Comment by jhjourdan** [comment]
Probably the simplest thing to do in order to fix the bug is to reset the `CAML_DEBUG_SOCKET` environment variable just after reading it.

**Comment by MSoegtropIMC** [comment]
> Probably the simplest thing to do in order to fix the bug is to reset the `CAML_DEBUG_SOCKET` environment variable just after reading it.

A good idea. I thought about removing it when starting child processes, but there are scenarios where one wants to debug both and explicitly passes a different `CAML_DEBUG_SOCKET` to the child process. But removing it at the point you suggest wouldn't hurt in this scenario. One thing I didn't look into is the communication of checkpoint fork processes with the debugger, since this anyway doesn't work on Windows. Is it possible that checkpoint forks need this environment variable later?

An important question remains: is there already some mechanism to prevent this which simply doesn't work on Windows? If so I would prefer to fix this existing mechanism instead of implementing a new one. I find it hard to believe that debugging processes which create child processes written in OCaml did never work, even on Linux.

P.S.: what I wrote above about winsock / winsock2 link compatibility with C++ is of cause wrong. Linking the wrong library doesn't (always) give errors in C++ either since it is still a C library without name decoration.

**Comment by jhjourdan** [comment]
> One thing I didn't look into is the communication of checkpoint fork processes with the debugger, since this anyway doesn't work on Windows. Is it possible that checkpoint forks need this environment variable later?

I don't think this is an issue: the checkpoint fork does not read the environment variable again, but rather inherits from its value stored in `dbg_addr`.

> An important question remains: is there already some mechanism to prevent this which simply doesn't work on Windows? If so I would prefer to fix this existing mechanism instead of implementing a new one. I find it hard to believe that debugging processes which create child processes written in OCaml did never work, even on Linux.

I can confirm that weird things do happen when calling an OCaml program in a program under `ocamldebug` control, even under Linux. I did not reproduce your specific behavior, though.

**Comment by MSoegtropIMC** [comment]
> I can confirm that weird things do happen when calling an OCaml program in a program under `ocamldebug` control, even under Linux. I did not reproduce your specific behavior, though.

Ok, then I will do the fix you suggested and try it on Windows and if it works fine (I have quite a bit of opportunity to test it) I will do a PR.

**Comment by xavierleroy** [comment]
There's a minimal fix in pull request #9594.  

The Windows parts of `runtime/debugger.c` are dated and would deserve some cleaning up, but they should still work.  Note in particular that the sockets are opened in synchronous mode.
