### ISSUE TITLE
Support symlinks without elevation on Windows 10 in Developer Mode

### ISSUE THREAD

**Issue by manu-unter** [ocaml/ocaml#8680]
In Windows 10, it has been possible since 2016 to enable Developer Mode which [allows symbolic links to be created without elevation](https://blogs.windows.com/buildingapps/2016/12/02/symlinks-windows-10/). This would be a great feature to support in many applications - specifically we could use it for the package manager esy. See https://github.com/esy/esy/issues/389

I think it would be rather easy to support this. We will need to pass a new flag - `SYMBOLIC_LINK_FLAG_ALLOW_UNPRIVILEGED_CREATE` - to CreateSymbolicLink in this piece of code
https://github.com/ocaml/ocaml/blob/28c337fecbebfc064c06ae0ba35a1107b0b58493/otherlibs/win32unix/symlink.c#L39
so that the symlinks will be created without an elevated shell.

Maybe some small changes to `has_symlink` might be required as well, but I can't tell yet because I haven't fully understood the privileges logic that is used there.

Would you be accepting PRs for making these changes?

**Comment by dra27** [comment]
This has been on my spike for a while, so a PR would be welcome - the only caveat would be that it needs to remain compatible. I expect it will involve a patch to the has_symlink code too.
