### ISSUE TITLE
undocumented OCAMLRUNPARAM settings

### ISSUE THREAD

**Issue by gasche** [ocaml/ocaml#8697]
http://caml.inria.fr/pub/docs/manual-ocaml/runtime.html contains a documentation of most OCAMLRUNPARAM settings, but several are missing:

- H (huge pages)
- M, m, n (custom space usage stuff)
- t ("trace level"?)
- w (caml major window size)
- W (runtime warnings)

**Comment by wylinelove** [comment]
JS每日一题: 小程序跳转页面有几种方式？ 有什么不同?
原创： qdmryt JS每日一题 3月1日

20190228
小程序跳转页面有几种方式？ 有什么不同?

在小程序中每个页面可以看成是一个pageModel，pageModel全部以栈的形式进行管理(最多十层)

在说跳转方式之前我们先来温习一下栈和堆的区别

管理方式不同
栈是系统编译器启动管理，不需要程序员手动管理

堆的释放由程序员手动管理，不及时回收容易产生内存泄露

分配方式不同
栈有两种分配方式：静态分配和动态分配

静态分配是系统编译器完成的，比如局部变量的分配

动态分配是由alloc函数进行分配的，但是栈的动态分配和堆的动态分配是不同的，它的动态分配也由系统编译器进行释放，不需要程序员手动管理

堆是动态分配和回收内存的，没有静态分配的堆

分配大小不同
栈是向低地址扩展的数据结构，是一块连续的内存区域

堆是向高地址扩展的数据结构，是不连续的内存区域

进入正题
小程序的路由跳转分为两种，组件跳转以及api跳转

api形式分为

navigateTo 保留当前页面，跳转到应用内的某个页面，使用wx.navigateBack可以返回到原页面

redirectTo 关闭当前页面，跳转到应用内的某个页面

switchTab 跳转到tabBar页面,同时关闭其他非tabBar页面

navigateBack 返回上一页面

reLanch 关闭所有页面，打开到应用内的某个页面

前面有提到栈，那么这些导航方式跟栈有什么关系呢,看下面

初始化 新页面入栈

navigateTo 新页面入栈

redirectTo 当前页面出栈，新页面入栈

navigateBack 页面不断出栈，直到目标返回页，新页面入栈

switchTab 页面全部出栈，只留下新的 Tab 页面

reLanch 页面全部出栈，只留下新的页面

通过组件形式进行跳转

// navigator 组件默认的 open-type 为 navigate 

<
navigator url
=
"/page/navigate/navigate?title=navigate"
>跳转到新页面</
navigator
>



// 如需要其它形式进行跳转，可以更改open-type 属性以上api值

<
navigator url
=
"/page/navigate/navigate?title=navigate"
 open
-
type
=
"switchTab"
>切换
 
Tab
</
navigator
>

getCurrentPages
getCurrentPages() 函数用于获取当前页面栈的实例(属性及方法)，以数组形式按栈的顺序给出，第一个元素为首页，最后一个元素为当前页面

// Page A 跳转至Page B

wx
.
navigateTo
({
 url
:
 
'/pages/B/B'
 
})



// Page B

const
 pages 
=
 getCurrentPages
()

const
 perPage 
=
 pages
[
pages
.
length 
-
 
2
]
 
// 上一个页面

perPage
.
setData
({

    title
:
 
'JS每日一题'

})

**Comment by shubhi2000** [comment]
Hey! I am an Outreachy applicant. Should I work on this issue as my first contribution? @lthls @Octachron

**Comment by gasche** [comment]
I think that whether this is a good first issue or not depends on how familiar you are with the OCaml compiler, or language implementations in general. If you have no experience with language runtimes, it could be difficult to come up with the missing documentation for these items (my best idea for how to proceed is to read the source code, and figure out from there what they are doing).

If you (or someone else) decide to work on this issue, I would recommend sending a separate PR for each item that you propose for the documentation, instead of trying to cover "everything" in a single PR. These documentation PRs tend to generate some discussion with a lot of rewording suggestions, so it helps to keep the scope of each PR small.

**Comment by shubhi2000** [comment]
@gasche Thank you for your insight.
I am new to OCaml. I am currently working on exploring the language. 
I would like to give it a try so that I could learn about language runtimes in the process.

**Comment by shubhi2000** [comment]
@gasche Can you please also suggest the directory in which I can find the associated source code?

**Comment by gasche** [comment]
That's a good question, thanks. To answer this sort of questions I usually `git grep`, as a way to look for a word (or pattern) in the whole codebase of a git repository. `git grep OCAMLRUNPARAM` returns the set of line talking about OCAMLRUNPARAM, and one can use, say, `-C 4` to get a bit of context around each occurrence, to get a chance of understanding the usage (this shows 4 lines before and after each occurrence).

`git grep OCAMLRUNPARAM` on a fresh OCaml repository checkout contains in particular the following line

```
runtime/startup_aux.c:/* Parse the OCAMLRUNPARAM environment variable. */
```

which indicates that the parsing is done in `startup_aux.c`. From there one can locate the parsing code:

```c
void caml_parse_ocamlrunparam(void)
{
  char_os *opt = caml_secure_getenv (T("OCAMLRUNPARAM"));
  uintnat p;

  if (opt == NULL) opt = caml_secure_getenv (T("CAMLRUNPARAM"));

  if (opt != NULL){
    while (*opt != '\0'){
      switch (*opt++){
      case 'a': scanmult (opt, &p); caml_set_allocation_policy ((intnat) p);
        break;
      case 'b': scanmult (opt, &p); caml_record_backtrace(Val_bool (p));
        break;
      case 'c': scanmult (opt, &p); caml_cleanup_on_exit = (p != 0); break;
      case 'h': scanmult (opt, &caml_init_heap_wsz); break;
      case 'H': scanmult (opt, &caml_use_huge_pages); break;
      case 'i': scanmult (opt, &caml_init_heap_chunk_sz); break;
      case 'l': scanmult (opt, &caml_init_max_stack_wsz); break;
      case 'M': scanmult (opt, &caml_init_custom_major_ratio); break;
      case 'm': scanmult (opt, &caml_init_custom_minor_ratio); break;
      case 'n': scanmult (opt, &caml_init_custom_minor_max_bsz); break;
      case 'o': scanmult (opt, &caml_init_percent_free); break;
      case 'O': scanmult (opt, &caml_init_max_percent_free); break;
      case 'p': scanmult (opt, &p); caml_parser_trace = (p != 0); break;
      case 'R': break; /*  see stdlib/hashtbl.mli */
      case 's': scanmult (opt, &caml_init_minor_heap_wsz); break;
      case 't': scanmult (opt, &caml_trace_level); break;
      case 'v': scanmult (opt, &caml_verb_gc); break;
      case 'w': scanmult (opt, &caml_init_major_window); break;
      case 'W': scanmult (opt, &caml_runtime_warnings); break;
      }
      while (*opt != '\0'){
        if (*opt++ == ',') break;
      }
    }
  }
}
```

One can see a list of options supported in the current OCaml `trunk` (development version / master), and see where it differs from the manual. For any of these options that one would like to document, I would recommend doing a `git grep` again to see where it is defined (if we are lucky there might be a code comment to explain what the option does) and how it is used. (Try `git grep -C5 caml_runtime_warnings` to understand what `W` does, for example.)

**Comment by shubhi2000** [comment]
Thank you so much, @gasche ! This is so helpful.

**Comment by Anukriti12** [comment]
Hi, I am an outreachy applicant. Can i work on this issue?

**Comment by gasche** [comment]
We haven't had news from @shubhi2000 who was also interested in working on this issue. It may be ok for @Anukriti12 to work on it, but maybe @shubhi2000 has feedback/questions that we could help with? (@Anukriti12 was also interested in #7141.)

**Comment by shubhi2000** [comment]
I am very sorry for not being able to update! I am facing some serious internet connectivity issues in my area. I'll try to get back soon.
Surely, @Anukriti12 can work on this if she wants.

**Comment by Anukriti12** [comment]
This is the document I prepared as far as my understanding so far. Let me know about accommodating changes.

-H: Allocates heap chunks by mmapping huge pages. Huge pages are locked into memory, and are not swapped.
-M: Print the magic number expected by this version of the runtime and exit.
-n: Intialize custom maximum size of custom objects counted as garbage in the minor heap.
-m: Print the magic number of the bytecode executable given as argument and exit.
-t: Increments debug trace level (ignored unless debug mode)
-w: Sets size of window used by major GC for smoothing out variations in its workload. This is an integer between 1 and 50. (Default: 1)
-W: Activates runtime warnings such as - Channel opened on file dies without being closed, unflushed data, etc.

**Comment by gasche** [comment]
@Anukriti12 this looks fairly good, thanks!

For `-M`, you should clarify that we are talking about the magic number of bytecode executables (there are other kinds of magic number in the runtime). Maybe just saying `expected for bytecode executable` would work.

For `-n`, I don't understand the explanation. (We could look more into what it does to clarify this, but you could also drop this one flag from a first PR; we don't need to document everything at once.)

For `-W`, I would put the examples after "such as" inside parentheses, rather than after a dash.

**Comment by Aman9026** [comment]
Hi @gasche ! I'm an outreachy applicant, I want to work on this issue.
M, m, n is already added to [runtime system doc](http://caml.inria.fr/pub/docs/manual-ocaml/runtime.html) should I add the remaining to ocamlrun.m and runtime.etex?

**Comment by gasche** [comment]
@Aman9026 thanks for your interest!

We want each option to be documented in the manual *and* in the manpages (in the manpages the description can be brief). If `M`, `m`, `n` are not in the manpages, they should be added as well.

Last year @Anukriti12 proposed a PR to fix this issue, #9398. According to @dra27 who made a detailed review, the proposed PR is "very nearly there", but @Anukriti12 seems to be working on other things and did not complete the PR. If you want to work on this topic, I would recommend starting from @Anukriti12's PR, making the changes recommended by @dra27 [there](https://github.com/ocaml/ocaml/pull/9398#pullrequestreview-395559583), and submitting this as a new PR.

Note: if you are not familiar with Github more advanced aspects, here are some details. You can start working on top of @Anukriti12's PR by:

- cloning the OCaml git repository
- creating a branch for this work
- downloading https://patch-diff.githubusercontent.com/raw/ocaml/ocaml/pull/9398.patch in your repository
- running `git am 9398.patch`

This should have the effect of "applying" the PR on top of your current branch. (There may be conflicts to solve.) Then you can perform changes and store them as new commits, and submit a PR. (In particular there is no worry about credits/attribution, the commits of both contributors will be attributed to themselves.)

**Comment by Aman9026** [comment]
Great :smile:, I got to learn a lot about patching. There are a few things that need to be updated to patch perfectly, I'm working on them.

**Comment by damiendoligez** [comment]
@Aman9026 are you still working on this?

**Comment by kirisky** [comment]
Hi! I'd like to take this issue.

**Comment by gasche** [comment]
Yes, please feel free. My [previous comment](https://github.com/ocaml/ocaml/issues/8697#issuecomment-812494226) contains explanations on how to proceed.
