### ISSUE TITLE
Variables in exported Makefile.config contain calls to macros

### ISSUE THREAD

**Issue by garrigue** [ocaml/ocaml#8703]
The `Makefile.config` exported by OCaml 4.08.0+rc1 contains calls to macros.
This prevents easy extraction of variables using grep, as it was done in labltk for instance.

**Comment by dra27** [comment]
This is a consequence of the switch to autoconf, and next to impossible to workaround.

The solution I see you've committed in https://github.com/garrigue/labltk/commit/390c2c88ec82470b0c571fc5558b382224548823 is the template for this, and elsewhere.

The other option might be to do something to "simplify" the `Makefile.config` file which is installed, but it feels like we've missed the boat for that only picking up on it during the RC stage of 4.08.

**Comment by xavierleroy** [comment]
The workaround (include Makefile.config rather than grep through it) is fine. I'm closing this PR.
