### ISSUE TITLE
Native code segfault with 4.08

### ISSUE THREAD

**Issue by bacam** [ocaml/ocaml#8705]
We've noticed that the [Lem specification tool](https://github.com/rems-project/lem) segfaults with the 4.08.0+rc1 compiler, when the build first tries to run the generated executable on Lem's standard library.  It only appears to happen for native code (testing with 64-bit and 32-bit x86 Linux), and bisecting suggests that commit 9b27a9c75ec4c76a7d9e440de29c203666ea6a28 introduces the problem.  Indeed, if I revert that commit in 4.08.0+rc1 Lem runs without faulting.

The top of the stack trace isn't terribly revealing:
```
#0  0x00005555558454c7 in camlStdlib__map__mapi_284 () at map.ml:306
#1  0x00005555558454d8 in camlStdlib__map__mapi_284 () at map.ml:310
#2  0x00005555557f70af in camlTyped_ast__exp_to_free_2768 () at finite_map.ml:111
#3  0x0000555555784d34 in camlPatterns__mk_opt_let_exp_1686 () at patterns.ml:1044
```
The call to `mapi` in the `exp_to_free` function is [here](https://github.com/rems-project/lem/blob/master/src/typed_ast.ml#L1273).  From experimenting with a large minor heap using `OCAMLRUNPARAM` and reducing the input size a bit it seems that the problem can be triggered without any GC activity.

If you want to try reproducing this, only ocaml, ocamlbuild and lem are needed.  Lem's other dependencies are only used later in the build process.

**Comment by mshinwell** [comment]
I'm looking at this.

**Comment by mshinwell** [comment]
Please see https://github.com/ocaml/ocaml/pull/8706
