### ISSUE TITLE
Heap initialization function in memory.h not doing anything

### ISSUE THREAD

**Issue by jflopezfernandez** [ocaml/ocaml#8709]
I was going through `memory.h` when I came across a function that according to its documentation is supposed to initialize the heap.

```C
int caml_init_alloc_for_heap(void);
```
As it is currently written, however, the function looks like this:

```C
/* Initialize the [alloc_for_heap] system.
   This function must be called exactly once, and it must be called
   before the first call to [alloc_for_heap].
   It returns 0 on success and -1 on failure.
*/
int caml_init_alloc_for_heap (void)
{
  return 0;
}
```
There is no heap initialization of any kind, and it is called on line `637` of `gc_ctrl.c` like this:
```C
if (caml_init_alloc_for_heap () != 0){
  caml_fatal_error( "cannot initialize heap: mmap failed");
}
```
The function is unconditionally returning zero, so it's obviously never going to fail. My question is, is it okay to simply remove it then, as it's just dead weight in the code base? Or is the call to `mmap` that is being referenced actually supposed to be there, and just never got implemented?

**Comment by mshinwell** [comment]
It looks like this has been fixed (#8710).
