### ISSUE TITLE
Feature wish: move Pervasives.(format_of_string, (^^)) into Format module or a separate module

### ISSUE THREAD

**Issue by bobzhang** [ocaml/ocaml#8717]
Steps: We can first mark it as deprecated and removed it after several releases

Reasons: those two functions are rarely used, it incurs a non-trival dependency on camlinternalFormatBasics which requires a huge runtime. The consequences is that
it can make js backend output big js output by accident.
Note it could be dead code eliminated in theory, but third party js tools in general can not handle it

**Comment by dra27** [comment]
A quick GitHub search suggests "rarely" may want quantifying. It'd have to be to a separate module, as I'm fairly sure `Scanf`, `Printf` and `Format` are presently independent and want to remain so, and obviously the types would want to move wholesale to a new module.

Personally not that convinced - if JS tools cannot handle it, what prevents dead-code elimination earlier?

**Comment by lpw25** [comment]
`camlinternalFormatBasics` has just 3 functions in it are you sure that your "huge" runtimes are coming from it?

**Comment by bobzhang** [comment]
```
jscomp>ls -al ../lib/js/camlinternalFormatBasics.js 
-rw-r--r--  1 hongbozhang  staff  7577 Jun  6 16:47 ../lib/js/camlinternalFormatBasics.js
```
@lpw25 It pulls in around 7KByte JS which is non-trivial for not obvious gain.
@dra27 we do separate compilation and ends up with Pervasives.js for Pervasives module, the rest is taken over by JS tools, since most JS users would have other mixed JS modules, it is unlikely that they have a closed tool-chain purely for OCaml. My impression is that functions living in Pervasives module should be the mostly used ones, `rarely` may want quantifying, but I think it is safe to say they are not frequently used.
