### ISSUE TITLE
OCaml manual syntax highlight in the manual

### ISSUE THREAD

**Issue by XVilka** [ocaml/ocaml#8718]
Currently manual is pretty dull looking:
![image](https://user-images.githubusercontent.com/203261/59024766-2be58200-8885-11e9-89a9-0f9f89a9ffb4.png)

And how it might look [with listings](https://tex.stackexchange.com/questions/483056/listings-for-ocaml-and-quotes):
![image](https://user-images.githubusercontent.com/203261/59024843-62bb9800-8885-11e9-8408-7501dc794fff.png)

**Comment by dra27** [comment]
Seems like a nice change, to me - do you have time to prepare an initial PR (it could just be a draft, showing that it works in one place, then can be extended to the whole manual).

**Comment by XVilka** [comment]
I wasn't able to find where `caml_example` pseudo-environment defined, but since it is used like that:
```tex
\begin{caml_example}
let x = Some y
\end{caml_example}
```
we can define (or extend the definition) it like
```tex
\newenvironment{caml_example}[1]{
\begin{lstlisting}[frame=single]}
{#1}
\end{lstlisting}
}
```
or
```tex
\usepackage{environ}
\NewEnviron{caml_example}[1]{
\begin{lstlisting}
{#1}
\BODY
\end{lstlisting}
```

**Comment by Octachron** [comment]
The `caml_example` environment is defined in `manual/styles/caml-sl.sty`. And in general stacking verbatim environment on top of each other does not work. Even more so when the `\caml` environment plays with catcode to support underlining.

**Comment by pmetzger** [comment]
Please do make sure that if this is done, the results still look okay when printed on a black and white printer.

**Comment by sanette** [comment]
another possibility is to post-process the html using `higlo`,
see https://sanette.github.io/ocaml-tutorial/core_tutorial.html
 Of course this doesn't work for the pdf (unless we recreate the pdf from the html...)
