### ISSUE TITLE
64bit sized bigarrays support

### ISSUE THREAD

**Issue by XVilka** [ocaml/ocaml#8733]
One of the good example is to use Bigarray mapped on top of the file, whose size can easily exceed the 32bit limits. It would be really useful in 2019 to have bigger bigarrays.

**Comment by nojb** [comment]
> One of the good example is to use Bigarray mapped on top of the file, whose size can easily exceed the 32bit limits. It would be really useful in 2019 to have bigger bigarrays.

Which limit is this? I thought bigarrays did not have any hard-coded limit.

**Comment by XVilka** [comment]
@nojb for example `Bigarray.Array1.get ba offset` requires `offset` to be int, rather than int64, obviously limiting the size to 32bits.

**Comment by dbuenzli** [comment]
> obviously limiting the size to 32bits.

To 30 bits to be precise. But then on a 32-bit machine addressing is limited to 32-bits anyways. 

If you want to use large files on 32-bit machines you should use `Unix.Largefile` rather than `mmap`ing them. Depending on the size of your platform's `off_t` type this may allow you to deal with files larger than what 30-bits allow.

**Comment by XVilka** [comment]
@dbuenzli well, I talk more about 64bit machines, since 32bit are quite rare these days.

P.S. Yes, of course 30 bits, you are right.

**Comment by nojb** [comment]
> @dbuenzli well, I talk more about 64bit machines, since 32bit are quite rare these days.

An `int` in a 64bit machine is 63 bits wide, so it limits you to 62 bits of addressable memory. This is surely enough, right?

**Comment by dbuenzli** [comment]
Well but your indexing `int`s on a 64-bit machine are 62-bit then which should be sufficient for most needs.

**Comment by XVilka** [comment]
Oh, I misunderstood then. Thanks for the answers, closing this one.
