### ISSUE TITLE
Organize issues into projects

### ISSUE THREAD

**Issue by XVilka** [ocaml/ocaml#8734]
GitHub offers amazing feature to make Project boards for managing issues and tracking progress. Since OCaml development migrated to use GitHub for everything, it makes sense to use this feature as well:
- https://github.com/ocaml/ocaml/projects
- https://help.github.com/en/articles/about-project-boards

For example possible projects are:
- DWARF/GDB improvements
- Multicore prerequisites
- Windows support
- Performance optimizations
- Flambda

**Comment by XVilka** [comment]
@xavierleroy I noticed you started cleaning up stalled PRs. Might I suggest that you also decide if this one worth considering, or close if nobody is going to do this? From my point of view, it will increase the development transparency, and it is mostly automated, also good for new contributors to understand where their help is needed.

**Comment by xavierleroy** [comment]
I missed your message initially, so thank you for the ping.  

I've never used those project boards, but that's something we could discuss among the core dev team.  Let me ping @shindere and @Octachron first to see if they have an opinion.

**Comment by Octachron** [comment]
I am not very familiar with github's project myself.
One relevant example of project might be: https://github.com/ocaml-multicore/ocaml-multicore/projects/3 .
It seems to be essentially a presentation layer for labels. One possibility would be to experiment on the documentation-related issues.

**Comment by shindere** [comment]
No opinion but I added the topic to the agenda of our next developer
meeting, thanks!

**Comment by Octachron** [comment]
This was discussed at a developer meeting, and there was no strong support for the idea.
