### ISSUE TITLE
Updating 4.08 Manual link

### ISSUE THREAD

**Issue by Fourchaux** [ocaml/ocaml#8740]
The 2 links:

http://caml.inria.fr/pub/docs/manual-ocaml/index.html
http://caml.inria.fr/pub/docs/manual-ocaml-4.08/index.html

display an "old" User's Manual (dated February 8, 2019).

Should not the manual dated June 14, 2019 be used?

**Comment by dra27** [comment]
There were some changes to the manual after beta1, so it would be worth re-generating it, yes.

**Comment by damiendoligez** [comment]
FTR, it was re-generated, but the uploading instructions failed because of a leftover file.
