### ISSUE TITLE
incorrect principality warning on functional updates of records

### ISSUE THREAD

**Issue by trefis** [ocaml/ocaml#8747]
```
# module M = struct type t = { x : int; y: char } end
  let f (x : M.t) = { x with y = 'a' }
  let g (x : M.t) = { x with y = 'a' } :: []
  let h (x : M.t) = { x with y = 'a' } :: { x with y = 'b' } :: [];;
Line 4, characters 40-58:
4 | let h (x : M.t) = { x with y = 'a' } (* a *) :: { x with y = 'b' } (* b *):: [];;
                                                    ^^^^^^^^^^^^^^^^^^
Warning 18: this type-based record disambiguation is not principal.
module M : sig type t = { x : int; y : char; } end
val f : M.t -> M.t = <fun>
val g : M.t -> M.t list = <fun>
val h : M.t -> M.t list = <fun>
```

We know principally that `x` is `M.t` (as illustrated by `(* a *)` and the other functions), so we shouldn't get a warning.

What happens is this: we first typecheck `(* a *)`, at this point the expected type is a fresh variable, which can't be used to disambiguate the fields, so we look at the type of `x`.
However for `(* b *)`, the expected type is `M.t`, which we can use to disambiguate, but it is not principally known.

This seems easy to fix: instead of first looking at the expected type, and then *if that fails* at the type of the expression; we should be looking at both.

**Comment by xvw** [comment]
Are you sure this warning is still triggered? When trying the code with OCaml 4.10.0 I have no warning triggered.

**Comment by garrigue** [comment]
No, it's still there (even in trunk).
To trigger it, one has to use `ocaml -principal`.
