### ISSUE TITLE
Broken links in the 4.08 Documentation

### ISSUE THREAD

**Issue by Fourchaux** [ocaml/ocaml#8752]
Re-testing https://github.com/ocaml/ocaml/issues/8574 with the new rebuilt manual:

http://caml.inria.fr/pub/docs/manual-ocaml/index.html
http://caml.inria.fr/pub/docs/manual-ocaml-4.08/index.html

The following broken links are still present:
```
(404 Not Found)

    Chapter 9: Ast_mapper
    Chapter 10: Ast_mapper
    Chapter 12: Ast_mapper
    Chapter 22: Pparse module - Typemod module - Simplif module - Clflags module
```
The _.../libref/...._ links (instead of _.../compilerlibref/..._) seem to be problematic.

**Comment by Octachron** [comment]
Those links have been fixed in the current version of the manual. Thanks for the report.
