### ISSUE TITLE
How to match a regex with a fixed range of repeated occurence using Str regexp?

### ISSUE THREAD

**Issue by coolakshay59** [ocaml/ocaml#8761]
Is there a way to check following regex "[a-zA-Z]{0,50}" using Str regexp library? It looks like the braces with the range is not supported here.
I tried both using "[a-zA-Z]{0,50}" and "[a-zA-Z]\\{0,50\\}"

**Comment by dra27** [comment]
You can’t do that with `Str` - I’d suggest using ocaml-re (https://github.com/ocaml/ocaml-re)
