### ISSUE TITLE
Spacetime module appearing in flambda section of the manual

### ISSUE THREAD

**Issue by lpw25** [ocaml/ocaml#8785]
Section 20 in the manual ("Optimisation with Flambda") currently has a mysterious Section 20.17 which contains the documentation of the Spacetime module. It clearly shouldn't be there and it is not at all clear to me looking at the manual sources how it ends up there either.

**Comment by Octachron** [comment]
This looks like the same issue than #8767 : there is a conflict between the rule for spacetime.html(the general overview) and Spacetime.html(the module documentation). I am working on it.

**Comment by gasche** [comment]
(wouldn't it be *great* if we had a check in our manual-tests that no paths are conflicting-modulo-casing...)

**Comment by Octachron** [comment]
It seems indeed a good idea to have at least a test for conflicts between modules and chapter filenames. I will look at it.
