### ISSUE TITLE
Segmentation fault: Marshal.to_string with large float32 bigarray

### ISSUE THREAD

**Issue by mseri** [ocaml/ocaml#8787]
Minimal reproduction steps:
```
(* in the toplevel *)
open Bigarray;;
let m = Genarray.create float32 c_layout [|58320; 11664|];;
Marshal.to_string m [];;
```

Note that it does fail also if `float32` is replaced by `complex64`, but does not fail with `float64` and `complex32`. Tested on mac osx 10.14.5, with ocaml 4.07.1 (also in native mode).

Origin: https://github.com/owlbarn/owl/issues/422

**Comment by yallop** [comment]
Thanks for the clear report & reproduction instructions.  There's a fix in #8788.
