### ISSUE TITLE
Possible (latent) bug in Ctype.normalize_type

### ISSUE THREAD

**Issue by alainfrisch** [ocaml/ocaml#8792]
The following line seems suspicious:

https://github.com/ocaml/ocaml/blob/fa33a180c85ac56296ce33dc49715ed57412e34b/typing/ctype.ml#L4467

I would expect that `fi`, not `ty` should be logged, since it is the one whose `desc` field is modified.

What about turning the `log_type` function into `logged_set_desc`, which does both the logging and setting the `desc` field?

(Introduced in commit 65c80f8ae1)

**Comment by garrigue** [comment]
This indeed looks like a no-brainer, particularly if one looks at the context of the commit.
Thanks for finding it.

**Comment by garrigue** [comment]
Fixed by #9018
