### ISSUE TITLE
https://caml.inria.fr/pub/docs/manual-ocaml/libref has been inaccessible for hours

### ISSUE THREAD

**Issue by jfehrle** [ocaml/ocaml#8793]
I've not been able to access the online library documentation for several hours.  The rest of the internet seems normal.  The message is

```
This site can’t be reached
caml.inria.fr took too long to respond.
```

FWIW I'm in Northern California.

**Comment by Armael** [comment]
Maintenance operations are currently going on at Inria. The servers are expected to be back online by 2pm today (local time).

**Comment by Armael** [comment]
It's back.
