### ISSUE TITLE
-plugin  exception raised

### ISSUE THREAD

**Issue by houndofsound** [ocaml/ocaml#8801]
I'm loading a library that uses ocamlcommon.cma and -plugin, erroring with
"Error: this object file is uses unsafe features while loading argument of -plugin"

indeed ocamlcommon has "unsafe features: YES" throughout.
but if one cannot use the compiler libraries how can the compiler internals be referred to by the plugin?

the native version of this works ok.

**Comment by Octachron** [comment]
First, plugins are not supported anymore starting from 4.09.

However, there was generally no need to link the `ocamlcommon.cma` when building a compiler plugin. You can look at the [plugin chapter of the manual](https://caml.inria.fr/pub/docs/manual-ocaml-4.08/plugins.html) for a small example.

If you need more help, may I refer you https://discuss.ocaml.org ?
