### ISSUE TITLE
Polymorphic method of anonymous object is incorrect

### ISSUE THREAD

**Issue by Guest0x0** [ocaml/ocaml#8812]
Consider the following example:
```
let self_apply (x : < call : 'a. 'a -> 'a >) = x.call x;;
let t1 f = (self_apply f, f 1, f true);;
let t2 f = (f 1, f true, self_apply f);;
```
t1 type checks with type (..., int, bool) but t2 will be rejected.
Hence the evaluation order of the type checker affect its behaviour, which is clearly contradictory to any possible type system specification.
The most applicable solution in my knowledge is [this paper](http://citeseerx.ist.psu.edu/viewdoc/download;jsessionid=406CA832F160A498D39723BFB92887DC?doi=10.1.1.51.1912&rep=rep1&type=pdf).
The main complexity of the paper is about unifying two polymorphic type schemes,
which is already done by OCaml.
The rest of work is annotating every polymorphic type scheme with a type variable,
and allowing only those polymorphic type schemes whose associated type variable is not in the type environment to be instantiated.
Annotations can rename all such type variables in the type scheme, For example:
```
let f (x : < call : 'a. 'a -> 'a >) = ...
```
is equivalent to
```
let f y =
  let x = (y : < call : 'a. 'a -> 'a >) in
  ...
```
The advantage of this method is that it requires the minimal change compared with other approaches to first class polymorphism. Adding it to OCaml should be straightforward.
In addition, this method can be used to extend OCaml with first class polymorphic type scheme
(without using objects or records)

**Comment by garrigue** [comment]
This method is actually implemented in ocaml, but only for polymorphic methods (for lack of a good syntax for wrap/unwrap).
To enable the principality check, you should use `ocaml -principal` (there is an extra cost involved, but for instance the compiler itself is compiled using this option).
Then you get the following output:
```ocaml
# let self_apply (x : < call : 'a. 'a -> 'a >) = x#call x;;
val self_apply : < call : 'a. 'a -> 'a > -> < call : 'a. 'a -> 'a > = <fun>
# let t1 f = (self_apply f, f#call 1, f#call true);;
Warning 18: this use of a polymorphic method is not principal.
Warning 18: this use of a polymorphic method is not principal.
val t1 : < call : 'a. 'a -> 'a > -> < call : 'a. 'a -> 'a > * int * bool =
  <fun>
# let t2 f = (f#call 1, f#call true, self_apply f);;
Error: This expression has type bool but an expression was expected of type
         int
```
I.e. the first case is a warning rather than an error, but it marks clearly that this code in not legit.
