### ISSUE TITLE
Adding a -bounds-checking contrary to -unsafe flag

### ISSUE THREAD

**Issue by bobzhang** [ocaml/ocaml#8814]
We have an -unsafe flag to make program faster (but dangerous).
It would be convenient to have such a flag to diagnose memory corruption issues

**Comment by xavierleroy** [comment]
OK, I bite:

Bounds checking is already the default.  What would the hypothetical -bounds-checking flag do that is not currently done?

**Comment by bobzhang** [comment]
Here is my experience: sometimes we are too confident that we use Array/String.unsafe_* in lots of cases, and hit a hard to find bug, so it would be helpful to have a flag to restore safe behavior for bug finding.
I understand that you could say you should use unsafe_* in very rare places, but the reality is quite complex
