### ISSUE TITLE
bug in Str?

### ISSUE THREAD

**Issue by progman1** [ocaml/ocaml#8829]
the following seems to show that putting the 'any character' pattern '.' into
a character set changes its meaning.
Naturally I am doubting my own sanity in the face of the many years of use and testing this module has received...

```
let _=
  let re=Str.regexp "[.]*word" in
  let s ="a b c word" in
  Printf.printf "%s / %b\n" s @@ Str.string_match re s 0;

  let re=Str.regexp ".*word" in
  let s ="a b c word" in
  Printf.printf "%s / %b\n" s @@ Str.string_match re s 0
```

**Comment by yallop** [comment]
This is standard behaviour for regular expressions.  For example, here's the same behaviour in Python:

```
>>> print re.match('[.]*word', 'a b c word')
None
>>> print re.match('.*word', 'a b c word')
<_sre.SRE_Match object at 0x7f4d3915f718>
```

This context-dependent meaning of `.` is even part of the [POSIX regex spec](http://pubs.opengroup.org/onlinepubs/009696899/basedefs/xbd_chap09.html#tag_09_03_05), which says "The period, left-bracket, and backslash shall be special *except when used in a bracket expression*".

**Comment by progman1** [comment]
OK thanks. It might be useful to mention an onward source of info in the Str docs or .mli given that there
is some info there but not, for instance, anything to do with whitespace, which gives the impression
that what you see is exactly what is supported and no more.

**Comment by gasche** [comment]
The suggestion to improve the document makes sense, but the issue itself has disappeared so I'm closing to facilitate triaging.
