### ISSUE TITLE
Add support for PF_UNIX on windows

### ISSUE THREAD

**Issue by Et7f3** [ocaml/ocaml#8863]
Since windows 10 1803, windows support PF_UNIX+SOCK_STREAM/SOCK_RAW combinaison
So Unix module can be updated.
source: https://devblogs.microsoft.com/commandline/af_unix-comes-to-windows

**Comment by dra27** [comment]
This would be fiddly, but that doesn't mean not worth doing. A bit like `Unix.symlink`, you have the issue of whether you compile win32unix with this support (so you have at least SDK 10763 or later) and then at runtime you have to replicate the logic behind the `sc query afunix` call (a little like `Unix.has_symlink` - although in this case the absence of the support at runtime would just be signalled with an exception, not a separate function, I expect)

**Comment by Et7f3** [comment]
The post say it is available if BuildNumber > 17063. I think it is safe to only check BuildNumber which is stored "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\CurrentBuildNumber".

**Comment by dra27** [comment]
This will be in 4.14!
