### ISSUE TITLE
Documentation: need better description of ( expr : typexpr )

### ISSUE THREAD

**Issue by jfehrle** [ocaml/ocaml#8880]
In section 7.7.2 (https://caml.inria.fr/pub/docs/manual-ocaml/expr.html#sec134) the description of `( expr : typexpr )` says only "This constraint forces the type of expr to be compatible with typexpr."

This description seems too terse: does the construct just give a specific compatible type that's other than what normal type inference come up with, or does it include other conversions?

In my case, I saw use of this construct to convert `expr` to a function--I wouldn't have guessed this was possible just from the description.  Example: https://github.com/coq/coq/blob/92f38826f767db01dbc51f2372b23e7b4e3b1aaa/plugins/ltac/tacentries.ml#L180-L180.

**Comment by gasche** [comment]
I don't understand what you mean by "to convert `expr` to a function", is it possible that you would be misreading the code you are linking to? In that case `expr` is `TacAlias (CAst.make ~loc (kn,l))`.

**Comment by gasche** [comment]
There is no implicit conversion happening with `(foo : bar)`: this expression has type `bar` provided that `foo` also has type `bar`.

**Comment by jfehrle** [comment]
You're right, thanks.  I'm working through some unfamiliar and complex code.  The behavior of the code isn't what I thought it was so I drew the wrong conclusion.

The wording is the doc is still a little strange.  typexpr has to be compatible with the type of expr; you can't "force" a string to be an int with `("abc" : int)`

**Comment by gasche** [comment]
I will be closing this issue for now, in the benefit of triaging. Better formulations may be possible, but after giving it a bit of thought I cannot find a clearly-better choice, and also the rest of the page is formulated with the idea of presenting type annotations as constraints, so a change in approach would need to encompass the whole chapter or maybe even manual.
