### ISSUE TITLE
incompleteness of ocamlc warning #8

### ISSUE THREAD

**Issue by ghost** [ocaml/ocaml#8883]
If I have the following "program":
```Ocaml
  type t = A | B of unit | C

  let f v =
    match v with
    | A -> ()
```
and try to compile it:
```
ocamlc -c main.ml
```
then I get the following warning:
```
File "main.ml", line 4, characters 2-26:
Warning 8: this pattern-matching is not exhaustive.
Here is an example of a case that is not matched:
C
```
I am wondering whether this is the desired behavior.
Wouldn't:
```
Warning 8: this pattern-matching is not exhaustive.
Here is an example of a case that is not matched:
(B () | C)
```
be less surprising?

**Comment by gasche** [comment]
In general there are performance questions with the idea of trying to collect "all" missing patterns, when that set may be large. If we give a single example, you can fix that one, and then you will see other missing patterns if there are any.

**Comment by ghost** [comment]
Ok. I understand.

(This incompleteness is a result of a compromise.
The quick response is preferred over complete response.)

I am closing the issue.
