### ISSUE TITLE
When using -pp errors are reported using a temporary file name

### ISSUE THREAD

**Issue by Armael** [ocaml/ocaml#8888]
```
$ cat /tmp/foo.ml
let _ = 1 +. 2 in ()
$ ocamlc -pp cat /tmp/foo.ml
File "/tmp/ocamlpp583366", line 1, characters 8-9:
Error: This expression has type int but an expression was expected of type
         float
```

Instead, the error location should mention the source file `/tmp/foo.ml`.

It looks like in `driver/pparse.ml` we take care of setting `Location.input_name` to the source file *before* preprocessing, but then in the case where the output is not a serialized ast, we do `Location.init` using the name of the temporary file, instead of the source file. 
This results in a mismatch between `Location.input_name` (which contains the name of the file before preprocessing) and the locations emitted by the lexer (which contain the name of the file after preprocessing).

**Comment by alainfrisch** [comment]
Locations refer to fragments of the temporary file; they wouldn't make sense as locations in the real source file (except when the preprocessor is `cat`!).

**Comment by trefis** [comment]
Agreed, it's the job of the preprocessor to include line directives in this case (because it knows the name of the actual source file).

**Comment by Armael** [comment]
Ah, that's interesting.

On the contrary, it was my understanding that it is the job of preprocessors to make sure that errors in their output can be mapped to the original input. Otherwise this makes up for a terrible user experience, where user errors in the input get reported at locations that depend on the preprocessed output.

The tools available for preprocessors to do that are (to my knowledge) line directives when outputting text (as menhir or mdx do for instance), or directly outputting a serialized ast, and adjusting the locations so that they either correspond to locations in the input, or are marked as ghost otherwise (to my knowledge this is what ppx rewriters do).

**Comment by alainfrisch** [comment]
Yes, exactly.  Altough line directives are useful in limited context, as they wouldn't be able to encode precise locations for all items in the Parsetree.

**Comment by Armael** [comment]
I see, I think I understand your point better. 
If I understand correctly, you say that a preprocessor should always start its output with a line directive (e.g. `# 1 "foo.ml"`) to indicate the name of the source input.

I guess that it is reasonable. 
My original idea was to have the source name default to the file before preprocessing instead of leaking a temporary filename that we know is not user provided. But I do agree that if no line directive is provided (bad!) it seems slightly better to default to the file that we are actually compiling (as we do currently).

**Comment by alainfrisch** [comment]
Line directives are unlikely to provide precise good locations, except for simple preprocessors that only extract fragments of the original source (conditional compilation, or ocamllex/ocamlyacc-like tools).  In general, you should aim at emitting Parsetree to have good control over locations.

**Comment by damiendoligez** [comment]
See the `ocamldoc/remove_DEBUG` script for a simple example with line directives.
