### ISSUE TITLE
Bespoke typedefs in the C runtime

### ISSUE THREAD

**Issue by jflopezfernandez** [ocaml/ocaml#8916]
Is there a reason for typedefs like `typedef size_t asize_t`? I can see the logic in using a typedef for `caml_stat_block` to indicate that memory must come only from caml_stat_* functions as opposed to another memory manager, but I feel like using a typedef like `typedef char* addr` just makes the take longer to understand because you have to figure out if 'addr' is a void*, char*, ptrdiff_t, unsigned long, etc. What is the project's stance on these data types? Would pull reviews refactoring some of these data types like asize_t to size_t be considered?

**Comment by dra27** [comment]
For `addr`, see #8896

**Comment by xavierleroy** [comment]
> Is there a reason for typedefs like `typedef size_t asize_t` ? 

Sometimes it's historical, sometimes it's questionable design.  For `asize_t`, this probably comes from Caml Light.  At that time (1989-1992), not all C compilers and C standard headers were ANSI-C compliant, so `size_t` was not guaranteed to be there, and we probably had a fallback:
```
#ifdef HAS_SIZE_T
typedef size_t asize_t
#else   
typedef unsigned int asize_t
#endif  
```
or something like that.

I agree that nowadays `size_t` should be used and `asize_t` should not.

**Comment by mshinwell** [comment]
I don't think this issue needs to remain open -- if someone wishes to submit a PR to improve this area, please feel free.
