### ISSUE TITLE
Ocamlopt tries to link shared runtime with static-lib extension

### ISSUE THREAD

**Issue by cspiel** [ocaml/ocaml#8922]
I wanted to link a program with the **shared runtime** using a
recent native compiler

```
$ ocamlopt -version
4.10.0+dev0-2019-04-23
$ git show HEAD | head -1
commit bf240cbab534d8b0af2ff75c0d19064dd398024f
```
and therefore I said
```
ocamlopt -runtime-variant _shared hello.ml
```
but the compiler complained
```
File "caml_startup", line 1:
Error: Cannot find file libasmrun_shared.a
```
However, the compiler driver ought to link against
*libasmrun_shared.so* on this system:
```
$ ocamlopt -config | grep ^ext
ext_exe:
ext_obj: .o
ext_asm: .s
ext_lib: .a
ext_dll: .so
$ (cd `ocamlopt -where`; find . -name 'libasmrun*')
./libasmrun.a
./libasmrun_shared.so
./libasmrun_pic.a
./libasmrund.a
./libasmruni.a
```
After applying the following (terribly ad hoc) patch ocamlopt
references the correct shared-runtime library.

```diff
--- a/asmcomp/asmlink.ml
+++ b/asmcomp/asmlink.ml
@@ -109,7 +109,8 @@ let add_ccobjs origin l =
   end
 
 let runtime_lib () =
-  let libname = "libasmrun" ^ !Clflags.runtime_variant ^ ext_lib in
+  let ext = if !Clflags.runtime_variant = "_shared" then ext_dll else ext_lib in
+  let libname = "libasmrun" ^ !Clflags.runtime_variant ^ ext in
   try
     if !Clflags.nopervasives || not !Clflags.with_runtime then []
     else [ Load_path.find libname ]
```

We arrive at
```
$ ocamlopt -verbose -runtime-variant _shared hello.ml
+ as  -o 'hello.o' '/tmp/camlasm973446.s'
+ as  -o '/tmp/camlstartup8ef270.o' '/tmp/camlstartupfade15.s'
+ gcc -O2 -fno-strict-aliasing -fwrapv -g  -fno-omit-frame-pointer -Wall -Werror -fno-tree-vrp -ffunction-sections -D_FILE_OFFSET_BITS=64 -D_REENTRANT -DCAML_NAME_SPACE  -Wl,-E -o 'a.out'  '-L/home/cls/lib/ocaml'  '/tmp/camlstartup8ef270.o' '/home/cls/lib/ocaml/std_exit.o' 'hello.o' '/home/cls/lib/ocaml/stdlib.a' '/home/cls/lib/ocaml/libasmrun_shared.so' -lm -ldl
/usr/bin/ld: warning: type and size of dynamic symbol `caml_system__frametable' are not defined
$ ldd a.out 
	linux-vdso.so.1 (0x00007ffcfdacf000)
	/home/cls/lib/ocaml/libasmrun_shared.so (0x00007f44e0d12000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f44e0b5b000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f44e0b56000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f44e0995000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f44e0d93000)
$ ./a.out 
Hello, world!
```

**Comment by nojb** [comment]
Someone will correct me if I am wrong, but I don't think linking to the runtime as a shared library is supported. Maybe if you explain what you are really trying to do it will be clearer if there is a problem or not.

**Comment by cspiel** [comment]
@nojb: I have found the executable size of even tiny OCaml programs
shockingly large.

```
$ cat hello.ml
let _ =
  print_endline "Hello, world!"
$ ocamlopt -o hello-static hello.ml
$ ocamlopt -runtime-variant _shared -o hello-shared hello.ml
$ ls -l hello-static hello-shared
-rwxr-xr-x 1 cls cls  132752 Sep  6 15:12 hello-shared
-rwxr-xr-x 1 cls cls 1255920 Sep  6 15:12 hello-static
```

Obviously, linking against the shared runtime pays off size-wise.

IMHO, the binary is still large given the complexity :wink: of the
source, but it is a step in the right direction if you want lots of
small OCaml tools each (hopefully) solving one problem.

**Comment by xavierleroy** [comment]
To be honest, a large part of this size is debug information, which you can remove using "strip".  

It is nonetheless true that every executable generated by `ocamlopt` contains its own copy of the OCaml run-time system, which is not small (but not huge either).  For many users it's a useful feature: the executable is self-contained.  But it could make sense to support `_shared` as a run-time variant, as @cspiel suggests.

**Comment by damiendoligez** [comment]
How does the C linker decide whether a given library is static or shared? Does it look at the file name or the file format?

**Comment by cspiel** [comment]
@damiendoligez: I'm not a linker lawyer but on my GNU/Linux box the linker (**ld.bfd**) looks
at the input files' formats and I suspect **ld.gold** and **ld.lld** behave similarly (not tested
though).

Here is a tiny *Makefile* I have tinkered with:

```makefile
.PHONY: all
all: hello-stat hello-dyn

.PHONY: clean
clean:; $(RM) hello-main* hello-stat* hello-dyn* libhello-stat* libhello-dyn*

hello-stat.c:; echo 'void say_hello(void) {puts("hello from static");}' > $@
hello-dyn.c:; echo 'void say_hello(void) {puts("hello from dynamic");}' > $@
hello-main.c:; echo 'int main(int argc, char **argv) {say_hello(); return 0;}' > $@

%.o:%.c; $(CC) -fpic -c $<

libhello-stat.a: hello-stat.o; $(RM) $@; $(AR) q $@ $^
libhello-dyn.so: hello-dyn.o; $(CC) -shared -o $@ $^

hello-stat: hello-main.o libhello-stat.a; $(CC) -o $@ $< -L. -lhello-stat
hello-dyn: hello-main.o libhello-dyn.so; $(CC) -o $@ $< -L. -Wl,-rpath=$(PWD) -lhello-dyn
```

After reaching the "all" target we can go on playing with the linker.

* Names do not matter to GNU linker.
    `ln -sf libhello-stat.a foo.bar; gcc -o helloX hello-main.o foo.bar`
    `ln -sf libhello-dyn.so foo.bar; gcc -o helloX -Wl,-rpath=$(PWD) hello-main.o foo.bar`
* Dynamic linking is the default for my configuration.
    `ln -s libhello-stat.a libhello.a; ln -s libhello-dyn.so libhello.so; gcc -o helloX -L. -Wl,-rpath=$(PWD) hello-main.o -lhello`
* But we can change preferences.
    `gcc -o helloX -L. -Wl,-rpath=$(PWD) hello-main.o -Wl,-Bstatic -lhello -Wl,-Bdynamic`

If I want to avoid the `-rpath` trickery, I use `LD_LIBRARY_PATH` at the shell level:

```
env LD_LIBRARY_PATH=`pwd` ldd ./helloX
env LD_LIBRARY_PATH=`pwd` ./helloX
```

**Comment by damiendoligez** [comment]
I see the same on MacOS (the linker doesn't take the file extension into account) so a workaround could be to symlink (or rename) `libasmrun_shared.so` to `libasmrun_shared.a`. I admit it could be slightly confusing for users.
