### ISSUE TITLE
Can't read empty environment variables on Windows

### ISSUE THREAD

**Issue by mroch** [ocaml/ocaml#8932]
On Linux, `Sys.getenv` on an empty environment variable returns `""`. On Windows, it raises `Not_found`.

Note: I have no Windows experience, and I'm not sure it's even valid to have an empty environment variable on Windows, but you _can_ do `setx FOO ""`. It seems possible to make them consistent.

--

On Windows, `Sys.getenv` calls `caml_win32_getenv` and raises `Not_found` if it returns null:

https://github.com/ocaml/ocaml/blob/5ad64306d36755b600f2556805effb73627508c8/runtime/sys.c#L360-L367

`caml_win32_getenv` returns null when `GetEnvironmentVariable` returns 0. `GetEnvironmentVariable` returns the length of the environment variable, not including the null terminator ([docs](https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-getenvironmentvariable)), so it'd return 0 for an empty variable. it also returns 0 on error.

https://github.com/ocaml/ocaml/blob/5ad64306d36755b600f2556805effb73627508c8/runtime/win32.c#L726-L731

on Linux, `getenv` returns a `char*` or `NULL`, so it can differentiate between an empty string and an error.

I think `caml_win32_getenv` should only raise `Not_found` if `GetLastError` returns `ERROR_ENVVAR_NOT_FOUND` (per the `GetEnvironmentVariable` docs).

**Comment by nojb** [comment]
I have a vague recollection that on Windows assigning an empty string to a variable is equivalent to deleting it, so am not sure how this is supposed to work. @dra27 ?

**Comment by damiendoligez** [comment]
ping @dra27
