### ISSUE TITLE
Doc: instruction on running tests not clear

### ISSUE THREAD

**Issue by gantsevdenis** [ocaml/ocaml#8976]
```
> chroot /chroot/ubuntu_bionic
> /home# git clone https://github.com/ocaml/ocaml.git
> /home/ocaml# ./configure 
>/home/ocaml# make world
> ...
> /home/ocaml# make tests
make -C testsuite all
make[1]: Entering directory '/home/ocaml/testsuite'
make[3]: ../../runtime/ocamlrun: Command not found
Makefile:40: recipe for target 'testing.cmi' failed
make[3]: *** [testing.cmi] Error 127
Makefile:246: recipe for target 'lib' failed
make[2]: *** [lib] Error 2
Makefile:87: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/ocaml/testsuite'
Makefile:782: recipe for target 'tests' failed
make: *** [tests] Error 2
```
`make world` and `make runtop` build OK

**Comment by gasche** [comment]
It's not clear how this failure could happen.

- do you not have a `runtime/ocamlrun` file?
  (but then the rest of the build should break)
- what happens when you `cd testsuite/lib && make`?

**Comment by gantsevdenis** [comment]
```
ocaml/testsuite# make all
cannot find file '../../ocamlopt'Makefile:46: recipe for target 'testing.cmx' failed
make[2]: *** [testing.cmx] Error 127
Makefile:246: recipe for target 'lib' failed
make[1]: *** [lib] Error 2
Makefile:87: recipe for target 'all' failed
make: *** [all] Error 2
root@denis-Aspire-VN7-791G:/home/ocaml/ocaml/testsuite# 
```
No, I don"t have any `runtime/ocamlrun` . On the other hand, I have a `boot/ocamlrun`, which is correctly invoked during `make world`:
```
../../boot/ocamlrun ../../ocamlc -nostdlib -I ../../stdlib ...
...
./boot/ocamlrun ./boot/ocamlc -g -nostdlib -I boot -use-prims runtime/primitives -strict-sequence -principal -absname -w +a-4-9-40-41-42-44-45-48-66 -warn-error A -bin-annot -safe-string -strict-formats -I utils -I parsing -I typing -I bytecomp -I file_formats -I lambda -I middle_end -I middle_end/closure -I middle_end/flambda -I middle_end/flambda/base_types -I asmcomp -I asmcomp/debug -I driver -I toplevel -c parsing/ast_helper.ml
...
```

So I don't understand why make is invoking`runtime/ocamlrun` instead of correct `boot/ocamlrun`. Is there anything to change in `Makefile.tools` (or elsewhere)?..

**Comment by gasche** [comment]
I would expect a `runtime/ocamlrun` to be built as a result of building `make world` -- it is a dependency of the `all` target of `runtime/Makefile`, see the `PROGRAMS` variable in this file. In fact it is invoked when you run `make runtop` (see the definition of the `RUNTOP` variable in the Makefile), so if that executable was missing I wouldn't expect `make runtop` to work either -- which is contradictory with what you say.

(Could you have a `runtime/ocamlrun.exe` file, or a file with a different executable extension?)

**Comment by gantsevdenis** [comment]
Okey I understood; it appears that  `make world.opt` needs to be run before `make tests`
this issue can be closed, sorry for inconvenience
