### ISSUE TITLE
Floating-point literals parsed incorrectly on musl

### ISSUE THREAD

**Issue by aantron** [ocaml/ocaml#8977]
On switch `4.09.0+musl+flambda`, this program:

```ocaml
let () =
  let f = 283686952306183. in
  let expected_bits = 0x42f0203040506070L in
  Printf.printf "%f\n" f;
  Printf.printf "%Lx\n" (Int64.bits_of_float f);

  (* Confirm that Printf is able to print the float correctly when its
     origin is not a literal. *)
  Printf.printf "%f\n" (Int64.float_of_bits expected_bits)
```

produces the output

```
283686952306176.000000
42f0203040506000
283686952306183.000000
```

The LSB of the of the representation of the float is zero, when it should be 0x70.

On switch 4.09.0, the program produces the correct output

```
283686952306183.000000
42f0203040506070
283686952306183.000000
```

**Comment by jhjourdan** [comment]
I guess this is due to a musl bug. Have you tried the same with musl's `strtod` in plain C?

**Comment by aantron** [comment]
Indeed, I just tried it. I will continue at musl, thanks.

**Comment by aantron** [comment]
For reference of others that may encounter this, the bug is still present in musl `master` now. I reported it here: https://www.openwall.com/lists/musl/2019/09/25/10.

**Comment by aantron** [comment]
And finally, this is caused by the state of the x87 control word on WSL, and assumptions about it by musl. See https://github.com/microsoft/WSL/issues/830. This is likely a vanishing problem, with the coming release of WSL2.

**Comment by richfelker** [comment]
Does WSL2 replace WSL1 or just supplement it? My understanding is that WSL2 is running a whole virtualized real Linux kernel, whereas WSL1 is more integrated with Windows, so WSL1 would still be potentially preferred for many uses if it's still offered. If so this bug really needs to be fixed.

**Comment by aantron** [comment]
My understanding is WSL2 is meant to supplement WSL1, but WSL1 will be kept around for compatibility for users that need it. I could very well be wrong on that, though. I would expect the user base of WSL1 to progressively shrink, though.
