### ISSUE TITLE
doc Graphics

### ISSUE THREAD

**Issue by pascal11111** [ocaml/ocaml#8999]
hello
the Graphics doc disappeared.
The requested URL /pub/docs/manual-ocaml/libref/Graphics.html was not found on this server.
Apache/2.4.25 (Debian) SVN/1.9.5 mod_python/3.3.1 Python/2.7.13 OpenSSL/1.0.2s mod_perl/2.0.10 Perl/v5.24.1 Server at caml.inria.fr Port 443

Is is possible to make it available ? (I am teaching Ocaml, and students need it).
Thank you
PL

**Comment by Octachron** [comment]
The graphics library was split from the compiler distribution in 4.09 . The documentation for the new library is available at https://ocaml.github.io/graphics/ or alternatively you can use a version of the manual anterior to 4.09, for instance https://caml.inria.fr/pub/docs/manual-ocaml-4.08/libref/Graphics.html .

**Comment by xavierleroy** [comment]
I added a link to the documentation in the README.md file, so that it appears prominently on the Github page https://github.com/ocaml/graphics/ 

Further issues with Graphics should be reported at https://github.com/ocaml/graphics/issues/

**Comment by pascal11111** [comment]
thank you !
PL
