### ISSUE TITLE
Win32 build broke between 4.08 and 4.09 due to doc change in README.win32.adoc

### ISSUE THREAD

**Issue by jakoblichtenberg** [ocaml/ocaml#9025]
Win32 build broke between 4.08 and 4.09 due to doc change in README.win32.adoc

Repro steps:
    make flexdll
    make
    make flexlink.opt
    make install

Expected: Works

Actual: At "make" I get message "Please refer to the instructions in file README.win32.adoc."

Workaround: Use "make world.opt" instead of "make".

@shindere : This looks to be a regression introduced with this change: https://github.com/ocaml/ocaml/commit/987b0814d721d583a96b362762760508f4d07a8d

**Comment by gasche** [comment]
The change of @shindere you are pointing out was merged a few days ago in trunk; it is *not* part of the 4.09 release. If you are building 4.09, you should use the [README.win32 file of 4.09](https://github.com/ocaml/ocaml/blob/4.09/README.win32.adoc), which does say `make world.opt` there.

**Comment by jakoblichtenberg** [comment]
Sorry about the noise.

**Comment by gasche** [comment]
No problem! (I'd rather have too many report about inconsistent documentation than too few.)

**Comment by shindere** [comment]
Thanks a lot, @gasche.
