### ISSUE TITLE
break/continue constructs

### ISSUE THREAD

**Issue by c-cube** [ocaml/ocaml#9033]
Most languages that provide loops provide break/continue (some, like rust, even make it possible to return values in `break` from a `while true` loop). It's very convenient for expressing [some algorithms](https://github.com/AestheticIntegration/minisat-ml/blob/master/docs/tech_report.md#imperative-programming) that are imperative in nature. It's more concise, convenient, and natural than using exceptions (especially in the case of `continue`).

Previously discussed in https://github.com/ocaml/ocaml/issues/4612, in 2008, so it might be time to reevaluate?

**Comment by chambart** [comment]
I do not endorse it, but if you need: https://github.com/ocaml/ocaml/pull/1342

**Comment by yminsky** [comment]
For what it's worth, Base comes with a module that provides a reasonably
lightweight way of doing this, without needing to extend the language:

https://github.com/janestreet/base/blob/master/src/with_return.mli

It's not used all that heavily, but it is occasionally useful.

The main semantic oddity of this approach is that a catch-all exception
handler can prevent the return from occurring in the way one might expect.

y

**Comment by c-cube** [comment]
Thanks Yaron, I remember seein something similar in batteries.
It still is more verbose, less readable, and potentially slower than a
builtin control flow construct.

**Comment by mshinwell** [comment]
There have been no further comments for six months (and also no sign of anyone willing to implement such a feature), so closing.
