### ISSUE TITLE
safe syntax, because scoping is hard™

### ISSUE THREAD

**Issue by c-cube** [ocaml/ocaml#9034]
Hello, it's me again, and I hereby propose to introduce a new syntax. Yes, a new syntax, because we clearly didn't have enough of these.

Why? because the current syntax is pretty neat, imho, *except* for the original sin of not including terminators for some constructs. I speak, of course, of `if`, `let`, `match`, `try`, and `fun`/`function` not having a mandatory `end`. Adding these removes a common source of errors that affects even seasoned OCaml programmers and makes the syntax simpler and cleaner. So I'm not suggesting a revised syntax or a new Reason, but rather the smallest possible change that makes the syntax of OCaml a safe one. It would take the shape of a compiler flag `-safe-syntax` (and matching `-unsafe-syntax` — yes, I did like the `-safe-string` process) that toggle this behavior, so modules can be migrated one by one. In addition, a small tool to migrate a module from the unsafe syntax, to the safe syntax, would be provided.

(I would also propose to convert toplevel `let` into `val` to remove the need for `;;` but it's not in the scope of this issue.)

**Comment by yallop** [comment]
#715 discusses this proposal.

**Comment by nojb** [comment]
xref #1480 #722, and especially #715

**Comment by c-cube** [comment]
Good point, I looked for prior issues, not PRs :man_facepalming: . I still feel like this is a very important issue, and the biggest wart on OCaml's face.

**Comment by c-cube** [comment]
Note that it might be possible to keep one parser for both syntax now that we use menhir. That's a better situation compared to #715 .

**Comment by let-def** [comment]
> Note that it might be possible to keep one parser for both syntax now that we use menhir. That's a better situation compared to #715 .

(That would have been rather easy to achieve with ocamlyacc ;), just generate different tokens for the closed constructs)

**Comment by alainfrisch** [comment]
FWIW, I don't think it's a good idea to introduce such a change and I believe much more in encouraging people to use the the existing delimited forms (`begin match ... end` or `(match ... end)`) in "ambiguous contexts".  Cf my note on https://github.com/ocaml/ocaml/pull/715#issuecomment-235184206 and a preliminary proposal on https://github.com/ocaml/ocaml/pull/716

**Comment by c-cube** [comment]
@alainfrisch for me it means I almost always write `begin match … end` (except in trivial cases) as I tend to have many nested matches. And for `if`, they're often going to create a bug if I don't preemptively add `()` around each case.

So for me, the whole point of this is that it would both:
- simplify my code (remove the `begin`s and decrease indentation)
- remove the cognitive overhead of having to be defensive without help from the language

**Comment by alainfrisch** [comment]
> simplify my code (remove the begins and decrease indentation)

The config I use for ocp-indent (and I think the default) applies the same indentation with and without `begin ... end` around `match`.  It seems that it adds one character extra indentation when using parentheses around `match` (but this can probably be configured and then `()` is more compact than `begin...end` if you care about the number of characters).  OTOH, for me, your proposal would add a lot of lines with just `end`.  Globally, I don't buy the argument about simplifying the code (if understood from a syntactical point of view): `end` always add more characters than parentheses.

(Also, in your proposal, you certainly want to add a combined `elseif` keyword, or writing cascading `if-then-else` would just "grow to the right" (with a sequence of `end`s at the end).)

**Comment by c-cube** [comment]
I imagine that the grammar could support `if … then … [else if … then …]* else … end` without a `elseif` construct.

Indeed, this would add a lot of `end` (not that much in my code as there's already a ton of begin/end even on non-nested match/try). I do think it's for the best, as it's simpler *conceptually*: all these dangerous constructs would be safe by default. I would never have to worry when adding a `printf "some debug message"; ` before or after existing code.

> The config I use for ocp-indent (and I think the default) applies the same indentation with and without begin ... end around match

Indeed, but not for `try`, which is also dangerous.

**Comment by alainfrisch** [comment]
> I imagine that the grammar could support if … then … [else if … then …]* else … end without a elseif construct.

How would that work?  It would have to disallow the following (and require adding `begin...end`), right?

````ocaml
if cond1 then
  print_endline "X"
else
  if cond2 then
    print_endline "A"
  else
    print_endline "B";
  end;
  print_endline "C"
end
````

> Indeed, but not for try, which is also dangerous.

Are you sure?  The following is well indented in my editor:

````ocaml
let foo f x =
  try f x with
  | Exit -> false

let foo f x =
  begin try f x with
  | Exit -> false
  end
````

(As a side note, for me, what takes useful real-estate in the second version if the `end`, which takes a full line, while the initial `begin` only take a few characters -- I guess you consider the noise lies with `begin`.)

**Comment by c-cube** [comment]
I get this for the `try` (note the weird 4 level indentation, might be my config though):

```ocaml
let foo x =
  begin try
      let x = 42 in
      ()
    with
    | Exit -> ()
  end
```

As for the `elseif`, oh well. Still beats the risk of dangling else problems.

**Comment by lthls** [comment]
> > The config I use for ocp-indent (and I think the default) applies the same indentation with and without begin ... end around match
> 
> Indeed, but not for `try`, which is also dangerous.

The default configuration for `ocp-indent` does not apply the same indentation with and without `begin ... end`, you have to set the `strict_with` variable to `auto` instead of its default `never`.
It treats `match` and `try` the same way.

**Comment by priamfive** [comment]
No view on whether the PR is a good idea but if terminators are introduced I find languages with separate terminators for different constructs (elegantly Algol-68 style IF....FI for example or IF...ENDIF if you must) clearer than ones which use END or brackets for everything.

**Comment by mshinwell** [comment]
I'm closing this given that #715 has also been closed and there seems little likelihood of achieving a consensus here.  If someone wants to come back with a concrete proposal accompanied by the resources to implement it then an RFC can be submitted.
