### ISSUE TITLE
Appveyor CI msvc64 is broken

### ISSUE THREAD

**Issue by jhjourdan** [ocaml/ocaml#9043]
Since 14 Oct 2019 at 12:21, the Appveyor CI seems broken in the `tool-debugger/dynlink` test. The last successful build happened the same day at 0:50.

**Comment by jhjourdan** [comment]
There is a similar failure at Inria CI on 12 Oct 2019 at 18:26.

**Comment by dra27** [comment]
It’s being investigated. The AppVeyor failure seems to be repeatable. Curiously, bisecting reveals that if either #8651 or #8760 is reverted then it goes away, but the problem is clearly deeper than that!

**Comment by jhjourdan** [comment]
Thanks. If you need some help, please ask : I'm one of the authors of #8654, the PR which introduced the test in question.
