### ISSUE TITLE
Functions `find_first` and `find_last` of the module `Set` are incorrect.

### ISSUE THREAD

**Issue by timothee-haudebourg** [ocaml/ocaml#9044]
The current definition of `find_first` :
```ocaml
let rec find_first f = function
    Empty ->
    raise Not_found
  | Node{l; v; r} ->
    if f v then
      find_first_aux v f l
    else
      find_first f r (* If [f v = false] then [l] is ignored?! *)
```
It is not correct as you can see in the comment I've added. I makes the function to return `None` even though there exists an item `e` such that `f e`.

This exact problem can be also found in the functions `find_first_opt`, `find_last` and `find_last_opt`.

**Comment by lthls** [comment]
The documentation for these functions specify that `f` has to be monotonically increasing. This means that, in your comment, if `f v = false`, then `f` is false for all elements of `l`.

I agree the function name is misleading, and the documentation not adapted for people not familiar with set/order theory. But the implementation is exactly what its developers intended.

**Comment by timothee-haudebourg** [comment]
Hum, you'r right. I should have read the specification more closely then. I suppose I can close the issue, and open a new one to ask for those functions to be more natural.

**Comment by alainfrisch** [comment]
There is a reason for the current behavior (allowing logarithmic lookup of things like "the smallest element greater than X"), so there is no need to ask for changing it.  But feel free to suggest adding other functions or improve the documentation for the current ones.
