### ISSUE TITLE
Miscompilation of recursive value

### ISSUE THREAD

**Issue by lpw25** [ocaml/ocaml#9048]
The discussion in #8956 got me thinking about recursive values and mutability again. In particular, I think this example is a bug:

```ocaml
# let rec x =
    let rec r =
      { contents = 0,
        fun new_count -> let old_count, f = !r in r := new_count, f; old_count }
    in
    r;;
val x : (int * (int -> int)) ref = {contents = (0, <fun>)}

# let get_set = snd !x;;
val get_set : int -> int = <fun>

# let get () = fst !x;;
val get : unit -> int = <fun>

# get ();;
- : int = 0

# let set y = x := y, snd !x;;
val set : int -> unit = <fun>

# set 4;;
- : unit = ()

# get ();;
- : int = 4

# get_set 6;;
- : int = 0

# get_set 6;;
- : int = 6
```

Possibly this is a known issue, since it is a fairly straightforward consequence of the approach we take to compiling recursive values, but I think it still qualifies as a bug.

(I actually thought that I had already tried to construct this example and failed -- so maybe we've already had this discussion elsewhere and it slipped my mind.)

**Comment by AltGr** [comment]
Replayed it on #8956, here is the result:
```ocaml
# let rec x =
      let rec r =
        { contents = 0,
        fun new_count -> let old_count, f = !r in r := new_count, f; old_count }
      in
      r;;
val x : (int * (int -> int)) ref = {contents = (0, <fun>)}
# let get_set = snd !x;;
val get_set : int -> int = <fun>
# let get () = fst !x;;
val get : unit -> int = <fun>
# get ();;
- : int = 0
# let set y = x := y, snd !x;;
val set : int -> unit = <fun>
# set 4;;
- : unit = ()
# get ();;
- : int = 4
# get_set 6;;
- : int = 4
# get_set 6;;
- : int = 6
```

This indeed seems closer to what I would expect :)

**Comment by yallop** [comment]
Perhaps #7768 was the previous construction you had in mind.

**Comment by lpw25** [comment]
Thank you! That was the one I was thinking of. This is a slight variation since it uses a different mechanism to escape the inner record, but the underlying problem is the same.

@AltGr Have you tried the example in #7768 with your branch?

**Comment by gasche** [comment]
In https://github.com/ocaml/ocaml/pull/1565#issuecomment-379788430, @lpw25  proposed to use the "size" classification (Static / Dynamic) to disallow recursive declarations that would result in shallow copies of mutable values. I think that it is an interesting way to think about this problem, and that we should explore it further -- see how to adapt the classification logic to it (for "dissection" #8956 we already discussed with @chambart, @lthls and @AltGr the addition of a Function size/classification, thinking about both changes at once would make sense), and check user programs to see if the restriction breaks code.
