### ISSUE TITLE
missing rpm Provides with 4.10 bytecode 

### ISSUE THREAD

**Issue by olafhering** [ocaml/ocaml#9050]
In my ocaml-4.09 bytecode-only target the resolved rpm dependencies are incorrect, no package can be build:

````
bytecode             x86_64     unresolvable: 
      nothing provides ocaml(Allocated_const) = d788591fd051cea76960dd758587acdc needed by ocaml-compiler-libs
      nothing provides ocaml(Backend_var) = cc0ee73d4b7f99938ae99815cc87ceff needed by ocaml-compiler-libs
      nothing provides ocaml(Clambda) = a39bf3c1e066d73da447bab6bf713172 needed by ocaml-compiler-libs
      nothing provides ocaml(Clambda_primitives) = acffc0be5c50c06c67304aff9b276505 needed by ocaml-compiler-libs
      nothing provides ocaml(Closure_element) = cd49deb3ba77e32ea16e2b648c9c90b2 needed by ocaml-compiler-libs
      nothing provides ocaml(Closure_id) = b4af5742be0c0ed8a76a93a523f542f3 needed by ocaml-compiler-libs
      nothing provides ocaml(Closure_origin) = 4eed62f64ad33273343134d4e5749a09 needed by ocaml-compiler-libs
      nothing provides ocaml(Compilation_unit) = 8c406b89a854dc7ab49c36dbc2571340 needed by ocaml-compiler-libs
      nothing provides ocaml(Export_id) = 14487b4fee3b2db551d5596ba080ce1e needed by ocaml-compiler-libs
      nothing provides ocaml(Export_info) = c3157f885fb7ea1dc19befb1856576ff needed by ocaml-compiler-libs
      nothing provides ocaml(Flambda) = 502bee543511638f3833964eafa692c1 needed by ocaml-compiler-libs
      nothing provides ocaml(Freshening) = d333a3bd79c5c2cebc92b2f8c6cee9ce needed by ocaml-compiler-libs
      nothing provides ocaml(Internal_variable_names) = 01176b3d16163d73549ebc5b59bda631 needed by ocaml-compiler-libs
      nothing provides ocaml(Linkage_name) = 3bad64e5f7bc0eeeef2e278ffc048abf needed by ocaml-compiler-libs
      nothing provides ocaml(Mutable_variable) = 71dd296fbc66e599e203a18bbcf4b79f needed by ocaml-compiler-libs
      nothing provides ocaml(Parameter) = 73877dc9d856b1e345da81b18b6d5e35 needed by ocaml-compiler-libs
      nothing provides ocaml(Projection) = 8731d153d30c0dbc401ebd6f19254253 needed by ocaml-compiler-libs
      nothing provides ocaml(Set_of_closures_id) = 0163c11eb62fcfe19fd7fb456425755f needed by ocaml-compiler-libs
      nothing provides ocaml(Set_of_closures_origin) = 3d2e188858209415c52ff9613cd8e623 needed by ocaml-compiler-libs
      nothing provides ocaml(Simple_value_approx) = 830fcad215b90f47d2a56a49fedeac76 needed by ocaml-compiler-libs
      nothing provides ocaml(Static_exception) = cad68c0ce65a3fae605c5df202da36e0 needed by ocaml-compiler-libs
      nothing provides ocaml(Symbol) = d67f6480c0f18f0147a403fa2ad578fa needed by ocaml-compiler-libs
      nothing provides ocaml(Tag) = 522adc229e49b2ad060ecfa16b8ef0eb needed by ocaml-compiler-libs
      nothing provides ocaml(Var_within_closure) = 2712989338e31a95907ac7891c87a6d2 needed by ocaml-compiler-libs
      nothing provides ocaml(Variable) = 5c81adbd4eb3c888a4595c072a544f1f needed by ocaml-compiler-libs
````
The ordinary ocaml.rpm with ocaml.opt works as expected. I just started to analyze this issue. Have to learn how this rpm dependency generator works, what it is looking for.

**Comment by gasche** [comment]
This organization is only in charge of the upstream OCaml compiler, not per-distribution packaging. We did not create the RPM you are referring to, and we probably cannot help diagnose or resolve the issue. Could you report the issue on your distribution-specific bugtracker?

**Comment by olafhering** [comment]
I am the packager and maintainer (because I touched ocaml last).

So, here are more details. Lets look at `Allocated_const` because it is alphabetically first:

The opt `Provides`:
````
usr/lib64/ocaml/compiler-libs/allocated_const.cmi
ocaml(Allocated_const) = d788591fd051cea76960dd758587acdc
usr/lib64/ocaml/compiler-libs/ocamloptcomp.cma
ocaml(Allocated_const) = d788591fd051cea76960dd758587acdc
````
The opt `Requires`:
````
usr/lib64/ocaml/compiler-libs/alias_analysis.cmi
ocaml(Allocated_const) = d788591fd051cea76960dd758587acdc
... too many to list here ...
````

The bytecode `Provides`:
````
... nothing related to allocated_const installed during make install ...
````
The bytecode `Requires`:
````
usr/lib64/ocaml/compiler-libs/cmx_format.cmi
ocaml(Allocated_const) = d788591fd051cea76960dd758587acdc
````

The only places where `allocated_const` appears in the build log are the compilation of the `ml` and `mli` file, and `ocamlc -g -nostdlib -I boot -use-prims runtime/primitives -a -o compilerlibs/ocamlmiddleend.cma ... middle_end/flambda/allocated_const.cmo ...`.
But then, I do not see where the `cmx_format.cmi` is created, and how it gets the Requires for Allocated_const.

This specifc interface does not appear in a 4.08 build. I need to check if something else that is missing in 4.09 was still used in both 4.08 and 4.09.

**Comment by olafhering** [comment]
Are the listed missing interfaces are even supposed to be visible? `/usr/lib/rpm/ocaml-find-requires.sh` has a few symbols that are ignored: `Annot|Asttypes|Outcometree|Cmo_format|Parsetree`.
Further more, it has an option to specifiy more such strings via the rpm specfile with
````
%global __ocaml_requires_opts -i stringA -i stringB
%global __ocaml_provides_opts -i stringC -i stringD
````
So if these are just "noise" that popup just now I can add workarounds like that to get it going.

**Comment by olafhering** [comment]
I think the question really is:
Does each "requires", as reported by `ocamlobjinfo`, in any case need a "provides" counter-part?

**Comment by dbuenzli** [comment]
@olafhering I'm not familiar with what any of what you are reporting so as far as I'm concerned it's difficult to help you, it's a bit greek to me. 

But:

> Does each "requires", as reported by `ocamlobjinfo`, in any case need a "provides" counter-part?

Depends if you want to be able to use the compilation object or not. For example what you report seems to be in `compiler-libs` so if you are not interested in using the library it doesn't harm. But maybe you (or upstream) simply forgot to install a compilation object.

**Comment by Octachron** [comment]
@olafhering , It sounds like you might be missing the files that moved around in #2281 . But it is hard to tell what is going wrong with your distribution specific tools without more information.

**Comment by olafhering** [comment]
I can not work on this anymore during this month.

Basically rpm parses ocamlobjinfo output for cma/cmi/cmo files, and creates Provides/Requires from the "Interfaces imported:" lines. The hash for "Name" is provided, everything else is required.

**Comment by olafhering** [comment]
I quickly packaged the 4.10 branch, same issue. This workaround does satisfy the rpm dependencies:
````
cp -avt %{buildroot}%{_libdir}/ocaml/compiler-libs compilerlibs/ocamlmiddleend.cma middle_end/backend_intf.cmi middle_end/flambda/inlining_decision_intf.cmi middle_end/flambda/simplify_boxed_integer_ops_intf.cmi
````

**Comment by gasche** [comment]
It looks indeed like the `install` target is missing those files, I'll have a look.

**Comment by gasche** [comment]
In fact, in the current `trunk` it looks like the cmi files that you mention are correctly installed, only `ocamlmiddleend.cma` seems to be missing. I'll send a PR to fix that, and investigate later whether the .cmi files are missing under 4.09.

**Comment by olafhering** [comment]
Commit dd47fafbf5a7c865be905c4a30a258737710597d does not fully fix it:
````
nothing provides ocaml(Backend_intf) = f817419bdc671dc24833ad722faebc11 needed by ocaml-compiler-libs-devel, nothing provides ocaml(Inlining_decision_intf) = ce230dfa331cd40ddb220186c1e1194c needed by ocaml-compiler-libs-devel, nothing provides ocaml(Simplify_boxed_integer_ops_intf) = ea5c5a08aa183f44c653a46a20c9f826 needed by ocaml-compiler-libs-devel
````
These files are still needed on my side, based on commit fc788ef6b2984ab05179322d8c1e2f04dbac98d2
````
middle_end/backend_intf.cmi \
middle_end/flambda/inlining_decision_intf.cmi \
middle_end/flambda/simplify_boxed_integer_ops_intf.cmi
````

**Comment by mshinwell** [comment]
Presumably the fact that the corresponding source files are `.ml` files without `.mli` files is something to do with it.

**Comment by olafhering** [comment]
I asked earlier already: are these missing interfaces supposed to be visible to the outside, maybe there is a way to hide them and make them "internal/private"?  I do not know enough about OCaml to answer this myself.

**Comment by olafhering** [comment]
Still seen with `4.12.0`

**Comment by lthls** [comment]
If the issue is still with those files:
```
middle_end/backend_intf.cmi \
middle_end/flambda/inlining_decision_intf.cmi \
middle_end/flambda/simplify_boxed_integer_ops_intf.cmi
```

These are mli-only files. The corresponding cmi files are installed, so your tool should find them, but no corresponding implementation is provided since they do not have a corresponding ml file. I suspect that this is what your tool is complaining about, and I believe that your tool should be improved to handle this case correctly.
Apparently (from one of your message above) the tool works around this by hardcoding the mli-only files it knows about (`Annot|Asttypes|Outcometree|Cmo_format|Parsetree`), so if you don't have the time to make your tool more robust, you could append the above files (or modules) to that list, and that should keep you going until another mli-only file is added to the compiler.

**Comment by olafhering** [comment]
Thanks for the explanation. I'm certainly fine with just hiding these three interfaces on my side.
