### ISSUE TITLE
Expose file descriptors as a printable type?

### ISSUE THREAD

**Issue by mjambon** [ocaml/ocaml#9052]
A minimal interface would be:
```ocaml
module File_descr : sig
  type t
  val to_int : t -> int
  val of_int : int -> t
end

type file_descr = File_descr.t
```

This would be useful for logging and debugging, for working with the proc filesystem where it's supported (e.g. process the output of `ls /proc/self/fd`), and for using as a key in various data structures.

If at some point in the future the representation changes to `int64` so as to accommodate more than 2 billion file descriptors per process, the `to_int` function could then fail with an exception.

I'm not sure about any bad consequences of converting arbitrary ints to invalid file descriptor numbers or whether they can be worse than uses after `close`.

**Comment by dra27** [comment]
See discussion in #1990

**Comment by dra27** [comment]
(FWIW, I have a longer answer to write on 1990, but I completely agree with Xavier that we should not have a function which readily maps a `file_descr` to `int`, but I could see a debugging case for providing a `%a` compatible printer, for example)

**Comment by xavierleroy** [comment]
I completely agree with @dra27 that we could provide a way to print `Unix.filedescr` values, for debugging and loggin purposes, but this should not be via conversions between `Unix.filedescr` and `int`, which I hate with a passion.

Just a function with type `Unix.filedescr -> string` would do the job.  For Unix, it's pretty much `string_of_int`, but for Windows the string could be more informative, including not just the value of the handle but also a HANDLE or SOCKET indication and an optional CRT file descriptor.

**Comment by mjambon** [comment]
Just like we have process IDs represented as ints, we could have file descriptor *identifiers* that are ints. And if some future OS doesn't offer an int-like identifier for open files, then it's probably too weird to be supported by the Unix module anyway.

Regardless, what I find often needed in practice is the following:
* a comparable and hashable key for the file descriptor
* a way to convert the file descriptor identifier within the process to what system calls use

So I suppose a `File_descr.to_string` function would work, but it would have to offer some guarantees about the uniqueness and the format of that string, which doesn't seem like a great idea. Instead I'd favor a clear distinction between a file descriptor (the resource) and its identifier (an index in a table for each process, managed by the OS). A minimal signature for a `File_descr` submodule could look like this:

```ocaml
module File_descr : sig
  type t (* abstract *)
  module ID : sig
    type t = int (* concrete *)
  end
  val id : t -> int (* and raise an exception if OS doesn't offer this *)
end
```
