### ISSUE TITLE
Show the line that's causing compiler errors

### ISSUE THREAD

**Issue by strugee** [ocaml/ocaml#9061]
It would be super nice if, when OCaml encountered an error during compilation, it printed out the actual line that caused the error. Rust, IIRC, does this really nicely although if I'm being honest I don't want to break out `rustc` to generate a sample (I can do this later though if anyone wants).

So e.g. instead of getting this:

```
File "interpreter.ml", line 595, characters 22-33:
Error: This pattern matches values of type ast_e
       but a pattern was expected which matches values of type parse_tree
```

I might get something like this instead:

```
and ast_ize_expr_tail (lhs:ast_e) (tail:parse_tree) : ast_e =
                      ^
File "interpreter.ml", line 595, characters 22-33:
Error: This pattern matches values of type ast_e
       but a pattern was expected which matches values of type parse_tree
```

with more `^`s if the range of characters was bigger, of course.

One big reason this would be helpful is that for whatever reason, as a novice OCaml programmer, I've found myself relying on that character position to try and find what I'm doing wrong much more often than in other languages - although of course, other people's experience may differ.

**Comment by hhugo** [comment]
It's this already addressed by https://github.com/ocaml/ocaml/pull/2096 ?

**Comment by strugee** [comment]
Yep! My university has OCaml installed from Fedora so I assumed the bits I was working with would be pretty new, but apparently not new enough. So sorry for the noise!
