### ISSUE TITLE
Compiler unnecessarily asking for a type to be parameterized

### ISSUE THREAD

**Issue by cemerick** [ocaml/ocaml#9069]
```ocaml
type k = [ `A of int | `B of string | `Ks of (string fn * k) list ]
and 'a fn = 'a -> k -> bool
```

Error reported by the compiler is: `In the definition of k, type string fn should be 'a fn`

Changing `k` to use regular variants instead of polys eliminates the error.

@Octachron asked to have this filed here, and said in irc that "it is a regularity test getting awry", attempting to prevent e.g.

```ocaml
type 'a k = [ `Tuple of ('a * 'a) k | `Nil]
```

**Comment by lpw25** [comment]
I'm not sure that I would describe this as the regularity check "getting awry". The current check is simple and well-defined and this definition doesn't meet it.

That being said, it would be nice to accept definitions like this. Maybe someone can come up with a better simple condition to test for regularity.

**Comment by Octachron** [comment]
An orthogonal fix would be to update the error message to describe why the type was deemed non-regular rather than start proposing a fix.

**Comment by cemerick** [comment]
Sorry if the "awry" quotation was out of turn. I was just aiming to capture as much context as possible from the irc exchange so as to inform (maybe much later) action here.

Anyway, I was indeed able to progress past this problem in my actual project by switching over to regular variant type.

More helpful error messages are always good, but speaking strictly as a user, it's not at all clear why regular and polymorphic variants have different treatments in this regard. Maybe there's a principled reason for the divergence (beyond the heritage of implementation details, etc), in which case documentation of such would be good.

This feels like a reasonably bite-sized problem to look at as someone new to the compiler internals. If that sounds right, I might take a look next week.

**Comment by garrigue** [comment]
(Strangely, a comment I thought I had sent didn't appear)

The difference between normal and polymorphic variants is clear enough.
The former defines iso-recursive types, while the latter defines equi-recursive types.
Equality of parametric equi-recursive types is known to be undecidable (IIRC this was proved in the 1990s), so some form of restriction is needed, and regularity (that the expanded form of a type should be a graph) is the most natural one.
OCaml implements a strong form of regularity by requiring that any occurrence of a type constructor inside its own definition use the same parameters. This is a hard requirement, as the expansion algorithm itself assumes this property, so this has to be imperatively checked when you define a type.

While I understand that it would be nice to accept examples such as yours, which are actually regular after one expansion, I do not see any way to change that short of changing the core of the type system.

**Comment by xavierleroy** [comment]
> Equality of parametric equi-recursive types is known to be undecidable (IIRC this was proved in the 1990s)

That's not what I remember.  Equality of parametric equi-recursive types reduces to equivalence of two deterministic pushdown automata, a problem which was not known to be decidable (nor undecidable) for a very long time, but which was proved to be decidable by G. Sénizergues in 1997.  However, Sénizergues' proof does not lead to a reasonably efficient algorithm, and I don't think any such algorithm is known.  Hence  equality of parametric equi-recursive types is best viewed as decidable but intractable in practice.

**Comment by xavierleroy** [comment]
References:
- Reduction of type equality to DPDA equivalence: Marvin Solomon, POPL 1978, https://dl.acm.org/citation.cfm?id=512765
- Sénizergues' decidability proof: http://dept-info.labri.u-bordeaux.fr/~ges/publis_automates.html
- Further work by Colin Stirling: http://homepages.inf.ed.ac.uk/cps/

**Comment by garrigue** [comment]
Indeed, I remembered wrongly. We actually met the same problem when working on recursive modules, and the same discussion (with pointers to Solomon and Sénizergues) is present in our OOPSLA paper:
* A Syntactic Type System for Recursive Modules:
Hyonseung Im, Keiko Nakata, Jacques Garrigue and Sungwoo Park. OOPSLA 2011. http://www.math.nagoya-u.ac.jp/~garrigue/papers/oopsla2011.pdf

We didn't look at Stirling's work.

While the decidability result might be hard to apply directly to the unification algorithm, which needs to be fast, this suggests that one could, in theory, relax the criterion we use in OCaml, for instance to detect regularity in a structural way.

Namely, the current approach is a mix of structural and nominal typing: when it expands a type, it looks at its name to decide whether it should introduce a back-link to an ancestor, requiring equality of parameters, or just expand it structurally. In your example, this breaks on `fn`, which is instantiated in the recursion. However, duplicating the definition of `fn`, using an instantiated version for the recursion, suffices to make the definition acceptable:
```ocaml
type k = [ `A of int | `B of string | `Ks of (string_fn * k) list ]
and string_fn = string -> k -> bool
and 'a fn = 'a -> k -> bool
```
One could probably detect this kind of situation (i.e. decide whether a definition is really regular or not), and convert it internally to allow using the current expansion algorithm.
Note however that this problem is distinct for the equality problem.
Whether this is worth the trouble is dubious; a better error message should be sufficient.

**Comment by gasche** [comment]
The usability issue with the error message is now solved by @Octachron's #9074. The new error message in this example is as follows:

```
# type k = [ `A of int | `B of string | `Ks of (string fn * k) list ]
  and 'a fn = 'a -> k -> bool;;
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^ 
Error: This recursive type is not regular.
       The type constructor fn is defined as
         type 'a fn
       but it is used as
         string fn
       after the following expansion(s):
         k = [ `A of int | `B of string | `Ks of (string fn * k) list ]
       All uses need to match the definition for the recursive type to be regular.
```

I'm considering this issue closed (the idea of extending the regularity criterion doesn't sound like it's going to happen any time soon, or is something we actually want to invest work in).

**Comment by SkySkimmer** [comment]
The new error should probably be explained in the manual.

The meaning of "regular type" is given in http://caml.inria.fr/pub/docs/manual-ocaml/polymorphism.html#sec60 ("5.2 Polymorphic recursion" subsection of "5 Polymorphism and its limitations")
>With a regular polymorphic algebraic data type, the type parameters of the type constructor are constant within the definition of the type.
>[...]
>Non-regular recursive algebraic data types correspond to polymorphic algebraic data types whose parameter types vary between the left and right side of the type definition.

but it's only about recursion, not defining types involving polymorphic variants.

I guess something should be added in "5 Polymorphism and its limitations" or "4.2.1  Weaknesses of polymorphic variants".

**Comment by Octachron** [comment]
This sounds like a good idea. I shall have look at explaining this preexisting restriction in the manual.
