### ISSUE TITLE
Wrong GC ratio multiplier when allocating custom blocks?

### ISSUE THREAD

**Issue by mmottl** [ocaml/ocaml#9073]
The following recent code for allocating custom blocks seems unclear and potentially incorrect:

https://github.com/ocaml/ocaml/blob/9a0ebc18d444a8cdb08396ea694084d07249ec5d/runtime/custom.c#L86-L98

The last argument in the call to `alloc_custom_gen` is multiplied by `caml_custom_major_ratio`.  Shouldn't this be `caml_custom_minor_ratio`?  There doesn't seem to be any other code in the runtime that references `caml_custom_minor_ratio` in any way that would actually affect the GC, i.e. changing the custom minor ratio appears to have no effect.

Furthermore, I don't understand the division by `150` in the preceding argument.  Shouldn't this also be just `100`?  If this is intended, a code comment would be helpful.

**Comment by gasche** [comment]
The code was added by commit 17b64ac2b25f8bc70eca5c589fcb9849f880bdde as part of PR #1738 (released in 4.08), and indeed it looks strange. Would you like to propose a PR to replace the last occurrence of `major_ratio` by `minor_ratio`? (cc @damiendoligez)

On the question of using `150`, @damiendoligez said in the original PR:

> `caml_custom_major_ratio` (M): This is a percentage relative to the major heap size. A complete GC cycle will be done every time 2/3 of that much memory is allocated for blocks in the major heap. Assuming constant allocation and deallocation rates, this means there are at most (M/100 * major-heap-size) bytes of floating garbage at any time. The factor of 2/3 (or 1.5) is (roughly speaking) because the major GC takes 1.5 cycles (previous cycle + marking phase) before it starts to deallocate dead blocks allocated during the previous cycle.

So `heap_size / 150` is really `heap_size * (2/3) / 100` (but faster), if I understand correctly. Feel free to include a comment in your PR :-)

**Comment by mmottl** [comment]
I've mostly taken the above PR comment as is to explain in the code why we are dividing by `150`.

**Comment by nojb** [comment]
Fixed in #9120
