### ISSUE TITLE
Manual discrepency: user let bindings

### ISSUE THREAD

**Issue by clembu** [ocaml/ocaml#9088]
According to the manual , https://github.com/ocaml/ocaml/blob/7fa72b117387c6606d9744a6bde467ef5badfb20/manual/manual/refman/exten.etex#L2601-L2606 
user let bindings contain an `operator-char`

yet apparently the compiler expects a `dot-operator-char` (quoting @Octachron from the discord server):
> octachron Today at 19:30
> Let bindings take a dot-operator-char after the first chars, which are operator-char minus  `.` and `~`.

**Comment by gasche** [comment]
@Octachron is right according to the [lexer implementation](https://github.com/ocaml/ocaml/blob/7fa72b117387c6606d9744a6bde467ef5badfb20/parsing/lexer.mll#L534-L537), which expects `"let" kwdopchar dotsymbolchar`.

Relatedly, `exten.tex` contains several un-named sets of operator symbols (those in the description of `letop` and those in the description of indexing operator), which I think is bad form. It would be better to give names to those classes, to make it easier to compare sets with each other (for example: I *think*, but I'm not sure, that indexing operators accept the same user-chosen operators as prefix operators).

@facelesspanda, if you are interested in submitting a PR against the manual to at least fix the discrepancy, I think that would be nice. For more you should probably discuss with @Octachron to know which changes he thinks are appropriate.
