### ISSUE TITLE
[Manual] Do not use “:” in refs/labels

### ISSUE THREAD

**Issue by Chris00** [ocaml/ocaml#9110]
Labels in the manual, such as [`c:core-xamples`](https://github.com/ocaml/ocaml/blob/trunk/manual/manual/tutorials/coreexamples.etex#L1), are rendered in HTML as `<a id="c:core-xamples"></a>`.  While this is valid HTML, these ID [cannot be used in CSS](https://github.com/ocaml/ocaml.org/issues/1093).  I propose replacing them with `-`.

**Comment by gasche** [comment]
There is an established tradition in LaTeX reference naming of using a `foo:` prefix to indicate a hierarchy level. I think that breaking this tradition in the manual could be a reasonable low-effort solution, but we could also consider improving Hevea to escape colons in that situation.

**Comment by Chris00** [comment]
If it is preferred to improve hevea, it is fine with me too.  I [opened an issue](https://github.com/maranget/hevea/issues/7) to see what hevea authors think about it.

**Comment by gasche** [comment]
Note: the discussion went on in https://github.com/ocaml/ocaml.org/issues/1093 and it looks like simply using `\:` instead of `:` in CSS selectors should work fine. No change to Hevea or the OCaml manual is required.
