### ISSUE TITLE
ocaml doc: two "iterators" sections for List API

### ISSUE THREAD

**Issue by sanette** [ocaml/ocaml#9126]
https://caml.inria.fr/pub/docs/manual-ocaml/libref/List.html

=> there are two sections called "Iterators" (due to the recent addition of Sequences at the end)

it happens also for other modules like Array

**Comment by sanette** [comment]
I would like to emphasize that this is a problem for html navigation, because two sections have the same "id" attribute.

**Comment by pmetzger** [comment]
@sanette If you have a fix for this, you might want to submit a pull request...

**Comment by sanette** [comment]
@pmetzger unfortunately I don't. At this point I've only been post-processing the html. For this issue, I suppose one should go into the manual sources:
* modify the LaTeX source
* maybe put something in Hevea (no, I mean ocamldoc) that detects duplicated "id"s, in which case it could add "_1", "_2", etc.

**Comment by Octachron** [comment]
There is no need at all to look at latex here. The documentation for the `list` module is in `stdlib/list.mli.

**Comment by sanette** [comment]
@Octachron oh yes, of course, that's right. Do you have an idea on how to change the section title?
(I mean : what new title could we use?)

**Comment by sanette** [comment]
Maybe the first one could be "Iterating on a list" and we reserve the word "Iterators" for Seq things?
(I personnally would prefer using "Sequences" instead of "Iterators", but I guess "Iterators" is already well established in other languages)

**Comment by Octachron** [comment]
I think it might be better to merge the two section: the current sequence iterator section could be a subsection of the first iterator section. Maybe `Sequence iterators` would be alright as a name in this case?

**Comment by sanette** [comment]
In order to be consistent, here is the list of all modules that have a section "Iterators" corresponding to Seq.t conversions.
In have put (2) to indicate modules where there are 2 sections called "Iterators".


* Array (2)
* ArrayLabels.html
* Buffer
* BytesLabels
* Float.Array (2)
* Hashtbl
* List (2)
* ListLabels (2)
* Map.S
* Queue
* Set.S
* Stack
* StringLabels
* String

**Comment by dbuenzli** [comment]
You likely don't want to have a whole section for only these two functions. Best would be to move these things in a `{1:converting Converting}` section where they can sit along various converter functions from/to the type.

**Comment by paurkedal** [comment]
An alternative title for sections dealing with "iter", ... and "iter2", ... would be "Iteration" and "Iteration over two lists".  Or even "Iteration over one list" for the former.  (Though, I also think "sequence" is a very good word for `Seq.t`.)

**Comment by xavierleroy** [comment]
Mentioning @johnwhitington , as this discussion could be of interest to him.

A pull request implementing some of the suggestions here would be welcome.

**Comment by pmetzger** [comment]
Wasn't this fixed in #10144? If so, perhaps it should be closed.

**Comment by johnwhitington** [comment]
Yes, this has been fixed.

**Comment by gasche** [comment]
Closed. Thanks @pmetzger for the triaging help!
