### ISSUE TITLE
manual: the list of exceptions should include the Stdlib exceptions

### ISSUE THREAD

**Issue by sanette** [ocaml/ocaml#9129]
https://caml.inria.fr/pub/docs/manual-ocaml/libref/index_exceptions.html

does not currently include exceptions like Not_found, etc.

**Comment by trefis** [comment]
`Not_found` is not defined in the stdlib, it is a [predefined exception](https://github.com/ocaml/ocaml/blob/trunk/typing/predef.ml#L100).
Predefined types and value are documented in [the core library](http://caml.inria.fr/pub/docs/manual-ocaml/core.html) section of the manual.

**Comment by sanette** [comment]
I know but don't you think it's confusing ?

The page https://caml.inria.fr/pub/docs/manual-ocaml/libref/index.html
does include Stdlib which does mention these exceptions, 
and the same page does have an entry "index of exceptions", which does not mention these..

**Comment by sanette** [comment]
Just compare with "index of values" , from the same general index page (so same section of the manual as "index of exception"). It *does* mention all the values that belong to "Pervasives", while the Pervasives module is presented in the "Core Library" section of the manual.
The questin would be the same for predefined types; to my opinion it would be more natural from the user viewpoint to include them in the "index of types".

**Comment by trefis** [comment]
Ah, you are correct: I had forgotten these exceptions were being reexported by `Stdlib`.
Then they should indeed be in the index.

**Comment by ashwinpn** [comment]
take

**Comment by stedolan** [comment]
Fixed by #9580
