### ISSUE TITLE
natdynlink problem and fix ... maybe.

### ISSUE THREAD

**Issue by houndofsound** [ocaml/ocaml#9135]
I have a dynlink module loading another dynlink module.
it works ok in bytecode but not native.

the last few lines of [loadunits] in natdynlink.ml:
...
  ndl_run handle "_shared_startup";
  List.iter (ndl_run handle) defines;
 { implems = new_implems; ifaces = new_ifaces }

[implems] does contain the outer dynunit but the call to [ndl_run] 
leads to the inner [loadunit] invocation that accesses [global_state] as seen by the outer.
the inner therefore does not see the required dynunit.

as a test I changed the code to:
  ndl_run handle "_shared_startup";
  global_state := { implems = new_implems; ifaces = new_ifaces };
  List.iter (ndl_run handle) defines;
 { implems = new_implems; ifaces = new_ifaces }

and the code ran as expected.
unfortunately I have no idea of the legitimacy of that hack and can only
point to the difference in behaviour to bytecode without it.

**Comment by houndofsound** [comment]
a patch accommodating the [priv] flag....

+++ otherlibs/dynlink/natdynlink.ml	2019-11-22 23:56:53.533348823 +0000
@@ -167,7 +167,7 @@
          raise (Error(Unavailable_unit name))
     ) ui.dynu_imports_cmx
 
-let loadunits filename handle units state =
+let loadunits priv filename handle units state =
   let new_ifaces =
     List.fold_left
       (fun accu ui -> add_check_ifaces !allow_extension filename ui accu)
@@ -182,15 +182,18 @@
   let defines = List.flatten (List.map (fun ui -> ui.dynu_defines) units) in
 
   ndl_run handle "_shared_startup";
+  let new_state={ implems = new_implems; ifaces = new_ifaces } in
+  if not priv then global_state := new_state;
   List.iter (ndl_run handle) defines;
-  { implems = new_implems; ifaces = new_ifaces }
+  new_state
 
 let load priv filename =
   init();
   let (filename,handle,units) = read_file filename priv in
-  let nstate = loadunits filename handle units !global_state in
+  let nstate = loadunits priv filename handle units !global_state in
   if not priv then global_state := nstate

**Comment by houndofsound** [comment]
a patch accommodating the [priv] flag ...
```
+++ otherlibs/dynlink/natdynlink.ml	2019-11-22 23:56:53.533348823 +0000
@@ -167,7 +167,7 @@
          raise (Error(Unavailable_unit name))
     ) ui.dynu_imports_cmx
 
-let loadunits filename handle units state =
+let loadunits priv filename handle units state =
   let new_ifaces =
     List.fold_left
       (fun accu ui -> add_check_ifaces !allow_extension filename ui accu)
@@ -182,15 +182,18 @@
   let defines = List.flatten (List.map (fun ui -> ui.dynu_defines) units) in
 
   ndl_run handle "_shared_startup";
+  let new_state={ implems = new_implems; ifaces = new_ifaces } in
+  if not priv then global_state := new_state;
   List.iter (ndl_run handle) defines;
-  { implems = new_implems; ifaces = new_ifaces }
+  new_state
 
 let load priv filename =
   init();
   let (filename,handle,units) = read_file filename priv in
-  let nstate = loadunits filename handle units !global_state in
+  let nstate = loadunits priv filename handle units !global_state in
   if not priv then global_state := nstate
```

**Comment by lpw25** [comment]
Your patch seems to be for the code before dynlink was rewritten. What version of OCaml are you seeing this problem on?

**Comment by houndofsound** [comment]
indeed, 4.07.1.
I see the new code does away with global_state in the module!
so that's probably that then...
may I draw your attention to a real issue:
https://github.com/ocaml/ocaml/issues/7893
that I raised (with fix) during mantis days.
the 4.10 code I just looked at has the same problem.
thanks.
