### ISSUE TITLE
The compiler gets confused when passed relative paths (Error: Could not find the .cmi file for interface …)

### ISSUE THREAD

**Issue by cpitclaudel** [ocaml/ocaml#9140]
Hi all,

Calling `ocamlc` or `ocamlopt` with a relative path to both a `.mli` and `.ml` only works if both reside in the current directory.

In the example below, I've creates `test/a.ml` and `test/a.mli` before calling `ocamlopt a.mli a.ml`.  The problem is that after compiling `test/a.mli` file to `test/a.cmi`, the compiler tries to compile `test/a.ml` and looks for `a.cmi` in the *current* directory, instead of `test/`.  Copying `test/a.cmi` manually to `a.cmi` fixes the problem. 

Setup:

```bash
$ cd /tmp/
$ mkdir test
$ echo 'val a: int' > test/a.mli
$ echo 'let a = 3' > test/a.ml
```

Error:

```
$ ocamlopt test/a.mli test/a.ml
File "test/a.ml", line 1:
Error: Could not find the .cmi file for interface test/a.mli.
```

Workaround:

```
$ (cd test; ocamlopt a.mli a.ml)
$ ls test/
a.cmi  a.cmx  a.ml  a.mli  a.o	a.out
```

Note that copying the `.cmi` file into the current directory works:

```
$ ocamlopt test/a.mli test/a.ml
File "test/a.ml", line 1:
Error: Could not find the .cmi file for interface test/a.mli.
$ cp test/a.cmi a.cmi
$ ocamlopt test/a.mli test/a.ml
```

I'm not sure whether this is a bug report or a feature request; at least, it's non-intuitive behavior: the `cmi` gets created, then OCaml complains about not finding it.

Thanks!

**Comment by nojb** [comment]
This is expected. You must use the `-I` flag to tell the compiler where to find `.cmi` files:
```
ocamlopt -I test test/a.mli test/a.ml
```

**Comment by lpw25** [comment]
To a certain extent the confusing -- and a bit dubious -- aspect of the current behaviour is that it automatically adds the current directory to the list of include directories.

**Comment by cpitclaudel** [comment]
> This is expected. You must use the -I flag to tell the compiler where to find .cmi files:

That's brittle: f there's an `a.cmi` file in the current directory, the compiler will pick that up first instead of the one in the -I path.

> To a certain extent the confusing -- and a bit dubious -- aspect of the current behaviour is that it automatically adds the current directory to the list of include directories.

Agreed.  Is there a way to remove the current directory from the include list?

**Comment by lpw25** [comment]
Looking at the code I think there is no way to avoid having the current directory in the include list.

**Comment by trefis** [comment]
I find that surprising. In merlin we've [added](https://github.com/ocaml/merlin/commit/85b1a6f0b439fd4e8b0dfedcc51bb34ec99c6534) a directive to exclude the current directory from the load path.
Why do you think we can't do something similar in the compiler?

**Comment by trefis** [comment]
Ah… I guess you just meant "there is currently no way".

**Comment by VishalDalwadi** [comment]
Hi, I am new in these corners and would like to work on this issue.

**Comment by gasche** [comment]
#11131 is a draft PR that proposes a new option (currently named `-removecwd`) to remove the current directory from the default search path. Reviewers welcome :-)
