### ISSUE TITLE
Limiting the function recursion

### ISSUE THREAD

**Issue by XVilka** [ocaml/ocaml#9148]
It is not an uncommon recommendation is to limit recursion by the logic in the function, but quite often it just limited with amount of "tries" or "depth" going further. I thought, what if the language itself could provide the shorthand for writing such limited recursion functions?
Maybe something like:
```ocaml
let rec [@limit=5] nasty_function x =
    nasty_function (x + 1)
```
where it will stop after going in depth 5 times.
What do you think? Would it be a useful language concept?

**Comment by gasche** [comment]
To be honest, I don't like the idea. What's the failure mode once you reach the recursion limit? I doesn't sound very usable without an explicit way to define the failure mode, and I wouldn't encourage this kind of transformation that changes a lot the rasoning model for the function.

It's not too hard to do this yourself as a library:

```ocaml
(* the usual fixpoint combinator for functions *)
val fix : (('a -> 'b) as 'f -> 'f) -> 'f

val depth_bounded_fix : limit:int -> (('a -> 'b) as 'f -> 'f) -> ('a -> 'b option)

let bounded_nasty =
  depth_bounded_fix ~limit:5 (fun nasty_function x -> nasty_function (x + 1))
```

**Comment by XVilka** [comment]
Indeed, you are right. Feel free to close the bug if you think it is unnecessary.
