### ISSUE TITLE
Executables produced by ocamlopt -linkall do not inlude the symbol caml_get_global_data

### ISSUE THREAD

**Issue by jhjourdan** [ocaml/ocaml#9151]
```
$ touch test.ml
$ ocamlopt -linkall test.ml
$ objdump -t a.out  | grep caml_get_global_data
$
```

The reason is that the GNU linker does not link the object file `meta.o` (part of `libasmrun.a`) because it is not referenced anywhere.

The symbol `caml_get_global_data` is useful in bytecode mode by the toplevel. It is a dummy function in native mode, but it is referenced by compilerlibs. If compilerlibs is used directly by the program, the C linker will no longer skip `meta.o`, so this is apparently not an issue. However, if the program does *not* use compiler lib, but loads a plugin (via Dynlink) which uses it, then Dynlink will refuse to load the plugin because of the missing symbol.

The issue described above can be reproduced with OCaml < 4.09. With OCaml >= 4.09, because of #2268, compilerlibs is included in Dynlink. Thus, as soon as `dynlink.cmxa` is passed to the final `ocamlopt` call with `-linkall`, Dynlink creates a dependency to `meta.o`, so the problem magically disappears for recent OCaml.

I am not really sure there is something to be done here. On the one hand, the wrong behavior is fixed for new versions of OCaml. On the other hand, it has been fixed by an unrelated PR (#2268), and nothing will prevent future changes to make the problem appear again.

My proposal is to pass `-Wl,-whole-archive` and `-Wl,-no-whole-archive` (or alike) to the C compiler when producing the final executable, so that we mae sure `meta.o` is included. Another option would be to add a test to the testsuite (not particularly easy to write, since the test would depend on compilerlibs and dynlink...) for making sure that we notify when the issue appears again.

"wait and see"

**Comment by xavierleroy** [comment]
This is an obscure problem that no longer shows up in 4.09 and more recent.  So, I move to close.
