### ISSUE TITLE
could ocamltest show the failing logs?

### ISSUE THREAD

**Issue by gasche** [ocaml/ocaml#9158]
My usage of ocamltest typically results in failure reports (on my terminal) that look like this:

```
 ... testing 'magic_number.ml' with 1 (bytecode) => failed (Running program /home/gasche/Prog/ocaml/github-trunk/testsuite/tests/utils//_ocamltest/tests/utils/magic_number/ocamlc.byte/magic_number.byte without any argument: command
/home/gasche/Prog/ocaml/github-trunk/testsuite/tests/utils//_ocamltest/tests/utils/magic_number/ocamlc.byte/magic_number.byte 
failed with exit code 2)
```

Whenever I see this kind of failure messages, I go explore the `_ocamltest` directory (whose location is given in the failure message) to find the log file that will actually contain useful information for me, to know what the failure cause was. When I was younger I used to jump at the `.log` file at the root of the _ocamltest directory, but I learned rather quickly that its content is rarely useful to diagnose the error; the information I want is contained in a `.output` file in a subdirectory, usually either `ocamlc.byte.output` (if it was a compilation error) or `<testname>.byte.output` (if it was a runtime error).

It would be fairly useful for me to cut the chase by having the output(s) of the failing command printed to the terminal when I'm running the test. Ideally this would be the case by default (maybe there is a risk of breaking the reporting machinery if the output is too strange? does that actually happen in practice?), or it could be conditioned on a `OCAMLTEST_VERBOSE=true` environment control that I can use for both the Makefile and when invoking `ocamltest` directly.

**Comment by gasche** [comment]
(cc @shindere @nojb)

**Comment by dra27** [comment]
I wonder if instead what would be clever is if the reporting machinery could display the appropriate logs/output (possibly with `ocamltest`s help). I’ve been pondering at various points adding some analysis to persist the artefacts of failed tests for CI runs.

**Comment by shindere** [comment]
Yeah there is definitely room for improvmeents here.

One thing for instance would be to include the content of the relevant
output files in the log file itself, whose readability could/should be
improved, I know.

That's something I have been wanting to work on for a long time, just
lacking time.

One other possible way of improving things would be to be able to get
the failing logs and output files out of the CI system. This will
require a bit of help from Jenkins and so far I have not been able to
find a nice way to put "artifacts" somewhere even for a failing build.
