### ISSUE TITLE
signature digest differences

### ISSUE THREAD

**Issue by houndofsound** [ocaml/ocaml#9173]
is it correct that
let v = (); ()
and 
let v = ()
produce the same signature but different digests?

**Comment by houndofsound** [comment]
correction:

module type M  =
  module type of
    struct
      let f =
        let _ = () in ()
    end

vs

module type M  =
  module type of
    struct
      let f =
        (); ()
    end

the problem goes away with -no-keep-locs

**Comment by houndofsound** [comment]
that's 4.07 - 4.08

**Comment by Octachron** [comment]
Different cmis produce different digests. It is not clear to me if there is any issues hidden behind your questions. I am thus closing. Please feel free to ask supplementary questions on https://discuss.ocaml.org .

**Comment by gasche** [comment]
Signature arise of `.mli` files. If you have a `.mli` file and change the implementation but not the interface, the `.cmi` should remain identical. If you don't use `.mli` files, a signature gets inferred from your `.ml` file, and changes in the implementation may result in the signature changing (in particular, in the locations, which are often the most fragile aspect).

**Comment by houndofsound** [comment]
are you saying that the signature inferred for the module type above is
retaining location information for elements of the implementation within itself?
which aspect of the signature produced for the above would hold such a location
given that there is nothing else defined before or after function f. 
I originally posted without the module type wrapper after going too far in reducing the case. 
and when there is no wrapper there is no difference in cmi generated.
is that to be expected given that it is the definition of function f that is causing the discrepancy?

**Comment by gasche** [comment]
I would guess (I haven't tried) that the module element (in the signature) may record the location of the whole module definition (from `module` to `end`), so that the extra line break makes a difference.
