### ISSUE TITLE
Internal runtime state variables are being made public in 4.10

### ISSUE THREAD

**Issue by gadmm** [ocaml/ocaml#9179]
There is an unintended consequence of #8713 which does not seem to have been discussed in that PR: apart from `caml_compare_unordered`, all the runtime state variables moved to Caml_state could only be accessed before by defining `CAML_INTERNALS` or with an `extern` declaration. Now it is all as if they are public. This is due to `mlvalues.h` including `domain_state.h` unconditionally, and `domain_state.h` not using `CAML_INTERNALS` (as it did at some point). There is at least some documentation missing stating that they are internal, and preferably one wants a mechanism based on the `CAML_INTERNALS` macro.

One complicated solution (I imagine) would be to repurpose the `Caml_state_field` macro to perform some static check according to a list of public Caml_state variables, using some complicated macro trick.

One simple and more forward-looking solution would be to make `Caml_state` itself internal, declare that `caml_compare_unordered` should in fact be internal, and provide a proper interface to query and change `caml_compare_unordered`, at the cost of a theoretical breaking change. (See [here](https://github.com/ocaml-multicore/ocaml-multicore/issues/245) for an example of code in the wild that uses `caml_compare_unordered` as a public variable.)

cc @stedolan, @kayceesrk, @gasche.

(This supersedes my comment to #9160 which refered to a problem with `compatibility.h` rather than `Caml_state` iself.)

**Comment by kayceesrk** [comment]
Thanks for bringing this up. Simply making `Caml_state` itself internal would not work. There is at least one example (`caml_local_roots` in `memory.h`) of a publicly accessible variable that has been moved to `Caml_state`. `caml_local_roots` was public since `CAMLparam*` which uses `caml_local_roots` can be used without defining `CAML_INTERNALS`. To do it in a backwards compatible manner, we will need to distinguish between public and internal variables.

**Comment by gadmm** [comment]
Indeed, I forgot `caml_local_roots`, which as I understand is internal but must be made public for technical reasons.

**Comment by stedolan** [comment]
Good point! Is it just `caml_local_roots` and `caml_compare_unordered` that are affected?

**Comment by gadmm** [comment]
That is indeed what I remember from my research of a test that did not require me to define `CAML_INTERNALS` in my other PR.

Edit: to be clearer for people reading it out of context, _all_ internal variables of the domain state are being made public, except those two which are already somewhat public.

**Comment by gadmm** [comment]
I was thinking maybe making the definition of the `DOMAIN_STATE` macro dependent on `CAML_INTERNALS` in some way could do the trick. Is somebody having a look currently?

**Comment by gadmm** [comment]
OCaml ships since 4.10 with these new headers with no indication that the domain state is internal (or which fields are public and which ones are private). For instance there is no way now for the user to know that `Caml_state->compare_unordered` is public but the others are private (or that it has changed since 4.10, if this is what implicitly happened). Even documentation in the manual or as comment in the header file would go a long way.

**Comment by gadmm** [comment]
Why would this be stale?

**Comment by gadmm** [comment]
Please disable the stale bot, or set a longer delay more relevant for the pace of OCaml development (e.g. 10 years).
