### ISSUE TITLE
OCaml 4.09.0 build fails on Gentoo Linux: No rule to make target '../stdlib/ocaml-4.09.0spacetime.mli'

### ISSUE THREAD

**Issue by rseichter** [ocaml/ocaml#9189]
As shown below, ocamllex fails with "no rule to make target". I have tried to configure with either of --enable-spacetime and --disable-spacetime, but this does not seem to change the outcome.
```
../boot/ocamlrun ../ocamlc -nostdlib -I ../stdlib -pp 'sh ./remove_DEBUG' -I
  ../utils -I ../parsing -I ../typing -I ../driver -I ../bytecomp -I ../toplevel
  -I ../stdlib -I ../compilerlibs -I ../otherlibs/str -I ../otherlibs/dynlink -I
  ../otherlibs/dynlink/native -I ../otherlibs/unix -absname -w
  +a-4-9-41-42-44-45-48 -warn-error A -safe-string -strict-sequence
  -strict-formats -bin-annot -c odoc_latex_style.ml
251 states, 2458 transitions, table size 11338 bytes
../boot/ocamlrun ../boot/ocamllex odoc_ocamlhtml.mll make[3]:
  *** No rule to make target '../stdlib/ocaml-4.09.0spacetime.mli',
  needed by 'stdlib_man/Stdlib.3o'.  Stop.
make[3]: *** Waiting for unfinished jobs....
111 states, 2871 transitions, table size 12150 bytes
make[3]: Leaving directory '/mnt/sdb3/tmp/portage/dev-lang/ocaml-4.09.0/work/ocaml-4.09.0/ocamldoc'
make[2]: *** [Makefile:1092: ocamldoc] Error 2
make[2]: Leaving directory '/mnt/sdb3/tmp/portage/dev-lang/ocaml-4.09.0/work/ocaml-4.09.0'
make[1]: *** [Makefile:450: all] Error 2
make[1]: Leaving directory '/mnt/sdb3/tmp/portage/dev-lang/ocaml-4.09.0/work/ocaml-4.09.0'
make: *** [Makefile:463: world] Error 2
```

**Comment by nojb** [comment]
It looks like a problem with the Gentoo package. There is not much we can do, you will probably get a better anwer by asking directly to the Gentoo maintainers. I just note that your console dump seems to be missing slashes, eg:
```
*** No rule to make target '../stdlib/ocaml-4.09.0spacetime.mli',
```
should have a slash between `ocaml-4.09` and `spacetime.mli`.

**Comment by rseichter** [comment]
> you will probably get a better anwer by asking directly to the Gentoo maintainers.

I am currently trying to update Gentoo's existing (and working) OCaml 4.05 ebuild to version 4.09, so I could only ask myself. 😉

> I just note that in your console dump there seems to be missing slashes, eg:
> ```
> *** No rule to make target '../stdlib/ocaml-4.09.0spacetime.mli',
> ```
> should have a slash between `ocaml-4.09` and `spacetime.mli`.

The build log shows exactly that, `ocaml-4.09.0spacetime.mli` without a second slash. As I am not applying any Gentoo-specific patches before calling `configure`, I wonder what could cause this?

**Comment by nojb** [comment]
Got it, do you have a link to the build script you are trying to use ? That may give us some clues.

**Comment by xavierleroy** [comment]
Please try to build manually first, before trying your build script.  I just started a Gentoo VM using LXC, did the following, and it worked just fine
```
wget http://caml.inria.fr/pub/distrib/ocaml-4.09/ocaml-4.09.0.tar.gz
tar xzf ocaml-4.09.0.tar.gz 
cd ocaml-4.09.0/
./configure
make -j2 world.opt
make -C testsuite all
```
Please try exactly the same steps.  If they fail, the problem is on our side.  If they succeed, the problem is very likely on your side.  Try to compare the build steps of your script with the default build above, that might help understanding what's going on.

**Comment by rseichter** [comment]
We are still investigating. Our build succeeds if we configure with `--disable-ocamldoc`, but fails otherwise. To make sure: The expected target name would be `../stdlib/ocaml-4.09.0-spacetime.mli`?

**Comment by nojb** [comment]
I think it should rather be `../stdlib/spacetime.mli`.

**Comment by rseichter** [comment]
@nojb Thanks, we suspected as much. When and where is the target name being generated? Something during the build seems to inject "ocaml-4.09.0". We're of course searching in our Portage build system first, but it would help us to know how exactly the string `../stdlib/spacetime.mli` is generated.

**Comment by nojb** [comment]
you can look in `ocamldoc/Makefile.docfiles` (included from `ocamldoc/Makefile`).

**Comment by Octachron** [comment]
This sounds like this could happen if `P` were defined to `ocaml-4.09.0-` in https://github.com/ocaml/ocaml/blob/trunk/stdlib/StdlibModules#L84

**Comment by rseichter** [comment]
@Octachron You may have hit the motherlode. Gentoo's Portage build system uses $P to hold the ebuild name and version, in this case "ocaml-4.09.0", and I was wondering if that has somehow ended up in the OCaml build.

**Comment by rseichter** [comment]
It's kinda funny that the hours effort spent boil down to a single character. When I change the `?=` operand in [this line](https://github.com/ocaml/ocaml/blob/trunk/stdlib/StdlibModules#L21) to a plain `=`, Gentoo's build system successfully executes the OCaml build.

I am of course wondering if the OCaml authors intentionally used `?=` in StdlibModules?

**Comment by XVilka** [comment]
Maybe it makes sense to rename the OCaml variable in the long run? To prevent such accidental hits in the future.

**Comment by nojb** [comment]
> I am of course wondering if the OCaml authors intentionally used `?=` in StdlibModules?

I think `?=` can safely be turned into `=`. @diml (original author of this code) will be able to confirm.

**Comment by ghost** [comment]
Just had a look at the makefiles that include `stdlib/StdlibModules` and it seems that this can indeed be changed. IIRC at some point `P` was set to something else when building the documentation, but it doesn't seem to be the case anymore.
