### ISSUE TITLE
Correcting person's names (in file Changes)

### ISSUE THREAD

**Issue by Fourchaux** [ocaml/ocaml#9190]
Correct (or better) way to spell people's names?

- L321: Angelettion / Angeletti
- L1072: Frish / Frisch
- L1206: Garrique / Garrigue
- L381: Whitequark / whitequark
- L2634: Jeremie / Jérémie
- L159_668_738_798_1500_1537_2441: Nicolas Ojeda Bar / Nicolás Ojeda Bär

**Comment by nojb** [comment]
Thanks! Would you like to propose a PR?

**Comment by Fourchaux** [comment]
Done.

**Comment by nojb** [comment]
Fixed in #9194
