### ISSUE TITLE
Backtrace difference between ocamlopt/ocamlc

### ISSUE THREAD

**Issue by rgrinberg** [ocaml/ocaml#9201]
I know that backtraces in the presence of tail calls aren't really good, but I'm surprised that ocamlc produces a worse backtrace than ocamlopt.

Consider this program:
```ocaml
let rec run () = bar ()
and bar () = failwith "foo"
let () = run ()
```

ocamlc gives this backtrace:
```
Fatal error: exception Failure("foo")
Raised at file "stdlib.ml", line 29, characters 22-33
Called from file "foo.ml", line 3, characters 9-15
```

while ocamlopt gives:
```
Raised at file "stdlib.ml", line 29, characters 17-33
Called from file "foo.ml" (inlined), line 1, characters 17-23
Called from file "foo.ml", line 3, characters 9-15
```

Why is the extra frame dropped by ocamlc? it's useful.

**Comment by gasche** [comment]
(cc @let-def who I believe worked last on backtraces+inlining.)

**Comment by xavierleroy** [comment]
> Why is the extra frame dropped by ocamlc? it's useful.

You have it backward.  

ocamlc / ocamlrun report the frames as they exist on the call stack. namely the call to `run()` on line 3, the other two calls (`bar()` and then `failwith()`) being tail-calls and having no existence on the call stack.  It is not dropping any frame.

ocamlopt also reports pseudo-frames that don't exist on the call stack but try to reflect the effect of function inlining.  Here, `bar()` was inline-expanded to `failwith "foo"` in the body of `run()`, so ocamlopt dutifully adds an entry to this effect in the backtrace.

It could be questioned whether pseudo-frames corresponding to function inlining should be reported in the case where the inlined function was tail-called, as in this example.  (I can't remember if this was discussed earlier.)  In favor: you get more informative backtraces, everyone likes that.  Against: it causes the kind of confusion that @rgrinberg is reporting.

**Comment by lthls** [comment]
By the way, with flambda you get even different backtraces: with the default settings you get this:
```
Fatal error: exception Failure("foo")
Raised at file "stdlib.ml", line 29, characters 17-33
Called from file "test.ml" (inlined), line 2, characters 13-27
Called from file "test.ml" (inlined), line 1, characters 17-23
Called from file "test.ml", line 3, characters 9-15
```

With `-O3`, you get no backtrace, because flambda has removed all function calls and transformed the regular `raise` into `raise_notrace`

**Comment by gasche** [comment]
> and transformed the regular raise into raise_notrace

Err, turning uncaught exceptions raisepoints into `raise_notrace` sounds like a dubious idea to me. Shouldn't you use `raise_notrace` only when the optimizer can tell that the exception will in fact be caught, and the backtrace will not be captured by the handler (or at least a best-effort in that direction)?

**Comment by lthls** [comment]
I'd have to check the details, this could be a special case because the raise is at toplevel.

**Comment by lthls** [comment]
Actually, I simply forgot to compile the test with `-g`. Without `-O3`, there is a call to `Stdlib.failwith`, which is compiled with `-g` and raise normally; with `-O3`, this call is inlined and whether it raises normally or without trace depends on the `-g` setting.

**Comment by xavierleroy** [comment]
Three months later, I'm closing this report because there is nothing wrong with ocamlc and ocamlopt occasionally producing different exception backtraces.  Each compiler is doing a best effort to describe the call chain that led to the exception, but compilation and optimization strategies differ and result in different backtraces.  This is all right.  Having exactly the same backtraces is not an objective.
