### ISSUE TITLE
Feature request: extension point short cut

### ISSUE THREAD

**Issue by bobzhang** [ocaml/ocaml#9204]
```ocaml
{%obj x = 2}
```

The same as
```ocaml
[%obj{ x = 2}]
```

**Comment by gasche** [comment]
This looks like a reasonable extension of, say, `begin%foo ... end` to me. I wonder if `delimiter%foo ... delimiter` can be generally rewritten into `[%foo delimiter ... delimited]`, or if there are conflicts or unpleasant consequences.

(I wondered if there was a conflict with the new syntax `{%foo| ... |}` of #8820, merged in trunk, but I don't think there is. Note that if we had accepted the short form `{%foo ...}` that was initially suggested for this feature (as sugar for `[%foo {|...|}]` when `...` has balanced braces), then there would be a conflict.)

**Comment by Drup** [comment]
> I wonder if `delimiter%foo ... delimiter` can be generally rewritten into `[%foo delimiter ... delimited]`, or if there are conflicts or unpleasant consequences.

That reminds me of a time where I wanted to introduce arbitrary user-defined delimiters, in the style of user-defined operators .... People hinted at me that it was a Bad Idea. :p 

The idea has some merit, but I think it would be even better if it wasn't (only) for ppxs!
