### ISSUE TITLE
Update Thread module doc to clarify that it's used for system threads

### ISSUE THREAD

**Issue by yawaramin** [ocaml/ocaml#9206]
As per this discussion: https://discuss.ocaml.org/t/thread-library-is-deprecated/4637

We need to update the module documentation of the [`Thread`](https://caml.inria.fr/pub/docs/manual-ocaml/libref/Thread.html) module to mention that it's using system threads now, not lightweight threads.

Related to #7687

**Comment by xavierleroy** [comment]
Thanks for the suggestion.  There are other things that need updating in `otherlibs/systhreads/thread.mli`.  For example, `kill` is not available (always fails) in this implementation; this should be documented, the function marked deprecated, and removed eventually.  The comments on the `wait_*` functions are odd, and these functions are probably redundant with the functions from the `Unix` module.
