### ISSUE TITLE
Ocamlyacc: overflow with 128 or more parsers

### ISSUE THREAD

**Issue by andreasabel** [ocaml/ocaml#9207]
`ocamlyacc` produces ill-formed `.ml` files if a grammar has 128 or more entrypoints.  
This generated `.ml` file was produced by `ocamlyacc` from a BNFC-generated `.mly` file:
```ocaml
...
let pSuper (lexfun : Lexing.lexbuf -> token) (lexbuf : Lexing.lexbuf) =
   (Parsing.yyparse yytables 126 lexfun lexbuf : Abstest.super)
let pSwitch (lexfun : Lexing.lexbuf -> token) (lexbuf : Lexing.lexbuf) =
   (Parsing.yyparse yytables 127 lexfun lexbuf : Abstest.switch)
let pSynchronized (lexfun : Lexing.lexbuf -> token) (lexbuf : Lexing.lexbuf) =
   (Parsing.yyparse yytables -128 lexfun lexbuf : Abstest.synchronized)
let pTemplate (lexfun : Lexing.lexbuf -> token) (lexbuf : Lexing.lexbuf) =
   (Parsing.yyparse yytables -127 lexfun lexbuf : Abstest.template)
...
```
`ocamlc` reports a type error:
```
File "Partest.ml", line 5129, characters 4-28:
5129 |    (Parsing.yyparse yytables -128 lexfun lexbuf : Abstest.synchronized)
           ^^^^^^^^^^^^^^^^^^^^^^^^
Error: This expression has type
         int -> (Lexing.lexbuf -> 'a) -> Lexing.lexbuf -> 'b
       but an expression was expected of type int
```
The buggy `.ml` code is produced by this print statement:
https://github.com/ocaml/ocaml/blob/4e6e9123287405a08b349c3e0e12d53000e8534d/yacc/reader.c#L1701-L1703
Seems like the `entry` component of the `bucket` type was (needlessly?) dimensioned to bytesize, not catering for values >=128:
https://github.com/ocaml/ocaml/blob/4e6e9123287405a08b349c3e0e12d53000e8534d/yacc/defs.h#L137-L150

I attach a `.mly` file created from this MWE BNFC file:
```
EInt. Exp ::= Integer;
coercions Exp 127;
```
[Par128entrypoints.mly.zip](https://github.com/ocaml/ocaml/files/3997930/Par128entrypoints.mly.zip)

**Comment by nojb** [comment]
Thanks for the report. Did you try patching `ocamlyacc` by changing `char entry` to `short entry` and trying it on your grammar? I'm wondering if there are more places where this assumption on the number of entries is made...

**Comment by dra27** [comment]
In this use case, are you able to use Menhir instead? Unless the fix is trivial, it’d seem better to alter ocamlyacc merely to display an error message if an attempt is made to generate more than 127 entry points.

**Comment by andreasabel** [comment]
If I supply a grammar with 256 entry points (or more) `ocamlyacc` complains:
```
File "Par256entrypoints.mly", line 21: more than 256 entry points
```
(Note the slight in accuracy in the error message: correct would be `more than 255` entry points.)
Thus, it seems that the idea was to allow 255 entry points, but printing `char` as a signed byte with `%d` below reduces this to 127 entry points.
https://github.com/ocaml/ocaml/blob/4e6e9123287405a08b349c3e0e12d53000e8534d/yacc/reader.c#L1701-L1703

> In this use case, are you able to use Menhir instead?

Well, I stumbled on this problem while trying to make [BNFC](https://github.com/BNFC/bnfc) more robust. BNFC's ocaml backend currently only targets ocamllex/ocamlyacc, writing a new backend to target Menhir is probably the long-term viable process.

> Did you try patching ocamlyacc ...?

No, I have not familiarized myself with the ocaml build process...

**Comment by nojb** [comment]
> No, I have not familiarized myself with the ocaml build process...

It is actually quite easy:

```
git clone https://github.com/ocaml/ocaml
cd ocaml
./configure
cd yacc
make
```
(`ocamlyacc` lives in the `yacc` subdirectory). The above creates an `yacc/ocamlyacc` executable. If you modify the source in the `yacc` directory just repeat the `make` step (in the `yacc` subdirectory) to rebuild the `ocamlyacc` executable.

**Comment by andreasabel** [comment]
Thanks, I will work on a PR then.
