### ISSUE TITLE
Access to C symbols dropped inbetween two calls to Dynlink with OCaml 4.10

### ISSUE THREAD

**Issue by kit-ty-kate** [ocaml/ocaml#9209]
`nocrypto` currently fails on OCaml 4.10 with the following error message:
```
- + ocamlfind ocamldep -package zarith -package ppx_sexp_conv -package bytes -package sexplib -package cstruct -modules src/nocrypto.mli > src/nocrypto.mli.depends
- File "_none_", line 1:
- Error: Cannot load ppx_sexp_conv: error loading shared library: Dynlink.Error
-        (Dynlink.Cannot_open_dll "(Failure\n 
-        \"/home/opam/.opam/4.10.0+trunk/lib/base/base.cmxs: undefined symbol:
-        Base_internalhash_fold_float\")")
```
Trying to debug the issue further made me write the following code:
```
let () =
  Dynlink.loadfile "/home/opam/.opam/4.10.0+trunk/lib/sexplib0/sexplib0.cmxs";
  Dynlink.loadfile "/home/opam/.opam/4.10.0+trunk/lib/base/base_internalhash_types/base_internalhash_types.cmxs";
  Dynlink.loadfile "/home/opam/.opam/4.10.0+trunk/lib/base/caml/caml.cmxs";
  Dynlink.loadfile "/home/opam/.opam/4.10.0+trunk/lib/base/shadow_stdlib/shadow_stdlib.cmxs";
  Dynlink.loadfile "/home/opam/.opam/4.10.0+trunk/lib/base/base.cmxs"
```
which compiles perfectly but fails with the same error:
```
Fatal error: exception Dynlink.Error (Dynlink.Cannot_open_dll "Dynlink.Error (Dynlink.Cannot_open_dll \"(Failure\\n  \\\"/home/opam/.opam/4.10.0+trunk/lib/base/base.cmxs: undefined symbol: Base_internalhash_fold_float\\\")\")")
```
Trying to decompose the issue a bit further here is a very minimal test case:
```
$ cat test.c
int testdynfail() {
  return 0;
}
$ cat lib.ml
external test : unit -> unit = "testdynfail"
$ cat lib2.ml
let test = Lib.test
$ cat dyn.ml
let () =
  Dynlink.loadfile "lib.cmxs";
  Dynlink.loadfile "lib2.cmxs"
$ ocamlopt test.c
$ ocamlmklib test.o -o test
$ ocamlopt -shared -linkall -I . -cclib -ltest lib.ml -o lib.cmxs
$ ocamlopt -shared -linkall lib2.ml -o lib2.cmxs
$ ocamlopt -linkall dynlink.cmxa dyn.ml
$ ./a.out
Fatal error: exception Dynlink.Error (Dynlink.Cannot_open_dll "Dynlink.Error (Dynlink.Cannot_open_dll \"Failure(\\\"/tmp/dynlink-fail/lib2.cmxs: undefined symbol: testdynfail\\\")\")")
```
The same minimal test case works with OCaml 4.09.0 and older. I'm not really sure what changed in Dynlink since 4.09 but it now seems to drop the accessibility of C symbols between two calls to `Dynlink.loadfile`.

In case you need access to some of the packages required to test the compilation of `nocrypto` or `base` you might need the following opam overlay:
```
$ opam remote add alpha git://github.com/kit-ty-kate/opam-alpha-repository.git
```

**Comment by dra27** [comment]
Bisecting suggests that this occurred in https://github.com/ocaml/ocaml/commit/6cbdfad (#2288) but I haven't looked as to why.

I have produced a functional but, in `ocamltest` terms, quite ugly translation of @kit-ty-kate's wonderfully minimum repro case at https://github.com/dra27/ocaml/commit/c1ac1d7fcb6a4d2dec0a089e2953d8a26c45b8d5 which should be merged with the fix.

**Comment by kit-ty-kate** [comment]
Oh thanks a lot! Looking at the commit, it seems like this comment is not enforced anymore: https://github.com/ocaml/ocaml/commit/6cbdfad#diff-a9a37f72322539fb9a3a5de9c9f481d0R141-R145

I have a fix and I *just* tested it successfully on the test case

**Comment by kit-ty-kate** [comment]
Closing as the fix has now been merged
