### ISSUE TITLE
Segfault with installed custom printer in ocamldebug

### ISSUE THREAD

**Issue by Rehan-MALAK** [ocaml/ocaml#9214]
Dear all,
I am currently unable to use a custom installed printer with ocamldebug in my project because of this segfault.

``mytype.ml``
```ocaml
type mytype = unit -> unit
```
``a.ml``
```ocaml
let () =
  let f : Mytype.mytype = fun _ -> () in
  ()
```
``p.ml``
```ocaml
let print_mytype fmt (f : Mytype.mytype) =
  let _ = f () in (* let _ = f () makes ocamldebug segfault ? *)
  Format.fprintf fmt "(installed printer) !"
```
Ocamldebug ``script``
```
set program a
br @ a 3
run
print f
load_printer p.cmo
install_printer P.print_mytype
print f
```
Commands
```bash
ocamlc -g -bin-annot -o mytype.cmo -c mytype.ml
ocamlc -g -bin-annot -o a.cmo -c a.ml
ocamlc -g -bin-annot -o p.cmo -c p.ml
ocamlc -g -bin-annot -o a mytype.cmo a.cmo
ocamldebug ./a << EOF
so script
EOF
```
Wanted behaviour (if you remove ```let _ = f ()``` for example) :
```bash
(ocd) Loading program... done.
Breakpoint 1 at 0:10532: file a.ml, line 3, characters 3-5
Time: 12 - pc: 0:10532 - module A
Breakpoint: 1
3   <|b|>()
f: Mytype.mytype = <fun>
File p.cmo loaded
f: Mytype.mytype = (installed printer) !
(ocd) Removed breakpoint 1 at 0:10532: file a.ml, line 3, characters 3-5
```
Actual behaviour with trunk c5e875d0 or 4.09.0
```bash
(ocd) Loading program... done.
Breakpoint 1 at 0:10532: file a.ml, line 3, characters 3-5
Time: 12 - pc: 0:10532 - module A
Breakpoint: 1
3   <|b|>()
f: Mytype.mytype = <fun>
File p.cmo loaded
Fatal error: exception End_of_file
Segmentation fault
```

Any idea ?

**Comment by Rehan-MALAK** [comment]
As far I understand :

- ''load_printer'' is essentially just a call to ``Dynlink.load_file``
- ''install_printer'' a call to ``Dynlink.unsafe_get_global_value`` + some ``Obj`` magic cast to a function

but inside ocamldebug memory, not in the target program.

I got confused because :

1. With ocaml toplevel, one can do :

``a.ml``
```ocaml
let f = function () -> 4
```
``p.ml``
```ocaml
let print_mytype (f : unit -> int) =
  let n = f () in (* in ocaml toplevel, this is not problematic *)
  Format.printf "installed printer : this is the constant function to %d" n
```
```
$ ocamlc -c p.ml
$ ocaml
        OCaml version 4.09.0

Cannot find file topfind.
# #use "a.ml";;	
val f : unit -> int = <fun>
# f;;
- : unit -> int = <fun>
# #load "p.cmo";;
# #install_printer P.print_mytype;;
# f;;
- : unit -> int = installed printer : this is the constant function to 4
```

2) I am used to gdb where one can call C functions of the target program but this turns out to be a nice non-trivial feature explained for example here https://jvns.ca/blog/2018/01/04/how-does-gdb-call-functions/

- Stop the process
- Create a new stack frame (far away from the actual stack)
- Save all the registers
- Set the registers to the arguments you want to call your function with
- Set the stack pointer to the new stack frame
- Put a trap instruction somewhere in memory
- Set the return address to that trap instruction
- Set the instruction pointer register to the address of the function you want to call
- Start the process again!

**Comment by jahierwan** [comment]
I've been bitten by this one too...

**Comment by Rehan-MALAK** [comment]
I don't know what one should do here. Maybe this should be tagged as "feature-wish" : ability to run code from ocamldebug. It would provide best of both worlds : 
-toplevel : run code
-ocamdebug : breakpoint in a big project
I remember reading somewhere that it was impossible (maybe because of the GC), but I can't say what he/she meant by impossible (not possible or too much work ?).

Comments from runtime experts welcome !

**Comment by jahierwan** [comment]
My wish is more modest. I just want to able to print, in ocamldebug, structures that have at least a field that is a function, event if this function is not used by the loaded and installed printer (which causes the core dump as your example illustrates). 

I other words, even if the printer does not try to use the function (as you'd like to do if I understand correctly), I have no way to print the structure using the other fields.

Hence I don't see it as a "feature-wish", but as a "ocamldebug-bug".

**Comment by Rehan-MALAK** [comment]
Hi ! I up this question :
"calling code from ocamldebug in the target debugged program memory" is impossible (because of the GC or something else?) or too-much work to implement ?
If it was possible, it would enable the possibility to run the pretty-printers of the targeted programs during an ocamldebug session
(I have in mind the type terms of an assistant prover).

**Comment by xavierleroy** [comment]
Plausible fix in #10709.

**Comment by jahierwan** [comment]
Excellent! Thanks Xavier.

**Comment by Rehan-MALAK** [comment]
With  https://github.com/xavierleroy/ocaml/commit/ab9588cace43beac19b9ff6fa782fc37ac597671 patch, one gets
```
$ ocamldebug ./a
        OCaml Debugger version 4.14.0+dev0-2021-06-03

(ocd) so script
Loading program... done.
Breakpoint 1 at 0:11240: file a.ml, line 3, characters 3-5
Time: 16 - pc: 0:11240 - module A
Breakpoint: 1
3   <|b|>()
f: Mytype.mytype = <fun>
File p.cmo loaded
f: Mytype.mytype =
  <printer P.print_mytype raised an exception: Failure("custom printer tried to invoke a function from the debuggee")>
(ocd) 
```
without quitting the ocamldebug session.

Thanks @xavierleroy

**Comment by Rehan-MALAK** [comment]
> Hi ! I up this question : "calling code from ocamldebug in the target debugged program memory" is impossible (because of the GC or something else?) or too-much work to implement ? If it was possible, it would enable the possibility to run the pretty-printers of the targeted programs during an ocamldebug session (I have in mind the type terms of an assistant prover).

:smile:

**Comment by xavierleroy** [comment]
> Hi ! I up this question : "calling code from ocamldebug in the target debugged program memory" is impossible (because of the GC or something else?) or too-much work to implement ? 

Not impossible but a lot of work to implement, as far as I can see.
