### ISSUE TITLE
Stdlib: provide a function to modify argv

### ISSUE THREAD

**Issue by Octachron** [ocaml/ocaml#9251]
With the deprecation of `Obj.truncate`, the programs that were using it to change the size of `argv` are under threat of deprecation: I am aware of two (and half) such programs outside of the toplevel: utop and lablgtk(and lablgtk3).

Both programs are using `Obj.truncat` in the same way as the toplevel: they detect standard arguments intended for some outer overlay (typically the toplevel for utop and gtk for lablgtk), and remove them from the arguments seen by the inner program.

Currently, `utop` has been patched to use the same `caml_sys_modify_argv` C function as the compiler toplevel, and lablgtk is ignoring the deprecation warning.

Since the number of affected programs is greater than one, it sounds like we may want to expose `caml_sys_modify_argv` in the stdlib API.

**Comment by gasche** [comment]
On the other hand, it's not hard for affected programs to declare the external themselves, and I am not convinced that we want to expose to OCaml programmers a mental model where `Sys.argv` may change.

**Comment by Octachron** [comment]
Since I have only been exposed to this issue once (when fixing utop) and there have been no other comments, a explicit function does not seem required. I am closing this issue.
