### ISSUE TITLE
Windows: stdout/stderr file descriptors invalid with GUI application

### ISSUE THREAD

**Issue by bryphe** [ocaml/ocaml#9252]
I've hit an issue when compiling a GUI application for Windows - using the `-mwindows`/`-subsystem windows` flags. 

Depending on the runtime parameters, I may allocate a console via the Win32 `AllocConsole` or `AttachConsole` APIs - and I was expecting that `print_endline` (and the default `stdout`/`stderr` file descriptors) would work with the newly allocated console. However, I get a `"Bad file descriptor"` error when trying to use `print_endline` after allocating a console. 

An example app:
```
// Attach a console to the process
let () = Lib.attachConsole()

// This print, using `printf` via a c-stub, succeeds
let () = Lib.nativePrint("test after attach")

// However, using `print_endline` fails with `Sys_error("Bad file descriptor")`
let () = print_endline("Print from ocaml after attach")
```

The library is compiled with a dune flag:
```
(flags -cclib "-subsystem windows")
```

And this is the output:
```
Printing from C: test after attach...
Fatal error: exception Sys_error("Bad file descriptor")
```

I'm guessing that what's happening is that the initial file descriptors the OCaml runtime picks up [here](https://github.com/ocaml/ocaml/blob/82d7971b4f3a18dbc6dcf5d228d2f4c2d3a66fb2/otherlibs/win32unix/unix.ml#L234):
```
external filedescr_of_fd : int -> file_descr = "win_handle_fd"

let stdin = filedescr_of_fd 0
let stdout = filedescr_of_fd 1
let stderr = filedescr_of_fd 2
```

...are invalid, since at the time of initialization here, there is no console because of `-subystem windows`. However, once we do attach / alloc a console, is there a way to connect these to the console I've allocated, so I can continue to use `stdin`/`stdout`/`stderr` from OCaml? There didn't seem to be a way, looking through the APIs, but I could totally be missing something.

I've put together a minimal repro here:
https://github.com/bryphe/ocaml-attach-console-repro/blob/master/repro.ml

Let me know if there any other details I can provide. What's interesting is that `printf` works as expected - picking up the new stdout - but `print_endline` does not.

As a workaround, I plan on funneling my logging via a stub for printf, but I was wondering if there was a more convenient option.  (Also, I worry about a stray `print_endline` or output on `stdout` crashing the app!) 

Thank you for the help!

**Comment by dra27** [comment]
I haven't double-checked all the facts here, but I think that the CRT's `printf` functions use `stdout` (i.e. at the `FILE*` or stream level) whereas OCaml uses `write` (i.e. at the `int` or file descriptor level). Your code at https://github.com/bryphe/ocaml-attach-console-repro/blob/master/lib/stubs.cpp#L24-L26 resets `stdin`, `stdout` and `stderr` - you need to reset fd 0, 1 and 2 as well. It should work to use `_open_osf_handle` on the results of `GetStdHandle` (after the `AllocConsole` call), `dup2` the resulting fds to `0`, `1` and `2` and then use `fdopen` to reallocate the `stdin`, `stderr`, `stdout` pointers.

[This answer on MSDN](https://social.msdn.microsoft.com/Forums/windows/en-US/286059e8-9163-4679-9663-efc63c5d9c53/allocconsole-backspace-and-newline-characters-incorrectly-printed-after-quotsystemquot-call?forum=vcgeneral#68a73761-7a40-4d4c-a15e-90902a1244ee-isAnswer) includes believable-looking code for it.

**Comment by dra27** [comment]
Cross-referencing my nemesis in #1408 - it shouldn't be affected by it, but it's making me wonder if there should be a test!

**Comment by bryphe** [comment]
> you need to reset fd 0, 1 and 2 as well. It should work to use _open_osf_handle on the results of GetStdHandle (after the AllocConsole call), dup2 the resulting fds to 0, 1 and 2 and then use fdopen to reallocate the stdin, stderr, stdout pointers.

That was exactly it - thank you @dra27 ! That code from the MSDN answer you linked worked perfectly:
```
 // Attach standard input/output to the created console
  int fd_in = _open_osfhandle ((intptr_t) GetStdHandle (STD_INPUT_HANDLE),
                               _O_RDONLY | _O_BINARY);
  int fd_out = _open_osfhandle ((intptr_t) GetStdHandle (STD_OUTPUT_HANDLE),
                                _O_WRONLY | _O_BINARY);
  int fd_err = _open_osfhandle ((intptr_t) GetStdHandle (STD_ERROR_HANDLE),
                                _O_WRONLY | _O_BINARY);

  if (fd_in)
    {
      dup2 (fd_in, 0);
      close (fd_in);
      SetStdHandle (STD_INPUT_HANDLE, (HANDLE) _get_osfhandle (0));
    }
  if (fd_out)
    {
      dup2 (fd_out, 1);
      close (fd_out);
      SetStdHandle (STD_OUTPUT_HANDLE, (HANDLE) _get_osfhandle (1));
    }
  if (fd_err)
    {
      dup2 (fd_err, 2);
      close (fd_err);
      SetStdHandle (STD_ERROR_HANDLE, (HANDLE) _get_osfhandle (2));
    }

  *stdin = *(fdopen (0, "rb"));
  *stdout = *(fdopen (1, "wb"));
  *stderr = *(fdopen (2, "wb"));

  setvbuf (stdin, NULL, _IONBF, 0);
  setvbuf (stdout, NULL, _IONBF, 0);
  setvbuf (stderr, NULL, _IONBF, 0);
```

Will close this out since the bug was on my side. Really appreciate the help!

**Comment by bryphe** [comment]
> Cross-referencing my nemesis in #1408 - it shouldn't be affected by it, but it's making me wonder if there should be a test!

@dra27 - ah, interesting! This does seem related.

In particular - I wonder if with that fix - I would need to manually run the `caml_setup_win32_terminal` function after `Alloc`/`Attach`Console. 

Epic battle to get that Unicode support! 😄 Your work to get a better experience on Windows is much appreciated!

**Comment by siliconvoodoo** [comment]
`*stdin = *(fdopen (0, "rb"));`
is illegal code.
normally `freopen` or `dup` are supposed to be enough. `stdin` is not assignable (rvalue). and `FILE` is supposed to be opaque so `*stdin` is not assignable either in theory.

**Comment by linsyking** [comment]
Does anyone solve this problem? Still experiencing the issue.

**Comment by nojb** [comment]
> Does anyone solve this problem? Still experiencing the issue.

Have you read the discussion? If you are building a GUI-mode application, then it is your responsibility to allocate a console and reset the standard outputs (file descriptors 0, 1, 2) to point to the newly allocated console. The code above shows how to do so.
