### ISSUE TITLE
Manual: PDF version: truncated page: ch7.7 p130 expressions grammar

### ISSUE THREAD

**Issue by hxa7241** [ocaml/ocaml#9255]
The text runs off the bottom of the page, and so is missing (visibly):

   ∣  module-path .[| expr |]
   ∣  module-path .{ expr }
   ∣  module-path .{< expr >}

**Comment by Octachron** [comment]
Indeed, the grammar has grown larger than the pdf page. Splitting some subgrammars should solve the issue.Thanks for the report!

**Comment by Octachron** [comment]
Resolved by #9300 .
