### ISSUE TITLE
ocamldebug "source" is not reentrant

### ISSUE THREAD

**Issue by SkySkimmer** [ocaml/ocaml#9265]
This causes strange behaviour when using it inside a sourced file. For instance with files

source1:
~~~
source source2

source source3
~~~
source2:
~~~
load_printer str.cma
~~~
source3:
~~~
load_printer dynlink.cma
~~~
running `source source1` produces output
~~~
File /home/gaetan/.opam/4.07.1/lib/ocaml/str.cma loaded
File /home/gaetan/.opam/4.07.1/lib/ocaml/str.cma loaded
File /home/gaetan/.opam/4.07.1/lib/ocaml/dynlink.cma loaded
~~~
ie `source2` gets sourced twice.
With recent ocaml the restriction on repeated links causes a failure instead.

See also https://github.com/coq/coq/issues/8952 https://github.com/coq/coq/issues/11405

**Comment by SkySkimmer** [comment]
ping

**Comment by damiendoligez** [comment]
I can't reproduce this problem on 4.07.1 nor on 4.14.0. On 4.14.0, the debugger complains about `dynlink.cma` being already loaded, but that's independent of any `source` command.

Is there anything special in your `.ocamldebug` files (either local on in $HOME) ?

**Comment by SkySkimmer** [comment]
On 4.14 
~/.ocamldebug just has `set break_on_load off`

Full repro script
~~~bash
#!/usr/bin/env bash

set -e

cd "$(mktemp -d)"

printf 'source source2\nsource source3\n' > source1
echo 'load_printer str.cma' > source2
echo 'load_printer unix.cma' > source3

touch foo.ml

ocamlc foo.ml -o foo

echo source source1 | ocamldebug foo
~~~
output
~~~
        OCaml Debugger version 4.14.0

Executing file /home/gaetan/.ocamldebug
(ocd) File str.cma loaded
Error during code loading: The module `Unix' is already loaded (either by the main program or a previously-dynlinked library)
~~~

**Comment by damiendoligez** [comment]
You get the same error if you simply try `load_printer unix.cma`.

This has nothing to do with `source` not being reentrant, and indeed it looks like `ocamldebug` correctly executed `source2`, then `source3`.

The fact that `Unix` is already loaded is not a surprise, since `ocamldebug` uses Unix internally.

**Comment by SkySkimmer** [comment]
Right, I got confused

I can still reproduce by replacing https://github.com/coq/coq/blob/203ad7363781fb8aa241c6ce8ca48e238f84e02f/dev/db#L1-L24 with `source core_dune.dbg`
(`core_dune.cbg` is the same load_printer list)

It seems to have something to do with empty newlines, with 
~~~bash
#!/usr/bin/env bash

set -e

cd "$(mktemp -d)"

printf 'source source2\n\nload_printer bigarray.cma\n' > source1
echo 'load_printer nums.cma' > source2

touch foo.ml

ocamlc foo.ml -o foo

echo source source1 | ocamldebug foo
~~~
I get 
~~~
        OCaml Debugger version 4.14.0

Executing file /home/gaetan/.ocamldebug
(ocd) File nums.cma loaded
Error during code loading: The module `Int_misc' is already loaded (either by the main program or a previously-dynlinked library)
~~~
but replacing the `\n\n` with `\n` it works fine

**Comment by damiendoligez** [comment]
> but replacing the \n\n with \n it works fine

There's your problem. In ocamldebug, most commands have the `instr_repeat` attribute: when you type a blank line after the command, `ocamldebug` repeats the same command. This is very useful for `step`, maybe less for `source`.

You can see which commands have `instr_repeat` in the definition of `init` at the end of `debugger/command_line.ml`.

I guess it would make sense to disable this feature within the `source` command to allow empty lines in command files but the immediate fix is to remove the empty lines in your file.

**Comment by xavierleroy** [comment]
May I suggest to mark the "source" command as not automatically repeating ?  I don't see the point of running it several times in a row.

**Comment by SkySkimmer** [comment]
One could put eg 
~~~
run
print bla
~~~
in a sourced file to easily print bla at some breakpoint

**Comment by xavierleroy** [comment]
One could, indeed.  What conclusion do you draw from this example?  Should "source" be auto-repeating (like now, although it causes the confusion reported in this issue) or not?
