### ISSUE TITLE
ocaml warning 29 can not be turned off by warning attribute

### ISSUE THREAD

**Issue by bobzhang** [ocaml/ocaml#9272]
seems `[@@@warning "-29"]` does not have an effect on such warning

**Comment by Octachron** [comment]
Indeed, the warning (29: End of line in string) is a lexical warning. All lexical warnings (1,2, 14 and 29) are not affected by attribute warning.

**Comment by Octachron** [comment]
To elaborate on my answer: currently, the local warning state is only known when we are typing the parsetree (by keeping this warning state updated by inserting warning_scope at the right position). Lifting those lexical warnings to the typyng phase sounds strange. Another option might to implement another warning-aware traversal of the parsetree that would raise those warnings after the parsing is done.
