### ISSUE TITLE
Clarify some bootstrap aspects.

### ISSUE THREAD

**Issue by dbuenzli** [ocaml/ocaml#9278]
The `BOOTSTRAP.adoc` explains the procedure very well, thanks. 

The following two points could be clarified: 

1. It could be mentioned that bootstrap is in general needed when the format of compilation objects changes (e.g. `cma`, `cmxa`) -- it mentions only `cmi` files.
2. It's unclear if you have a PR that needs a bootstrap how you should proceed. Do you include the bootstrap in the PR and if so in a commit before/after/with the change that needs it. Or is the bootstrap to be done by a trusted core dev member and you PR without the bootstrap and just mention that it needs one ? 

I'll glady update the document with the answers.

**Comment by Octachron** [comment]
For the second point, my memory of previous discussion is that bootstrap commits should be in separate commits that will be replayed by one of the core dev member before merging.

**Comment by dbuenzli** [comment]
Thanks @octachron and where should be the commit. Before the code that needs the bootstrap or after it ? 

I would tend to say before as this makes it sure the compiler remains  `bisect`able. Is that right ?

**Comment by Octachron** [comment]
Before the commit that needs the bootstrapping: ideally, all commits should pass the test suite (to be usable in bisecting indeed).

**Comment by gasche** [comment]
I usually put the bootstrap commit after the commit that needs bootstrapping. This breaks bisectability, but it makes it possible for someone to reproduce the bootstrap by going to that point in the history, redoing the bootstrap, and checking that the result is (morally) the same as the committed bootstrap. If we start bootstrapping things from future commits, it seems harder to get this guarantee.

If we want bisectability, I think the best approach is to have the bootstrap *with* the commit that requires it. In the meantime, I mark explicitly in the commit log that a given commit requires a bootstrap (which in my mind means: we know it is broken, please bisect-skip it).

Note: I don't  like the current bootstrapping policy: it requires more work in theory, we don't know how to take any advantage of the extra properties that it gives us, and people mostly ignore it in practice.
