### ISSUE TITLE
content of cma files is not reproducible

### ISSUE THREAD

**Issue by olafhering** [ocaml/ocaml#9307]
I get random changes in `*.cma` archives. I think the issue is that [create_archive](ba204305d6c9d039917240e92e34363725381d3a/bytecomp/bytelibrarian.ml#L91) does not sort the list. As a result, each rebuild of unchanged sources leads to slightly different, yet usable, archives. AFAICS this is the only noise with ocaml binary files.

See [reproducible-builds](https://reproducible-builds.org/) for reasons to have predictible builds.

**Comment by olafhering** [comment]
Well, just as I wrote this, `*.cmti` might be affected as well. I did not spot this before....

**Comment by olafhering** [comment]
I briefly browsed the ocaml 4.05 build logs. It seems in 4.05 the cma files are reproducible. But it is not clear from browsing the 4.05 source tree why the input list would be sorted. Maybe the current log snapshots just do not show the issue.

**Comment by xavierleroy** [comment]
`Bytelibrarian.create_archive` does not sort the argument list `file_list` because linking order is significant in OCaml -- if B refers to A, A must be linked before B -- so we respect the order of files given on the command-line.  But this order doesn't change from build to build!

> each rebuild of unchanged sources leads to slightly different, yet usable, archives

Do you have a repro case?

**Comment by olafhering** [comment]
I may be able to force it by building once in tmpfs and once on another filesystem.

In the past I did not pay close attention to this. But I do think 4.05 was not that much affected, unlike 4.10 now. I will inspect the logfiles from 4.04 to 4.10.

Is there a readdir(3) involved somewhere? Maybe this would be part of the issue, its result is not predictable.

**Comment by olafhering** [comment]
> I may be able to force it by building once in tmpfs and once on another filesystem.

Yes, this seems to be a way to observe differences with a local build.

**Comment by hhugo** [comment]
Is the issue with `*.cma` archives from the OCaml compiler codebase or from a third-party OCaml codebase ?

**Comment by olafhering** [comment]
What do you mean by that? I will see it in all of [devel:languages:ocaml](https://build.opensuse.org/project/show/devel:languages:ocaml) once it is switched from 4.05 to 4.10 (maybe even 4.09).

**Comment by olafhering** [comment]
Further inspection shows the issue starts with 4.08. Build logs in 4.04..07 show no differences in cma files. Starting with 4.08 I see them in cma, cmt, cmti. The latter may just be a result of different ordering in cma?

**Comment by lthls** [comment]
The `.cmo` files contain debug information that include paths to the source files. Since these `.cmo` files are then (more or less) copied into the `.cma` file, this could explain what you found. It's possible that the paths to the source files were only introduced in 4.08, which would explain why you only get the issue starting from there, but I'm not 100% sure.

Do you use the `BUILD_PATH_PREFIX_MAP` environment variable ? If not, then it's expected that builds are not reproducible, see #1515 for more information. If you do, then indeed there is something that needs investigating.

**Comment by olafhering** [comment]
I was not aware of `BUILD_PATH_PREFIX_MAP`, no pkg at SUSE seems to use it. I will dig into it.

**Comment by olafhering** [comment]
It seems the included paths do just contain the rpm package version number, not the rpm release number.
Some example: same source, different size of result. Not sure if there is a "cma inspector", like `readelf` for ELF.
[issue9307.ppxlib.tar.zip](https://github.com/ocaml/ocaml/files/4215654/issue9307.ppxlib.tar.zip)

**Comment by glondu** [comment]
> Not sure if there is a "cma inspector", like `readelf` for ELF.

There is `ocamlobjinfo`.

**Comment by olafhering** [comment]
I made a copy of all binary packages, triggered global rebuild, now waiting for the results to compare changed binary packages. This may take a while.

**Comment by hhugo** [comment]
> What do you mean by that? I will see it in all of [devel:languages:ocaml](https://build.opensuse.org/project/show/devel:languages:ocaml) once it is switched from 4.05 to 4.10 (maybe even 4.09).

Looking at your issue9307.ppxlib.tar.zip, it seems that you're having issue with `ppxlib` (not with `*.cma` provided by the ocaml compiler). Is is possible that only the build of ppxlib is not reproducible (e.g. because its build system doesn't pass individual `*.cmo` in a stable order) ?

**Comment by olafhering** [comment]
> Is is possible that only the build of ppxlib is not reproducible (e.g. because its build system doesn't pass individual `*.cmo` in a stable order) ?

No, it affects many more packages. I'm in the process of collecting the affected binaries.

**Comment by olafhering** [comment]
Here is the first result, a number of files from ocaml.git#409 differ. It is not clear to me what the actual difference is, even the filesize differs? I suppose the different `cmo` files do also cause the different `cma` files?
[issue9307.ocaml409.tar.zip](https://github.com/ocaml/ocaml/files/4220749/issue9307.ocaml409.tar.zip)

Is is enough to get an understanding, or should I provide more examples?

**Comment by hhugo** [comment]
I had a look with @xclerc, the issue seems to be that since ocaml 4.08, we keep track of cmi available in load paths inside the environment. The environment is propagated in cmo, cma, cmti ..
With parallel build, the set of available cmi in load paths can vary. Cc @trefis, @diml

**Comment by ghost** [comment]
I believe this is what #9039 is meant to fix

**Comment by olafhering** [comment]
> With parallel build, the set of available cmi in load paths can vary.

Does this mean a forced single threaded build (make -j1/dune build -j1) may fix it?

**Comment by hhugo** [comment]
> > With parallel build, the set of available cmi in load paths can vary.
> 
> Does this mean a forced single threaded build (make -j1/dune build -j1) may fix it?

Possibly

**Comment by ghost** [comment]
It's sad to disable parallelism, but yh it should fix it.

**Comment by olafhering** [comment]
Yes, forcing `-j 1` helps indeed. Tested with an ocaml 4.09 based tree.

**Comment by Octachron** [comment]
For futrure reference, the reproducibility issues is fixed in the current development version; and thus should be fixed for version of OCaml ulterior to 4.11 .
