### ISSUE TITLE
Unix.execv on Cygwin+MinGW splits Sys.argv on spaces

### ISSUE THREAD

**Issue by maroneze** [ocaml/ocaml#9320]
While debugging an issue with why3 on Windows (https://gitlab.inria.fr/why3/why3/issues/445), I ended up finding a difference of behavior with `Unix.execv` on Windows and on Linux. To be more specific, using [OCaml for Windows](https://fdopen.github.io/opam-repository-mingw/installation/) and then creating a switch `4.10.0+rc2+mingw64` (the same behavior also happens on older versions, such as `4.07.0+mingw64c`).

The following programs illustrate the difference:

    (* test_execv.ml: ocamlopt unix.cmxa test_execv.ml -o test_execv *)
    let () =
      Unix.execv "./test_execv2" (Array.of_list ["arg with space"])

    (* test_execv2.ml: ocamlopt test_execv2.ml -o test_execv2 *)
    let () =
      Format.printf "argv (%d) = " (Array.length Sys.argv);
      Array.iter (fun a -> Format.printf "{%s} " a) Sys.argv;
      Format.printf "@."

When running `./test_execv` on Linux, I get the following output:

    argv (1) = {arg with space}

On Cygwin, I get instead:

    argv (3) = {arg} {with} {space}

This prevents `why3` from working correctly, since some of its commands expect a single argument such as `why3 config`, instead of two separate arguments.

**Comment by nojb** [comment]
This is a bug in Windows implementation of `execv`. You may try wrapping your arguments in double quotes (or use `Filename.quote`), but that is a hack at best. You can also try using `Unix.create_process` which does the quoting for you automatically.

I guess we could try to do the quoting in the `Unix` library...

**Comment by xavierleroy** [comment]
I'm curious to know how `execv` is implemented in the MS CRT.  If it's just CreateProcess + ExitProcess, maybe we could just reimplement `Unix.execv*` in OCaml based on `Unix.create_process`.

**Comment by xavierleroy** [comment]
Fixed by #9550
