### ISSUE TITLE
Problem with pretty-printing of lists in toplevel when opening List module

### ISSUE THREAD

**Issue by tofgarion** [ocaml/ocaml#9337]
I am using OCaml 4.09.0 from OPAM and I have just noticed something peculiar using the toplevel.

When evaluating `1 :: 2 :: []`, the list is pretty-printed as usual:

```
# 1 :: 2 :: 3 :: [] ;;
- : int list = [1; 2; 3]
```

If I open first the `List` module, then the printing is different:

```
# let open List in 1 :: 2 :: 3 :: [] ;;
- : int List.t = (::) (1, [2; 3])
```

The list is now typed with the type `t` used in the `List` module signature
and the list representation is different.

[Florian Angeletti](https://github.com/Octachron) has just posted an explanation on caml-list (see https://inbox.ocaml.org/caml-list/87v9ntdpx4.fsf@port-garion.isae.fr/T/#m81832d8a041da3a1306426ecd78944e95d47fd54) and a PR with a solution, see #9336.

Best,

Christophe

**Comment by mshinwell** [comment]
The discussion on #9336 can supercede this issue.
