### ISSUE TITLE
Dynlink.*_units () functions are inaccurate before the first load.

### ISSUE THREAD

**Issue by dbuenzli** [ocaml/ocaml#9338]
Currently the Dynlink state querying function [`Dynlink.*_units`](https://github.com/ocaml/ocaml/blob/1fd6dc077d63fc8e0b36e2a684dae55a0f3383d4/otherlibs/dynlink/dynlink_common.ml#L318-L3279) report invalid information before any load occurs. This is because they fail to call the internal [`init`](https://github.com/ocaml/ocaml/blob/1fd6dc077d63fc8e0b36e2a684dae55a0f3383d4/otherlibs/dynlink/dynlink_common.ml#L148-L153) function.

I will provide a fix. Here's a small program that shows the issue:

```
> cat test.ml

let units () = String.concat " " (Dynlink.main_program_units ())
let main () =
  Printf.printf "before: %s\n" (units ());
  try Dynlink.loadfile "/dev/null" with e -> ();
  Printf.printf "after: %s\n" (units ())

let () = main ()
> ocamlc -o a.out dynlink.cma test.ml
> ./a.out
before: 
after: CamlinternalFormat CamlinternalFormatBasics CamlinternalLazy Dynlink Dynlink_common Dynlink_compilerlibs Dynlink_types Std_exit Stdlib Stdlib__arg Stdlib__array Stdlib__buffer Stdlib__bytes Stdlib__char Stdlib__digest Stdlib__filename Stdlib__format Stdlib__fun Stdlib__gc Stdlib__hashtbl Stdlib__int Stdlib__int32 Stdlib__int64 Stdlib__lexing Stdlib__list Stdlib__map Stdlib__marshal Stdlib__nativeint Stdlib__obj Stdlib__option Stdlib__parsing Stdlib__printexc Stdlib__printf Stdlib__queue Stdlib__random Stdlib__result Stdlib__seq Stdlib__set Stdlib__stack Stdlib__string Stdlib__sys Stdlib__uchar Stdlib__weak Test
```

**Comment by gasche** [comment]
Thanks! If you provide a fix, please include the repro case in the testsuite (we already have various `testsuite/tests/lib-dynlink-*/` test directories, you can create a new one).

**Comment by damiendoligez** [comment]
@dbuenzli It seems that you did the work, but forgot to open a PR?

**Comment by dbuenzli** [comment]
No, it was part of another line of work. PR #9790 cherry picks the patch.
