### ISSUE TITLE
missing 'output' variable in ocamltest 

### ISSUE THREAD

**Issue by progman1** [ocaml/ocaml#9339]
in ocamltest/ocaml_compilers.ml there is this:
```
method program_output_variable =
    if Ocaml_backends.is_native host
    then None
    else Some Builtin_variables.output
```
when I used the action [setup-ocamlopt.opt-build-env] an error ensued 
with [compare-program-output] because the [output] variable was missing.
the above code appears to be the source.
I hesitate to call it a bug but cannot fathom why program output isn't handled
the same way as for the byte equivalent when the compiler backend happens to be native!

**Comment by shindere** [comment]
@progman1 I do not remember the details of why the code is like this
now, but the code in `ocaml_actions.ml` seems to handle the `None` case
so I assume I had a reason to write things as they have been written.

Could you perhaps elaborate on what you were trying to do andwhat
exactly it was that failed?
A concrete and reproducible example would actually be most welcome.

Thanks!

**Comment by shindere** [comment]
Will look into it.

**Comment by shindere** [comment]
As long as there won't be a repro case this is going to be hard to
investigate.

S I am going to close this issue but please @progman1 do not hesitate to
re-open it if it still matters to you but then some help to understand
and reproduce the problem would really be appreciated.
