### ISSUE TITLE
deprecate Hashtbl.add and use Hashtbl.add_and_shadow instead

### ISSUE THREAD

**Issue by c-cube** [ocaml/ocaml#9342]
https://github.com/ocaml/ocaml-lsp/pull/111 is the last straw on the OCaml's back, I think. The behavior `Hashtbl.add` is confusing to 100% of newcomers and a footgun, and while I think it's a useful feature, it should not be _the default_ imho.
(I can make a PR)

**Comment by jberdine** [comment]
FWIW, in the past I ran across so many bugs due to this that I added two type-incompatible modules, `HashMap` and `HashMultiMap`, both as thin wrappers of `Hashtbl`, and shadowed `Hashtbl` to make sure that no one could use it directly.

**Comment by yakobowski** [comment]
I too think that `Hashtbl.add` is a massive pitfall, for both newcomers and experienced users. Now that it is possible to mark functions as deprecated, I think this path should be seriously considered.

(I would add that there are security implications too, something that not-so-long ago lead to massive changes in Hashtbl. Misusing `Hashtbl.add` easily results in memory leaks, that can be turned into applications with poor performances, or denial of service.)

**Comment by c-cube** [comment]
Ah, that's sad. Can this still be on the table (for 5.0 even)?

**Comment by gasche** [comment]
If we wanted to work on this for 5.0, it would be some amount of work:
- Agree on a new name for the `add` replacement (or a new HashtblMulti module, or...)
- Write a PR that deprecates `Hashtbl.add` and introduces the new name (or module...)
- Do opam-wide testing to get an idea of the breakage
- Converge to a decision and (hopefully) merge it.

Currently people working on the 5.0 release are already spread thin. @c-cube indicated his unwillingness to do more thankless jobs for the stdlib, and I understand. We may be out of workforce for this one.

**Comment by c-cube** [comment]
That seems like a reasonable amount of work, @gasche, if it's about adding _one_ alias. Of course picking a name is highly bikesheddable.

I don't think there's any need to introduce a new module, `Hashtbl` does the job. Having an alert on `add` would suffice imho.

So, is there anything wrong with, say, `add_shadowing` with an appropriate docstring that explains what it does precisely?

**Comment by shindere** [comment]
How about `add_masking` whihc is 2 characters shorter?

(no strong opinion, just suggesting)

**Comment by c-cube** [comment]
I think this is sufficiently rarely useful that 2 characters shouldn't make a difference. That said, it's also a good name imho :)

**Comment by shindere** [comment]
Simon Cruanes (2022/08/11 06:53 -0700):
> I think this is sufficiently rarely useful that 2 characters shouldn't
> make a difference. That said, it's also a good name imho :)

I'd say the shorter the better, independently ofthe frequency, because
it makes the code more compact (when you can only feel 40 characters at
a time, because you read in Braille, such small details may end up
making a difference)

**Comment by bluddy** [comment]
How many people actually make use of the add+shadowing functionality?

**Comment by c-cube** [comment]
@bluddy I use it, sparingly, for what I think is its original purpose: implementing scoping in compiler-like computations. When you enter a variable binding, your add the variable by its name to the hash table, potentially shadowing previous variables with the same name. When you are done, you remove one occurrence (the topmost), and voilà. It's a pretty niche use case.

**Comment by dbuenzli** [comment]
Even though it doesn't share the type structure (`'a` vs `'a list`) in view of https://github.com/ocaml/ocaml/pull/11410 `Hashtbl.add_to_list` could be an option. Also I think that having `replace` as the base function to use is a tad odd. Maybe `Hasthbl.set` could be added along the way.

**Comment by c-cube** [comment]
I actually like `set` as an alias for `replace`! I think it's a good idea, as it mirrors `Array.get`/`Array.set`.

**Comment by xavierleroy** [comment]
I believe add + shadowing is rarely used, except to implement dynamically-scoped symbol tables like @c-cube describes.

However, I and probably others use `Hashtbl.add` when we know we'll never remove anything from the hash table, and keys are unique (or the extra memory usage from duplicate keys is negligible), because it runs faster than `Hashtbl.replace` !  A typical example is hash consing, where nothing is ever removed from the table and keys are unique by construction.

**Comment by xavierleroy** [comment]
For what it's worth, here is how I feel about the proposed changes:
- +1 for introducing `Hashtbl.set` as a synonymous for `Hashtbl.replace`
- +1 for reordering the declarations in `Hashtbl` so that it describes `Hashtbl.set` and `Hashtbl.find` first, and much later, in a separate section marked "Advanced usage", `Hashtbl.add` (with the "shadowing" behavior") and `Hashtbl.find_all`.
- -1 for deprecating `Hashtbl.add`.  It is an advanced function but it has 100% legitimate uses.

**Comment by xavierleroy** [comment]
Just to clarify what I wrote: `Hashtbl.add` is faster but functionally-equivalent to `Hashtbl.replace` when EITHER keys are unique by construction, OR `Hashtbl.remove` is never invoked and the extra memory usage from duplicate keys is negligible.  The first case (unique keys) is quite common.

**Comment by c-cube** [comment]
@xavierleroy I hear you on the fact that `add` is also useful when one knows of additional invariants (although I do 100% of my hashconsing using `Weak.S.merge`, so that's not my use case there). I was not proposing to deprecate the feature, only the short (and confusing) name.

But even there it makes sense to use a slightly longer, slightly more explicit name, correct? With a comment that explains that we can use this function because there is no shadowing possible because <invariant>
