### ISSUE TITLE
Program built with `--output-complete-exe` cannot read debug infos

### ISSUE THREAD

**Issue by ghost** [ocaml/ocaml#9344]
When a byte code program needs the debug info, for instance to print a backtrace, the runtime tries to open `Sys.executable_name` as a byte code program to read the debug info. That doesn't work when the program is built with `--output-complete-exe`.

For instance:

```
$ echo "raise Not_found" > test.ml
$ ocamlc -o test -output-complete-exe test.ml
$ ./test
Fatal error: exception Not_found
Fatal error: executable program file not found
Aborted (core dumped)
```

**Comment by nojb** [comment]
For reference, the relevant logic is in https://github.com/ocaml/ocaml/blob/1fd6dc077d63fc8e0b36e2a684dae55a0f3383d4/runtime/backtrace_byt.c#L359-L363

**Comment by ghost** [comment]
Indeed. So I haven't yet dug deep into this, but I'm thinking of:

- having a variable pointing to a function that read the debug info
- the default implementation would open the executable as it does now
- when generating the C code for `--output-complete-exe`, we would set this variable to a function that reads directly from the static data containing the debug info

**Comment by gasche** [comment]
Thanks for the catch! It's a shame that we didn't notice this discrepancy before; we should try to get testsuite coverageT for this (even if recording the wrong behavior to not break the testsuite, with a note saying that it is wrong). Are there other aspects of bytecode programs that we are missing with `--output-complete-exe`?

**Comment by glondu** [comment]
We've faced this issue in Debian, with 4.08.1 patched to make `-custom` basically work like `--output-complete-exe` now (the error was triggered when building ppxlib, too). The surrounding code in the OCaml runtime seemed to behave correctly, so I decided to comment out the call to `caml_fatal_error`:

https://salsa.debian.org/ocaml-team/ocaml/-/blob/debian/sid/debian/patches/0006-read_main_debug_info-do-not-die-in-custom-executable.patch

This is not very subtle... but it doesn't seem to trigger other misbehaviours. Of course, @diml 's plan looks better.

**Comment by ghost** [comment]
No problem, it's actually @RiderALT and @jamesjer who reported the error to ppxlib and did the debugging work. I just narrowed the reproduction case and grepped the compiler for the error message :)

Adding a reproduction case seems good. It seems simple enough to fix, so I'm going to take a shot at fixing it directly.

@glondu not subtle indeed :) I guess the difference must be that you don't get a nice backtrace.

**Comment by ghost** [comment]
So I started hacking around and it seems that with `--output-complete-exe`, we currently don't save the debug info at all:

```
$ touch x.ml
$ ocamlc --output-complete-exe -o x -c x.ml
$ ocamlc -g --output-complete-exe -o xg -c x.ml
```

and `x` and `xg` are the same.

**Comment by dra27** [comment]
Cross-referencing #2195

**Comment by ghost** [comment]
Ok, so since programs built with `--output-complete-exe` don't embed the debug  info, I'm planning to do a quick fix along the lines of what @glondu did. Then I'll backport it to 4.10.0. And then we can look at the better long term solution, which is to effectively embed the debug info for such executables.

**Comment by nojb** [comment]
Thanks for looking at this @diml!

For the long term solution, note that there is already some logic to pass the debug info via a side file for bytecode executables: one can set the `CAML_DEBUG_FILE` environment variable to point to a `.cds` file that contains the marshalled debug info, and it will be used when unwinding stack traces:

https://github.com/ocaml/ocaml/blob/22b1df80c4b326ca1cde199e566fd2b7874073df/runtime/startup_byt.c#L508-L511

and

https://github.com/ocaml/ocaml/blob/87296ee8e0ffa5e29d21fc54b6a8bce3db6e1889/runtime/backtrace_byt.c#L353-L357

(The `.cds` file is generated when compiling bytecode to a `.c` file.)

I guess we could adapt the same logic to point to a global variable containing the marshalled debug info directly in the generated code.

**Comment by ghost** [comment]
Ah, thanks for the pointer @nojb, I wasn't aware of cds files!

**Comment by modlfo** [comment]
I wonder if this issue is related to a problem I just discovered. I'm using Dune to build a program that has the mode `byte_complete`. In OCaml 4.09.1, I can debug the produced executable (with extension `.bc.exe`) using ocamldebug. I'm trying to move to OCaml 4.11.x, but the same executable shows the message `is not a bytecode file`. I have the same issue with OCaml 4.10.x.

**Comment by gasche** [comment]
If I understand correctly, this is a choice made by Dune which compiles bytecode executables without debug information. According to https://github.com/ocaml/dune/issues/3017 and https://github.com/ocaml/dune/pull/3066, you should be able to get Dune to build not-complexe-exe bytecode executables by asking for the target `foo.bc` instead of `foo.bc.exe`, provided you used the explicit `(mode bytes)` stanza (see [here](https://dune.readthedocs.io/en/stable/quick-start.html#building-a-hello-world-program-in-byte-code)).

**Comment by modlfo** [comment]
@gasche I don't think this has to do with Dune. I'm using the same version (2.7.1) in both switches. Unless they behave differently depending on the OCaml compiler. That's why I though it was related to a change in the OCaml compiler itself.

Unfortunately, due to the complexity of our build system and dependencies, I have not being able of linking a bytecode executable (.bc not .bc.exe). I need to give it a try one more time. We haven't been able of moving from 4.09 due to issues in ocamldebug in recent versions (huge slowdowns and crashes).

As I mentioned, I'm not sure if this specific issue is related to the fact that now I get the message `is not a bytecode file`. If it's not related, just ignore this. I will try to create a minimal example.

**Comment by dra27** [comment]
Dune does behave differently depending on the compiler, most specifically here because `-output-complete-exe` is only available in 4.10+. See the implementation in https://github.com/ocaml/dune/pull/2692

**Comment by gasche** [comment]
As a meta note: there are few users of `ocamldebug` and they tend to rarely report feedback, so as the compiler upstream we aren't told about new issues until it's too late to fix them in the versions that users want to use. If you have found crashes in ocamldebug, it would help if you could ensure that they have been reported. If previous reports exist, it is useful to post a message pointing out that you are also affected.

(One large slowdown was reported in the ocamldebug of OCaml 4.10, but it was reported months after the release so the fix will only be including in our upcoming releases.)

**Comment by ghost** [comment]
@modlfo this is expected, and not related to this ticket.

The old way to produce self-contained bytecode programs wasn't very portable, so we changed it. However, ocamldebug wasn't updated to support the new way. We have ideas for how to update ocamldebug to support the new way. Happy to share if you or someone is interested in giving it a shot.

**Comment by modlfo** [comment]
@jeremiedimino I'm glad to help. Let me know what I need to do. Today I found another issue when generating a `.bc.exe` in our code base (when using 4.11.1).

**Comment by ghost** [comment]
Great :)

So with the old way (`-custom` option), the compiler would produce a file that was the concatenation of an ELF executable and a bytecode program. ocamldebug, which needs to extract the bytecode to function was just reading it directly at the end of the file. This method was problematic because the `strip` command would always strip the bytecode part, and some Linux distributions strip all their executables.

With the new way (`-outpdut-complete-exe` option), the compiler produces only an ELF executable and the bytecode is stored inside a symbol. As a result, the bytecode is never stripped by `strip`, but on the other hand it is more difficult for `ocamldebug` to extract the bytecode.

So the goal is to teach `ocamldebug` how to extract the bytecode from a program produced by `-output-complete-exe`. @nojb recently added a `Binutils` module that can decode the ELF format, so I would suggest to use this module in ocamldebug to locate the symbol that contains the bytecode and extract it from there.

A few pointers:

- the code of `ocamldebug` is in the `debugger` directory. I don't know this code so I can't give you more precise pointers, you will have to look for the part that loads the bytecode and change it
- using `Binutils`: you can look at `tools/objinfo.ml`, which implements the `ocamlobjinfo` tool, to see how it uses `Binutils`. Essentially, it uses `Binutils` to find the offset at which a symbol is stored and then simply moves to this offset with `seek` and read the data from there
- `bytecomp/bytelink.ml` contains the code that links byte code programs. When using `-output-complete-exe`, the OCaml compiler generates a C file with a `main` function and then calls the C compiler to compile and link it into an executable. The function responsible for generating the C file is `link_bytecode_as_c`. Inside this function, you can see `"static int caml_code[] = {\n"`, which is the part where the bytecode is turned into a C constant array. You might have to remove the `static` so that the symbol becomes global and you can access it form the outside.

**Comment by nojb** [comment]
> With the new way (`-outpdut-complete-exe` option), the compiler produces only an ELF executable and the bytecode is stored inside a symbol. As a result, the bytecode is never stripped by `strip`, but on the other hand it is more difficult for `ocamldebug` to extract the bytecode.
> 
> So the goal is to teach `ocamldebug` how to extract the bytecode from a program produced by `-output-complete-exe`. @nojb recently added a `Binutils` module that can decode the ELF format, so I would suggest to use this module in ocamldebug to locate the symbol that contains the bytecode and extract it from there.

Unfortunately, I don't think this will be enough. Currently, binaries built with `-output-complete-exe` do not even contain debug information. The reason is that most C compilers choke if you try to put a multi-gigabyte string literal in the generated C source. So this obstacle will have to be solved first before the proposed approach can be used.

**Comment by ghost** [comment]
Indeed. I also just remembered about your comment about cds files. We could also update `-output-complete-exe` to also produce a cds file. It'd be a bit less convenient than having everything in the same file, but it would work.

**Comment by dra27** [comment]
C compilers may choke on the literal, but I think most (all?!) linkers can deal with multi-gigabyte objects, so it may just be a matter of having just enough knowledge to generate a single-symbol object file?

**Comment by gasche** [comment]
It looks like there are generic tools to safely embed binary data in a C executable, see the [incbin](https://github.com/graphitemaster/incbin) project for example that exports an `INCBIN` macro that itselfs uses `.incbin` directives in inline assembler, and is tested to work on a wide variety of C compilers (but not MSVC).

**Comment by Et7f3** [comment]
for msvc can we generate an assembly file like this:

```asm
_DATA   SEGMENT
char * caml_code DB 00H                                ; caml_code
        DB      011H
        DB      011H
        DB      011H
        DB      011H
        ORG $+3 ; we reserve 3 other char can be useful if we have zone refilled with 0
_DATA   ENDS
```

Same for gcc/clang we could use:
```asm
came_code:
        .ascii "Hello world"
```

or assembler also choke on big file ?

EDIT:

I tried with:
gen.c:
```c
#include <stdio.h>

int main(void) {
  for (int i = 0; i < 100000; ++i) {
    printf(" DB 030H");
    for (int j = 0; j < 47; ++j) {
      printf(", 030H");
    }
    puts("");
  }
}
```
```shell
cl gen.c
{ cat pre.asm; ./gen; cat post.asm; } > caml_code.asm
```
after 48 elements we get `A2042: statement too complex`

Thing I haven't tested: use other encoding than `030H`

pre.asm is header
post.asm is footer

For this limit we get a `4 891 136` octet binary
[caml_code.zip](https://github.com/ocaml/ocaml/files/7475623/caml_code.zip)
The linking take time (with ml64) and don't choke.
