### ISSUE TITLE
manual: change fibonacci example?

### ISSUE THREAD

**Issue by sanette** [ocaml/ocaml#9351]
At the end of file `coreexamples.html` there is an example with the Fibonacci sequence.
_I know this is just an illustration_, and there is no claim that this function is correct, but it can be found by googleing, and it shows exactly what I'm trying to teach my students not to do... ;)

* (minor) the convention is not the same as Wikipedia, where  F_0=0, F_5=5...
* (quite bad IMO) the double recursive call is kind of horrible. For instance try to compute fib 50...
( it needs about 2^50=1125899906842624 iterations to complete). A normal algorithm would need only 50 iterations.

A normal one would be (for instance)

```
let fib n =
  let rec loop n =
    if n <=0 then 0,1 else let a,b = loop (n-1) in a+b,a in
  fst (loop n);;
```
(then fib 50 returns immediately, of course)

So my request is: could we change this, or use another example? Thanks!!

**Comment by Octachron** [comment]
A pull request to change this standalone example would be welcome.

Nevertheless, I am not that convinced by the complexity argument since a normal algorithm should require only `ln_2 n` calls to compute the `n`-th element of the Fibonacci sequence. 

So it is probably better to switch to another example altogether.

**Comment by sanette** [comment]
Right, of course a "good" algorithm takes O(log(n)) (since you just have to compute powers of a 2x2 matrix). By "normal" I meant "what a first naive approach should do when trying to mimick what you do when you compute fib(10) by hand".

Another solution would be to add a comment saying "Of course, don't do this if you really want to compute Fibonacci numbers".

**Comment by Anukriti12** [comment]
This Fibonacci is linear time (so can easily compute fib(50))
As well as for Fib(0) it gives 0 Fib(1) = 1 Fib(2) = 2 as per wikipedia. It also prints every every fibonacci it computes like a table to make the code readability simpler.
```ocaml
let fib (n) =
  let previous_ref = ref (0, 1) in
  Printf.printf "fib(0) = 0\n";
  for i = 1 to n do
    let (a, b) = !previous_ref in
    let next = a + b in
    previous_ref := (next, a);
    Printf.printf "fib(%d) = %d\n" i next
  done

let main () =
  let arg = int_of_string Sys.argv.(1) in
  fib (arg);
  exit 0;;
main ();;
```

Output:
![image](https://user-images.githubusercontent.com/31126248/78090282-4e81f200-73e7-11ea-9d0e-3ca64e2b6b0b.png)

**Comment by sanette** [comment]
> So it is probably better to switch to another example altogether.

What about Euclid's algorithm for the GCD? Simple, clean, and super fast.

```
let rec gcd a b =
  if b = 0 then abs a
  else gcd b (a mod b)

```

**Comment by gasche** [comment]
Personally I like the idea of using `gcd` as an example.

**Comment by gasche** [comment]
@xavierleroy would you be happy with `gcd` as an example instead of `fib`? I think it meets both your requirement (simple mathematical expression) and our preference for not-wildly-inefficient examples.

(The fact that people disagree on the initial terms of the Fibonacci sequence is also a reason to avoid it as an example; at least we should change the example to have `fib 0 = 0`.)

**Comment by xavierleroy** [comment]
OK with GCD,  Not a very exciting function, but Fibonacci isn't either.

**Comment by gasche** [comment]
@Anukriti12 based on this feedback, I think that you could rework a PR using the `gcd` function above rather your modified Fibonacci, if you wish to. (One then has to read two parameters from the command-line.)
