### ISSUE TITLE
Rust-like or-patterns support syntax improvement feature request

### ISSUE THREAD

**Issue by XVilka** [ocaml/ocaml#9354]
They introduced ["or-patterns"](https://github.com/rust-lang/rust/issues/54883) recently, which allows to avoid some code duplication.
In OCaml that would look something like:
```ocaml
match x with
| Some a -> ()
| Some b -> ()
| Some _ -> ()
| None -> ()
```
becomes
```
match x with
Some (
| a -> ()
| b -> ()
| _ -> ()
)
| None -> ()
```
Or something like that.

**Comment by gasche** [comment]
In the [Rust RFC](https://github.com/rust-lang/rfcs/blob/master/text/2535-or-patterns.md), I only see pretty standard or-patterns `p | q`, possibly nested. They do not contain right-hand-sides, unlike your example above where you write `Some(p -> e1 | q -> e2)`. I don't see any sign of Rust supporting this. (I proposed this syntax [on Discuss](https://discuss.ocaml.org/t/musings-on-extended-pattern-matching-syntaxes/3600) for the last 1st of April.)

**Comment by XVilka** [comment]
They had this example in their recent blogpost: https://blog.rust-lang.org/inside-rust/2020/03/04/recent-future-pattern-matching-improvements.html

**Comment by gasche** [comment]
I do not see such an example in this blog post, which code fragment are you referring to?

**Comment by XVilka** [comment]
```rust
// Any local node that may call something in its body block should be explored.
fn should_explore(tcx: TyCtxt<'_>, hir_id: hir::HirId) -> bool {
    match tcx.hir().find(hir_id) {
        Some(
            Node::Item(..)
            | Node::ImplItem(..)
            | Node::ForeignItem(..)
            | Node::TraitItem(..)
            | Node::Variant(..)
            | Node::AnonConst(..)
            | Node::Pat(..),
        ) => true,
        _ => false,
    }
}
```

**Comment by gasche** [comment]
I believe that you are reading the example wrong. There are no right-hand-sides within the `Some( p | q | ... )` pattern.

**Comment by Centril** [comment]
Indeed, @gasche is right that the RFC/issue/blog-post is about standard or-patterns. Rust is just catching up to OCaml. ;)
