### ISSUE TITLE
Set Module in Ocaml: expected type VariableSet.elt = VariableOrder.t error

### ISSUE THREAD

**Issue by tmibvishal** [ocaml/ocaml#9377]
**Platform:** MAC OS X
**OS Version:** 10.15.3
**Category:** typing

If I have the following code
```ocaml
module IntSet = Set.Make( 
  struct
    let compare = Pervasives.compare
    type t = int
  end );;
IntSet.singleton 1;;
```
I get perfect output
```
# IntSet.singleton 1;;
- : IntSet.t = <abstr>
```

But if I try doing it in this manner
```ocaml
module IntOrder : Set.OrderedType = struct
  let compare = Pervasives.compare
  type t = int
end;;
module IntSet = Set.Make( IntOrder );;

IntSet.singleton 1;;
```
I get this error but IntOrder.t is int itself
```
# IntSet.singleton 1;;
Error: This expression has type int but an expression was expected of type
         IntSet.elt = IntOrder.t
```

**Comment by Octachron** [comment]
This is the expected behavior, signature constraints in OCaml hide information.
By writing
```ocaml
module IntOrder: Set.OrderedType = ...
```
you have hidden the equality `IntOrder.t`=`int` and made the type `IntOrder.t` abstract.

If you have more question about Ocaml module system, I will happy to answer you at https://discuss.ocaml.org .
