### ISSUE TITLE
ephemeron's doc is broken

### ISSUE THREAD

**Issue by redianthus** [ocaml/ocaml#9381]
Hi,

The doc for [Ephemeron.GenHashTable.MakeSeeded](https://caml.inria.fr/pub/docs/manual-ocaml-4.10/libref/Ephemeron.GenHashTable.MakeSeeded.html) seems to be broken. If you grep for `(** same as` you should see the broken part. Here's [the corresponding .mli](https://github.com/ocaml/ocaml/blob/trunk/stdlib/ephemeron.mli#L335). I'm not sure what's going on, but at least it's reported now.

Cheers.

**Comment by Octachron** [comment]
Ocamldoc doesn't really know how to handle explicit signatures in functor arguments. In this case, it decided to use the whole code as a description here. An indirect fix would be to give the module type of the argument a name. This is a non-documentation fix to a documentation issue, but this is in line with the good practice of naming large signature.
