### ISSUE TITLE
request: ocamldebug: toggle to previous commands with arrow keys?

### ISSUE THREAD

**Issue by jajajasalu2** [ocaml/ocaml#9382]
Hi,

Can it be possible to introduce a feature to toggle to previously entered commands in ocamldebug?

I'm using version 4.07.0, and when I'm debugging for long periods, having to type in repeated commands is a bit stressful. Debuggers like the python debugger and gdb have the capability to toggle to previous commands with the arrow keys.

I could not find any pull requests or issues for this, so I'm making this issue. Apologies if this has been asked before.

**Comment by nojb** [comment]
None of the OCaml REPL-prompts (toplevel, debugger, ...) support readline functionality. This is due I think to the lack of a good cross-platform solution.

However, you can obtain more or less the same effect by using the `rlwrap` utility, which makes readline available to an arbitrary command-line program, as follows:
```
rlwrap ocamldebug ...
```

**Comment by jajajasalu2** [comment]
Thank you! `rlwrap` is quite helpful and does the job.
