### ISSUE TITLE
Structure fails to ascribe to signature with signature-local binding

### ISSUE THREAD

**Issue by ncik-roberts** [ocaml/ocaml#9384]
Version: 4.09.0

A structure fails to ascribe to a signature that gives the type of a val binding in terms of a signature-local type binding. The same structure (plus the definition of the previously signature-local type binding) successfully ascribes to a similar signature which doesn't have any signature-local type bindings.

This behavior seems to only happen when the signature-local type binding binds a type variable to a polymorphic variant type.

a.ml

    module M : sig
      type 'a t := [< `A ] as 'a
      val f : 'a -> 'a t
    end = struct
      let f x = x
    end

b.ml

    module M : sig
      type 'a t = [< `A ] as 'a
      val f : 'a -> 'a t
    end = struct
      type 'a t = [< `A ] as 'a
      let f x = x
    end

Expected: a.ml, b.ml both successfully compile
Actual: a.ml fails to compile; b.ml successfully compiles

```
$ ocamlopt a.ml
File "a.ml", lines 4-6, characters 6-3:
4 | ......struct
5 |   let f x = x
6 | end
Error: Signature mismatch:
       Modules do not match:
         sig val f : 'a -> 'a end
       is not included in
         sig val f : [< `A ] -> [< `A ] end
       Values do not match:
         val f : 'a -> 'a
       is not included in
         val f : [< `A ] -> [< `A ]
       File "a.ml", line 3, characters 2-20: Expected declaration
       File "a.ml", line 5, characters 6-7: Actual declaration
```

**Comment by lpw25** [comment]
This comes from the fact that destructive substitutions are not able to handle constrained types in general. Indeed, if you try to implement this code using traditional destructive substitutions you get an error:
```ocaml
# module type T = sig
    type 'a t = [< `A] as 'a
    val f : 'a -> 'a t
  end;;

# module type R = T with type 'a t := [< `A] as 'a;;
Line 1, characters 16-48:
1 | module type R = T with type 'a t := [< `A] as 'a;;
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Error: Destructive substitutions are not supported for constrained 
       types (other than when replacing a type constructor with 
       a type constructor with the same arguments).
```
See #792 for a discussion of why this restriction exists (basically it would be quite a lot of work to support it properly).

The new local bindings should require the same restriction.

**Comment by lpw25** [comment]
Here's an example that crashes the compiler:
```ocaml
# type foo = { foo : 'a. ([< `A] as 'a) -> 'a };;
type foo = { foo : 'a. ([< `A ] as 'a) -> 'a; }
# module F (X : sig type 'a t := [< `A ] as 'a type foo2 = foo = { foo : 'a. 'a t -> 'a t } end) = struct
    let f { X.foo } = foo
  end;;
    Fatal error: exception File "typing/ctype.ml", line 1419, characters 11-17: Assertion failed
Raised at file "typing/ctype.ml", line 1419, characters 11-23
Called from file "list.ml", line 92, characters 20-23
Called from file "typing/ctype.ml", line 1421, characters 13-38
Called from file "typing/ctype.ml", line 1440, characters 10-60
Called from file "typing/btype.ml", line 544, characters 14-21
Called from file "typing/typecore.ml", line 1455, characters 34-60
Called from file "typing/typecore.ml", line 733, characters 6-9
```
Still working on making it a soundness bug.

**Comment by lpw25** [comment]
Actually, my initial analysis is wrong. Whilst the lack of the constrained types restriction is a bug this issue can be triggered without using constrained types:

```ocaml
# type foo = { foo : 'a. ([< `A] as 'a) -> 'a };;
type foo = { foo : 'a. ([< `A ] as 'a) -> 'a; }
# module F (X : sig type 'a t := 'a type foo2 = foo = { foo : 'a. ([< `A] as 'a) t -> 'a t } end) = struct
    let f { X.foo } = foo
  end;;
    Fatal error: exception File "typing/ctype.ml", line 1419, characters 11-17: Assertion failed
Raised at file "typing/ctype.ml", line 1419, characters 11-23
Called from file "list.ml", line 92, characters 20-23
Called from file "typing/ctype.ml", line 1421, characters 13-38
Called from file "typing/ctype.ml", line 1440, characters 10-60
Called from file "typing/btype.ml", line 544, characters 14-21
Called from file "typing/typecore.ml", line 1455, characters 34-60
Called from file "typing/typecore.ml", line 733, characters 6-9
Called from file "typing/typecore.ml", line 1479, characters 12-248
```

**Comment by lpw25** [comment]
It turns out these were two separate bugs within the same part of the type-checker. #9385 should fix them both.

However, it is still the case that this example should be prevented as we cannot handle local constrained types in general. I'm going to make a PR to add that restriction.
