### ISSUE TITLE
Limitations of `with module` wrt module aliasing

### ISSUE THREAD

**Issue by rossberg** [ocaml/ocaml#9400]
Trying to write some functor code I ran into `with module` not having the expected effect on module aliasing. Minimised example:
```
module type VAR = sig end
module type CONTEXT = sig module Var : VAR end

module Type (Var : VAR) = struct type t = X end

module Make (Var : VAR) (Context : CONTEXT with module Var = Var) =
struct
  let f (x : Type(Var).t) = (x : Type(Context.Var).t)
end
```
The `let` won't type-check. Effectively, the `with module` has no effect here. That can be seen in the REPL:
```
# module type CONTEXT = sig module Var : VAR end;;
module type CONTEXT = sig module Var : VAR end
# module type CONTEXT' = CONTEXT with module Var = Var;;
module type CONTEXT' = sig module Var : sig end end
```
whereas upfront manifest modules,
```
# module type CONTEXT'' = sig module Var = Var end;;
module type CONTEXT'' = sig module Var = Var end
```
works as expected.

I assume that has to do with the lack of syntax for manifest modules with (possibly narrowing) signature annotations:
```
# module type T = sig module A : S = X end;;
Error: Syntax error: 'end' expected
```

It would be nice to close this gap, because it essentially breaks the classical use of "fibration" via nested modules in the presence of applicative functors. (My workaround was to replace it with parameterisation, but short of parameterised module types, that requires nesting signature definitions into auxiliary functors.)

**Comment by garrigue** [comment]
Actually, there are two separate problems here.
One is that there is currently no way to alias a functor argument, and this is indeed related to the absence of transparent ascriptions you describe here.
We are working on that (@lpw25 and @Drup have some proposals).

But there is also another problem: even if we could alias `Var`, this is not the original meaning of `with module M = Var`. The question is whether this breaks little enough code that we can change the semantics silently, or we need to introduce new syntax. Note that this part is really only about syntax, since internally there is already a distinct representation for module aliases.

**Comment by rossberg** [comment]
> One is that there is currently no way to alias a functor argument, and this is indeed related to the absence of transparent ascriptions you describe here.

The one way I know is parameterised signatures:
```
module type VAR = sig end
module CONTEXT (Var : VAR) =
struct
  module type S = sig module Var = Var end
end

module Type (Var : VAR) = struct type t = X end

module Make (Var : VAR) (Context : CONTEXT(Var).S) =
struct
  let f (x : Type(Var).t) = (x : Type(Context.Var).t)
end
```
That works, but requires you to plan ahead and forego fibration, and thus may not scale so well.

> But there is also another problem: even if we could alias Var, this is not the original meaning of with module M = Var.

Isn't the original semantics to selfify the respective sub-signature with the module's path? I assume that would still happen, just adding the manifest path identity on the side. But I'm not sure if there might be a problem with that.

**Comment by rossberg** [comment]
Btw, a related issue is that module aliasing is tied to structure types in the first place. For example, this does not work:
```
module F(X : sig end) = Var
let f (x : Type(Var).t) = (x : Type(F(Int)).t)
```
although something seemingly more complicated does:
```
module F(X : sig end) = struct module Var = Var end
let f (x : Type(Var).t) = (x : Type(F(Int).V).t)
```

I think you mentioned to me a while ago that there are plans to overhaul the `module type of` construct to become something closer to singleton types. If that was the case, then one could perhaps desugar manifest modules into singleton types and probably handle cases like this one as well?

**Comment by Drup** [comment]
@rossberg  Yes, that's how it works in the WIP version I'm working on: singleton types that are not tied to the structure. 

> But there is also another problem: even if we could alias `Var`, this is not the original meaning of `with module M = Var`. The question is whether this breaks little enough code that we can change the semantics silently, or we need to introduce new syntax.

In positive positions, this simply makes the signature more precise. In negative positions, we already added new type manifests linking to the new module, so it only prevents providing a module argument which is not an alias but has all the exact same types. The behavior can be recovered in a backward compatible manner by desugaring the `with module` into several `with types`. I think I've seen code that does that (related to tyxml, iirc ...) but I think it's worth making the change in the long run.

**Comment by lpw25** [comment]
>  The behavior can be recovered in a backward compatible manner by desugaring the with module into several with types. 

My plan for my WIP version (apologies for getting us into a situation with two WIP branches -- I should have finished mine of years ago now) was to support the operation:
```
S with module M : T
```
to replace a module type with a stronger one. Then you can get the old behaviour of `with module M = N` via:
```
S with module M : module type of struct include N end
```

**Comment by rossberg** [comment]
> Then you can get the old behaviour of `with module M = N` via:
> ```
> S with module M : module type of struct include N end
> ```

I don't think that is the same when nested structures occur. Consider:
```
module type S = sig module M : sig module A : sig type t end end end
module N = struct module A = struct type t = int end end
module type T = S with module M = N
```
In current Ocaml, that yields
```
module type T = sig module M : sig module A : sig type t = int end end end
```
The replacement will presumably yield
```
module type T = sig module M : sig module A = N.A end end
```

**Comment by lpw25** [comment]
Good point. You could still get the old behavior with:
```ocaml
  S with module M : module type of struct include N end [@remove_aliases]
```
although at that point we might as well just support:
```ocaml
  S with module M = N [@remove_aliases]
```
I think using an attribute is kind of fine because I think people should try to move away from these old behaviours. They are more important as quick fixes for existing code.
