### ISSUE TITLE
Ocamldoc is rendering list variant constructors without parentheses

### ISSUE THREAD

**Issue by yawaramin** [ocaml/ocaml#9421]
See e.g. https://caml.inria.fr/pub/docs/manual-ocaml/libref/List.html

```ocaml
type 'a t = 'a list =
| []
| :: of 'a * 'a list
```

This is syntactically incorrect, the expected output rendering is:

```ocaml
type 'a t = 'a list =
| ([])
| (::) of 'a * 'a list
```

**Comment by Octachron** [comment]
Indeed, ocamldoc was not updated after the change of internal representation of `::`. Thanks for the report. (The parentheses are not needed for `[]`.)

**Comment by gasche** [comment]
Could we hide the re-exports from ocamldoc?

**Comment by Octachron** [comment]
Do we want to? The re-export has an observable effect on user code whenever the List module is opened (since it affects which constructors are in the scope). I am not keen on making this observable effect unpredictable from the documentation.

**Comment by gasche** [comment]
Makes sense, although I must say that I slightly regret this decision to re-export. It is useful for expert users, but it makes the documentation less beginner-friendly by starting with this weird syntax (I'm not even sure it is considered part of the language and not just an undocumented experimental feature).

**Comment by yawaramin** [comment]
@gasche re-exporting seems to be covered in the reference manual ( https://caml.inria.fr/pub/docs/manual-ocaml/typedecl.html ):

> The optional type equation `= typexpr` makes the defined type equivalent to the type expression `typexpr`: one can be substituted for the other during typing. If no type equation is given, a new type is generated: the defined type is incompatible with any other type.

**Comment by gasche** [comment]
But is `(::)` covered in the manual?

**Comment by yawaramin** [comment]
Looks like it is: https://caml.inria.fr/pub/docs/manual-ocaml/typedecl.html#constr-decl

EDIT: but `true`, `false`, and `()` are not listed as valid constructors although they are accepted. I assume they were intentionally omitted.
