### ISSUE TITLE
Debian install fails brutally

### ISSUE THREAD

**Issue by alcover** [ocaml/ocaml#9434]
Install blowing up in Debian stable :
**$ apt install opam
$ opam init
$ Do you want opam to modify ~/.profile? y**
[...]
### > Creating initial switch (ocaml-system>=4.02.3)

Then goes nuts, 100% CPU 100% RAM (16G..) for long minutes.
Then fails : 
### >[ERROR] Solver failed: "/usr/bin/aspcud
        /tmp/opam-me-24664/solver-in-24664-548b09
        /tmp/opam-me-24664/solver-out-24664-8b8a2d
        -count(removed),-sum(request,version-lag),-count(down),-sum(solution,version-lag),-count(changed)"
        exited with code 1 "ERROR: grounder returned with non-zero exit status"

**Comment by hannesm** [comment]
Dear @alcover, thanks for your report. This is an issue with `opam` (https://github.com/ocaml/opam) and debian. It has been already reported there (see https://github.com/ocaml/opam/issues/3827 - several workarounds are documented in that issue) as well as to the debian OCaml team (at https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=908203). The current state of opam in debian is annoying, and I hope the debian maintainer team will solve this rather sooner than later in their stable release series.

**Comment by alcover** [comment]
@hannesm 
Thank you.
I'm quite puzzled by this state of affairs..
I'd bet Ocaml and Debian intersect quite often.
How many users must have been burned by this ..
