### ISSUE TITLE
 #load "graphics.cma";; Cannot find file graphics.cma.

### ISSUE THREAD

**Issue by ghost** [ocaml/ocaml#9472]
Versions:
---------
Catalina 10.15.4
Xcode 11.4.1
XQuartz 2.7.11 (xorg-server 1.18.4)

 Hello,
After done : 
```
$ brew install opam 
```
(y for opams questions)
```
$ opam init
$ eval $(opam env)
$ opam install ocaml
$ opam install graphics

The following actions will be performed:
  ∗ install graphics 5.1.0

<><> Gathering sources ><><><><><><><><><><><><><><><><><><><><><><><><><><>  🐫 
[graphics.5.1.0] found in cache

<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><>  🐫 
∗ installed graphics.5.1.0
Done.
```
and the test
```
$ ocaml 
        OCaml version 4.10.0

# #load "graphics.cma";;
Cannot find file graphics.cma.
# 
```

I don't understand this issue.

Thanks for your help,

**Comment by Octachron** [comment]
Starting with OCaml 4.09.0, `graphics` is no longer part of the compiler distribution. It is thus necessary to use it as a normal library by invoking `#require "graphics"` rather than `#load "graphics.cma"`.
