### ISSUE TITLE
Toplevel #mod_use behaves differently in OCaml 4.11, breaking topkg

### ISSUE THREAD

**Issue by rwmjones** [ocaml/ocaml#9474]
It seems as if the toplevel `#mod_use` changed in some way that breaks topkg.  It's best to read the Fedora contributor's full description of the problem here:
https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/message/NEOBFOY2RIBSKEZMLC7AXA463KPWLDBE/

We are tracking this in the following downstream bug: https://bugzilla.redhat.com/show_bug.cgi?id=1825451

**Comment by rwmjones** [comment]
I should say here that I don't know if this is a bug, but I did search the git log to see if there was any indication that the change was made intentionally, and I couldn't see anything.  But if this is intentional, just close this bug and we'll work with topkg to make the required changes.

**Comment by nojb** [comment]
xref #9457 #9455

**Comment by rwmjones** [comment]
Oh this definitely looks like a duplicate of #9455.

**Comment by gasche** [comment]
Let's close the issue as a duplicate -- bug thanks again for your bug report!
The fix in #9457 is going to be merged very soon.
