### ISSUE TITLE
#require "graphics" ;; Unknown directive `require'.

### ISSUE THREAD

**Issue by ghost** [ocaml/ocaml#9475]
Hello 

i have an issue

```
% ocaml
        OCaml version 4.10.0
# #require "graphics" ;;
Unknown directive `require'.
# open Graphics ;;
Error: Unbound module Graphics
```
The opam reinstall says 
```
opam reinstall graphics
The following actions will be performed:
  ↻ recompile graphics 5.1.0

<><> Gathering sources ><><><><><><><><><><><><><><><><><><><><><><><><><><>  🐫 
[graphics.5.1.0] found in cache

<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><>  🐫 
⊘ removed   graphics.5.1.0
∗ installed graphics.5.1.0
```
and always the same problem

Thanks for your help

**Comment by Chris00** [comment]
On 19 April 2020 at 17:29 CEST, fredOnGitHub <notifications@github.com> wrote:
>
> % ocaml
>         OCaml version 4.10.0
> # #require "graphics" ;;
> Unknown directive `require'.

“require” is provided by “topfind”.  Issue first:

#use "topfind";;


Best,
C.

**Comment by ghost** [comment]
> On 19 April 2020 at 17:29 CEST, fredOnGitHub ***@***.***> wrote: % ocaml OCaml version 4.10.0 # #require "graphics" ;; Unknown directive `require'.
> “require” is provided by “topfind”. Issue first: #use "topfind";; Best, C.
```
# #use "topfind";;
Cannot find file topfind.
```

**Comment by Chris00** [comment]
On 19 April 2020 at 17:44 CEST, fredOnGitHub <notifications@github.com> wrote:
>
>  On 19 April 2020 at 17:29 CEST, fredOnGitHub @.***> wrote: % ocaml OCaml
>  version 4.10.0 # #require "graphics" ;; Unknown directive `require'.
>  “require” is provided by “topfind”. Issue first: #use "topfind";; Best, C.
>
> #use "topfind";;
>
> Cannot find file topfind.

Then, execute this first (better: put it in your ~/.ocamlinit):

let () =
  Topdirs.dir_directory (Sys.getenv "OCAML_TOPLEVEL_PATH")
;;

If the variable “OCAML_TOPLEVEL_PATH” is not defined, you should do that first (see `opam config env`), for example by running in your shell

$HOME/.opam/opam-init/init.sh

**Comment by gasche** [comment]
You should install `ocamlfind` (through opam) to get `topfind`, or use the `utop` toplevel (instead of `ocaml`) that comes with `#require` built-in.

This said, those are (sensible) user-level issues, not development issues, so this repository is not the appropriate place to raise them. Please consider going to the [Discuss Forum](https://discuss.ocaml.org/) or [IRC/Discord groups](https://ocaml.org/community/mailing_lists.html#Discussion-Groups) for your questions.
