### ISSUE TITLE
Feature request: Stdlib.Random.int62

### ISSUE THREAD

**Issue by UnixJunkie** [ocaml/ocaml#9487]
Dear maintainers,

From reading the documentation for Random.int, I understand it
could be named Random.int30.
But, nowadays we have 64 bits integers, so we might want
to have a Random.int62 that would give us a random
integer for the 64 bits era.

That is to say: Random.int is from the OCaml 32 bits era.
I pledge for the addition of Random.int62, which would be its counterpart
for the 64 bits era.

If people are interested, I will try to send a PR.

The interface would be:
```
val Random.int62: int -> int
```

Best regards,
F.

**Comment by dra27** [comment]
Not sure why it needs a new function (especially as that would have to fail on 32-bit systems) - I've pushed a tentative extension of `Random.int` but I'm not sure if there's a history as to why it was constrained to 2^30 in the first place.

**Comment by UnixJunkie** [comment]
Why a new function: to not change the behavior of the existing one and hence satisfy upward compatibility.
The newly introduced function would indeed have to fail on 32-bit systems, however if this is documented, I don't see any problem with that.

**Comment by Octachron** [comment]
Fixed by #9489
