### ISSUE TITLE
Unix.stat rounds time in some circumstances

### ISSUE THREAD

**Issue by d3zd3z** [ocaml/ocaml#9490]
The implementations of `Unix.stat` and friends convert file times to a double using the following code:

```c
  mtime = caml_copy_double((double) buf->st_mtime
                           + (NSEC(buf, m) / 1000000000.0));
```

Unfortunately, with the seconds part of time needing 31 bits, and nanoseconds needing 30 bits, the full precision doesn't fit into a double. If the nanosecond portion of the time is too large, the double value of time will instead be rounded to the next second. Given that many programs only look at the seconds field, and truncate the nanosecond portion, this means that the time seen by Ocaml will appear to be off.

As an example, I have a file: with a stat of
```
Modify: 2018-11-12 13:28:55.999999931
```

After doing a backup and restore with a tool that doesn't record the nano second times, the stat value is:
```
Modify: 2018-11-12 13:28:55.000000000 -0700
```

My file integrity program [osure](https://github.com/d3zd3z/osure) uses only the integer seconds portion of the time, and as a consequence, sees this time as being one second off.

Honestly, I'm not sure what the correct fix is. I will probably end up implementing my own stat call that returns the time as two values, or something like that.

**Comment by d3zd3z** [comment]
One possible fix, at least that would work with reasonably recent times, and IEEE doubles would be to use `+ ((NSEC(buf, m) & 0xfffffe00) / 1000000000.0)` to get the sub-second portion of the time. This should at least prevent rounding (although I haven't tested it, and may have the constant off).

**Comment by xavierleroy** [comment]
Interesting issue!  I like floating-point puzzles, but I'll mention my master @silene just in case.

A pedestrian fix would be to compute the sum `SEC + NSEC / 1e9` using downward rounding instead of round-to-nearest.  I know it's bad style to change rounding modes; on the other hand, this computation is not speed critical at all.

Another possible fix would be to check that the integer part of the sum is equal to `SEC`, and return the predecessor of the sum if not.

Zeroing low bits of `NSEC` before the sum should also work, but it's unclear to me how many bits to zero as a function of `SEC`.

**Comment by silene** [comment]
No clue. If the specification is that the integer part should be correct, then the following is presumably the best way of doing it:

> Another possible fix would be to check that the integer part of the sum is equal to SEC, and return the predecessor of the sum if not.

Note that you do not even need to compute the integer part. Comparing the result with `SEC + 1` is sufficient.

**Comment by d3zd3z** [comment]
Using the predecessor of the sum would result in the time being almost a second off. Although the cases that ignore the fractional part would then work, other cases would not. I guess you would need to subtract an appropriate epsilon to get slightly before the next integer.

**Comment by silene** [comment]
You are misunderstanding. Here, "predecessor" means the floating-point predecessor, i.e., the largest floating-point number that is smaller than the result. Cf `nextafter`.
