### ISSUE TITLE
Adding cram test support in the testsuite

### ISSUE THREAD

**Issue by ghost** [ocaml/ocaml#9501]
At a recent developer meeting, we discussed adding support for cram tests in the OCaml test suite. This should make it easier to add "integration tests" in the test suite, in particular for bug reproduction cases.

This ticket is for tracking the evolution of this work. If you are wondering what cram tests are, you can have a look at [this demo repository](https://github.com/jeremiedimino/cram-demo).

TODO:
- [ ] 1. add the code of the cram test tool in the repo
- [ ] 2. teach ocamltest about `.t` files and how to handle them
- [ ] 3. setup the environment for cram tests
- [ ] 4. add a section in `HACKING.md` to describe how to add and work with cram tests

1 is so that we don't have to install the cram tool to run the testsuite. The cram tool can be embed directly in `ocamltest` for simplicity.

For 3, we should make sure that inside `.t` things such as `ocamlc` or the stdlib point to the local newly built ones rather than the global ones installed on the system. This can be done by altering environment variables such as `PATH` or `OCAMLLIB`.

For 4, we should also make sure to add a HOWTO aimed at users so that anyone can submit a reproduction case as a pull request that we can just merge.

/cc @shindere

**Comment by shindere** [comment]
Thanks a lot for having opened this issue, @diml.

In your opinion, what should the ocamltest workflow be?

Do you think when ocamltest is called on a `.t` file it should
systematically consider it as a cram test, or do you think only .t files
starting with a `(* TEST *)\ comment should be considered by ocamltest?

**Comment by ghost** [comment]
No problem. In my opinion we should do the former, i.e. systematically consider a `.t` file as a cram test. We don't currently use the `.t` extension for anything else, so we might as well keep the boilerplate to a minimum. Plus `.t` is the extension that is usually used for cram tests. In particular, this is what is mentioned on the page for the original cram test tool: https://bitheap.org/cram/

PS: my username is now @jeremiedimino. I changed it this morning

**Comment by shindere** [comment]
Sorry, @jeremiedimino. I did'nt know it was possible to modify a
username on GitHub but that really nice!

**Comment by ghost** [comment]
Yeah, it's actually pretty easy. Github even sets up redirections for your old repository names so that old URLs don't break.

**Comment by ghost** [comment]
@shindere I started working on 1. I had in mind to embed the tool directly in ocamltest to keep things simple. However, that's turning out to be difficult than expected because `ocamltest` isn't allowed to depend on `Unix`.

The upstream `dune-cram` tool that we use in dune has now been used for hundreds of tests for a few years, so it seems fair to say it is trustworthy. So I'm thinking to instead call `dune-cram`  as an external tool. The drawback would be that people would have to install the tool separately via opam before they can run the testsuite. What do you think?

**Comment by nojb** [comment]
> @shindere I started working on 1. I had in mind to embed the tool directly in ocamltest to keep things simple. However, that's turning out to be difficult than expected because `ocamltest` isn't allowed to depend on `Unix`.

As I understand, the non-dependency of `ocamltest` on `unix` was due to a desire to minimize the amount of "trusted code" in the testing tool. But if we are going to depend anyway on `unix` indirectly through `dune-cram`, we may as well just allow `ocamltest` itself to depend on `unix`, no? Personally I would like to run the testsuite on Windows if at all possible, and having to install an outside tool to do so represents a bit of a chore.

**Comment by ghost** [comment]
That seems fine to me. Another mental model here is to take the `ocamltest` tool as a black box and test it using simpler technologies that we take as granted and trust. For instance, we could have a few shell scripts to test `ocamltest` itself. Then it doesn't matter so much how `ocamltest` itself is implemented.

**Comment by xavierleroy** [comment]
Let'sgive @shindere some time to look at this.  My guess is that the cram test implementation needs no more features from Unix than ocamltest today, namely the ability to spawn a process with redirections of standard input and outputs.  This facility is already available in the ocamltest code base.  If you need more from Unix to implement cram tests, I'd like to hear about it.

**Comment by ghost** [comment]
Spawning processes is all the cram test implementation requires. However, the API for that is quite different from the `Unix` one so it requires rewriting some code in the cram test implementation. Nothing complicated, but if we start copying and rewriting quite a bit of code there is also a higher risk of introducing bugs, especially if the tool is used by a single project.

**Comment by shindere** [comment]
Xavier Leroy (2020/05/07 10:18 -0700):
> Let'sgive @shindere some time to look at this.  My guess is that the
> cram test implementation needs no more features from Unix than
> ocamltest today, namely the ability to spawn a process with
> redirections of standard input and outputs.  This facility is already
> available in the ocamltest code base.  If you need more from Unix to
> implement cram tests, I'd like to hear about it.

You are reading my mind, @dra27. Thanks.

**Comment by shindere** [comment]
I meant @xavierleroy, sorry.

**Comment by ghost** [comment]
I'm not going to have time to revive this anytime soon, so closing
