### ISSUE TITLE
ldexp gives different result in bytecode and native code on riscv64

### ISSUE THREAD

**Issue by rwmjones** [ocaml/ocaml#9515]
I'm using OCaml 4.11 pre from approximately two weeks ago, so ignore this bug if you've very recently fixed ldexp!  Note this bug happens only on riscv64 (HiFive Unleashed).

This test program is a distillation of a test failure that happens in ocaml-num `float_of_big_int` test.  I have reduced it to a simple standalone test case:

```
open Printf ;;

let () =
  printf "backend %s\n"
         (match Sys.backend_type with
	  | Sys.Native -> "native" | Bytecode -> "bytecode" | Other s -> s);
  let f = 0x1p+54 in
  (*let f = 1e16 in*)
  printf "f = %g (%h)\n" f f;
  let r = ldexp f 970 in
  printf "ldexp = %g (%h)\n" r r
```

Bytecode, riscv64 (I believe this is the correct output):
```
backend bytecode
f = 1.80144e+16 (0x1p+54)
ldexp = inf (infinity)
```

Native code, riscv64:
```
backend native
f = 1.80144e+16 (0x1p+54)
ldexp = 3.60288e+16 (0x1p+55)
```

On x86-64 the output is the same as for bytecode above.

**Comment by rwmjones** [comment]
FYI @nojb

**Comment by nojb** [comment]
Thanks for the report, I will take a look.

**Comment by rwmjones** [comment]
Note that 2^54 * 2^970 = 2^1024 which should be beyond what double precision floats can represent (and therefore end up as +infinity).  The native code answer is completely bogus.

**Comment by xavierleroy** [comment]
This could be a mismatch in calling conventions.  `ldexp` is interesting as one of the few C standard library functions that takes a mixture of integers and FP numbers and is not variadic.  And indeed the RISC-V calling conventions for a function taking a double then an int changed between the old ISA 2.1 specification and the newer ELF psABI specification.  

Just to make sure: in Fedora you use the new [ELF psABI specification](https://github.com/riscv/riscv-elf-psabi-doc/blob/master/riscv-elf.md), right?

**Comment by rwmjones** [comment]
TBH I've no idea, but @davidlt says yes we do.  Here is how ldexp is called from a C program, in case that helps to answer the question:
```
   10582:	3ca00513          	li	a0,970
   10586:	fe843507          	fld	fa0,-24(s0)
   1058a:	f27ff0ef          	jal	ra,104b0 <ldexp@plt>
```

**Comment by xavierleroy** [comment]
Yes, that's "obviously" the ELF psABI.  Indeed, the OCaml port seems to use the old ABI for C function calls.  I'll submti a fix later today.

**Comment by rwmjones** [comment]
Disassembly of the test program compiled for native code.  Note it passes 970 (second arg) in a1~~although that is a call to an OCaml function so not necessarily wrong~~:
http://oirase.annexia.org/9515.disas.txt

**Comment by xavierleroy** [comment]
Right.  That's characteristic of the old ABI.  On the OCaml side the issue is here:
 https://github.com/ocaml/ocaml/blob/2e30946419bd22cd6dfd69ea5066b96ce9aab9b8/asmcomp/riscv/proc.ml#L214-L215

**Comment by nojb** [comment]
Indeed, I missed this change between ABIs, thanks for the quick detective work!

**Comment by xavierleroy** [comment]
See #9516 for a proposed fix.

**Comment by xavierleroy** [comment]
> Indeed, I missed this change between ABIs, thanks for the quick detective work!

I went through the same pains recently with the RISC-V port of CompCert, so it's all very fresh in my mind!
