### ISSUE TITLE
Clash with C++ 20 header file version

### ISSUE THREAD

**Issue by bschommer** [ocaml/ocaml#9523]
I recently encountered a problem when compiling some C++ bindings. The problem is that the include path needed for the OCaml header files points normally to the library directory which contains a file name `VERSION`. Unfortunately  C++ introduced a new header file [version](https://en.cppreference.com/w/cpp/header/version) and with a case sensitive file system this results in the OCaml `VERSION` file being included instead of the C++ one.

**Comment by gasche** [comment]
VERSION is installed in `$(ocamlc -where)`, while the .h files are installed in `$(ocamlc -where)/caml`. Why does your C(++) compiler look for headers in `$(ocamlc -where)`?

**Comment by bschommer** [comment]
> VERSION is installed in `$(ocamlc -where)`, while the .h files are installed in . Why does your C(++) compiler look for headers in `$(ocamlc -where)`?

Because adding `$(ocamlc -where)/caml` to the include path would lead to even more clashes, for example `threads` would clash with the standard header of the same name. Also `ocamlopt` automatically adds `-I$(ocamlc -where)/ocaml` to the flags calling the c compiler.

**Comment by bschommer** [comment]
One way of fixing this would be to install the header files in the `includedir` that could be set by the `configure` script, like for example the [GNU Coding Standards](https://www.gnu.org/prep/standards/html_node/Directory-Variables.html) suggest, however this would obviously not be backward compatible and would require additional documentation.

**Comment by gasche** [comment]
> Also ocamlopt automatically adds -I$(ocamlc -where)/ocaml to the flags calling the c compiler.

I see, this is the problem: ocamlopt automatically adds `-I $(ocamlc -where)` (not /ocaml). I suppose that this allows people to then include eg. `<caml/memory.h>`, so the lookup has to start from `$(ocamlc -where)`.

One weird way to fix this would be to move the C headers file to `$(ocamlc -where)/c/caml`, and pass `-I $(ocamlc -where)/c` to the C compilers. We could still provide the old `$(ocamlc -where)/caml` path for compatibility.

The `includedir` option you suggest seems to go, at least by default, to the system library hierarchy `/usr/{local/,}lib`, which is only suitable for system-wide installations of OCaml. It is fine to solve the problem in this case, but it doesn't help for the vast majority of OCaml developers who have a user-local installation (typically through opam). But in any case, if we want to move to a different include directory for C headers, we have to think about the compatibility issues indeed.

Another approach may be to get rid of VERSION. If people can find the `VERSION` file, they should also be able to find compiler binary and call it with `--version` to get the same information.

**Comment by bschommer** [comment]
> One weird way to fix this would be to move the C headers file to `$(ocamlc -where)/c/caml`, and pass `-I $(ocamlc -where)/c` to the C compilers. We could still provide the old `$(ocamlc -where)/caml` path for compatibility.

In that case I would suggest to name the folder `$(ocamlc -where)/include` since then it should be clear that the folder contains the include files.
 
> The `includedir` option you suggest seems to go, at least by default, to the system library hierarchy `/usr/{local/,}lib`, which is only suitable for system-wide installations of OCaml. It is fine to solve the problem in this case, but it doesn't help for the vast majority of OCaml developers who have a user-local installation (typically through opam). But in any case, if we want to move to a different include directory for C headers, we have to think about the compatibility issues indeed.

In that case I would suggest to add a `includedir` option to the configure script, autoconf supports this and then the install location would be `$(prefix)/include`. However the simple approach of using `$(ocamlc -where)` to locate the library would then no longer work.

> Another approach may be to get rid of VERSION. If people can find the `VERSION` file, they should also be able to find compiler binary and call it with `--version` to get the same information.

That would help with this clash, however OCaml installs quite a few files in this folder which might clash with other include files.

**Comment by xavierleroy** [comment]
I'm a bit irritated at C++ for 1- not requiring a suffix on its header files (suffixes are the poor man's type system), and 2- hijacking such common names as "version".  Half of my directories have a file named "Notes" in them.  Does it mean that when C++2032 standardizes a "notes" header file, half of my directories will become unsuitable for C++ compilation?

One solution is just to stop installing the VERSION file, or install it with a different, C++-hardened name like VERSION.txt.  I would hope that few makefiles and scripts read `$(ocamlc -where)/VERSION` to determine the version number, because `$(ocamlc -version)` does the job better and simpler (VERSION has extraneous comment lines that need stripping).

It would be nice to do an OPAM-wide grep for possible uses of the VERSION file.

**Comment by bschommer** [comment]
> I'm a bit irritated at C++ for 1- not requiring a suffix on its header files (suffixes are the poor man's type system), and 2- hijacking such common names as "version". Half of my directories have a file named "Notes" in them. Does it mean that when C++2032 standardizes a "notes" header file, half of my directories will become unsuitable for C++ compilation?
> 
> One solution is just to stop installing the VERSION file, or install it with a different, C++-hardened name like VERSION.txt. I would hope that few makefiles and scripts read `$(ocamlc -where)/VERSION` to determine the version number, because `$(ocamlc -version)` does the job better and simpler (VERSION has extraneous comment lines that need stripping).
> 
> It would be nice to do an OPAM-wide grep for possible uses of the VERSION file.

I agree that this is bad style, however most C++ standard header files don't come with a suffix and I think at least a std before this would have helped.

**Comment by bschommer** [comment]
> It would be nice to do an OPAM-wide grep for possible uses of the VERSION file.

Is there any way to perform such a grep automate or does one to perform this by hand?

**Comment by xavierleroy** [comment]
> Is there any way to perform such a grep automate or does one to perform this by hand?

My own way: run `opam source` on every package returned by `opam list -a`, then use recursive grep or find + grep.  I keep hoping there are better ways.  At any rate, the grep for VERSION is inconclusive, since many packages have VERSION files or Makefile variables.

**Comment by bschommer** [comment]
There seems to be a tool for checking all opam packages, [opam-health-check](https://github.com/kit-ty-kate/opam-health-check), could this help with testing whether not installing the `VERSION` file breaks some packages @kit-ty-kate ?

**Comment by kit-ty-kate** [comment]
> There seems to be a tool for checking all opam packages, [opam-health-check](https://github.com/kit-ty-kate/opam-health-check), could this help with testing whether not installing the `VERSION` file breaks some packages @kit-ty-kate ?

sure, I can check for that. You can use this tool but doing it yourself is most probably going to take several days but with our server it should be faster. I just need a PR with this change in (may it be moved elsewhere or just removed) so that I can run the check.

This is a wild guess but I don't think it's gonna break that many packages, maybe one or two, but most just use `ocaml -vnum`/`ocamlc -version` or dune's `%{ocaml_version}` variable to get the version number. I may be wrong but I don't think I've ever seen any packages use this file before.

**Comment by bschommer** [comment]
> sure, I can check for that. You can use this tool but doing it yourself is most probably going to take several days but with our server it should be faster. I just need a PR with this change in (may it be moved elsewhere or just removed) so that I can run the check.
> 
> This is a wild guess but I don't think it's gonna break that many packages, maybe one or two, but most just use `ocaml -vnum`/`ocamlc -version` or dune's `%{ocaml_version}` variable to get the version number. I may be wrong but I don't think I've ever seen any packages use this file before.

I created PR #9895 which simply does not install the `VERSION` file.
