### ISSUE TITLE
ocamldoc warning for functors and signatures in the standard library

### ISSUE THREAD

**Issue by hendriktews** [ocaml/ocaml#9524]
Running ocamldoc on an mli file with
```OCaml
module M0 : Hashtbl.S
```
produces two warnings
```
Module type Stdlib.Hashtbl.S not found
```
Similarly for functors in ml files. This problem is present in 4.10 and many other versions. It may be related to #5536.

**Comment by gasche** [comment]
Unfortunately, we don't have much manpower to improve these non-trivial aspects of ocamldoc in the future, so it is likely that the issue will remain unaddressed -- I will close it now to focus on issues that are more likely to be revisited in the future. There is more momentum towards using `odoc`, whose design may be more amenable to solve this kind of issues.
