### ISSUE TITLE
building 4.08.1 fails on fedora-32

### ISSUE THREAD

**Issue by xaki23** [ocaml/ocaml#9540]
"found" while trying to build mirage-firewall.
seems like a gray area between "opam" and "ocaml", but @hannesm pointed me here.

switch create 4.08.1 fails on fedora-32 (gcc 10.0.1 and system-ocaml 4.10 )
```
# gcc -shared -o libcamlrun_shared.so interp_bpic.o misc_bpic.o stacks_bpic.o fix_code_bpic.o startup_aux_bpic.o startup_byt_bpic.o freelist_bpic.o major_gc_bpic.o minor_gc_bpic.o memory_bpic.o alloc_bpic.o roots_byt_bpic.o globroots_bpic.o fail_byt_bpic.o signals_bpic.o signals_byt_bpic.o printexc_bpic.o backtrace_byt_bpic.o backtrace_bpic.o compare_bpic.o ints_bpic.o floats_bpic.o str_bpic.o [...]
# /usr/bin/ld: backtrace_bpic.o:/home/user/.opam/mirage-firewall-4.08.1/.opam-switch/build/ocaml-base-compiler.4.08.1/runtime/backtrace.c:31: multiple definition of `caml_debug_info'; backtrace_byt_bpic.o:/home/user/.opam/mirage-firewall-4.08.1/.opam-switch/build/ocaml-base-compiler.4.08.1/runtime/backtrace_byt.c:47: first defined here
# collect2: error: ld returned 1 exit status
# make[1]: *** [Makefile:310: libcamlrun_shared.so] Error 1
# make[1]: Leaving directory '/home/user/.opam/mirage-firewall-4.08.1/.opam-switch/build/ocaml-base-compiler.4.08.1/runtime'
# make: *** [Makefile:323: coldstart] Error 2
```

**Comment by XVilka** [comment]
It's a problem of `-fno-common` with GCC 10, I suspect: https://gcc.gnu.org/gcc-10/porting_to.html

See the respective commit in OCaml https://github.com/ocaml/ocaml/commit/06db4c995ca4d6273a4b809841060e375f10e2cf

**Comment by xavierleroy** [comment]
The issue was fixed in OCaml 4.09.1 and 4.10.0.  Could you use one of those versions instead of 4.08.1?

**Comment by xavierleroy** [comment]
Looks like the answer is "yes": https://github.com/mirage/qubes-mirage-firewall/pull/96#issuecomment-625267322

**Comment by psafont** [comment]
Are there any other workarounds for allowing 4.08.1 switches to be created using the latest version of gcc?

This is going to be painful for Citrix engineers as 4.08.1 is used in supported releases and it's meant to be supported for years.

**Comment by Octachron** [comment]
We are planning to publish updated opam packages for older OCaml versions with an explicit `-fcommon` flag.

See ocaml/opam-repository#16583 .

The easy path is to compile with `CC="cc -fcommon"`. This has the unfortunate effect on turning off a de-optimization (`-fno-tree-vrp`) for gcc that is here as a workaround for an intel sky lake bug.

We willl publish the patched opam packages once this last wrinkle is figured out.

**Comment by glondu** [comment]
In Debian, I applied [this patch](https://salsa.debian.org/ocaml-team/ocaml/-/blob/debian/sid/debian/patches/0007-Avoid-duplicate-definitions-of-common-global-variabl.patch), but the package FTBFS at the moment because of https://github.com/ocaml/ocaml/issues/9800 .
