### ISSUE TITLE
Unclear scope of the recursive modules

### ISSUE THREAD

**Issue by bobzhang** [ocaml/ocaml#9574]
```ocaml
module rec Person: sig include module type of (struct 
  type t = {
    name: string;
    pet: Cat.t; 
  } 
end : sig end)
end = Person

and Cat:sig
  type t = {
    name: string;
    isLazy: bool;
  }  
end = Cat
```
It complains about unbound type `Cat.t`, if I comment that line, everything is fine, is this a bug or expected behavior? 
The error is Error: Illegal recursive module reference
This is a piece of generated code trimmed from the version reported here https://github.com/BuckleScript/bucklescript/issues/4383

**Comment by jberdine** [comment]
I don't know whether this is intended, but would cutting the cycle in something like the following way work in your case:
```ocaml
module rec Person_t : sig
  type t = {name: string; pet: Cat.t}
end =
  Person_t

and Person : sig
  include sig
      type t
    end
    with type t := Person_t.t
end =
  Person

and Cat : sig
  type t = {name: string; isLazy: bool}
end =
  Cat
```

**Comment by xavierleroy** [comment]
It is expected behavior that a recursively-defined module `X` cannot be used inside a `module type of` that defines its own signature.  This is to prevent nonsense such as
```
module rec X : module type of X = X
```
where the signature of `X` cannot be determined.
