### ISSUE TITLE
incremental parallel build appears broken due to stdlib dependencies

### ISSUE THREAD

**Issue by gasche** [ocaml/ocaml#9595]
Since a couple months ago I see this kind of parallel-build failures when I switch to a different (but closely related) branch and run `world.opt -j5` again to be able to run the testsuite (note: maybe I should use `opt.opt -j5` instead?). This only affects incremental builds; cleaning and then rebuilding works fine (but takes a lot of time).

```
File "/home/gasche/Prog/ocaml/github-trunk/utils/identifiable.ml", line 1:
Error: The files /home/gasche/Prog/ocaml/github-trunk/boot/stdlib__map.cmi
       and /home/gasche/Prog/ocaml/github-trunk/utils/misc.cmi
       make inconsistent assumptions over interface Stdlib__map
```

I decided to track this down today, and here is my current understanding of the issue.
1. At the start of the build, I have build artifacts lying around from a previous branch. I thus have "old" standard build artifacts in `stdlib/*.cmi`, and consistently old `boot/stdlib.cm{i,a}` files.
2. The bytecode build runs with `-nostdlib -I boot` (in `CAMLC`), so it sees the old `boot/` files and things work fine. In particular, it builds the new standard library, with different .cmi from the old one.
3. Then the native build starts with `-nostdlib -I stdlib` (in `CAMLOPT`), and this cannot work: when we try to build say `utils/misc.ml`, `utils/misc.cmi` (built in the previous step) has the `.cmi` of the old standard library from `boot/stdlib.cmi`, but now we are trying to link with the new standard library in `stdlib/*.cmi` (rebuilt in the previous step), which is incompatible. Broken build.

I wonder if I understand this correctly, and I am a bit surprised because it looks like an obvious issue that should have broken everyone's incremental builds for a while. Am I missing something? Did this issue appear recently, we were doing things differently in the past?

Assuming the analysis is correct, here would be a change proposal:
1. Have an explicit `boot/stdlib.cmi` target in the Makefile, with correct dependencies on the `stdlib/*.cmi` files. (This should not change the clean-state build order as we already build the stdlib before any compiler sources in the `coldstart` phase.)
2. Have all compiler sources depend on `boot/stdlib.cmi`. If this file changes, then their own interfaces need to be rebuilt.

(Maybe we could apply the same treatment of explicitating dependencies to other `boot/stdlib*` files, I haven't thought about it as much.)

Does that sound reasonable?

cc @shindere @xavierleroy @dra27

**Comment by xavierleroy** [comment]
You didn't tell us which `make` target you used.

With `make`, i.e. `make world` or `make world.opt`, I was expecting stdlib/ to be rebuilt then .cmi files copied from stdlib/ to boot/, so this specific source of "inconsistent assumptions" should not show up.  However, `make world` and `make world.opt` were designed for a "start from a clean source tree" situation, so something else could make them misbehave if compiled artefacts already exist.

`make world` and `make world.opt` won't work if the bootstrap hypothesis was broken, e.g. if the .cmi format changed.  In this case, the incremental build to do is `make core`, rebuilding a bytecode compiler that will produce the new .cmi format, but the native-code compiler cannot be built, as it assumes the bootstrap hypothesis to hold.  In this case, the proper sequence to do is `make core` until no bugs remain, then `make bootstrap`, then `make opt.opt`.

**Comment by gasche** [comment]
I think my reasoning in the first post doesn't quite work, because `make coldstart` should be done before everything when running `world.opt`, so indeed the "stale stdlib" phenomenon should not occur. I will try to wait until I get a reproducible failure (and not just a common but transient occurrence) to investigate more; in the meantime, closing this unconvincing report.

**Comment by gasche** [comment]
I hit this problem again, I think. I am in a situation where I changed branches (going from trunk to a branch from a month ago), I run `make world.opt -j5`, and I see (after a coldstart that works correctly, in particular rebuilds the library):

```
./boot/ocamlrun ./boot/ocamlc -g -nostdlib -I boot -use-prims runtime/primitives -strict-sequence -principal -absname -w +a-4-9-40-41-42-44-45-48-66 -warn-error A -bin-annot -safe-string -strict-formats -I utils -I parsing -I typing -I bytecomp -I file_formats -I lambda -I middle_end -I middle_end/closure -I middle_end/flambda -I middle_end/flambda/base_types -I asmcomp -I asmcomp/debug -I driver -I toplevel -c utils/misc.mli
File "/home/gasche/Prog/ocaml/github-trunk/utils/misc.mli", line 1:
Error: The files /home/gasche/Prog/ocaml/github-trunk/boot/stdlib.cmi
       and /home/gasche/Prog/ocaml/github-trunk/utils/build_path_prefix_map.cmi
       make inconsistent assumptions over interface Stdlib
```

Indeed, `ocamlobjinfo` tells me that `build_path_prefix_map.cmi` uses a cmi digest for the Stdlib that is different from the one in boot/stdlib.cmi. `build_path_prefix_map.{ml,mli}` have no dependencies and they were not changed between the two git branches, so the `checkout` did not touch them in the filesystem.

I think that my analysis in the first message was wrong, but that there *is* a problem indeed with the absence of explicit dependency of the compiler modules on the standard library.

**Comment by gasche** [comment]
I think it would make sense to add a dependency from compiler files (for example the `.mli.cmi` rule of the root Makefile, which is not used for the stdlib) to `boot/stdlib.cmi`.

One negative impact would be that, because we `cp stdlib.cmi boot/` during the coldstart, all world(.opt) builds would always rebuild all compiler files. This is wasteful if the stdlib has not changed (the case that works correctly today).

A standard solution would be to emulate a checksum-based rather than timestamp-based build system: before copying stdlib.cmi to boot, if a file already exists there, do a diff and do not copy if the files are identical. In terms of rebuild this would be a "best of both world" strategy, but it means complexifying/polluting the build path with this logic, which partly relies on development-environment tools. One would have to be careful not to introduce more tool dependencies in the "clean build" case, and I'm not sure we want the complexity.
