### ISSUE TITLE
Report: building bytecode OCaml on AIX 7.2 with gcc

### ISSUE THREAD

**Issue by johnwhitington** [ocaml/ocaml#9616]
A customer reports that the following procedure is required to successfully build bytecode OCaml on AIX 7.2 64bit (The latest major version, from 2015). These instructions are for GCC, not xlc, as in `INSTALL.adoc`.

```
# Adjust Makefile.common to add build-aux
# INSTALL ?= /u01/downloads/ocaml-4.10/install-sh -c 
# to
# INSTALL ?= /u01/downloads/ocaml-4.10/build-aux/install-sh -c

# Adjust Makefile.config, replace -Werror with -w
# OC_CFLAGS=-O2 -fno-strict-aliasing -fwrapv -Wall -Werror -fno-common
# to
# OC_CFLAGS=-O2 -fno-strict-aliasing -fwrapv -Wall -w -fno-common

export CC='gcc -maix64 -pthread -fPIC -std=c99'
export AR='/usr/bin/ar -X64'
export NM='/usr/bin/nm -X64'
export SIZE='/usr/bin/size -X64'

./configure \
    --prefix=/u01/projects/ocaml \
    2>&1 | tee log.configure

gmake world
gmake install
```

I don't know if it is worth updating the document, or if any changes to OCaml would help to simplify this process, but I couldn't think of a better place to put this experience than the bugtracker. So here it is.

**Comment by Octachron** [comment]
The bugtracker does seems to be the right place for such report. I am wary of integrating documentation for a non-strictly supported OS from a single punctual source, I am thus closing this issue. Don't hesitate to reopen it if there is more information available.
