### ISSUE TITLE
trunk uses magic number from 4.10 - should use the one from 4.11

### ISSUE THREAD

**Issue by hhugo** [ocaml/ocaml#9627]

**Comment by dra27** [comment]
Actually the 4.11 magic numbers haven't yet been bumped - @Octachron, is that because they'll be bumped at the first beta release?

@hhugo - is it causing a problem at this stage?

**Comment by gasche** [comment]
I believe that the 4.11 magic numbers were bumped in 

  https://github.com/ocaml/ocaml/commit/7c8c9452f45a8bd5d7cad74451bd318e0e5255d7

**Comment by dra27** [comment]
Gah - sorry, I apparently had only fetched 4.11, not pulled it.

**Comment by dra27** [comment]
I'm happy to do the cherry-pick and bootstrap unless someone else is doing it already?

**Comment by Octachron** [comment]
I have bumped the number for 4.11 just before the first alpha indeed.

I have been wondering if we should systemically update the magic numbers before branching the new release branch.

cc @damiendoligez

**Comment by xavierleroy** [comment]
All this manual management of magic numbers is a pain.  Why don't we derive magic numbers from the version number?  This way there's only one thing to update by hand: the VERSION file.

**Comment by nojb** [comment]
> All this manual management of magic numbers is a pain. Why don't we derive magic numbers from the version number? This way there's only one thing to update by hand: the VERSION file.

See #9645 for a possible approach.

**Comment by hhugo** [comment]
Could we fix the magic number manually in trunk while #9645 is being discussed ?

**Comment by hhugo** [comment]
Ping again

**Comment by ghost** [comment]
Looking at previous discussions on caml-devel, my understanding is that the current policy is to bump all the magic numbers in trunk after each major release. So trunk should be using the 4.12 ones now (i.e `Caml1999?029`), and then be bumped as soon as 4.12 is released. @Octachron does that match your understanding? If yes, I propose that we update trunk to use `Caml1999?029` now.

Agreed that something automatic would be better, and that fixing trunk while an automated version is being discussed seems good.

**Comment by Octachron** [comment]
I have bumped the magic numbers in both 4.12 and trunk.
