### ISSUE TITLE
performance regression of ocamldebug in 4.10.0

### ISSUE THREAD

**Issue by vprevosto** [ocaml/ocaml#9637]
Running `frama-c.byte` (the bytecode version of [Frama-C](https://git.frama-c.com/pub/frama-c/)) in `ocamldebug` has become much slower in 4.10.0 with respect to 4.09.0. As `frama-c` relies heavily on dynamic loading of OCaml modules, I'd tend to suspect that this might be related to #8654, but I didn't bisect to confirm.

Basically doing `run` on `ocamldebug frama-c.byte` (i.e. letting `frama-c` just load its plug-ins and do nothing else) takes around 4/5 seconds in 4.09 and 4/5 minutes in 4.10 (with `set break_on_load off` before `run` in that case, of course), rendering the tool basically unusable.

**Comment by nojb** [comment]
Sounds like #9606, fix in #9635.

**Comment by vprevosto** [comment]
Indeed, #9635 restores `ocamldebug` performances. I didn't see them in the issues labelled `ocamldebug` which is why I reported this one in the first place. Thanks for the link.

**Comment by xavierleroy** [comment]
It feels so good to have submitted the fix 6 hours before receiving the bug report :-)

> Indeed, #9635 restores ocamldebug performances

Thanks for the confirmation!  Technically, we were O(n) in the past, then got to O(n^2) with #8654, and are down to O(n log n) with #9635 .
