### ISSUE TITLE
Possible regression following 9623

### ISSUE THREAD

**Issue by hhugo** [ocaml/ocaml#9640]
The following compiles with 4.10 and 4.11+alpha2 but fails with ocaml/4.11
@gasche, it's likely related to your work on https://github.com/ocaml/ocaml/pull/9623

```ocaml
module type Packet_type = sig
  type t
end
module type Unpacked_header = sig
  module Packet_type : Packet_type
  type t
  val f : t -> Packet_type.t -> unit
end
module type Header = sig
  module Packet_type : Packet_type
  module Unpacked : Unpacked_header with module Packet_type := Packet_type
end
module type S = sig
  module Packet_type : Packet_type
  module Header : Header with module Packet_type = Packet_type
end
module type Iobuf_packet = sig
  module Make (Header : Header) () :
    S
    with module Packet_type = Header.Packet_type
    with module Header.Unpacked = Header.Unpacked
end
```
```
File "a.ml", lines 19-21, characters 4-49:
19 | ....S
20 |     with module Packet_type = Header.Packet_type
21 |     with module Header.Unpacked = Header.Unpacked
Error: In this `with' constraint, the new definition of Header.Unpacked
       does not match its original definition in the constrained signature:
       Modules do not match:
         sig
           type t = Header/2.Unpacked.t
           val f : t -> Header/2.Packet_type.t -> unit
         end
       is not included in
         sig type t val f : t -> Packet_type/2.t -> unit end
       Values do not match:
         val f : t -> Header/2.Packet_type.t -> unit
       is not included in
         val f : t -> Packet_type/2.t -> unit
       File "a.ml", line 7, characters 2-36: Expected declaration
       File "a.ml", line 7, characters 2-36: Actual declaration
       File "a.ml", line 15, characters 2-62:
         Definition of module Header/1
       File "a.ml", line 18, characters 15-21:
         Definition of module Header/2
       File "a.ml", line 10, characters 2-34:
         Definition of module Packet_type/1
```

**Comment by gasche** [comment]
Thanks! I will try to look at this as quickly as possible (but I'm probably not working this afternoon). This is indeed a regression caused by #9623, but probably by the signature handling rather than the with-type part. (cc @lpw25 @garrigue, who could know better what is causing this).

**Comment by garrigue** [comment]
Indeed, the problem is with the fixed `sig_env` computed at the beginning.
If we revert to incrementally extend `initial_env` using `Env.add_item`, this code goes through.
Which is strange, as typability is supposed to be monotone wrt environment extension.
At least if we're not shadowing an identifier.
Some identifier conflict?

**Comment by garrigue** [comment]
Much simpler: we extend the environment with the outside signature, but we fail to do that for inner modules. And here we are constraining an inner module...

**Comment by gasche** [comment]
Thanks @garrigue, I will have a look at your PR.

In the meantime, I built a smaller repro case:

```ocaml
module type S = sig
  type t
  type u = t
end
module type Pack = sig
  module M : S
end
module type Weird = sig
  module M : S
  module P : Pack
    with type M.t = M.t
    with type M.u = M.u
end
```

**Comment by garrigue** [comment]
Indeed, the same thing happens with type constraints in submodules.

This said, my remark about overwriting identifiers in the environment is valid in general: while we may be doing it intentionally, this is potentially dangerous, as we assume monotonicity when working with the environment, and it could break it (but this is not what happens here).

**Comment by gasche** [comment]
I don't think we are overwriting identifiers in the environment. Before #9623, we were incrementally adding each signature item to the outer signature (so no overwrite), but Leo pointed out that this doesn't make sense when items are mutually recursive. After #9623, we add all signature items at once before traversing them, but then we don't add them incrementally, so there is no overwrite either. Your fix also preserves this property.

I think that the "non-monotonicity" that you observed in your earlier message comes from the fact that by going back to incremental addition, you restored (incremental) addition of sub-module items, which fixes the bug on those examples (but would fail in mutually-recursive scenarios).

**Comment by garrigue** [comment]
(As I wrote above) the problem here is not with overwriting, just that we had removed all addition of the items of submodules.
But while looking for the problem, I instrumented `Ident.add`, and observed that this kind of overwriting occurs in the compiler. Removing those occurrences would avoid considering this possibility.

**Comment by gasche** [comment]
@hhugo there is now a fix by @garrigue in both trunk and 4.11. We're looking forward for your next bug :-)

**Comment by gasche** [comment]
@hhugo gentle ping: this has been very helpful so far, so I'm curious to know if you have managed to typecheck your codebase with 4.11, or if there may be more typing-related issues left to be found (the earlier they are reported, the better).

**Comment by hhugo** [comment]
I should be able to give you an update later today

**Comment by hhugo** [comment]
my build is green, no more bug to report at the moment
