### ISSUE TITLE
tools/check-typo and Ubuntu 20.04

### ISSUE THREAD

**Issue by xavierleroy** [ocaml/ocaml#9643]
On a default installation of Ubuntu 20.04, `tools/check-typo` produces thousands of error lines like this:
```
awk: not an option: --re-interval
./.gitignore:1.1: [missing-header] bad copyright header (first line)
```
Reason: in Ubuntu, the default `awk` is `mawk`, which cannot execute `tools/check-typo`.  Before 20.04, the problem was detected and reported by `check-typo`:
https://github.com/ocaml/ocaml/blob/ae5eb6b4719b7fafa062dd983c5dbdbd295e70c1/tools/check-typo#L176-L182

However, Ubuntu 20.04 upgraded `mawk` to a new version that escapes the detection above...

Hours of enjoyment guaranteed with these awk scripts!

**Comment by gasche** [comment]
Could we fix the issue by explicitly calling `gawk` instead of `awk`? My Fedora machine at least exports both, and "missing gawk" errors are easy to diagnose and fix.
