### ISSUE TITLE
./build failed through ocamlfind package after updating OCaml compiler from 4.01.0 to 4.05.0 or new version 

### ISSUE THREAD

**Issue by ajaymas** [ocaml/ocaml#9658]
Hello, 
I am trying to build our project on the OCaml compiler 4.05.0 or 4.07.1 version. Basically the original version of our project called Uroboros (https://github.com/s3team/uroboros) was implemented and currently, it is working well with the Ocaml compiler version 4.01.0. However, after updating the compiler version to 4.05.0 or newer its failed to build and getting some strange error that is not part of our project module. But its from the Ocamlfind package. Could you please help me on how to fix this issue?  * Host system Ubuntu 18.04 LTS. 
Thanks in advance.   
            ----
Error as shown below:

@ubuntu:~/uroboros/src$ ./build 
+ ocamlfind -nodynlink -c -g -annot -bin-annot -thread -package deriving,deriving.syntax -syntax camlp4o -package batteries,parmap -I plugins -o type.cmx type.ml
Usage: ocamlfind query        [-help | other options] <package_name> ...
   or: ocamlfind ocamlc       [-help | other options] <file> ...
   or: ocamlfind ocamlcp      [-help | other options] <file> ...
   or: ocamlfind ocamlmklib   [-help | other options] <file> ...
   or: ocamlfind ocamlmktop   [-help | other options] <file> ...
   or: ocamlfind ocamlopt     [-help | other options] <file> ...
   or: ocamlfind ocamloptp    [-help | other options] <file> ...
   or: ocamlfind ocamldep     [-help | other options] <file> ...
   or: ocamlfind ocamlbrowser [-help | other options]
   or: ocamlfind ocamldoc     [-help | other options] <file> ...
   or: ocamlfind install      [-help | other options] <package_name> <file> ...
   or: ocamlfind remove       [-help | other options] <package_name>
   or: ocamlfind printppx     [-help | other options] <package_name> ...
   or: ocamlfind printconf    [-help] [variable]
   or: ocamlfind lint         [-help] <file>
   or: ocamlfind list
   or: ocamlfind pkg/cmd arg ...
Select toolchain with:
  ocamlfind -toolchain <t> <command>
Abbreviations:
  e.g. ocamlfind opt instead of ocamlfind ocamlopt
Command exited with code 2.
Compilation unsuccessful after building 3 targets (2 cached) in 00:00:00.
@ubuntu:~/uroboros/src$

**Comment by gasche** [comment]
This is not a compiler bug, but a bug in your build script (you are incorrectly passing an `-ocamlopt` option to ocamlbuild). Could you please open an issue on your software repository, and post the link here?

**Comment by gasche** [comment]
Note: the error in your build script was [reported on your issue tracker in 2017](https://github.com/s3team/uroboros/issues/3), with a proposed fix.

**Comment by ajaymas** [comment]
@gasche ./build issue is resolved the detailed explanation link is worked. currently, the Uroboros tool is working well on both 4.05.0 and 4.07.1 OCaml compiler. 
If anyone noticed this bug. The below changes is needed in /src/build   file
1. go to /src/build
2. open build file with any editor 
3. By default, the last line of the code is written as:
.... -ocamlopt "-inline 20" -ocamlopt -nodynlink
4. Change to 
 ... -ocamlopt "ocamlopt -inline 20 -nodynlink"
5. Then run ./build

Thanks!.
