### ISSUE TITLE
libbigarray.a seems to no longer be built or installed

### ISSUE THREAD

**Issue by johnwhitington** [ocaml/ocaml#9667]
Tested with trunk and 4.10 on OS X.

I have searched through the open and closed issues and pull requests and can't find any reference to the reasons for this. `libunix.a`, which is the most similar item, still exists.

The last reference to `libbigarray.a` in the Changes file is for 4.07.0.

**Comment by nojb** [comment]
`Bigarray` has been included inside the stdlib since 4.07 (with the exception of `map_file` which has been merged into `Unix`), so `libbigarray.a` is no longer needed or built.

**Comment by johnwhitington** [comment]
Thanks!
