### ISSUE TITLE
Bump ocaml-secondary-compiler to use ocaml 4.11.0 when released

### ISSUE THREAD

**Issue by mdedetrich** [ocaml/ocaml#9679]
Due to https://github.com/ocaml/ocaml/issues/9144 and https://github.com/ocaml/ocaml/commit/53327d777ddcacf829c77c0bd3569a8ade2c72b8 , the opam `ocaml-secondary-compiler` should be bumped to depend on version ocaml 4.11.0 when that ocaml version is released. opam should also be updated to use the newly updated ocaml-secondary-compiler version.

If this is not done than machines with GCC 10.1.0 or higher cannot compile opam properly.

**Comment by Octachron** [comment]
The opam package `ocaml-secondary-compiler` is not managed by the compiler team. There is already on the opam repository bugtracker for GCC 10-related compilation woes: ocaml/opam-repository#16583 .

**Comment by mdedetrich** [comment]
The error I am getting is

```
    /usr/bin/ld: backtrace_bpic.o:/home/mdedetrich/.esy/3/b/opam__s__ocaml_secondary_compiler-opam__c__4.08.1-1-ed533906/runtime/backtrace.c:31: multiple definition of `caml_debug_info'; backtrace_byt_bpic.o:/home/mdedetrich/.esy/3/b/opam__s__ocaml_secondary_compiler-opam__c__4.08.1-1-ed533906/runtime/backtrace_byt.c:47: first defined here
    collect2: error: ld returned 1 exit status
    make[1]: *** [Makefile:310: libcamlrun_shared.so] Error 1
    make[1]: *** Waiting for unfinished jobs....
    make[1]: Leaving directory '/home/mdedetrich/.esy/3/b/opam__s__ocaml_secondary_compiler-opam__c__4.08.1-1-ed533906/runtime'
    make: *** [Makefile:323: coldstart] Error 2
    error: command failed: 'env' '-u' 'OCAMLLIB' 'bash' './esy-build' (exited with 2)
    esy-build-package: exiting with errors above...
    
  building @opam/ocaml-secondary-compiler@opam:4.08.1-1
esy: exiting due to errors above
```

@Octachron Wanted me to specify some more info so I did. I suspect this is the same issue though, `ocaml-secondary-compiler` is using a non patched version of Ocaml that doesn't work with GCC 10
