### ISSUE TITLE
Add Filename.with_extension

### ISSUE THREAD

**Issue by jeffa5** [ocaml/ocaml#9718]
The `Filename` module currently has three extension related functions:
- `extension` to get the current extension
- `remove_extension` to remove an extension
- `chop_extension` to remove an extension

I feel like a way to add an extension is missing and was thinking of the following:
```ocaml
val with_extension : string -> string -> string
(** [with_extension f e] is [f] with the extension [e]. It behaves equivalently to [(remove_extension f) ^ "." ^ e]
```

**Comment by gasche** [comment]
Apologies for not giving feedback earlier...

I'm not convinced by the proposed definition `with_extension p ext = (remove_extension p) ^ ext`, when we consider filenames that have no extensions or several extensions. If I try to put myself into the shoes of someone seeing `Filename.with_extension "foo.ml.zip" ".txt"`, what do I expect as output, `foo.txt`, `foo.ml.txt` or `foo.ml.zip.txt`?

I think that `replace_extension` would be a clearer name, as it makes it clearer (to me) that we are removing one extension as we are adding a new one.
