### ISSUE TITLE
inconsistent html in module signature

### ISSUE THREAD

**Issue by sanette** [ocaml/ocaml#9720]
For instance in:

https://ocaml.org/releases/4.10/htmlman/compilerlibref/Arg_helper.Make.html

the use of `<pre>` tag is not very consistent. 
* it should not close after the `functor` line
* for the first and last lines the `sig_block` class is inside the `<pre>` tag, while it is the opposite for the `module` lines. It would be better to have a consistent stucture.

The reason I raises this is that it makes it very difficult to style it correctly with CSS; see for instance my (bad) attempt in
https://sanette.github.io/ocaml-api/compilerlibref/4.10/Arg_helper.Make.html

**Comment by dra27** [comment]
Have you tried doing this against the output of odoc instead? There's a lot of effort going into getting odoc to replace ocamldoc for generating the compiler's documentation, with a view ultimately to removing ocamldoc from the OCaml distribution, so you're more likely to get changes there than ocamldoc (just to be clear: that's my opinion, rather than a formal developer team statement!)

**Comment by sanette** [comment]
I haven't tried odoc for this (although I use odoc for my personal projects).
Concerning the OCaml API, I'd be happy to follow whatever is chosen, be it odoc or sphinx,
but I have no idea about the delay for this, so for the moment prefer to stick to what is currently used.

**Comment by Octachron** [comment]
To give some more context, I am expecting to have a first version of a latex backend for odoc soon (this week, the next one?). And once this backend is ready, I plan to upstream my Makefile target for building the standard library API with odoc and spend the required time to get the manual to build with odoc. Consequently, it is unlikely that I will spend some time to fix this issue any time soon.

**Comment by sanette** [comment]
OK great. Then I'm waiting ;)

**Comment by Octachron** [comment]
There is  now an odoc version of the manual (that still needs some stabilization), and I am not planning to improve the htm generated for ocamldoc.

I am thus marking this issue as a `wont_fix`.
