### ISSUE TITLE
Injectivity & recursive modules

### ISSUE THREAD

**Issue by yallop** [ocaml/ocaml#9721]
First, some standard bits and pieces for equality & injectivity:
```ocaml
type (_,_) eql = Refl : ('a, 'a) eql

module Uninj(X: sig type !'a t end) :
sig val uninj : ('a X.t, 'b X.t) eql -> ('a, 'b) eql end =
struct let uninj : type a b. (a X.t, b X.t) eql -> (a, b) eql = fun Refl -> Refl end

let coerce : type a b. (a, b) eql -> a -> b = fun Refl x -> x
```

Now the questionable part, defining two "injective" type definitions in a pair of mutually-recursive modules.  These definitions are correctly rejected if given as a pair of mutually-recursive types, but wrongly accepted when defined as follows:

```ocaml
module rec R : sig type !'a t = [ `A of 'a S.t] end = R
       and S : sig type !'a t = 'a R.t end = S
```

The parameter of `R.t` is never used, so we can build an equality witness for any instantiation:

```ocaml
let x_eq_y : (int R.t, string R.t) eql = Refl
```

and then use injectivity to obtain a proof that the parameters are equal:

```ocaml
let boom = let module U = Uninj(R) in print_endline (coerce (U.uninj x_eq_y) 0)
```
leading to:
```
Segmentation fault
```

**Comment by garrigue** [comment]
Oops. Ill-founded injectivity declaration.
Well spotted.
