### ISSUE TITLE
Missing Information in OCaml Compiler frontend docs

### ISSUE THREAD

**Issue by JamesShaker** [ocaml/ocaml#9731]
On the online [docs for the compiler frontend](http://caml.inria.fr/pub/docs/manual-ocaml/parsing.html) it says:
> For interactive use of the compiler-libs library, start ocaml and type
> `#load "compiler-libs/ocamlcommon.cma";;`

This should be ammended to:

> For interactive use of the compiler-libs library, start ocaml and type
> `#load "compiler-libs/ocamlcommon.cma";;`
> `open Compile_common;;`

This second step does not appear to be documented anywhere, is only clear from manual inspection of a compiled binary, and is required to access the modules documented on that page.

**Comment by gasche** [comment]
What version of OCaml are you using?

**Comment by JamesShaker** [comment]
My version is `4.10.0`. Not sure why but the solution I posted no longer seems to work on my machine. Apologies for that :/ Either way the currently listed solution appears to be insufficient. I now have to use `ocaml -I +compiler-libs ocamlcommon.cma` as a command instead of just `ocaml`

**Comment by nojb** [comment]
Indeed, for interactive use one must add `-I +compiler-libs` in the command line invoking `ocaml` or, alternative, use `#directory "+compiler-libs"` once started.

Would you like to propose a PR amending the manual in this sense?
