### ISSUE TITLE
Bad error message about "the type variable int"

### ISSUE THREAD

**Issue by stedolan** [ocaml/ocaml#9739]
This program:
```ocaml
let rec foo () = [42]

and bar () =
  let x = foo () in
  x |> List.fold_left max 0 x
```
fails to compile with this error:
```
File "bad.ml", line 5, characters 7-29:
5 |   x |> List.fold_left max 0 x
           ^^^^^^^^^^^^^^^^^^^^^^
Error: This expression has type int but an expression was expected of type
         int list -> 'a
       The type variable int occurs inside int list -> 'a
```
The error message is appropriate and the location is accurate, but the last line is nonsense: `int` is not a type variable.

The weird last line goes away if the `and` is changed to a `let`.

**Comment by Octachron** [comment]
It is a problem with the error trace being better at tracking the origin of a type error: we remember that the error was raised when checking for a recursive occurrence, but I didn't think to check in the recursive occurrence error message that the printed type was still a type variable.
