### ISSUE TITLE
Scanning N hex digits - is this a bug or just potentially surprising?

### ISSUE THREAD

**Issue by dc-mak** [ocaml/ocaml#9740]
From https://caml.inria.fr/pub/docs/manual-ocaml/libref/Scanf.html

> The field width is composed of an optional integer literal indicating the maximal width of the token to read. For instance, %6d reads an integer, having at most 6 decimal digits; %4f reads a float with at most 4 characters; and %8[\000-\255] returns the next 8 characters (or all the characters still available, if fewer than 8 characters are available in the input).

the manual is fairly clear on the intended behaviour. However, @CuiCui66 and I were caught out by the `(*   7, ??*)` example recently.
```ocaml
[ (* 122, OK *) Scanf.sscanf "7A" "%2x" (fun x -> x)
; (* 122, OK *) Scanf.sscanf "7A," "%2x" (fun x -> x)
; (* 122, OK *) Scanf.sscanf "7A" "%1x%1x" (fun x y -> (x lsl 4) lor y)
; (* 122, OK *) Scanf.sscanf "7A," "%1x%1x" (fun x y -> (x lsl 4) lor y)
; (*   7, ?? *) Scanf.sscanf "7=" "%2x" (fun x -> x)
; (*  -1, OK *) (try Scanf.sscanf "7=" "%1x%1x" (fun x y -> (x lsl 4) lor y)
                with Scanf.Scan_failure _ -> -1)
; (*  -1, OK *) (try Scanf.sscanf "=" "%1x" (fun x -> x)
                with Scanf.Scan_failure _ -> -1)
]
```

We wanted to get your thoughts; I suspect updating the manual with such examples may be the best option.

**Comment by xavierleroy** [comment]
Sorry for the late reply.  The behavior you observe is consistent with the meaning of field widths (`2` in `%2x`), Quoting
[the documentation](https://ocaml.org/releases/4.11/htmlman/libref/Scanf.html):
> The field width is composed of an optional integer literal indicating the maximal width of the token to read. For instance, %6d reads an integer, having at most 6 decimal digits; %4f reads a float with at most 4 characters; and %8[\000-\255] returns the next 8 characters (or all the characters still available, if fewer than 8 characters are available in the input).

So, `%2x` means "read an hexadecimal number of at most two digits", not "having exactly two digits".

As unintuitive as it can be sometimes, this behavior is also the one of the `scanf` functions in the C standard library, on which OCaml's `Scanf` module is modeled.
