### ISSUE TITLE
Typing without -principal is broken in 4.11 and trunk

### ISSUE THREAD

**Issue by trefis** [ocaml/ocaml#9759]
Noticed while adding support for 4.11 in merlin, reproducible with:
```
$ ./runtime/ocamlrun ./ocamlc -nostdlib -I stdlib -I utils -I parsing -I typing -principal -c ./typing/typedtree.ml
$ ./runtime/ocamlrun ./ocamlc -nostdlib -I stdlib -I utils -I parsing -I typing -c ./typing/typedtree.ml
File "./typing/typedtree.ml", lines 793-808, characters 17-22:
793 | .................match p.pat_desc with
794 |   | Tpat_var (id, s) -> (* note the ``Not_found'' case *)
795 |       {p with pat_desc =
796 |        try Tpat_var (alpha_var env id, s) with
797 |        | Not_found -> Tpat_any}
...
805 |   | d ->
806 |      let pat_desc =
807 |        shallow_map_pattern_desc { f = fun p -> alpha_pat env p } d in
808 |      {p with pat_desc}
Error: This expression has type k pattern_desc pattern_data
       but an expression was expected of type 'a 
       This instance of k is ambiguous:
       it would escape the scope of its equation
```

The code in question:
```ocaml
let rec alpha_pat
  : type k . _ -> k general_pattern -> k general_pattern
  = fun env p -> match p.pat_desc with
  | Tpat_var (id, s) -> (* note the ``Not_found'' case *)
      {p with pat_desc =
       try Tpat_var (alpha_var env id, s) with
       | Not_found -> Tpat_any}
  | Tpat_alias (p1, id, s) ->
      let new_p =  alpha_pat env p1 in
      begin try
        {p with pat_desc = Tpat_alias (new_p, alpha_var env id, s)}
      with
      | Not_found -> new_p
      end
  | d ->
     let pat_desc =
       shallow_map_pattern_desc { f = fun p -> alpha_pat env p } d in
     {p with pat_desc}
```
Given the error message, it looks like the type annotation on the function is ignored.
This doesn't appear to be due to #1132 (I confirm that the bug also exists before that PR).

It could also be that this is just an issue with the printing of the error, that the expected type is in fact not ignored but that the level handling is incorrect in some place(s).

Note: I'm going on vacation tonight, so I won't be able to look at this before the end of next week. Anyone else should feel free to have a look.

**Comment by gasche** [comment]
Ah, it's good that we have more GADT annotations in the compiler itself, so that we notice this things more quickly :-D

**Comment by trefis** [comment]
This can be reduced to:
```
type 'a general = { indir: 'a desc; unit: unit }
and 'a desc =
  | C : unit general -> unit desc

let rec foo : type k . k general -> k general = fun g ->
  match g.indir with
  | C g' ->
      let new_g' = foo g' in
      if true then
        {g with indir = C new_g'}
      else
          new_g'
  | indir ->
     {g with indir}
```
which is also rejected on 4.10 without `-principal` (but accepted if the flag is given).

If the last two lines are replaced by:
```ocaml
  | _ ->
    { g with unit = () }
```
then the error becomes:
```
File "./repro.ml", lines 8-12, characters 6-16:
 8 | ......let new_g' = foo g' in
 9 |       if true then
10 |         {g with indir = C new_g'}
11 |       else
12 |           new_g'
Error: This expression has type k general
       but an expression was expected of type k general 
       This instance of k is ambiguous:
       it would escape the scope of its equation
```

Adding the type annotation `: k general` on either of the if-branches, or on the binding of `new_g'` makes it disappear.
The same will also fix the previous version of the code.

It does look like the expected type might not be propagated correctly in non-principal mode.

**Comment by trefis** [comment]
Note: this can be traced as far back as 4.02 (I don't have an older version installed) with the same behavior (accepted with `-principal`, rejected without).
So I guess there's no need to hold off the release of 4.11 because of this.

**Comment by garrigue** [comment]
> It does look like the expected type might not be propagated correctly in non-principal mode.

Thanks for the analysis. It probably means that we should not only call `correct_levels` on `ty_arg` but also on `ty_res` to make the ambiguity check happy. I'm going to look into this.

**Comment by garrigue** [comment]
Actually, we already copy it, so this seems more subtle.
