### ISSUE TITLE
Module overriding standard OCaml library?

### ISSUE THREAD

**Issue by akshajgaur** [ocaml/ocaml#9762]
This is probably a very silly issue, but I have benn working with OCaml for the past couple of months and everything was working fine. However, I install "Core" and all of its dependencies yesterday, and it seems that it is overriding the standard List module, so I can't compile even the simplest programs such as the following. Would uninstalling and re-installing ocaml make me re-install all of the opam packages that I already have?

```
let test a =
   List.length [a;a;a]
```
Any suggestions as to how to correct this?

**Comment by nojb** [comment]
This bugtracker is dedicated to compiler development. For general OCaml usage questions, I would recommend you ask your question https://discuss.ocaml.org/, where you will probably get a better answer sooner.

Having said that, as a general rule, `core` shouldn't affect your code unless you `open` it, and even if you do, the quoted code should still work. Showing the error message you would help in tracking down the issue.
