### ISSUE TITLE
Undetected match failure in variant with empty cases

### ISSUE THREAD

**Issue by craigfe** [ocaml/ocaml#9768]
In the following example, `f` is defined to return `1` on a list of length 1 (and to raise a `Match_failure` otherwise), with list elements taken from an empty type:

```ocaml
type v = |

let f ([ _ ] : v list) = 1    (* No exhaustivity warning printed *)
```

This example sneaks past the exhaustivity checker. More interestingly, it returns `1` even when passed an empty list:

```ocaml
let () = print_int (f [])   (* Prints 1 *)
```

I consider this to be a bug, since `f` should be undefined on the empty list.

As expected, adding a refutation case to `f` correctly detects the non-exhaustivity of the definition:

```ocaml
let f' : v list -> int = function
  | [ _ ] -> 1
  | _ -> .

(* 3 |   | _ -> .
           ^
   Error: This match case could not be refuted.
          Here is an example of a value that would reach it: [] *)
```

**Comment by Octachron** [comment]
Fixed in 4.11 by #9318 .
