### ISSUE TITLE
Function sleepf is missing in UnixLabels

### ISSUE THREAD

**Issue by stefan-kral** [ocaml/ocaml#9770]
The "OCaml 4.10 User's Manual" says `sleepf` has been present in module `Unix` since `4.03.0`.
>val sleepf : float -> unit

It is absent from module `UnixLabels`. This is wrong. `UnixLabels` should parallel `Unix`.

**Comment by dra27** [comment]
Actually it's worse than that: we're missing `is_inet6_addr`, `process_full_pid`, `process_pid`, `process_out_pid`, `process_in_pid`, `fsync` and `unsafe_environment`. I've adapted the lib-stdlabels test and will do a PR shortly.

**Comment by nojb** [comment]
xref #9745

**Comment by johnwhitington** [comment]
I am preparing an update to #9745 to unify Unix and UnixLabels.

Lots of missing documentation (especially Windows comments).

I have to polish it up, but it should be done soon.

**Comment by dra27** [comment]
Ah - have you done a test already or shall I just push the simple test I’ve already done to your branch?

**Comment by johnwhitington** [comment]
I have made no changes to any tests, either for this, or for the earlier work. So feel free to push it.

**Comment by dra27** [comment]
Pushed https://github.com/ocaml/ocaml/pull/9745/commits/78d9f34f8cda0b3c7422d8e4559153b098786b7a to #9745

**Comment by Octachron** [comment]
Fixed by #9745 .
