### ISSUE TITLE
Bad interaction between local identifier scopes and moregen

### ISSUE THREAD

**Issue by lpw25** [ocaml/ocaml#9771]
If you use the following code for both `foo.ml` and `foo.mli`
```ocaml
module type S2 = sig
  type t
  module Range : sig
    type +'a range
      constraint 'a = [< `c of t ]

    val aa : 'a range -> 'a
  end
end
```
then you will get a gratuitous error message:
```
File "foo.ml", line 1:
Error: The implementation foo.ml does not match the interface foo.cmi:
       ...
       At position module type S2 = sig module Range : <here> end
       Values do not match:
         val aa : ([< `c of t ] as 'a) range -> 'a
       is not included in
         val aa : ([< `c of t ] as 'a) range -> 'a
       File "foo.ml", line 7, characters 4-27: Expected declaration
       File "foo.mli", line 7, characters 4-27: Actual declaration
```

This is caused by an interaction of the scoping of local identifiers and the `generic_level - 1` stuff that goes on in `Ctype.moregen`.

One reasonable fix would be to replace the use of `Env.add_signature` in `Includemod.sigantures` with something more like `Env.enter_signature`. Obviously you would not do the substitution eagerly like `enter_signature` does because that would be very expensive, you would delay the substitution just like is already done for the other side in the `Includemod` functions.

To my mind this the correct way to deal with identifiers: bound identifiers should have no scope and identifiers in the environment should always have a scope. That means that when you traverse under a binder you should substitute the bound identifier for a fresh one with an appropriate scope.

Other possible fixes include:

- Changing how moregen represents rigid type variables
- Changing the overly conservative (I think?) level handling in the `Reither` case of `unify_row`

but I'm less confident in how to make those fixes.

**Comment by garrigue** [comment]
Actually, a trivial solution is to replace `highest_scope` by `highest_scope - 1` in `Ident.scope`.
It could be even less. It should just be higher than any normal level.

I agree with you that this use of a fixed local scope when working inside signatures is counter-intuitive. I would like to understand why it works in general.

**Comment by trefis** [comment]
> Actually, a trivial solution is to replace highest_scope by highest_scope - 1 in Ident.scope.
It could be even less. It should just be higher than any normal level.

Please, let's not.

**Comment by garrigue** [comment]
That was just a suggestion in case you expected the current code to work.
Otherwise, I suppose you need to apply a substitution that replaces the local scopes by the correct global ones.
