### ISSUE TITLE
Polymorphic Variants losing typing information

### ISSUE THREAD

**Issue by Cjen1** [ocaml/ocaml#9785]
(Initial discussion on: [discuss.ocaml.org](https://discuss.ocaml.org/t/how-to-represent-a-function-which-can-take-the-union-of-two-sets-of-polymorphic-variants/6119))

The main issue is:
```
type a = {v:int}
type b = {v:bool}

type foo = [ `EventA of a | `EventB of b ]

let foo : [<foo] -> string = function
| `EventA t -> Int.to_string t.v
| `EventB t -> Bool.to_string t.v
;;
Line 8, characters 29-32:
Error: This expression has type bool but an expression was expected of type int
```

however: 
```
type a = {v:int}
type b = {v:bool}

type foo = [ `EventA of a | `EventB of b ]

let foo : foo -> string = function
| `EventA t -> Int.to_string t.v
| `EventB t -> Bool.to_string t.v
;;
type a = { v : int; }
type b = { v : bool; }
type foo = [ `EventA of a | `EventB of b ]
val foo : foo -> string = <fun>
```

There appears to be two issues in this case. 

1. The type information is being lost inside the matching. 
2. When `t` is getting typed it is taking the 'most recent' type which matches the accessors, rather than trying to match on the type of the accessors (though I can imagine that solving this part may be very expensive in compilation time or developement time).

The second issue I've run into several times but can relatively easily be fixed by manual typing of functions.

@levi_roth (can't find their github account) also had a good example of this occurring:
```
# module M = struct type t = M end;;
module M : sig type t = M end
# type t = [ `M of M.t ];;
type t = [ `M of M.t ]
# let f : [< t ] -> unit = function | `M M -> ()
;;
Line 1, characters 39-40:
Error: Unbound constructor M
```

**Comment by garrigue** [comment]
This is the expected behavior:
1. This is intentional. "Vanishing" polymorphic variant constructors interact with the exhaustiveness check in a non-principal way, and for this reason typing information concerning these constructors is not propagated to patterns.
2. This is a consequence of 1: in the absence of type information, selection of variant and record types chooses the newest one in scope with the given constructor or a sufficient set of labels.

**Comment by Cjen1** [comment]
I've been playing with this to figure out how to best achieve what I want (good correspondence in the type of the function while avoiding this issue). What appears to work is to manually apply the type information within the matches.

Using collections of the variants makes this quite a nice approach:
```
type a = {v:int}
type b = {v:bool}

type foo = [ `EventA of a | `EventB of b ]

let foo : [<foo] -> string = function
| (`EventA t : foo) -> Int.to_string t.v
| (`EventB t : foo) -> Bool.to_string t.v
```

@garrigue given that this is an intentional (and I can see why it would be) I'll close this issue and hope that at some point in the future some academic works out an efficient way do this kind of thing. :smile:
