### ISSUE TITLE
Trivial fix for compiling OCaml with Link-Time Optimization (LTO)

### ISSUE THREAD

**Issue by rwmjones** [ocaml/ocaml#9825]
Fedora and OpenSUSE package build systems now compile everything with Link-Time Optimization enabled by default.  This allows optimizations to cross compilation unit boundaries which gives more opportunities for inlining in particular.  Unfortunately OCaml didn't build:
```
    major_gc.c:66:14: warning: type of 'caml_fl_merge' does not match original declaration [-Wlto-type-mismatch]
       66 | extern char *caml_fl_merge;  /* Defined in freelist.c. */
          |              ^
    freelist.c:47:7: note: 'caml_fl_merge' was previously declared here
       47 | value caml_fl_merge = Val_NULL;  /* Current insertion pointer.  Managed
          |       ^
    freelist.c:47:7: note: code may be misoptimized unless '-fno-strict-aliasing' is used
```

Fedora is now carrying this trivial fix which you may want to consider:
https://pagure.io/fedora-ocaml/c/7364f5081851fe306802883d9a8069da559d4973?branch=fedora-33-4.11.0-dev2

**Comment by rwmjones** [comment]
As a patch file: https://pagure.io/fedora-ocaml/c/7364f5081851fe306802883d9a8069da559d4973.patch

**Comment by avsm** [comment]
Oh no, is this another few hundred patches i need to carry for older compilers in opam-repository again, thanks to the changed default? I'm just recovering from the -fno-common changes in Fedora 32 ;-)

Having this fix included in 4.10.1 would be very useful if not too late, @Octachron, assuming that Fedora 33 will have this LTO change by default.

**Comment by Octachron** [comment]
@rwmjones , is link-time optimisation enabled by default at the package or compiler level? In other words, does this mean that every version of OCaml will need this patch (and friends) to build in Fedora or OpenSuse, or is the optimization just a global package policy?

**Comment by rwmjones** [comment]
This only affects Fedora and OpenSUSE, and also it only happens if you compile using Fedora's suggested flags (`rpm --eval '%{optflags}'` and `rpm --eval '%{__global_ldflags}'`).  If you use GCC in Fedora (or OpenSUSE) to compile something from source and you don't explicitly add those flags then nothing at all changes for you.  IOW this should not affect opam unless opam is opting in to those flags (which could be a good idea for other reasons, especially hardening, but is not mandatory).

Having said that, every OCaml package built through the Fedora Koji build system (or OpenSUSE OBS) *does* have LTO enabled by default and you have to opt out, so the C parts of existing OCaml packages and the OCaml compiler will be getting a lot of free testing + extra optimization, and we expect it'll break stuff and you'll see bug reports similar to this one.

Hope that clears things up.

**Comment by Octachron** [comment]
Thanks for the precision.
With this context, I think this is more of a 4.12 fix.

**Comment by avsm** [comment]
Thanks, that's very helpful indeed -- not a candidate for backporting indeed then.  However, this fits neatly into some opam 2.2 features we are speccing out at the moment to add "package parameter" support in, which should make it very easy to add hardening flags on certain operating systems (cc @dra27 @rjbou).

**Comment by xavierleroy** [comment]
See #9830.  There was another, less serious instance of the same problem involving the `caml_spacetime_my_profinfo` function, bytecode version.
