### ISSUE TITLE
Function is_normal is dearly missing in module Float

### ISSUE THREAD

**Issue by stefan-kral** [ocaml/ocaml#9836]
The OCaml module `Float` offers the function <code>is_<b>finite</b></code>:
> val is_finite : float -> bool<br>is_finite x is true iff x is finite i.e., not infinite and not Float.nan.<br>Since 4.08.0</pre>

Alas, `is_finite` also includes subnormal values :-(

Right now, I'm using the following workaround (in a tight inner loop):
<pre>
let is_normal_or_zero f =
  match Float.classify_float f with
  | FP_normal | FP_zero                 -> true
  | <b>FP_subnormal</b> | FP_infinite | FP_nan -> false
</pre>

Please consider adding a fast <code>is_<b>normal_or_zero</b></code> function to module `Float`. Thank you.

--

Edit: to better reflect the common FP-classification nomenclature.

**Comment by pmetzger** [comment]
This seems reasonable. isnormal() is part of the C libraries after all. See: https://pubs.opengroup.org/onlinepubs/009695399/basedefs/math.h.html

**Comment by nojb** [comment]
> This seems reasonable. isnormal() is part of the C libraries after all. See: https://pubs.opengroup.org/onlinepubs/009695399/basedefs/math.h.html

Note that the function `isnormal` from `libc` does not match what is requested in this issue, as it returns `0` if the argument is (positive or negative) zero (it corresponds to the `FP_NORMAL` classifier, see https://www.gnu.org/software/libc/manual/html_node/Floating-Point-Classes.html).

**Comment by xavierleroy** [comment]
As mentioned in #10703, it looks like
```
Float.(match classify_float f with FP_normal | FP_zero -> true | _ -> false)
```
does the job and is reasonably fast.  Unlike other `is*` FP functions, `isnormal` doesn't appear to have an efficient implementation.  Also, ISO C `isnormal` returns false on zeros while this feature wish wants something that returns true on zeros.  All in all, I don't think this is a useful extension to the standard library, and suggest that users build the predicates they want on top of `Float.classify_float`.
