### ISSUE TITLE
Tagging integers on Intel64 processors

### ISSUE THREAD

**Issue by stefan-kral** [ocaml/ocaml#9850]
For x86-64, `ocamlopt` emits code like `leaq 1(%rax,%rax),%rax` when tagging integers.

However, for all Intel Core processors since 2011, `leaq 1(,%rax,2),%rax` would be better.

Comparison:
* PRO: shorter latency (1 cycle vs. 3 cycles)
* PRO: higher throughput (2 per cycle vs. 1 per cycle)
* CON: larger encoding (8 bytes vs. 5 bytes)

Also, note that the proposed code:
* works on *all* AMD64/Intel64 processors
* is *not* an de-optimization for older Intel64 / current AMD64 processors
(slightly higher stress on the instruction decoders / I-caches)

So please consider adapting the Intel64 code generator in `ocamlopt`.

Thank you!

PS. For details on the timing, see https://www.agner.org/optimize/

**Comment by lpw25** [comment]
Presumably would be addressed by #8531

**Comment by stefan-kral** [comment]
> Presumably would be addressed by #8531

Yes, but what I am aiming at is *simple*. So simple, `sed` could do it:)

**Comment by gasche** [comment]
#8531 ended up closed, so maybe the smaller change proposed here would still be of interest? (But then @xavierleroy criticism of code-size increase still stands.) cc @gretay-js @xavierleroy .

(I suppose it may be useful to run macro-benchmarks to evaluate the impact of such a change?)

**Comment by gasche** [comment]
Also looks related to the discussion in https://github.com/ocaml/ocaml/issues/6125#issuecomment-472988968.

**Comment by xavierleroy** [comment]
I'd be happy to see performance measurements on realistic programs (not micro-benchmarks), e.g. on the Sandmark suite, or bigger.

In the absence of convincing performance measurements, I stick with the more compact code.  Fitting more code in the  instruction cache is almost always a win with big, realistic applications.
