### ISSUE TITLE
Windows: bad interaction between eol translation and channel_length/seek

### ISSUE THREAD

**Issue by alainfrisch** [ocaml/ocaml#9868]
Under Windows, files opened in text mode are subject to an implicit end-of-line translation (CRLF -> LF) performed by Windows itself.  This mode interacts badly with the implementation of OCaml channels (explanations for in_channel, but the same applies for out_channels):

  - Upon reading, the internal channel->offset field is bumped by the number of character read, after the translation.  As a consequence, `Stdlib.pos_in` returns a number of bytes which does not correspond to real offsets in the file (let's call that a `virtual` offset).

  - `Stdlib.seek_in` generally expects a "real" offset in the file, but (1) it doesn't perform an lseek if the target offset is already in the loaded buffer -- but it does this check based on the offset field, which use "virtual" offsets; (2) after calling lseek, it sets the `channel->offset` field to the requested offset, which is now a real offset, not a virtual one.  So the result of `pos_in` is not always a "virtual" offset either.

  - Worse, `Stdlib.in_channel_length` restores the current reading offset calling `lseek` on `channel->offset`, which is usually wrong.  This means that calling that function can change the actual reading position.

The last point is demonstrated by the following program:
````ocaml
let () =
  let oc = open_out "foo.txt" in
  for i = 1 to 3 do
    Printf.fprintf oc "%s\n%!" (String.make 50000 'x');
  done;
  close_out oc;

  let ic = open_in "foo.txt" in
  for i = 1 to 3 do
    let s = input_line ic in
    Printf.printf "%i %i\n%!" (in_channel_length ic) (String.length s)
  done;
  close_in ic
````

which prints, under Windows:
````
150006 50000
150006 50001
150006 50001
````

The programs reads lines of length 50001, although the file contains only line of length 50000.  Adapting the code to create 10 lines of length 15000, one gets:
````
150020 15000
150020 15000
150020 15000
150020 15000
150020 15004
150020 15000
150020 15000
150020 15000
150020 15004
150020 15000
````

One way to fix those problems would be to emulate the eol translation on our side, in order to get an offset field which corresponds to actual offsets in the files.  `pos_in` would then naturally returns a real offset, which could safely be passed to `seek_in`.

**Comment by alainfrisch** [comment]
Note: the last problem (in_channel_length moving the cursor) could be fixed easily by explicitly requesting the current offset (with an extra call to lseek) instead of trusting the internal offset field.  Still, pos_in would remain unreliable (couldn't be compared with in_channel_length, passed to seek_in, etc).

**Comment by xavierleroy** [comment]
Seeking makes limited sense on files opened in text mode.  But, yes, it would be better if we could reliably seek to a position returned by `pos_in`/`pos_out`.

> One way to fix those problems would be to emulate the eol translation on our side

That's a bit of a pain, and could misbehave with file descriptors pre-opened in text mode such as stdin, stdout, stderr.   You'd need to set them to binary mode so that the translation can be done on our side.  But then `fprintf(stderr, ...)` in the runtime system or in C code linked with OCaml will print in binary mode, which is not what you want.

**Comment by xavierleroy** [comment]
Perhaps the most radical solution to this problem is to reimplement OCaml's buffered I/O using `<stdio.h>`, so that the buffering is handled by the C standard library.  The current "let's do our own buffering" implementation is of historical nature and may not have any raison d'être left.

**Comment by alainfrisch** [comment]
I guess not supporting pos_in/seek_in/in_channel_length on stdin would be fine :-)  So perhaps one could support two modes.

Since there is no simple and full solution, I would suggest the following steps:

   - Make sure that in_channel_length doesn't move the cursor.
   - Document that seek_in should be avoided under Windows on text files (except perhaps to rewind to offset 0) and that pos_in might be unreliable (I don't think one want to document that it returns "virtual" offset, since this might change).

Do you agree?

**Comment by shindere** [comment]
Xavier Leroy (2020/08/31 05:33 -0700):
> Perhaps the most radical solution to this problem is to reimplement
> OCaml's buffered I/O using `<stdio.h>`, so that the buffering is
> handled by the C standard library.  The current "let's do our own
> buffering" implementation is of historical nature and may not have any
> raison d'être left.

I remember we already discussed this. It would definitely be nice to
have the buffering done in C, also because currently printing from C
code does not behave well.

Could that perhaps be a topic for an (outreachy) intern? @gasche?

**Comment by xavierleroy** [comment]
> Since there is no simple and full solution, I would suggest the following steps: [...]

I think we can go a little further by just ignoring the cached file position (field `offset` of `struct channel`) if the channel is opened in text mode, and always call lseek.  This should fix `{in,out}_channel_length` and give a clear behavior for `seek_{in,out}` (seeking to absolute positions in the underlying file, before eol conversion). 

`pos_in` remains broken.  We could raise an exception if the channel is in text mode, or just document the issue.

`pos_out` could be fixed by flushing then asking for the absolute position in the file using lseek.  Not sure we want to go that far.

**Comment by xavierleroy** [comment]
Concerning the stdio-based reimplementation: there are dragons, esp. with signal handling, also with Windows sockets.  I wouldn't give this as an intership topic.

**Comment by alainfrisch** [comment]
> pos_in remains broken. We could raise an exception

Returning an approximate position (with the appropriate disclaimer in the doc) could be useful, e.g. to report a progress indicator while scanning a text file (it will just converge to something like 96% rather than 100%, but that's ok).
