### ISSUE TITLE
RISC-V code generator: inconsistent use of register t0

### ISSUE THREAD

**Issue by xavierleroy** [ocaml/ocaml#9888]
Register `t0` is allocatable, yet it is not properly tracked by the GC:
https://github.com/ocaml/ocaml/blob/trunk/runtime/riscv.S#L72-L94
`t0` is not saved and restored to/from the `caml_gc_regs` array.  If a pointer to the heap is allocated in `t0` and is live across an allocation point, something wrong will happen at GC time.

On the other hand, according to some comments, `t0` should not be allocated as it is intended to be used as a temporary:
https://github.com/ocaml/ocaml/blob/trunk/asmcomp/riscv/proc.ml#L58-L59

Please clarify the intended use of `t0`.

**Comment by xavierleroy** [comment]
Pinging @nojb .

**Comment by nojb** [comment]
Thanks for the ping. As far as I remember `t0` should not be allocatable, but there were some register assignment changes when the PR was merged, so maybe things got mixed up at that point. Will take a look.

**Comment by nojb** [comment]
Indeed the change in use of `t0` was done in the original PR, commit https://github.com/ocaml/ocaml/pull/9441/commits/7b6ac9dd1cec24e067fb64f0317d1badfee1bd2e. The discussion starts at https://github.com/ocaml/ocaml/pull/9441#discussion_r407177621.

It seems that `t0` indeed can be used for the register allocator, but I forgot to update the assembly stubs to spill it to `caml_gc_regs` (and update the comment that says that it should not be used by the register allocator).

**Comment by nojb** [comment]
Also, there is an unrelated typo https://github.com/ocaml/ocaml/blob/961aaf5d1c6ff91cff6b06eb41bc0bb4f2857abd/runtime/riscv.S#L114-L115

PR incoming.
