### ISSUE TITLE
Out-of-date example in "Implementing primitives"

### ISSUE THREAD

**Issue by dra27** [ocaml/ocaml#9897]
The example of the `input` primitive in the Interfacing with C chapter of the manual is out-of-date: the primitive is now called `caml_ml_input` and it's much more complicated than when the example was written! 

`caml_ml_seek_in` is a closer example to the point the paragraph is trying to make.

**Comment by xavierleroy** [comment]
Closing #9897 via  #9977 (if I'm not mistaken).
