### ISSUE TITLE
Bad error message when attempting to cast objects

### ISSUE THREAD

**Issue by bruce-ricard** [ocaml/ocaml#9953]
Using these 2 classes and objects:

```
class a =
object(self : 'a)
  method equals (y : 'a) =
    true
end

class b (x : int) =
object(self : 'a)
  inherit a as super
  method m = x
end

let a = new a
let b = new b 3

```

When I try to cast a to b, I get the expected error:

> let x = (a :> b)
             ^^^^^^^^
Error: Type a = < equals : a -> bool > is not a subtype of
         b = < equals : b -> bool; m : int >
       The first object type has no method m

But now when I try to cast b to a:

> let x = (b :> a)
             ^^^^^^^^
Error: Type b = < equals : b -> bool; m : int > is not a subtype of
         a = < equals : a -> bool >
       Type a = < equals : a -> bool > is not a subtype of
         b = < equals : b -> bool; m : int >
       The first object type has no method m

It starts well, stating that "type b is not a subtype of type a", which is why this operation is not allowed. But then it states that "type a is not a subtype of type b", which I am well aware off, and which I don't care about. And it continues by stating that "The first object type has no method m", which is again true, but I again don't care about.

I was using Ocaml 4.11.0. I also tried with Ocaml 4.02.3, and I got the same result except for the message not mentioning the method `m`.

I tried reproducing this error with more "normal" classes, but I wasn't able to get the double "is not a subtype of" without using the contravariant method example.

**Comment by gasche** [comment]
If you want `b -> bool` to be a subtype of `a -> bool`, then `a` must be a subtype of `b`. This is precisely contravariance. There is no bug here. The checker could give some information on contravariance to explain the issue to the user, but it is unclear that a longer error message would be better in general.

**Comment by bruce-ricard** [comment]
I am sorry but I believe you did not read my message properly @gasche . I even explain in my message that I am aware that b is not a subtype of a. 

What I am saying is that when I try to cast b to a, the compiler tells me that **a** is not a subtype of **b**, instead of only telling me only that **b** is not a subtype of **a**. 

If you believe this is not a bug, then you should consider adding a couple more true assertions for the user, like:
> bool is not a subtype of int
> 1 + 1 is not equal to 5
> the sun is not a planet

I could go on but I think I've made my point :)

**Comment by lthls** [comment]
The problem is that both your `a` and `b` types contain occurrences of themselves in contravariant position (in the type of the method `equals`).
So for `b` to be a subtype of `a`, you need `b -> bool` to be a subtype of `a -> bool`, which in turn needs `a` to be a subtype of `b`.
This is why you get the second error message, and why your example can't work.
Imagine you have `b = < equals : int -> bool; m : int >` and `a = <equals : float -> bool >`.
The error message you would get when trying to convert from `b` to `a` would be:
```
Error: Type b = < equals : int -> bool; m : int > is not a subtype of
a = < equals : float -> bool >
Type float is not a subtype of type int
```
In your example this gets confusing because of the recursion, but that's still the expected result.

**Comment by gasche** [comment]
> I could go on but I think I've made my point :)

The point being that you are rude. I'm sorry my explanation was unclear (it's hard to say things that are intuitive with a fairly abstract, synthetic example), but the sun is not a planet.

**Comment by bruce-ricard** [comment]
OK I think that I did misunderstand your message actually. Both your message and the error message. 
The error message is saying that in order for this cast to be valid, `b` needs to be a subtype of `a` and because of the `equals` method, `a` hence needs to be a subtype of `b`.

Now that I think about it I guess it's pretty common Ocaml type error messaging
> type x is invalid 
> (because) type y is invalid
> (because) method m is not present

I guess the word "because" in this particular context would have helped a lot.

Thanks for your reply. 

EDIT: somehow my github didn't show me the new messages before I sent this one. Thank you for your explanation @lthls , I think that I was trying to explain the exact same thing as what you did.

**Comment by bruce-ricard** [comment]
> The point being that you are rude.

I'm sorry you took it this way. I was trying to be playfully sarcastic and pedagogic, using a comparaison to explain what I was thinking at the time. And it's a [quote](https://the-big-bang-theory.com/quotes/quote/8219/#quote_8219:~:text=.%20I%20could%20go%20on%2C%20but%20I%20think%20I've%20made%20my%20point.).
> I'm sorry my explanation was unclear (it's hard to say things that are intuitive with a fairly abstract, synthetic example),

It is also very hard to explain things you understand very well. This is why I value the open source community (and fresh pairs of eyes in general). I learned something from your explanation, because you have expertise on the topic (and I thank you for it). I also think that you learned something from me, which is that when you are not an expert these error messages can be confusing. 

> the sun is not a planet

I know that. Aren't my 3 assertions true? I'm confused.
