### ISSUE TITLE
ocamllex cannot handle large regexes (with small minimal automaton)

### ISSUE THREAD

**Issue by andreasabel** [ocaml/ocaml#9964]
[BNFC](https://github.com/bnfc/BNFC) is a tool to generate parsers from a LBNF file, e.g. producing input for `ocamllex` and `ocamlyacc`/`menhir`.
Here is a toy LBNF file:
```lbnf
EInt.  Exp ::= Integer;
EPlus. Exp ::= Exp "+" Integer;

comment "anananas" "anananas";
```
This specifies a grammar for +-expressions.  Further, block comments are begun and ended by the string `anananas`.

BNFC-2.8.4 (current master) generates a large regular expression
[Lex.mll.txt](https://github.com/ocaml/ocaml/files/5348368/Lex.mll.txt)
that ocamllex cannot process (bnfc/BNFC#202):
```
$ ocamllex Lex.mll
1548 states, 169242 transitions, table size 686256 bytes
transition table overflow, automaton is too big
```
However, Haskell's lexer generator Alex can handle such large regular expressions (munches a while on them).

Shouldn't it be possible to optimize the produced automaton?  In the end, the minimal automata (both deterministic and non-deterministic) for recognizing `anananas` are rather small.

There might also be a better way to recognize block comments, via lexer states, not going through regular expressions. I'd be happy for advice.

**Comment by xavierleroy** [comment]
By default, `ocamllex` generates tables for a table-driven automaton, and indices into the tables are 16-bit integers, so 169242 transitions cannot be addressed.  "64k transitions ought to be enough for anybody."  

You could try `ocamllex -ml`, which generates the automaton as recursive OCaml functions instead.  But you'll end up with 1548 mutually-recursive functions which could cause `ocamlc` and especially `ocamlopt` to overflow the stack or take forever to compile.

The usual way to handle  block comments is via lexer states indeed.  Something like
```
rule main = parse
| "anananas"  { comment lexbuf }
| ...

and comment = parse
| "anananas"  { main lexbuf }
| eof  { raise (Error "unterminated  comment") }
| _ { comment lexbuf }
```
That's extremely efficient and can even handle nested block comments shall your language support them.

Concerning automaton compression, that's something we could attempt indeed.  In the general case, ocamllex automata are DFAs with "memories", to handle named groups (`regexp as var`), and I'm not sure how to minimize these.  In your particular example, there are no named groups so standard DFA minimization applies.

**Comment by andreasabel** [comment]
Thanks for your quick reaction, Xavier! 
Looks like I should try to modify the BNFC Ocaml backend to use lexer states.
The rest (DFA minimization in the absence of named groups) is then maybe more of academic interest...

**Comment by xavierleroy** [comment]
I'll take the liberty to close this PR.  It's objectively better to keep the automaton small by using lexer states.  Please holler if you disagree.

**Comment by andreasabel** [comment]
Well, this is of course your decision!  I raised the issue to alert of a problem, but workarounds exist, so this is entirely optional...

I must confess that I haven't changed BNFC yet, hoping for a miracle upstream, but I also haven't gotten any user complaints.  So the issue might be just academic for now.
