### ISSUE TITLE
Compiling 4.11.1 as well as trunk is failing on FreeBSD.

### ISSUE THREAD

**Issue by breakone9r** [ocaml/ocaml#9969]
I've managed to track much of it down. It appears to be an assembly issue. I have attempted to compile it all variations of the following compilers, linkers, and assemblers: gcc-9.3.0, clang-11.0.0, as and ld from binutils 2.33.1, clang's internal as and ld.

I managed to figure out, from an included patch to get 4.05 compiled on FreeBSD, that the file: `runtime/amd64.S` needs the following changes: 
```#elif defined(SYS_mingw64) || defined(SYS_cygwin)
         .section .rdata,"dr"
 #else
-        .section    .rodata.cst8,"a",@progbits
+        .section    .rodata.cst8,"aM",@progbits,8
 #endif
         .globl  G(caml_negf_mask)
         .align  SIXTEEN_ALIGN
```

But after making them, I'm getting the exact same error, in a different place, and these files appear to be generated at compile time, and I cannot figure out where or how.

```tmp/camlasmf76fdb.s:2:2: error: changed section flags for .rodata.cst8, expected: 0x12
        .section .rodata.cst8,"a",@progbits
        ^
/tmp/camlasmf76fdb.s:2:2: error: changed section entsize for .rodata.cst8, expected: 8
        .section .rodata.cst8,"a",@progbits
        ^
File "/usr/home/break19/ocaml/stdlib/camlinternalAtomic.ml", line 1:```

**Comment by nojb** [comment]
`grep` is your friend in these cases. Grepping for `"a"` shows that the same code is emitted in the assembly generated for each compiled module, here:
https://github.com/ocaml/ocaml/blob/d910c3530180669c505a3350415edea96d1a407a/asmcomp/amd64/emit.mlp#L959
and here
https://github.com/ocaml/ocaml/blob/d910c3530180669c505a3350415edea96d1a407a/asmcomp/amd64/emit.mlp#L985

**Comment by xavierleroy** [comment]
Which version of FreeBSD?  We do CI on FreeBSD 12.1, which is the latest stable release if I'm not mistaken, and everything works fine.

**Comment by xavierleroy** [comment]
On the CI machine, `cc` is `FreeBSD clang version 8.0.1` and generates `.section .rodata,"a",@progbits` for constant data.

**Comment by breakone9r** [comment]
> `grep` is your friend in these cases. Grepping for `"a"` shows that the same code is emitted in the assembly generated for each compiled module, here:
> https://github.com/ocaml/ocaml/blob/d910c3530180669c505a3350415edea96d1a407a/asmcomp/amd64/emit.mlp#L959
> and here
> https://github.com/ocaml/ocaml/blob/d910c3530180669c505a3350415edea96d1a407a/asmcomp/amd64/emit.mlp#L985

Well. I saw that, but I d one know assembly enough to know if changing it here would even do anything, tbh. Ty.

**Comment by breakone9r** [comment]
> Which version of FreeBSD? We do CI on FreeBSD 12.1, which is the latest stable release if I'm not mistaken, and everything works fine.

Interesting. I just spun up a 12.1 VM and opam switch'd to 4.11.1 and everything went fine. Now I have to wonder what has changed between 12.1 and 13 on freebsd's end, as they kinda pride themselves on not breaking things in such a manner.....

I guess we can consider it closed at this point.

**Comment by gasche** [comment]
This appears to have been a pre-duplicate of #9981, which proposes a patch due to the same issue, and explains that the issue only shows up with Clang 11.0.0 -- I guess this explains why only newer versions of FreeBSD are breaking.
