### ISSUE TITLE
Reference equality behaves differently in bytecode vs native code

### ISSUE THREAD

**Issue by Vighnesh-V** [ocaml/ocaml#9972]
The following code:
```
let test () : bool = [1;2;3] == [1;2;3]
;; print_endline @@ Bool.to_string (test())
```

prints `true` if the executable is a `.native` and `false` is the executable is a `.byte`.

I expected the latter behaviour (the lists would have been Heap allocated in two different chunks), but it seems like `.native` targets do some fancy optimizations that causes this behaviour to be different.

For context, I compiled on both `4.09.0` and `4.10.0` with the command `ocamlbuild *.native` and `ocamlbuild *.byte` respectively.

Trying to get some insight into if this is expected behaviour and if so, why?

**Comment by gasche** [comment]
Yes, it is expected: it is implementation-defined what the equality does on structurally-equal immutable structures, it is valid to either share them or not. Different compilers, or different versions of the same compiler, could behave differently here.
