### ISSUE TITLE
Empty variants do not count as immediate

### ISSUE THREAD

**Issue by aalekseyev** [ocaml/ocaml#9975]
The following error message seems strange:
```
# type t = | [@@immediate];;
Error: Types marked with the immediate attribute must be non-pointer types
       like int or bool.
```
I would expect an empty type to count as immediate because all values of that type are (vacuously) immediate.
If it's in fact not safe to treat it as immediate, the error message can be improved.

**Comment by nojb** [comment]
Reopening as this has not yet been submitted upstream.
