### ISSUE TITLE
Refine types for catch-all patterns in matches on polymorphic variants

### ISSUE THREAD

**Issue by tbrugere** [ocaml/ocaml#9993]
Hi, 
this is my first time opening an issue,  so please be lenient if it I made an error, thank you !

I have a suggestion on the type-checking behaviour : basically, when type-checking a match statement on polymorphic variants, the typechecker could use the previous clauses could be used to refine the type of the pattern.  (I have no idea of difficult to implement this is though)
For example, with a 
```
match x with 
| `A -> do_something ()
|  y   -> do_something_else y  (* we know here y is not `A, so the typechecker could give a subtype of type(x) to y*)
```

Let’s give an example : 
Let’s say I want to define
`` f : [`A | `B | `C ] -> [`A | `B] ``
So that (for example) : `` `C`` is mapped to `` `A ``, and all other values are mapped to themselves
In OCaml, I would like  to write :

```
let f (x : [`A | `B | `C]) : [`A | `B] = match x with
| `C -> `A
|  y -> y
;;
```
But that returns an error
```
Line 3, characters 7-8:
Error: This expression has type [ `A | `B | `C ]
       but an expression was expected of type [ `A | `B ]
       The second variant type does not allow tag(s) `C
```
While it could actually guess that y actually matches the type `` [`A | `B] ``

It works if I write the following (semantically equivalent)  code : 
```
let f (x : [`A | `B | `C]) : [`A | `B] = match x with
| `C -> `A
| (`A | `B) as y -> y
;;
val f : [ `A | `B | `C ] -> [ `A | `B ] = <fun>
```

Thank you for reading this !

**Comment by nojb** [comment]
Note that to make your "semantically equivalent" code more convenient to write, type definitions can be used as abbreviations for or-patterns:
```
type y = [`A | `B]
type x = [y | `C]
let f : x -> y = function
| `C -> `A
| #y as y -> y
```
